### ISSUE TITLE
Bidi text model doesn't take into account wrapped lines

### ISSUE THREAD

**Issue by twiss** [codemirror/CodeMirror#1757]
(Tested everywhere)
- Again, go to http://codemirror.net/demo/bidi.html or http://codemirror.net/demo/indentwrap.html
- Shrink the window until the rtl text on line 6 wraps
- Click inside `<dd>` and move right

Both in chrome and firefox on linux, in a textarea in this case the cursor never jumps (just like on a non-wrapped line), but in CodeMirror with `rtlMoveVisually` set to true, the cursor moves to the lower part of the rtl text first. I don't know "how wrong" this would seem to a speaker of a rtl language, though.

**Comment by adrianheine** [comment]
This should be fixed in master since #4463 got merged.

**Comment by marijnh** [comment]
*Applause.* Thanks for taking care of this!
