### ISSUE TITLE
Unable to position cursor after a hyphen in word-wrapped, hyphenated text.

### ISSUE THREAD

**Issue by bchintx** [codemirror/CodeMirror#1862]
Unable to position cursor after a hyphen in word-wrapped, hyphenated text.

Steps to Reproduce:
1. In Chrome Browser, go to: http://codemirror.net/demo/indentwrap.html
2. Replace the existing text in the editor with: `Cernantur quorum dolor ut fugiat, non in dolore nostrud, anim minim veniam eernantur–coniunctione enim coniunctione.`
3. Resize the editor width so that the hyphen is close to the right edge of the editor window and the "coniunctione" part of the word shows up on the next line: ![hyphen-cursor-problem](https://f.cloud.github.com/assets/1774931/1051093/98c67b3e-10c4-11e3-9c72-78e7ef2dd68a.PNG)
4. Click the mouse cursor in the space at the end of the 1st line of text, specifically to the right of "eernantur-".

Result: The editor will position the cursor to the **left** of the hyphen, rather than to the **right**.  Even using the arrow keys, you can only be positioned to the left of the hyphen or at the beginning of the next line.

Other text editors, such as Notepad and the Visual Studio editor allow the cursor to be positioned of the right of the hyphen.

**Comment by jackycute** [comment]
Hi, I found this problem too.
And it's not only happen in hyphenated text but also in a very long text on wrap mode.
Then, we can't click to move the cursor to the end of wrap line, or even select to it.
![2015-05-25 12 30 43](https://cloud.githubusercontent.com/assets/2639151/7791844/288649b2-02da-11e5-9410-31402d666471.png)
Also found related issue in brackets, but seems they made some work arounds.
https://github.com/adobe/brackets/issues/5408

**Comment by akkatracker** [comment]
Does anyone know if this is going to be fixed?

**Comment by squirrelyscoutz** [comment]
I discovered an acceptable workaround
When the cursor is above the problem line (in my case line 31) and I hit enter twice the line then becomes available for me to interact with (moving my code to line 33). I can update my code as needed then delete the two extra spaces (returning to line 31) and move on as expected.

**Comment by doughballs** [comment]
Hi...I was having the same issue and fixed it by taking my zoom back to 100%. Some of the exercises recommend that you to zoom out to see the full page. I was at 80% zoom and having issues with the cursor, when I zoomed in to 100% the issue went away. Purely observational but it has cropped up again on further exercises and has been fixed the same way.

**Comment by Sarseth** [comment]
Newest Chrome here, 100% zoom, no weird plugins. Happens every time when I go to another challange and try to write on page for first time. Everytime. Have to click false "ENTER" then ctrl+z to work normally.

**Comment by HamerWV** [comment]
It is March 25, having the same problem.  Windows 10 and Chrome.  Have not figured out a way to stop it from happening.  Just annoying.

**Comment by sogen** [comment]
+1
