### ISSUE TITLE
Add support for alternative comment syntaxes in Clojure and Clojurescript

### ISSUE THREAD

**Issue by chrisfjones** [codemirror/CodeMirror#1896]
In Clojure and Clojurescript:
Codemirror currently supports line comments:
```clojure
; line comment
```

... but not the comment macro
```clojure
(comment
  (println "this is a comment macro example"))
```

... nor the form comment reader macro
```clojure
#_ (do
     (println "this is a comment reader macro example"))
```

**Comment by marijnh** [comment]
I'm going to close this. Patches welcome, but it doesn't seem all that critical.
