### ISSUE TITLE
Indentation Bug in .sass Mode

### ISSUE THREAD

**Issue by chriscoyier** [codemirror/CodeMirror#2156]
http://codemirror.net/mode/sass/index.html

type like:

```
div
  color: red
```

{return}

you'll be indented +2 more spaces instead of remaining along the current indentation level.

**Comment by marijnh** [comment]
> But, highly nested nature of SCSS and lack of braces in SCSS makes it impossible for even a human to determine the correct point of dedent

You're right. I initially thought the Python mode gets this right, but it doesn't either, except when there is a `return` or `pass` statement at the end of the block.

**Comment by marijnh** [comment]
(Can this be closed now that your pull request was merged?)

**Comment by ankitstarski** [comment]
Yes!
