### ISSUE TITLE
Android Chrome Backspace and Enter do not fire keydown events

### ISSUE THREAD

**Issue by ZombieHippie** [codemirror/CodeMirror#2234]
The only way Backspace works is when your `.CodeMirror textarea:focus` has a *non-empty* value and it still doesn't fire a `keypress` event it fires an `input` event.

So when you begin typing, CodeMirror shows your current typing from the textarea (textarea has value), allowing you to back space. But once the `<textarea>.value` is empty you can't make any backspaces because no events are fired. Whenever you move your cursor to another location, the text area is reset: `value=""`

Is there any way that the textarea can hold a portion of the document where ever your cursor is or is re-located? Or are there any tips on how this can be done efficiently?

This applies to v3 and v4

**Comment by marijnh** [comment]
This problem is solved for Chrome in the current mobile code. (Though Firefox Android still has a similar issue - #3102)

**Comment by ZombieHippie** [comment]
Awesome! Thanks!
