### ISSUE TITLE
Char Measurement Bug in v4 on Mobile Safari

### ISSUE THREAD

**Issue by fe9lix** [codemirror/CodeMirror#2414]
Hi,

there seems to be a bug with chars being incorrectly measured when zooming a page containing a CodeMirror v4 instance on Mobile Safari (latest iOS 7.1 version), v3.23 works fine. After zooming the viewport, calls to the method coordsChar() always return 0 for ch-positions (line positions seem to be correct, though). When the page is not zoomed, correct line and ch values are returned. With v3.23, both zoomed and unzoomed pages work.

I've created a simple example to demonstrate the problem: 
http://jsbin.com/baqeqeso/1

If you open the page in Safari, zoom on the button and click the button, it reports line:1, ch:0. The expected result is line:1, ch:9, which is correctly displayed when the page is not zoomed.

Any ideas?

**Comment by marijnh** [comment]
I am not able to reproduce this with current CodeMirror and iOS 8's Safari
