### ISSUE TITLE
Selections in v4 not correctly updated when viewport is zoomed

### ISSUE THREAD

**Issue by fe9lix** [codemirror/CodeMirror#2417]
I guess this bug is closely related to #2414 (char measurement): When the editor has an active selection and the viewport is zoomed (tested on Mobile Safari, iOS 7.1), the active selection is not correctly updated after a call to refresh(). CodeMirror reports the correct selection range (listSelections()) but displays the wrong chars as selected. I've updated the example for #2414 to demonstrate the bug: 

http://jsbin.com/baqeqeso/2

When you zoom in, hit the button, the previously selected range is now displayed differently.

**Comment by marijnh** [comment]
Since the selection is now shown as a native selection on mobile, I guess this no longer exists.
