### ISSUE TITLE
Suggested fix for mobile zooming/scrolling issues

### ISSUE THREAD

**Issue by fe9lix** [codemirror/CodeMirror#2419]
Hi Marijn,

I've reported two bugs (#2414, #2417 - actually it's one) related to incorrect measuring of characters on mobile devices. The problem not only occurrs when zooming but more generally when the browser viewport is horizontally scrolled. I tried to locate the part where the incorrect measuring happens and it seems to be the call to getBoundingClientRect() in measureCharPrepared(). On iOS, this returns a wrong rectangle when the browser viewport has a pageXOffset > 0 (i.e. is horizontally zoomed/scrolled): The properties "right" and "width" contain their values plus the pageXOffset. This leads to the wrong calculation of the char width later since the pageXOffset is *not* added to the property "left".

I could fix the problem by adding the following lines to the end of measureCharInner() (currently after line 1626):
```
if (ios) {
    var xOff = pageScrollX();
    if (xOff > 0) {
      result.left -= xOff;
      result.right -= xOff;
    }
}
```
This fixes everything on iOS 7.1 (tested on iPad and iPhone). I've also tested on an Android 4.1.2 phone but - at least the Android browser - does not show the described issue.

My questions are:

- Can you think of a better solution than the above fix? I'm not sure if you can test on iOS to reproduce the issue? 

- Is this the right method/line to add the fix? Since much of the other code related to positioning seems to depend on the char measurement in measureCharInner(), I hope that this completely solves the issue on iOS (it seems so in my tests).

**Comment by marijnh** [comment]
Timing this out until I get further reports.
