### ISSUE TITLE
Suggestion: Visible cursor on dragover

### ISSUE THREAD

**Issue by CareyJWilliams** [codemirror/CodeMirror#2645]
Not a bug or even a request really, just an offhand suggestion I thought of whilst implementing similar functionality for myself.
I think it would be nice if when you are dragging and dropping blocks of text into a CodeMirror instance, that the cursor was visible and moved with your mouse position so that you could pinpoint the drop location with more accuracy. 

Running the following code in the console of one of the demo pages (in Chrome) will give you an idea of what I mean (though the code in itself isn't enough/wouldn't work to implement it (as it seems to break internal drops for a start)). 

    editor.on("dragover", function(cm, e) {
	    document.getElementsByClassName("CodeMirror-cursors")[0].style.visibility = "visible";
        var cursors = document.getElementsByClassName("CodeMirror-cursor");
        for (var i = 0; i < cursors.length; i++) {
           cursors[i].style.visibility = "visible";
        }
        var xy = {"left": e.x, "top": e.y};
	    var newPos = editor.coordsChar(xy);
	    editor.setCursor(newPos);
    });

**Comment by peterflynn** [comment]
Fwiw, +1... this is one of the [few missing pieces](https://trello.com/c/io24Byhm/910-drag-and-drop-to-move-selected-text-within-editor) that makes me a little hesitant to have drag & drop turned on by default in Brackets, since it's very hard to get the insertion location right without it.

**Comment by marijnh** [comment]
Set up a ~500€ bountysource.com bounty (or allow me to invoice that sum) and I'll take care of it.
