### ISSUE TITLE
Difficult to reopen screen keyboard on Android

### ISSUE THREAD

**Issue by Rosbicn** [codemirror/CodeMirror#2764]
On Android, close screen keyboard, it is difficult to reopen it in CodeMirror area. I tried so many times, found a workarround. Tap some area outside the CodeMirror editor, then tap the CodeMirror area again, screen keyboard come back. I hope to bring back screen keyboard by tapping the CodeMirror area twice. Or some better actions. Thanks a lot.

**Comment by marijnh** [comment]
Should be fixed now that the mobile/contenteditable code landed.
