### ISSUE TITLE
[vim] :substitute can't find $ (EOL)

### ISSUE THREAD

**Issue by dbarnett** [codemirror/CodeMirror#2806]
In vim, I can append to the end of each line with `:%s/$/SOMETHING/`. In CodeMirror, I see `No matches for $` instead.

Users should be able to represent end-of-line in `:substitute` commands using `$`.

**Comment by marijnh** [comment]
Due to limitations in JavaScript's regexp API, the searchcursor addon isn't able to properly match all expressions. We could special-case this situation, but I'm not sure if it's worth it.

**Comment by heppe** [comment]
this one can be closed (IIUC I'd need to have the right permissions to be able to do it myself)

**Comment by marijnh** [comment]
Thanks!
