### ISSUE TITLE
Copying a whole blank line clears previously copied content

### ISSUE THREAD

**Issue by le717** [codemirror/CodeMirror#2824]
Originally reported at adobe/brackets#9311.

---

Steps to reproduce:
* Type then select some text and copy it
* Paste it on a new line, note how the content is pasted
* Use the whole line copy feature to copy a blank line
* Paste, a blank line is pasted
* Expected: the blank line is not copied, and instead our previous content is pasted instead

I've traced this to f4ae5b42c929edc78c2df0888ae1b0179098652a (#2697). It appears the `d.input.value = lastCopied.join("\n");` and `d.input.value = text.join("\n");` lines are the culprits, but I am not totally sure on that. Disabling them also remedies some issues I found in adobe/brackets#9130.

I am not sure what CodeMirror demo I can use to reproduce this in, but the expected behavior can be seen in Brackets 0.38, and the bug in Brackets 0.42+.

**Comment by marijnh** [comment]
Closing this. @peterflynn If you can tell me more about the way 'pasting over' blank lines should work, please open a new issue.
