### ISSUE TITLE
Script error in internet explorer

### ISSUE THREAD

**Issue by ADangl** [codemirror/CodeMirror#2833]
We recommend to change line 541 in codemirror.js.
Before:
    return display.scroller.getBoundingClientRect().left - display.sizer.getBoundingClientRect().left;
After:
    try {
      return display.scroller.getBoundingClientRect().left - display.sizer.getBoundingClientRect().left;
    }
    catch (e) { return 0 }
This prevents a script error in Internet Explorer (tested with 9/10/11) when the editor is destroyed immediately after it has been loaded.

**Comment by Vadorequest** [comment]
Is there any workaround for this?
We are running into the same issue on IE11.
https://cloud.githubusercontent.com/assets/14806310/18201769/492a88f8-710c-11e6-88f9-47402b34eb0f.png

**Comment by marijnh** [comment]
A good start would be providing a way for me to reproduce it (in a minimal, stand-alone HTML page, not somewhere deep inside some bigger system!)

**Comment by dobos** [comment]
I'm getting the same error when using a codemirror form inside an asp.net UpdatePanel. I need to resize the codemirror panel when the (partial) page is loaded, so I register an ajax event:

var prm = Sys.WebForms.PageRequestManager.getInstance();
        prm.add_pageLoaded(Function.createDelegate(this, this.init));

And the init function looks like this:

this._codeMirror.setSize(this._width, this._height);

_width and _height are both 100%

I'll try to strip the page down to minimum but it's unlikely I'll have time to create a stand-alone reproduction that doesn't use asp.net and update panel.
