### ISSUE TITLE
Closing braces dont dedent in perl

### ISSUE THREAD

**Issue by Naatan** [codemirror/CodeMirror#2870]
If I type something like:
```
    for (my $i = 0; $i < 10; $i++) {
        print "$i\n";
    }
```
The end brace actually winds up at the same indent as the print statement. Hitting Shift-Tab doesn't force a dedent, and the only way I've found to dedent is to just erase the spaces in front of the end brace. Mildly annoying at one level of indent, but two or three would be worse.

**Comment by marijnh** [comment]
Going to close this as 'too bad, but I'm not going to work on adding this feature'
