### ISSUE TITLE
Smartymixed mode needs to be within a html tag

### ISSUE THREAD

**Issue by znap026** [codemirror/CodeMirror#2871]
![brokensmartymixed](https://cloud.githubusercontent.com/assets/2813146/4645208/0fee6a42-5466-11e4-95e8-70cfd477bda1.png)

In smarty mixed mode the layout breaks if there is smarty code within a html tag and that tag is not contained within another. As in the image its fine if there is an opening div but if that is closed or removed the highlighting breaks. It can be seen in the example on codemirror http://codemirror.net/mode/smartymixed/

just remove the <html> tag.

**Comment by marijnh** [comment]
Attached patches extend the Smarty mode to support a base (background) mode, and kill the Smartymixed mode.
