### ISSUE TITLE
Horizontal bar doesn't appear when tabbing past the boundary of code mirror

### ISSUE THREAD

**Issue by cdchambers** [codemirror/CodeMirror#2901]
Repro steps:
1. Use the demo on http://codemirror.net/
2. Place the cursor at the end of any line and tab till you reach the right-hand boundary of the editor. 
3. Tab again

Expected: the horizontal scroll bar appears 
Actual: code mirror moves the cursor to the beginning of the line and increases the size of the cursor.

Note: this problem doesn't occur if there is text behind the cursor when you tab.

**Comment by jochenberger** [comment]
I just encountered that issue. Unfortunately the workaround does not work if the `.cm-tab` is wrapped inside other spans. For example, I have the following structure:
```html
...
<span class="cm-punctuation">
  <span class="cm-tab" role="presentation" cm-text="	">   </span>
  <span class="cm-tab" role="presentation" cm-text="	">    </span>
</span>
```
Maybe the workaround should check the last child that has text content.

**Comment by marijnh** [comment]
Wow, they still didn't fix this. Oh well, attached patch seems to solve the problem.
