### ISSUE TITLE
LaTeX code displays as italic between underscores in Markdown mode

### ISSUE THREAD

**Issue by benrbray** [codemirror/CodeMirror#2942]
This is a very minor nuisance I have noticed while editing markdown cells in IPython Notebooks.  The problem appears to also persist on the [MarkDown Demo](http://codemirror.net/mode/markdown/index.html) on CodeMirror's site.  

In Markdown, underscores toggle italics, but in LaTeX they also serve to indicate subscripts.  Unfortunately, while editing with CodeMirror, underscores used in LaTeX mode sometimes cause italics to be toggled in the edit view.

Steps to reproduce:
1) Start editing a markdown cell.
2) Type the following:  $$a_{n+1} = 2a_{n} + b$$
3) The text will display as a_***{n+1} = 2a***_{n}+b` where the characters in bold here have been italicized in the editor.

Non-example:
1) Enter the following into a Markdown cell:  $$a_n = 2a_n+b$$

It appears that italics are ignored when there is a single alphanumeric character after the underscore, but the case in which the subscript consists of a bracketed group of characters is not handled correctly.

This is particularly annoying, because in italic monospaced fonts, pipes `|` look like forward slashes `/` and backslashes `\` look like pipes `|`.

Thanks!

PS:  WIndows 7, 64-bit with Chrome, but I doubt it matters!

**Comment by carbonscott** [comment]
I solve it by manually running a vim command `syn region NoUnderscoreFormat start="_" end ="_"`, so that the content between a pair of underscore will be reformated in gvim.

**Comment by Menci** [comment]
@williamstein A bug in your solution is if I type a `$` in a inline code or code block, it'll be highlighted as TeX.

like

```js
$('#div').html();
```

See https://github.com/Moeditor/Moeditor/issues/5

Maybe we can find a way to set the "priority" of the marks?
