### ISSUE TITLE
setValue without focus?

### ISSUE THREAD

**Issue by pingram3541** [codemirror/CodeMirror#3010]
When passing html from a contenteditable preview element using

    editor.getDoc().setValue(previewdata);

a loss of focus on the contenteditable element occurs. This naturally interrupts the editing process.

Passing a delay timer to allow for continued keystrokes allows uninterrupted editing

    previewtimer = 0;
    clearTimeout (previewtimer);
    previewtimer = setTimeout( function() {
        editor.getDoc().setValue(previewdata);
    }, 3000);

but once the timer expires and the cm instance is updated, the focus on the contenteditable area is lost.

The work around for now is to update a button (or similar) to indicate the changes on the contenteditable element and then use the click event to update the cm instance.

Would be nice to setValue silently without the focus effect.

**Comment by marijnh** [comment]
You could check for the `origin` field in the change object (passed to the change handler), and ignore it when it is `"setValue"`.

**Comment by pingram3541** [comment]
Perfect!
