### ISSUE TITLE
CoffeeScript Syntax Highlighting

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3011]
(adobe/brackets#9797) (I don't know anything about CoffeeScript, I'm just cross-filing this issue)

Apparently, the CoffeeScript syntax highlight in CM is really basic. Would be cool if you could improve it.

Code:
``` coffee
app.getUrlParams = (url = location.href)->
  args = {}
  query = url.substr(url.lastIndexOf('?')+1)
  pairs = query.split("&")
  for item in pairs
    pos = item.indexOf '='
    if pos == -1 then continue
    key = item.substring 0 , pos
    value = item.substring pos + 1
    args[key] = decodeURIComponent value
  return args

app.isLogined = ->
  if appConfig.userName then return true else return false

@View =
  render : (id,datta,tmpl_id)->
    tmpl_id = if !tmpl_id then id + '-template' else tmpl_id
    tmpl = $("##{tmpl_id}").html()
    html = _.template(tmpl,data)
    $("##{id}").html html
  
  info : (selector,message,type) ->
    if type
      $(selector).show().removeClass(alertType.join(' ')).addClass("alert-#{type}").html(message)
    else
      $(selector).show().removeClass(alertType.join(' ')).html(message)
  
  hideInfo : (selector)->
    $(selector).hide()
```

CodeMirror:
![image](https://cloud.githubusercontent.com/assets/2641501/5572610/42855b20-8fa1-11e4-94bb-5f2d8f99c01e.png)

Sublime Text 3:
![image](https://cloud.githubusercontent.com/assets/2641501/5572615/4f61fa92-8fa1-11e4-82d1-534552ed106c.png)

**Comment by MarcelGerber** [comment]
Oh, I actually just noticed that variables, `->` and classes *are* actually given the correct classes, but these are all black in the default stylesheet, which makes syntax highlighting pretty much senseless.
I wonder if we should change `cm-variable` to `cm-def`, which is the class the JS mode applies for variables (but why?).

So the only issue that still exists is the missing highlight of `for ... *in*`.

**Comment by marijnh** [comment]
> I wonder if we should change cm-variable to cm-def, which is the class the JS mode applies for variables (but why?).

It only does so for variable _definitions_. (It also styles local variables as `variable-2`, which requires more precise parsing than the CoffeeScript mode does.)

**Comment by marijnh** [comment]
There were some improvements to the CoffeeScript mode recently. They solved the low-hanging fruit issues, such as property highlighting. Please open specific new issues for other problems you find.
