### ISSUE TITLE
scrollbars not hearing `mouseup`

### ISSUE THREAD

**Issue by leeoniya** [codemirror/CodeMirror#3017]
hey @marijnh,

dunno if this is just an issue with the [scrollbar demo](http://codemirror.net/demo/simplescrollbars.html), but it looks like the mouseup handler isnt firing, so the scrollbar is stuck to the cursor after dragging ends. thought it was an issue of mouseup firing outside the bar itself; was gonna suggest delegation to cm's wrapper or even document, but it looks like even when mouseup is inside the scrollbar, it doesnt fire.

EDIT: tested in FF and IE11

**Comment by marijnh** [comment]
There actually was no `mouseup` handler at all, since Webkit browsers set a sane `which` property on `mousemove` events that allows us to detect button release in a much more reliable way, but I guess other browsers don't. Fixed in attached patch.
