### ISSUE TITLE
4.10.0 badly tagged ? (still scrollbar issues, but on chrome OSX)

### ISSUE THREAD

**Issue by Carreau** [codemirror/CodeMirror#3022]
Hey Marijnh, it seem like the scrollbar fix : https://github.com/codemirror/CodeMirror/commit/198d00f80882e80e0f5cd4f4dff1249541e36ed8 for  https://github.com/codemirror/CodeMirror/issues/3009

Did not make it to the tagged version: https://github.com/codemirror/CodeMirror/blob/4.10.0/lib/codemirror.js#L778-L783 

(still named plus gap instead of total)

Which make 4.10 still have the scrollbar issue in some cases eg: https://github.com/ipython/ipython/issues/7395

Any chance to have a 4.10.1 ? 

Thanks !

**Comment by marijnh** [comment]
Yes, I found a few more problems after tagging 4.10, but wasn't sure whether they'd be major enough to warrant yet another tagged release. I guess they were. I pushed 4.11.0.

**Comment by Carreau** [comment]
I guess it was a bad start for 2015... Thanks a lot, should have reviewed beta more carefully.
