### ISSUE TITLE
Line style unexpectedly carried over to new value, expected it to be cleared

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/CodeMirror#3023]
Summary:
Seen in @9ee2cef. When setting a new value in a CodeMirror editor, I expected it to wipe out all of the line styles in lines it replaced. However, it ended up with an unexpected style at the end, at an empty line.

Test case:

```html
<script src="codemirror.js"></script>
<link rel="stylesheet" href="codemirror.css">

<style>.CodeMirror .lineclass .CodeMirror-linenumber { color: red; }</style>
<textarea id="code1"></textarea>

<script>
var cm1 = CodeMirror.fromTextArea(document.getElementById('code1'), {lineNumbers: true});
cm1.addLineClass(0, "wrap", "lineclass");
// NOTE: Without a trailing newline at the end, this works as expected!
var content = "a\nb\nc\nd\ne\nf\ng" + "\n";
cm1.setValue(content);
</script>
```

Actual results: Unexpected line styles on line 8.

![actual](https://cloud.githubusercontent.com/assets/11351/5674971/e45961ac-9768-11e4-8dea-2fbf8b8efce3.png)

Expected results: I would expect the setValue call, which overwrote line 1 to eliminate styles.

![expected](https://cloud.githubusercontent.com/assets/11351/5674975/e987fa6c-9768-11e4-8345-f42cb0b0b542.png)

**Comment by marijnh** [comment]
That is indeed not something you'd expect. Attached patch should help.
