### ISSUE TITLE
noHScroll LineWidgets report wrong dimensions in measure div

### ISSUE THREAD

**Issue by hitsthings** [codemirror/CodeMirror#3024]
A sister issue to #2611

noHScroll means the `.CodeMirror-linewidget` element is given an explicit width equal to the viewport width of the CodeMirror editor.
However this isn't reflected in the measure div, which is `width: 100%` inside of the `.CodeMirror-lines` element. Instead, the measure div is as wide as the longest line of text in the document.

The effect of this is that `widgetHeight()` of `noHScroll` `LineWidget`s will be less than expected since they will be measured at a wider width than they are eventually displayed at.

Reproduction is here: http://jsbin.com/levahexoli/2/edit?html,js,console,output

**Comment by marijnh** [comment]
Thanks for noticing that! Attached patch should take care of it.

**Comment by hitsthings** [comment]
Awesome. Thanks for fixing it!
