### ISSUE TITLE
Tagged template literals

### ISSUE THREAD

**Issue by ForbesLindesay** [codemirror/CodeMirror#3026]
I'd like an easy way to contribute plugins for the JavaScript mode to add special overlays for specific tagged template literals.  Currently I have [this code](https://github.com/ForbesLindesay/jade-brackets/blob/master/lib/overlay.js) which attempts to add the overlay via some horrible hacks so that something like:

```js
var template = jade`
h1 The Jade Language
p Jade is an awesome language
`;
```

gets syntax highlighted as JavaScript with a section of jade in it.

**Comment by marijnh** [comment]
You definitely don't want to monkey-patch `getMode`. Rather, it'd be possible to define a `javascriptmixed` mode which wraps the `javascript` mode much like `htmlmixed` wraps `xml`, and switches to an inner mode when specific (configurable) types of tagged templates are encountered.

**Comment by ForbesLindesay** [comment]
That sounds like a good approach, we could then request brackets move to javascriptmixed as the default JavaScript mode.

**Comment by leeoniya** [comment]
+1 for a `javascriptmixed` and also for re-opening this issue.

embedding html and other template languages in js is getting pretty common as libraries move away from pure vdom-building to faster strategies that diff only dynamic parts of templates. would be cool to get html highlighting in Codemirror for libs like `t7` [1] and also enable JSX [2].

[1] https://github.com/trueadm/t7
[2] https://github.com/codemirror/CodeMirror/issues/3122
