### ISSUE TITLE
Sublime Text, Command-Shift-Period tag closing

### ISSUE THREAD

**Issue by chriscoyier** [codemirror/CodeMirror#3028]
(Feel free to just close this, as it's not really a bug, just a wish.)

When writing HTML in Sublime Text Command-Shift-Period just closes the closest tag that it can find that's still open. It's probably my most-used command.

The [close-tag demo](http://codemirror.net/demo/closetag.html) is pretty cool, but it's more heavy-handed as it's automated insertion rather than on-demand insertion.

**Comment by marijnh** [comment]
Hi Chris, with the attached patch, you can bind keys to `"closeTag"` to get the behavior you describe. It was a small change to have the addon also expose a command.

**Comment by chriscoyier** [comment]
Works wonderfully, thank you so much!
