### ISSUE TITLE
Tags are not recognized after 10000th column

### ISSUE THREAD

**Issue by happibum** [codemirror/CodeMirror#3029]
For example,

```
<div>
<div>aaa...aaa</div>
</div>
```

If the number of a's is more than 9989,
the close tag on the second line is not properly recognized.

**Comment by marijnh** [comment]
CodeMirror stops tokenizing after 10k characters, for performance reasons. Adjust the `maxHighlightLength` option to change this.

**Comment by happibum** [comment]
Thank you for the pointer. I can use the option. :)

I am sorry to comment on this closed issue. 
I just found a tiny inconsistency.

The HTML syntax checker(not the highlighter) also ignores characters after 10000th column.
For example,
```
<li>
<div>aaa..aaa</div>
</li> 
```
can show error on the third line. (because of missing close div tag?)
On the other hand, it seems JavaScript syntax checker does not ignore such characters.
For example,
```
var x = "aaa..aaa"; if (x) {
} else { }
```
does not show any syntax errors.
Is it possible to make the HTML syntax checker not depend on ```maxHighlightLength```?

**Comment by marijnh** [comment]
The syntax checker is integrated with the highlighter. The basic assumption is that giant lines will be minified content that you probably don't want to hand-edit anyway.
