### ISSUE TITLE
'Go to line' command is missing in default key map

### ISSUE THREAD

**Issue by davido** [codemirror/CodeMirror#3030]
Is there any obvious way, that i am missing, to jump to a line in default key map? Something that this addon addresses: [1], [2], that makes use of interactive dialog feature?

Any reason why similar functionality is not included in CodeMirror distribution?

* [1] http://djadmin.github.io/addon/search/goto-line.js
* [2] http://djadmin.github.io/

**Comment by marijnh** [comment]
Nope, there isn't. There is no sane way to prompt for a number in the core library, so this isn't part of the core. You can write it yourself in a few lines of code, though:

```javascript
CodeMirror.commands.jumpToLine = function(cm) {
   var line = Number(prompt("Where", ""));
   if (!isNaN(line)) cm.setCursor(line, 0);
};
CodeMirror.keyMap.default["Alt-G"] = "jumpToLine";
```

(For extra points, use the dialog addon to make the prompt less ugly.)

**Comment by mihailik** [comment]
Somebody's already done it, including the bonus dialog:

http://djadmin.github.io/

Specifically the addon code:

https://github.com/djadmin/djadmin.github.io/blob/master/addon/search/goto-line.js

Looks worthy, should it be added to the CM addon tree?

**Comment by dpursehouse** [comment]
The reason we didn't add it in Gerrit is that the license is unclear.  See the commit message of @davido's commit that was referenced above.

**Comment by davido** [comment]
Indeed, @dpursehouse meant this non answered question to clarify the license: [1].

* [1] https://github.com/djadmin/djadmin.github.io/commit/6ee5941512d73cdcede929b6b832896842e0845d#diff-5

**Comment by mihailik** [comment]
OK, shell I implement it close to what @marijnh suggested, separate from @dpursehouse 's take?

* Use Alt-G as a shortcut
* Parse single number: `line`
* Parse colon-separated: `line:character` or relative to the current line `:character`
* Parse plus-minus offsets relative to the current position: `+line`, `-line`
* Parse percentages: `30%` - those take in account line counts, not character size

How does that sound?

**Comment by jenspohle** [comment]
@marijnh:

at the beginning of this thread you posted some lines of code, that shall make the "goto-line-function" work.

Well, javascript is not my strong ;-)

Can you tell me, in which files i have to place it, to make it working?

Thank you very much in advance! :-)

**Comment by djadmin** [comment]
Thanks guys for adding the `Goto line` command to CodeMirror :+1:

**Comment by marijnh** [comment]
@jenspohle It's probably easier to enable the new [addon](http://codemirror.net/doc/manual.html#addon_jump-to-line) than to paste in that code.

**Comment by xpectmore** [comment]
marijnh the correct code in my case is 

CodeMirror.commands.jumpToLine = function(cm) {
   var line = Number(prompt("Where", ""));
   if (!isNaN(line)) cm.setCursor(line-1, 0);
};
CodeMirror.keyMap.default["Alt-G"] = "jumpToLine";



"line-1"  

good job!
