### ISSUE TITLE
Sometime, Past insert extra white caracter

### ISSUE THREAD

**Issue by Carreau** [codemirror/CodeMirror#3031]
illustrated by sequence of event on front page:

Double click on a word to select:

![capture d ecran 2015-01-14 a 14 44 35](https://cloud.githubusercontent.com/assets/335567/5739648/356271dc-9bfc-11e4-9634-477634cf34ca.png)

past it in middle of first line (got whitespace) 
![capture d ecran 2015-01-14 a 14 45 21](https://cloud.githubusercontent.com/assets/335567/5739661/617d2b2c-9bfc-11e4-91ac-b3f38934d228.png)

Select by drag ; 
![capture d ecran 2015-01-14 a 14 45 29](https://cloud.githubusercontent.com/assets/335567/5739671/6ac73394-9bfc-11e4-90c2-40a33c5e41b1.png)

paste (no white space) 
![capture d ecran 2015-01-14 a 14 45 47](https://cloud.githubusercontent.com/assets/335567/5739675/74a8961e-9bfc-11e4-9c70-0244bf524f52.png)

Select by double click does not seem to insert whitespace in url bar, or javascript console.

OS X (at least 10.7 and 10.10) Chrome 40 and Safari, reported here: https://github.com/ipython/ipython/issues/7448 so might be quite old, I searched but did not found related issues.

I'm a little surprised on how this can happend though your code path, so I'm fine with closing as can't fix, I would suspect a weird clipboard interaction that try to past rich mimtype.

Thanks.

**Comment by marijnh** [comment]
Does not appear to happen on Chrome Linux, so it does seem likely to be related to OS X shenigans. My only OS X device died for good a few weeks ago, so I can't currently test this. I do intend to get another one at some point, but help in debugging this (verifying that we are indeed getting nonsense from the clipboard, and trying out workarounds) would be much appreciated.

**Comment by Carreau** [comment]
> My only OS X device died for good a few weeks ago, so I can't currently test this

Old my condolences, I would have an availlable old spare os-x laptop, I would have gladely send it to you (assuming you type on AZERTY keybord :-P ). 

I'll dig a bit.

**Comment by Carreau** [comment]
Hum, seem indeed to be osx shenigan indeead. When you past into a [web textarea](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea) but no other input field of course, osx will append space before and/or after depending on wether the character before (and/or after) is a whitespace or not, depending on how you copied it. (ie I can repoduce the bug on above linked page)

I'll dig to see if there is a flag to  set on the text area to tell OS X not to try to be smart.

**Comment by Carreau** [comment]
Webkit feature called "smart copy/paste"  seem to be a won't fix, or more precisely a "dont' really care ehencement request".

https://bugs.webkit.org/show_bug.cgi?id=29732

Should I close ?

**Comment by marijnh** [comment]
You could probably work around this by using the clipboard API in the paste event handler. Not sure if it is worth the trouble, though.

**Comment by Carreau** [comment]
Even the past event handler might get the data with space, and you won't have any way of knowing wether the sent data spaces at start or end is indeed coming from user or webkit "smartness". 

So you would displace the bug from people double-clicking-to-select-that-dont-want-space-and-have-one to people click-and-draging-to-select-that-want-space-but-dont. (IIUC)

**Comment by marijnh** [comment]
Are you sure? Does `event.clipboardData.getData` return the text including the space?

**Comment by Carreau** [comment]
Indeed you are right, seem to return the [raw text](http://jsfiddle.net/tbv32f76/). 

Maybe in wishlist once clipboard API stabilises ?

**Comment by marijnh** [comment]
I think it's pretty stable, and work in recent browsers. I didn't use it yet because the fallback needed for older browsers works just as well in modern ones, but this might be a good reason to start using it when available.

**Comment by dalguji** [comment]
Hello, would there be any updates on this issue? I am looking forward to seeing https://github.com/ipython/ipython/issues/7448 resolved, which depends on this issue.

**Comment by marijnh** [comment]
Could you see if attached patch helps?

**Comment by dalguji** [comment]
I am not quite sure. @Carreau, could you advise on this?
