### ISSUE TITLE
Lint tooltip doesn't work when editor is in shadow dom

### ISSUE THREAD

**Issue by forresto** [codemirror/CodeMirror#3039]
Specifically, [this logic](https://github.com/codemirror/CodeMirror/blob/6534d9e1aa49a47d523338d7c88a1d19fc9119b9/addon/lint/lint.js#L47-L53) always hides the lint tooltip after 400ms.

    var poll = setInterval(function() {
      if (tooltip) for (var n = node;; n = n.parentNode) {
        if (n == document.body) return;
        if (!n) { hide(); break; }
      }
      if (!tooltip) return clearInterval(poll);
    }, 400);

As the `for` loop travels up the tree, it hits the shadow dom boundary (document fragment), which doesn't have a `.parentNode`. I can make a reduced case if that helps.

It works for me commenting those lines out, but I'd like to make a fix that takes what this logic is supposed to do into account. What is it there for?

**Comment by marijnh** [comment]
This is used to automatically remove the tooltip when the relevant node is no longer in the document. I have very little experience with shadow DOM. Does `.contains` see through shadow DOM boundaries? If so, we could use that instead here.

**Comment by forresto** [comment]
Doesn't look like it:
![screen shot 2015-01-22 at 10 21 09 am](https://cloud.githubusercontent.com/assets/395307/5858346/7a0cb03e-a220-11e4-99b4-df0461925839.png)

Here's a reduced CodeMirror-in-Polymer case:

``` html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <title>polymer + codemirror lint tooltip autohide bug</title>

  <link rel="stylesheet" href="./bower_components/codemirror/lib/codemirror.css">
  <link rel="stylesheet" href="./bower_components/codemirror/addon/lint/lint.css">

  <script src="//www.polymer-project.org/webcomponents.js"></script>
  <script src="//www.polymer-project.org/polymer.js"></script>
  
  <script src="./bower_components/codemirror/lib/codemirror.js"></script>
  <script src="./bower_components/codemirror/mode/javascript/javascript.js"></script>
  <script src="//ajax.aspnetcdn.com/ajax/jshint/r07/jshint.js"></script>
  <script src="./bower_components/codemirror/addon/lint/lint.js"></script>
  <script src="./bower_components/codemirror/addon/lint/javascript-lint.js"></script>
</head>
<body>

<code-mirror></code-mirror>

<div>
  Bug: <a href="https://github.com/codemirror/CodeMirror/issues/3039">codemirror/CodeMirror#3039</a>
</div>
  
<polymer-element name="code-mirror">
  <template>
    <link rel="stylesheet" href="./bower_components/codemirror/lib/codemirror.css">
    <link rel="stylesheet" href="./bower_components/codemirror/addon/lint/lint.css">
    <div id="code"></div>
  </template>
</polymer-element>
  
<script>
Polymer('code-mirror', {
  ready: function () {
    var cm = CodeMirror(this.$.code, {
      lineNumbers: true,
      value: '"hello lint"',
      mode: 'javascript',
      gutters: ['CodeMirror-lint-markers'],
      lint: true,
      width: 300,
      height: 300
    });
    console.log(cm);
  }
});
</script>

</body>
</html>
```

**Comment by marijnh** [comment]
Does the attached patch work? It tries to continue through the element's `root` property when it hits a shadow root node.

**Comment by forresto** [comment]
At that point, `n` is `#shadow-root` with native implementations and `ShadowRoot` with webcomponents.js polyfill. The line should be:

    if (n && n.nodeType == 11) n = n.host;

This works for native (Chrome). You probably don't want to worry about Polymer's polyfill morass, but this is needed for it to work everywhere:

        if (n && n.nodeType == 11) {
          n = n.host; 
          if (typeof unwrap == "function") n = unwrap(n);
        }

**Comment by marijnh** [comment]
Thanks. I adjusted the property name in 34622a2 (not sure where I got `root` from -- I was looking at the spec which clearly says `host`).
