### ISSUE TITLE
[selection-pointer] Wrong block position after page scroll

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3040]
1. Go to http://codemirror.net/mode/htmlmixed/index.html
2. Resize the browser window so you have a reasonable-sized page scrollbar
3. Select multiple lines (for example the `<style>` content)
4. Scroll *the page* down a few lines
5. Hover the first line of the selection

Result:
Caret is shown.

Expected:
`cursor: default` is shown.

**Comment by marijnh** [comment]
Indeed, I forgot to attach an event handler for window scrolling. Attached patch should fix that.
