### ISSUE TITLE
[mobile branch] code mirror loses focus after first click in IE8

### ISSUE THREAD

**Issue by cdchambers** [codemirror/CodeMirror#3041]
1. Go to http://jsfiddle.net/a4vuoydw/5/embedded/result/ in IE8. Click somewhere outside of code mirror to ensure that code mirror doesn't have focus.
2. Click the code mirror text area.
3. Observe the blinking cursor and start typing a few letters (e.g. abc). 

Expected: newly typed characters appear.
Actual: none of the newly typed characters appear. 

4. Click the code mirror text area again and start typing. Now the characters appear.

Note:
-If you hit the backspace key as opposed to other character keys after the first click, the existing characters do get deleted as expected.
-Does not repro in Chrome, Firefox, or IE9 and above.

**Comment by marijnh** [comment]
Thanks for reporting that. Should be fixed in attached patch.
