### ISSUE TITLE
What is the best way to reset the value of the text area bound to code mirror

### ISSUE THREAD

**Issue by sagarmj76** [codemirror/CodeMirror#3044]
Hi I am trying to reset the value of the text area (bound to a code mirror instance) and for some reason it does not work .
What is the best way or standard practice to reset the value of the editor or the underlying text area to blank as what I figured out that setting it to '' (empty string does not work) but setting to a blank space ' ' sets the value but then again it's more of a hack. It would be nice come to know the standard way to this.
As of now, we have ko observables bound to the text area.

**Comment by marijnh** [comment]
Use the `setValue` method on your CodeMirror instance. Also, this is not a bug report, and thus does not belong in the bug tracker. Use http://discuss.codemirror.net for such questions.
