### ISSUE TITLE
Mobile branch - cannot modify document within "changes" event 

### ISSUE THREAD

**Issue by mihailik** [codemirror/CodeMirror#3046]
Updating document within "changes" handler screws up the content.

That's when using the latest mobile branch. On master there are no problems. To reproduce, try this HTML. Put the cursor in the editor, and type something, then press ';' -- which the script wants to auto-expand to ';// autoformat'. Instead CodeMirror cuts a chunk off and leaves garbage text.

    <html>
      <script src="https://rawgit.com/codemirror/CodeMirror/bdde0a7d3e9ab9ab450e48ba664014dd03efbf22/lib/codemirror.js"></script>
      <link rel=stylesheet href="https://rawgit.com/codemirror/CodeMirror/bdde0a7d3e9ab9ab450e48ba664014dd03efbf22/lib/codemirror.css">
      <script>
        window.onload = function() {

          document.body.innerHTML = '';
          var editor = CodeMirror(document.body, {
            lineNumbers: true
          });
          editor.on('changes', function(editor,changes) {
            if (!changes[0] || !changes[0].text.length) return;

            if (changes[0].text[0][changes[0].text[0].length-1]===';') {
              var after = { line: changes[0].to.line, ch: changes[0].to.ch+1 };
              //setTimeout(function ( ) {
                editor.replaceRange('// autoformat', after, after);
              //}, 1);
            }
          });

        };
      </script>
    <body></body></html>

**Comment by mihailik** [comment]
The URLs above point to mobile branch at the commit "Don't immediately focus on click in IE", a tip of mobile banch as of today.

Can point them to your local repo.

**Comment by mihailik** [comment]
Looks like the crucial piece involved in this bug is at line 1290, in TextareaInput.reset function:

      } else if (!typing) {
        this.prevInput = this.textarea.value = "";
        if (ie && ie_version >= 9) this.hasSelection = null;
      }

Not sure what !typing check is for here. But changing textarea.value from its current content to the empty string is picked up by the copyObj.poll (see line 1344) as a sign of deletion.

**Comment by marijnh** [comment]
Thanks for isolating that. It was a confusion between about when the input was being reset -- `TextareaInput.poll` was messing with `prevInput` after the operation ended, creating an inconsistent state. Attached patch should help.
