### ISSUE TITLE
JSCS plugin?

### ISSUE THREAD

**Issue by zz85** [codemirror/CodeMirror#3048]
can't say again how awesome codemirror is again.

i've integrated this with node-jscs for this javascript code style validator / autoformatter https://github.com/zz85/mrdoobapproves by modifying the lint plugin (and also the merge plugin for the autoformat feature).

not sure if @marijnh would like the [jscs plugin](https://github.com/zz85/mrdoobapproves/blob/gh-pages/mdcs-lint.js) to be contributed back to the codemirror project?

**Comment by marijnh** [comment]
Hi. This is cool. But no, I don't want to keep it in the CodeMirror distribution itself. Please add it to [the wiki](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons) so that others can find it easily.

**Comment by zz85** [comment]
sounds reasonable, thanks! :)
