### ISSUE TITLE
[vim] How can I define and map custom Vim commands?

### ISSUE THREAD

**Issue by kevinushey** [codemirror/CodeMirror#3049]
(this is a slight repeat of https://github.com/codemirror/CodeMirror/issues/2840)

I understand that I can define custom ex commands through `defineEx()`, and define key-to-key mappings through `map()`, but is there any way to map a particular (sequence of) keys to execute an arbitrary Javascript function?

Would it be sufficient to just append an appropriate object to the `defaultKeymap`? Or is there an alternative API available for this?

(It would be useful if some of the documentation re: extending Vim were placed here: http://codemirror.net/demo/vim.html)

Thanks! `vim.js` is really incredible :)

**Comment by mightyguava** [comment]
> I understand that I can define custom ex commands through defineEx(), and define key-to-key mappings through map(), but is there any way to map a particular (sequence of) keys to execute an arbitrary Javascript function?

No, there is not. I'm open to adding one. Just never had a request (oddly), and have not had time to think of a good API
> 
> Would it be sufficient to just append an appropriate object to the defaultKeymap? Or is there an alternative API available for this?

Adding to defaultKeymap will not work unless the command is already defined in vim.js

**Comment by kevinushey** [comment]
Some thoughts on how I imagine this might work:

1. Add an API for adding specific entries to the `operators`, `actions` and `motions` objects. I imagine this would be with e.g.

```js
addMotion("name", function(cm, head, motionArgs) { ... });
```

Or even:

```js
add("motion", "name", function(...) {});
```

Validating the function could be tricky; maybe it could be applied to some dummy text and see if it actually e.g. returns a `Cursor` object (in the case of a `motion`)?

After doing this, one could bind a (sequence of) keys to a particular action by either appending to the default keymap (probably not desired), or by asking the appropriate parts of `vim.js` to check both a `defaultKeymap` and a `userKeymap` for dispatching on a set of keys. Does that make sense?

If it does, I'd be happy to prototype and PR an implementation (time permitting)

**Comment by mightyguava** [comment]
I think I like the `addMotion` option a bit better (would call it `defineMotion` to better align with CodeMirror). I'd remove `head` from the argument list though, it's a bit controversial whether it should have been added to the list of arguments to start with...

For binding to them, I'd have a
```js
mapCommand('keys', 'type', 'name', {motionArgs: {}});
```
and corresponding `unmapCommand` function.

Adding a `userKeymap` for storing the user-defined map is something I've wanted to add for a while now, but I don't consider it necessaary for this.

As for validation, I don't believe CodeMirror core does validation on any of its extensions, so I'd just not bother with it for vim either.

**Comment by kevinushey** [comment]
I've been using something super simple and it seems to work well: https://github.com/rstudio/ace/commit/7d81d46b873ec022524d4128eef670dd11597415

The API is 'low level', though, so the onus is entirely on the user to pass in the correct objects, but that's not really that bad, I suppose -- the interface is fairly obvious to anyone who reads the source code. Any thoughts on whether something like this would be appropriate for `vim.js`? I feel that the `define*` API is fine as-is, but the `mapCommands` might be better as e.g.

```js
function mapCommand(keys, type, name, args, extra) {
    var command = {keys: keys, type: type};
    command[type] = name;
    command[type + "Args"] = args;
    for (var key in extra)
         command[key] = extra[key];
    defaultKeymap.push(command);
}
```

**Comment by mightyguava** [comment]
Cool. Looks like a nice clean API. Agreed that your alternate `mapCommand` proposal looks better. Would you like to submit a pull request?
