### ISSUE TITLE
IE8: fromTextArea(): Can't move focus to the control because it is invisible...

### ISSUE THREAD

**Issue by kamelkev** [codemirror/CodeMirror#3052]
Running into a problem on IE8 whereby I cannot perform a "fromTextArea" call on a hidden textarea. I'm currently running on 4.12.

Details:
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0) Timestamp: Wed, 28 Jan 2015 01:31:24 UTC
Message: Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus. Line: 12 Char: 8674 Code: 0 URI: https://ABC/js/codemirror/lib/codemirror-compressed.js

In my case I have a tabbed UI with 2 tabs. The user starts on tab 1, all content in tab 2 is display:none. My textarea I wish to attach CM to is within tab 2. Upon execution of"fromTextArea" I receive the above error.

I found several other references to problems exactly like this in the past, they are located here:
https://github.com/codemirror/CodeMirror/issues/1200
https://groups.google.com/forum/#!topic/codemirror/lk_O6zeMxQc

Suggestions on how to proceed? I far prefer to configure the instance at pageload then to wait for a tab swap to occur, if only for consistency reasons with a bunch of other code I'm maintaining.

thanks,
  K

**Comment by marijnh** [comment]
Attached patch adds a `try`/`catch` around the call to `focus` to prevent the error from crashing things. However, you'll still have to call the editor's `refresh` method when it becomes visible, because CodeMirror needs to be able to see its own size in order to draw itself correctly (and can not detect becoming visible).

**Comment by kamelkev** [comment]
Thank you so much Marijn, works exactly as expected now.
