### ISSUE TITLE
Autocomplete doesn't work when there are multiple cursors

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3057]
A better behavior would be that if you have several cursors and they're all positioned after the *same word*, then the autocomplete menu should show up for the main cursor, and selecting a completion should insert the new text at each cursor.

This is essentially Sublime's behavior and works very well there. If the prefixes at different selections are different, then autocomplete call can be silently ignored as it is now.

**Comment by marijnh** [comment]
A hurdle is that completers do their own context scanning, so each completer would have to be changed to do that for each cursor. This is not a big problem, but somewhat awkward, and potentially breaking for 3rd-party code. Maybe I can add a property that allows completers to opt-in to multi-cursor support. Is there a specific language that you are most interested in?
