### ISSUE TITLE
IME switching input occurs error on vim-mode with Japanese IME

### ISSUE THREAD

**Issue by mizchi** [codemirror/CodeMirror#3058]
`CodeMirror.keyName` in `onKeyEventTargetKeyDown` returns false if CodeMirror get IME switch.

https://www.dropbox.com/s/jgvkfsyaatqrgu7/スクリーンショット%202015-01-30%2018.33.30.png?dl=0

My local patch is here.
https://github.com/mizchi/CodeMirror/commit/8230879f9083586b16148b0c38593390f652122f
but I have no confidence this is right…

**Comment by marijnh** [comment]
Did you test with patch f97df90d832fa523d26f26131e6646567f5a83d0 (which is part of release 4.12)? That sounds like it would be addressing the same problem.
