### ISSUE TITLE
CodeMirror is not defined in php.js

### ISSUE THREAD

**Issue by rakibtg** [codemirror/CodeMirror#3060]
This is how i have loaded the CM PHP mode.
    var editorCore = CodeMirror.fromTextArea(document.getElementById("ed_php"), {
        lineNumbers: true,
        mode: 'php'
    });

But it seems to be not working again, getting a error in the browser console.
![screenshot of error](http://i.imgur.com/NlT0u1R.png)
Is that i'm missing something?

**Comment by hitsthings** [comment]
You need to add lib/CodeMirror.js and the php mode script files to the page.

This is a pretty generic new programmer kind of question so next time I'd suggest asking for help somewhere where you can get more help, like stackoverflow.com

**Comment by rakibtg** [comment]
ah! Thanks for your time :) I think i did all of those in my scripts file. But still unable to highlight code.
Here is my index.php => http://paste.ubuntu.com/9978554/
Here is my script.js    => http://paste.ubuntu.com/9978582/
* Making sure that the relative path for the CM and JS/CSS is working.
Here is the output      => http://i.imgur.com/0ZmyCZp.png

**Comment by rakibtg** [comment]
Okay, things getting prettier with Require.js :)
