### ISSUE TITLE
Mobile branch - losing line breaks on paste on Chrome mobile

### ISSUE THREAD

**Issue by mihailik** [codemirror/CodeMirror#3062]
Pasting several lines of text on Chrome Mobile replaces all newlines with spaces, concatenating the whole text in one long line.

That seems to be happening all the time, regardless of the options/modes.

- - -

I tried to investigate, the problem is already there at the time pollContent looks at the nodes. When I stick alert(0) in domTextBetween, and look at the text on screen -- it's already squashed in one line, so naturally the function returns squashed text.

Tried to reproduce it with just contenteditable outside of CodeMirror, getting no quirks, newlines are preserved when pasted into DIV, PRE and SPAN. Here's a sample I used to test without CodeMirror:

      <div id=ceditable style="width: 90%; height: 40%; margin: 1em; border: solid 3px gold; overflow: auto;" contenteditable=true>
        <div style="margin: 1em; border: solid 3px silver; padding: 1em;">AA</div>
        <pre style="margin: 1em; border: solid 3px silver; padding: 1em;">BB</pre>
        <span style="margin: 1em; border: solid 3px green; padding: 1em;">CC</span> 
      </div>
      <br>
      
      <textarea id=tarea style="width: 90%; height: 40%; margin: 1em; border: solid 3px cornflowerblue;"></textarea>
      <br>

      <button onclick="tarea.value = ceditable.innerHTML"> html? </button>

Borders are intentional and they tell an interesting story when pasting into DIV: every pasted line gets a border of its own.

It looks like the Chrome code dealing with the paste into contenteditable elements takes surrounding elements into consideration. For PRE elements it does not create DIVs per line, for DIVs it does, and copies parent element style, for SPANs it does create DIVs except for the first and last line. My suspcion those smarts is what screws things up.

**Comment by mihailik** [comment]
Got it!

I used contenteditable=true in my investigations, and that works OK. Apparently, CodeMirror uses contenteditable=plaintext-only. That's the one that breaks.

Pasting inside PRE, when parent DIV is contenteditable=plaintext-only results in newlines replaced with spaces. At least in Chrome Mobile on Android, will check others later.

Now the question is how to work around it. I wonder whether replacing PRE with particularly styled DIVs is necessary.

**Comment by mihailik** [comment]
Sample with contenteditable=plaintext-only in JSBin:

http://jsbin.com/zofabobaqo/1/edit?html,output

Copy from textarea (blue) and paste into DIV (AA), PRE (BBBB) or SPAN (CC). It works fine everywhere except for PRE.

**Comment by mihailik** [comment]
Well, one fix would be to avoid contentEditable='plaintext-only' and go for contentEditable='true' (line 1484).

It appears that the key difference between 'true' and 'plaintext-only' is in the way that alien input is treated, and it's not treated in a good way after all in browsers that do support 'plaintext-only' (although I didn't try it on Safari yet, it could be Blink's quirk).

**Comment by marijnh** [comment]
Thanks for analyzing that. I was happy to use plaintext-only because I assumed we would be able to capture almost all input before it affected the DOM, and disallowing non-text input would be great for preventing funny side effects. But since Mobile Chrome does _not_ let us intercept paste events, I guess that my reasoning does not hold, and we might as well just go for full contenteditable and deal with any complications as they come up.

Does the attached patch solve the problem for you?

**Comment by mihailik** [comment]
The multiline/squash bug is fixed!

There is definitely still something wrong during pasting.

Often it would insert an exta newline in front of the pasted text. It looks like the logic calculating the beginning node of the pasted text gets confused. Perhaps that should be a separate issue? I'll collect more info and try to ping down a clear reproduction case.
