### ISSUE TITLE
Init hooks are called before initialization is complete

### ISSUE THREAD

**Issue by tism** [codemirror/CodeMirror#3067]
When registering an init hook, the hooks are called before the text area is registered.

```cm.getTextArea()``` is defined after the call to ```CodeMirror()```, however ```CodeMirror()``` triggers the firing of the init hooks.

Is there a blocker to moving the assignment of ```getTextArea()``` into ```CodeMirror()```?

Reproduction jsbin using the 4.12.0 release: http://jsbin.com/dapofenisa/1/edit?html,js,output

Tested in Chrome 40.0.2214.94, using CodeMirror 4.12.0.

**Comment by marijnh** [comment]
That's a good point. Attached patch should solve it.
