### ISSUE TITLE
Async lint

### ISSUE THREAD

**Issue by JamesNK** [codemirror/CodeMirror#3073]
I've been trying to figure out how to create an async lint function and I have been unable to. I can't find documentation about it anywhere.

There is this stackoverflow question from a couple of years ago that appears out of date: http://stackoverflow.com/questions/16031072/using-an-asynchronous-warning-source-for-codemirrors-lint-feature/16031073#16031073

I searched the source code for async and I found this flag in lint.js but I don't know how to set it to true: https://github.com/codemirror/CodeMirror/blob/34622a2690493742c4246c04ad3fdc0d8f27ab50/addon/lint/lint.js#L123

**Comment by JamesNK** [comment]
I downloaded the uncompressed source and after some debugging found the solution was to pass these options when creating the CM instance:

    'lint': { 'getAnnotations': schemaLint, 'async': true }

I still think it would be useful to have an example.

**Comment by leopatras** [comment]
The linter demo does not make use of the special linter options, so novices like me do not necessarily understand thats its easy to customise.
It was only clear to me after several hours reading und debugging the lint.js code.
