### ISSUE TITLE
Indent for SQL mode not working anymore since 3.21

### ISSUE THREAD

**Issue by patrick-wolf** [codemirror/CodeMirror#3074]
In CodeMirror 3.20 their was basic indent support for mode SQL to at least indent a new line with the same indent as the previous line. But since v3.21 there is no indent for new lines at all.

Reproduces with 4.12 at http://codemirror.net/mode/sql/index.html
Go to the end of line 3 and press enter. The cursor is at the beginning of the line.

Download 3.20 (http://codemirror.net/codemirror-3.20.zip) and do the same as above. The cursor is positioned below @.

**Comment by marijnh** [comment]
Your bug report is pretty much the inverse of #2064. But on closer look, I think going back to the old behavior is more sane than what we are currently doing. Attached patch reverts the change made because of #2064.

**Comment by patrick-wolf** [comment]
Thanks!
