### ISSUE TITLE
Findbar annotations in search & replace demo

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3079]
1. Type in 'a\n' * 8. It's short enough that the scrollbar doesn't appear.
2. Ctrl+f for 'a'; All 'a' characters get highlighted.
3. At the end of the document type a bunch of newlines.

Expected:
When there are enough newlines to cause the scrollbar to appear, the scrollbar should have annotations corresponding to the part of the document that has find matches (the first 8 lines out of ~24 needed to get a scrollbar).

Actual:
100% of the height of the scrollbar is covered by the yellow annotations.

**Comment by marijnh** [comment]
Thanks for reporting that. Could you verify that attached patch solves your issue?

**Comment by mtaran-google** [comment]
That fixes it, thanks!
