### ISSUE TITLE
Should not use ctrl+space to activate autocompletion

### ISSUE THREAD

**Issue by linquize** [codemirror/CodeMirror#3082]
Should not use ctrl+space to activate autocompletion.
This is the shortcut key to switch input method in Windows, so it does not work for me.

**Comment by marijnh** [comment]
The editor core or hint addon does not prescribe any key combination to use for autocompletion. Ctrl-Space is just used in some of the demos because it is widely used for this purpose. You are free to configure another combination for your own site.
