### ISSUE TITLE
[mobile branch] DisableBrowserMagic does not work in div contenteditable

### ISSUE THREAD

**Issue by beretzls** [codemirror/CodeMirror#3087]
Hi, 
I am running CodeMirror on iPad Air 2, iPhone 6 Plus, and iOS Simulator with iOS 8.1.2. It seems that if given a blank CodeMirror, the keyboard capitalization is always turned on, even after I type the first character. A quick Google search tells me that the autocapitalize attribute does not work for div that has contenteditable.

To reproduce this, use an iOS device or the iOS Simulator, go to [the mobile branch index.html page](https://rawgit.com/codemirror/CodeMirror/mobile/index.html) and clear all the contents in the code editor, exit focus and refocus on the code editor.

Thanks!
Alex

**Comment by marijnh** [comment]
I know. I don't think there is a way to actually turn this behavior off in contentEditable, so there's not much I can do about this problem. (Though none of this stuff is properly documented -- it's possible that there is some trick, and I just don't know about it. If so, let me know.)
