### ISSUE TITLE
[go] JS error "Cannot read property 'align' of undefined"

### ISSUE THREAD

**Issue by spearce** [codemirror/CodeMirror#3093]
The Go mode can get itself into a state where state.context is null/undefined:

  SEVERE: (TypeError) : Cannot read property 'align' of undefined
        at Unknown.token(...)
        at Unknown.readToken(...)
        at Unknown.processLine(...)

(File and line number data is useless due to Closure compiler stripping whitespace.)

**Comment by marijnh** [comment]
I assume my patch fixes it. If you run into the issue again, please show me the code that triggers the problem.
