### ISSUE TITLE
Line number is misaligned when we overwrite the text using setValue method

### ISSUE THREAD

**Issue by Manoj-RG** [codemirror/CodeMirror#3098]
I have created a text editor in my application using Code mirror. The content of the text editor has to be fetched from DataBase, when I reopen the text editor in my application. I aslo have line number for the text editor in the left side.

The problem is when I overwrite the content using setValue method, the line numbers are misaligned. That is it get collapsed with the content. 
![misaligned](https://cloud.githubusercontent.com/assets/11134452/6314043/149ff812-b9f1-11e4-8478-5b5e9cbb22d2.jpg)
The above image is the output which I get. The line numbers has to be in the left. But after calling setValue method, the line numbers moved out from left position and gets collapsed with the content

**Comment by silverwind** [comment]
I also noticed some strange gutter alignment recently, but only in the themes `mdn-like` and `pastel-on-dark`.

On Firefox, the line numbers look like this:
![fx](https://cloud.githubusercontent.com/assets/115237/6315109/bd9a61ea-b9f7-11e4-8cb0-dfa0e584f4aa.png)

On Chrome, I see the whole gutter moved a few pixels to the right, leaving a small gap on the left:

![chrome](https://cloud.githubusercontent.com/assets/115237/6315128/40744d10-b9f8-11e4-9503-a0db916a8169.png)

It appears the inline style values get calculated incorrectly. On Chrome, `CodeMirror-gutters` gets `left: 5px`, and If I set it to `0`, it looks correct.

Unfortunately, I can't reproduce in the demo and `setValue` seems to have no effect on the bug for me.

**Comment by silverwind** [comment]
I think I have an regression window here:

last good: 4.6.0
first bad: 4.7.0

@Manoj-RG can you confirm it works in 4.6.0 for you?

**Comment by silverwind** [comment]
Reverting https://github.com/codemirror/CodeMirror/commit/cde95c423cd59621b1f7b33a0de04f539fb9888a fixes it for me.

**Comment by marijnh** [comment]
Can you provide a test HTML file that produces the issue? Calling `setValue` is done everywhere, and does not in general cause problems.

**Comment by silverwind** [comment]
Try my [demo](http://droppy-demo.silverwind.io/#/code/client/client.js). Go to 'Prefs' and set 'Editor Theme' to 'mdn-like'. The issue should be visible immediately (floating gutter in Chrome, gutter bleeding into text in Firefox).

(If for some reason, the link doesn't open to a CodeMirror, nagivate and click any other text file).

**Comment by marijnh** [comment]
Can you create a _stand alone_ demo? The problem could be anywhere in the bucketloads of scripts and styles that that page is including. I am not going to sift through them.

**Comment by silverwind** [comment]
Can do, but I can assure you that no script touches CM positioning or gutter positioning.

**Comment by silverwind** [comment]
Still investigating, I got this rather interesting display:

![lines](https://cloud.githubusercontent.com/assets/115237/6328366/0030701a-bb67-11e4-8c82-923f37acc89d.png)

**Comment by silverwind** [comment]
Well, I was able to solve the issue about the floating gutter in Chrome it seems. I think the cause for it was that I did `cm.setOption("theme", theme)` before the theme's CSS was available. The theme sets a `border-left: 6px`, and I think CM didn't see that 6px border in `.clientLeft` yet when `getDimensions` ran before the theme was applied.

The line number misalignment in Firefox is still unresolved. The `left: 6px` corresponds to two times the width of mentioned border, so i'd say it must be something with `.clientLeft` and the border again.

**Comment by silverwind** [comment]
Dumping out the 3 vars in `getDimensions` shows a browser inconsitency:

Firefox
```js
n.offsetLeft = 6
n.clientLeft = 0
gutterLeft =  6
```

Chrome
```js
n.offsetLeft = 0
n.clientLeft = 0
gutterLeft = 6
```

**Comment by silverwind** [comment]
Probably this: https://bugzilla.mozilla.org/show_bug.cgi?id=850684

@marijnh think you can work around that bug?

**Comment by silverwind** [comment]
Also, I think the `left` calculation is wrong even in Chrome with the border present. This is with `6px`:
![3px](https://cloud.githubusercontent.com/assets/115237/6329740/6c481062-bb73-11e4-963b-753cbf260ff5.png)

Setting it to `3px` seems to be the correct value so it won't overflow.

**Comment by silverwind** [comment]
I'll see if I can provide a patch for Firefox, but I'd appreciate a workaround in the meantime :)

**Comment by silverwind** [comment]
Firefox build finally finished, turns out the miscalculation of `offsetLeft` is not caused by bug 850684. The fact that it doesn't show in the demo means to me that it must be another edge case related to the positioning of CM's parent nodes.

**Comment by silverwind** [comment]
I scanned all offset related bugs in bugzilla, and while there are at least 5-6 dupes of above bug, none matches our case.

I wonder if we could do without JS positioning on the line numbers. How about using CSS positioning like `right: 0` on the line numbers inside the gutter? Would certainly bea lot less prone to browser bugs like this.

**Comment by marijnh** [comment]
So is there still a problem if you ensure that you don't use a theme that hasn't been loaded? And if so, for the last time, can you give me an HTML page that actually allows me to reproduce it? I need to be able to see a bug and poke at it in order to know what's going on.

**Comment by silverwind** [comment]
I'm not sure how much help just a HTML would be. The bug is only happening in a seemingly rare condition where Firefox miscalculates `offsetLeft`. Been trying to reproduce in JSFiddle, but no luck so far.

https://github.com/codemirror/CodeMirror/issues/3098#issuecomment-75554110 is a separate bug, where the border of the gutter isn't taken into account when calculating line number width.

**Comment by silverwind** [comment]
Finally found the cause, it's `box-sizing` related. Minimal testcase here:

http://jsfiddle.net/silverwind/ozrsqch2/4/

**Comment by marijnh** [comment]
Thanks! I've pushed two patches that should help here -- one to force `CodeMirror-gutters` to the right box-sizing, and one to fix a problem in the mdn-like theme, whose line numbers ended up 3px too much to the right.

**Comment by silverwind** [comment]
Awesome, thanks :+1: 

@Manoj-RG: Please verify. I'm not totally sure this change covers your issue.

**Comment by goyatparmod** [comment]
We have still same issue.... even thought we have .css with 
-moz-box-sizing: content-box;
  box-sizing: content-box;


![image](https://cloud.githubusercontent.com/assets/13874876/9411467/572c2cc0-47e3-11e5-88b8-9729e02ca0d4.png)

**Comment by goyatparmod** [comment]
But When it hot line number 10 it automatically adjust content on screen properly. 

![image](https://cloud.githubusercontent.com/assets/13874876/9411522/95c1af82-47e3-11e5-9aca-37f58fffb759.png)

**Comment by Manoj-RG** [comment]
@goyatparmod  In my case, I was using the version 4.6.0 and I was not allowed to migrate to higher versions. I fixed this gutter issue by making the 'fixedGutter' parameter to FALSE. I don't know how it worked. I was trying multiple options and finally setting the 'fixedGutter' parameter to FALSE fixed my issue (same version 4.6.0). 

@silverwind  and @marijnh 
Thanks for your awesome work

**Comment by mwileyTibco** [comment]
I had the exact same issue when displaying a CM element on an Angular-wrapped bootstrap tab that's hidden when the page loads (i.e. another tab is shown by default). When the user clicks on the tab with the CM element, the element would appear, but it would behave as @goyatparmod described (weird until you enter the 10th line). I figured I might have to call CM.refresh when the tab gets activated. The trouble was figuring out what event actually corresponded to the tab being activated. I found that the element wasn't hidden, so trying to react to element.show() didn't help. Rather, the element had width & height set to 0 until the tab it was displayed on became active. This actually might explain the weird CM behavior because it would have initialized with zero width and height. So instead of reacting to .show() I tried .resize() and it works. I suspect this might help you @goyatparmod because you're showing the code in a modal kinda like I'm showing it in a tab.

In essence the code looks something like this (sorry just off the top of my head here...)
```html
<div id="target"></div>
```

```javascript
var elem = $('#target');
var cm = CodeMirror(elem[0], {});
elem.resize(function(){
    if(elem.width() > 0){ cm.refresh(); }
});
```

**Comment by goyatparmod** [comment]
Thanks to marijnh....mwileyTibco..My problem is also solved ..I use https://fossies.org/dox/Joomla_3.4.4-Stable-Full_Package/autorefresh_8js_source.html and autorefrsh:true and it work very well.
ui-codemirror="{lineNumbers: true,
                                     lineWrapping : false,autoRefresh:true,
                                     theme: 'paraiso-light',
                                     styleActiveLine: true,fixedGutter:true,
                                     lint:true, coverGutterNextToScrollbar:false,
                                     gutters: ['CodeMirror-lint-markers'],
                                     mode: 'javascript'}"

**Comment by stateoflux** [comment]
Whew! so glad I stumbled across post.  I had the same issue as @goyatparmod and i've working on it for the past few hours trying to figure how to fix.  Installing the "autorefresh" addon and setting the config option to true solved the problem for me.

**Comment by dcsaszar** [comment]
Could we please reopen this issue, as it seems to be present still?

I created a fiddle to reproduce. It shows another issue (CodeWarrior being not visible at all), but this isn't relevant here.

http://jsfiddle.net/TcqAf/184/ tested with Firefox 42.0

**Comment by marijnh** [comment]
No we can't reopen the issue. Use [`refresh()`](http://codemirror.net/doc/manual.html#refresh) or autorefresh, as described in the previous discussion.

**Comment by tedwong** [comment]
@dcsaszar  did u solve the issue?

**Comment by dcsaszar** [comment]
@tedwong The quick fix was using `codemirror/addons/display/autorefresh` and `autoRefresh: true`, as mentioned in https://github.com/codemirror/CodeMirror/issues/3098#issuecomment-147022207

I later fixed it by initializing the editor at a later point in time, when the page rendering was more complete. I don't remember the specifics.

**Comment by rochapablo** [comment]
https://github.com/scttcper/ngx-codemirror/issues/288
