### ISSUE TITLE
getComputedStyle missing "window." prefix

### ISSUE THREAD

**Issue by spearce** [codemirror/CodeMirror#3101]
lib/codemirror.js line 119 in 4.13 is missing window. before getComputedStyle:

    if (webkit && options.lineWrapping &&
        getComputedStyle(display.lineDiv).textRendering == "optimizelegibility")

This causes errors when packing CodeMirror with Closure Compiler.

**Comment by marijnh** [comment]
The problem appears to be with Closure, not CodeMirror. Global variables like `setTimeout` and `getComputedStyle` can be accessed without the `window` prefix, and if the Closure Compiler chokes on that, you should report it there.
