### ISSUE TITLE
Feature request: make automatic `setSize` on window resize optional.

### ISSUE THREAD

**Issue by sccolbert** [codemirror/CodeMirror#3103]
When embedding code mirror in a larger framework which provides its own resize event dispatching, it would be nice to be able to disable code mirror's default window resize handler to eliminate the double notification.

A workaround is to replace the `setSize` handler with a no-op and manually invoke the original handler when the editor is resized.

**Comment by marijnh** [comment]
Which notification are you talking about? In recent versions, the resize handler should not do any real work if the size of the editor did not actually change.

**Comment by sccolbert** [comment]
I was referring to this function:
https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L3413

I was concerned about the  `clientHeight` and `clientWidth` reads causing unnecessary reflow but didn't see that they would only be called at 100ms intervals.

This is a non-issue. I apologize for the noise.
