### ISSUE TITLE
New option to specify how many lines should be scrolled on mousewheel scroll

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3109]
Reading https://github.com/adobe/brackets/issues/10214 inspired me to suggest this to CM:

There should be an option to specify how many lines (code lines!) should be scrolled when scrolling with the mouse wheel.
Such a setting exists in the Windows control panel (see the screenshot in the issue linked above), but it's completely neglected by Chrome (and it's even worse in CEF), so I guess introducing it in CM makes sense.

**Comment by marijnh** [comment]
Currently CodeMirror lets the browser's native scrolling behavior take effect, and does not `preventDefault` wheel events except in rare circumstances. This has the advantage of the scrolling actually feeling native. Thus, such an option doesn't fit very well in the library.

If you want to capture wheel events yourself, and force a given scroll distance, that's easy too -- just add your own event handler, which calls `preventDefault` and makes a call like `cm.scrollTo(null, cm.getScrollInfo().top + X * cm.defaultTextHeight())`. Determining X based on the event's delta is another story, but if you're only targeting one browser engine (as Brackets is), that shouldn't be hard.

**Comment by doppl3r** [comment]
Hi marijnh, could you point me in the direction in which I can prevent the default scroll options? Is there a certain file I can change/include this code? What should the code look like?

This 12-20 line hop (based on font-size) is tempting me to migrate back to notepad++ haha

**Comment by MarcelGerber** [comment]
@doppl3r You can take a look at what I did in adobe/brackets#10685

**Comment by doppl3r** [comment]
Perhaps this is a newb question, but does this go into the brackets.json file?

ex:
{
    "themes.theme": "darcula-theme",
    "fonts.fontSize": "11px",
    "livedev.multibrowser": true,
    "wordWrap": false,
    "closeBrackets": true,
    "styleActiveLine": true,
    **"scrollAmountY": {"size": 1, "unit": "lines"}**
}

I assume 'no' would be the correct answer because i'm still skipping many lines on mouse scroll.

**Comment by MarcelGerber** [comment]
Ah, so you're a Brackets user. In that case, your question would fit better in https://github.com/adobe/brackets/issues/10214, but it's ok her too I guess.
`scrollAmountY` isn't yet part of a Brackets release, so you can't just set the preference without the corresponding code.

But yeah, assuming you have [Brackets set up for "hacking"](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets), you can either merge my pull request into your local git repository or simply copy & paste the content of the edited `Editor.js` file.
