### ISSUE TITLE
[doc] Update addon_lint section.

### ISSUE THREAD

**Issue by lukas-vlcek** [codemirror/CodeMirror#3113]
I think [addon_lint](http://codemirror.net/doc/manual.html#addon_lint) section needs some update after https://github.com/codemirror/CodeMirror/commit/794abd19160a95269badd66b2b5ee704cbc8a99d. Specifically, it would be useful to metion that `cm` instance is passed into method.

Anyway, thanks for great work!

**Comment by marijnh** [comment]
Are you using the editor argument? If so, for what?

**Comment by lukas-vlcek** [comment]
Because I need `cm` instance and did not find other way how to get hold of it. IIRC it should be possible to pass it via second `options` argument too but I do not know how to do it. Moreover, passing it via generic map is less type secure in my case (I am using Closure Compiler thus I prefer the option to benefit from "strongly" typed arguments if possible).

More specifically, the reason why I think I need `cm` instance is that I want to get `start` and `end` position of errored token. The parser `error` can give me any position inside the token, but I want whole token to be underlined in editor.

Here is (pseudo-code) of what I do:

````js
CodeMirror.registerHelper('lint', 'json', function(text, options, cm) {
    try {
        someParser.parse(text);
    } catch (error) {
        var actualToken = cm.getTokenAt(cm.posFromIndex(error.offset));
        return [{
            'message': error.message,
            'from': CodeMirror.Pos(error.line, actualToken.start),
            'to': CodeMirror.Pos(error.line, actualToken.end),
        }];
    }
}); 
````

May be there is better way of doing it?

**Comment by marijnh** [comment]
Right, if you need access to the actual mode's tokenizer, I guess there's no getting around touching the editor instance. That's a valid use case, and I've added a note about that argument to the docs.

**Comment by lukas-vlcek** [comment]
Thanks.
