### ISSUE TITLE
Combination of lineWrapping, specialChars and non-breaking spaces can hang Chrome, Internet Explorer

### ISSUE THREAD

**Issue by markrian** [codemirror/CodeMirror#3117]
This is super-obscure, and it can hang Chrome and Internet Explorer, but not Firefox.

Since the introduction of the `specialChars` option (I bisected for the issue: f0610e60c3b220814d80c133326adebc7339a35f), if you have a CodeMirror instance with `lineWrapping` enabled, and add the non-breaking space character U+00A0 to the default `specialChars` option (`/[\t\u0000-\u0019\u00ad\u200b-\u200f\u2028\u2029\ufeff]/g`), entering three consecutive spaces will actually insert one space, one non-breaking space, and one final space character. The non-breaking space will be displayed as a red dot. Interestingly, if you `.getValue()` on the instance, the result is just three space characters; no non-breaking spaces are present.

Now, where's the crash? Remove global flag from the `specialChars` option. Now, entering the first two spaces is fine, but entering the third results in an infinite loop and hangs the process. The loop occurs, I believe, in `buildToken()`: the [condition to break the while-loop](https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L6810) is never satisfied.

It's also worth noting that the documentation is out of date. It says that the default value of `specialChars` is

    /[\u0000-\u0019\u00ad\u200b\u2028\u2029\ufeff]/

but it's actually

    /[\t\u0000-\u0019\u00ad\u200b-\u200f\u2028\u2029\ufeff]/g

If you disable `lineWrapping`, this problem entirely disappears. Firefox doesn't exhibit this at all either way.

I've prepared a [gist of a demo html file](https://gist.github.com/markrian/b07b6b7c2a628958ad98#file-codemirror-oddness) demonstrating the non-crashing variant of this.

**Comment by marijnh** [comment]
These are two separate bugs -- attached patches should fix them. The code that ensured the specialchars regexp was always global didn't kick in when the option was given immediately on initialization. And the hack to replace stretches of spaces with alternating spaces and non-breaking spaces (to work around odd browser behavior in Webkit and IE) was kicking in before the special character filter, which produced the effect you saw.

As for `\t` not being mentioned as part of specialChars in the docs, that's intentional -- technically, tabs are treated special, and are only in there as an optimization.

**Comment by markrian** [comment]
What an incredibly fast turnaround for a ticket! Amazing. Thank you.

As for the docs, it's not just \t that's missing, it's also the character range \u200b-\u200f, and the (admittedly redundant) global flag. Are these also intentional?

**Comment by arunkumaralagesan** [comment]
Hi Team, still the "nbsp" issue persists. Can we reopen the issue, or any suggestion to display placeholder text?

using below, but seems hacky.

    specialChars: /[\u00a0]/g,
    specialCharPlaceholder: function(m, k) {
      console.log('-----check------', m, k);
      var span = document.createElement("span");
      span.appendChild(document.createTextNode("."));
      span.setAttribute("class", "my-class");
      return span;
    }
