### ISSUE TITLE
JSX support?

### ISSUE THREAD

**Issue by chuyik** [codemirror/CodeMirror#3122]
Hi devs, how about adding JSX support into [javascript.js](https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js)?

**Comment by marijnh** [comment]
If you want to work on this, the way to do it would be to make the JavaScript mode extensible, so that you can override the way it parses expressions. And then write an extension that, in case an expression starts with a `<`, switches to the JSX mode.

**Comment by eranimo** [comment]
What about this?
https://code.google.com/p/lite/source/browse/trunk/Lite/web/doc/codemirror/jsx.js?spec=svn1482&r=1482

I've tried using it, but I get an error: `Uncaught RangeError: Maximum call stack size exceeded`

**Comment by weblogixx** [comment]
:+1: Would also love to see this feature.

**Comment by baconface** [comment]
+1

**Comment by marijnh** [comment]
The link @eranimo posted looks a lot like the approach I would take if I were to implement it. So instead of posting +1's here, you could try debugging and fixing it (though note that it's LGPL code -- you might want to contact the author and ask if it can be moved under an MIT license first).

**Comment by Ore4444** [comment]
+1

**Comment by pcostanz** [comment]
:+1:

**Comment by williamstein** [comment]
Hi,

I was using CJSX (the coffeescript analogue of JSX) recently in codemirror,
and needed syntax highlighting and indent.  I found a mode for Adobe
Brackets and rewrote it to work in codemirror, and put it here:


https://github.com/sagemathinc/smc-public/blob/master/static/codemirror-5.3/mode/coffeescript2/coffeescript2.js

Anybody is welcome to it (under the Brackets's MIT license)...

William

On Fri, May 29, 2015 at 12:16 PM, Patrick Costanzo <notifications@github.com
> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemirror/CodeMirror/issues/3122#issuecomment-106906712>
> .
>



-- 
William (http://wstein.org)

**Comment by abdelouahabb** [comment]
for the moment I use this trick:
https://github.com/abdelouahabb/CodeMirror/commit/521c476de9b8a961a3205e7284863de88d012a96

**Comment by foo123** [comment]
Hello, why not try the [codemirror-grammar add-on](https://github.com/foo123/codemirror-grammar) (author) and do it your-self quite easily. On top of that one can have a base js-grammar and only the necessary extensions for JSX etc.. and extend the base as needed, if needed

Cheers

**Comment by jquense** [comment]
this has driven me crazy for months I finally broke down and just wrote a better mode

https://gist.github.com/jquense/265b46c740da4d20a718

It doesn't handle jsx expressions as well as I'd like (see comments) someone smarter than me, please improve it!

**Comment by kidwm** [comment]
@jquense My patch-up approach was rejected. Could I try to improve your code and send PR again?

**Comment by jquense** [comment]
@kidwm please do! the current issues with my approach is tracking the inline jsx expressions right now it just works when the js starts and ends on the same line. I've tried more nuanced attempts at it (tracking brackets in state) but haven't had the time to solve the issues there. 

I'd be great if you took a whack at it :)

**Comment by cldwalker** [comment]
@jquense You may find this useful (similar to first link) - https://github.com/antimatter15/codemirror-jsx/blob/master/jsx.js

**Comment by TimothyGu** [comment]
This should be closed after #3742.

**Comment by jquense** [comment]
:tada: WOOHOO! Thanks so much @marijnh
