### ISSUE TITLE
Print preview of editor is not working properly in Firefox 

### ISSUE THREAD

**Issue by rsmith31415** [codemirror/CodeMirror#3123]
When I tried to print preview an Ipython document (which uses CodeMirror) the text in the cells appears truncated. Then I looked at CodeMirror's homepage and realized that the main demo has the same problem.

This is part of the HTML page:

![screenshot from 2015-03-09 21 48 10](https://cloud.githubusercontent.com/assets/599274/6568979/2ccdd87e-c6a7-11e4-973c-1dab08694d91.png)

And this is the print preview in Firefox (36.0):

![screenshot from 2015-03-09 21 48 33](https://cloud.githubusercontent.com/assets/599274/6568981/43842168-c6a7-11e4-8842-bcbc53237f46.png)

The print preview works without issues in Chrome 41.0.2272.76. I haven't tested other browsers.

**Comment by marijnh** [comment]
What exactly do you mean by 'appears truncated'? The page is reflown to fit on paper. The fact that this changes the size of the CodeMirror box is expected.

**Comment by rsmith31415** [comment]
Well, if you look at the second image above, line 8 is being cut off. Let me show you a bigger screenshot:

![screenshot from 2015-03-12 14 20 31](https://cloud.githubusercontent.com/assets/599274/6627352/226620ee-c8c3-11e4-86e1-eb87951f1c27.png)

I don't think the logo and "Other demos" field are a big problem because that's page dependent, but the last line of code is missing from the CodeMirror box when your input is short enough to be displayed without scrollbars.

**Comment by marijnh** [comment]
I see what you mean. The editor's layout is computed using JavaScript, and I guess Firefox doesn't let JavaScript run after computing a print layout. I'm not sure we can do much about that.

**Comment by rsmith31415** [comment]
I was tinkering a bit with `min-height ` in the Ipython notebook and this has a positive effect in the print preview, but I think I needed to increase the height of empty CodeMirror boxes to display the last line of code correctly. Something like this:

![screenshot from 2015-03-12 14 42 55](https://cloud.githubusercontent.com/assets/599274/6627754/1d6693b4-c8c6-11e4-9ca8-3687b8e71ce1.png)

Maybe all it takes is an adjustment to the CSS and/or an additional media query targeting the print preview.
