### ISSUE TITLE
Ctrl-Shift-Click for selecting multiple ranges broken

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3128]
1. Go to http://codemirror.net/demo/fullscreen.html
2. Select `Whether` in line 3 (it doesn't matter _how_ you select it)
3. `Ctrl-Click` before `indenting` (line 3)
4. `Ctrl-Shift-Click` after `indenting` (line 3)
5. Look at console

Result:
```
Uncaught TypeError: Cannot read property 'empty' of undefined codemirror.js:3597
```

Expected:
Second selection ranging over `indenting`

Apparently, `ourIndex` is `undefined` in [line 3597](https://github.com/codemirror/CodeMirror/blob/def124276c090d85ae6bf296bdedb3a3bf9f9199/lib/codemirror.js#L3597)

===========
`git bisect` points to b833e63142d18e89a43cc37b712325f5b530c08c.
`Ctrl-Shift-Click` was implemented in 99dbd74d0866532ac466bc633f2cf4d2e932b09e.

**Comment by marijnh** [comment]
Attached patch should fix this.

**Comment by MarcelGerber** [comment]
Works, thanks!
