### ISSUE TITLE
height calculation broken

### ISSUE THREAD

**Issue by flying-sheep** [codemirror/CodeMirror#3129]
hi, i tried to write an userscript embedding a codemirror editor into reddit for stylesheet editing.

it breaks horribly: [the userscript](https://gist.github.com/0cf393e9d88eb4351aec)

you can try it with the account csstestacc (same password) [here](http://www.reddit.com/r/boitest/about/stylesheet/)

**Comment by marijnh** [comment]
That may be related to any number of things. I do not have time to debug specific integration issues.

**Comment by flying-sheep** [comment]
eh, and how can i help to debug it?

**Comment by marijnh** [comment]
You could start by describing what 'breaks horribly' actually means. And then set up a stand-alone demo that shows the issue.
