### ISSUE TITLE
FR: Highlight class-names in Java

### ISSUE THREAD

**Issue by cgrushko** [codemirror/CodeMirror#3136]
CodeMirror is awesome!
Feature request: make class-names in Java in a separate color.
For example in Sublime Text 2:
![image](https://cloud.githubusercontent.com/assets/1998689/6660078/5d5e898c-cb68-11e4-9264-3ebc354b35aa.png)

vs. CodeMirror:
![image](https://cloud.githubusercontent.com/assets/1998689/6660082/70dde750-cb68-11e4-8e65-967e3300cb45.png)

That is:
ST2 chooses blue for all of the types (which is not the same as reserved words) 
and green for the method name.
CodeMirror chooses the same color to pretty much all of the code I wrote.
As a result, it's harder to read code in CodeMirror.

Any ideas how this can be improved?
Thanks!

**Comment by marijnh** [comment]
The Java mode is a simple configuration of the the `clike` mode, which handles basic indentation and highlighting of keywords and literals in C-style languages, but nothing more. To get better Java support, you'd have to write a specialized Java mode, or pay me to do so.

**Comment by vincentwoo** [comment]
@marijnh would it be untoward to ask what your price for this would be? Happy to talk offline as well.

**Comment by marijnh** [comment]
This has been done in 3d5d9a4af38fac
