### ISSUE TITLE
Undo bug

### ISSUE THREAD

**Issue by liquibyte** [codemirror/CodeMirror#3142]
Undo is always available and replaces last character behind current cursor position with a space when invoked.  This only affects invocation with the right mouse button and gecko (Firefox 36), webkit doesn't seem to have this issue (tested with Chrome 41.0.2272.89 and Opera 29.0.1795.0).

I've tried this with my implementation and at https://codemirror.net/index.html in the demos.

**Comment by marijnh** [comment]
Firefox, unlike other browsers, seems to include programmatic changes in the user-visible undo history, which is why it enabled the undo menu item in the first place. Choosing that confused CodeMirror's interpretation of what was happening the textarea. Should be better with attached patch.

**Comment by liquibyte** [comment]
I patched my local version and that did fix the space replace undo issue, however the actual undo functionality of the menu is now disabled in its entirety even though the menu choice is enabled.  Ctrl-z works as expected so not really a show stopper for me but I imagine it could be to those not familiar with the keyboard.

I don't envy you having to try and support so many browsers.  Good work by the way.  I'm using this in a microblog project I'm writing because, as far as I can tell, there's no way to syntax highlight a textarea without javascript or messing with the DOM on a level I'm not willing to explore at the moment.  I'm still having a hard time figuring out how to integrate require.js into everything as I'd like to have highlighting for many languages available.  Javascript is not my strong suit.

**Comment by marijnh** [comment]
Though, as I said, there is no sane way to capture context-menu undo, I found an insane way, which seems to work (put in a nonsense unicode character which is then overwritten, and when the browser undoes and restores that character, abort the input reading and fire an undo instead).

**Comment by liquibyte** [comment]
Yep, that works.  I should really take a look at FF source one of these days but it's so big and unwieldy.  It doesn't even compile on Gentoo by default without a lot of work, but the same could be said of Chromium as well due to webkit issues.

**Comment by liquibyte** [comment]
I hate to do this to you but I found another bug that is a result of the patching.  Copy and paste no longer works from the menu.  I get our nonsense character back now "⇚".

**Comment by marijnh** [comment]
> I hate to do this to you but...

No, _thank you_ for reporting that so quickly. I messed up the order of assignments in my previous patch, and this would have been rather critical had it ended up in a release. (And I still haven't found a way to automatically test the context menu -- or the clipboard, for that matter.) Attached patch should help.

**Comment by liquibyte** [comment]
That seems to have fixed it in Firefox.  The behavior didn't manifest in Opera or Chrome originally but I can verify that the undo menu selection in the webkit browsers isn't working right after the patch.  If you copy and paste and then undo, nothing happens.  It works as expected in FF though.

I'll keep my eye out for unexpected behavior as I test out my project on various browsers.  Right now I'm just working with FF mostly with the occasional test for odd rendering quirks in Opera and Chrome to make sure that everthing looks right but I'm working with PHP so I don't have to worry about anything other than my own css goofs.  I don't use Window or plan on testing in IE.  I went through that fiasco the first go around and decided to just not support it with special attention, if it works, it works, if it doesn't it's their fault.

I plan on doing a test page for each language once I get require working.  I've mapped out the dependencies so I can load each one but it's been slow going as I'm not that familiar with it so I'm having to learn how it works.  I can add to the documentation with detailed examples once I get done if you'd like.  The short example given in the codemirror documentation wasn't all that helpful as it assumes a basic knowledge of require.  I've not really worked with javasript all that much but can muddle through.  I did the drag and drop fixes on the Flatpress admin panel a year or two ago.

**Comment by marijnh** [comment]
It seems Chrome does show 'Undo' as being available if you right-click right after typing. It does not, however, seem to do anything except reset the selection when this option is picked. That did sometimes have the effect of causing select-all detection to fire when it shouldn't, which patch 8757ba2 works around. I can't think of any way to actually reliably detect and handle this undo though.
