### ISSUE TITLE
trouble with .on/off and "beforeChange" event

### ISSUE THREAD

**Issue by aleatorybug** [codemirror/CodeMirror#3143]
I seem to be unable to 'off' a listener on the beforeChange event.  I have a fiddle up here demonstrating the behavior: http://jsfiddle.net/9a6r1949/1/

**Comment by marijnh** [comment]
You have to pass `off` the exact function you passed to `on` (just like with `removeEventListener`). You can't just unregister all handlers for an event by not passing a second argument.
