### ISSUE TITLE
CodeMirror swallows onClick event

### ISSUE THREAD

**Issue by hankduan** [codemirror/CodeMirror#3145]
CodeMirror's parenthesis match mechanism swallows the event on the first click when user clicks on a matching parenthesis.

For example, if I have a listener on the CodeMirror element:
```javascript
    var editor = new CodeMirror(editorEl, config);
    goog.events.listen(editor.getElement(),
        goog.events.EventType.CLICK,
        function(e) { console.log('CLICKED'); });
```

Then if the editor displays code with parenthesis:
```
1 var xyz = function() {
2   // do something
3 };
```

If I click on line 1, codemirror will highlight the matched parenthesis on line 3, which is expected. However, it will also swallow the click event, and the listener wouldn't fire.

**Comment by marijnh** [comment]
It has to. To prevent the default mouse behavior, CodeMirror must `preventDefault` `mousedown` events, which will prevent `"click"` from happening. Listen to `mousedown` or `mouseup` instead.

**Comment by hankduan** [comment]
Thanks for the quick response! Can you provide a little more detail regarding why "it has to"? i.e. what behavior is it trying to prevent?

**Comment by marijnh** [comment]
We don't want clicking to steal focus from the hidden textarea, and we don't want dragging to create a DOM selection.
