### ISSUE TITLE
Feature requests for dart mode

### ISSUE THREAD

**Issue by kasperpeulen** [codemirror/CodeMirror#3146]
There are a couple of features that could be added to the dart mode. Some time ago, I tried to add those features to code mirror, just by copying the groovy mode and making some minor adjustments. <strike>You can see that here: http://kasperpeulen.github.io/dart-pad/</strike>

If I'm done with my exams, I will try write up a pull request, but I thought about already filing the issue here. Here are the features that I would like to see in code mirror:

* Like in groovy, the code inside `${<code>}` shouldn't be styled as as string.
* properties and methods should be styled as `cm-property`
* documentation (/// or /\*\*) and comments (// or /\*) to be styled differently

It would be nice to in general have features that javascript has, such as the automatic insert of // when pressing enter in a comment.

**Comment by Scorpiion** [comment]
@kasperpeulen sounds like a great features :+1:

**Comment by Scorpiion** [comment]
Any specific reason for closing this issue @marijnh?

**Comment by marijnh** [comment]
I don't really take feature requests, so until something happens on this front, I don't want this cluttering up the bug list.

**Comment by Scorpiion** [comment]
Got it, I can understand that, good to clean up the list every once in a while. 

Pull requests are welcome but you want to keep the issue list as clean as possible, that's cool, keep up the good work! :+1:
