### ISSUE TITLE
Indentation looks incorrect on the <tr> tag

### ISSUE THREAD

**Issue by AJDBenner** [codemirror/CodeMirror#3147]
When you make the `<tr>` tag within a table, the auto indentation seems to be incorrect when you hit enter to move the `</tr>` tag to the next line. Here's what I mean.

![demo](https://cloud.githubusercontent.com/assets/9154982/6781513/9975c66a-d144-11e4-88a9-132416f09cb8.gif)

**Comment by marijnh** [comment]
I can't reproduce this in http://codemirror.net/demo/closetag.html

**Comment by AJDBenner** [comment]
Seems to be working perfect using that demo, sorry about that
