### ISSUE TITLE
How to manage full line readOnly textMarkers ?

### ISSUE THREAD

**Issue by petitben** [codemirror/CodeMirror#3149]
Hi,

I'm facing a problem with automatic text visual replacement. 
I'd like to replace automatically some content with readOnly and non removable widgets while keeping the correct line numbers (for backend sync purpose) but it looks like a bit tricky as the textmarker implementation is designed for inline widget purpose.

I could use line widgets but I will loose the original number of lines in the code.

I tried to mix empty readonly left and right inclusive textMarkers with line widgets but there is still a problem as the textMarker produce an empty span (Markedspan ?) I'd like to remove because:

* keyboard navigation is then strange (you must press two times on the Left key for instance)
* content deletion may put the cursor after the marker without any possibilities to go back or put the cursor before it

Could you give me some hints how I can implement this kind of functionality ?

Thanks in avance!

**Comment by marijnh** [comment]
Please move requests for help over to http://discuss.codemirror.net , and include a jsbin/jsfiddle link that shows what you are currently doing along with a clearer description of what you are _trying_ to do.

**Comment by petitben** [comment]
Sorry didn't notice the presence of the forum...
