### ISSUE TITLE
CodeMirror in a separate window

### ISSUE THREAD

**Issue by ngn** [codemirror/CodeMirror#3156]
I wish I could use CodeMirror in a popup, like this:
```js
var w = open('', '_blank', 'width=800,height=500'),
    place = w.document.body,
    cm = CodeMirror(place);
```
However it always looks up `document` from the current window.  How feasible would it be to refactor CodeMirror so it uses `place.ownerDocument` for all DOM manipulation?

**Comment by marijnh** [comment]
This would be good to have, but somewhat involved to do. All references to `window` and `document` would have to be modified to point at the editor instance's window and document. And the addons that build nodes or register window-wide event listeners would also have to be updated.

**Comment by ngn** [comment]
Thanks.  So, for the time being I'll stick with loading the `.js` in the popup window so it gets the right `window` and `document`.
