### ISSUE TITLE
5.1 specialchars catching tabs and spaces

### ISSUE THREAD

**Issue by tablatronix** [codemirror/CodeMirror#3161]
Is this expected behavior?

All my tabs and spaces are being matched by specialchars and getting invalidchar instead of cm-tab etc.

**Comment by marijnh** [comment]
No, obviously not, as it doesn't happen in any of the demos. What options are you passing?

**Comment by tablatronix** [comment]
Thanks, I will test options and plugins, and try to narrow it down.

**Comment by tablatronix** [comment]
Well this is only occuring on the minified code, from your minification helper, so probably an uglifyjs issue.

I have not tested further, my node is not working properly...

**Comment by tablatronix** [comment]
I think its something in my dev or build or svn clobbering the actual tab characters in the source.
The minified code seems to have tabs as actual tabschars. `l+="	"` , shrug.

**Comment by marijnh** [comment]
Okay, I'm closing this then.

**Comment by tablatronix** [comment]
I am considering this a uglify bug, although it could be a config option also on the minifier. I would not expect tabs to be present in escaped strings, probably not the best practice, maybe there is a config option that is causing this, changing "\t" into "TAB"

**Comment by jonty-comp** [comment]
I minified codemirror + css.js + javascript.js + xml.js + htmlmixed.js and I get this issue.  It doesn't happen if I omit xml.js.  My tabs are tooltipped as \u9 and spaces as \u20.  

If I cut and paste all the above files into an unminified JS file, then it works fine with my database-driven fields. Therefore, I can only assume that xml.js is being minified incorrectly somehow!

**Comment by tablatronix** [comment]
Thanks, I meant to look into this again.
jscompress.com also uses uglify.js so I wonder if this is a known issue with uglify.
Not sure if I ever checked it, looks similar to this 
https://github.com/mishoo/UglifyJS2/issues/54
