### ISSUE TITLE
How to prevent multiple characters being inserted when typing on multiple selections?

### ISSUE THREAD

**Issue by baoshan** [codemirror/CodeMirror#3163]
Provide a code editor simulates a web form.
![screen shot 2015-03-30 at 6 36 53 pm](https://cloud.githubusercontent.com/assets/1096182/6894831/0a7a585e-d70c-11e4-86e9-b64d92804691.png)

The labels remain intact although they're part of the source. The user is only able to edit content after the colon, include selecting content:

![screen shot 2015-03-30 at 6 40 47 pm](https://cloud.githubusercontent.com/assets/1096182/6894854/4ed21f82-d70c-11e4-9857-3f33f2ad32df.png)

The part right to the vertical colon line looks like a stand alone document.

When type something while multiple lines are selected, the typed character was inserted to all lines.

![screen shot 2015-03-30 at 6 42 50 pm](https://cloud.githubusercontent.com/assets/1096182/6894880/991e3684-d70c-11e4-8ad9-4ecb1a1b2fc7.png)

Is there's a recommended way to prevent multiple characters being inserted in my use case?

**Comment by marijnh** [comment]
Inserting multiple characters is what multiple selections do. I would say this is simply not an appropriate situation to use multiple selections. You might be able to use a `"beforeChange"` event handler that filters changes in the way you want them to behave, but core CodeMirror is doing exactly what it should here, and isn't going to add support for this.
