### ISSUE TITLE
Asynchronous Hinting Racing Observed

### ISSUE THREAD

**Issue by baoshan** [codemirror/CodeMirror#3166]
I noticed when the phrase to be completed has some whitespaces in it, the auto hint widget will not show at each whitespace.

![auto](https://cloud.githubusercontent.com/assets/1096182/6912545/6b0388c8-d7a5-11e4-9b8d-97c6d23d6a7a.gif)

After type `EMI`, the hint showed, but when type the next whitespace, the hint hides until continue typing a non-whitespace char.

**Comment by baoshan** [comment]
I also noticed the position of the popup widget slightly shifts (horizontally) while I types.

**Comment by marijnh** [comment]
See the `closeCharacters` option to the `showHint` method for the first issue. I've never seen the second issue, you'll have to set up a demo if you want me to look at it (though it is possible that it is some browser quirk for a given font/style situation that I can't help, maybe it's a rounding issue that I can work around).

**Comment by baoshan** [comment]
I screencasted my operation with a dom inspector opened. I can see the `left` of the popup changes from `456.615px` to `456px`.

Please let me know if I should setup a live version for your convenience.

![ahp](https://cloud.githubusercontent.com/assets/1096182/6917455/4b65911e-d7d7-11e4-8582-bbbc7b6dcf93.gif)

Thanks.

**Comment by marijnh** [comment]
A live version would be useful.

**Comment by baoshan** [comment]
I setup a live version [here](http://521.cloudapp.net:3000).

Try to change the `label` to `ABC Classics` and see if you can catch it.

Thanks.

**Comment by baoshan** [comment]
Forget to mention that happens in Safari, not Chrome, to me.

**Comment by baoshan** [comment]
Another phenomenon I noticed:

When using asynchronous hinting function, type two characters very fast, e.g. `AB`.
The add on doesn't call the hint function the when you press `B` because the 1st call to the hinting function hasn't called back yet. Which will lead to wrong hinting results be shown. (`Apple` in the popup list, while the input text is `AB` indeed)

Please let me know what I missed to implement a correct asynchronous hinting feature.

P.S. Could the add-on handle racing in XHRs and shows only the correct popup list? Or XHR racing should be handled by myself?

**Comment by marijnh** [comment]
Could you retry that latest issue with the current git master branch? I believe I fixed it a few days ago.

**Comment by baoshan** [comment]
I diffed `https://raw.githubusercontent.com/codemirror/CodeMirror/master/addon/hint/show-hint.js` and `http://521.cloudapp.net:3000/css/addon/hint/show-hint.js`. They're the same file.

**Comment by baoshan** [comment]
Please let me know if my demo can reproduce the racing issue on your machine.

**Comment by marijnh** [comment]
You have not linked to any actual demo, as far as I can see.

**Comment by baoshan** [comment]
I provided the demo at http://521.cloudapp.net:3000. Please let me know if you can't browse it.

**Comment by baoshan** [comment]
In case you're interested in the implementation. I stripped down the relative code as:

```
        cm.on('inputRead', function() {
            if (cm.state.completionActive) {
                return;
            }
            var hint = function(cm, callback) {
                var from = get_from();
                var to = get_to();
                var uri = get_uri(); // Some calculations here.
                var req = new XMLHttpRequest();
                req.onload = function() {
                    return callback({
                        from: from,
                        to: to,
                        list: JSON.parse(req.responseText)
                    });
                };
                req.open('GET', uri);
                return req.send();
            };
            hint.async = true;
            return cm.showHint({
                hint: hint,
                completeSingle: false,
                closeCharacters: /$./
            });
        });
```

**Comment by marijnh** [comment]
This does indeed seem to be Safari-only -- I can't get it to happen on any other browser. I'm Mac-less at the moment, since my old MacBook died, but there should be a new one on the way, and I'll test when it arrives.

**Comment by baoshan** [comment]
Sounds great! :)

**Comment by marijnh** [comment]
I have a mac now, but the demo is offline. I tried to see the pixel-shifting issue in the [completion demo](http://codemirror.net/demo/complete.html) but could not get it to show up.

**Comment by baoshan** [comment]
Congratulations for the new mac. I have restored the [demo](http://521.cloudapp.net:3000).

Thanks.

**Comment by marijnh** [comment]
Thanks for putting the demo back up. Unfortunately, if I follow the steps you describe, the pop-up widget stays in place perfectly still, and the DOM view of the developer tools shows it receiving the exact same pixel offset every time.

I suspect that in some (obscure) circumstances, Safari's font measurements are slightly different for 'after A when A is the last letter on the line' and 'after A with more text following'. It seems unlikely that CodeMirror is going to be able to work around that anyway, since it is dependent on what the browser tells it about text positions.

**Comment by baoshan** [comment]
I agree with you that any treatment like rounding to a nearest integer is somewhat hacky.

Have you find a way to prevent racing? Thanks.

**Comment by marijnh** [comment]
So now we're talking about three different problems in a single issue report. It would help, next time, to open new issues for different problems, so that the discussion can stay somewhat focused.

Again, several race conditions were recently fixed in show-hint.js. If the current git code still shows the problem, please open a new issue with a clear description of what happens.

**Comment by baoshan** [comment]
So we mainly talk about size measuring on this thread. I changed the title accordingly.
