### ISSUE TITLE
Late enabling of dragDrop option doesn't work

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3167]
(adobe/brackets#10812)

1. Go to http://marcelgerber.github.io/github/demo/codemirror/dragdrop-change.html and follow the steps

The editor is loaded with `dragDrop: false` and the button calls `editor.setOption("dragDrop", true)`.

Result:
![image](https://cloud.githubusercontent.com/assets/2641501/6915989/f5998b20-d798-11e4-9bbb-0dd445eb281d.png)
(on Windows).

On Mac, apparently nothing happens.

Using Chrome 41 (on Windows 8.1, in my case).

**Comment by marijnh** [comment]
Attached patch should fix this. Can you let me know whether it works for you?

**Comment by MarcelGerber** [comment]
Yeah, works fine, thanks!
Closing.
