### ISSUE TITLE
Test vim_dw_unicode_word is failing on Firefox 36

### ISSUE THREAD

**Issue by marijnh** [codemirror/CodeMirror#3168]
(And possibly also on other versions -- I only tested 36.)

Passes on Chrome.

@mightyguava Do you have an idea what happens? I am, as usual, having a hard time figuring out what the test is supposed to test.

**Comment by nightwing** [comment]
This is caused by `toUpperCase` function behaving differently on chrome and firefox.

The `և` (`\u0587`) character is a word character, but it doesn't have uppercase and is written as two characters at the start of the word (`Եվ` or `ԵՒ`). toUpperCase returns  `ԵՒ` on Chrome and `և` on firefox.

**Comment by marijnh** [comment]
I see. Can we reword the test so that it isn't sensitive to this platform-specific behavior?

**Comment by nightwing** [comment]
Technically not recognising `\u0587` as a word character is a bug and correct solution would be to add  it to `nonASCIISingleCaseWordChar` regex, but since it's unlikely to affect many people, just replacing it in the test with any other word character is fine too.
