### ISSUE TITLE
Ctrl-X without selection kills a line

### ISSUE THREAD

**Issue by aslushnikov** [codemirror/CodeMirror#3169]
Repro:
1. goto http://codemirror.net/demo/complete.html
2. put cursor in the first line
3. hit `Ctrl-X`

**Actual**: the line gets deleted.
**Expected**: nothing happens - there's no such shortcut in the CodeMirror.

**Comment by marijnh** [comment]
Ctrl-X is your browser's *cut* shortcut, and CodeMirror will do a line-wise cut when nothing is selected. This is  by design, though if it is causing problems for you I can add an option that turns line-wise copy/cut off.

**Comment by aslushnikov** [comment]
An option would be great, thank you.
