### ISSUE TITLE
Can't backspace in Sublime mode

### ISSUE THREAD

**Issue by JasinYip** [codemirror/CodeMirror#3170]
I was updated CodeMirror(v5.1) on my website. But when I checkout to Sublime mode, I cannot delete a blank line by pressing Backspace Key but Shift+Backspace. Is it a bug or something wrong I did?

**Comment by marijnh** [comment]
This is a recent regression -- a 'smart backspace' that consumes blocks of indentation in one keypress was added, but it contains a bug that makes it not work at the start of line. Attached patch fixes this.

**Comment by JasinYip** [comment]
We're using bower and waiting for this fix to be included in the next release. Would you mind to cut a bugfix release?  Thanks :smile:

**Comment by marijnh** [comment]
I don't think this is big enough to warrant another release, but you can monkey-patch the problem away by including a line like this until the next release/upgrade:

    CodeMirror.keyMap.sublime.Backspace = null

**Comment by vincentwoo** [comment]
Whoops, sorry about this one. My bad.
