### ISSUE TITLE
Selecting particular BiDi string with mouse hangs the browser

### ISSUE THREAD

**Issue by markrian** [codemirror/CodeMirror#3172]
The original string that caused this issue is:

يتم السحب في 05 فبراير 2014

If you put that in CodeMirror (e.g. the one at codemirror.net) and try to select the line by clicking and dragging from the right to the left, the browser will hang. Selecting the text via the keyboard works as expected, though.

A minimal string to repro this issue:

ر2

Tested in Chrome, Firefox and IE. All hang.

**Comment by marijnh** [comment]
Indeed, the bidi code got confused by the fact that a level-2 (number-inside-rtl) span of text ended up at the start of the line. Attached patch should help.
