### ISSUE TITLE
Please allow specifying maxMatches as an option to the find matches addon

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3175]
Currently MAX_MATCHES is set to 1000, while we'd like to change it to be higher to match the limit in our find/replace bar implementation.

**Comment by marijnh** [comment]
The option is added to `showMatchesOnScrollbar` in 4fb97fee8745bfc4a. Does that work for you, or do you want to be able to configure the built-in search addon to pass a given value?

**Comment by mtaran-google** [comment]
This should solve our issue, thanks for the quick response! :)
