### ISSUE TITLE
Javascript mode indentation bug

### ISSUE THREAD

**Issue by SN4T14** [codemirror/CodeMirror#3180]
I was writing some JS code in Brackets when I noticed that if a function gets called with the string "=>" as any argument other than the first one, any new lines you create after that get indented too far:

```javascript
console.log(asdf, "->");
// This line gets indented this far
console.log(asdf, "=>");
			// This line gets indented this far
```

A friend of mine told me that Brackets indentation bugs should be filed with CodeMirror, which is why I'm not filing this issue with Brackets.

**Comment by marijnh** [comment]
I believe I already fixed this in 27fe44c3cb75ab (and indeed, I can no longer reproduce this problem).
