### ISSUE TITLE
Smarty in HTML attributes breaks highlighting

### ISSUE THREAD

**Issue by marcguyer** [codemirror/CodeMirror#3186]
I suspect a regression of #1768 in the shiny new smarty mode. Here's a basic example:

![screen shot 2015-04-07 at 4 12 55 pm](https://cloud.githubusercontent.com/assets/35496/7032824/69605ebc-dd43-11e4-8872-b965757a432f.png)

**Comment by marijnh** [comment]
Does the attached patch solve the problem for you?

**Comment by marcguyer** [comment]
That works for me. Thanks.
