### ISSUE TITLE
Trigger event on electric char

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3188]
In Brackets, we'd love to react to electric chars in order to remove possible trailing whitespace (for more background, see adobe/brackets#8395 and [the code that currently handles the common chars \]{})](https://github.com/adobe/brackets/blob/97ed87bb8597a859c3fd3def860cc1a97d1bb4bf/src/editor/Editor.js#L436-L454)), but unfortunately, there's no way to do so right now.
I suggest CodeMirror should fire an event (like `electricCharIndent`) in such cases. Any objections?

**Comment by marijnh** [comment]
Sounds useful. Implemented in attached patch.
