### ISSUE TITLE
async completion widget is sometimes later shown than it is closed

### ISSUE THREAD

**Issue by kasperpeulen** [codemirror/CodeMirror#3189]
I think this picture illustrates the problem quite well:

![](https://camo.githubusercontent.com/fd253e7874dd36defff5e6f7bb3949ef53c4923b/687474703a2f2f672e7265636f726469742e636f2f756252645478754244652e676966)

I tried to analyse the problem a little bit, and I think the following is going on:

1) The completion is started when I press `i`.
2) When I press `;` the completion widget is not yet inserted. Which means that this eventListener is also not loaded: `this.cm.on("cursorActivity", activity);`. Normally the `activity` functions check is the widget has to be removed on user activity.
3) Now somewhat later the widget is inserted, and the event listener is added. But `;` is already pressed, and the event listener didn't catch that.

I guess a solution could be to register a event listener for cursorActivity already before the widget is inserted, and then if (widget == null), it could check similarly as in the activity function if the completion popup has to be cancelled.

**Comment by marijnh** [comment]
That's a good point. Could you see whether patch 0a83a4b solves the issue for you?

**Comment by kasperpeulen** [comment]
@marijnh thanks, that patch solves it for me :)

**Comment by tophf** [comment]
0a83a4b broke `completeSingle: true`.

**Comment by marijnh** [comment]
Oops, I routed all calls around the method that was supposed to handle that and did not notice. Attached patch should fix this.
