### ISSUE TITLE
[JavaScript mode] The "=+" statement determined as a single "operator" token

### ISSUE THREAD

**Issue by aslushnikov** [codemirror/CodeMirror#3203]
Steps:

1. Goto http://codemirror.net/demo/complete.html
2. Delete everything; paste the following code: `c=+a`

3. Inspect rendered highlight

**Actual**:
The `=+` is reported as a single "operator" token

**Expected**:
There should be two separate tokens.

The issue makes it hard to use `runMode` plugin for code tokenization.

**Comment by marijnh** [comment]
If you want _serious_, correct tokenization, you'll run into many other problems if you try to use the JavaScript mode (or any CodeMirror mode). Have you considered simply pulling in Acorn or so, which has a well-tested, mature tokenizer?

**Comment by aslushnikov** [comment]
I'll play with it. Though I was initially under impression that `Acorn` is somewhat less maintained:
1. In a [blogpost](http://marijnhaverbeke.nl/blog/acorn.html), you claim to set up a [project page](http://marijnhaverbeke.nl/blog/acorn.html), but it seems to go down
2. In that same blogpost, there's a [link on benchmark](http://marijnhaverbeke.nl/acorn/test/bench.html) which is also down
3. On [esprima comparison](http://esprima.org/test/compare.html) page, the Acorn seems to be broken 

What's your goal regarding codemirror modes correctness? We rely on them heavily in devtools front-end.

**Comment by marijnh** [comment]
The [github page](https://github.com/marijnh/acorn) is the project page now. I'll update those links. The Esprima page is broken because they blindly upgraded to 1.0. The project is very much alive (see the commit history) and recently saw a lot of improvement (ES6, extensibility, 1.0 release).
