### ISSUE TITLE
setSize seemingly doesn't work

### ISSUE THREAD

**Issue by JasonBarnabe** [codemirror/CodeMirror#3206]
Go to http://codemirror.net/index.html, fire up the browser dev tools, run

```js
editor.setSize({width: 1000, height: 1000});
```

and nothing happens. No error either.

**Comment by marijnh** [comment]
You're passing it the wrong kind of arguments (it expects two separate values). See the [manual](http://codemirror.net/doc/manual.html#setSize)

**Comment by JasonBarnabe** [comment]
Ah, I was reading the manual and I thought that's what it was telling me to do. Thanks.

**Comment by satyapendem** [comment]
use editor.setSize(1000,1000);
