### ISSUE TITLE
Inconsistent keybindings for goDocStart/goDocEnd

### ISSUE THREAD

**Issue by petetnt** [codemirror/CodeMirror#3207]
The docs state that:

>
goDocStart *Ctrl-Up (PC), Cmd-Up (Mac), Cmd-Home (Mac)*
Move the cursor to the start of the document.
 
> goDocEnd *Ctrl-Down (PC), Cmd-End (Mac), Cmd-Down (Mac)*
Move the cursor to the end of the document.

When the PC keybindings for `doDocStart` and `doDocEnd` are `Ctrl+Home` and `Ctrl+End` respectively (while `Ctrl-Up` and `Ctrl-Down` are `goLineUp` and `goLineUp`, same as `Up` and `Down`, while the Mac defaults to `doDocStart` and `doDocEnd`)

First I though that was just a documentation issue, but it seems like it's wrong in the docs and the keybindings itself?

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch fixes the docs.

**Comment by petetnt** [comment]
@marijnh should the keybindings for `Ctrl-Up` and `Ctrl-down` be consistent between the PC and MAC keybindings too? The current PC bindings for those on PC serve no purpose what-so-ever.

Otherwise thanks :+1:

**Comment by marijnh** [comment]
No, I try to follow existing conventions on each platform, and consistency between them is not a goal. Having ctrl-up/down behave like plain up/down is common behavior on the PC

**Comment by petetnt** [comment]
Ah okay, that's what I though.
