### ISSUE TITLE
CodeMirror() replaces textarea (accidently?)

### ISSUE THREAD

**Issue by WulleBulle** [codemirror/CodeMirror#3209]
Hi there

thanks for this outstanding tool.

I am initiating my CodeMirror editor

    var myCodeMirror = CodeMirror.fromTextArea(myTextArea);

while "myTextArea" is the <textarea> object. Unfortunately this replaces the textarea so it is gone and can't be accessed by other parts of my application.

The documentation reads:

This will, among other things, ensure that the textarea's value is updated with the editor's contents when the form (if it is part of a form) is submitted. See the API reference for a full description of this method.

So I think there my be an issue. Or did I miss something?
What I want to do is to change a textarea with its content (some css) into an CM editor accessible for other parts of my application.

Thanks in advance

**Comment by marijnh** [comment]
This is what `fromTextArea` does: it hides the textarea, so and displays a CodeMirror instance in its place.

**Comment by WulleBulle** [comment]
Thank u for answering. The textarea isn't hidden. It's completly gone. So other parts of my application can't access its content. Is there any other way to get the content?

**Comment by WulleBulle** [comment]
Please forget about my comment. It was a code error. Me stupid. Thank you very much again.
