### ISSUE TITLE
doc.getModeAt is not available from the doc object

### ISSUE THREAD

**Issue by kasperpeulen** [codemirror/CodeMirror#3214]
From the documentation:
> doc.getModeAt(pos: {line, ch}) → object
>Gets the inner mode at a given position. This will return the same as getMode for simple modes, but will >return an inner mode for nesting modes (such as htmlmixed).

However it seems like that this method is only available from the codemirror object and not from the doc object.

**Comment by marijnh** [comment]
The manual was wrong here, and attached patch fixes that. Documents without editors attached to them do not do highlighting, which is needed to get token state, which, in turn, is needed to find the local mode at a given position.
