### ISSUE TITLE
Search dialog covers the underlying line at the top of editor.

### ISSUE THREAD

**Issue by amshali** [codemirror/CodeMirror#3221]
Search dialog covers the underlying line at the top of editor. This is particularly an issue when that line contains the string that you just searched. Is there anyway we can fix this? Any ideas? Thank you.

**Comment by marijnh** [comment]
Doesn't the dialog disappear when you search, so that it can not cover something you 'searched' only something that you are 'going to search'?

**Comment by stonefly** [comment]
the dialog will not disappear if it's in 'replace' mode, thus if the 1st line contains a matching it will never appear, i think amshali was right here
