### ISSUE TITLE
Gutter seems unaligned in >5.0.0

### ISSUE THREAD

**Issue by flehoux** [codemirror/CodeMirror#3228]
The gutter seems unaligned in our project. We pretty much only modified the color attributes.

![screen shot 2015-04-30 at 4 40 42 pm](https://cloud.githubusercontent.com/assets/2939798/7422063/b46e942a-ef57-11e4-9f39-3f9a18bc742c.png)

V4.3.0 used to add these 2 attributes to .CodeMirror-gutter-wrapper:
position: absolute;
left: -28px;

V5.0.0+ no longer does. I found out that I could reposition it by adding position: relative to .CodeMirror-gutter-wrapper

Is anyone else experiencing this?

**Comment by marijnh** [comment]
This is not happening in the demos. It is likely to be a CSS conflict or other CSS issue. Can you try and reduce your setup to the minimum HTML/CSS needed to cause this problem?

**Comment by flehoux** [comment]
My bad, app wasn't fetching latest .css file from node_modules. Who know which css version we we're running with^^
