### ISSUE TITLE
Bug in auto indentation of PHP code with Closebrackets

### ISSUE THREAD

**Issue by parisk** [codemirror/CodeMirror#3233]
It seems that automatic indentation of PHP code fails in a specific case when Closebrackets addon is enabled.

Attempting to put the brackets after a class/function definition in the line below the function/class name indents them one level inner than it should.

## Example
This is what is expected at first, when typing normally

```php
<?php
function someFunction ()
{}
?>
```

This is what you get

```php
<?php
function someFunction ()
  {}
?>
```

This bug is not present in JavaScript + Closebrackets mode (which uses C-like syntax as well), neither on PHP mode alone (indents properly the `{` symbol after typed).

This makes me pretty confident that the issue is in the combination of PHP mode with smart indentation enabled + Closebrackets addon.

I have set up a page to quickly test Closebrackets with PHP at https://codemirror-paris.apps.lair.io/demo/closebrackets-php.html.

**Comment by marijnh** [comment]
Good catch. Attached patch should help.
