### ISSUE TITLE
Unable to load modes

### ISSUE THREAD

**Issue by oscarotero** [codemirror/CodeMirror#3234]
Hi. I've spend a lot of time trying to load modes dinamically using requirejs but I cannot make it work.

I have this code:
```js
define([
	'jquery',
	'require'
], function ($, require) {
	var module = {
		init: function ($element) {
			var modename = $element.data('mode') || 'htmlmixed';

			require([
				'./bower_components/codemirror',
				'./bower_components/codemirror/mode/' + modename + '/' + modename
			], function (codemirror) {
				var editor = codemirror.fromTextArea($element.find('textarea').get(0), {
					lineNumbers: true,
					mode: modename
				});
				console.log(editor.getMode().name);
			});
		}
	};

	return module;
});
```
The `console.log` always returns `"null"`. I've tried putting `editor.setOption("mode", "javascript");` after instantiation but it keeps not working. Requirejs loads codemirror and the mode correctly, but for any reason the mode is not initialized. Maybe I'm doing something wrong? I've tried to [follow the manual](http://codemirror.net/doc/manual.html#overview).

Thank you very much for this great library :smile:

**Comment by oscarotero** [comment]
Well, I've found the issue.
Seems that there is a conflict on configure the path of codemirror in requirejs and the mode scripts, and this causes that codemirror is loaded two times. 

```js
require.config({
	paths: {
		"codemirror": "../bower_components/codemirror/lib/codemirror"
	}
});

require(['codemirror', '../bower_components/codemirror/mode/htmlmixed'], function (codemirror) {
    //this instance of codemirror is not the same than the one loaded by htmlmixed.
});
```
I don't know if it's an issue of codemirror or requirejs (I've found some issues related with relative urls, for example https://github.com/jrburke/requirejs/pull/1263)

**Comment by marijnh** [comment]
People have run into this before. It looks very dumb behavior on the part of requirejs, but I don't have enough experience with that library to really comment on what it is thinking. In any case, this isn't something CodeMirror itself can fix.

**Comment by oscarotero** [comment]
I think it can fixed loading the codemirror as a module id, instead relative path. This is something that do all jquery plugins, for example: https://github.com/MiniPlugins/minitabs/blob/master/src/minitabs.js#L10

So, in this code: https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js#L10

a possible solution should be:
```javascript
(function(mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
    mod(require("codemirror"));
  else if (typeof define == "function" && define.amd) // AMD
    define(["codemirror"], mod);
  else // Plain browser env
    mod(CodeMirror);
})(...)
```

So the user only have to define the path of codemirror module.

**Comment by marijnh** [comment]
I don't want to do this, though. It requires every user to add a definition, which shouldn't be necessary.

**Comment by oscarotero** [comment]
Yes, I'm agree it's not a perfect solution :smiley: . I hope requirejs fixes this soon.
Thanks anyway.

**Comment by oscarotero** [comment]
Hi again. I finally resolved this issue in a more elegant way. Requirejs has a package config for this things. More info here: https://github.com/jrburke/requirejs/issues/1345#issuecomment-105609735
It should be great add this to the documentation.

**Comment by marijnh** [comment]
I can't say I really understand the issue and the solution here. @oscarotero Would you mind suggesting a formulation for the docs that you feel would be helpful?

**Comment by oscarotero** [comment]
Currently in the documentation there is this code:
```js
require([
    "cm/lib/codemirror",
    "cm/mode/htmlmixed/htmlmixed"
], function(CodeMirror) {
    CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        mode: "htmlmixed"
    });
});
```
This works fine in cases where codemirror is placed in the same folder than the main js file (in this case, in "cm" subdirectory).
If it's placed outside, for example in bower_components, the path to use must be relative:
```js
require([
    "../bower_components/codemirror/lib/codemirror",
    "../bower_components/codemirror/mode/htmlmixed/htmlmixed"
], function(CodeMirror) {
    CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        mode: "htmlmixed"
    });
});
```
The problems begin when we need configure the location of the used modules. Requirejs has "paths" config for individual cases, but for packages like codemirror, there is the "packages" config:

```js
require.config({
    packages: [{
        name: "codemirror",
        location: "../bower_components/codemirror",
        main: "lib/codemirror"
    }]
});
```

Now we don't have to put the full url, just the package name:
```js
require([
    "codemirror",
    "codemirror/mode/htmlmixed/htmlmixed"
], function(CodeMirror) {
    CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        mode: "htmlmixed"
    });
});
```

And this works fine in all cases, so I think this is the better way to use it. I'll put the packages config example in the documentation as the best way to use it with requirejs.

**Comment by marijnh** [comment]
So the important thing is to us `packages`, not `paths` to configure CodeMirror?

**Comment by oscarotero** [comment]
yes, exactly :)
