### ISSUE TITLE
.getLineNumber() in mode

### ISSUE THREAD

**Issue by scottyli** [codemirror/CodeMirror#3236]
What's the best way to get line number in mode? I would like to have different highlighting rules based on line number.

```javascript
mode.token = function(stream, state) {
  // lineNumber?
})
```

**Comment by marijnh** [comment]
You can't, and you shouldn't, since highlighting information will be reused if the line moves (through lines being inserted/deleted above it), so you're not highlighting a specific numbered line in the first place.
