### ISSUE TITLE
Vim mode's defineEx()'s documentation says prefix is optional, but it's really not

### ISSUE THREAD

**Issue by theclapp** [codemirror/CodeMirror#3237]
Here is the defineEx function:

      defineEx: function(name, prefix, func){
        if (name.indexOf(prefix) !== 0) {
          throw new Error('(Vim.defineEx) "'+prefix+'" is not a prefix of "'+name+'", command not registered');
        }
        exCommands[name]=func;
        exCommandDispatcher.commandMap_[prefix]={name:name, shortName:prefix, type:'api'};
      },

Nothing in there makes prefix optional.

I guess you want something like

  if (arguments.length == 2) { func = prefix; prefix = name }

at the top.

**Comment by mightyguava** [comment]
Oops. I've made the prefix optional, but you still need to pass in `undefined`.

**Comment by theclapp** [comment]
Thank you for your quick attention to this issue.  I think your solution is suboptimal, at least with respect to the documentation of defineEx():

> defineEx(name: string, ?prefix: string, fn: function(cm: CodeMirror, ?params: object))
> Defines an Ex command, and maps it to :name. If a prefix is provided, it, and any prefixed substring of the name beginning with the prefix can be used to invoke the command.

Everywhere else in the documentation, an optional parameter could just be omitted, not set to undefined.  I think the check of arguments.length that I mentioned earlier would be a better solution.  That said, there certainly may be other constraints of which I am not aware, so certainly please do as you see fit.

I also note that functions in the CM documentation with optional arguments in the middle of the arglist are rare; the few I could find are all in the Vim API.

Thanks again for your time!

**Comment by mightyguava** [comment]
> Everywhere else in the documentation, an optional parameter could just be omitted, not set to undefined. I think the check of arguments.length that I mentioned earlier would be a better solution. That said, there certainly may be other constraints of which I am not aware, so certainly please do as you see fit.

That's not entirely true. If there is more than 1 optional parameter, and you want to set the second optional parameter, the first can't be omitted. You either need to pass in a value or undefined. I very much dislike method overloading in general, and fake overloading by omitting parameters in Javascript kind of just makes me cringe.

That said, the Vim API is a bit poorly designed to that respect. Unfortunately, the methods were added over time and all have existing usages. I only recently managed to document them. I will look into making the API cleaner in the next major release, but for now I can't tweak the order of arguments.

I _can_, however, revert my last commit and instead update the documentation to say that the prefix is required, if you prefer.

**Comment by theclapp** [comment]
> That's not entirely true. If there is more than 1 optional parameter, and you want to set the second optional parameter, the first can't be omitted.

That's a good point, and not one I'd considered.  Sorry about that.

> I only recently managed to document them.

Thank you for doing that, by the way!

> I can, however, revert my last commit and instead update the documentation to say that the prefix is required, if you prefer.

Thank you for the offer.  You're the maintainer, you should do as you think best.  But if you're asking me, and apparently you are :) , I'd say keep your last commit _and_ update the documentation to say you can pass any falsy value (or whatever's actually appropriate; I know in documentation you have to consider all the angles, which might not be apparent to me (like in your point above :)) for the prefix to default it to being the same as the command name.

**Comment by mightyguava** [comment]
That sounds fine too. Updated in fbd336f.

**Comment by theclapp** [comment]
Awesome.  Thanks!
