### ISSUE TITLE
can't scroll to the end of a large file

### ISSUE THREAD

**Issue by ngn** [codemirror/CodeMirror#3240]
First of all: I think the way CodeMirror renders to DOM only the visible part of the text is absolutely fantastic.

I know I'm really pushing limits here but there seems to be a threshold at around 1.5-2 million 
lines beyond which it's impossible to scroll.  Repro: go to https://codemirror.net/mode/markdown/index.html and type in the JS console:
```js
var s = Array(2000000).join('a\n'); // executes almost instantly
editor.setValue(s); // a few seconds, depending on browser
```
Drag the scrollbar all the way down or press ctrl+end: the scrollbar goes to the bottom but the text is far from the last line.  In Chromium it's around line 1.7 million.  In Firefox: 1.9 million and you can't see the scrollbar (well, not unexpectedly).

Any pointers for where I should look in the code to circumvent that limit?

**Comment by marijnh** [comment]
The problem appears to be that Chrome only uses ~25 bits for the height of an element. I assume a similar issue exists in Firefox. If I inspect the `.display.sizer` element after running your example code, I see an element with `min-height: 38000008px`, yet if I get its `clientHeight`, it says 33554428 (which is 2^25 - 4). The scrollbar height is based on this reported element height, but it seems that in general the browser refuses to scroll the wrapping div any further (manually adding to its `scrollTop` has no effect).

So you seem to be reaching a limitation in browsers, not in CodeMirror, here. We could work around it by doing a lot more scroll-related work in our own code, but I am not really interested in doing that right now (I'm relying on native scrolling to keep wheel scrolling smooth, and changing that would create all kinds of new issues).

I'm closing this as 'can't cleanly fix'. If you feel it is very important, try bugging browser vendors to lift their height limitations.

**Comment by ngn** [comment]
Initially I thought this would be due to some arbitrarily set constant in CodeMirror.  25 bits in the browser - that's an interesting insight.  Thank you.
