### ISSUE TITLE
Right clicking inside CodeMirror instance causes textarea to show from then on

### ISSUE THREAD

**Issue by yelvert** [codemirror/CodeMirror#3241]
This happens only in chrome and only in certain circumstances that I haven't been able to narrow down yet. When I right click my CodeMirror instance the hidden textarea shows up and never goes away.
![image](https://cloud.githubusercontent.com/assets/7054/7499712/040c3924-f3ef-11e4-9f92-bfec833ffa61.png)

It is caused by setting `position: fixed` here https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L1464, but removing the `position: fixed` from that cssText causes the context-menu to not have copy/cut/paste https://github.com/codemirror/CodeMirror/issues/3238

**Comment by yelvert** [comment]
It seems like Chrome doesn't respect the `position: absolute` when it gets changed back in the rehide function.

**Comment by yelvert** [comment]
I have added `opacity: 0` to the textarea and everything seems to work. Anyone know of any issues it might could cause?

**Comment by marijnh** [comment]
So after putting back the `cssText` (which presumably contains a `position: absolute`) the element's `.style.position` is still `"fixed"`? I don't want to sweep the bug under the rug with an `opacity: 0`, I'd rather figure out what is going wrong and how we can work around it. Is there any way I can reproduce the issue?

**Comment by yelvert** [comment]
I haven't been able to figure out what causes this bug to manifest. I can tell you that where this bug shows up for me, that the screen shot above is from, is deeply nested inside several absolute positioned elements several of which are animated. I can actually cause this bug just by setting the textarea's position to fixed, then changing it back to absolute, with 0 right clicks.

**Comment by marijnh** [comment]
Interesting. If you can submit a (minimal) test HTML page that allows me to reproduce this, that would be useful.

**Comment by jerivemo** [comment]
Hi, I have the same problem!! Any have a good solution!!!

**Comment by marijnh** [comment]
Closing until a test case shows up.

**Comment by chrisyip** [comment]
Same issue here, we're using CodeMirror with [ui-codemirror](https://github.com/angular-ui/ui-codemirror).

Don't know how to reproduce, but will submit a test HTML when I can reproduce it.
