### ISSUE TITLE
HTML comments in CSS mode

### ISSUE THREAD

**Issue by ilkkao** [codemirror/CodeMirror#3244]
![image](https://cloud.githubusercontent.com/assets/474587/7512685/eaeb3e20-f4ae-11e4-8169-91e74cbeacef.png)

Not sure if this is a bug or not but CSS mode shows HMTL comment with the same color as CSS comments which incorrectly indicates that HTML comments are allowed in CSS files.

**Comment by marijnh** [comment]
Some git digging shows that this is a holdover from CodeMirror 1's CSS mode, repeatedly ported forward without rethinking. I've removed it in patch 9d320fd
