### ISSUE TITLE
Please make test page consistent (passed vs succeeded)

### ISSUE THREAD

**Issue by anaran** [codemirror/CodeMirror#3245]
Running http://codemirror.net/test/#verbose,help I get

```
Test Suite

A limited set of programmatic sanity tests for CodeMirror.
Ran 1 tests

All passed (1353 skipped)
```

which suggests searching the page for `passed` might be a good idea.

Not so, because the relevant tests have not `passed`, they have `succeeded`.

The request is to use one of the two terms and stick with it.

...

```
core_helpers
    Test 'core_helpers' succeeded
```

**Comment by anaran** [comment]
Also, failing tests use a noun:

`1 failure`

while the consistency assumption would lead `1 failed`.

The failure, however, is only colour-marked, therefor cannot be searched for by text, e.g.

```
addon_help_commandsHelp
    TypeError: wrap.CodeMirror.commands is undefined (localhost:8000)
```

(that particular failure will be gone later tonight)

**Comment by marijnh** [comment]
Where are you searching? The output of the test runner, unless you broke a bunch of core functionality, should be short enough to not even need text search.

**Comment by anaran** [comment]
See the URL in the very first line of this issue report. And no, I have not been able to break that one yet :-)

I find verbosity and text search important while working on tests on my own branches, either hosted via branch `gh-pages` on github, or better yet via a server on my localhost, like `pushd /var/tmp/CodeMirror/ && python -m SimpleHTTPServer`.

**Comment by marijnh** [comment]
I think I'll make per-editor window configuration part of the next version of the editor, but from the sound of it I don't think I want to merge in your semi-global solution.

**Comment by anaran** [comment]
I don't understand your comment in the context I am reading it in, which is issue #3245.
Are you referring to my help commands prototype, #3249?
Let me know if you're interested in that  help addon functionality, if we can find a way to generalize its integration..

**Comment by marijnh** [comment]
Sorry, I commented in the wrong issue (that was meant for #3251)
