### ISSUE TITLE
[php] Wrong indentation in switch block

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3252]
(adobe/brackets#11067)

1. Go to https://marcelgerber.github.io/github/demo/codemirror/php-switch.html and follow the steps there
2. Notice how the back-indents (it's indented 1 level) when it's meant to be indented 2 levels

I think a behavior like in JS would suit PHP better.

**Comment by marijnh** [comment]
First, there is no 'wrong' indentation here -- there are a whole bunch of styles for indenting c-style `switch`, and thus the indentation isn't 'meant to' be anything. I've had people complain about the indentation in the JS mode as well, and had to add an option to disable it.

But yeah, having the same default behavior in the clike and javascript mode seems like a good idea. Attached patch adds it. Please test.

**Comment by MarcelGerber** [comment]
Thanks. Works great!

**Comment by cithukyaw** [comment]
There is another proof of this with HTML in a Ruby file. As I said in [the referenced issue](https://github.com/adobe/brackets/issues/11067#issuecomment-100213457), back-indents are happening not only in `switch`.

![code-indentation-glitch-14-05-2015-06-40-38](https://cloud.githubusercontent.com/assets/4285555/7631803/c95102fe-fa6c-11e4-98da-bf3e6f3d63dd.gif)

You might notice that the first paste of the line 29 and 30 is no problem, but the line 31 to 34 got the problem of auto back-indents.

**Comment by marijnh** [comment]
@cithukyaw How is that in any way related to the issue you are replying to?
