### ISSUE TITLE
Alt+F, Alt+D key bindings interfere with symbols on non-standard keyboard layouts

### ISSUE THREAD

**Issue by tjanson** [codemirror/CodeMirror#3254]
I’m using the German ergonomic keyboard mapping [Neo](http://neo-layout.org/). Under Mac OS and only when using Firefox, CodeMirror text areas intercept `Alt+F` and `Alt+D` key bindings, which in my layout are the characters `&` and `:`. I.e., in Chrome and Safari, `&` and `:` are inserted correctly; in Firefox, the key bindings "jump word right" / "delete word right" are triggered and the symbol is not inserted.

If this is an upstream issue (that is, bad behaviour on Firefox’s part), let me know, but I think it might be caused by the way you intercept keyboard presses (because to my knowledge this only happens with CodeMirror).

**Comment by marijnh** [comment]
CodeMirror can not detect your system's keymapping, so all it can do is take the default text editing keybindings for your platform, and bind similar functionality to them by capturing browser events. There is not really much we can do about this issue (apart from not binding any keys, which would make the editor rather horrible to use). But the good news is that keybindings are entirely customizeable, so if you control the site, you can change them, and if you don't, you can at least create a bookmarklet that changes them (in this case, something like `delete CodeMirror.keyMap.emacsy["Alt-F"]; delete CodeMirror.keyMap.emacsy["Alt-D"]`)

**Comment by tjanson** [comment]
Thanks for the bookmarklet tip!

**Comment by k0nserv** [comment]
I have this problem with Jupyter, is there a way to persist the changes so that they don't have to be redone on load?

**Comment by mercutiodesign** [comment]
@k0nserv Not sure if you're still looking for a solution but I just had the same problem as you. After researching I found out that you can create a jupyter custom.js file in your jupyter custom config location (for me it's at `~/.jupyter/custom/custom.js`).
I also deleted the `Alt-B` key-binding (for the + sign):
```
delete CodeMirror.keyMap.emacsy["Alt-F"]; 
delete CodeMirror.keyMap.emacsy["Alt-D"]; 
delete CodeMirror.keyMap.emacsy["Alt-B"];
```
