### ISSUE TITLE
Code folds uncollapse when selecting over the arrow marker on nested collapses 

### ISSUE THREAD

**Issue by petetnt** [codemirror/CodeMirror#3255]
I reported this as adobe/brackets#11091 but it seems to be an CodeMirror issue as it also behaves so on the [demo](https://codemirror.net/demo/folding.html).

Write some HTML
``` html
<div class="test">
    <p>        
        <span>Test</span>
    </p>
</div>
```

Fold the inner `<p>`

![image](https://cloud.githubusercontent.com/assets/7641760/7582919/63cab066-f89a-11e4-8f46-85398d9558f2.png)

Start selecting text from the beginning or end of line 2 (the collapsed one). The fold uncollapses when mouse hovers over `<->`

**Comment by marijnh** [comment]
This is by design. If you put the cursor in the folded code, the assumption is, you probably want to see what's inside.

The `clearOnEnter` option to `markText` can be used to control this behavior.

**Comment by petetnt** [comment]
@marijnh oh okay, I see. Thanks for the prompt reply and especially for the control option!
