### ISSUE TITLE
CodeMirror.normalizeKeyMap doesn't work

### ISSUE THREAD

**Issue by tophf** [codemirror/CodeMirror#3258]
```js
CodeMirror.normalizeKeyMap({"Ctrl-Shift-F2":"test", "Alt-Ctrl-Shift-F2":"test"})
```

>Object {Ctrl-Shift-F2: "test", Alt-Ctrl-Shift-F2: "test"}

Apparently, it didn't work since [the beginning](https://github.com/codemirror/CodeMirror/commit/b077d68ae1a731f0685f615db1664f3507751079#diff-69ea38ebbc0152fa18e2928063a0f622R4941) because the normalized result was overwritten with the initial `keyName` in last (or the only) iteration.

Fix:

```diff
--- a/lib/codemirror.js
+++ b/lib/codemirror.js
@@ -5720,7 +5720,7 @@
       for (var i = 0; i < keys.length; i++) {
         var val, name;
         if (i == keys.length - 1) {
-          name = keyname;
+          name = keys.join(" ");
           val = value;
         } else {
           name = keys.slice(0, i + 1).join(" ");
```

**Comment by marijnh** [comment]
Thanks for noticing that. Fixed in attached patch.
