### ISSUE TITLE
The Escape key isn't captured by the editor

### ISSUE THREAD

**Issue by rathboma** [codemirror/CodeMirror#3260]
So I enabled auto-complete in our deployment and the natural way for our users to dismiss the auto-complete options is by pressing `escape`, however it seems that pressing that button takes the cursor focus completely out of the input box.

I've added the key to the start-up configuration, but that doesn't seem to help. Eg:

```javascript
      extraKeys: {
        "Ctrl-Space": "autocomplete",
        "Esc": function() {
          // doing stuff here does nothing!
          // I've tried Esc and Escape
        }
```

**Comment by marijnh** [comment]
This does not happen in the demos (at least, not on Chrome), so I suspect it is some other local code you have that is doing this, or it only happens on a specific browser and you didn't give away which one you are using.

**Comment by rathboma** [comment]
Yes I found the suspect, it was vimium

Matthew

please excuse typos - sent from my phone.
