### ISSUE TITLE
How to maintain focus on codemirror text editor

### ISSUE THREAD

**Issue by RichardBansal** [codemirror/CodeMirror#3262]
Just working through a problem.

Code can be found [here](https://github.com/RichardBansal/mide/tree/development/mide/development/features/challenge-code) and a video of the problem: http://recordit.co/ErtX7XG8R5.

Basically something is forcing the keyboard to loose focus, and I am wondering if there is anyway to maintain focus on codemirror after each input is received and updated.

**Comment by marijnh** [comment]
CodeMirror maintains focus unless focus is explicitly moved to some other element. This is probably some Angular magic getting in your way. Feel free to reopen if you have more evidence that the problem is directly CodeMirror-related, but until then, I'm marking this closed.
