### ISSUE TITLE
Allow passing a LineHandle to charCoords

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3264]
Looking at your fix(es) for #3173, I thought it would make sense to allow handing `charCoords` (the public one!) a LineHandle, too.

The private API already has this as a param, and as it can speed performance up in some cases, I wonder if it's a good idea to make it possible here as well?

**Comment by marijnh** [comment]
Did you benchmark? I expect the work of looking up a line handle to be small compared to fetching actual coordinates (but if you're asking for lots of cached coordinates, it might not be). I did a simple benchmark where I couldn't even find a significant improvement from using such an extension.

And doing this isn't free -- it clutters up the API. We wouldn't just have to do it for `charCoords`, but also `cursorCoords`, and probably just about every method that takes a position, for the sake of consistency. That means we have more noise in the docs, and an additional optional parameter for these methods and if we ever come up with another parameter we want to add, it'll have to go after that one. I don't think I'm willing to pay that price unless a serious improvement can be demonstrated.

**Comment by MarcelGerber** [comment]
You're right, it's actually only a very tiny amount of time spent on getting the LineHandle.
I didn't benchmark before, sorry.

Closing.
