### ISSUE TITLE
Cursor is not positioning to correct position

### ISSUE THREAD

**Issue by mato75** [codemirror/CodeMirror#3270]
We have a sort of XML document. When window is resized and user clicks on specific text, cursor is sometimes positioned at the wrong place. After text is changed, the positioning of the cursor with mouse works ok. Is there a conf that has to be added or is this a bug.

lineWrapping is se to true, and because of this, the cursor gets positioned wrong on window resize.

**Comment by marijnh** [comment]
Are you resizing the whole browser window, or using some in-page resizing functionality?

**Comment by mato75** [comment]
No I am resizing a dialog, so textare is also resizing.

**Comment by marijnh** [comment]
Right -- CodeMirror can not detect such resizes (no meaningful events are fired for them), so in cases like this, where your script forces the editor to resize, you should call the [`resize`](http://codemirror.net/doc/manual.html#resize) method on the editor (without arguments) to force it to clear its position caches and re-measure the actual positions of things.

**Comment by mato75** [comment]
thx, it works, awesome.
