### ISSUE TITLE
.scrollTo and .scrollIntoView don't do nothing

### ISSUE THREAD

**Issue by mato75** [codemirror/CodeMirror#3271]
When calling this two functions, nothing happens. I want to scroll the editor by javascript, and I call

      codeMirror.scrollTo({'x': 300}); 

and nothing happens.

**Comment by marijnh** [comment]
Read the [docs](http://codemirror.net/doc/manual.html#scrollTo) and make sure you are actually passing it the parameters it expects.

**Comment by mato75** [comment]
yes just saw it, really sorry for the scrollTo
