### ISSUE TITLE
Selecting words in "contextmenu" handler can make them disappear

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3273]
(adobe/brackets#11142)

Go to http://marcelgerber.github.io/github/demo/codemirror/contextmenu-handler.html and follow the steps. There's a very simple `contextmenu` handler set up:
``` js
$("form").on("contextmenu", function () { // Notice how it's not ".CodeMirror" itself. Dunno if that makes a difference
    var word = editor.findWordAt(editor.getCursor());
    editor.setSelection(word.anchor, word.head);
});
```

A `git bisect` showed that 5d8347d is the culprit.
It results in [`poll` no longer returning false](https://github.com/codemirror/CodeMirror/blob/9e4e844898a60576aebb31a0999cb767a758cf39/lib/codemirror.js#L1392-L1394) because the editor is _still_ focused, which then makes a _weird-looking_ call to `applyTextInput` (https://github.com/adobe/brackets/issues/11142#issuecomment-103656931).

**Comment by marijnh** [comment]
Why is the call to `applyTextInput` 'weird-looking'?

Does replacing the check for `!cm.state.focused` with `activeElt() != this.textarea` help?

**Comment by MarcelGerber** [comment]
The call looks like this: `applyTextInput(cm, "", 0, null, null)`, which, looking further into it, is not as strange as I thought (I assumed the `deleted` param reflects the number of chars deleted, which is not the case).
Still, though, `inserted` being a zero-length strings is weird.

Replacing the condition didn't help.

**Comment by marijnh** [comment]
Does attached patch solve the issue for you?

**Comment by MarcelGerber** [comment]
Thanks, this one works.
Closing.
