### ISSUE TITLE
Formatting with <br/>

### ISSUE THREAD

**Issue by KRademacher** [codemirror/CodeMirror#3275]
Hello!
I'm using CodeMirror in combination with TinyMCE for creating Email signatures. One of the things I use a lot is '&lt;br/&gt;'. I'd like to make it so, that whenever there's a linebreak like that, Codemirror puts it on a new line. So far, as soon as I close and open the sourcecode window of TinyMCE, it all puts it on 1 line. I've had a scan through the files, but I can't find a setting anywhere. Any help?

Thanks in advance.

**Comment by marijnh** [comment]
CodeMirror edits plain text. It does not format it. If TinyMCE feeds it a single line, it'll display a single line.
