### ISSUE TITLE
Markdown mode does not recognise list after HR

### ISSUE THREAD

**Issue by billymoon** [codemirror/CodeMirror#3279]
When using markdown mode, if I write an HR, followed by newline, then list, it works as expected, with the next bullet being suggested...

    ---
    
    - this
    - <~ automatically inserted

If I have list immediately following `---` without newline, it does not auto insert next bullet

    ---
    - this
    <~ no auto insertion of bullet

Poking around in the code, it has something to do with `prevLineIsList` not being set correctly, but I got lost beyond that.

**Comment by marijnh** [comment]
@bfrohs Want to take a look at this? (The report makes is framed in terms of `continuelist`, but the issue actually also shows in the highlighting -- a list after a HR isn't recognized as such.)

**Comment by MarcelGerber** [comment]
This broke in 0bfd44a40248fe5d47268f1226ecc561eee74887 (PR #3178)

**Comment by marijnh** [comment]
Fixed via #3282
