### ISSUE TITLE
Dialog input does not inherit font size

### ISSUE THREAD

**Issue by baconface** [codemirror/CodeMirror#3280]
I am working on an addon that adds zoom in/out with Alt-Scrollwheel. All is going great except this minor noncritical bug.

I read if you change the font size of the correct element (```.CodeMirror[0]``` for example) then follow up with a refresh of the editor the font size should be inherited throughout. The dialog input fields seem to be the only element I can find that doesn't inherit this change. I will try to find the solution but my time is limited. I am posting it here in case anyone wants to beat me to to a solution/PR.

Zoomed In:
![Zoomed In](http://localabstract.com/uploads/zoomin.png)
Zoomed Out:
![Zoomed Out](http://localabstract.com/uploads/zoomout.png)

**Comment by marijnh** [comment]
This is due to the default (browser) style for `<input>` elements not inheriting the font size of its parent. Simply override it in your own css, like `input { font-size: inherit }`, and you should be fine.

**Comment by baconface** [comment]
Thanks, that did fix the issue. But is there a reason ```.CodeMirror input { font-size: inherit }``` or something like it isn't shipped with codemirror.css?

**Comment by marijnh** [comment]
Why would we? Font sizes in dialogs are not what this library is about. There are a hundred other CSS corner cases that we could proactively address, but including them would just bloat up the library and cause unexpected side effects.
