### ISSUE TITLE
SQL-Hint does not respect a table alias, when column information is fed as objects

### ISSUE THREAD

**Issue by madhuracj** [codemirror/CodeMirror#3281]
In summary, this issue is same as https://github.com/codemirror/CodeMirror/issues/3246, where CodeMirror recognizes the use of alias in hints but does not respect them when adding the selected value from hints to the editor. The issue still exists when columns are fed as objects.

List of columns are fed as 
```javacript
table.columns.push({  text: "<column_name>", displayText: "<column_description>"  });
````
The exact code is here at https://github.com/phpmyadmin/phpmyadmin/blob/master/js/functions.js#L1837...L1843

With a SQL like 
```sql
select t. from super_long_complicated_table t
```  
the hints show the columns belonging to alias `t` correctly, but uses `super_long_complicated_table` when adding the selected column to the editor.

I believe https://github.com/codemirror/CodeMirror/pull/3274 is a potential fix for this issue.

**Comment by marijnh** [comment]
Fixed via #3274
