### ISSUE TITLE
Tern CodeComplete functions missing parenthesis

### ISSUE THREAD

**Issue by mg80** [codemirror/CodeMirror#3286]
Is there a reason why when code completing on a function like Array, the parenthesis aren't provided for free?

Thanks

M@

**Comment by marijnh** [comment]
You might not want them, if you're just taking the value of the function. There's a long tradition of simply-complete-the-word style autocompletion, and the Tern addon sticks to that approach.

If you want, you can submit a pull request that adds a hook to the Tern addon to make extending completions from client code possible (say, a function that is called on the completion object before returning it).
