### ISSUE TITLE
[markdown mode] Issue with quotes in lists

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3287]
Go to http://marcelgerber.github.io/github/demo/codemirror/markdown-quote-in-list.html.

Result:
`  ## foo` and `   # foo` are marked `.cm-comment` (indented code block).

Expected:
`  ## foo` and `   # foo` are marked `.cm-header` (atx header).

Note:
This is caused by a negative `state.indentation`, which shouldn't ever happen. There's something wrong with how lists and blockquotes increase `state.indentation`.

Workaround:
Make `state.indentation = Math.max(state.indentation, 0)` so it's always positive. That works, but still it'd be better if we completely understand the issue.

**Comment by MarcelGerber** [comment]
@bfrohs Could you maybe take a look at this?

**Comment by vincentwoo** [comment]
Additionally, is there any interest in using a popular JS markdown parser to run the MD mode instead of a hand-rolled one? Say, for instance, https://github.com/chjj/marked?

**Comment by marijnh** [comment]
I'm not aware of any of these parsers (I think [markdown-it](https://github.com/markdown-it/markdown-it) is the most mature one in that family) exposing the primitives needed to build a CodeMirror mode on top of them (incremental parsing and being able to copy the parser state).

**Comment by bfrohs** [comment]
> @bfrohs Could you maybe take a look at this?

Yeah, I'll try to take a look tonight.

**Comment by MarcelGerber** [comment]
Thanks @bfrohs!
