### ISSUE TITLE
sql-hint small annoying bug

### ISSUE THREAD

**Issue by gooddaytoday** [codemirror/CodeMirror#3290]
There was issue about supporting schema names in sql hints: https://github.com/codemirror/CodeMirror/issues/2323 but it still don't work properly. After typing  shema. and continiung writng you will see wrong hints, so as shema.table. 

It seems for me that code doesn't work properly when sql-hint getting token at strings like schema."first characters of table". Code doesn't know about previous dot and showing hints only for "first characters of table".

I have created a little addon, that showing hints automaticaly during typing and this bug more noticeable. Unfortunately, addon writen on typescript, but I can contribute if there is a big need.

**Comment by marijnh** [comment]
I can't reproduce this anymore, and there have been big changes to sql-hint in the meantime, so I'm going to assume it was fixed.
