### ISSUE TITLE
Feature Request: Mixed Twig Mode

### ISSUE THREAD

**Issue by bobrocke** [codemirror/CodeMirror#3292]
Twig is a popular enough template language that I would think many could find a mixed-language Twig mode useful if they use Brackets (or other dependent editor) with such systems as Grav, Symphony and Craft.

I would suspect that Twig-HTML is the most needed. But Twig-HTML-JavaScript would be good, too.

**Comment by marijnh** [comment]
See https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list

**Comment by daniel-zahariev** [comment]
Until it's properly done, here's a walk-around:
```
CodeMirror.defineMode("htmltwig", function(config, parserConfig) {
  return CodeMirror.overlayMode(CodeMirror.getMode(config, parserConfig.backdrop || "text/html"), CodeMirror.getMode(config, "twig"));
});
```

**Comment by eman1986** [comment]
that workaround didn't work for me

> Uncaught TypeError: CodeMirror.overlayMode is not a function

**Comment by eman1986** [comment]
+1 I'd love this myself

**Comment by alex94040** [comment]
+1

**Comment by bastos71** [comment]
+1

**Comment by curruwilla** [comment]
@daniel-zahariev how to use?

**Comment by grekpg** [comment]
When i add 

CodeMirror.defineMode("htmltwig", function(config, parserConfig) {
  return CodeMirror.overlayMode(CodeMirror.getMode(config, parserConfig.backdrop || "text/html"), CodeMirror.getMode(config, "twig"));
});
 CKEDITOR.config.codemirror = {}

get editor?id=181:743 Uncaught ReferenceError: CodeMirror is not defined

**Comment by lajosbencz** [comment]
> Until it's properly done, here's a walk-around:
> 
> ```
> CodeMirror.defineMode("htmltwig", function(config, parserConfig) {
>   return CodeMirror.overlayMode(CodeMirror.getMode(config, parserConfig.backdrop || "text/html"), CodeMirror.getMode(config, "twig"));
> });
> ```

I've spent an hour trying to figure out why this piece of code won't work for me (webpack).

The import i was missing:

```js
import 'codemirror/addon/mode/overlay'
```
