### ISSUE TITLE
[vim] Add support for the star register (system clipboard copy+paste)

### ISSUE THREAD

**Issue by kevinushey** [codemirror/CodeMirror#3293]
I'm not sure what the best way of wiring this in would be, but here's a proposal:

1. Create a `SystemRegister` function, and have its prototype 'inherit' from `Register`,
2. Override the `setText`, `pushText` and `toString` methods to instead access the system clipboard.

Because there's a lot of messiness in accessing the clipboard, there could be placeholder functions like `$readClipboard` and `$writeClipboard` that users of `vim.js` could then implement themselves (pushing the onus of reading/writing to the clipboard to the user), which would then hopefully 'just work' in the context of the remaining code.

Any thoughts on the feasibility of this? I'd be happy to try and prototype an implementation if you think this is the right way to go.

**Comment by marijnh** [comment]
Note that, at the moment, there is _no_ way to get the content of the clipboard from JavaScript, and only spotty support for setting its content (outside of the context of copy/paste events), so I'm not sure this is a realistic feature.

**Comment by nightwing** [comment]
It is possible to set clipboard content when editor is used in an nw.js app or on a site with a [chrome extenison](https://chrome.google.com/webstore/detail/cloud9/nbdmccoknlfggadpfkmcpnamfnbkmkcp?hl=en) installed. So this feature might be useful to a sizable group of users.

**Comment by mightyguava** [comment]
We could expose a generic `addRegister` API on vim mode and let the integrating party deal with handling read/writes to it. I'd have to look into how feasible it is and what it would look like.

**Comment by kevinushey** [comment]
@marijnh In my case, my web application is running on top of Qt WebKit, and we have some relatively 'easy' access to the system clipboard via callback functions. It seems that (at least for my case) it would be possible to handle this; in general though, I think users would have to define how the system copy + pastes get handled, since (as you point out) this can't be handled reliably in a cross-platform way just within JavaScript.

@mightyguava That would be perfect for my use case.

**Comment by mightyguava** [comment]
That was simpler than I thought...

@kevinushey let me know if this rudimentary api is sufficient for your use case. https://github.com/codemirror/CodeMirror/pull/3315

Registers should really just be text buffers, but unfortunately linewise and blockwise yank complicates things a bit. And macro recording complicates it more... But if you just want the system register to act like a keybuffer, then the implementation should be pretty trivial
