### ISSUE TITLE
clike and closebrackets interaction problem

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#3295]
*I've made a codepen that recreates this issue here: http://codepen.io/anon/pen/vOgRyP*

When running a CodeMirror editor with just a clike mode enabled (say, standard C), CodeMirror is smart enough to know to deindent opening brackets on new lines. By way of example, say you have an editor like so:

```
1  int main()
```

and hit return. CodeMirror will give you a newline, but indented:

```
1  int main()
2      | <- cursor here
```

If you now type an opening bracket `{`, CodeMirror is ALSO smart enough to move that bracket back to the start of the line like so:

```
1  int main()
2  {
```

If you also enabled `autoCloseBrackets`, you'd expect that result following that exact same series of actions to be something like:

```
1  int main()
2  {}
```

instead, what actually happens is

```
1  int main()
2      {}
```

It appears that closebrackets and clike fight over who gets to act on that keypress. I'm not sure exactly what's going on. I took a look at `closebrackets.js` but it was a bit beyond me.

Furthermore, hitting enter right after typing `{` with both clike and closebrackets on results in the very awkward:

```
1  int main()
2      {
3
4  }
```

Any help on this issue would be much appreciated. I've disabled closebrackets on my project for the time being.

**Comment by marijnh** [comment]
The clike mode's `electricInput` property was too restrictive, and didn't fire on `{}EOL`, only `{EOL`. Attached patch fixes the problem for me (but note that you'll also need patch 5e989bdabd385357949 from early last month).

**Comment by vincentwoo** [comment]
Thanks!
