### ISSUE TITLE
invalid unicode in extendingChars

### ISSUE THREAD

**Issue by erichanson** [codemirror/CodeMirror#3296]
In https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L8232 the character \udc00-\udfff is invalid unicode.  Discovered while trying to encode codemirror.js to jsonb using PostgreSQL 9.4.0, that blew up on invalid unicode (since fixed).

```
aquameta=# select row_to_json(row('\udc00-\udfff'))::jsonb;
ERROR:  invalid input syntax for type json
DETAIL:  Unicode low surrogate must follow a high surrogate.
```

**Comment by marijnh** [comment]
There is no unicode in the CodeMirror source file, the is 'backslash-u-dee-cee-zero-zero' etc. As such, I'm not sure how that could cause Postgres to complain.
