### ISSUE TITLE
[JavaScript Mode] variable scopes not consistent

### ISSUE THREAD

**Issue by bobrocke** [codemirror/CodeMirror#3300]
![oth_domain js renanveroneze brackets-open-terminal-here brackets](https://cloud.githubusercontent.com/assets/2962426/7949030/bf79bf7e-0957-11e5-8d8c-5bf1702a1a11.jpg)

In this example, the first appearance of fullpath gets the scope `cm-def`.

The second gets `cm-variable-2` as do the remaining appearances.

Should they all not get the same scope? Perhaps `cm-variable-2`?

**Comment by marijnh** [comment]
`cm-def` is assigned to the token that _defines_ the variable. This one is a function parameter, so it is defined in the function signature.
