### ISSUE TITLE
Collapse/expand entire code editor

### ISSUE THREAD

**Issue by TravisTheTechie** [codemirror/CodeMirror#3302]
It would be nice to be able to collapse and expand the entire code editor. If there's a bunch of code blocks on a page, some of them might just be supporting code. You can have a  header + up/down or something on a single line indicating that there's content in there but it's only there if you want to take a peek.

**Comment by baconface** [comment]
Are you referring to [code folding](https://codemirror.net/demo/folding.html)?

**Comment by TravisTheTechie** [comment]
No, though code folding is an awesome feature, I want the entire editor to collapse/expand. Line down to one line/header/bit that shows there could code there.

**Comment by marijnh** [comment]
Again, this is out of scope for CodeMirror. You seem to be referring to a specific use for displaying code blocks (though you never mention which one) but this is something built on top of the editor, and functionality like folding away an editor would have to be built into whatever code is inserting those editors.
