### ISSUE TITLE
How to prevent CSS styles on specific classes

### ISSUE THREAD

**Issue by ngn1123** [codemirror/CodeMirror#3306]
Hello. Thank you for this awesome API!

Quick question, is there a way to prevent a user from inputting css styles on specific classes? For my company, we have our product header and footer, and it is possible for a client to hide these simply by referring to the class/id.

I've looked through the API and open/closed tickets, but haven't able to find a similar question.

Please let me know. Thanks!

**Comment by marijnh** [comment]
You could make part of your document readonly with [`markText`](http://codemirror.net/doc/manual.html#markText), or you could use the `"beforeChange"` event to try and filter changes that you don't allow, but there is no easy to way to express such filters in terms of 'adding a style to a class', that's much more high-level than the text level that CodeMirror works at.
