### ISSUE TITLE
Cannot select all code

### ISSUE THREAD

**Issue by mato75** [codemirror/CodeMirror#3309]
when pressing Cmd+A (select all) it selects the text and deselects it.

event change is triggering. I create a widget that uses CodeMirror. Is this correct, or do I need to create a new instance of codeMirror differently.

     self.codeMirror = CodeMirror.fromTextArea('textare', {
     });

```javascript
CodeMirror Library:
 - codemirror.js
 Modes:
 - css.js
 - htmlembedded.js
 - htmlmixed.js
 - http.js
 - javascript.js
 - xml.js
 Add-ons:
 - anyword-hint.js
 - closebrackets.js
 - closetag.js
 - comment.js
 - comment-fold.js
 - continuecomment.js
 - css-hint.js
 - html-hint.js
 - javascript-hint.js
 - mark-selection.js
 - match-highlighter.js
 - show-hint.js
 - xml-hint.js

```

**Comment by marijnh** [comment]
Does it also happen on the demos on http://codemirror.net ? Which browser are you using?

**Comment by mato75** [comment]
$el.off('keydown').on('keydown', function (e) {
			if ((e.ctrlKey || e.metaKey) && (e.keyCode == 65)) {
				if (!$(e.target).is('textarea')) {
					e.preventDefault();
					self.codeMirror.execCommand('selectAll');
				}
			}
		});

		self.panel.$el.on(
