### ISSUE TITLE
Enter key not working on Android

### ISSUE THREAD

**Issue by pigletso** [codemirror/CodeMirror#331]
I'm using Code Mirror since 2.18 and I wish to use Code Mirror through my 2.3.5 version android phone to edit my code.

Everything was great but there is one problem I have met and I hope this will be fixed.

The problem is : I cannot new a line when I press "Enter" button in android default browser

I looked up closed issues and found one was talking about iOS and android supporting (https://github.com/marijnh/CodeMirror2/issues/60) which had a comment posted by @schanzer provided a link to a "Functional Enter button" of previous versions of CodeMirror (www.litech.org/~schanzer/iOS). I tried to find the position of the problem using diff checker but I still failed.

I thought editing code in mobile phones were really cool. I also tried to use another browser (Firefox) to try the problem and it works OK, but I am not willing to use another browser before I tried to find the solution here.

Please take a look of this issue if you are interesting in. And, thanks a lot to Marijn for creating this powerful CodeMirror!

**Comment by marijnh** [comment]
Should be much better in 5.0.
