### ISSUE TITLE
lineNumbers=true are inside of a code

### ISSUE THREAD

**Issue by mato75** [codemirror/CodeMirror#3310]
Line numbers are located inside of a code.

![screen shot 2015-06-05 at 15 43 37](https://cloud.githubusercontent.com/assets/616192/8007096/b876aebe-0b99-11e5-8ea5-82f5e7372458.png)

```javascript
CodeMirror Library:
 - codemirror.js
 Modes:
 - css.js
 - htmlembedded.js
 - htmlmixed.js
 - http.js
 - javascript.js
 - xml.js
 Add-ons:
 - anyword-hint.js
 - closebrackets.js
 - closetag.js
 - comment.js
 - comment-fold.js
 - continuecomment.js
 - css-hint.js
 - html-hint.js
 - javascript-hint.js
 - mark-selection.js
 - match-highlighter.js
 - show-hint.js
 - xml-hint.js

```

**Comment by marijnh** [comment]
Please provide a full demo html file, and tell us which browser you are using. Also make sure the codemirror.css you have corresponds to the version of codemirror.js that you're using.

**Comment by mato75** [comment]
sorry, wrong css version file.
