### ISSUE TITLE
Not an editor command ":1d"

### ISSUE THREAD

**Issue by Cagiva-Raptor** [codemirror/CodeMirror#3311]
When trying to delete all rows containing 12811 the vim plugin returns the error : 
Not an editor command ":1d"

command executes is: %d/12811/d

![issue codemirror 01](https://cloud.githubusercontent.com/assets/6719521/8008053/eb952e6e-0b9f-11e5-8068-3e26472d00bd.JPG)
![issue codemirror 02](https://cloud.githubusercontent.com/assets/6719521/8008060/f678aa0e-0b9f-11e5-8b5e-9154f47a40a3.JPG)

**Comment by mightyguava** [comment]
`:d` is not supported. I'm happy to merge if anyone wants to submit an implementation

**Comment by Cagiva-Raptor** [comment]
Ok thx, I'll see If I can get it working :D

Yunchi Luo schreef op 7/06/2015 om 18:25:
