### ISSUE TITLE
Line editor gets wider when line number increases

### ISSUE THREAD

**Issue by danielo515** [codemirror/CodeMirror#3313]
I'm using codemirror in one project, just to provide line numbers to the text areas. The problem I'm facing that the editor gets wider while the line number grows. So if I have an editor which is 150 pixels wide, and I add 100 lines for example, it goes to 160 px wide (just example) if I reach the 1k lines it goes to 200 px wide and so on. All the lines have the same width because it is a list, but the editor still getting wider.

How can I prevent this? Thanks in advance.

**Comment by marijnh** [comment]
This does not happen in a regular CodeMirror instance. You probably have some CSS rules that are forcing the editor lines to have the same width. Try removing your custom CSS piece by piece to find out which rules are causing the problem.

**Comment by danielo515** [comment]
Ello @marijnh ,

What do you mean with regular CodeMirror Instance ? I have tried on several examples of codemirror web page and it happens in all of them. With how many rows have you tried? I'm talking about very large ammounts. In my example I'm using 227k rows.

**Comment by marijnh** [comment]
No, it does not. The editor's size is fixed. When you say 'line editor', do you mean the line number gutter? If so, yes, _obviously_ that has to get wider, if it must fit wider numbers.

**Comment by danielo515** [comment]
I think sometimes an image is better than thousand words. Take a look at this screenshot, it's from codemirror.net

![image](https://cloud.githubusercontent.com/assets/2270425/8021957/922c9fa8-0cb5-11e5-8028-16308023504d.png)


All that I have done is to paste a very long text. If  you see that text on notepad++ you can see there there are no werid characters:

![image](https://cloud.githubusercontent.com/assets/2270425/8021959/bb2a9536-0cb5-11e5-8401-ecf6d1c4ceaa.png)

Note that I have show blank characters activated. I checked the text and all the lines have more or less the same length, not exactly the same.

**Comment by danielo515** [comment]
I leaved an example text file here, so you can test your own:

https://www.dropbox.com/s/xef136zgwrjdavi/codemirrorBreak.txt?dl=0

Regards

**Comment by marijnh** [comment]
I still do not know what the problem is. The screenshot looks fine. Could you take a step back and try to actually explain what is happening, and what you expected to happen?

**Comment by danielo515** [comment]
Thank you @marijnh  for your patience. What I expect is the editor to do not increase its width. In the following screenshot you can see that all the editors are the same width. The first one has 200k numbers, the second one, which was on the same size than the others, holds the example file I posted here, and the other two are just empty at their original size. What I want, is the second editor to be wide enough to just hold its wider line. Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/2270425/8023600/a55e2224-0d12-11e5-962b-db40f94bf6f2.png)


Hope it is clear now.

**Comment by vincentwoo** [comment]
@danielo515 for what it's worth, I personally still do not understand the issue, or what you expect to happen.

**Comment by danielo515** [comment]
Hello @vincentwoo , 

Can you see the latest screenshot I posted? Do you see the second codemirror editor? It is far wider than the others, it's like 90% of the screen. But as you can see the text it contains is not as long. The other editors are just wide enough to hold it's contents. All of them have the same configuration. What I expect is the second editor be as wide as the first one.

**Comment by vincentwoo** [comment]
Okay, I see what you mean now. Your problem is that you think that CodeMirror is introducing additional horizontal scroll width, which you in turn are convinced has to do with the number of line numbers.

However, I think it might be something in your dataset. I pasted the first 100k lines in your text file, and the editor was fine. Pasting lines 100k-200k did cause the problem you are describing, though. Maybe you can isolate what part of your text file causes this problem?

**Comment by vincentwoo** [comment]
Oh, I found it. 

Line 164695: 10704x649aused by Saused by SubscriptionxErrorException(Consumer does not belong to DTAC.)

Do your homework next time!

**Comment by danielo515** [comment]
That's a lot of shame on me. I checked the whole dataset several times. I even activated the mini map and I checked it from the beginning to the bottom several times. The only thing I did not do was to run a regular expression. I think the dataset was so big that it was not properly rendered. Thank you very much and sorry everyone for wasting your time.
