### ISSUE TITLE
Select all + deleting throws an error on mobile Chrome

### ISSUE THREAD

**Issue by j13z** [codemirror/CodeMirror#3316]
Hi. I’ve found a bug affecting **Chrome mobile** (works fine on desktop Chrome):

Selecting the entire editor content (via the Android UI, see image below) and then trying to delete it with backspace results in an exception:

```
Uncaught TypeError: Cannot read property 'nodeType' of null
	walk                  @ codemirror.js:1929
	domTextBetween        @ codemirror.js:1959
	copyObj.pollContent   @ codemirror.js:1770
	(anonymous function)  @ codemirror.js:1589
```

(`node` is `null` in `domTextBetween`.)

I tested this with CodeMirror 5.3 as well as the latest version from the repo. Browser was Chrome Mobile 43.0.02357.92 on Android 5.1.1 (Nexus 5, inspected via DevTools remote debugging).

**Steps to reproduce the error** on any CodeMirror instance, e.g. `demo/themes.html`:

- Long tap
- Select all (via Android UI)
- Delete text (via Android keyboard)

Things that *do* work:

- Overwriting the selection with new text after "select all"
- Selecting a range of text (long tap) and then deleting or overwriting it

![codemirror-5 3_chrome_moible](https://cloud.githubusercontent.com/assets/3612115/8025817/750f0c40-0d63-11e5-8cc5-6ed03625d1a4.png)

Maybe I’ll do some further debugging later on, but for now I just wanted to track this bug.

**Comment by marijnh** [comment]
I think attached patch fixes this. Could you also test it?

**Comment by j13z** [comment]
@marijnh Works as expected now. Thanks a lot!
