### ISSUE TITLE
How could I force to redraw the highlight of all the lines?

### ISSUE THREAD

**Issue by sunstrd** [codemirror/CodeMirror#3318]
I was writing a mode recently of which one function is to memorize all the variables declared and highlight them when tokenized in the stream. This functon now works normally for most times, but i've found an issue, for example:

when a variable is newly declared in line 20 (with line 20 getting changed), the same variables from line 20 to the end will be immediately highlighted, but those from the beginning to line 19 will remain still.

I understand that for most times redraw merely from the line that is newly changed will save a lot, but on this occasion I just need CodeMirror redraw the highlight from the beginning to the end once I change some line. I've read the Manual and scanned the codemirror.js and I've got nothing useful. Sincerely looking for a way out :)

**Comment by marijnh** [comment]
Resetting the `mode` option with `setOption` will trigger a full re-parse.
