### ISSUE TITLE
a problem in loadmode addon with requirejs

### ISSUE THREAD

**Issue by cpoyraz** [codemirror/CodeMirror#3320]
When I try to load codemirror modes with loadmode and requirejs.. I receive the loading error of "libs/cm/lib/codemirror" of the loadmode.
I use packages in requirejs config below.

 packages: [{
        name: "codemirror",
        location: "libs/cm",
        main: "lib/codemirror"
    }],

Is there any a complete sample about loading codemirror with loadmode and requirejs?

**Comment by marijnh** [comment]
Attached patch adds this feature to the `demo/requirejs.html` demo. The trick was probably that you have to set `CodeMirror.modeURL` to something that requirejs can work with.
