### ISSUE TITLE
Markdown scope error?

### ISSUE THREAD

**Issue by bobrocke** [codemirror/CodeMirror#3321]
![item md brackets-real-twig brackets](https://cloud.githubusercontent.com/assets/2962426/8092984/dfe2d4f0-0f8b-11e5-8f98-c0de3d7d77ac.jpg)

**Comment by marijnh** [comment]
The `link` style is added for the link text, not the url, so I think the image link looks good.

Which theme is that? In the default theme, the `cm-link` style has higher precedence than `cm-quote`, but it appears that is not the case in this theme.

**Comment by bobrocke** [comment]
Should there be a scope for URLs, separate from the scope for strings? Maybe `cm-url`?

So, so in the case of quotes, it could be `cm-url.cm-quote`.

The theme is my own adaption of the Tomorrow Night theme. I'll look there for the problem with quote link coloring.

**Comment by marijnh** [comment]
We intentionally don't have token styles for every possible semantic thing, so that writing themes remains workable. This many modes overload token styles to mean different things, but this should not be a problem.

**Comment by bobrocke** [comment]
Are you saying it shouldn't be a problem to add a `cm-url` style? Or that overloading the `cm-string` style for Markdown mode isn't a problem.

I can see an argument for a `cm-url` style, as that would be a pretty specific semantic case.

Off the top of your head, can you think of a theme using mode overloading that I could use as an example?

**Comment by marijnh** [comment]
I am saying that using `cm-string` for URLs is not a problem. Themes don't overload modes, modes overload styles -- using `string` for urls is exactly an example of that.

**Comment by bobrocke** [comment]
OK, so the intent of the Markdown mode is that URLs should use the same styling as strings. Could it at least use `cm-stings-2`, so that my theme can show URLs in Markdown differently than strings in JavaScript?

**Comment by marijnh** [comment]
Markdown already adds a bunch of extra styles for semantic disambiguation. Attached patch also styles link targets as `url`, so that a site can give them a custom style.

**Comment by bobrocke** [comment]
Thank you!
