### ISSUE TITLE
Markdown with a URL in a quote

### ISSUE THREAD

**Issue by bobrocke** [codemirror/CodeMirror#3325]
![item md www br dev brackets](https://cloud.githubusercontent.com/assets/2962426/8114139/7ba649a8-1040-11e5-8fe6-0ebfc227f9a5.jpg)

**Comment by marijnh** [comment]
Nope, this is fine the way it is. All the text in a quote gets the `quote` style added.

**Comment by bobrocke** [comment]
I don't see that it gets a `quote` style from anything:

![devtools html](https://cloud.githubusercontent.com/assets/2962426/8129749/4494850c-10da-11e5-92e3-c5c74aa9be3c.jpg)

**Comment by marijnh** [comment]
Aha, I see what you mean now. That was a bug. Attached patches fix it, along with a CSS precedence issue that the fix exposed.
