### ISSUE TITLE
loadmode with requirejs

### ISSUE THREAD

**Issue by cpoyraz** [codemirror/CodeMirror#3326]
I use loadmode with requirejs. Although autoLoadMode function does not give error, CodeMirror does not change the mode. How can I use autoLoadMode with requirejs properly? or What may cause of this?

**Comment by marijnh** [comment]
Please don't open issues for support requests. Use http://discuss.codemirror.net for that.

I updated the [demo/requirejs.html](http://codemirror.net/demo/requirejs.html) yesterday to include an example of using the loadmode addon. That'll probably help.
