### ISSUE TITLE
Block comments won't work if lineComment is in place..?

### ISSUE THREAD

**Issue by remy** [codemirror/CodeMirror#3328]
Going by these lines: https://github.com/codemirror/CodeMirror/blob/master/addon/comment/comment.js#L44-L46

If the mode has a `lineComment`, like the JavaScript mode for instance, which would want single lines to be commented as `// ...` then the blockComments will never kick in.

All of the line comment types are correctly set up in the mode, but I can't see how multiline block comments would actually work.

If this is a bug, and you don't have the time, I'm happy to send a PR to fix.

**Comment by dhenson02** [comment]
+1 this

**Comment by vincentwoo** [comment]
That's the definition for the lineComment extension. Block commenting works as expected: https://github.com/codemirror/CodeMirror/blob/master/addon/comment/comment.js#L76

**Comment by dhenson02** [comment]
Actually @vincentwoo I don't think it does - try doing a block comment on the demo page http://codemirror.net/demo/sublime.html.  Select a few lines and hit `Ctrl+/`.  On my browser it line comments everything.  And `Ctrl+Shift+/` does nothing at all (expected to be block commenting keystroke).  Am I overlooking something here?

I'm on Chrome in Linux but I don't think that'll help much here.

**Comment by vincentwoo** [comment]
That's expected behavior. Sublime also line comments by default. If you want to do block commenting, you can very easily bind a key to `blockComment`.

**Comment by remy** [comment]
Then surely this logic should be removed from the source entirely? If it's
a redundant check that should be controlled through a key binding (not that
toggle would work...but that's a different issue).

It also means the documentation needs updating, because it suggests that
block comments can be enabled via options, but it conflicts with line
comments.

**Comment by marijnh** [comment]
Block commenting works fine, and there is no conflict. The _command_ `toggleComment` will try to line-comment before it tries block commenting. That is what it does. If you want something else, call the methods defined by the addon yourself.
