### ISSUE TITLE
Markdown with a URL in a quote (continued)

### ISSUE THREAD

**Issue by bobrocke** [codemirror/CodeMirror#3331]
See also: https://github.com/codemirror/CodeMirror/issues/3325

![](https://cloud.githubusercontent.com/assets/2962426/8114139/7ba649a8-1040-11e5-8fe6-0ebfc227f9a5.jpg)

I don't see that it gets a quote style from anything:

![](https://cloud.githubusercontent.com/assets/2962426/8129749/4494850c-10da-11e5-92e3-c5c74aa9be3c.jpg)

**Comment by marijnh** [comment]
See my comment on #3325
