### ISSUE TITLE
Annotations above lines of text

### ISSUE THREAD

**Issue by cha55son** [codemirror/CodeMirror#3333]
Would it be possible to implement something like the following with CodeMirror? I'm just trying to see if I could tweak or configure CodeMirror to accomplish something like the following.

![brat](http://anoopsarkar.github.io/nlp-class/assets/img/bratconll2k.jpg)

**Comment by vincentwoo** [comment]
Certainly not out of the box, but you can use CM methods like [markText](http://codemirror.net/doc/manual.html#markText) to annotate ranges with additional classes, or replace their DOM representation entirely.

**Comment by cha55son** [comment]
Interesting I wasn't aware we could replace the DOM element entirely. Would that be the `replacedWith` option?

**Comment by vincentwoo** [comment]
Yup

**Comment by marijnh** [comment]
You won't be able to actually edit the text if you replace it with another
DOM node, though. In this case, I think the easiest approach is to use
zero-height line widgets that you place above the lines. See
http://codemirror.net/doc/manual.html#addLineWidget

**Comment by cha55son** [comment]
Thanks Marjin, that looks useful as well. I'll check it out when I get the
chance.

On Thursday, June 18, 2015, Marijn Haverbeke <notifications@github.com>
wrote:

> You won't be able to actually edit the text if you replace it with another
> DOM node, though. In this case, I think the easiest approach is to use
> zero-height line widgets that you place above the lines. See
> http://codemirror.net/doc/manual.html#addLineWidget
>
> On Wed, Jun 17, 2015 at 8:35 PM, Vincent Woo <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Yup
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/codemirror/CodeMirror/issues/3333#issuecomment-112908277
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemirror/CodeMirror/issues/3333#issuecomment-113068899>
> .
>


-- 
Thanks,
Chason Choate

**Comment by cha55son** [comment]
Thanks, I believe the lineWidgets will be able to accomplish my task. Thanks everyone!

**Comment by theronic** [comment]
@cha55son did you manage to do this?

**Comment by cha55son** [comment]
I did. You can find my initial work here. https://github.com/digitalreasoning/AnnoMirror We pulled newer changes into our product but you can get the basic idea from the repo.
