### ISSUE TITLE
[Vim] Shift-tab leaves the editor in normal mode

### ISSUE THREAD

**Issue by crantok** [codemirror/CodeMirror#3334]
In Vim insert mode, I can use shift-tab in order to smart indent a line or selection of lines. In Normal or visual modes, tab and shift-tab cause focus to leave the editor.

I found this originally in Light Table. It also happens in the CodeMirror vim bindings demo when using either Firefox or Opera Beta. (I've not tried other browsers.)

**Comment by mightyguava** [comment]
This is the expected behavior for vim. Indentation in normal mode should be done with `>`.

**Comment by crantok** [comment]
The codemirror vim keymap wiki page ( https://github.com/codenvy/plugin-editor-codemirror/wiki/Vim-keymap ) only shows the use of `>` for manual indenting. Experimentation in the codemirror vim key bindings demo ( https://codemirror.net/demo/vim.html ) seems to confirm this. Does your response indicate that smart indentation is intended only for 'insert' mode?

**Comment by mightyguava** [comment]
Yes, exactly. Smart indentation is indented only for 'insert' mode.

`>` is for shifting blocks of text, and is the only indentation command supported in normal mode. See 'shift-left-right' http://vimdoc.sourceforge.net/htmldoc/change.html
