### ISSUE TITLE
Enhance search addons custom keybinding support.

### ISSUE THREAD

**Issue by jeff-blaisdell** [codemirror/CodeMirror#3337]
At my place of work we've had several requests to change the editor's search functionality to mimic the browser's search.  Specifically:
* Search bar should remain displayed while user cycles through matches.
* When closing search, the highlighted searches should disappear.
* Use same shortcuts Enter (Next) / Shift-Enter (Previous) as browser.

I do not believe this is possible to accomplish in the current state due to the search addons current usage of the dialog addon.  It would be useful to expose the dialog onClose and onKeyDown extension options through the search addon to allow for further customization of the search key bindings.

**Comment by marijnh** [comment]
Done via #3338
