### ISSUE TITLE
PHP nowdoc corrupted by smart indent

### ISSUE THREAD

**Issue by crantok** [codemirror/CodeMirror#3340]
Heredoc and nowdoc are treated differently by smart indent so that nowdoc strings are corrupted. I just modified the code in the PHP demo ( http://codemirror.net/mode/php/ ) and smart indent gave me this:

```PHP
function hello($who) {
	$a_string = <<<END
this is my first string
END;

	$another_string = <<<'END2'
		this is my second string
		END2;

	return "Hello $who!";
}
```

**Comment by marijnh** [comment]
The second form is simply not currently recognized as a string by the PHP mode. Attached patch fixes that.
