### ISSUE TITLE
CodeMirror fails to recognize Markdown headers if they lack a space after the final '#'

### ISSUE THREAD

**Issue by WesCossick** [codemirror/CodeMirror#3343]
CodeMirror fails to add the class `cm-header` to headers that lack a space between the final '#' and the title. For example:

```
# H1 ... has class cm-header
## H2 ... has class cm-header

#H1  ... does not have class cm-header
##H2  ... does not have class cm-header
```

Whether or not there technically should be a space, nearly all Markdown parsers will process `#H1` without a space identically to `# H1` with a space. This leads to inconsistencies when formatting is applied to the headers while editing using the `cm-header` class and when previews are generated using other parsers.

This issue can be tested at http://codemirror.net/mode/markdown/

**Comment by cben** [comment]
Indeed:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23foo%0A%0A%23%23+bar

But it's notable that one of the few exceptions is CommonMark (the spec
says "The opening sequence of # characters cannot be followed directly by a
non-space character.")

Perhaps it's better to make it an option?

2015-06-23 8:18 GMT+03:00 Wes Cossick <notifications@github.com>:

**Comment by WesCossick** [comment]
Making it an option would help, certainly. I still believe the default should be that it _can_ be followed by a non-space character, since this appears to be the most common implementation across parsers (as seen in the link above).

**Comment by marijnh** [comment]
I'm leaning towards targeting CommonMark by default, since having a spec to compare what we are doing against (rather than a vague consensus of parsers) provides a much more firm ground. I'd be open to an option that enables parsing such headers, though.
