### ISSUE TITLE
Markdown mode issue

### ISSUE THREAD

**Issue by amshali** [codemirror/CodeMirror#3345]
Hi
I am doing the following to set the mode for different files and it does not work properly for '*.md' files.
```javascript
var info = CodeMirror.findModeByFileName(filename);
var mode, spec;
if (info) {
  mode = info.mode;
  spec = info.mime;
} else {
  mode = null;
  spec = 'text/plain';
}
CodeMirror.autoLoadMode(this.editor, mode);
this.editor.setOption('mode', spec);
```
Any idea how I can resolve this?

Thank you.

**Comment by marijnh** [comment]
This works for me. Make sure the mode scripts are in the place where loadmode expects them (see the `CodeMirror.modeURL` setting). You'll see an error in the console if it can't find them.

**Comment by amshali** [comment]
It still not working for me. I checked the modeUrl. It is correct. I mean it works for everything else. 
Here is a snapshot of variables. Seems like it does not like setting mode option set to "text/x-gfm". If I set that to "gfm" it will work. But then I cannot change my logic because it will break the clike mode.
```javascript 
      CodeMirror.autoLoadMode(this.editor, mode); // mode = "gfm"
      this.editor.setOption('mode', spec); // spec = "text/x-gfm"
```

**Comment by marijnh** [comment]
Aha, you didn't mention you were using gfm. It seems the gfm failed to actually define the MIME type that meta.js declared for it. Attached patch fixes this.

**Comment by amshali** [comment]
Yayy! Awesome! Thanks a bunch.
