### ISSUE TITLE
[vim] pasting text yanked with Y  from  block mode doesn't work

### ISSUE THREAD

**Issue by nightwing** [codemirror/CodeMirror#3347]
When pressing `Y` in visual block mode [vim.js#L1519](https://github.com/codemirror/CodeMirror/blob/5.4.0/keymap/vim.js#L1519) extends selection to the end of line and sets both  linewise and blockwise to true (which is different from what vim does).

Since [vim.js#L2391](https://github.com/codemirror/CodeMirror/blob/5.4.0/keymap/vim.js#L2391) checks for `linewise` before `blockwise`, [vim.js#L2433](https://github.com/codemirror/CodeMirror/blob/5.4.0/keymap/vim.js#L2433) gets a string instead of an array and inserts whole text in one column

**Comment by marijnh** [comment]
@mightyguava Is this on your radar? Anything I can do to help?

**Comment by mightyguava** [comment]
@nightwing what is the expected behavior? That "linewise" is ignored and only the selection is copied? I don't use blockwise mode very often. Is there a general behavior for all linewise operators in visual block mode?

**Comment by justin8** [comment]
@mightyguava if you use y or Y when selecting a block in vim it will only copy the selected block of text; if you do Y with codemirror it copies all lines your block mode has highlighted, instead of only the selection. I can try and get some screenshots if that isn't clear enough.
