### ISSUE TITLE
showHint to take index of option active on startup

### ISSUE THREAD

**Issue by cgrushko** [codemirror/CodeMirror#3348]
Currently showHint activates the first element of option, when it shows the completion widget.
I'd like to control which element is active by default.

I can submit a patch if it's acceptable. Thanks!

**Comment by marijnh** [comment]
Looking at the code, it seems you can already set a `selectedHint` property on your completion object to control this (a zero-based integer index)

**Comment by cgrushko** [comment]
Ah, cool! 
Let's reopen the bug, to track the fix to the documentation? (it doesn't mention selectedHint)

**Comment by marijnh** [comment]
Good point. See attached patch
