### ISSUE TITLE
Selection and change event

### ISSUE THREAD

**Issue by amshali** [codemirror/CodeMirror#3349]
I have noticed many times in my using of CM that a change event is triggered despite the fact that nothing been done to trigger a change. Or nothing as far as I can tell. This always happens when I select a piece of text in the editor and then switch windows or tabs in the browser and come back and the change event is triggered. The change object is an array with one element where the same piece of text is added and removed. 

Do you have any clue what might cause this? I am in chrome under ubuntu.

**Comment by marijnh** [comment]
Does this also happen on the demos on codemirror.net? I tested with Chrome under Debian, which should be close to your setup, but couldn't reproduce this.

**Comment by amshali** [comment]
I have to figure out a solid way of reproducing it. It might have nothing to do with CodeMirror, but I am not sure yet.
