### ISSUE TITLE
TypeError: htmlMode.startState is not a function 

### ISSUE THREAD

**Issue by FabianCernota** [codemirror/CodeMirror#3351]
With this Code:
```
  <script>

   var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
     lineNumbers: true,
     extraKeys: {"Ctrl-Space": "autocomplete"},
     mode: "text/html"
   });
  
 </script>
```
i get in firefox this error message 
TypeError: htmlMode.startState is not a function  
but why ?:D I include all needed Javascripts.

Thanks Fabian

**Comment by marijnh** [comment]
Did you include the XML, JavaScript, and CSS modes? These are dependencies of the htmlmixed mode.

**Comment by FabianCernota** [comment]
yes😊

**Comment by marijnh** [comment]
Well, it works in the [demo](http://codemirror.net/mode/htmlmixed/), so compare your setup with the situation in the demo to figure out what is going wrong.

Closing, but feel free to add comments or reopen if you've isolated an actual bug.

**Comment by CharlyJazz** [comment]
i try use the php mode  and have this error
`php.js:163 Uncaught TypeError: htmlMode.indent is not a function
 ....
`
any idea?

**Comment by MaxSmith** [comment]
@marijnh hi! Can you please fix wrong regex:
http://codemirror.net/mode/htmlmixed/

Wrong:
`/^text/(x-)?scss$/`
Correct:
`/^text\/(x-)?scss$/`

![image](https://user-images.githubusercontent.com/1188493/30987327-55d9fa80-a49f-11e7-80ff-12dda8fcbf4a.png)

![image](https://user-images.githubusercontent.com/1188493/30987302-2bcba630-a49f-11e7-8860-26f9a3b685a0.png)

Thanks!

**Comment by TeaWeb** [comment]
> i try use the php mode and have this error
> `php.js:163 Uncaught TypeError: htmlMode.indent is not a function .... `
> any idea?

+1

**Comment by adrianheine** [comment]
Could you post an example setup that has this issue?

**Comment by paulalbertdev** [comment]
@TeaWeb & @CharlyJazz 
Look @ this example https://github.com/codemirror/CodeMirror/blob/master/demo/html5complete.html
htmlmixed seems to rely on other needed addons ;)
