### ISSUE TITLE
Vertical scroll bar is not draggable when dragging down or up

### ISSUE THREAD

**Issue by JonesXavi** [codemirror/CodeMirror#3355]
Hey,
I'm unable to drag the vertical scroll bars to bottom or top in my codemirrror editors. The mouse wheel up and down works. But while trying to drag by pulling the bar, the content inside the editor gets selected not scrolled. Any help? Thanks in advance.

**Comment by marijnh** [comment]
I haven't run into this before (there have been similar bugs, but they were fixed). You can try to reduce it to the minimal set of factors that trigger the issue, and submit a demo for me to debug.

**Comment by JonesXavi** [comment]
Hey thanks for the reply @marijnh !
I fixed it. The problem was because of z-index set to zero in .CodeMirror-vscrollbar in codemirror.css Line : 180
