### ISSUE TITLE
Tall line widget above the line breaks scroll

### ISSUE THREAD

**Issue by satamas** [codemirror/CodeMirror#3357]
Using wheel  in this [fiddle](http://jsfiddle.net/1Lm6eb8t/) i can scroll  editor down so that all it's content would be above the field of view. None of this happens if widget is below the line or if it's smaller(100px instead of 1000px).

I have tested firefox and chrome in Windows and Ubuntu with latest (5.4.0) release of CodeMirror.

**Comment by marijnh** [comment]
I was able to reproduce this and found the cause (poor placement/sizing of gutter background nodes). I haven't yet found a solution, but you could put this in your css as a workaround:

```css
.CodeMirror-gutter-wrapper {
  height: auto !important;
}
```

I'll continue to look for a solution next week.

**Comment by marijnh** [comment]
Attached patch implements a proper fix.
