### ISSUE TITLE
[vim] imap mapping to ESC fails to exit insert mode

### ISSUE THREAD

**Issue by daveosborne** [codemirror/CodeMirror#3360]
Reproducible in vim [demo](http://codemirror.net/demo/vim.html)

While in insert mode Esc, Ctrl-C and Ctrl-[ behave as expected, exiting insert mode.
Map jk using `:imap jk <ESC>`
Now, when jk is typed, the jk is correctly eaten, but the editor stays in insert mode.

**Comment by nightwing** [comment]
`:imap jk <Esc>` works

**Comment by daveosborne** [comment]
I've tried it in Linux and Windows in Chrome, Firefox, Safari and IE and the bug is reproducible for me in all of them. Does it exit insert mode for you?

**Comment by nightwing** [comment]
It depends on the way `esc` is written:  `<Esc>` works, but other forms like `<ESC>` or `<esc>` do not

**Comment by Newton0314** [comment]
> 

Thank you! The devil hides in the details!
