### ISSUE TITLE
unable to set linenumbers in runmode

### ISSUE THREAD

**Issue by cpoyraz** [codemirror/CodeMirror#3364]
in editor , line numbers , first line number exist, why not in runmode?

**Comment by vincentwoo** [comment]
This issue is very difficult to understand. Can you please illustrate the problem with two different jsfiddles or some screenshots?

**Comment by mkaminsky11** [comment]
He's saying that there are no line numbers in runmode (https://codemirror.net/demo/runmode.html)

**Comment by mkaminsky11** [comment]
Proposed the ability to pass a `lineNumbers` attribute like 
```javascript
  CodeMirror.runMode(document.getElementById("code").value, "application/xml", document.getElementById("output"), {
    lineNumbers: true
});
```

In https://github.com/codemirror/CodeMirror/pull/3358

**Comment by marijnh** [comment]
runmode does not support line numbers by default, intentionally. You can pass your own callback to construct line numbers in your own way, but as a default, it doesn't make much sense (the CSS styles for the line numbers in the actual editor would only work if we'd replicate a lot of the complicated DOM structure that the editor has, and you don't want to do that when highlighting code).

**Comment by cpoyraz** [comment]
I think the codemirror should provide better highlighting code option since codemirror is not used only for editors.
