### ISSUE TITLE
TypeError: cm.getHelpers is not a function, foldcode.js.

### ISSUE THREAD

**Issue by Newbie-Jack** [codemirror/CodeMirror#3366]
When the foldCode function is called it is giving me this error in the console:

Uncaught TypeError: cm.getHelpers is not a function            foldcode.js  :  line 121

When starting up the comment-fold.js file I also get this error in the console:

Uncaught TypeError: CodeMirror.registerGlobalHelper is not a function        comment-fold.js  :  line 14

**Comment by marijnh** [comment]
Could it be that you are using an old version of CodeMirror with addons from a more recent distribution? `CodeMirror.registerGlobalHelper` definitely exists in current versions.
