### ISSUE TITLE
Hope to provide the toolbar

### ISSUE THREAD

**Issue by zy8008** [codemirror/CodeMirror#3367]
Hope to provide the toolbar and context menu interface can be used to put some buttons or help information

Like the following
![image](https://cloud.githubusercontent.com/assets/11024800/8586838/13818cf6-2626-11e5-8db6-0a061258fc3b.png)

**Comment by marijnh** [comment]
CodeMirror doesn't provide such functionality. It does provide an API aimed to make it easy for 3rd-party code to do so.
