### ISSUE TITLE
a display bug ,very important

### ISSUE THREAD

**Issue by iicanf** [codemirror/CodeMirror#3368]
i use codemirror for a editor of some conf file, sometimes load like this:
![2015-07-09_111329](https://cloud.githubusercontent.com/assets/2391122/8587279/cdf2765e-262b-11e5-99a3-f1255881c49d.png)
but sometimes:
![2015-07-09_111259](https://cloud.githubusercontent.com/assets/2391122/8587278/cc746c2e-262b-11e5-9a7d-6cbab546c8a5.png)
and this is the Develop tool capture：
![2015-07-09_111420](https://cloud.githubusercontent.com/assets/2391122/8587285/ddc6d44e-262b-11e5-9757-b7a833e7cd0a.png)

**Comment by marijnh** [comment]
The style you circled is on the hidden textarea and will not impact the display of the editor. If you can provide me with an HTML page, a browser in which this happens, and instructions to reproduce it, I'll gladly try to debug it.
