### ISSUE TITLE
CodeMirror searching does not play well with Polymer 1.0 & Shadow Roots

### ISSUE THREAD

**Issue by beaudesigns** [codemirror/CodeMirror#3369]
In CodeMirror, the `activeElt()` method checks `document.activeElement`. With Shadow Roots, each one has their own `activeElement`. See: https://www.polymer-project.org/0.5/resources/faq.html#activeelement

The affect of this is that when you activate the search in CodeMirror, essentially nothing happens. If you break on DOM changes, you can see that it does actually bring up the search dialog, but then instantly closes it, focusing back on the main CodeMirror editable area.

----------

I modified the `activeElt()` method to the following:

```
function activeElt() {
	var activeElement = document.activeElement;
	while (activeElement && activeElement.root && activeElement.root.activeElement) {
		activeElement = activeElement.root.activeElement;
	}
	return activeElement;
}
```

This drills down into the each activeElement's Shadow Root and returns the one that we need.

This probably isn't the best way to resolve it which is why I'm not submitting a pull request. I'd like to get some input on better ways to resolve this.

**Keep in mind** that this only happens in Polymer when Shadow Dom is enabled, the default is currently shady DOM, which I believe doesn't have any issues.

**Comment by marijnh** [comment]
I actually don't think this is a bad way to resolve it. We did a similar thing in our implementation of `contains`, which also doesn't automatically see through shadow DOM. I've applied this in 8e6aca8, let me know if you run into further issues.
