### ISSUE TITLE
cm-error highlight after img dataurl

### ISSUE THREAD

**Issue by Cerealkillerway** [codemirror/CodeMirror#3371]
When it finds a img tag with dataurl in the src attribute, like

    <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAA0JCg....

it highlights next tag as an error; it seems to be due to the length of the src attribute;

**Comment by marijnh** [comment]
Highlighting ridiculously long lines is a performance hazard, and yes, that can sometimes confuse the tokenizer. You can set the `maxHighlightLength` to `Infinity` or to something larger than the default (10000) to work around this, but I don't know of a general solution to this problem. Suggestions welcome, though.
