### ISSUE TITLE
Markdown: multiline links

### ISSUE THREAD

**Issue by nodirt** [codemirror/CodeMirror#3385]
Given Markdown

```md
[multiline
link](http://localhost)

[singleline link](http://localhost)
```

the multiline link is not syntax highlighted as a link

GitHub considers multiline links as valid links:
[multiline
link](http://localhost)

**Comment by marijnh** [comment]
This is one of those cases where not being able to do across-line lookahead makes it impossible to get accurate highlighting. Since CodeMirror does not support such a lookahead, this is not going to be supported.
