### ISSUE TITLE
bugginess with very long wrapped lines

### ISSUE THREAD

**Issue by greaber** [codemirror/CodeMirror#3387]
I have been trying to use CodeMirror as a special purpose WYSIWYG editor for an application where I only need very simple formatting and want a very clean document model with no html.  To do this, I turn line wrapping on and let each line represent a paragraph.  I am also using cursorCoords to align marginal notes with particular lines within a paragraph.

I have experienced a lot of strange behaviors.  For instance, sometimes using the cursor keys moves the cursor by more than one line, sometimes the cursor keys seem unable to move the cursor into a given region, and sometimes the marginal notes get out of alignment with the lines they are supposed to (which could of course be due to a bug in my code, but I think it is a CodeMirror issue).  I have experienced these problems with different browsers and with inputStyle set both to contentEditable and not, though changing browsers and inputStyle does seem change the exact behavior in some cases.

I have a fairly small test case that exhibits the cursor jumping problem if you mess around with it.  So far I have only observed the other problems in the full version of my code.  I am willing to work more on getting small test cases that show the problems, but before I put a lot of effort into that I thought I should check if any of these issues are known or to be expected given how I am abusing CodeMirror.

**Comment by marijnh** [comment]
Submit your test case (make sure it is really small, not fairly small -- i.e. don't make me dig through irrelevant code) and I'll try to debug it.

**Comment by greaber** [comment]
OK, this is pretty small and shows some problems.

<html>
<head>
    <link rel="stylesheet" href="codemirror.css">
    <script src="codemirror.js"></script>
    <style>
    body {
        width: 200px;
    }
    </style>
</head>

<body>


    <textarea id="myTextarea">blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah</textarea>

    <script>
    (function () {
        var myTextArea = document.getElementById('myTextarea')

        var cm = CodeMirror.fromTextArea(myTextArea, {
            lineWrapping: true
        })

        var marker = cm.markText({line: 0, ch: 495}, {line: 0, ch: 499})

        cm.on('change', function (instance, changeObj) {
            var fromTo = marker.find()
            cm.cursorCoords(fromTo.from)
        })
    })()
    </script>
</body>
</html>

In Chrome, paste the following string at the beginning of the buffer: "sdlfj sdlkf jsdlkfjsd lkfjsd flksdj flsd flsdf afa ".  This should result in the last line having one "blah" on it.  Click at the end of the buffer.  Then push the up arrow key.  The cursor should go up two lines instead of one.

I have mainly been working in Chrome, but I tried in Firefox and got different behavior because  Firefox is only putting four "blah"s on a line instead of five like Chrome.  So with this exact recipe, the bug doesn't manifest in Firefox.  But there seems to be a different bug showing up in Firefox: after I paste the string, even when I scroll the editor all the way to the bottom, I only see the top of the last line.

By the way, I was setting "height: auto" on .CodeMirror originally, and I still saw the bug (in Chrome); I just took it out to be more minimal.

**Comment by marijnh** [comment]
I did not get the problem you describe, but your demo did uncover a different wrong behavior for me (not being able to scroll down to the bottom of the document), which attached patch fixes. It is possible that it also fixes the problem you are describing. On my Chrome, I don't end up with a single 'blah' on the last line when I follow your instructions, probably due to a small difference in font rendering (I assume you meant the css at the top of your demo to be a `<style>` tag).

Could you pull the latest code and retry?

**Comment by greaber** [comment]
Thanks! This fix does solve the Chrome issue, but I want to experiment some more to see if all the problems I was having are fixed.

I did notice that there is still a surprising behavior in Firefox, though I don't know if it qualifies as a bug.  Namely, as I said before, on my system (OS X), Firefox only fits four blahs on a line initially.  Yet it seems to leave room for a fifth blah in the sense that the scrollbar is a full blah away from the right side of the text, instead of abutting the right side of the text as in Chrome.  Furthermore, after I paste the string at the beginning, I actually see five blahs on the last line!

Possibly related is a Chrome/Firefox difference I observed in the rendering of textareas.  In Chrome, if you have one word at the end of a line and another at the beginning of the following line, with a single space separating them, pressing the right cursor key at the end of the first line takes you directly to the beginning of the second line.  More generally, if n spaces separate separate the two words, there are n-1 spaces at the end of the first line.  In other words, the linebreak is treated as logically equivalent to a single space.  Firefox, on the other hand, treats linebreak as logically equivalent to nothing at all; it displays n spaces at the end of the first line.  CodeMirror on both Chrome and Firefox seems to have the Chrome textarea behavior, which I think is superior, but could it be that the Firefox way of handling textareas is throwing off some calculation?

**Comment by greaber** [comment]
Load the following page, then insert an 'x' as the first character in the buffer.  In Chrome, inserting the 'x' pushes the start of line 1 down a line, so I believe the output should be two different numbers with the second larger than the first; but the output is "313\n313\n".  In Firefox, inserting the 'x' doesn't move the start of line 1, so I believe the output should be the same number twice; but the output is "350.5\n283\n".

```html
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="CodeMirror/lib/codemirror.css">
    <script src="CodeMirror/lib/codemirror.js"></script>
    <style>
    body {
        width: 200px;
    }
    .CodeMirror {
        height: auto;
        border: 1px solid red;
    }
    </style>
</head>

<body>

    <textarea id="myTextArea">blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah
blah</textarea>

    <script>
    (function () {
        var myTextArea = document.getElementById('myTextArea')

        var cm = CodeMirror.fromTextArea(myTextArea, {
            lineWrapping: true
        })

        console.log(cm.cursorCoords({line: 1, ch: 0}).top)

        cm.on('change', function (instance, changeObj) {
            console.log(cm.cursorCoords({line: 1, ch: 0}).top)
        })
    })()
    </script>
</body>
</html>
```

**Comment by marijnh** [comment]
The line wrapping is done by the browser, so the Chrome/FF differences are
to be expected and not something to worry about (though I agree that
sometimes browsers do weird things here).

The measurement effect you're seeing happens because the "change" event is
fired before the redraw is done (so that changes triggered by change events
don't keep causing new redraws), at which point the editor does not have
accurate information about the new line height yet. You could listen to the
"changes" event or set a timeout in the "change" event, to have your code
run when the display update is finished.

**Comment by greaber** [comment]
Thanks! I guess the Firefox weirdness around linewrapping is ultimately Firefox weirdness as I was speculating, and perhaps Firefox should fix it.  But I guess the Firefox philosophy is to treat spaces as first class citizens, and it does that even to the extent of letting you move the cursor between the position before and after a space when that space is at the end of a line and causing line wrapping.  CodeMirror goes halfway toward the Chrome behavior by removing this possibility, so the extra Firefox space appears totally mysterious and you don't really get the benefit of the Firefox way, if I am understanding correctly.

On the second point, thanks!!  Doing either of the things you recommend fixes the example I sent.  Hopefully it will fix all the issues I have been having with my real code too, but I still need to test that.  Your explanation makes good sense of why I was seeing stale values in Chrome, but do you understand why I was seeing weird transient line heights in Firefox when none of the line breaks in the whole editor were changing?

**Comment by greaber** [comment]
Also, it would be cool if the explanation of 'change' and 'changes' in the manual explained this issue.  The 'changes' explanation links to the explanation of cm.operation, which focuses on efficiency.   This gave me the impression that 'changes' was just for optimization.

**Comment by marijnh** [comment]
When a line is updated, CodeMirror starts by guessing its height, so that it has an approximation to work with until it has drawn the line and measured the actual height. Since the wrapping algorithms in the different browsers are different, that estimate may be closer to the real height in some browser than in others.

I've pushed a small documentation tweak to clarify the event timing around the end of an operation.
