### ISSUE TITLE
lint markers tied to a particular doc

### ISSUE THREAD

**Issue by amshali** [codemirror/CodeMirror#3391]
Is it possible to tie a lint call to a specific doc? 
In cases where there is a single editor and multiple doc, this is going to be very useful. 
My current issue is that I have this async lint process which might take up to 3 or 4 seconds to complete. If during that 3-4 seconds we switch docs (swapDoc), then the markers will appear in the new doc which is totally wrong. 
Do you have any idea how to fix this? I'd be willing to code a fix if you give me some hints. Thanks.

**Comment by marijnh** [comment]
We could abort asynchronous lints when a change or a swapDoc happens. Does that sound like it'd solve your problem?

**Comment by amshali** [comment]
I was hoping we could continue doing those async jobs and hopefully get the results in the right place. 
I can add logic to my code to stop those async lints (or ignore their results) if the doc has changed.

**Comment by amshali** [comment]
Is it possible to trigger a lint event? I want to have control over when we lint or at least I would like to initiate it when I want.

**Comment by marijnh** [comment]
No, there isn't. The addon currently simply starts on a debounced change event.

**Comment by marijnh** [comment]
Done via #3415
