### ISSUE TITLE
How to use the API to find out the string and selected automatically

### ISSUE THREAD

**Issue by zy8008** [codemirror/CodeMirror#3392]
I want to  by using the method of API to find and automatically select the specified content!

For example: codemirror. Find (" the Test word ")

result:
![image](https://cloud.githubusercontent.com/assets/11024800/8720312/8e37a1d8-2be4-11e5-940c-68a45bdb1a0e.png)

I did not find in the API documentation and demo corresponding method, do not know to have this feature

**Comment by marijnh** [comment]
Look here: http://codemirror.net/doc/manual.html#addon_searchcursor
