### ISSUE TITLE
Preserve newline LF/CRLF for each line

### ISSUE THREAD

**Issue by mihailik** [codemirror/CodeMirror#3395]
Currently CodeMirror has a single newline character for the whole document.

That means `getValue` may return different text to what `setValue` was called with, depending on the newlines used.

Can the code preserve the ending newline for each line of the document, and use exactly that when concatenating line text for ranges, copy/paste, getValue/setValue please?

Ideally pressing 'Enter' would be made smarter too, so it insert the right kind of newline based on the one at the end of the current line.

**Comment by marijnh** [comment]
Though I agree with your premise (it _would_ be nice if you could round-trip through CodeMirror without losing information), I don't think your solution is the right way to go.

The reason why this hasn't been much of a problem for people so far is probably that there are very few good reasons for mixing different line ending conventions in a single file. I am not really interested in supporting a system where CodeMirror magically keeps track of each line's ending and restores that.

Instead, I've implemented a different solution, which is much less likely to cause problems and is fully backwards compatible. Attached patches add a `lineSeparator` option, which defaults to null to give the current behavior (normalize to `\n`). You can set it to a string to have the editor break lines on exactly that string, and leave other characters as part of the line text. That way, your documents won't be damaged, but you also keep the invariant that an editor instance has a single line separator.

The intended use would be for those who care about line endings to implement some kind of heuristic that determines the line endings used in a given file, and pass that to the editor in the `lineSeparator` option.

**Comment by mihailik** [comment]
Thanks a lot @marijnh.

Though I do **not** think `lineSeparator` would add value. It certainly does not help the use case I have.

My suggestion is to revert this change and leave it as is for now. It complicates code without solving any practical problem.

The use case I have is that user edits a file from external source, and upon save the only changes are those the user made.

I totally see it is not a trivial one to implement, so don't disagree with letting it rest until better opportunity (or until a friendly fork). But let's help that future work by not muddling the code with options almost nobody uses.

**Comment by marijnh** [comment]
The patch is not going to be reverted. This is how I think being able to preserve mixed line endings should work.

**Comment by mihailik** [comment]
No worries for not reverting, that's why I said 'suggestion' :)

But sorry, I might be missing the point. All the original line endings are removed from the document. How exactly do you intend to preserve *mixed line endings* with an extra parameter?

**Comment by marijnh** [comment]
If you have `"foo\nbar\r\nbaz"` as your document and your line-ending-determination algorithm decides that it is using `"\n"` as its main line separator. You create an instance with `{doc: "foo\nbar\r\nbaz", lineSeparator: "\n"}`, and you'll get three visible lines `foo`, `bar\r`, and `baz`. I.e. the leftover characters that don't match the document's line separator are considered part of the line's _content_, and show up in the editor.

**Comment by mihailik** [comment]
Is it really how it **should** work? This approach produces visual garbage like red dots, may still break addins, and it even glues lines together (try `"foo\nbar\nbaz"`).

Whereas keeping precise account of actual line terminators handles any of those cases and more. Say, you'd be able to implement stricter [Unicode conformance](https://en.wikipedia.org/wiki/Newline#Unicode), as there are actually more than 3 line terminators in the standard.

Also [those compilers](https://github.com/Microsoft/TypeScript/issues/1693) that pay attention to EOLs commonly have unit tests for handling the relevant combinations. It would be nice for CodeMirror to be able to open such files without going weird :)
