### ISSUE TITLE
Auto close tag doubles closing with </>

### ISSUE THREAD

**Issue by makfruit** [codemirror/CodeMirror#3409]
Reproduce:
1. Open http://codemirror.net/demo/closetag.html in a browser.
2. Put "<div>" in the text field
3. Put any content
4. Put "<>"
5. Add "/" between the tag brackets. The closing tag will be automatically added with additional closing bracket (>), so the resulting text would be <div>content</div>> with one extra bracket

Expected:
Codemirror would detect that the "/" was being added before ">" and wouldn't add another ">". 

Gif attached
![closetag_doubles_closing](https://cloud.githubusercontent.com/assets/1201983/8872543/a3c727b2-3206-11e5-8fb3-b8dcada4dd66.gif)

**Comment by marijnh** [comment]
Why are you typing both brackets first though? That doesn't seem like a sane/common enough case to address specially.

**Comment by makfruit** [comment]
This is not a very common case – you're right. I've been always typing so, though, and it turns out some people are typing this way, too. Not sure how to check whether this is a frequent case – let's just see if anyone joins this report.

**Comment by marijnh** [comment]
Well, that's an interesting editing style, but it is pretty easy to support this. See attached patch.

**Comment by makfruit** [comment]
That was fast! 
Thank you!
