### ISSUE TITLE
readOnly: true does not prevent pasting

### ISSUE THREAD

**Issue by markrian** [codemirror/CodeMirror#3410]
Tested on CodeMirror 5.5.1 (on codemirror.net) on latest Firefox and Chrome. Set an editor's readOnly option to true, and then copy some text from somewhere and try pasting it into the editor. The text is pasted successfully into the editor, but I would expect nothing to happen.

**Comment by marijnh** [comment]
Oops -- this was broken in a recent change to the paste handler. Attached patch fixes it again.
