### ISSUE TITLE
browsers unusably slow due to line wrapper using position:relative

### ISSUE THREAD

**Issue by spearce** [codemirror/CodeMirror#3412]
When line numbers are enabled or line widgets are attached to a line, ensureLineWrapped() replaces the line with <div style='position: relative'>. This causes major performance problems in if there are a lot of lines in the DOM, e.g. 13000.

Latency is so bad that individual characters in a textarea can be delayed 250ms in Chrome.

Removing the position:relative from ensureLineWrapped() fixes the performance problem, and doesn't really seem to break anything.

lineNumbers: true and viewportMargin: Infinity need to be enabled in this application.

Setting lineNumbers:false does avoid the position:relative wrapper on most lines, mostly fixing the performance problem, but we need lineNumbers:true.

Setting viewportMargin to a sane value matching the height of the browser window also fixes the problem, but is also unacceptable as users are demanding browser native search support and will not use any variation based on CodeMirror's search addons.

Tested in:
  Mac Chrome 43.0.2357.134
  Linux Chrome 43

Example:
  https://gist.github.com/spearce/a03aa2fb161fd94b0155

**Comment by marijnh** [comment]
Setting `viewportMargin` to infinity with huge documents is simply not supported by CodeMirror. The relative positioning is essential to the way we are displaying line numbers, and thus won't go away.
