### ISSUE TITLE
Issue with breakpoints

### ISSUE THREAD

**Issue by liquid2026** [codemirror/CodeMirror#3414]
If there was a breakpoint set, the width of the numbers are set to 1px.

Because display.lineNumInnerWidth was set to 1px in maybeUpdateLineNumberWidth()

To fix this change
      display.lineNumChars = display.lineNumInnerWidth ? last.length : -1;
to
      display.lineNumChars = display.lineNumInnerWidth > 1 ? last.length : -1;

and it will recalculate the position correctly.

**Comment by marijnh** [comment]
What do you mean by 'there was a breakpoint set'? Do you have a simple demonstration of the problem?
