### ISSUE TITLE
Create an addon.

### ISSUE THREAD

**Issue by ronaldohoch** [codemirror/CodeMirror#3416]
Hello!
How can I create an addon to prevent user to type scripts tag in html files?

**Comment by marijnh** [comment]
You'd first have to define exactly what it is you want to prevent from happening, and then probably register a `beforeChange` handler that implements this. How to do this, however, is something you'll have to work our yourself.

**Comment by ronaldohoch** [comment]
Thank you for the answer, but, there's a tutorial for it?

**Comment by marijnh** [comment]
No... there's the manual that explains the API, and you can look at other addons, but no, no one has written down how to do what you are trying to do here.
