### ISSUE TITLE
[css] Missing some common media query features and values

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/CodeMirror#3417]
Some common media query features are missing, resulting in "error" syntax highlighting colors.

It would be nice to support `device-pixel-ratio` and `orientation` for these common scenarios:

```css
/* iPhone, iPhone 3G/3GS portrait */
@media only screen and (min-device-width: 320px) and (max-device-width: 480px) and (-webkit-device-pixel-ratio: 1) and (device-aspect-ratio: 2/3) and (orientation: portrait) {
}

/* iPhone, iPhone 3G/3GS landscape */
@media only screen and (min-device-width: 320px)  and (max-device-width: 480px) and (-webkit-device-pixel-ratio: 1) and (device-aspect-ratio: 2/3) and (orientation: landscape) {
}
```

Taking a look at the CSS4 Media Query spec: (Currently in Draft)
https://drafts.csswg.org/mediaqueries-4/#media-descriptor-table

CodeMirror currently supports: (including min/max variants)

```
width <length>
height <length>
aspect-ratio <ratio>
resolution <resolution>
grid <mq-boolean>
color <integer>
color-index <integer>
monochrome <integer>
device-width <length>
device-height <length>
device-aspect-ratio <ratio>
```

CodeMirror does not support these non-standard but common features:

```
device-pixel-ratio: <integer> (and min/max)
```

CodeMirror does not support these draft CSS4 standard Media features:

```
orientation
    portrait | landscape

update-frequency
    none | slow | normal

overflow-block
    none | scroll | optional-paged | paged

overflow-inline
    none | scroll

inverted-colors
    none | inverted

pointer
    none | coarse | fine

hover
    none | on-demand | hover

any-pointer
    none | coarse | fine

any-hover
    none | on-demand | hover

light-level
    dim | normal | washed

scripting
    none | initial-only | enabled

scan
    interlace | progressive 
```

WebKit appears to support some of the above: (device-pixel-ratio, orientation, inverted-colors, pointer, hover, any-pointer, any-hover, light-level, scan). Not sure what you think is worth adding given the spec is still draft.

WebKit also includes one non-standard media query feature `-webkit-video-playable-inline`. No value is expected. Not sure if you want to add a vendor specific value though!

----

While in the area, CSS4 includes a `speech` media type.
https://drafts.csswg.org/mediaqueries-4/#valdef-media-speech

**Comment by marijnh** [comment]
I don't think we should be over-eager adding future spec stuff (since specs tend to change) but for properties that are widely supported (even if they are not standard), I'm okay with adding them. Want to open a pull request?

**Comment by JosephPecoraro** [comment]
Sure, I'll start on it.

There does appear to be decent support for some of these CSS4 ones already:
http://caniuse.com/#feat=css-media-interaction
