### ISSUE TITLE
Minimized JS Version Wanted

### ISSUE THREAD

**Issue by NgYueHong** [codemirror/CodeMirror#3420]
Hi,

The original codemirror.js file is HUGE which is about 341KB. It would be great if CodeMirror can come with minimized version together with it. This way developer will have the choice to load minify version with their webpage, so it will load a lot more faster.

Thank you.

**Comment by marijnh** [comment]
See the compression helper [here](http://codemirror.net/doc/compress.html).

**Comment by NgYueHong** [comment]
What I mean is putting the minify version together with the uncompressed version of JS together. This way we can easily use with bower install and use the minified version directly. Not manually custom minify it every-time we want to use it in project.

**Comment by marijnh** [comment]
You'll usually want to include multiple modules (modes, addon) in your site, so you'll need some kind of build step to reduce the amount of separate script files anyway. Just run UglifyJS locally as part of that build step.

**Comment by s100** [comment]
The [compression helper link](http://codemirror.net/doc/compress.html) seems to be broken now. What did it say?

**Comment by marijnh** [comment]
That was an HTML page providing a UI for creating a compressed version of the library. It is no longer supported -- you're expected to set up your own build system now

**Comment by melloware** [comment]
I just commented in the forums.  Is there anyway to provide an example script to combine everything into one script?  Maybe even put it on GitHub in the /examples folder?

**Comment by melloware** [comment]
Submitted this PR:  https://github.com/codemirror/CodeMirror/pull/4567
