### ISSUE TITLE
PHP Heredoc syntax

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3421]
(https://github.com/adobe/brackets/issues/11376)

According to http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc, a PHP Heredoc identifier can also be enclosed in double quotes (`"`) (see Example # 5).
Then, according to @valtlait, there can also be whitespace between the leading `<<<` and the identifier.

**Comment by MarcelGerber** [comment]
See also http://sandbox.onlinephpfunctions.com/code/531fbdd6f134c9d0621b16d75d0cabf7fd618280 for a little demonstration of it working.

**Comment by MarcelGerber** [comment]
Well, that's still not quite right.

From reading the docs, `<<<'END'` (single quote) is nowdoc (where variable names are not parsed), whereas `<<<"END"` is heredoc.

See also http://sandbox.onlinephpfunctions.com/code/45f208a8842d13d21a4bada8644e595a7000406f.

**Comment by marijnh** [comment]
Hah. Obscure. Does attached patch look good?

**Comment by MarcelGerber** [comment]
Yes, this looks about right.
Thank you!
