### ISSUE TITLE
[closetag addon] Implicitly closed tags cause incorrectly indented closing tags

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3422]
(https://github.com/adobe/brackets/issues/11382)

1. Go to http://codemirror.net/demo/closetag.html
2. Insert the code below
3. Place the cursor after `<ul`
4. Add the missing `>`

``` html
<p>
  <ul
</p>
```

Result:
The `</ul>` closing tag is not indented.

Expected:
The `</ul>` closing tag is indented 2 spaces.

That's because `<p>` is one of HTML's [implicitly closed tags](https://github.com/codemirror/CodeMirror/blob/bd6268517d65cab1a1a5239c30f8ca68719089d2/mode/xml/xml.js#L25-L27), which are handled specially in `indentLine`.

**Comment by marijnh** [comment]
I am not sure if you can really blame this on the closetag addon. The problem is that the opening `<ul>` isn't reindented, but since the closetag addon did not insert that, I don't think it is responsible for reindenting it.
