### ISSUE TITLE
Accessibility Patch in CodeMirror

### ISSUE THREAD

**Issue by vedanshujain** [codemirror/CodeMirror#3429]
Hi
So I've created a hackish kind of patch for enabling screen reader to read the contents of editor. As far as I have checked this is working fine for me, at least for my purposes. Can someone check/test this out so that I can convert into a proper patch and raise a pull request after making necessary changes. 
Thanks

Just include this in your source code:

https://gist.github.com/ce244ac29072c267bd18

Please note that if you insert an html element with aria-live tag dynamically, it won't be picked by some AT unless it is present in the source code at the time of first rendering.

**Comment by marijnh** [comment]
Have you tried setting the option `inputStyle: "contentEditable"`? That should give you much  better results.

**Comment by vedanshujain** [comment]
I tried it out but I was having problem with VoiceOver in Mac. On NVDA it was usable though.

**Comment by marijnh** [comment]
Okay. But this patch doesn't really look like a viable direction. I'd much rather continue working out problems with the contenteditable input style, which provides the browser with much more information (and thus probably requires less invasive hacks).
