### ISSUE TITLE
CodeMirror.defaults doesn't work

### ISSUE THREAD

**Issue by ingro** [codemirror/CodeMirror#3430]
Hello, I'm trying to use the defaults object but it seems like it's ignored, here is a sample code:

```html
<html>
<head>
	<meta charset="UTF-8">
	<title>Codemirror test</title>
	<link rel="stylesheet" href="css/codemirror.css">
	<link rel="stylesheet" href="css/theme/dracula.css">
</head>
<body>
	<div id="editor"></div>

	<script src="js/codemirror.js"></script>
	<script src="js/mode/htmlmixed/htmlmixed.js"></script>
	<script src="js/mode/xml/xml.js"></script>
	<script>
		CodeMirror.defaults = {
			lineNumbers: true,
			theme: 'dracula'
		};

		CodeMirror(document.getElementById('editor'), {});
	</script>
</body>
</html>
```

The generated editor has the default theme and no line numbers.

**Comment by marijnh** [comment]
Don't assign to `CodeMirror.defaults`. You can override individual properties on that object, but it has to contain the defaults for all defined options, so replacing it with a new object does not work (CodeMirror will continue using the old object)

**Comment by ingro** [comment]
Thanks for the insight, I didn't understand that reading the docs.
