### ISSUE TITLE
Improvements for search/replace

### ISSUE THREAD

**Issue by sirtet** [codemirror/CodeMirror#3431]
Just used the search/replace feature, and had some ideas for improvements:

* Add keyboard shortcuts for the Yes/No/Stop buttons
* Add "Yes to all" button
* Scroll the current match into viewport

**Comment by marijnh** [comment]
The current match _should_ be scrolled into the viewport. Can you describe what you did that resulted in a match not being visible?

**Comment by sirtet** [comment]
Scroll did not work: Not sure, but trying to replicate the effect, i think it was a match on line 1, which was covered by the dialogue itself...

Plus a new thing i saw:
The existing _replace all_ function is saying "replace" in the dialogue, same as the _replace_ function... maybe change this to "replace all"? or, it would be kind of obsolete if there was the proposed "Yes to all" button on the _replace_ function.

Did i mention? CodeMirror is awesome, thanks!

**Comment by marijnh** [comment]
I've made some adjustments (attached patches). The scroll issue you are seeing does exists when

 - You use the persistent dialog
 - Your match is on the first line of the editor

Our current dialog addon doesn't provide a proper way to work around this, but I've pushed a hack that make the dialog transparent when this happens.
