### ISSUE TITLE
Keyboard shortcuts (or maybe just `ctrl-space`) not working on Ubuntu?

### ISSUE THREAD

**Issue by timbur** [codemirror/CodeMirror#3432]
When trying out the auto-completion demos [here](http://codemirror.net/demo/), I'm unable to trigger it on Ubuntu using the latest Chrome or Firefox.  It works for me on Windows though.

**Comment by marijnh** [comment]
I have no issue on Debian Chrome/Firefox. Probably your window manager or other external program (IME modules like to use ctrl-space as well) is capturing the key.

In any case, this is external to this library, and ctrl-space isn't even a default binding in CodeMirror. Closing this.
