### ISSUE TITLE
sublime indent selection

### ISSUE THREAD

**Issue by MasseGuillaume** [codemirror/CodeMirror#3444]
in sublime when you highlight multiple lines and press tab those lines get indented.
in codemirror the lines get deleted and a tab is inserted.

**Comment by vincentwoo** [comment]
This doesn't appear to be true on https://codemirror.net/demo/sublime.html. When I highlight multiple lines by cmd + triple clicking and hit tab, they get indented. Can you make a JSFiddle repro case or explain how to cause the issue on the linked page?

Are you using the sublime bindings? CodeMirror doesn't behave like sublime by default, you have to tell it to.

**Comment by MasseGuillaume** [comment]
oh that's correct. I was using `"Tab": "insertSoftTab"`
