### ISSUE TITLE
`System` support

### ISSUE THREAD

**Issue by timbur** [codemirror/CodeMirror#3446]
I'm using [`systemjs`](https://github.com/systemjs/systemjs) which is built on top of [`es6-module-loader`](https://github.com/ModuleLoader/es6-module-loader) which is a polyfill implementation of the [`ES6 module loader spec`](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#august_24_2014_draft_rev_27).

`CodeMirror` rightly detects `cjs` when dynamically loading modes and all that, and it's awesome, except for one thing:  `systemjs` [throws an exception](https://github.com/systemjs/systemjs/blob/73bef11de4eff9aa30897b2c791d298a85503633/lib/register.js#L379) when trying to `require` an unmapped dependency.  I could go through the trouble of some complex `systemjs` configuration, and I've copied/rewritten portions of `CodeMirror` addons to use `System.import` instead (since it works for me), but I've realized that the best/easiest solution would be to just check for `System.import` within this block of code:

```js
(function(mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
    mod(require("../../lib/codemirror"), "cjs");
  else if (typeof define == "function" && define.amd) // AMD
    define(["../../lib/codemirror"], function(CM) { mod(CM, "amd"); });
  else // Plain browser env
    mod(CodeMirror, "plain");
})(function(CodeMirror, env) {
  /* ... */
});
```

Which would mean essentially changing it to:
```js
(function(mod) {
  if (typeof System == "object" && typeof System.import == "function")  // System
    System.import("codemirror").then(function (CM) { mod(CM, "system"); });
  else if (typeof exports == "object" && typeof module == "object") // CommonJS
    mod(require("../../lib/codemirror"), "cjs");
  else if (typeof define == "function" && define.amd) // AMD
    define(["../../lib/codemirror"], function(CM) { mod(CM, "amd"); });
  else // Plain browser env
    mod(CodeMirror, "plain");
})(function(CodeMirror, env) {
  /* ... */
});
```

And then where applicable:
```js
  if (env == "system") {
    System.import(file).then(cont);
  }
```

I kinda hate that there are so many different ways to load modules but I suppose that's the precise problem the spec is trying to solve.  If you @marijnh think these minor changes are a good idea and would be so kind to point me to how/where that top block of code is (presumably) generated, I'd be happy to submit a PR with all the changes where applicable.

**Comment by marijnh** [comment]
That code is not generated. I am really not interested in adding another clause there and bloating up the file headers even further. You'll have to hack something up, like passing the loadmode addon a wrapped version of `require` that does the right thing in your setup.

**Comment by matt-mcdaniel** [comment]
@timbur Can you upload your implementation? It might be helpful for others to see a workaround.

**Comment by timbur** [comment]
It's been months since I've looked at this so I've forgotten what I did exactly, but @matt-mcdaniel I think this might be what you're looking for: https://github.com/loggur/branches/blob/master/config.codemirror.js
