### ISSUE TITLE
diff_match_patch is not a constructor when using Require.js

### ISSUE THREAD

**Issue by clintmilner** [codemirror/CodeMirror#3447]
I have a project using Require.js (ver 2.1.18) where I'm using CodeMirror (ver 5.5.1) to view/edit a JavaScript file in the browser (this and all CodeMirror addons work as expected).

I now need to show any diffs in the file, so I've been trying to implement the merge.js addon, but having troubles with the diff_match_patch.js lib that is also required.
```javascript
// Firebug + Firefox 39.0.3
// merge.js
// (line 550, col 12)
"TypeError: diff_match_patch is not a constructor
var dmp = new diff_match_patch();"
```
```
// Chrome Version 44.0.2403.130 (64-bit)
// merge.js (551)
"Uncaught TypeError: diff_match_patch is not a function"
```

I can see that diff_match_patch.js is being loaded by Require, but when passed to that function in merge.js, the JavaScript error breaks the page. The Merge view doesn't show.
Changing the line 
``` 
var dmp = new diff_match_patch();
``` 
to
```
var dmp = diff_match_patch;
```
allows the 2 views to render, but the dmp.diff_main map is not created.

**Comment by marijnh** [comment]
Unfortunately, `diff_match_patch` isn't packaged very well -- it doesn't know that there is such a thing as module loaders, and just assumes that it is okay to dump four variables into global scope.

I managed to get it working with a small change to `merge.js` (which tried to access diff_match_patch through an interface object). See [this gist](https://gist.github.com/marijnh/fe4b132e254d4dc311ba) for the working requirejs-based code.

**Comment by clintmilner** [comment]
Thanks @marijnh - working great on my end too!

**Comment by ajinkyasurya** [comment]
@marijnh Is that gist still valid? It does not render any view for me.
Also @clintmilner assuming you are using typescript, how did you declare a global variable? 
I added
```
"@types/diff-match-patch": "^1.0.32",
"diff-match-patch": "^1.0.1"
```
to my package.json but I still get
```
ERROR ReferenceError: diff_match_patch is not defined
    at getDiff (merge.js:649)
    at DiffView.init (merge.js:52)
    at new CodeMirror.MergeView (merge.js:570)
    at Function.CodeMirror.MergeView (merge.js:536)
```

**Comment by clintmilner** [comment]
@ajinkyasurya I dumped Require.js about a year ago, and I can't find the commit where I had this + Require.js working. I do know that I was wasn't importing CodeMirror-related files vai a package.json file. Perhaps try importing manually?

**Comment by thecere** [comment]
Hacking the globals with webpack, works for me:

```
new webpack.ProvidePlugin({
    diff_match_patch: 'diff-match-patch',
    DIFF_EQUAL: ['diff-match-patch', 'DIFF_EQUAL'],
    DIFF_INSERT: ['diff-match-patch', 'DIFF_INSERT'],
    DIFF_DELETE: ['diff-match-patch', 'DIFF_DELETE'],
}),
```
