### ISSUE TITLE
showHint's close() event to include reason

### ISSUE THREAD

**Issue by cgrushko** [codemirror/CodeMirror#3448]
I'd like to know if a hint's close event was called because an option was chosen, or because of hitting Escape. 

I think the easiest would be to pass the chosen object in a close event if there was one, otherwise undefined. (line 59, 79, 64 in show-hint.js).

@marijnh if you're ok with this, I'll send a pull-request? Thanks!

**Comment by marijnh** [comment]
Doesn't listening to the `"pick"` event solve this? It'll be fired right before the `"close"` event when a completion is chosen.

**Comment by cgrushko** [comment]
I want to know when a completion is abandoned (user hit the Escape key).

**Comment by marijnh** [comment]
Set a flag when the `"pick"` event happens, and in the `"close"` handler, check for this flag to figure out what kind of close event it is.

**Comment by cgrushko** [comment]
This relies on the fact that the `pick` event is sent before the `close` event does. Moreover, it depends on the order they arrive. 
Is it guaranteed they arrive in this order?
I think it's easier and more error-proof to explicitly send the reason for closing; something like

    CodeMirror.signal(this.data, "close", data);

**Comment by marijnh** [comment]
Yes, `pick` is guaranteed to be fired before `close`, and events arrive in the order they are fired in.
