### ISSUE TITLE
indent error with Tab

### ISSUE THREAD

**Issue by Tedko** [codemirror/CodeMirror#3449]
![12](https://cloud.githubusercontent.com/assets/6687437/9217844/26326e76-40ff-11e5-9dd1-a25019941108.gif)

when I input 2 tabs here, and hit del, the second tab will be removed but the 1st one will not be removed.

**Comment by vincentwoo** [comment]
Are you using the sublime keymappings? This issue is reproducible here: https://codemirror.net/demo/sublime.html is probably my fault when I introduced the "smart backspace" behavior.

**Comment by JasinYip** [comment]
But if I locked(set `readOnly: true` by using `markText`) the code, it can not be deleted.

**Comment by vincentwoo** [comment]
I'm sorry, can you explain more about readOnly? What is it? The tab? Which tab is readonly and which one is not? Can you make a http://jsfiddle.net/ to demonstrate?

**Comment by Tedko** [comment]
@vincentwoo  The read-only tab is the one(the second tab) will be delete in this situation. Readonly means that certain text in this block should not be modified by our user (such as ```#include ```in C)

but if we locked the tab in such case ```(tab) static void abc()  ``` in order to make a readable indent, the user may insert a tab before the read-only tab by mistake. In such case, the user cannot delete that tab by hit delete.

Could you offer a switch for this  "smart backspace"  function? it's definitely useful in some case, but if we want to limited the action of users, a switch will be helpful.

**Comment by marijnh** [comment]
Keybindings can always be reconfigured, so there's no need for an extra switch.

As for the underlying problem, I still don't understand your use case, but if you can provide a minimal demo page that would probably clear it up.
