### ISSUE TITLE
A new CoffeeScript mode for CodeMirror

### ISSUE THREAD

**Issue by huaoguo** [codemirror/CodeMirror#3450]
I made a new CoffeeScript mode for CodeMirror [https://github.com/huaoguo/codemirror-coffee-script](https://github.com/huaoguo/codemirror-coffee-script). Hope it would be useful.

# Screencasts

![monokai](https://raw.githubusercontent.com/huaoguo/codemirror-coffee-script/master/demo/monokai.png)

![material](https://raw.githubusercontent.com/huaoguo/codemirror-coffee-script/master/demo/material.png)

**Comment by marijnh** [comment]
Hi. Could you tell me how this improves on the existing CoffeeScript mode? And is your intent to have this become part of the main distribution?

**Comment by huaoguo** [comment]
This mode implements all the CoffeeScript language specifation, like:
* and、is、or... keywords will be highlight
* Class(capital word) will be highlight
* method def will be highlight
* properties will be highlight
* module、exports、require (commonjs) will be highlight
and so on...

It make the highlight more comprehensive.

Yes, I want let it become part of the main distribution.

**Comment by marijnh** [comment]
I've taken a closer look, but your mode doesn't do any indentation, which seems a regression. Have you considered simply modifying the old mode to fix its shortcomings? I've pushed 89c8c3d, which highlights properties as properties. I noticed that operators like `and` and `is` are already highlighted as operators (choose a different theme if you want a different color for them).

**Comment by marijnh** [comment]
Closing until further comments.
