### ISSUE TITLE
chat room

### ISSUE THREAD

**Issue by MasseGuillaume** [codemirror/CodeMirror#3451]
Hi @marijnh, is it possible to create a gitter.im room for codemirror ?

https://gitter.im/codemirror/CodeMirror

**Comment by marijnh** [comment]
I've activated this room. I don't know much about gitter, but I'll try to drop in now and then.

**Comment by MasseGuillaume** [comment]
@marijnh thanks a lot I will spend some time there to answer questions  ;-)
