### ISSUE TITLE
Search with regex replacement

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#3456]
I tried the search demo here: http://codemirror.net/demo/search.html.
I wanted to replace some char with a newline:
- pressed Ctrl-Shift-R
- written `<dd>` in the text box and pressed enter
- written `\n` in text box and pressed enter

Actual result:
`<dt id="option_indentWithTabs"><code><strong>indentWithTabs</strong>: boolean</code></dt>`
`\nWhether, when indenting, the first N*<code>tabSize</code>`

Expected result:
`<dt id="option_indentWithTabs"><code><strong>indentWithTabs</strong>: boolean</code></dt>`
` `
`Whether, when indenting, the first N*<code>tabSize</code>`

I tried with `/<dd>/` but the result was the same.

**Comment by marijnh** [comment]
The input field takes the raw replacement text. Backslash escapes aren't interpreted, and there's no reason to believe that they would be. I agree that it would be useful to be able to insert newlines, but I don't think doing some ad-hoc backslash interpretation is the answer. A better proposal or a clean pull request would be welcome.

**Comment by ficristo** [comment]
The simplest, and maybe silliest thing that comes to my mind, is to detect only the `\r` and `\n` and replace them with the `CR` and `LF` characters respectively.
If the user writes `\\r` or `\\n` (two backslash) it will be inserted `\r` or `\n` (one backslash).
I don't think I can help, however where is the code used for this operation?
(I know almost nothing about CodeMirror apart is used in Brackets)

**Comment by ficristo** [comment]
Thanks for patch!
One question though: the replacement with new lines should work only with the regular expression otherwise should work normally, for example inserting exactly the char `\` followed by `n`.
Can you confirm?

**Comment by marijnh** [comment]
I don't think I agree. Why should it only work when replacing a regular expression? You might also want to replace some string with a newline.

**Comment by ficristo** [comment]
IMHO there are two way in which find and replace should work:
normal: I search some string and replace them with the one wanted exactly as they are. So if I searched `foo` and replaced with \n, I expect to see the char `\` followed by `n` instead of foo.
regex: in this case if I searched `foo` and replaced with `\n`, I expect to see a new line instead of foo.
But if I replaced with `\\n`, I expect to see the char `\` followed by `n` instead of foo.

(My english isn't very good, I hope I have been clearer than before)

**Comment by marijnh** [comment]
I think the behavior you are proposing is horrible (inconsistent parsing of input in two different situations) and I am not going to change this.

**Comment by ficristo** [comment]
As far as I can tell It is the same behaviour of Netepad++, Sublime Text 2 and Netbeans.

**Comment by ficristo** [comment]
If you really disagree in the behaviour I asked, I think the patch should be reverted: it adds an unexpected behaviour in the "normal" case.
Instead, an help on how to implemented the behaviour I asked using the CodeMirror API would be really appreciated.
Let's say for example I have called this cm.replaceSelection(replaceText), how could I insert the new line?
Thanks for the patience.

**Comment by marijnh** [comment]
I don't see how you are claiming that this is expected behavior in one case and not in an almost identical one. There is no API to implement this from outside, short of reimplementing the search addon. The patch is not going to be reverted.

**Comment by ficristo** [comment]
Because most of code editor work as I said, while as far as can i understand now codemirror has an odd behaviour: that is way I think is unexpected
.
