### ISSUE TITLE
How can I highlight the selected code which had been marked?

### ISSUE THREAD

**Issue by JasinYip** [codemirror/CodeMirror#3461]
I had change the background for a part of code by `cm.markText`:

``` javascript
cm.markText(from, to, { css: 'background: #ccc; color: #978046;' })
```

![image](https://cloud.githubusercontent.com/assets/7105264/9379446/d7b5913e-475b-11e5-98d6-e5eb5caed7f9.png)

But if I select some code in that part of code, it will have no background changed.

For example, when I select `14549`, it will looks like:

![image](https://cloud.githubusercontent.com/assets/7105264/9379675/73334538-475d-11e5-96b7-d95ffb8c7dfd.png)

`1454` will not be highlight. It there anyway I can highlight it? Thanks a lot :smile: !

**Comment by marijnh** [comment]
Try enabling the [mark-selection](http://codemirror.net/doc/manual.html#addon_mark-selection) addon

**Comment by JasinYip** [comment]
Thank you very much! It works ! :)
