### ISSUE TITLE
CodeMirror css issues inside Chrome Extension

### ISSUE THREAD

**Issue by redraw** [codemirror/CodeMirror#3466]
I'm using CodeMirror inside a Chrome extension, actually, it's loaded on a content script context.
The problem is that when another site uses its own CodeMirror, it overrides my CodeMirror css style, because both uses `.CodeMirror` class.

What should be a right way to custom my CodeMirror css without interfering with another website's CodeMirror style?

**Comment by marijnh** [comment]
Have you looked into using a shadow DOM? I haven't used it seriously, but I believe it allows scoped CSS. https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM

**Comment by redraw** [comment]
I'll take a look at it, thanks ! :)

**Comment by redraw** [comment]
well, it's not so easy to integrate CodeMirror into a Shadow DOM as I thought, I'll keep finding a way

**Comment by WraithKenny** [comment]
I know this is old, but if you use LessCSS, you can easily scope the entire lib with  

```
.myplugin { 
    @import (less) "codemirror.min.css"; // Pre-bundled, or list all files here.
}
``` 

such that all of your rules will only apply to a CodeMirror that's a descendant of `<div class="myplugin">` .

(Other extensions would have to opt in to this scheme for theirs to not clobber yours, however, you'd be a good citizen.)
