### ISSUE TITLE
[markdown mode] continued quote in a list styled as increasingly nested quotes

### ISSUE THREAD

**Issue by cben** [codemirror/CodeMirror#3473]
http://codemirror.net/mode/markdown/

```
-   list
    > quote-1
    > quote-2?
    > quote-3?!
    still quote-3
```

[[babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+++list%0A++++%3E+quote-1%0A++++%3E+quote-2%3F%0A++++%3E+quote-3%3F!%0A++++still+quote-3%0A) showing these should be parsed as continued 1st-level quote.]

Doesn't happen with quotes at top level.

**Comment by dwelle** [comment]
we can close since it appears to work correctly now

**Comment by marijnh** [comment]
Great!
