### ISSUE TITLE
special characters in codemirror.js prevent reencoding the entire file

### ISSUE THREAD

**Issue by michael-gollmick** [codemirror/CodeMirror#3474]
at least line 6955 if codemirror.js in the current stream contains invalid characters that are displayed differently in different editors. While this website displays them as CR and NL, text editors show them as an 'a' character with some very special umlaut sign. Eclipse even says the file cannot ever be edited as the character encoding cannot be converted into the systems internal character encoding.

If the characters in this line are really meant to be CR and NL why aren't the written as \r resp. \n?

**Comment by marijnh** [comment]
They are validly encoded UTF-8 characters. Blame your tools or your setup for decoding them incorrectly.

But since this happens a lot, our policy is to `\u`-escape such characters, which I failed to do in this case. Attached patch fixes this.

**Comment by michael-gollmick** [comment]
great, thank you.
