### ISSUE TITLE
How can I clear all addLineClass?

### ISSUE THREAD

**Issue by MojoDK** [codemirror/CodeMirror#3477]
Hi

Is there a command to clear all addLineClass?

Thanks.

**Comment by marijnh** [comment]
You can call `removeLineClass` and pass `null` as the class.

**Comment by MojoDK** [comment]
Sry for not being clear...

If I have this code...
myEditor.addLineClass(23, "background", "error");
myEditor.addLineClass(25, "background", "error");
myEditor.addLineClass(29, "background", "error");

... how can I without knowing the linenumbers, clear all the addLineClass above?

Thanks

**Comment by marijnh** [comment]
You can't, but you could loop over all lines that might have the class and remove it from them.
