### ISSUE TITLE
what level of CSS is supported in mode/css.js?

### ISSUE THREAD

**Issue by michael-gollmick** [codemirror/CodeMirror#3480]
while editing one of my CSS files in CodeMirror I realized a CSS4 property (namely background-position-x) not being highlighted as expected. I then realized this was a CSS Level 4 property and wondered what Level of the CSS specification is supported?

**Comment by cbaldwinweb** [comment]
Do any browsers even support CSS4 yet?

**Comment by michael-gollmick** [comment]
Support seems to be partly implemented. So, specifically background-position-x and background-position-y properties are supported by some browsers and not supported by others. When I saw this, I was just wondering if there's a certain level that is supported.

**Comment by cbaldwinweb** [comment]
You can add these by going to the file modes/css.js and find this variable `propertyKeywords_` and add the properties themselves. You can look through that file and add values if there are new CSS4 values as well.

**Comment by marijnh** [comment]
We're currently targeting things that are implemented and/or in use, regardless of the spec level. So if you have specific properties that come up in reality that you'd like to add, open a bug or a pull request.

**Comment by baconface** [comment]
There are a small handful CSS4 classes supported on most modern browsers such as Placeholder pseudo-class, Scope pseudo-class, Matches-any pseudo-class, Range pseudo-class and a few others. But there is still a lot of the spec not yet implemented.

**Comment by marijnh** [comment]
Closing as being a question rather than an issue. PRs to add support for specific features would be appreciated.
