### ISSUE TITLE
Cannot place cursor inside Farsi string if line wrapping is enabled

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3489]
(https://github.com/adobe/brackets/issues/11612)

1. Go to http://codemirror.net/demo/activeline.html
2. Paste the below markup in
3. Try to place the cursor anywhere in the Farsi string using the mouse

Result:
You can only ever reach the very beginning or the very end of the Farsi string.

Note:
This does only happen with `lineWrapping: true`

``` html
<div class="col-md-4">
                    <p>
                     لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیستری را برای طراحان رایانه ای و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                     </p>
                </div>
```

**Comment by Netman82** [comment]
Where do i paste that piece of code?
I pasted it after <html> - and next time at the end of markup - and i brought up some none-scence texts:
<code>
codemirror: http://cloud-ide.com — they're springing up like mushrooms. This one uses CodeMirror as its editor. Thu, 17 Mar 2011 23:34:47 +0000 http://twitter.com/codemirror/statuses/48527733722058752 http://twitter.com/codemirror/statuses/48527733722058752 web codemirror: Posted a description of the CodeMirror 2 internals at http://codemirror.net/2/internals.html Wed, 02 Mar 2011 12:15:09 +0000 http://twitter.com/codemirror/statuses/42920879788789760 http://twitter.com/codemirror/statuses/42920879788789760 web
</code>
Beside twitter is censored in my country so it's no gonna be useful.
Don't guys in Brackets decide to solve this? I've seen many other Iranians and Arabs complaied already.

**Comment by MarcelGerber** [comment]
You can find the link above.
Brackets uses CodeMirror as its main editing component and thus, such fixes will need to go into CodeMirror and can then be picked up in the Brackets code base.

**Comment by Netman82** [comment]
That won't work for me, I need a solution INSIDE brackets not in that link. thanks for trying tho.

**Comment by marijnh** [comment]
This is a known issue (#1757). We had a Google summer of code student working on this a few years ago, but his work (the `direction` branch) never made it to production quality and he pretty much stopped responding to email.

This is one of those things that are not going to happen unless someone contributes the code or a significant bit of money.

**Comment by marijnh** [comment]
Going to close this as a duplicate.
