### ISSUE TITLE
Cursor cannot be positionned correctly

### ISSUE THREAD

**Issue by xperseguers** [codemirror/CodeMirror#3495]
In an extension I am developing for the TYPO3 community, I'm using CM to provide editing facility for reStructuredText documents.

This bug was reported with CM 5.4 but I know of it since many versions, just did never report it yet.

Here's the description I got from https://forge.typo3.org/issues/69467:

If I want to make a modification I point my cursor to where the modification should be made and hit the enter key (or spacebar).

99% of the time the result is frustration: the hard return is not inserted at the place where I placed my cursor, but breaks up the code randomly on the page. Sometimes it's near the place where I placed my cursor, more often it is not, and I need to search the hole text to find the position where I can start typing.

It's also hard to position my cursor in the source code. It's often not possible to reach certain areas in the source code at first (you simply can't place your cursor there). If I try to maneuverer using the arrow keys certain lines are skipped.
The solution is hit enter first (resulting in a source code break up described above, then it works fine).

CM editor is embedded into some js-based "frames" (or panel) and I wonder if this could cause some (known) side-effect with the position of the cursor. As described, after a first (faulty) edit, the cursor can then be properly positionned and editing works fine.

**Comment by marijnh** [comment]
Sounds like this may be a missing call to [`refresh`](http://codemirror.net/doc/manual.html#refresh) after changing the size of the editor's container (maybe there's a CSS animation involved).

**Comment by xperseguers** [comment]
Thanks for the hint, will try and report back.

**Comment by xperseguers** [comment]
Could not reproduce anymore but the original reporter tried my fix and it works. Thanks a lot for your hint.
