### ISSUE TITLE
Replace in selection only

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#3503]
Is there a way to replace text only in the selected code?
As far as I can understand there are API to get the selected code, but not to replace text only in the selected texts.

**Comment by djadmin** [comment]
There is an API to replace the selection(s) with a given string 
> doc.replaceSelection(replacement: string, ?select: string)

A simple example is given below which will replace the selection with the given string.
`editor.replaceSelection(replaceStr); `.
Please refer the manual (http://codemirror.net/doc/manual.html) for more information.

**Comment by ficristo** [comment]
Sorry, I should have been clearer.
I do not want to replace all the selection.
If I select some code, and then I search something, I want the search, and therefore the replace, work only in the selected code.

**Comment by marijnh** [comment]
Use the `addon/search/searchcursor.js` addon and do something like this (untested):

```javascript
function replaceAllIn(cm, oldString, newString, start, end) {
  var cursor = cm.getSearchCursor(oldString, start)
  while (cursor.findNext() && CodeMirror.cmpPos(cursor.to(), end) <= 0)
    cursor.replace(newString)
}
```
