### ISSUE TITLE
What happend with autoClearEmptyLines option?

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [codemirror/CodeMirror#3506]
I don't see this option in actual manual and don't see in release notes that this option was removed, we have only:
27-02-2012: Version 2.22:
Add autoClearEmptyLines option. 
and description in old manual:
http://codemirror.net/2/doc/manual.html#option_autoClearEmptyLines

Any chance to restore this option?

**Comment by marijnh** [comment]
This was dropped in 3.0 (a387b8336767aba3), as it was somewhat flaky (it'd also kill pre-existing trailing whitespace -- but only if you moved your cursor through a line) and had very few users.

You could re-implement it as an external addon like this:

```javascript
CodeMirror.defineOption("autoClearEmptyLines", false, function(cm, value) {
  if (value && !cm.state.clearEmptyLines) {
    cm.state.clearEmptyLines = {prev: cm.getCursor()}
    cm.on("cursorActivity", maybeClearLines)
  } else if (!value && cm.state.clearEmptyLines) {
    cm.off("cursorActivity", maybeClearLines)
    cm.state.clearEmptyLines = null
  }
})

function maybeClearLines(cm) {
  var cursor = cm.getCursor()
  var prev = cm.state.clearEmptyLines.prev, prevLine
  if (cursor.line != prev.line && prev.line <= cm.lastLine() &&
      (prevLine = cm.getLine(prev.line)) && !/\S/.test(prevLine))
    cm.replaceRange("", new CodeMirror.Pos(prev.line, 0), new CodeMirror.Pos(prev.line, prevLine.length))
  cm.state.clearEmptyLines.prev = cursor
}
```
