### ISSUE TITLE
Issue with lintOnChange

### ISSUE THREAD

**Issue by NessBird** [codemirror/CodeMirror#3512]
Hi!  Thanks VERY much for the excellent editor :)

I have reproduced this in Chrome and FireFox on Mac OS X.

When I set the lintOnChange Option, I expect linting not to respond to changes in the editor text, but linting continues as changes are made.

In the demo, I set the option in demo/lint.html, as indicated below:

  var editor = CodeMirror.fromTextArea(document.getElementById("code-js"), {
    lineNumbers: true,
    mode: "javascript",
    gutters: ["CodeMirror-lint-markers"],
    lint: true,
      lintOnChange: false
  });

**Comment by NessBird** [comment]
Oh -- this is appears to be version 5.4, based on CodeMirror/doc/releases.html.  I'm using the copy of the lint files in CodeMirror/demo/lint_files, because it appears to be more up-to-date than the one in CodeMirror/addon/lint.  The addon one doesn't include performLint().

**Comment by NessBird** [comment]
Hm.  Looks like I'm not on the most recent version!  I'll check if it works now.

**Comment by NessBird** [comment]
Same problem, at least in Chrome.

**Comment by amshali** [comment]
@NessBird I am using this lint option and it works fine for me. I think I see what is wrong in your situation.
You should use it like this:
```
      lint: {
        lintOnChange: false
      },
```

**Comment by NessBird** [comment]
Thank you!  I'm sure that will fix my problem.

May I suggest a change in the docs?  My JavaScript experience is pretty limited...so I'm learning JS terminology and ways of thinking while I'm configuring CM.  It would help if the docs were explicit about what is meant by things like: "Linting on every change can be disabled by setting the lintOnChange option to false."

I would be happy to submit changes to docs if that would be appreciated.  Do you think it would be?

**Comment by amshali** [comment]
@marijnh Thanks.
