### ISSUE TITLE
palette.js doesn't work well in the current CM version

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [codemirror/CodeMirror#3515]
Hi, palette.js addons provide nice indicator for colors. Its missing in actual addons folder, but exist in older branch:

http://www.jeditoolkit.com/CodeMirror/demo/palette.html << live example
https://github.com/Gozala/CodeMirror/blob/addon/palette/addon/display/palette.js << code

I see that its works correct for CodeMirror.version = "3.21.1" (look example above) but when I update CM to actual version I get problem when pasting code. Steps for reproduce:

1. Open http://www.jeditoolkit.com/CodeMirror/demo/palette.html (save them ass complet page and change CM to new version).
2. Copy example code from editor, remove this code from editor, and again past code to editor.
3. Indicator for colors aren't show up, we must make some trick, like 2 times past code and make one undo, or manualy goes to end of color value and press some key (its show up), or change actual line before color value, etc.

This is very annoying, if you figure out how fix above problem please write.

**Comment by marijnh** [comment]
This is the bug tracker for the main distribution of CodeMirror -- support for branches that aren't in that distribution, or that other people created, isn't something that you're going to find here.
