### ISSUE TITLE
[docs] Where to put 3rd party addons?

### ISSUE THREAD

**Issue by matthewbauer** [codemirror/CodeMirror#3520]
I've got some CodeMirror addons that might be useful to some people:

* [load-share](https://github.com/matthewbauer/editor/blob/master/load-share.js) - attach a ShareJS context to a CodeMirror editor
* [soft-nav](https://github.com/matthewbauer/editor/blob/master/soft-nav.js) - use "soft" tabs for navigation
* [detect-indent](https://github.com/matthewbauer/editor/blob/master/detect-indent.js) - detect indention
* [detect-mode](https://github.com/matthewbauer/editor/blob/master/detect-mode.js) - detect mode based on file extension

Is there a good place to put these? Originally, I wanted to get them merged in, but they all require external dependencies.

**Comment by marijnh** [comment]
List them on [our wiki](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons)
