### ISSUE TITLE
Change text before putting into clipboard

### ISSUE THREAD

**Issue by yapcheahshen** [codemirror/CodeMirror#3524]
Could we have a event handler which allow changing of text to be put into clipboard:

"beforeCopyToClipboard" (instance: CodeMirror, text: string, event: Event)
modify selected text by returning a new string.

which enable adding the source information of where the text is copied.
e.g:
"the selected text" from [filename]:[line]

**Comment by marijnh** [comment]
This would require a rather invasive change (to the already fragile clipboard-handling code), and your use case doesn't sound very compelling (people tend to want the text they selected on their clipboard, without extra junk), so I'm going to say no.
