### ISSUE TITLE
Click event on TextMarker

### ISSUE THREAD

**Issue by cha55son** [codemirror/CodeMirror#3529]
I'm creating text markers within CodeMirror but I can't seem to find a good way to detect click events within the markers. CM doesn't seem to provide access to the DOM node which makes sense. Therefore is there a good way to catch click events within a marker? I've tried `beforeCursorEnter`, which strangely is triggered on click but is called twice. I've also tried `cm.on(marker, 'mousedown', fn)` with no luck. Could someone shed some light on this?

**Comment by marijnh** [comment]
The best way to handle this is to register a `mousedown` handler on `editor.getWrapperElement()`, and in there, use the `coordsChar` method to figure out what text was clicked, and then the `findMarksAt` method to figure out whether there's a marker you're interested at at that position.

**Comment by cha55son** [comment]
Posting here for others who care to do something similar. Everything works great, thanks @marijnh!

```
 cm.getWrapperElement().onmousedown = function(e) {
    var lineCh = _cm.coordsChar({ left: e.clientX, top: e.clientY });
    var markers = _cm.findMarksAt(lineCh);
    if (markers.length === 0) { return; }
    ... do stuff with markers ...
```
