### ISSUE TITLE
auto resizing issues

### ISSUE THREAD

**Issue by chrisdrackett** [codemirror/CodeMirror#3537]
I'm trying to match the auto resize example and I'm running into issues. I have viewportMargin set to `Infinity` and .CodeMirror has a height of `auto`. For some reason however my editor is setting its size to be equal to the viewport height.

**Comment by marijnh** [comment]
Can you provide an HTML file that demonstrates the problem? Does [the demo](http://codemirror.net/demo/resize.html) also have this issue for you?

**Comment by jmuharsky** [comment]
I am seeing this issue as well; it's not clear what the "demo" is supposed to be doing in this case, so I can't say if it's working.  I've created a jsfiddle that demonstrates buggy behavior (option #1) with height: auto, and "working" behavior (option #2) with an explicit height set.

https://jsfiddle.net/jmuharsky/kpza6wuu/

**Comment by marijnh** [comment]
Yeah, and while you did remember to complain that it's not clear what the demo is supposed to be doing (though it does say so on the linked page -- "automatically resize to fit its content"), you didn't actually remember to mention what the problem you're running into is. Your jsfiddle shows a single editor, which appears to work, except that you put it into a fixed-height container, which does look rather wonky.
