### ISSUE TITLE
Haxe mode - ellipses not correctly highlighted when preceded directly by integer

### ISSUE THREAD

**Issue by increpare** [codemirror/CodeMirror#3542]
haxe for loops can have the follow structure
    
    for (i in 0...3) { }

but the current highlighter mistakes the 0. for a number and highlights in incorrectly:

<img width="189" alt="screen shot 2015-09-20 at 16 27 21" src="https://cloud.githubusercontent.com/assets/465632/9981457/77e025d6-5fb5-11e5-8d39-74c1b970f1d8.png">

(fix incoming...)

**Comment by marijnh** [comment]
Does patch 9f149ba also solve this for you? It seems like a simpler solution.

**Comment by increpare** [comment]
That works just as well for me :+1:
