### ISSUE TITLE
Codemirror in flex-child container

### ISSUE THREAD

**Issue by vdv73rus** [codemirror/CodeMirror#3547]
So, what if we put codemirror into child of flexbox layout.

It is work not correctly, because `.Codemirror-scroll` has `height: 100%;` parameter.
And it's really height will become equal first parent with absolutely height parent.

**Comment by marijnh** [comment]
Does flexbox actually specify that `height: 100%` will end up referring to something else than the height of the wrapping `position: relative` container, or is this just a browser bug that you're running into?

**Comment by marijnh** [comment]
This appears to be the same as #4142
