### ISSUE TITLE
hardwrap addon can infinite loop & OOM

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3548]
A repro case is 

```
    implemented using an Android [`TextureView`](http://developer.android.com/reference/android/view/TextureView.html).

```
(with the newline above and below, and +4 indent)

if you then call editor.wrapRange({line:1, ch:0}, {line:1, ch:null}, {column:80}) it goes into an infinite loop and steadily increases memory usage of that process.

**Comment by marijnh** [comment]
I assume you are doing something like what the demo is (was) doing, reacting to every changes with a new call to `wrapParagraphsInRange`. It is cheaper to suppress this effect for changes generated by the hardwrap addon (see d708748a9c3) but I've also updated the addon (edfe2106348c5c) to not emit any changes when there's nothing to change (it was creating an empty change, endlessly re-triggering the event handler).

**Comment by mtaran-google** [comment]
No, I wasn't calling it like that. The repro case is still that you just have the text above in the editor and call editor.wrapRange(...) and it still goes into an infinite loop and causes the tab to get killed.

**Comment by marijnh** [comment]
I can't reproduce that. Could you give me a simple HTML file that triggers the problem?

**Comment by mtaran-google** [comment]
Github seems to hate html attachments, even when they're reamed with .txt. Here you go though:

```html
<!doctype html>

<title>CodeMirror: Hard-wrapping Demo</title>
<meta charset="utf-8"/>
<link rel=stylesheet href="../doc/docs.css">

<link rel="stylesheet" href="../lib/codemirror.css">
<script src="../lib/codemirror.js"></script>
<script src="../mode/markdown/markdown.js"></script>
<script src="../addon/wrap/hardwrap.js"></script>
<style type="text/css">
  .CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}
</style>
<div id=nav>
  <a href="http://codemirror.net"><h1>CodeMirror</h1><img id=logo src="../doc/logo.png"></a>

  <ul>
    <li><a href="../index.html">Home</a>
    <li><a href="../doc/manual.html">Manual</a>
    <li><a href="https://github.com/codemirror/codemirror">Code</a>
  </ul>
  <ul>
    <li><a class=active href="#">Hard-wrapping</a>
  </ul>
</div>

<article>
<h2>Hard-wrapping Demo</h2>
<form><textarea id="code" name="code">

    implemented using an Android [`TextureView`](http://developer.android.com/reference/android/view/TextureView.html).

</textarea></form>

<p>Demonstration of
the <a href="../doc/manual.html#addon_hardwrap">hardwrap</a> addon.
The above editor has its change event hooked up to
the <code>wrapParagraphsInRange</code> method, so that the paragraphs
are reflown as you are typing.</p>

<script>
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
  mode: "markdown",
  lineNumbers: true
});
</script>

</article>

```

After opening this, run `editor.wrapRange({line:1, ch:0}, {line:1, ch:null}, {column:80})` and it should hang.

**Comment by marijnh** [comment]
Thanks, now I can reproduce. Attached patch fixes this.
