### ISSUE TITLE
VIM mode - large green cursor does not display in contenteditable mode

### ISSUE THREAD

**Issue by paulmarrington** [codemirror/CodeMirror#3552]
```
ContentEditableInput.prepareSelection(this.cm, false)
```

while

```
TextareaInput.prepareSelection(cm);
```

prepareSelection has a line

```
  if (primary === false && i == doc.sel.primIndex) continue;
```

which causes to loop to be skipped for ContentEditableInput. In vim mode this means that html looks like

```
<div class="CodeMirror-cursors"></div>
```

instead of

```
<div class="CodeMirror-cursors" style="visibility: hidden;"><div class="CodeMirror-cursor" style="left: 129px; top: 95px; height: 19px;">&nbsp;</div></div>
```

**Comment by marijnh** [comment]
That's true. contentEditable doesn't support cursor styling, so we can't hide the regular cursor, but maybe it would be a good idea to overlay the block cursor anyway. I'll look into it.

**Comment by marijnh** [comment]
We could add logic for drawing the cursor as a one-character selection overlay, but that still wouldn't hide the regular native cursor, and having two cursor blink (out of sync) seems like it would be worse than not having the cursor be wide.

**Comment by mtaran-google** [comment]
So it's not possible to hide the underlying system cursor?

**Comment by marijnh** [comment]
If you're only targeting Webkit and Firefox, it seems you can set `caret-color: transparent` via CSS to hide the cursor. Does that suffice for you, or do you need IE/Edge compatibility?

**Comment by mtaran-google** [comment]
That would work for us! Would you mind wiring it in to the vim mode code?

**Comment by marijnh** [comment]
I'm not going to be able to get to that this week, but will take a look early next week (I suspect it won't be complicated).

**Comment by mtaran-google** [comment]
Sounds good, thank you :)

**Comment by marijnh** [comment]
Please take a look at patch ad6635a5
