### ISSUE TITLE
contextmenu event not firing after 5.x upgrade

### ISSUE THREAD

**Issue by kmctown** [codemirror/CodeMirror#3555]
I have observed that the `contextmenu` event no longer fires in CodeMirror 5.x. Here are two examples, where the 4.x version is firing the event and the 5.x version is not:

CodeMirror 4.13.0: https://jsfiddle.net/1obhvc46/

CodeMirror 5.7.0: https://jsfiddle.net/j5f0tk0p/

I performed a (long) `git bisect` and it appears that this change landed in the commit immediately following the `4.13.0` release 0dc2189. Tried looking into it but did not get very far.

**Comment by marijnh** [comment]
You are right, it appears to have been removed in the inputStyle overhaul, because I'm not interacting with the context menu in the contentEditable input style. But I could restore it and add a handler just for this kind of hooks in the contentEditable backend. What were you using it for?

**Comment by kmctown** [comment]
I'm using typo.js for spellchecking was using this to display a context menu of spellcheck suggestions when applicable.

**Comment by marijnh** [comment]
Attached patch should bring back support for this event.

**Comment by kmctown** [comment]
Confirmed that the patch restores the event. Thank you!
