### ISSUE TITLE
Bookmarks adjacent to collapsed ranges (marked text) are ignored

### ISSUE THREAD

**Issue by twpol** [codemirror/CodeMirror#3556]
If you use `markText` and `replacedWith` to create a collapsed mark and also use `setBookmark` and `widget` with the same location, the bookmark is ignored when rendering. E.g.

```js
doc.markText({ line: 0, ch: 0 }, { line: 0, ch: 5 }, { replacedWith: ... });
doc.setBookmark({ line: 0, ch: 0 }, { widget: ... });
```

I'd not expect bookmarks *inside* a collapsed range, but when they're *adjacent* it seems like it should work, and I'd like this to work.

I've hacked it up locally by swapping the two `ifs` at https://github.com/codemirror/CodeMirror/blob/3c9df966c36f7b8314c792fd1e1ecb60cdab1320/lib/codemirror.js#L7071-7078 and removing the `!collapsed` requirement from the bookmarks one. I wouldn't be surprised if this causes issues when bookmarks are *inside* the collapsed areas, but it's enough for my use cases.

P.S. I'm using CodeMirror 5.3.0 and have this problem in Internet Explorer 11 but believe it's cross-browser. I'll try and produce a live demo.

**Comment by twpol** [comment]
Example: http://jsbin.com/zacajegijo/edit?js,output (gist: https://gist.github.com/anonymous/332dcfe46dc574029c80)

If you change the `markText` to start from `ch: 1` the alert will show both span-a and span-b, but with them both starting from `ch: 0` you only get span-a.

**Comment by schanzer** [comment]
I'm seeing this same issue in OSX on Chrome 47.

**Comment by marijnh** [comment]
See patch 8f2149c2d586184
