### ISSUE TITLE
Need a wheel-event like handler for touch scrolling

### ISSUE THREAD

**Issue by marijnh** [codemirror/CodeMirror#3564]
Swiping the content up or down shows the flickering of content being drawn after it enters the viewport, just like the issue we used to have with wheel scrolling. A similar solution (predict scrolling, make sure content is drawn) will probably work here, but I am unsure whether there is an easy way to see such scrolling coming, and whether analyzing touch events ourselves is a sane way to go here.

Any touch event expert want to chime in?

**Comment by justbittin** [comment]
This is a very tricky situation on mobile devices since the onscroll event is normally updated until the scroll is finished, or if a momentum scroll is used, til it stops.

http://cubiq.org/iscroll-5

That would be an interesting place to start, maybe the underlying engine will help.  The idea is to manage the scrolling without default behavior.

I think you could incorporate this into codemirror.

**Comment by justbittin** [comment]
@marijnh, any progress with a solution?

**Comment by marijnh** [comment]
I've looked into this, but didn't find a good solution. The touch events' correspondence with the scrolling is platform-specific and hard to predict. Mobile browsers fire scroll events only in ~350ms intervals, since they do their scrolling on hardware, and don't actually show the up-to-date DOM during scrolling (but rather, a texture that they rendered at the start of such a ~350ms slice).

I tried to predict scrolling from the scroll events, but typically it ramps up very fast, you'll get an event for a handful of pixels scrolled as the touch gesture is done, and then it accelerates to >1000px already for the next event, and even more (>2000) for the one after that. Rendering thousands of pixels ahead on ever scroll event isn't realistic -- it'd cause awful lag.

You can try setting your `viewportMargin` to something bigger than the default (setting it to 500 mostly, but not entirely, solved the problem for me), but that'll cause a bigger DOM to be rendered and startup, as well as redraws, to be slower.

**Comment by marijnh** [comment]
Since browsers have decided to prioritize scroll performance over the ability of scripts to interact with scrolling, my impression is that this is a losing battle, and the [CodeMirror 6](https://codemirror.net/6/) design just gives up on this—it'll try to quickly render the content of the viewport when it's notified of the scrolling, but does away with all the [awful hacks](https://marijnhaverbeke.nl/blog/a-pathological-scrolling-model.html) that try to predict scrolling in advance. So you'll see a flash of empty content during quick scrolling, but the library can be simpler and avoids eating battery by rendering stuff that may not bee needed.
