### ISSUE TITLE
Gutter 1px wider than what I set it to

### ISSUE THREAD

**Issue by tolmasky** [codemirror/CodeMirror#3568]
Any idea what could cause this?

![screen shot 2015-10-04 at 12 07 44 am](https://cloud.githubusercontent.com/assets/23753/10266798/0ecbddde-6a2c-11e5-9663-857c9a4c9bdd.png)

**Comment by marijnh** [comment]
The line number gutter's width is adapted to make sure line numbers fit. There's an extra pixel added to work around issues where rounding causes `offsetWidth` to be less than the actual element width.
