### ISSUE TITLE
better css hints

### ISSUE THREAD

**Issue by gujiman** [codemirror/CodeMirror#3570]
hi, currently when you view hints for css properties you end up getting all the css values for a css property including values that are not used by that property, for example:

1) goto https://codemirror.net/mode/css/index.html
2) enter 'cursor:' as a css property, and press ctrl-space to view the values (instead of only showing cursor values it ends up showing all css values).

'cursor:{above|absolute|activeborder......}

I have managed to come up with a solution for this at:
https://github.com/gujiman/CodeMirror/tree/better-css-hints

If you run my code then only matching css values will be displayed for css properties.

for example 'cursor:{auto|pointer|cross......}

However my only problem is that when running the tests on:
https://github.com/gujiman/CodeMirror/blob/better-css-hints/mode/css/index.html
It ends up failing 12 test, however the outcome of the test are same as what is expected in the test? So i was thinking are the tests wrong?

**Comment by marijnh** [comment]
Thanks, but I am not really willing to incur this extra complexity for this feature. Also, your implementation, which uses simple string scanning to figure out the property, will break when faced with comments or newlines.

I suggest you package this (including the list of properties) up as a custom replacement or extension to the css hinter, and distribute it yourself.
