### ISSUE TITLE
application/x-httpd-php error on chrome.

### ISSUE THREAD

**Issue by bradx954** [codemirror/CodeMirror#3572]
typing:
<?php
?
causes a error montage.
![phpbug](https://cloud.githubusercontent.com/assets/8339482/10299129/7f81dedc-6bb4-11e5-9009-f4d31d903d27.png)

**Comment by marijnh** [comment]
Could it be that you forgot to include one or more of the modes that the PHP mode depends on? (XML, JavaScript, CSS, HTMLMixed, and clike)

**Comment by bradx954** [comment]
You are absolutely right I forgot to include clike. Thanks for the quick response btw.
