### ISSUE TITLE
When CodeMirror 5.8.0 will be released?

### ISSUE THREAD

**Issue by angelozerr** [codemirror/CodeMirror#3573]
@marijnh I would like just to know when you will plan to release 5.8.0? In my case I need https://github.com/codemirror/CodeMirror/commit/b0d525acc5db0eb6cd2fa67c564057d6b89bca37 for several tern plugins like tern-tabris.

**Comment by marijnh** [comment]
In about two weeks (I release around the 20th of each month)

**Comment by angelozerr** [comment]
Thanks @marijnh for your info.
