### ISSUE TITLE
How to create a simple mode

### ISSUE THREAD

**Issue by MarkBond91** [codemirror/CodeMirror#3578]
So I just got into codemirror recently because I needed a text editor for my website, but that means I don't know much about the program. I got the editor working but I need to create some syntax for the editor, which I believe means I have to create a mode for the editor, and I am having trouble doing this. I have read over the manual a few times but something just isn't clicking for me, probably because I've never worked with something like this. Anyways right now I just need to get the hang of it, by creating simple add, subtract, and multiply functions. if someone could get me rolling with this I'd be very appreciative.

**Comment by marijnh** [comment]
You can start with the example (see the page source) [here](http://codemirror.net/demo/simplemode.html). But your question is too general for us to say anything useful to it, and the bug tracker is not the correct place for support questions. If you run into _specific_ problems, ask questions on the [discussion forum](http://discuss.codemirror.net).
