### ISSUE TITLE
How to get CodeMirror to respect the height of its container?

### ISSUE THREAD

**Issue by greggman** [codemirror/CodeMirror#3591]
Sorry if this is a noob question

I'm just trying to make a simple editor. The html/body is set to 100% height, There's a toolbar div on top set to 20% height and an editor div on bottom set to 80% height. Inside the editor div I insert a CodeMirror (or rather I pass the editor div into CodeMirror and CodeMirror inserts itself)

But, if the window is tall CodeMirror does not stretch to fit its container.

![gif](http://i.imgur.com/1WSVLZ2.gif)

    Green = top area
    Blue = container for editor (editor should fill this minus 1em padding, bottom is too large)

If the window is too short  CodeMirror grows larger than its container or something strange happens when scrolling to the bottom. You can see

![gif](http://i.imgur.com/FG5TOYx.gif)

    Green = top area
    Blue = container for editor
    Red = body (should never see red given that top is 20% and editor is 80%)

The docs say set `.CodeMirror` to the size I want it but no matter what I set it to it seems to be ignored

Here's a CodePen: http://codepen.io/greggman/pen/LpjwKp

How I can I get CodeMirror to just match the size of its container?

**Comment by marijnh** [comment]
Add `position: relative` to the wrapper div, and make sure your stylesheet gets applied _after_ the standard CodeMirror css (which sets a default height of 200px), which isn't happening in the codepen.

**Comment by satyapendem** [comment]
Hiii, 
I have a codemirror div I used `$(code_div).each(function() {

      var $this = $(this),
      $code = $this.html(),
      $unescaped = $('<div/>').html($code).text();
      $this.empty();
      CodeMirror(this, {
        value: $unescaped,
        lineNumbers: true,
        theme: "neo",
        readOnly: "nocursor"
      });
    });` for syntax highlight. But I want a the text in that div in a arranged format I'm getting in a single. So how i can arrange that
