### ISSUE TITLE
Request to include a reference to codemirror-grammar add-on

### ISSUE THREAD

**Issue by foo123** [codemirror/CodeMirror#3594]
Hello, i suggest an included reference in Codemirror site and/or repository to the [codemirror-grammar add-on](https://github.com/foo123/codemirror-grammar) (author).

The add-on was created specificaly to handle highlighting arbitrary code and/or highlight alternatively from included modes. Since most of that work was found to be the same, a general grammar-based add-on was created with many important features, many of which not found in existing hard-coded highlight modes.

On top of that, the add-on solves the problem of transfering highlight-modes to text or another editor and vice-versa and also extending existing modes with new features in an optimum way.

i think the add-on is very usefull for all users of codemirror and it would be nice to have a reference to it.

The code is open-source and free and anyone can use and contribute freely.

Thank you, keep up the good work

**Comment by marijnh** [comment]
Nice project. Did you see [simple modes](http://codemirror.net/demo/simplemode.html), which has a somewhat similar goal (though it doesn't do inheritance). We have [this wiki page](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons) for external links, which you can edit directly.

**Comment by foo123** [comment]
added a reference in the [wiki page](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons) under a new category **Highlighting / Extra Modes** which seemed more appropriate.

ps. the add-on is currently being revised to new versions with new features, open to suggestions, if there are any. The idea is to make it as self-contained as possible, both in terms of language highlight-specification detail and in terms of editor-specific out-of-the-box features like autocomplete, annotate, fold indentation, and so on..

Cheers

**Comment by foo123** [comment]
The state-machine in `simple modes` add-on is similar to what ace editor uses (which supports a similar feature) as well (based on that common specification, and codemirror's success) and is how cm-grammar add-on was initialy created (doing only lexical analysis, without having to create the same old mode over and over) but with a separate style model, so editor-specific styles are not hardcoded, but are just a modular parameter. 

Then when having to highlight xml (and similar popular languages) became not-trivial with a simple lexical analysis, then the syntax model of the grammar add-on was created to handle xml (or similar) easily. Syntax was created as a generalisation to regular expressions both for ease of notation and intuitiveness (which turns out to be a variation of what is known as PEG form).

Then more features were added and an ability to write rules as natively (and easiest) as possible (without these configuration objects) so parsing syntax directly in bnf/peg form was added, plus some new token types (action tokens) to enable complex context-specific functionality (like unique in-context identifiers and so on) which are important to many (programming) languages. 

The need for such an add-on was created when having to highlight arbitrary code for which no mode existed or highlighting alternatively without delving into each mode's source code (and without duplicating the same modes over and over where only "tokens" changed).

**Comment by foo123** [comment]
@marijnh 

For a new model for a common and modular specification for (intercative) highlighting, you might want to see [this part](https://github.com/foo123/editor-grammar/blob/master/grammar-reference.md#modularity-and-future-directions)
