### ISSUE TITLE
Custom mapping of key sequence

### ISSUE THREAD

**Issue by gboehl** [codemirror/CodeMirror#3595]
Hi,

I tried to map a sequence of keys to a function for https://github.com/lambdalisue/jupyter-vim-binding, but without success. 

This is what my last paragraph looks like:
```javascript
  var exports = {
    'load_ipython_extension': function() {
      // apply options and events on existing CodeMirror instances
      namespace.notebook.get_cells().map(function(cell) {
        var cm = cell.code_mirror;
        var map = {'J K': leaveInsertOrNormal};
        CodeMirror.normalizeKeyMap(map);
        if (cm) {
          cm.setOption('keyMap', 'vim');
          cm.setOption('extraKeys', {
            map,
            'Esc': leaveInsertOrNormal,
            'Ctrl-I': leaveInsertOrNormal,
            'Tab': insertSoftTab,
          });
          cm.on('blur', leaveInsert);
        }
      });
    }
  };
  return exports;
```

'Esc' and 'Ctrl-I' are working, but the 'j,k' sequence isn't. Do you have any idea why?

Thanks in advance!

**Comment by marijnh** [comment]
Putting a keymap under the `map` property of another keymap won't do anything. (Your code won't even compile as ES5, but I guess you're using Babel or something similar.)

Move all of your bindings into `map`, and then use it directly as the `extraKeys` option.
