### ISSUE TITLE
MergeJS cannot highlight differences

### ISSUE THREAD

**Issue by thienan93** [codemirror/CodeMirror#3599]
I have the problem with highlight differences as picture below:
![image](https://cloud.githubusercontent.com/assets/10244759/10503001/0b586d2c-731c-11e5-8465-75d382ce76b5.png)

After click to expend we will see highlight as picture below:
![image](https://cloud.githubusercontent.com/assets/10244759/10503057/8c65db52-731c-11e5-9897-fd3fa42fd9e9.png)

And here is snippet code:
![image](https://cloud.githubusercontent.com/assets/10244759/10503100/f0dbae72-731c-11e5-8ed8-5dd412929762.png)

Thank you!

**Comment by marijnh** [comment]
I can not reproduce this problem in the merge view demo. Could you set up an HTML page that makes it easy to get the problem to occur (and include instructions on what to do to make it happen)?

**Comment by thienan93** [comment]
When I try to reproduce this problem I notice that it occur when we have more text with litter the differences. One html page was prepare but I cannot attach in here. How to I provide it for you?

**Comment by marijnh** [comment]
You could put it on gist.github.com and link to it.

**Comment by thienan93** [comment]
It is available at: https://gist.github.com/thienan93/b6ea740ad7a89d014f3d. Hope that it will help you find the root cause for the problem. Thanks

**Comment by marijnh** [comment]
Thanks. That helped. Attached patch seems to fix this.
