### ISSUE TITLE
Allow markText with "bookmark" type.

### ISSUE THREAD

**Issue by yapcheahshen** [codemirror/CodeMirror#3600]
setBookmark will not copy all keys from options,
markText will copyObj(options) , all keys in options will be stored in the marker.
but the type is fixed to "range".

Please change the markText API (eedb58faa301551d530b34e5c765a90607232a31 codemirror.js line 7560) from
-    markText: function(from, to, options) {
-      return markText(this, clipPos(this, from), clipPos(this, to), options, "range");

to:

+    markText: function(from, to, options, type) {
+      return markText(this, clipPos(this, from), clipPos(this, to), options, type||"range");

In order to create bookmark with custom options properties.

**Comment by marijnh** [comment]
Attached patch does this, but by reading the `type` option from the options object rather than adding an argument.
