### ISSUE TITLE
Support a Mustache mode that highlights the templated language

### ISSUE THREAD

**Issue by srawlins** [codemirror/CodeMirror#3602]
**Preface:** I'm opening this issue mostly for the technical discussion. If this feature seems possible and would be accepted into the project, I'd be happy to do the work.

I think that most often, Mustache template files have two extensions: the "wrapped" language extension, followed by ".mustache". So an HTML template file has the extension ".html.mustache" and a Markdown template might have the extension ".md.mustache".

It would be awesome if CodeMirror supported a mixed mode Mustache mode that highlighted the "wrapped" language as normal, and caught Mustache tags, highlighting them as Mustache tags.

One way that mustache makes this crazy simple is it's [crazy simple interface](https://mustache.github.io/mustache.5.html): Mustache tags are exactly the two following syntaxes: `{{tag}}` and `{{{tag}}}`. The mustache highlighter could distinguish between variables `{{name}}` and sections `{{#list}}`, etc., but honestly, if they were just plain text, that'd be fine.

The ["Set Delimiter"](https://mustache.github.io/mustache.5.html#Set-Delimiter) functionality would probably be hard to support, but I don't think it would be needed in v1. It's not a commonly used feature.

The only tricky thing I can think of is the Mustache mode knowing the file extensions, and dynamically using the proper mode for the "wrapped" language.

**Comment by marijnh** [comment]
This is already how most CodeMirror template language modes work. For example the [handlebars mode](http://codemirror.net/mode/handlebars/) -- scroll down in the example to see HTML highlighting of the content.

As for a specific Mustache mode (if the syntactic differences with Handlebars annoy you), I don't take feature requests for modes -- you can write it yourself (probably by making the Handlebars mode configurable) or pay me to do so.
