### ISSUE TITLE
Wikibase RDF hint

### ISSUE THREAD

**Issue by Jonas-WMDE** [codemirror/CodeMirror#3613]
Hey,

we have implemented a Wikibase RDF hint addon for CodeMirror at query.wikidata.org. Would you be interested in having this in upstream? https://gerrit.wikimedia.org/r/#/c/246697/12/gui/addon/hint/wikibase-rdf-hint.js

Cheers,
Jonas

**Comment by marijnh** [comment]
Nice. But nope, that's too obscure for me to want to maintain it. Put it on github and link it from [here](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons), maybe.
