### ISSUE TITLE
Fat arrows

### ISSUE THREAD

**Issue by AdriVanHoudt** [codemirror/CodeMirror#3614]
Would it be possible to treat fat arrows (es6) differently than `equals or bigger than`? so for example highlighters in Brackets can color them differently?

**Comment by marijnh** [comment]
We already are parsing fat arrow expressions as functions (see, for example, the way the variables declared as arguments are highlighted differently). What else were you hoping for?

**Comment by AdriVanHoudt** [comment]
hmm do you by any change now if Brackets already takes this into account? because if this is already the case I will open an issue on brackets to see if they can incorporate a fix

**Comment by marijnh** [comment]
Try http://codemirror.net/mode/javascript/ and see if it behaves better than Brackets.

**Comment by AdriVanHoudt** [comment]
by brackets I mean http://brackets.io/

**Comment by marijnh** [comment]
I know that, yes.

**Comment by AdriVanHoudt** [comment]
ok then I am not sure what you mean with the javascript mode, let me open an issue on the brackets repo for this

**Comment by abose** [comment]
I do not see that `=>` is colored differently in http://codemirror.net/mode/javascript/

**Comment by marijnh** [comment]
It's styled as an operator, intentionally, because it is.

**Comment by abose** [comment]
Now I see why that coloring makes sense. 
Thanks.

**Comment by petetnt** [comment]
In that Brackets issue I said the same, that `=>` was correctly highlighted as ´.cm-operator` but now that I think about it, it's never referenced to as operator but as `arrow function` (or similar) so it might make sense to highlight it as `keyword` instead (just like `function` is).

**Comment by abose** [comment]
http://www.ecma-international.org/ecma-262/6.0/ does not define `=>` as an operator. It is identified as `Arrow Function Definitions` .

**Comment by AdriVanHoudt** [comment]
So codemirror is not marking it correct?

**Comment by marijnh** [comment]
There is no 'correct' mapping from the grammar to highlighting. CodeMirror is highlighting this token as an operator and I see no reason to change it (keyword highlighting is used for actual keywords, and wouldn't make more sense than operator).

**Comment by AdriVanHoudt** [comment]
I am not familiar with codemirror itself, just know it is used by brackets, but as @abose pointed out shouldn't it be tagged as arrow function instead of operator? (or am I understanding this wrong?)
