### ISSUE TITLE
Compression Helper is broken

### ISSUE THREAD

**Issue by raveren** [codemirror/CodeMirror#3615]
https://codemirror.net/doc/compress.html

The resulting `.js` file is actualy HTML from an uglify.js landing page.

**Comment by vincentwoo** [comment]
I can't reproduce, do you have more specific steps to follow? What browser are you using?

**Comment by marijnh** [comment]
Works for me too. Feel free to add more information if you find out under what circumstances it doesn't.

**Comment by raveren** [comment]
woah it works on chrome, firefox is broken though

**Comment by raveren** [comment]
Also, the steps are:
1. Click compress
2. Get bad output :)

**Comment by marijnh** [comment]
I tested Firefox 40 and 41 on Linux, but neither show the problem (the downloaded file is a compressed CodeMirror script). Do you have any strange proxy or caching setup?

**Comment by raveren** [comment]
No, strangely I do not. Ah if it works for everyone else, I'll just drop it
:)
