### ISSUE TITLE
float should not be a C keyword

### ISSUE THREAD

**Issue by oksayt** [codemirror/CodeMirror#3616]
Currently `float` is a member of both a `cKeywords` and `cTypes`:
https://github.com/codemirror/CodeMirror/blob/master/mode/clike/clike.js#L255

Keywords seem to trump types, which causes `float` to appear as a different color than `int`, `long`, etc.

It looks like removing `float` from `cKeywords` would fix this.

**Comment by marijnh** [comment]
Thanks for noticing that. It was a holdover from before the clike mode did type highlighting. Fixed by attached patch.

**Comment by oksayt** [comment]
Thanks for the quick fix!
