### ISSUE TITLE
width in chars

### ISSUE THREAD

**Issue by ngn** [codemirror/CodeMirror#3618]
What would be a reliable way to figure out how many characters can fit side by side in the viewport (assuming a mono font and no Unicode nastiness with zero-width or composition)?
The best I could come up with is:
`cm.coordsChar({left:cm.display.lineDiv.clientWidth, top:4}, 'local').ch`
I had to set `top:` to a small positive number as 0 is considered to be outside and a large number such as `.clientHeight` would risk running into a wrapped line.

**Comment by marijnh** [comment]
If you have an empty editor, or you have line wrapping enabled, you can get `cm.display.lineDiv.querySelector("pre").clientWidth` and divide that by `cm.defaultCharWidth()`. If there might a horizontal scrollbar, this won't work, as the `lineDiv` will be wider than the display area, and there's no element that actually has the right width (accounting for gutter width and horizontal padding).

**Comment by ngn** [comment]
In my particular case there's never a gutter, so this turned out to be easier:
`Math.floor((e.clientWidth-cm.display.scrollbarFiller.clientWidth)/cm.defaultCharWidth())`
where `e` is CodeMirror's root element.  Padding contributes a negligible number of pixels which I don't mind compensating for with a constant.

I noticed that `defaultCharWidth()` initially reports a wrong width, always an integer.  After a call to `refresh()` it starts returning the correct one.

**Comment by marijnh** [comment]
Are you, by any chance, using a webfont for the editor's content?

**Comment by ngn** [comment]
Yes, though it's not hosted on a web server.  It's bundled with a [NW.js](https://github.com/nwjs/nw.js) app.

**Comment by marijnh** [comment]
That generally doesn't matter, font loading will still be async, meaning that if you didn't somehow wait for the fonts to load before initializing CodeMirror, it will initialize with a fallback font and thus not get the right measurements.

**Comment by ngn** [comment]
I see.  Thank you.  I have an easy workaround -- `cm.refresh()`.
