### ISSUE TITLE
Multiple hint addons not working

### ISSUE THREAD

**Issue by Jonas-WMDE** [codemirror/CodeMirror#3620]
When registering multiple hints for example for SPARQL: 
```javascript
CodeMirror.registerHelper( 'hint', 'sparql', function ( editor, callback, options ) {
```
Only the last registered addon will work.

**Comment by marijnh** [comment]
What you are doing there will, by design, replace the already existing hint for `sparql`. Only a single hint can be directly associated with a given string. If you want to combine multiple hint sources, you'll have to write a wrapper and register that as helper.
