### ISSUE TITLE
Findbar annotations skew on long files

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3621]
Repro:

1. Open http://codemirror.net/demo/search.html
2. Run editor.setValue('a\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\nb\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\nb\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\n')
3. Ctrl+f for 'b' (the viewport moves to the first b, and both b locations are highlighted on the scrollbar)
4. Shift+click the second find-match marker in the scrollbar

Expected:
The viewport should shift so the b is visible.

Actual:
The viewport shifts to significantly below the b.

Some skew like this is inevitable since the handle in the scrollbar has a minimum height, and so on long files the actual fraction of the scrollbar corresponding to the viewport will be smaller than the handle. But the current setup makes it so that the overlap between the viewport and handle happens at the *bottom* of the handle, while shift-clicking sets the location of the *middle* of the handle. I think the best resolution would be to have the viewport be in the middle of the handle, when possible. The other resolution would be to have shift+clicking set the bottom of the scrollbar, though I think that'd be more confusing.

What do you think?

**Comment by marijnh** [comment]
Which platform is this on? On Firefox and Chrome linux, the minimum height of the native scrollbar handle is rather big, so the handle stops having much to do with the viewport height at a relatively low line count. (In your example, I would say it's about the size of five viewports, in relation to the total scrollbar height). Given the skew from the scrollbar button sizes, the markings appear pretty much where I'd expect them when I scroll the matches into view.

Have you tried enabling the non-native scrollbar (scroll/simplescrollbars addon), and seeing if that helps? (Those don't have scrollbar buttons, and should thus show less skew).
