### ISSUE TITLE
Does CodeMirror have an autosave feature?

### ISSUE THREAD

**Issue by GonzaloCh** [codemirror/CodeMirror#3628]
Hey guys, I was wondering if Code Mirror has an autosave feature built into it.

**Comment by amshali** [comment]
Define save.

**Comment by GonzaloCh** [comment]
My goal is that after every few seconds codemirror will save the file. Sort of like how Google Docs does it for say.

**Comment by marijnh** [comment]
Saving is outside of the scope of CodeMirror (it doesn't have a server component or save to localstorage), but you can use your own timeouts along with [`markClean` and `isClean`](http://codemirror.net/doc/manual.html#markClean) to implement this.

**Comment by Hypnosphi** [comment]
> Define save

`cm.save()`

> Define autosave

`cm.on('change', () => cm.save())`
