### ISSUE TITLE
Feature Request: Indent by +n in C-like modes

### ISSUE THREAD

**Issue by tedks** [codemirror/CodeMirror#3629]
I'd like to write code like this:

```
Foo foo = new Foo(
    new Bar(
         "bar param one",
         "bar param two"),
    new Baz());
```

where the indentation advances +4 (or +n) per level, rather than indenting to the next open paren. This makes it easier to work with verbose java code.

**Comment by marijnh** [comment]
The clike mode does not, in this situation, indent to the open paren. It indents one indentunit, which is [configurable](http://codemirror.net/doc/manual.html#option_indentUnit).

(It does indent to the paren if there's other elements on the same line as the paren, as in

```
do_foo(bar,
       baz)
```

but that doesn't seem to be what you are talking about)
