### ISSUE TITLE
scroll-past-end addon messes up the scrollbar highlights

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3630]
You can see the problem by enabling `scrollPastEnd` in the find/replace scrollbar highlighting demo. The issue is that the highlights act as if the bottommost position of the scroll rectangle corresponds to the bottom of the file, but with the `scrollPastEnd` option enabled the bottommost position of the rectangle corresponds to almost one screen *below* the last line. Thus the scrollbar annotations all get misaligned, especially near the bottom of the document.

**Comment by marijnh** [comment]
Attached patch seems to address this. Let me know if you run into more issues.
