### ISSUE TITLE
DOT language support

### ISSUE THREAD

**Issue by AlgyTaylor** [codemirror/CodeMirror#3638]
Hi CodeMirror folk!

What's the chances of getting some support for DOT in CodeMirror?
https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29

http://www.graphviz.org/Documentation.php

**Comment by marijnh** [comment]
Not good, unless you do it yourself. See [the mode wish list](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list)
