### ISSUE TITLE
<p><br></p> remove by default

### ISSUE THREAD

**Issue by kickthemooon** [codemirror/CodeMirror#3639]
Im using summernote and codemirror.

When I open my view the codemirror has "<p><br></p>" by default written inside of it

![codemirrordefaultpbr](https://cloud.githubusercontent.com/assets/7913974/11116521/743be62a-8933-11e5-9b1d-c680a4c217fa.jpg)

Can i disable this?

**Comment by marijnh** [comment]
This isn't something CodeMirror does. You'll have to look at other factors (probably this is the default content of the Summernote editor)

**Comment by Cipher22** [comment]
summernote have default value <p><br></p> 

You can use striphtml to remove html tags  while storing in database 

using System.Text.RegularExpressions; // for striphtml regex 

public partial class XXX : System.Web.UI.Page
{

  
    static string StripHTML(string inputString)
    {
        inputString = Regex.Replace(inputString, @"<(.|\n)*?>", string.Empty);
        inputString = inputString.Replace("&nbsp;", "");
        return inputString;

    }

and then  use this 

       string summaryhtml = StripHTML(txtsummary.Text);
       summary = summaryhtml;


I dnt know your purpose, Many of them searching for summernote validation  so i attach this also it will help anyone

you can validate summernote by using custom validator  like



                <asp:CustomValidator ID="cvsummary" runat="server" ValidationGroup="submit" ValidateEmptyText="true" ControlToValidate="txtsummary" ForeColor="Red" Text="*" Display="Dynamic" ErrorMessage="Summary Required" OnServerValidate="CustomValidator1_ServerValidate"></asp:CustomValidator>

                                          

you need to check validate function in the required button to fire custom validation

    protected void BtnSaveNew_Click(object sender, EventArgs e)
    {
       // Page.Validate();         // i used when custom validator not fired for the first time
    
    if (IsValid) { 

    //code here       
     string summaryhtml = StripHTML(txtsummary.Text);
       summary = summaryhtml;
     //
         }
        }


    protected void CustomValidator1_ServerValidate(object source, ServerValidateEventArgs e)
    {

        if (e.Value.Equals("<p><br></p>"))
        {
            e.IsValid = false;

            ScriptManager.RegisterStartupScript(this, this.GetType(), "Popup", "alert('Please Enter all Details');", true);

        }
        else
        {
            e.IsValid = true;
        }

    }
}
