### ISSUE TITLE
Request to include DOM element within CodeMirror.TextMarker object

### ISSUE THREAD

**Issue by ohmance** [codemirror/CodeMirror#3644]
Thanks for this awesome plugin!

When I call the `markText()` method with the `replacedWith` parameter I am able to pass in a pre-existing DOM element.  This is great as it makes it possible for me to add tooltips, listen for events, etc on the specific dom element as well as do other cleanup operations.

The problem comes in when I don't want the marker that is created to be `atomic`...ie I want to delete parts of it one character at a time rather than have it erase the entire content of the marker.

Would really be nice to have a "span" property in the TextMarker object (returned from the `markText()` method) both with and without the replacedWith parameter so I can still do DOM manipulation on the span easily.

**Comment by marijnh** [comment]
If you just want to listen to events, don't use `replacedWith`. Rather, register event handlers on the whole editor (`.getWrapperElement()`) and look at the `target` or the coordinates of the events to see if they match your ranges.
