### ISSUE TITLE
Simple Mode Addon regular expression for coloring names not working as expected.

### ISSUE THREAD

**Issue by lilezek** [codemirror/CodeMirror#3646]
I'm using this:
https://codemirror.net/demo/simplemode.html

Barely edited with this code:

http://lilezek.github.io/zl/editor.js

At lines 17 and 18 you can see:

```
regex: /(subrutina)(.+)\s([a-zA-Z]+)/i,
token: ["keyword", null, "variable-2"]
```

Which, according to regex101, this input:

```
Subrutina Externa Inicio
```

Matches 3 groups:
```
1.	[0-9]	`Subrutina`
2.	[9-17]	` Externa`
3.	[18-24]	`Inicio`
```

But the editor renders this:

![captura de pantalla de 2015-11-16 12 02 35](https://cloud.githubusercontent.com/assets/2767229/11181443/5e3c9004-8c62-11e5-8aec-9fd285eb6c69.png)

The last letter of the line is never colored as `variable-2.`

You can test the issue here:

http://lilezek.github.io/zl/

**Comment by marijnh** [comment]
If you use this token-splitting approach, your regexp groups have to cover the _whole_ token. You have `\s` that's not in a group, which is causing this. Move the closing paren before the `\s` after it and you should be fine.
