### ISSUE TITLE
ES6 String Template syntax issues with spread and computed object keys

### ISSUE THREAD

**Issue by kalley** [codemirror/CodeMirror#3650]
The issues from #3536 are definitely fixed, but I've uncovered an additional case:

```js
const test = 'test';
const parent = { me: true };

const obj = {
  ...parent,
  [`${test}_option`]: 'some string'
}
```

When you comment out the spread, the highlighting is correct.

Tested at http://codemirror.net/mode/javascript/

**Comment by marijnh** [comment]
Spread in object literals isn't something that's part of ES6, which is why the JavaScript mode wasn't aware of it. Attached patch fixes this.
