### ISSUE TITLE
initialize .extend

### ISSUE THREAD

**Issue by jots** [codemirror/CodeMirror#3652]
I'm using codemirror with a library that overwrites Object.extend.  This causes codemirror to think that it's in "extending" mode.  I fix it by after creating the editor:
`editor.setExtending(false); // conflicts with lib`

Can codemirror initialize that property itself?

I realize it's not good practice to add properties to Object, but it does happen sometimes.

**Comment by marijnh** [comment]
Yes, it should have been doing that, and attached patch fixes this.

**Comment by jots** [comment]
Thank you Marijn!
