### ISSUE TITLE
Editor does not focus from webconsole

### ISSUE THREAD

**Issue by peterkroon** [codemirror/CodeMirror#3656]
Initial issue mentioned [here CM discuss forum](https://discuss.codemirror.net/t/closed-question-regarding-editor-focus/544).

Tested on Windows 10 64 bit.

Steps to reproduce:
- Open latest stable Chrome browser
- Go to: https://codemirror.net/
- Open webconsole
- Execute `editor.on("focus", function(){console.log("hi, focus..");});`
- Execute `editor.focus();`

The listener is not fired.
When the cursor is activated via mouse by clicking in the edit the listener is fired.

**Comment by amshali** [comment]
I don't think there is any issue with CM here. 

The issue is that when you run `editor.focus();`, the focus is actually on web console and not on the page.
Try this for a change:
`
setTimeout(function() {editor.focus();}, 5000);

Immediately, mouse click somewhere inside the page. You should see your log statement appearing after 5 seconds. 
`

**Comment by peterkroon** [comment]
> The issue is that when you run editor.focus();, the focus is actually on web console and not on the page.

The `textarea` does get focus.
Try the following steps.

- `editor.on("focus", function(){console.log("hi, focus..");});`
- `editor.setOption("value", "Hello World\n");`
- `document.activeElement` //I've got the body element
- `editor.focus();`
- `document.activeElement` //returns the textarea

**Comment by peterkroon** [comment]
You are right. This is not a CodeMirror bug.
This used to be different but that was probably some time ago. I remember being able to focus the CM instance from the console.

The onfocus is triggered when the webconsole is not active.
Example:

- editor.on("focus", function(){console.log("hi, focus.."); editor.setOption("value", "New value.\n");});
- `document.getElementsByTagName("textarea")[1].onfocus = function(){console.log("test");};`
- `editor.setOption("value", "Hello World\n");`
- `document.activeElement` //the body element
- `editor.focus();`
- `document.activeElement` //returns the textarea

To get the focus triggered, click somewhere in the webpage. No need to click in the editor.
