### ISSUE TITLE
A subtle bug when closebrackets addon works with simplemode

### ISSUE THREAD

**Issue by rrandom** [codemirror/CodeMirror#3660]
In such situation, when input a single `"`, codemirror will not insert closing `"`, but will insert it when input `""` which will become `"""`.

  I found that `rust.js` and `handlebars.js` have this bug and `factor.js` will not have this bug, although they all defined by `defineSimpleMode`. That's because `factor.js` implement string token with a `next`. And In `rust.js` or `handlebars.js`, [`type1`](https://github.com/codemirror/CodeMirror/blob/master/addon/edit/closebrackets.js#L190) will not return `string` as  in `factor.js` but will return `null`. that's because [`"\"".match(/""/)`](https://github.com/codemirror/CodeMirror/blob/master/addon/mode/simple.js#L119) will return null.

  So I think it's better to write `rust.js` and `handlebars.js` in `factor.js` way.

Bug illustrate below 

http://codepen.io/rrandom/full/RWOYmY/

**Comment by marijnh** [comment]
The problem wasn't directly related to the simple mode addon, but that addon did invite writing string matching as a single regexp, which then wouldn't match if the string wasn't closed yet. I've updated the Rust, Handlebars, and NSIS modes to also recognize unclosed strings, which should address this.
