### ISSUE TITLE
Change event not including autoindentation

### ISSUE THREAD

**Issue by mihaipopa12** [codemirror/CodeMirror#3662]
Hi,

CodeMirror v5.8.0, tested in Chrome and Safari. CodeMirror does not include autoindentation spaces in change events.

##### Configuration
```javascript
var editor = CodeMirror.fromTextArea(editorArea, {
  lineNumbers: true,
  mode: {name: "javascript", globalVars: true},
  keyMap: "sublime",
  autoCloseBrackets: true,
  matchBrackets: true,
  showCursorWhenSelecting: true,
  theme: 'monokai',
  foldGutter: true,
  gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"],
  tabSize: 2
});
```
##### Reproduction
1. Open a CodeMirror instance
2. Type '{'. The matching bracket is automatically generated. Therefore, the change event is:

 >  {"from":{"line":0,"ch":0},"to":{"line":0,"ch":0},"text":["{}"],"removed":[""],"origin":"+input"}

As expected, so far.
3. Type newline between the two brackets. This causes the empty line to be autoindented with two spaces:
```javascript
{
  
}
```
Only the following change event is fired:

> {"from":{"line":0,"ch":1},"to":{"line":0,"ch":1},"text":["","",""],"removed":[""],"origin":"+input"}

However, I would have expected the following change event:

> {"from":{"line":0,"ch":1},"to":{"line":0,"ch":1},"text":["","``  ``",""],"removed":[""],"origin":"+input"}

Is this the expected behaviour and I am doing something wrong? Thanks!

**Comment by marijnh** [comment]
It does, but in a different change event, fired separately.
