### ISSUE TITLE
Shift-Cmd-Z to redo on a Mac with a Dvorak keyboard layout doesn't redo

### ISSUE THREAD

**Issue by maryrosecook** [codemirror/CodeMirror#3668]
Hi Marijn!

To reproduce:

* Go to codemirror.net
* Enable the Dvorak keyboard layout.
* Type some characters into the example CodeMirror editor on the homepage.
* Press Cmd-Z to undo.
* Press Shift-Cmd-Z to redo.  (Nothing happens.)
* Select Redo from the Chrome Edit. (Nothing happens.)

Extra notes:

* Mac OS X 10.11.1 (El Capitan).
* Chrome 46.
* Pressing Cmd-Y redoes correctly.
* Using a US QWERTY keyboard layout stops the bug from occurring.

Thanks!

**Comment by marijnh** [comment]
Are you pressing the key labeled Z or the one that Dvorak maps to Z? I'm guessing the former, since that seems to be how keydown event keycodes work.

The mapping from key events to bindings is relatively straightforward. Have you checked whether a sensible event is generated in this case? What does `CodeMirror.keyName` return when called on the event?

**Comment by maryrosecook** [comment]
Thanks a lot for your response!

For your first question: I'm pressing the key Dvorak maps to `z` (on a keyboard with US QWERTY keycap markings, this is marked as `/`).

I can't answer your second question, I'm afraid.  See below for why!

I went to the CodeMirror homepage in Chrome and executed the following code in the console:

```
window.onkeydown = function(e) {
  console.log(e)
};
```

I then put the caret into the CodeMirror textarea near the top of the page and pressed the key combos below.

If I press the key bound to `z` on it's own (on a keyboard with US Qwerty keycap markings this is marked with `/`), a `KeyboardEvent` is logged that has a `keyCode` attribute of `90` (which is reported by http://keycode.info to be the `keyCode` for `z`.  All as expected.

However, if I press `Shift-Command-Z` I get two events (not the expected three):

KeyboardEvent 1: `keyCode` of `16` (keycode.info reports this as the shift key).
KeyboardEvent 2: `keyCode` of `91` (keycode.info reports this an the left command key).

Note that no event for the `z` key being pressed was emitted.

As an experiment, I pressed `Shift-Command-V` and got the expected three events:

KeyboardEvent 1: `keyCode` of `16` (keycode.info reports this as the shift key).
KeyboardEvent 2: `keyCode` of `91` (keycode.info reports this as the left command key).
KeyboardEvent 3: `keyCode` of `86` (keycode.info reports this as `v`).

Is this helpful?

**Comment by marijnh** [comment]
Yes, but it suggests that Chrome is not firing an event at all for the Z press in Shift-Cmd-Z, which means CodeMirror also can't handle any event. (I expect you'll see the same if you don't focus or even load CodeMirror).

Does a key event get fired when you disable Dvorak layout and then press Shift-Cmd-Z? What about Shift-Cmd-slash?

**Comment by maryrosecook** [comment]
I switched from Dvorak to a US QWERTY keyboard mapping and tried the key combos.

* For Shift-Command-Z, the expected three events get fired.
* For Shift-Command-/, a event gets fired for Shift and an event gets fired for command, but no event gets fired for the `/`.  Instead, the Chrome Help menu appears!

Further, I think you're right that no key event gets fired for the `z` in `Shift-Command-Z` in Dvorak. I made a test textarea (without CodeMirror) here: http://maryrosecook.com/textareaexample.html It includes code that binds to `keydown` events on the textarea.  In Dvorak mode, when I press `Shift-Command-Z`, only the events for shift and command get fired.

Should I file a bug on Chrome?

**Comment by marijnh** [comment]
This does indeed sound like a Chrome bug (or even an OS X bug -- did you test another browser?). So reporting it elsewhere sounds like a good idea. As for CodeMirror -- I'm closing this, since it sounds like  there really is no way to fix this on my side.

**Comment by maryrosecook** [comment]
Yes I tested in Safari and it works fine.  It may just be Chrome.  Thanks a lot for looking into it!
