### ISSUE TITLE
Spaces being replaced by Tabs 

### ISSUE THREAD

**Issue by sindhus** [codemirror/CodeMirror#3670]
We used to use CM 4.11.0 and recently upgraded to CM 5.8.0 in production and we noticed that both `gfm` and `markdown` mode of the editor renders space as tabs (evident in DOM: spaces being wraped in `cm-tab`)

![screen shot 2015-11-25 at 1 28 56 pm](https://cloud.githubusercontent.com/assets/4291156/11391466/b046472e-9378-11e5-9cc4-c135081bb7b8.png)

Notice how in description field, the area between words "blah" and "blah" are tabs and not spaces even though I pressed the spacebar. 

How can I fix this? What could be causing this? Thanks!

**Comment by marijnh** [comment]
CodeMirror does not change the content you give it, and by default does not react to the spacebar by inserting a tab, so I think you'll have to look at other components of your system (or your own CodeMirror-related code).

If you can isolate this in a page with only CodeMirror in it, feel free to reopen or add a comment.
