### ISSUE TITLE
[JavaScript Mode] syntax highlighting of global/local/undefinied variables

### ISSUE THREAD

**Issue by chriscoyier** [codemirror/CodeMirror#3674]
http://codemirror.net/mode/javascript/

Slightly weird that it's colored differently? I think?

![img](http://d.pr/i/qwvp/iJpTh4Hz+)

**Comment by marijnh** [comment]
I consider coloring local variables specially a feature, but if you don't like it, I guess you can either change your theme to make `variable-2` the same a `variable`, or submit a pull request to support a new option in the JavaScript mode.

**Comment by chriscoyier** [comment]
Nah it's fine with me. A user just reported it to us at CodePen so I figured I'd pass it along.

**Comment by yukulele** [comment]
I think global variable should be colored in blue (on line 4&12) like local variable
