### ISSUE TITLE
Is it possible to make replaceRange not triggering change event?

### ISSUE THREAD

**Issue by coodoo** [codemirror/CodeMirror#3691]
In some cases I may want to programmatically change the texts by invoking `replaceRange` but do not want to trigger a `change` event, is that possible?

**Comment by marijnh** [comment]
Nope. Many uses of the "change" event rely on getting every single change (so that they can keep a consistent view on the document) so this would not be a good idea.

**Comment by coodoo** [comment]
Thanks for the reply and that makes sense, I've found a way to workaround the issue.

**Comment by olpoco** [comment]
@coodoo  how did you work around this?

**Comment by coodoo** [comment]
`replaceRange` has an API like this:

```
doc.replaceRange(replacement: string, from: {line, ch}, to: {line, ch}, ?origin: string)
```

I passed in the `origin` argument with a value `@ignore` and made sure all event listeners check for that argument then act accordingly, worked like a champ for me, hth.
