### ISSUE TITLE
Ada Support

### ISSUE THREAD

**Issue by Shafaet** [codemirror/CodeMirror#3692]
Codemirror doesn't have syntax highlight support for Ada language. Please have a look at it.

**Comment by marijnh** [comment]
I don't implement modes on request, but I've added Ada to [the mode wishlist](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list)

**Comment by mgrojo** [comment]
> I don't implement modes on request, but I've added Ada to [the mode wishlist](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list)

That link is now broken. Where is that wishlist?

**Comment by marijnh** [comment]
There is no wishlist anymore, and no new modes will be added to the main distribution. To get support for a new mode, you'll have to implement and distribute it as a separate package (see for example the [Elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir)).
