### ISSUE TITLE
GitBook embed?

### ISSUE THREAD

**Issue by kevinSuttle** [codemirror/CodeMirror#3694]
Example: https://plugins.gitbook.com/plugin/tonic

**Comment by marijnh** [comment]
What?

**Comment by kevinSuttle** [comment]
What I'm saying is that it would be great to embed a Codemirror into a GitBook. https://ymcatar.gitbooks.io/gitbook-test/content/testing_ace.html

**Comment by marijnh** [comment]
I see. That doesn't sound like it would be in scope for this repository, though.
