### ISSUE TITLE
ShowHint `mousemove` is triggered on cycling through the suggestions

### ISSUE THREAD

**Issue by basarat** [codemirror/CodeMirror#3698]
Started with https://github.com/codemirror/CodeMirror/pull/3636. Only happens if you go across the hints *first -> last* (up arrow) or *last -> first* (down arrow) and if the cursor is in a position over the show hint list. `mousemove` is triggered even if the cursor isn't moved. So instead of going to `first` or `last` it jumps to the cursor location.

Tested on `chrome` on both windows and mac.

Here is a recording showing the issue: 
![show hint error](https://cloud.githubusercontent.com/assets/874898/11730997/85daa856-9fec-11e5-8cd3-105c5d0022a2.gif)

If one puts a `console.log` here : https://github.com/codemirror/CodeMirror/blob/4bdf6440429bc455f4ce39486d424fba0be7fa14/addon/hint/show-hint.js#L300 it will get triggered. Would love your input on how to approach a fix :rose:

**Comment by marijnh** [comment]
Could it be that your mouse is so sensitive that the desktop vibrations caused by hitting the arrow keys cause it to move? There shouldn't actually be any mousemove event firing unless the mouse actually moves, but I guess that could happen.

I think attached patch solves this.

**Comment by basarat** [comment]
> Could it be that your mouse is so sensitive that the desktop vibrations caused by hitting the arrow keys cause it to move?

No, because it only happens on first to last or last to first transition. Also the patch looks empty 🌹 

Thanks for this project 🌹

**Comment by basarat** [comment]
@marijnh I applied the patch locally and its made it worse in that it doesn't work if I use a custom render function:

![broken](https://cloud.githubusercontent.com/assets/874898/11833513/78bc8606-a417-11e5-91e4-8c9918c59228.gif)

And for the simple one it is still broken. I noticed it also jumps if you cause any form of `scroll` to happen on the autocomplete (e.g. moving an item before the first item shown using `up` arrow):

![alsojumpsonscroll](https://cloud.githubusercontent.com/assets/874898/11833540/a948a930-a417-11e5-8c4e-6e70136ad292.gif)

Thanks :rose:

**Comment by marijnh** [comment]
Ugh. Well, this week is not one where I have time to debug other people's code. I've reverted the whole behavior for now. @continuata Do you want to take a look at this?

**Comment by continuata** [comment]
Will do

**Comment by continuata** [comment]
seems to be caused by the fact your cursor is hovering over the hint pane when it scrolls, which is triggering a mouse-move event (as the window is moving behind the static cursor)  ... which then initiates another select event.
I may be able to get it to ignore mouse move events whilst scrolling ... I'll take a proper look soon.

**Comment by mihailik** [comment]
Ignoring scrolling for say 200ms after keydown/up would make it go away and also fix over-sensitive mouse problem.

**Comment by continuata** [comment]
Yes that should work

**Comment by basarat** [comment]
> I've reverted the whole behavior for now

Thank you :rose:

> seems to be caused by the fact your pointer is hovering over the hint pane when it scrolls, which is triggering a mouse-move event (as the window is moving behind the static pointer)

Yup :rose:

**Comment by basarat** [comment]
I updated to `5.13.4` and as the reversion commit is there : https://github.com/codemirror/CodeMirror/commit/06e83fd66ebe639038eb64013891a1535ed07f25 I'm fine without this being fixed. Leave it to you guys to `close | keep open` :rose:
