### ISSUE TITLE
vim bindings: text object i] not working

### ISSUE THREAD

**Issue by ascheidl** [codemirror/CodeMirror#3718]
in the codemirror vim bindings demo putting the cursor on BUFSIZ and hitting di] has no effect.

tested on Win7, FireFox

**Comment by marijnh** [comment]
@heppe Let me know if I should stop mentioning you on every Vim PR, but here's another one I'd like to have a Vim user review. Thanks!

**Comment by marijnh** [comment]
(Err, this is not a PR, sorry about that. I shouldn't be triaging bugs when it's late.)

We don't currently have an active maintainer for the Vim mode, but I'll leave this open and hopefully someone will pick it up eventually.

**Comment by nightwing** [comment]
This is likely related to keyboard layout. di] works with qwerty

**Comment by acornejo** [comment]
this works for me too, I tested on OSX and Linux, and with chrome and firefox. I think this is not a bug with codemirror
