### ISSUE TITLE
Julia syntax to match github's

### ISSUE THREAD

**Issue by pabloferz** [codemirror/CodeMirror#3725]
Currently Julia syntax does not match the one used by github for Julia's source code.

I have some proposals to improve it and make it work (in most of the cases) for

- Function calls
- Function definitions
- Multi-line comments
- Multi-line strings

I don't know if there is a desire of handling syntax this way or if the current syntax scheme is preferred, so I'm opening an issue before submitting a PR.

@malmaud @Carreau

**Comment by malmaud** [comment]
Ya, that PR would be highly appreciated.

**Comment by marijnh** [comment]
Fixed via #3731
