### ISSUE TITLE
Show number of matches on search-replace (and on persistent search)

### ISSUE THREAD

**Issue by sirtet** [codemirror/CodeMirror#3728]
It would be nice if the search-replace dialogue would show the count of matches like so:

Match 1 of 5: Replace? **Yes No All Stop**

**Comment by marijnh** [comment]
I guess it would, but the scope of this module is potentially huge, and I don't want to maintain an all-possible-bells-and-whistles search module. If you want this, you'll have to write your own version.

**Comment by 343IsaMesih** [comment]
It is also really important for me... I want to help for this...

**Comment by Gatunox** [comment]
Yes, it sounds good to have the number of items found, either on search of replace funtions
