### ISSUE TITLE
Add key bindings to buttons in dialog.js

### ISSUE THREAD

**Issue by sirtet** [codemirror/CodeMirror#3729]
Something i noticed in search/replace, but i think it might belong to dialog.js?
(Testing at https://codemirror.net/demo/search.html, using chrome 47 win7_64)

On search/replace, the YES button is active, so i just need to hit enter for yes. But it seems there's no way via keyboard to use the other buttons like NO etc.

1. There could/should be Keybindings for the buttons, visualized with underlinded Cars
(can only do bold here) **Y**es **N**o **A**ll **S**top

2. Cursor keys should/could allow to move between buttons.

**Comment by marijnh** [comment]
Don't tab and shift-tab, the standard way to move between browser controls, work?

**Comment by sirtet** [comment]
Ah i see, yes it does, but...
Rab-ing after the last button exits the dialogue, i think it should cycle through it.
I had windows dialogues in mind, there you can move the focus with cursor keys (stops at end) and with tab (loops to the first button after last).
That's why i also had the idea of direct keybindings.

PS:
Tab-ing on the "replace" and "with" steps, aborts the dialogue.
I think that's wrong from the user-experience. It should... hmm, do the same as enter?

**Comment by nivan22** [comment]
yes it does, but...
Tab-ing after the last button exits the dialogue, i think it should cycle through it.
I had windows dialogues in mind, there you can move the focus with cursor keys (stops at end) and with tab (loops to the first button after last).
That's why i also had the idea of direct keybindings.

**Comment by marijnh** [comment]
I think being able to tab out of the dialog is a feature (locking users out of expected browser behavior is generally a bad idea).

Also, tabbing out of the dialog seems like a very different action than confirming it, so no, I don't think that should do the same as enter.

In general, if you want a different search UI, you can implement your own on top of searchcursor.js and (optionally) dialog.js.

**Comment by sirtet** [comment]
Ok i see.
In my view, i just saw the dialogue more as a DIALOGUE than a part of the page. And on dialogues, browsers don't leave them with tab either i think.
For aborting, i thought ESC. was enough, and very standard.
