### ISSUE TITLE
Change origin undefined when user deletes delimiters using the closebrackets addon

### ISSUE THREAD

**Issue by den1k** [codemirror/CodeMirror#3733]
The `.origin`any delete operation should presumably be `"+delete"` or something similar.
However when the user deletes a delimiter using the `closebrackets` addon, the `.origin` of the change can be `undefined`.
It will appear correctly as `"+delete"` if the cursor is behind the close delimiter before the delete operation, e.g.
```
abc[]<cursor>
result => abc[
```
However `.origin` will be `undefined` when the cursor is inside the delimiters, e.g.
```
abc[<cursor>]
result => abc
```

This only occurs with empty brackets parenthesis and quotes.

**Comment by marijnh** [comment]
Good point. Attached patch adds the fitting origin. But note that you can't rely on origins to match what you'd expect -- user code can put anything in there. They are an expression of intent, not a hard guarantee, and if you depend on a specific feature of a change (for example, whether it deletes something), you should inspect the actual change data.

**Comment by den1k** [comment]
@marijnh Thanks for the patch!

I've come around to understanding your point about origin. My use case is meta in that I need more granular event information. Imagine you are recording all the actions incl. their attributes a user and editor perform that lead to a change in the text. Using that, one should be able to replay all the changes by sending events to some dispatching function. Whether these events are triggered by the user or programmatically should not matter to their effect.
