### ISSUE TITLE
What about not moving the cursor if setValue does not change the content?

### ISSUE THREAD

**Issue by radek-holy** [codemirror/CodeMirror#3734]
Hello,

I'm trying to integrate CodeMirror into my Angular 2 based application. IIUIC, Angular encourages people to write forms in such a way that a controller listens to events fired from the form fields and updates the internal models of these fields. Under certain circumstances the controller [fires events back](https://github.com/angular/angular/issues/6114) to the form fields if the internal model changes. (This is useful e.g. if you need to initialize the field with a value.)

In such case in my application, every change in the CodeMirror editor results in an event that consequently calls the editor's `setValue` with the same value which is already there. Since the `setValue` method apparently sets the cursor position to the beginning of the document, it results in resetting the cursor position after every change in the editor.

To resolve this, I have included a test `if (value != editor.getDoc().getValue())` before the `setValue` call. There is a problem that if I hold a key down, it apparently updates the editor's value before the previous event is handled which results in an endless loop. But I have to investigate this more deeply first. For now, I just wanted to suggest whether it would make sense to (optionally) not reset the cursor position if I (consequently) call something like `doc.setValue(doc.getValue())`.

**Comment by marijnh** [comment]
This would be overhead and complexity, as well as a non-obvious exception in the editor's behavior, for a use case that concerns precisely only you. So no, I'm not going to do this. Just do your own check, as you describe (and figure out where the infinite loop is coming from -- "change" event occur after the change has been applied, so you should definitely see the post-change document when they fire)

**Comment by radek-holy** [comment]
Well, speaking of obviousness... Is this behaviour (moving the cursor to the beginning) documented somewhere? I failed to find the reason why the cursor is moved to the beginning rather than to the end, or to the beginning of the first difference or to the end of the last difference.

**Comment by marijnh** [comment]
When you open a document, the cursor defaults to the start, since that's what editors do. `setValue` is equivalent to dropping the current document and opening a new one. There is no comparing of the old and new document happening.

**Comment by LeonStaufer** [comment]
I do not believe this is an issue that "concerns precisely only [@radek-holy]". 
I am working on a live editor and I believe this is an issue that would affect anyone replacing the content of the editor with other content (which I imagine is quite a number of people).

@marijnh explains why using `setValue` causes this behavior. However, maybe another function could be implemented that updates the content and maintains the cursor position.

**Comment by LeonStaufer** [comment]
Okay fair enough. If I may ask, what's the harm of adding this functionality?
If it's a question of prioritization, I would gladly add the function and submit a PR.

**Comment by marijnh** [comment]
In order to keep the core's size and interface size reasonable, I prefer to keep utilities that can easily be implemented on top of it, unless they are very commonly used, out of the core

**Comment by LeonStaufer** [comment]
That is very reasonable. 
Would it be open to adding it as a note to the manual, for future users who might encounter the problem and not discover this issue?

**Comment by marijnh** [comment]
Not really—this isn't something that makes a lot of sense in the first place (if you set a different document there's no obvious way the selection should be 'preserved') so I don't think it belongs in the manual
