### ISSUE TITLE
RFE: an even more aggregated event

### ISSUE THREAD

**Issue by radek-holy** [codemirror/CodeMirror#3735]
Hello,

I'm trying to integrate CodeMirror into my Angular 2 based application. IIUIC, Angular encourages people to write forms in such a way that a controller listens to events fired from the form fields and updates the internal models of these fields. However, if I e.g. hold a key down for several seconds, I don't need to update the model on every change. It would be enough to update it e.g. at a rate of 60 FPS. Actually, this huge amount of events generated per second probably causes [some problems](https://github.com/angular/angular/issues/6103) to my browser and I can imagine that it may cause some other problems and that it can produce an unnecessary load.

Would it make sense to add a new event which is fired at a reasonable rate even if someone holds a key down?

FYI, it was [suggested](https://github.com/angular/angular/issues/6103#issuecomment-167025061) to me to use RxJS's `throttleTime`. I just thought that it would make sense to have it directly in the CodeMirror.

**Comment by marijnh** [comment]
No, this is too specific for doing in the editor. [Debouncing](http://eloquentjavascript.net/14_event.html#h_AOVmaqj10I) events in your own code is an easy and widely understood technique, just do that.
