### ISSUE TITLE
touch events not registering callbacks

### ISSUE THREAD

**Issue by justbittin** [codemirror/CodeMirror#3736]
'mousedown' and 'dblclick' not registering events on touch.  Simple solution is to force the callbacks here:

    on(d.scroller, "touchend", function(e) {
      var touch = d.activeTouch;
      if (touch && !eventInWidget(d, e) && touch.left != null &&
          !touch.moved && new Date - touch.start < 300) {
        var pos = cm.coordsChar(d.activeTouch, "page"), range;
        if (!touch.prev || farAway(touch, touch.prev)) // Single tap
          range = new Range(pos, pos);
        else if (!touch.prev.prev || farAway(touch, touch.prev.prev)) // Double tap

Simply where you have commented Single tap register the mousedown eventhandler, Double tap.... the same.

This way cm.on('mousedown', function) can be used in mobile environments without modifying the core codemirror.js every update.

**Comment by marijnh** [comment]
I don't think the single tap case in the touchend handler really corresponds closely enough to a mousedown event to pretend it is the same.

I could change `onMouseDown` to first run `signalDOMEvent` and then check for an active touch event. Would that solve your issue?

**Comment by justbittin** [comment]
How about adding 'touchstart', 'touchmove', 'touchend', 'touchtap', 'touchdbltap' event handlers for Codemirror.  This way on updating codemirror there is no reason to modify the core.  Since mobile devices are supported a:

cm.on('touchtap', function() {
// handle the touch
});

Would be a simple solution for handling touch events -- and from your code, you would just need to signal these events.

Just looking for a solution you can adopt as part of the core to stop the need to modify codemirror.js on every update.

Thank you for your consideration.

**Comment by marijnh** [comment]
CodeMirror does not interfere with any of touchend, touchtap, touchmove, or touchdbltap, so you can just register those on the DOM and there's no need to involve CodeMirror.

Attached patch adds a CodeMirror event for `touchstart`, and makes sure `mousedown` is fired even during touch.
