### ISSUE TITLE
editor.getCursor() not working in mobile

### ISSUE THREAD

**Issue by merbin2012** [codemirror/CodeMirror#3750]
editor.getCursor() not working in mobile
In desktop system return {line: 7, ch: 6}
but in mobile return {line: 7, ch: 0, bad: true}
what can I do?

**Comment by marijnh** [comment]
Without some information about how you got to the state where it returns that, there is nothing I can say about this.

**Comment by adrianheine** [comment]
I'm closing this due to a lack of details. Please feel free to re-open if you have further information.
