### ISSUE TITLE
Fastclick incompatibility

### ISSUE THREAD

**Issue by horner** [codemirror/CodeMirror#3751]
When fastclick is on the page with CodeMirror, clicks for focus are ignored.   Others have documented the problem in their projects: https://github.com/TryGhost/Ghost/issues/5717

I have commented on an existing pull request in fast click that fixed the problem.   The call to blur in the simulated click makes CodeMirror lose focus: https://github.com/ftlabs/fastclick/pull/350

I opened this issue to make others aware.

**Comment by marijnh** [comment]
This seems like an issue in another component or an integration issue. Going to close, since I don't have time to debug such things.
