### ISSUE TITLE
findPosH inconsistent behaviour with different unit input

### ISSUE THREAD

**Issue by ohlo** [codemirror/CodeMirror#3753]
findPosH, given a negative input and using "char" units moves backward over newlines as expected.

however, when doing this using "group" unit, it stops at the first newline and "hitSide" is true in the result, which it shouldn't be unless it is the start or end of the document, as described in docs: "When the motion was clipped by hitting the end or start of the document, the returned value will have a hitSide property set to true"

Please let me know if you require any more info.

**Comment by marijnh** [comment]
Attached patch should fix this.

**Comment by ohlo** [comment]
that was quick! thanks
