### ISSUE TITLE
Jade mode fails to auto-load

### ISSUE THREAD

**Issue by Leonya** [codemirror/CodeMirror#3755]
1) Go to https://codemirror.net/demo/loadmode.html
2) Paste the template from http://jade-lang.com/
3) Type `index.jade` in the filename input
4) Press `change mode`

The editor clears, console shows the following error:

`Uncaught TypeError: jsMode.startState is not a function`

This bug was originally reported by a user of my application but is easily reproduced out of the box.

**Comment by Leonya** [comment]
By the way, I sent a pull request that fixes a couple of typos in jade.js

**Comment by marijnh** [comment]
This appears to be fixed by 754939707b
