### ISSUE TITLE
Using Capybara Webkit to enter text into CodeMirror

### ISSUE THREAD

**Issue by tansaku** [codemirror/CodeMirror#3756]
We're writing some tests to check the operation of a site using codemirror.  We're using capybara webkit, but it's not clear how to simulate entering text into the editor.

I've found some mention of a solution online that involves making an editor variable global which feels like a bit of a hack: 

http://stackoverflow.com/questions/30376526/fill-in-editor-textarea-using-capybara-webkit

Does anyone know of a good way we can use to enter code into codemirror using Capybara Webkit or similar that's a bit less hacky?

**Comment by marijnh** [comment]
No idea. In any case, this isn't an issue with CodeMirror itself.
