### ISSUE TITLE
Block Comment Indentation

### ISSUE THREAD

**Issue by AlJohri** [codemirror/CodeMirror#3765]
Hi,

I opened this issue on jupyter notebook and wanted to follow up upstream here.

https://github.com/jupyter/notebook/issues/954

Is there anyway to replicate the default comment indentation behavior from Sublime Text?

![](http://i.imgur.com/DZ2HNfh.gif)

Essentially, if within a block, it indents the comment symbol. If containing the the start, end, or both of the block, it does not indent the comment symbol.

**Comment by vincentwoo** [comment]
If you use the sublime keymap, this is default behavior. I made this change a while ago and it's pretty easy to port into your application as well: https://github.com/codemirror/CodeMirror/blob/master/keymap/sublime.js#L246

It's simply a matter of calling toggleComment with `indent: true`

**Comment by marijnh** [comment]
Indeed, the feature exists, you just need to bind it differently.

**Comment by stdedos** [comment]
> If you use the sublime keymap, this is default behavior. I made this change a while ago and it's pretty easy to port into your application as well: [/keymap/sublime.js@`master`#L246](https://github.com/codemirror/CodeMirror/blob/master/keymap/sublime.js#L246) [](/codemirror/CodeMirror/blob/HEAD@{2016-01-14T23:47:53Z}/keymap/sublime.js#L246)
> 
> It's simply a matter of calling toggleComment with `indent: true`

How can you change the default keymap?
