### ISSUE TITLE
[swift] No indenting on scope open

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#3766]
# Description

The Swift mode does not appear to indent the cursor when opening new scopes. This is generally how the other modes work (especially clike, which swift is very similar to).

## Reproduction

1. Go to https://codemirror.net/mode/swift/index.html
2. Replace editor contents with `if true {`
3. Hit enter

Here you would expect the next line to start indented, but the cursor remains on column 0.

**Comment by marijnh** [comment]
The Swift mode does not indent, period. A pull request that adds this would be nice, but as it is, the feature does not exist.

**Comment by vincentwoo** [comment]
I have a very hard time following the examples of the other modes, and would consider paying for this to be added to the Swift mode. Would you be interested in spending a bit of time implementing it?  I can be reached again at vincent@coderpad.io.
