### ISSUE TITLE
Error: Mode django failed to advance stream.

### ISSUE THREAD

**Issue by dperetti** [codemirror/CodeMirror#3767]
Can be tested here : https://codemirror.net/mode/django/index.html
With the following code :

    {# Load the products using an assignment tag #}
    {% get_products as products %}

    <div class="container">
        {% render_bundle 'Downloads' %}
    </div>

Apparently the comment is the issue.

**Comment by dperetti** [comment]
While I'm at it, would it possible to break the analyse and display non-colored code instead of throwing an error (I don't see a way to catch it, is there any ?).

Thanks.

**Comment by dperetti** [comment]
The fix is here : https://github.com/dperetti/CodeMirror/commit/5201a7003aa8c41adc98bf128cbb28332dfb643c

**Comment by marijnh** [comment]
I've pushed an alternative patch (db3c12d).

A mode not advancing a stream is a bug, and I don't want to go down the road of trying to 'sandbox' bugs in modes, so yes, a crash is the appropriate reaction to that.
