### ISSUE TITLE
.CodeMirror pre z-index issue

### ISSUE THREAD

**Issue by andrew-vandenbrink** [codemirror/CodeMirror#3770]
.CodeMirror pre by default have z-index:2
This causing some issue with another js component which having overlay

A workaround can use this code after initialization
```
$('.CodeMirror pre').css({ "z-index": "0" });
```

The problem is every editing on any line always making that line to have z-index:2 again.

I'm not quite sure the reason to have z-index:2 by default, is it possible to change z-index always 0 by default in the next release?

**Comment by marijnh** [comment]
Could you describe the nature of the problem you are having? Given the way CSS z-indices work, I can't really think of a way in which this could cause a problem that isn't solved by a single line of CSS.

**Comment by andrew-vandenbrink** [comment]
No workaround
![image](https://cloud.githubusercontent.com/assets/12871379/12356133/3a7fea26-bba1-11e5-857e-8a5e29971664.png)

With workaround
![image](https://cloud.githubusercontent.com/assets/12871379/12356167/5da9c972-bba1-11e5-92ca-5ed4cb557f60.png)

With workaround, change one line
![image](https://cloud.githubusercontent.com/assets/12871379/12356199/877b879a-bba1-11e5-85d8-5d6bc92dffd3.png)

Of course I can change codemirror.css
```
.CodeMirror pre {
  z-index: 2; /*Change this to 0*/
}
```
But what will be the consequence of changing it?

**Comment by marijnh** [comment]
What is the parent node of that overlay? And in which browser are you seeing the problem?

And no, definitely don't change codemirror.css

**Comment by andrew-vandenbrink** [comment]
The other way around is to change the z-index overlay, that will also fix the issue, I assume z-index:10 is sufficient?

**Comment by marijnh** [comment]
Something like `.CodeMirror { z-index: 0 }` should do it.
