### ISSUE TITLE
Gutter Marker - Multiline Support

### ISSUE THREAD

**Issue by paulsputer** [codemirror/CodeMirror#3778]
Hi, great work on CodeMirror! I'm currently integrating it into Gitblit (https://github.com/gitblit/gitblit) to support in-browser editing of repository files.

The code sample on gutter notes (https://codemirror.net/doc/upgrade_v3.html#gutters) gave me a thought that this would be a useful way to implement and present code review and gitblame pages.  However, it would require line ranges to be defined and it looks as though setGutterMarker only accepts a single line.

Would a PR be accepted for allowing multiline gutter markers in a similar way to the markText functions where a from-to range can be provided?  Or can you recommend a way to do this already using the markText functionality?

**Comment by marijnh** [comment]
What would multiline gutter markers do, exactly?

**Comment by paulsputer** [comment]
@marijnh setting a gutter marker across a range of lines along with an alignment option for placing the passed element either to each line, or align within the group i.e top, middle, bottom line.

`cm.setGutterMarker(from: {line}, to: {line}, gutterID: string, value: Element, align: string (each|top|middle|bottom) )  → LineHandle[]`

The `lineInfo` function would then include all gutters which are defined on or that cross over the given line.
`cm.lineInfo(line: integer|LineHandle) → object`

For example building upon the v3 gutter sample, a note relevant to lines 1 through 5 could be placed with align:middle, so only one note is shown.  However, if lineinfo is called on any line between 1 and 5 it will return the associated note.

In-addition multiple markers could be placed on the same line in the same gutter, allowing support of multiline markers whose ranges cross.  Currently it appears only one item per line and gutter type pair is supported.

Perhaps this is an application specific use case better handled outside the core codemirror source.  What do you reccommend?

**Comment by marijnh** [comment]
Nope, that doesn't really fit the current model, where lines (including their gutter content) are rendered separately and independently, and doesn't seem that much of a win.
