### ISSUE TITLE
CodeMirror-gutter Re-size

### ISSUE THREAD

**Issue by wissamsaikali** [codemirror/CodeMirror#3781]
i am using the merge plugin. ( https://codemirror.net/demo/merge.html )

Scenario : 
1 - Write a long commands on the same line
2- try to scroll right than left
3- gutters will move 

Please check the attached files 
i've tried to refresh the editor but it didn't worked .
how can i fix this ?

Thank you 
Regards
![screencapture-codemirror-net-demo-merge-html-1453211741453](https://cloud.githubusercontent.com/assets/7591496/12420660/9f2cddf8-bec6-11e5-9d5f-aa5c2b856eab.png)

**Comment by marijnh** [comment]
Hi. This does not happen for me on Chrome. Which browser / version are you using?

**Comment by wissamsaikali** [comment]
Hey, i am using Version 47.0.2526.111 (64-bit) on ubuntu

On Wed, Jan 20, 2016 at 11:54 AM, Marijn Haverbeke <notifications@github.com

**Comment by marijnh** [comment]
Hm, that's exactly what I'm using. Could you describe your steps in more detail? When I go to the merge demo page, and scroll either of the editors right and then left, the gutter stays in place.

**Comment by wissamsaikali** [comment]
1. Go the merge demo page
   2. Keep adding additional characters at the end of any line till the
   scrollbar on the left editor becomes clearly smaller than the one on the
   right
   3. Now when you scroll left and right on the left editor you will notice
   that the gutter will shift to the right

PS: this issue appears on Chrome Windows as well.

Thank you

On Wed, Jan 20, 2016 at 12:03 PM, Marijn Haverbeke <notifications@github.com

**Comment by kepta** [comment]
+1, I was able to reproduce it on
Browser Firefox 
Mac

**Comment by rtparsons** [comment]
Pull request to fix this #3788

**Comment by marijnh** [comment]
The editor was clipping the horizontal scroll position wrong, leading to it believing it was setting its horizontal scroll somewhere the DOM wouldn't allow it to, confusing the gutter alignment code.
