### ISSUE TITLE
Is it possible to initialize codemirror from a contenteditable?

### ISSUE THREAD

**Issue by cauburtin** [codemirror/CodeMirror#3783]
Because this is awkward: http://jsbin.com/hakipo/edit?html,js,output

**Comment by marijnh** [comment]
This is out of scope for CodeMirror, but yes, it's definitely possible (get HTML, create editor with that HTML as content, I guess).

**Comment by cauburtin** [comment]
Thanks marijnh, yes I can get innerHTML, but how do you create the editor from that string, how do you position the editor for exemple as an overlay on top of the element, and how do you retrieve that content before destroying it? many questions sorry but that's exactly what I'd like
