### ISSUE TITLE
[gfm] Add support for newlines to be treated as <br>

### ISSUE THREAD

**Issue by BrianOtto** [codemirror/CodeMirror#3784]
GitHub treats newlines as a `<br>`, and so it doesn't force you to enter two spaces (or a `<br>` tag) to get this kind of formatting. Can you please add support for this, or at least make it a configurable option. Many backend parsers support this, and it would be nice if your preview could match their output.

**Comment by marijnh** [comment]
CodeMirror doesn't do any kind of rendering/previewing, it just highlights the source text, and I don't think there's an difference in text highlighting needed between these two dialects of Markdown. As such, it sounds like you filed this in the wrong project.

**Comment by cben** [comment]
Only relevant aspect that differs in the https://codemirror.net/mode/gfm/ vs https://codemirror.net/mode/markdown/ demos is that the markdown demo highlights the trailing spaces, while gfm doesn't.
But both actually apply `cm-trailing-space-a` and `cm-trailing-space-new-line` classes, it's just that only demo/markdown/index.html has CSS to make it visible.

**Comment by BrianOtto** [comment]
Oh I see, my mistake. I am using UI Kit and they have a component that implements your editor. I thought the live preview was a part of your codebase, but I guess it's something on their end.

http://getuikit.com/docs/htmleditor.html

I will look into the issue there. Thanks, and sorry for the mistaken bug report.
