### ISSUE TITLE
singleCursorHeightPerLine and Selection Range Height

### ISSUE THREAD

**Issue by antimatter15** [codemirror/CodeMirror#3792]
In CodeMirror 5.11, increasing the line height with CSS and setting `singleCursorHeightPerLine: false` appropriately shrinks the height of the cursor, but selection ranges are still really tall:

![screenshot 2016-01-28 05 47 40](https://cloud.githubusercontent.com/assets/30054/12642291/b6500592-c582-11e5-966b-22009a706b03.png)

This behavior can be fixed by changing the definition of measureChar to include the varHeight argument in its call to measureCharPrepared.

```
function measureChar(cm, line, ch, bias) {
    return measureCharPrepared(cm, prepareMeasureForLine(cm, line), ch, bias, !cm.options.singleCursorHeightPerLine);
  }
```

This sizes the selection bands "correctly", more closely hugging the boundary of the actual text.

![screenshot 2016-01-28 05 46 58](https://cloud.githubusercontent.com/assets/30054/12642374/327a5730-c583-11e5-91c7-5ca34e866407.png)

**Comment by marijnh** [comment]
So yes, the reason why selection spans the line's whole vertical range is exactly to prevent gaps in block selections. I find your second screenshot to look strictly worse than the first, which is also the reason CodeMirror uses the strategy it currently uses. I know aesthetics are subjective, but you can probably imaging why I'm not putting energy into implementing something that I feel looks awful.

**Comment by antimatter15** [comment]
I agree that among the screenshots the former is aesthetically nicer, but I think that's just an argument for keeping the default setting `singleCursorHeightPerLine: true`. 

Currently, when `singleCursorHeightPerLine: false` is set, the selection bands are taller than the height of the cursor. It feels a bit like walking on a beach, looking behind and seeing meter-wide elephant tracks where your own footsteps ought to have been. 

![](http://g.recordit.co/UohFSnE1Of.gif)

The proposed behavior seems consistent with what typical user agents do when rendering text with higher line heights (actually, Chrome hugs the text even more tightly, leaving that oddly asymmetric vertical gap on the lower right of the selection band). 

<img width="611" alt="screenshot 2016-02-03 01 38 52" src="https://cloud.githubusercontent.com/assets/30054/12774866/ea2b2034-ca16-11e5-9857-1330aca19d75.png">

My particular use-case involves sticking interlinear widgets in between lines to preview values of expressions or to hint names of method arguments. 

<img width="334" alt="screenshot 2016-02-03 01 44 46" src="https://cloud.githubusercontent.com/assets/30054/12774932/c0a335d4-ca17-11e5-8d2e-7ec0c365d0e9.png">

The current selection band placement seems to clash rather tragically:

<img width="152" alt="screenshot 2016-02-03 01 47 00" src="https://cloud.githubusercontent.com/assets/30054/12774966/293ae772-ca18-11e5-86a0-0df298b169b6.png">

**Comment by marijnh** [comment]
Are you using line-wrapping? If not, you might be able to just use a line widget to create the space below the line, which wouldn't cause this issue.

I guess I could add an option `singleSelectionHeightPerLine`, but pretty sure that if I just apply the simple patch you propose, these selections will look entirely wrong when you mix font sizes or have bidirectional text, since they assume that the height at the measured point will be valid for the whole line. Stuff will stick out of the selection, for example, and the selection size will depend on the size of the characters at its endpoints.

**Comment by antimatter15** [comment]
I was inserting line widgets between every line in an earlier prototype, but decided to switch to the extended line height exactly because I was using line-wrapping. 

I would really appreciate it if you added a `singleSelectionHeightPerLine` option. Thank you for such a fantastic library!

**Comment by marijnh** [comment]
On closer look no, I think you'll just have to continue patching your version of CodeMirror. I'm not volunteering for implement this in a way that solves the problems I outlined, and I also don't want to add unsupported single-use options for specific cases like this.
