### ISSUE TITLE
In Python, multiple closing braces on a new line does not dedent multiple times.

### ISSUE THREAD

**Issue by ienzam** [codemirror/CodeMirror#3794]
Python indentation of closing braces does not trigger dedentation correctly.
Best explained with following example:
 
**Steps to reproduce:**
1. Go to any Codemirror python text area (http://codemirror.net/mode/python/index.html).
2. Write the following code.
```
# | shows the position of cursor
a = [{( | )}]
```
3. Press enter.

**What is observed:**
Code changes to:
```
# | shows the position of cursor
a = [{( 
        |)}]
```

**What is expected:**
Code may change to:
```
# | shows the position of cursor
a = [{( 
|)}]
```

**Comment by marijnh** [comment]
Please take a look at attached patch, and see whether it solves your problems.

**Comment by ienzam** [comment]
Thanks for a quick fix.

I tested the code. It improved the situation did not fix the problem completely.

Example:
1. Go to https://rawgit.com/codemirror/CodeMirror/master/mode/python/index.html
2. Write code:
```
a = [[
    [|]
]]
```
3a. Pressing enter turns the code to 
```
a = [[
    [
]
]]
```
3b. Expected
```
a = [[
    [
    ]
]]
```

PS: https://rawgit.com/ienzam/CodeMirror/issues/py_indentation/mode/python/index.html shows correct behaviour (at least for this case).

**Comment by marijnh** [comment]
Good catch. Attached patch fixes this case.

**Comment by ienzam** [comment]
Great, thanks for fixing these two issues quickly.
