### ISSUE TITLE
In Python, add support to indent only once after multiple opening braces on previous line.

### ISSUE THREAD

**Issue by ienzam** [codemirror/CodeMirror#3795]
In Python, after a line with multiple (`n`) open braces, next line starts with `n * hangingSpace`.
But in most languages, indentation is only one unit of `hangingSpace`.

Here is coding example to make it clear what I mean.

**Steps to reproduce:**
1. Go to any CodeMirror python and clike text area (http://codemirror.net/mode/python/index.html).
2. Write the following code on both. (`|` shows the position of cursor)
```
a = [(|
```
3. Press enter.

**What is observed:**
Python cursor is like following:
```
a = [(
        |
```
Clike cursor is like following:
```
a = [(
  |
```

**What is expected:**
Both will have same clike cursor:
```
a = [(
  |
```

**Comment by marijnh** [comment]
Again, I think this is addressed by 3df470adc8e7be
