### ISSUE TITLE
TypeScript generics and template strings.

### ISSUE THREAD

**Issue by MizardX** [codemirror/CodeMirror#3796]
In TypeScript, when specifying a generic type as return type of a function, the template-strings inside looks strange.

    function UpdatePriority(): JQueryPromise<boolean> {
        console.log(`${dto.Name} Priority -> ${priority} (id = ${dto.id})`);
        priority++;
    }

This is rendered as:

![](http://i.imgur.com/Evb5gBT.png)

If I remove the generic parameter `<boolean>`, this renders ok.
It is the same behavior in both [JavaScript mode][1] and [TypeScript mode][2].

[1]: https://codemirror.net/mode/javascript/
[2]: https://codemirror.net/mode/javascript/typescript.html

**Comment by marijnh** [comment]
Yes, TypeScript support is a kludge (was contributed) that doesn't really play well with the JS mode's context-sensitive parsing. This is mostly visible in template strings, but will cause a bunch of other issues. I'm not supporting this code, but if you want to submit a patch, I'll gladly look at it.
