### ISSUE TITLE
Soy keywords not highlighted consistently

### ISSUE THREAD

**Issue by dbarnett** [codemirror/CodeMirror#3799]
The soy mode seems to always highlight the first word after an open `{` as a keyword regardless of whether it's actually a valid keyword, and leaves a lot of actual keywords unhighlighted.

Examples I noticed:
- `as` in `{alias x as y}`
- `and`, `or`, `not` in `{if $a and not $b or $c}`
- `in` in `{foreach $a in $b}`

**Comment by dbarnett** [comment]
Is it going to be possible to improve this highlighting without completely rewriting the parser, or is it at a local maximum right now?

**Comment by marijnh** [comment]
The Soy mode was contributed, I haven't really looked closely at it nor have I ever used Soy. You can try to convince the original contributor (@vrana) to address this, or submit a patch yourself.

**Comment by vrana** [comment]
I think that it should be possible. I don't plan on doing it though.

**Comment by Victorystick** [comment]
@dbarnett Highlighting was extended to support this in 2bed274. Can this issue be closed?

![example-soy](https://cloud.githubusercontent.com/assets/703602/21522364/38294260-cd05-11e6-81eb-41f2db72309c.png)

Just noticed another _worrying_ issue; filed #4468. :wink:
