### ISSUE TITLE
Markdown and GFM mode comment highlight might escaped

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#3800]
This issue happens when you insert \ in the single comment syntax.
Then anything following will be highlighted as comments.

<img width="608" alt="2016-01-30 9 16 49" src="https://cloud.githubusercontent.com/assets/2639151/12699996/dc4d4b04-c796-11e5-9153-e06e50879f52.png">

You can also reproduce this issue in both markdown and GFM mode.
https://codemirror.net/mode/markdown/
http://codemirror.net/mode/gfm/

**Comment by Rplus** [comment]
:+1:

**Comment by jackycute** [comment]
Thank you very much!
