### ISSUE TITLE
Sublime keymap "delete line" wrong combination for OSx

### ISSUE THREAD

**Issue by jakealbaugh** [codemirror/CodeMirror#3803]
The combination for `deleteLine` is bound to `"Shift-" + ctrl + "K"`, but according to the Sublime default keymap it should be the same for either OS and bound to `"Shift-Ctrl+K"`. I didn't want to do a PR in case this was intentional, so I figured I'd start the conversation here.

Sublime Source: `Default (OSX).sublime-keymap:590`

[/keymap/sublime.js:108](https://github.com/codemirror/CodeMirror/blob/master/keymap/sublime.js#L108)

Existing code:
```js
map["Shift-" + ctrl + "K"] = "deleteLine";
```

Fix:
```js
map["Shift-Ctrl-K"] = "deleteLine";
```

I'm happy to do the PR if this was simply an oversight.

**Comment by vincentwoo** [comment]
my guess as well is that this is an oversight
