### ISSUE TITLE
html-mixed mode: <style> tag with props split across lines breaks the css highlighting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3804]
Repro:
1. go to codemirror.net
2. in the example editor input
```html
<style x="y"
       y="z">
  .foo {
    font: "bar";
  }
</style>
```

Expected:
css highlighting should apply inside the `<style>` tag

Actual:
no highlighting in the `<style>` tag

If you move all the properties of the style element into one line it works fine

**Comment by marijnh** [comment]
Attached patch should help here.
