### ISSUE TITLE
Vim-mode: ⌃Q as alternative to ⌃V

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [codemirror/CodeMirror#3806]
So, on a lot of platforms, ⌃V is unavailable (for obvious reasons ;); and that means a lot of us vimmers have the ⌃Q-alternative burned into muscle-memory.

>     						*CTRL-V-alternative* *CTRL-Q*
>     Since CTRL-V is used to paste, you can't use it to start a blockwise Visual
>     selection.  You can use CTRL-Q instead.  You can also use CTRL-Q in Insert
>     mode and Command-line mode to get the old meaning of CTRL-V.  But CTRL-Q
>     doesn't work for terminals when it's used for control flow.

Any chance of getting ⌃Q as included as a default binding?

**Comment by marijnh** [comment]
I've gone ahead and simply added the alias, despite not really understanding the implications. If anyone wants to suggest a different approach, do comment. (@heppe)
