### ISSUE TITLE
SPARQL indentation error following GRAPH keyword

### ISSUE THREAD

**Issue by keski** [codemirror/CodeMirror#3808]
The automatic indentation for the SPARQL mode results in an indentation error following the ```GRAPH``` keyword if the closing bracket is not followed by a period. See the example below:
```
SELECT *
WHERE {
  GRAPH ?graph {
	?a ?b ?c .
  }
		?a ?b ?c .
}
```
The next time a period is used the indentation snaps back to normal.

**Comment by keski** [comment]
I created a quick fix where I execute ```popContext(state)``` again when a closing ```}``` bracket is found:
```
...
else if (/[\]\}\)]/.test(curPunc)) {
   while (state.context && state.context.type == "pattern") popContext(state);
      if (state.context && curPunc == state.context.type) popContext(state);
      if (curPunc == "}" && state.context) popContext(state);
   }
...
```
However, I'm not sure if this is the proper way to do it so I'll leave it to more experienced eyes to verify.

**Comment by marijnh** [comment]
I think attached patch should cover it. Let me know if you still see bad indentation.
