### ISSUE TITLE
Question: highlighting the active difference in Merge View

### ISSUE THREAD

**Issue by wissamsaikali** [codemirror/CodeMirror#3809]
Hi, is there any way to change the style (e.g. highlight color) of the active difference when we jump from one difference to another in the merge view? When the user jumps to the Next or Previous difference in the editor, it would be more practical to differentiate it from the other ones so that he can easily tell which one he has landed on.

**Comment by marijnh** [comment]
Nope, there isn't. In fact, there isn't really a concept of an active difference, it just looks at the cursor when moving to the next one.

**Comment by tomerep** [comment]
I would also expect highlight of the active difference functionality.
