### ISSUE TITLE
Strange IE/Edge problem with keyboard input

### ISSUE THREAD

**Issue by andersevenrud** [codemirror/CodeMirror#3810]
Hi,

I'm having some very strange behaviour in IE/Edge when putting the editor inside a movable/resizable container (I'm using a javascript window manager of sorts).

The editor loads just fine and has the correct look, but when I focus it the keyboard input does not register properly -- all the keys are printed to my document body, not inside the editor.

If I *right click* (contextmenu) on the editor the problem goes away and I can type normally.

This is just a standard setup (from docs), the only difference is that I make use of focus/blur methods (whenever appropriate), ex:

```
        this.editor.getInputField().blur();

```

Works perfectly in Chrome and Firefox.

Does anyone have an idea as of what is going on or seen anything like this ?

*Attaching a video so you get a better idea.* https://www.youtube.com/watch?v=BBVzut3bO5A&feature=youtu.be

**Comment by Tedko** [comment]
how about simulate an right click event? (a dirty fix but might work)

**Comment by andersevenrud** [comment]
@Tedko I tried to emit a contextmenu event on the "input field", but that did not work :( I'm going to try hacking around some more

**Comment by andersevenrud** [comment]
Looks like I'm affected by #2127 in this case

**Comment by marijnh** [comment]
Is the body editable? If not, the only explanation for this that I can think of is a CSS problem causing the content of the editor to show up in the body. What does `getValue()` return after you type some stuff like this?

**Comment by andersevenrud** [comment]
@marijnh 

`document.body.contentEditable` returns `inherit`.

The text is inserted into the body element itself.

>  If not, the only explanation for this that I can think of is a CSS problem causing the content of the editor to show up in the body

It's definately not a positioning problem. The weird thing is that a right-click fixes the problem (but not when simulated).

**Comment by marijnh** [comment]
Strange. But I'd say that this is a form of focus confusion that's an Edge bug, not something CodeMirror can help. (If you have evidence to the contrary, feel free to add further information.)

**Comment by andersevenrud** [comment]
Leaving this here for others to see:

A very kind stranger contacted me with this exact same problem and it seems that the `-webkit-user-select` CSS property is the cause of this.
