### ISSUE TITLE
.bower.json file created which is generating an error on bower update

### ISSUE THREAD

**Issue by shoebsd** [codemirror/CodeMirror#3822]
D:\myapp >bower update {bower package}
**bower EMALFORMED **   Failed to read D:myapp\bower_components\CodeMirror\**.bower.json**

Additional error details:
**Unexpected token .**

I don't know why .bower.json file is created although there is a valid bower.json file. the dot infront of bower.json file is throwin an error which says unexpected token. 

I have checked the json format in bower.json as well as package.json. Is there anyone who's getting this same issue?

**Comment by marijnh** [comment]
The `.bower.json` file isn't in the repository, and is not something CodeMirror is creating.
