### ISSUE TITLE
Wrong context menu with CSS transform in Chome/Safari/Firefox

### ISSUE THREAD

**Issue by st44100** [codemirror/CodeMirror#3827]
Chome/Safari/Firefox browsers show wrong context( ) when parent element has css transformation.

` transform: translate(100px, 100px)` =>  :x: 
` transform: translate(0px, 0px)` =>  :x: 
` transform: rotate(10deg)` =>  :x: 
` transform: rotate(0deg)` =>  :x: 

**Example:** http://codepen.io/st44100/pen/jWJvry

### Without `transform` in Window Chrome

![2016-02-16 at 5 02](https://cloud.githubusercontent.com/assets/293909/13070348/2a1883fe-d4cf-11e5-9ead-87c3384447ab.png)

### With `fransform` in Windows Chrome

![2016-02-16 at 5 03](https://cloud.githubusercontent.com/assets/293909/13070369/525ed660-d4cf-11e5-856f-de2339911a08.png)

**Comment by marijnh** [comment]
Transforming a CodeMirror editor is not supported in general. See also #2443

The issue with zero transforms breaking the context menu was fixed earlier this month (see #3238)
