### ISSUE TITLE
Way to get the line number in custom overlays

### ISSUE THREAD

**Issue by yannickglt** [codemirror/CodeMirror#3830]
Is there a way to get the line number in an overlay token method?
I did something similar [here](https://github.com/yannickglt/CodeMirror/commit/3117ef0060402b34bbcccfb4cbedcbd4033e0d8d) but the way I did it looks not scalable. That's why I did not make a PR.
I need this feature to highlights parts of code not depending on string matching but on line and column indexes.
Thanks

**Comment by marijnh** [comment]
You should probably use `markText` for this use case. The way overlays (and modes in general) work relies on them being stateless, and oblivious to line numbers.

**Comment by yannickglt** [comment]
Thank you! I'll try :wink:
