### ISSUE TITLE
Markdown list highlighting only works on the top item in the second level list

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#3833]
Try to put below codes on Markdown mode or GFM mode:

```
- root1
- root2
    - sec1
    - sec2
        - third1
        - third2
```

<img width="608" alt="2016-02-19 9 47 41" src="https://cloud.githubusercontent.com/assets/2639151/13164135/e11b67ae-d6ed-11e5-8614-23890da3171a.png">

The second level list only highlighting the top item (sec1) but not the others (sec2).
Is this a feature or bug maybe?
Thanks for helping!

**Comment by marijnh** [comment]
@bfrohs I looked into this a little, and am getting very wrong values for the indentation and indentation difference in this example. The indentation-computing code appears confused -- the list handling code adjusts its to include the marker, but then the code that computes the difference assumes that it need only count to the first non-whitespace character. Git blame pins it on you, so would you maybe take a look?

**Comment by bfrohs** [comment]
> Git blame pins it on you, so would you maybe take a look?

Oh fun. Yeah, I'll take a look at this tonight!

**Comment by bfrohs** [comment]
It looks like this was broken in 662d71f91e2246cb190ed7dcd2d7bfad2cda076b, in order to fix #2962. However, since there weren't any tests for this particular case, it went without being noticed.

I'm going to have to refamiliarize myself with the CommonMark spec in order to properly fix this. I can't dive into it tonight, but I'll try to get to it this week.

**Comment by marijnh** [comment]
Thanks! (And sorry for breaking it.)

**Comment by bfrohs** [comment]
Alright, I think I've got a pretty good grasp of the CommonMark list indentation rules. I'm going to take the night to think about the right way to implement the change and try to get a PR in the next day or two.

**Comment by marijnh** [comment]
Patch afed95a should help (& adds a test checking the snippet you showed).

**Comment by jackycute** [comment]
Thanks a lot! OMG, You guys are so awesome :+1:
