### ISSUE TITLE
Markdown scroll when it's one line

### ISSUE THREAD

**Issue by yutuo** [codemirror/CodeMirror#3834]
I tested it at chrome 48.0.2564.109.

1. Open the site <https://codemirror.net/>
2. Delete CodeMirror's text, leave one line(eg.`<!-- Create a simple CodeMirror instance -->`).
3. Move mouse to CodeMirror. CodeMirror can scrol.

I'am sorry, My English is poor.

**Comment by marijnh** [comment]
The demo at http://codemirror.net does not show a scrollbar when there's only a single line in it, neither could I scroll it with the scroll wheel. What kind of scrolling do you mean?

**Comment by yutuo** [comment]
It's not scrollbar.

When CodeMirror has only a single line, The text in CodeMirror will up and down when the mouse are scrolling
![20160219232006](https://cloud.githubusercontent.com/assets/2993927/13177909/5b6df9c4-d75f-11e5-9c85-a37cbce17ff0.png)
.

I'am sorry, My English is poor.

**Comment by marijnh** [comment]
Ah, now I can see it. Attached patch fixes it for me (on Chrome)
