### ISSUE TITLE
line wrapping and horizontal scrollbar does not work if text area is inside of a fieldset 

### ISSUE THREAD

**Issue by GrumpyPants** [codemirror/CodeMirror#3836]
Here is an example to illustrate the problem. Keep typing in the fiddle below and you will notice that the container just keeps on growing and never wraps or adds a scrollbar. If you remove the fieldset then it works as expected.

http://jsfiddle.net/3pVxP/17/

Testing this in chrome.

**Comment by marijnh** [comment]
This is more an issue with `<fieldset>` than with CodeMirror. See this very good [stackoverflow answer](http://stackoverflow.com/a/17863685/486527) for details (and a hack to work around it).
