### ISSUE TITLE
Mode Grammar : Option to make it precise only

### ISSUE THREAD

**Issue by basarat** [codemirror/CodeMirror#3839]
Code mirror has an optimization where it will go up a few lines to find the one with the minimum indent and call `startState` from that point on. While in the background it will at some point resume the tokenizer that started with actual line 0. I have a TypeScript grammar that needs accurate line numbers. Without that it gives wrong results. So because of this optimization first we get a *bad* tokenization and then we get a *good* tokenization after a delay. This is shown below where because we have the initial lines as comments the initial tokenization is *comment* but then it updates to the correct result: 

![grammar](https://cloud.githubusercontent.com/assets/874898/13200099/65cc8950-d88e-11e5-8e11-97a534c3afac.gif)

This is much worse if the first few lines in the file are funky ... we get funky tokenization for the ending lines (which ofcourse auto fix after a while): 

![grammar2](https://cloud.githubusercontent.com/assets/874898/13200112/e50fe1ee-d88e-11e5-9d50-c655ced0d872.gif)

Ideally I would prefer that it was *white* to begin with instead of funky.

# More info
The call stack actually goes to `getLineStyles` -> `getStateBefore` but `precise` is not passed in (`undefined` / falsy).
![image](https://cloud.githubusercontent.com/assets/874898/13200192/e9b1a130-d891-11e5-81d6-5b0185329f9e.png)

![image](https://cloud.githubusercontent.com/assets/874898/13200173/3ce0e29a-d891-11e5-8985-7b5d5d7c93a5.png)

If we pass in `precise` true ... it becomes slow (as it gets state for all the lines). Is there a solution to have it temporarily be white?

# If Curious : Why I need exact line numbers

Because the lexical grammar was deemed too complex for JSX https://github.com/Microsoft/TypeScript/issues/5545. TypeScript also provides what they call *syntactic* tokenizer which basically works on a *complete source file*. I feed the source file to it (https://github.com/alm-tools/alm/blob/e588cccd8178f3130180586f468f5ec03a6b6ea7/src/app/codemirror/mode/classifierCache.ts#L23-L33) and then query it from the mode (https://github.com/alm-tools/alm/blob/05204a372e667e4057a457c44441413109b42ff5/src/app/codemirror/mode/typescript.ts#L143) giving it the right line numbers.

PS: Love CodeMirror :rose:

**Comment by marijnh** [comment]
What if you add some sanity-checking to your mode so that it doesn't output any styling when the tokens in the stream don't match the tokens in its token list?

Immediately doing a synchronous parse of the whole document isn't a good approach, since it could block the UI for an arbitrary amount of time at critical moments when the user is expecting feedback, making the editor feel unresponsive.

Making it so that the editor doesn't highlight at all if it couldn't get a precise state would be possible, but that'd be somewhat invasive, since it'd require a bunch of code to know about this special state that highlighting can happen in.

**Comment by basarat** [comment]
Thanks for your review :rose:

> What if you add some sanity-checking to your mode so that it doesn't output any styling when the tokens in the stream don't match the tokens in its token list?

I explored this option but consider the following file: 

```
1: aaa
// ... some 300 lines 
301: aaa
```

Now if the editor jumps to `301` (or something similar) I still might think that its valid `aaa` if line `1` is being passed in. Basically file contents can repeat on different lines and I can't sanely check that from the grammar 


> Making it so that the editor doesn't highlight at all if it couldn't get a precise state would be possible, but that'd be somewhat invasive, since it'd require a bunch of code to know about this special state that highlighting can happen in

I understand. Feel free to close. I just wanted this to be known issue and see if there was perhaps a quick win :rose:

**Comment by marijnh** [comment]
> Basically file contents can repeat on different lines and I can't sanely check that from the grammar

That's true, but large stretches of repeated text are rare, and highlighting a few lines wrong (potentially -- it might even be right) and then disabling highlighting as soon as a mismatch is found is still much preferable to the color soup in your screenshot, no?

Going to close this. I see the use case, and I'm going to rethink the way this works the next time I do major work on the highlighting system, but right now this isn't something I want to implement.

**Comment by basarat** [comment]
@marijnh its okay if you never implement this. I did the sanity checks on my side (https://github.com/alm-tools/alm/blob/c5834a2080a942340b3e51161a947cd3f019e139/src/app/codemirror/mode/classifierCache.ts#L38-L51) and it seems to work fine in real world testing :rose:
