### ISSUE TITLE
findMarks is broken for multi-line marks

### ISSUE THREAD

**Issue by idubrov** [codemirror/CodeMirror#3840]
The following test fails:

```javascript
  testDoc("findMarksMiddle", "A='line 0\nline 1\nline 2\nline 3'", function(a) {
    var mark = a.markText(Pos(1, 1), Pos(3, 1));
    var found = a.findMarks(Pos(2, 1), Pos(2, 2));
    eq(found.length, 1);
    eq(found[0], mark);
  });
```

It creates mark spanning over "line 1", "line 2" and "line 3" and searches for marks in the "line 2". Current implementation returns empty array.

**Comment by marijnh** [comment]
Ugh, accidental type conversion strikes again (null → 0). Attached patch fixes this and adds you test.
