### ISSUE TITLE
Support search+replace with query of /^/ or /$/

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3841]
Searching for /^/ and replacing with 'foo' should add 'foo' as a prefix to every line (and similarly for /$/ & suffix). This matches the behavior of e.g. JS `"foo bar baz".replace(/^/, 'quux')` and the behavior of other editors like Sublime Text.

https://github.com/codemirror/CodeMirror/issues/2259 was also about these types of queries, though at that point I had not heard of a sensible use for them.

**Comment by marijnh** [comment]
The `^` and `$` regexp syntax isn't support in CodeMirror's search/replace addon (due to JavaScript's crude regexp API), so this use case is simply not covered by the addon.
