### ISSUE TITLE
Collapsed atomic region with bidi character causes TypeError

### ISSUE THREAD

**Issue by Dominator008** [codemirror/CodeMirror#3846]
Sorry that I don't have a clean repro script. To reproduce on Chrome on Linux:
1. Go to https://codemirror.net/demo/markselection.html
2. Clear the editor.
3. Press and hold Ctrl+V to paste a few `ك` characters on the first line.
4. Press Enter
5. Press and hold Ctrl+V once again to paste a few `ك` characters on the second line.
6. Press F12 to open the Developer Console.
7. Type

```js
editor.markText(CodeMirror.Pos(0, 0), CodeMirror.Pos(1), {
  "collapsed": true,
  "inclusiveLeft": true,
  "inclusiveRight": true
});
```
Then
8. Refocus on the editor.
9. Move cursor up and down.

Sometimes it gives:
```
Uncaught TypeError: Cannot read property 'level' of undefined
  getBidi @ codemirror.js:2840
  cursorCoords @ codemirror.js:2856
  (anonymous function) @ codemirror.js:5210
  map @ codemirror.js:8318
  (anonymous function) @ codemirror.js:7471
  (anonymous function) @ codemirror.js:3203
  (anonymous function) @ codemirror.js:5207
  (anonymous function) @ codemirror.js:3194
  goLineDown @ codemirror.js:5693
  doHandleBinding @ codemirror.js:4090
  (anonymous function) @ codemirror.js:4154
  CodeMirror.lookupKey @ codemirror.js:5867
  CodeMirror.lookupKey @ codemirror.js:5871
  lookupKeyForEditor @ codemirror.js:4104
  dispatchKey @ codemirror.js:4120handleKeyBinding @ codemirror.js:4154
  onKeyDown @ codemirror.js:4173(anonymous function) @ codemirror.js:3186
```
git bisect indicates that https://github.com/codemirror/CodeMirror/commit/0df380b6384f6138764a2f1c78d960edddf6fbce caused the problem.

**Comment by davido** [comment]
Can we consider to revert 0df380b and release new version of CodeMirror? CodeMirror upgrade was reverted in Gerrit Code Review because of this problem, and new and shiny jump-to-dialog feature as well: [1], [2].

* [1] https://gerrit-review.googlesource.com/75143
* [2] https://gerrit-review.googlesource.com/75142

**Comment by Dominator008** [comment]
@davido I trust in @marijnh :)

**Comment by marijnh** [comment]
@Dominator008 Thanks for the vot of confidence ;) Attached patch should help.

**Comment by Dominator008** [comment]
Thanks @marijnh !

**Comment by Dominator008** [comment]
@marijnh It turned out that your patch didn't fix the TypeError in our project. I've filed another pull request that fixed the problem for us. #3855.
