### ISSUE TITLE
Add Syntax Highlighting for HubL

### ISSUE THREAD

**Issue by TheWebTech** [codemirror/CodeMirror#3850]
Hi all,

I realize it's not one of the higher priority languages out there, but I edit a lot of **HubL** files, and so do my co-workers, it'd be nice if CodeMirror had **syntax highlighting for HubL code.**

Background knowledge for those interested: **HubL is a server side language similar to PHP, it's based on Jinja, and was developed by a company called HubSpot**, and is HubSpot's only server side language that they allow developers to use.

http://designers.hubspot.com/docs/hubl/intro-to-hubl

I realize it's not high on everyone's priorities, I just wanted to get this in there.
Also sorry if this isn't where you want syntax highlighting requests, I read the readme and it didn't seem to specifically say where those should go. Good work guys! love the editor.

**Comment by marijnh** [comment]
Hi. We don't take mode feature requests. See [the wiki](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list)
