### ISSUE TITLE
Synth .running? doesn't work when playing multiple notes.

### ISSUE THREAD

**Issue by mron** [codemirror/CodeMirror#3854]
Testing to see if a synth is running using .running? works fine for single notes. It never registers "true" when playing multiple notes. play_chord also fails to register it's running.

os x, sonic pi v2.9

**Comment by marijnh** [comment]
I can't interpret any of this, but it sounds a lot like you're working with music software. CodeMirror isn't, so this appears to be filed in the wrong repository.

**Comment by mron** [comment]
I’m sorry, I must have missed a link.
