### ISSUE TITLE
matchBrackets swallows click events attached to adjacent Bookmarks

### ISSUE THREAD

**Issue by louh** [codemirror/CodeMirror#3863]
In our implementation of CodeMirror, we have a situation where some values have special meaning, so we set a bookmark widget element next to these values. These widgets have a `click` event listener attached, and `handleMouseEvents` is set to `true`, to prevent drag-movements that begin on the widget element from mistakenly highlighting DOM elements. When clicked, these will open a modal UI (not pictured).

![screenshot 2016-03-02 15 10 33](https://cloud.githubusercontent.com/assets/2553268/13473794/f3c96c1c-e088-11e5-9253-99f362b53a01.png)

It seems that whenever the value is enclosed in brackets, then clicking on the widget element once will highlight the brackets, but no modal UI will appear. Then, clicking on the widget element a second time, the modal UI will appear properly.  (issue: https://github.com/tangrams/tangram-play/issues/266)

This does not happen (that is, the modal UI appears after one click on the widget) when the preceding values are not in brackets.

We believe it's related to the `matchBrackets` feature and how mouse events are handled. If we initialize the editor without `matchBrackets: true`, then clicking the bookmark widgets behave as expected (but brackets are no longer highlighted). If we set `handleMouseEvents` on the widgets to `false`, then we can also get the modal UI to appear after one click (but we get the DOM highlighting problem).

Is there a way around this? Is this a bug to fix?

Thanks!

**Comment by marijnh** [comment]
Sounds like you actually want `handleMouseEvents: false` (with your own code to `preventDefault` drag events).
