### ISSUE TITLE
addTextMarker() interferes with click handlers on Chrome

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3866]
This repro is a simplified version of some code we used to highlight what things you can usefully click on when you hold ctrl/cmd and hover over that link.

### Repro:
1. Open codemirror.net
2. Enter the following in the dev console:
```js
var cmEl = document.querySelector('.CodeMirror');

var onMouseOver = function(e) {
  // Marker deletion omitted ...
  if (e.ctrlKey || e.metaKey) {
    var cur = editor.coordsChar({left: e.clientX, top: e.clientY});
    var token = editor.getTokenAt(cur);
    if (token.type == 'word' || token.type == 'property' ||
        token.type == 'variable') {
      var marker = editor.markText(
      	  {line: cur.line, ch: token.start},
          {line: cur.line, ch: token.end},
          {className: 'word_underline'});
    }
  }
};

var onMouseDown = function(e) {
	console.log('Mouse down %o', e);
};

cmEl.addEventListener('mousedown', onMouseDown);
cmEl.addEventListener('mouseover', onMouseOver);
```
2. Move your cursor over some white space in the editor
3. Press down ctrl or cmd
4. Move your cursor over a black token in the JS part of the editor
5. Click (while holding ctrl/cmd down)

### Expected:
The mousedown handler fires

### Actual (Chrome):
The mousedown handler doesn't fire.

This repros in Chrome on Mac and Linux, but works as expected in FF.

If you're able to repro this issue with a smaller test case this might be something to submit as a bug report to FF or Chrome.

**Comment by marijnh** [comment]
Seems to be a Chrome bug. Here's a tiny (CM-free) reproducing snippet:

```html
<!doctype html>

<div><span>foo</span></div>

<script>
var div = document.querySelector("div")

div.addEventListener("mouseover", function(e) {
  if (e.ctrlKey || e.metaKey) div.innerHTML = "<span>foo</span>"
})
div.addEventListener("mousedown", function() {
  console.log("mouse down")
})
</script>
```
