### ISSUE TITLE
How to clear all marks created with markText()?

### ISSUE THREAD

**Issue by s-a** [codemirror/CodeMirror#3872]

**Comment by sbruchmann** [comment]
You’ll have to keep track of your marks on your own and clear them yourself when they aren’t needed anymore.

```javascript
const markers = [];
markers.push(cm.markText(…));
markers.forEach(marker => marker.clear());
```

See [documentation for `doc.markText()`](http://codemirror.net/doc/manual.html#markText).

---

GitHub Issues is a **bug tracker**. There’s a dedicated forum for questions and user support at [discuss.codemirror.net](https://discuss.codemirror.net).

**Comment by wolfiex** [comment]
A better way to do this would be 
```js
editor.doc.getAllMarks().forEach(marker => marker.clear());
```
