### ISSUE TITLE
Horizontal scrollbar displayed on enabling of the Line Warp option

### ISSUE THREAD

**Issue by SabareeshDivakaran** [codemirror/CodeMirror#3875]
I have a dynamic option to enable and disable Line Wrap.

1. Disable Line Wrap.
2. Add data say 40k characters.
3. Keep Focus on the editor.
4. Enable Line Wrap.

     Now, you could see the animation of horizontal scroll bar and finally the horizontal scrollbar displayed but not usable. Normally, the animation should not be shown and horizontal scroll bar should be hidden.
     It works fine when the cursor focus is not there in the editable area.

      Is there anything wrong in the below code?

```
<html>
<head>
<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
<script src="jquery-1.9.1.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css"
href="codemirror.css" />
<script type="text/javascript"
	src="codemirror.js"> </script>
<script type="text/javascript">
		function wrapLine(doWrapLine) {
		
		window.editor.setOption('lineWrapping',doWrapLine);
		window.editor.refresh();		
		}
	</script>
</head>
<body>
<span class="pull-right"><input type="checkbox"
					style="margin: 0px;" checked
					onChange="wrapLine(this.checked)">&nbsp;Line
					Wrap</span>
			<div>
				<textarea id='sqlArea' rows="10" cols="139"></textarea>
			</div>
			<script type="text/javascript">
				window.editor = CodeMirror.fromTextArea(document
						.getElementById('sqlArea'), {
					mode : 'text/x-mysql',
					indentWithTabs : true,
					smartIndent : true,
					lineNumbers : true,
					autofocus : true,
					lineWrapping : false	
				});
			</script>

</body>
</html>
```

**Comment by marijnh** [comment]
I've never seen CodeMirror _animate_ a scrollbar. When I follow your instructions (I initialized the editor's content to a long line, and then flipped the checkbox a few times), everything seems to work -- the scrollbar appears when it should, and is usable. Any further information?

**Comment by MatteoCigognini** [comment]
I've a question, I need to wrap text on fixed width.
But the problem is horizontal scroll, I would remove it and automatically wrap text on max width. 

How is it possible ?
