### ISSUE TITLE
Dart mode should handle nested comments

### ISSUE THREAD

**Issue by joseluis** [codemirror/CodeMirror#3878]
Dart has nested comments, but the highlighter doesn't treat them like nestable. [Test in Dartpad](https://dartpad.dartlang.org/643e218beb6a896ad565).

```dart
/*
/*
 Comment
 
 /* nested comment */
​
*/ // <-- not highlighted
​
main() {}
```

Related: https://github.com/codemirror/CodeMirror/pull/2947#issuecomment-64822887
Related: https://github.com/dart-lang/sdk/issues/25931

**Comment by marijnh** [comment]
@devoncarew Do you want to take a look at this?
