### ISSUE TITLE
[Rust Mode] - defineSimpleMode in Compression Helper?

### ISSUE THREAD

**Issue by mattpass** [codemirror/CodeMirror#3883]
After the compression helper to compress quite a few languages and addons into one, the compressed file it produces used has the error 'a.defineSimpleMode is not a function' on load. Looking at the compressed JS it only occurs once and seems to be related to Rust mode. If I deselect this language in the compression helper and compress a file without it, the output JS file works fine.

So I tried rewording defineSimpleMode as defineMode and the JS file loads without error, However, when then trying to open a Rust file then reports the error 'Uncaught TypeError: c is not a function'.

**Comment by marijnh** [comment]
> So I tried rewording defineSimpleMode as defineMode

Yeah, that's not going to help. You have to include `simple.js` in your bundle to use modes defined on top of that addon.

(In general, I'd recommend moving to a real bundler, since the compression helper doesn't understand dependencies, and we're getting increasingly complicated dependencies.)

**Comment by mattpass** [comment]
I've tried including simple.js (both in the bundle and as a separate JS file) and it still complains of the same issue: ```Uncaught TypeError: a.defineSimpleMode is not a function```.

I can see the simple.js file contains the CodeMirror.defineSimpleMode function but is odd it's causing an issue?

I'm bundling quite a lot of files into one (36 in fact) and all works fine if I exclude rust.js and simple.js.

**Comment by melloware** [comment]
+1 I am trying the same thing while updating the Primefaces Extension CodeMirror JSF component.  I am having the exact issue as above

**Comment by mattpass** [comment]
@melloware - I didn't manage to get to the bottom of this and like using the CodeMirror compression helper, so in the end I excluded rust from my editor.

**Comment by melloware** [comment]
@mattpass that is exactly what I did I removed all simple.js languages and simple.js itself from my compression and now everything is compiling and happy in the browser.

**Comment by melloware** [comment]
I fixed this with this PR.  https://github.com/codemirror/CodeMirror/pull/4567
