### ISSUE TITLE
Markdown scroll Error

### ISSUE THREAD

**Issue by yutuo** [codemirror/CodeMirror#3884]
I tested it at chrome  48.0.2564.116 m

1. Open the site https://codemirror.net/
![1](https://cloud.githubusercontent.com/assets/2993927/13735723/521146b2-e9f0-11e5-8977-2a5e4647004f.png)

2. Input words unless the scroll is showed.
![2](https://cloud.githubusercontent.com/assets/2993927/13735737/6fe8177e-e9f0-11e5-96dd-88f5d629e8dc.png)

3. Delete words unless the scroll is hided.
![3](https://cloud.githubusercontent.com/assets/2993927/13735752/96f6bf32-e9f0-11e5-95b6-b976efb75bc5.png)

4. And then, Move mouse to CodeMirror. CodeMirror can scroll.
![4](https://cloud.githubusercontent.com/assets/2993927/13735758/a808cacc-e9f0-11e5-9008-8a81966303ea.png)

**Comment by sbruchmann** [comment]
How is that related to Markdown?

**Comment by yutuo** [comment]
I'm sorry. I made a stupid mistake.
The title is "CodeMirror can be scroll to up when scroll bar is hided".
