### ISSUE TITLE
Allow gutter width to be specified inline

### ISSUE THREAD

**Issue by jochenberger** [codemirror/CodeMirror#3886]
Currently, you can add a gutter via
```javascript
cm.setOption('gutters', ['foo']);
```
then you have to add a CSS file with
```css
.CodeMirror-gutter.foo {
  width: 16px;
}
```
I'd like to be able to specify the display properties in the option directly so that I don't need an extra CSS file. This could look like
```javascript
cm.setOption('gutters', [{
                          'id': 'foo',
                          'style': { width: '16px' }
                          }]);
```

**Comment by marijnh** [comment]
Since you'll often want to specify additional styling anyway, and pixel sizes tend to belong in CSS, I don't think the current state of affairs is very problematic.
