### ISSUE TITLE
Failing indent for trailing if/unless in crystal

### ISSUE THREAD

**Issue by bcardiff** [codemirror/CodeMirror#3887]
Trailing if/unless are counted for indentation. 

If user inputs,

```
a = rand if true
```

Then, the cursor is left with one extra indentation level.

![](http://g.recordit.co/psgFlmciWj.gif)

![](http://g.recordit.co/YMmsrZy7pm.gif)

The ruby mode does not suffer from this, maybe there is something to reuse from there.

version: CodeMirror 5.12.0
cc: @MakeNowJust

**Comment by marijnh** [comment]
@MakeNowJust Do you want to take a look at this?

**Comment by MakeNowJust** [comment]
Yes. I am considering this now. `if` is not only suffix keyword but expression.
Example:
```
# below if is suffix
foo = 42 if 1 == 2
# below if is expression
bar = if foo
  1
else
  2
end
```
How do I support it?
And, I am in busy now. Please wait for some days;) 月曜日, 21 3月 2016, 06:31午後 +09:00 from Marijn Haverbeke < notifications@github.com> :

**Comment by marijnh** [comment]
Looks like you'll have to somehow distinguish between suffix `if` and start-of-expression `if`. I'm not sure how hard that is in in this grammar
