### ISSUE TITLE
Wrapper element does not contain gutter elements

### ISSUE THREAD

**Issue by jochenberger** [codemirror/CodeMirror#3890]
The `addLineClass` documentation states that if I set `where` to `wrap`, it adds the class to "the wrapper node that wraps all of the line's elements, including gutter elements". I remember that it used to be like that, but now the gutter elements seem to be outside of the wrapper element.

**Comment by marijnh** [comment]
Nope, it isn't, nothing about that changed, and I just tested.

**Comment by jochenberger** [comment]
Yes, you're right, I just noticed myself while trying to reproduce the issue in a fiddle. Sorry.
