### ISSUE TITLE
Simple scroll bar might disappear when height decreasing

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#3891]
1. Go to https://codemirror.net/demo/simplescrollbars.html
2. Scroll to the bottom
3. Delete from line 31 to line 39 at once
4. The scroll bar now is half beneath the editor.
![default](https://cloud.githubusercontent.com/assets/2639151/13896171/d09b1622-edbd-11e5-9b64-c5a2df65f44e.png)

**Comment by marijnh** [comment]
Which browser? I'm not having any luck reproducing it in Chrome Linux.

**Comment by marijnh** [comment]
Oh, hold on, no, I *can* reproduce. Investigating.

**Comment by marijnh** [comment]
Attached patch seems to help.
