### ISSUE TITLE
TypeScript JSX support

### ISSUE THREAD

**Issue by christianalfoni** [codemirror/CodeMirror#3893]
Hi there!

I am working on a service called www.webpackbin.com and CodeMirror has been a great tool to help developers learn and share code with NPM tools.

But I can not find any highlighting for TypeScript with JSX (.tsx format). I can look into it, but I have no idea where to start. So was wondering if someone had a couple of pointers to solving this issue.

Thanks in advance!

**Comment by marijnh** [comment]
With patch 1de61c6 you can set your mode to `{name: "jsx", base: {name: "javascript", typescript: true}}` to get JSX-with-TypeScript

**Comment by christianalfoni** [comment]
Ah, that is great! Is this part of next release? Or am I on the wrong version? Thanks for your time :-)

**Comment by zaggino** [comment]
@marijnh Can you please create MIME definition for `jsx` with `typescript` ? Didn't find one in the `jsx.js` file. Similar to: https://github.com/codemirror/CodeMirror/blob/1de61c6a2031b06045d0c867c7c27b5b9bbb7e3a/mode/javascript/javascript.js#L739
Thanks

**Comment by marijnh** [comment]
@zaggino Done in a7bfe34 . Any ideas for a better MIME type string?
