### ISSUE TITLE
getValue in beforeChange event

### ISSUE THREAD

**Issue by hanspeter1** [codemirror/CodeMirror#3894]
Is there a way to get the text value, inside the beforeChange event handler like:

```
this.instance.on("beforeChange", function (cm, change) {
    var oldContent =  cm.getValue();
    var newContent = cm.getChangedValue();
}
```

The method getChangedValue() should be return the codemirror content after the change is executed.

**Comment by marijnh** [comment]
Nope, but you could use the information in the `change` object to create the new content yourself if you really want to.

**Comment by hanspeter1** [comment]
That's bad .... 

Who among you needs this:

        this.instance.on("beforeChange", function (cm, change) {
            console.log(change);

            var oldContent = cm.getValue();
            var newContent = "";

            // Split lines
            var lines = oldContent.split('\n');

                if (change.origin == "+delete") {

                    // Change is only inline
                    if (change.from.line == change.to.line) {

                        // Modify the line
                        lines[change.from.line] = lines[change.from.line].substr(0, change.from.ch) + lines[change.from.line].substr(change.to.ch + 1, a.length);

                        // Concat new content
                        lines.map(function (line) {
                            newContent += line + "\n";
                        });
                    }
                    // Change over min. 2 lines
                    else {
                        var newLines = [];
                        for (var i = 0; i < lines.length; i++) {

                            if (i < change.from.line || i > change.to.line) {
                                newLines.push(lines[i]);
                            }
                            else if (i == change.from.line) {
                                newLines.push(lines[i].substr(0, change.from.ch));
                            }
                            else if (i == change.to.line) {
                                newLines.push(lines[i].substr(change.to.ch, lines[i].length));
                            }
                        }

                        // Concat new content
                        newLines.map(function (line) {
                            newContent += line + "\n";
                        });
                    }
                }
                else if (change.origin == "+input") {

                    // Modify the line
                    lines[change.from.line] = [lines[change.from.line].slice(0, change.from.ch), change.text[0], lines[change.from.line].slice(change.to.ch)].join('');

                    // Concat new content
                    lines.map(function (line) {
                        newContent += line + "\n";
                    });

                }
                else if (change.origin == "paste") {
                    // Create content to paste
                    var pasteContent = "";
                    change.text.map(function (line) {
                        pasteContent += line + "\n"
                    });

                    // Modify the line
                    lines[change.from.line] = [lines[change.from.line].slice(0, change.from.ch), pasteContent, lines[change.from.line].slice(change.to.ch)].join('');

                    // Concat new content
                    lines.map(function (line) {
                        newContent += line + "\n";
                    });
                }
                
                console.log("***************************************");
                console.log(oldContent);
                console.log("***************************************");
                console.log(newContent);
                console.log("***************************************");
        });
