### ISSUE TITLE
Line number gutter style not applied in some cases in merge view

### ISSUE THREAD

**Issue by Dominator008** [codemirror/CodeMirror#3895]
Try scrolling around in: https://codemirror.net/demo/merge.html
Sometimes the style of the line number gutter is not applied on one side of the view, causing the background of the line number gutter to become transparent and allowing the text in the editor to show through them.

**Comment by marijnh** [comment]
Which browser did this occur in? (No luck getting it to happen on Chrome so far)

**Comment by Dominator008** [comment]
I'm running Chrome 51 on Linux. Also happening on Firefox 45 on Linux.
Try scrolling down then scrolling right on the right pane.

**Comment by vincentwoo** [comment]
can confirm on chrome 49 on windows

![overflow](https://cloud.githubusercontent.com/assets/613320/13978393/e7240994-f08d-11e5-8f25-eab7a3e6d237.PNG)

**Comment by Dominator008** [comment]
I suspect https://github.com/codemirror/CodeMirror/commit/ecaa8914751ad5472f315bce5f0c49c232aa5c26 caused this.

**Comment by marijnh** [comment]
I've reverted that code in 0814679 . Am now looking for an alternative fix to address the issue it was trying to fix.

**Comment by marijnh** [comment]
(Will bring out a new release when I've found an alternative fix.)
