### ISSUE TITLE
Language Request: PowerShell

### ISSUE THREAD

**Issue by RandomlyKnighted** [codemirror/CodeMirror#3898]
There is currently no support for the PowerShell language. If at some point, PowerShell is supported it would be great if both [.ps1](https://github.com/NARKOZ/hacker-scripts/blob/master/powershell/smack_my_bitch_up.ps1) and [.psm1](https://github.com/NARKOZ/hacker-scripts/blob/master/powershell/hangover.psm1) were supported.

**Comment by marijnh** [comment]
We don't keep open issues for mode requests. See [the wiki](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list)

**Comment by Dominator008** [comment]
@RandomlyKnighted https://github.com/VapidWorx/powershell-cm-mode
