### ISSUE TITLE
Issues on show-hint.js

### ISSUE THREAD

**Issue by ttyrueiwoqp** [codemirror/CodeMirror#3901]
Refer to the line 112 and 113 in `update()`, I am wondering whether `this.options.hint` should be an object or a function.

If I want to use `async`, I may pass in options like this `hintOptions: {
    async: true
}`, and I guess here it should be `this.options.async` instead of `this.options.hint.async`, according to `parseOptions()` in line 147, right?

If I pass in options like this `hintOptions: {
    hint: {
        async: true
    }
}`, then `this.options.hint` function in `else` in line 116 will not work.

**Comment by marijnh** [comment]
JavaScript functions _are_ objects, so you should pass in a function, and give it an `async` property if appropriate.
