### ISSUE TITLE
posFromIndex and indexFromPos assume length of line separator is 1

### ISSUE THREAD

**Issue by marcelklehr** [codemirror/CodeMirror#3905]
However, if e.g. lineSeparator is set to `"\r\n"`, which has length 2 in javascript, things don't fit anymore.

See https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L7651

**Comment by marijnh** [comment]
Good point. Attached patch should fix this.

**Comment by marcelklehr** [comment]
Thanks! :)
