### ISSUE TITLE
Getting "Missing license blob" for most files when running lint under Windows

### ISSUE THREAD

**Issue by ashmind** [codemirror/CodeMirror#3909]
Getting a lot of "Missing license blob" messages from `bin/lint`:

```
...skipped...
mode/haskell/haskell.js: Missing license blob
mode/haskell-literate/haskell-literate.js: Missing license blob
mode/haxe/haxe.js: Missing license blob
mode/htmlembedded/htmlembedded.js: Missing license blob
mode/htmlmixed/htmlmixed.js: Missing license blob
mode/http/http.js: Missing license blob
mode/idl/idl.js: Missing license blob
mode/jade/jade.js: Missing license blob
mode/javascript/javascript.js: Missing license blob
mode/javascript/test.js: Missing license blob
mode/jinja2/jinja2.js: Missing license blob
mode/jsx/jsx.js: Missing license blob
mode/jsx/test.js: Missing license blob
mode/julia/julia.js: Missing license blob
mode/livescript/livescript.js: Missing license blob
mode/lua/lua.js: Missing license blob
mode/markdown/markdown.js: Missing license blob
mode/markdown/test.js: Missing license blob
...skipped...
```

It seems that it is caused by `.gitattributes` defining some files as `text`, which causes `LF` in those files to be replaced with `core.eol` on checkout. On Windows, default `core.eol` is `native` (`CRLF`), and there is no way to set it to "keep as is" on a global level.

Potential fixes:
- Preferred: Add `eol=lf` setting to `.gitattributes`
- Change lint rule so that it matches any of `\r`, `\n` or `\r\n` in license blob.

**Comment by ficristo** [comment]
It would be nice to have a fix here.

**Comment by marijnh** [comment]
We're moving away from tagging all files with a license blob, so attached patch removes the check.
