### ISSUE TITLE
BIND missing from ops in sparql mode

### ISSUE THREAD

**Issue by keski** [codemirror/CodeMirror#3922]
The operator *bind* seems to be missing from the list of ops:
```
SELECT *
WHERE {
   ...
   BIND("test" AS ?t)
}
```
will show BIND as an unrecognised.

**Comment by marijnh** [comment]
I can't find anything about this op in [the standard](https://www.w3.org/TR/rdf-sparql-query/). Where is it defined?

**Comment by keski** [comment]
Yes, it's missing from the 2008 version but it is defined in the later published [SPARQL 1.1 specification](https://www.w3.org/TR/sparql11-query/).

**Comment by marijnh** [comment]
Makes sense. If you feel like extracting a full list from that standard, that'd be useful. For now, I've simply added `bind`.

**Comment by keski** [comment]
I couldn't really see anything else that was missing but I didn't have time to put in much effort. If I stumble across anything I'll make sure to provide feedback.
