### ISSUE TITLE
glyph for broken line?

### ISSUE THREAD

**Issue by scottdraves** [codemirror/CodeMirror#3923]
is there a way to get a style set where lines have been broken, like for a long line when word wrap is set?
we would like there to be a visual indication (like a bent arrow) at the end of lines that are broken or wrapped to the next line.
we can't find a way to do this with code mirror https://github.com/twosigma/beaker-notebook/issues/3744
thanks.

**Comment by marijnh** [comment]
Nope, this feature does not exist, and is unlikely to exist in the future. The browser handles the wrapping, and CSS doesn't provide a way to do what you describe.

**Comment by scottdraves** [comment]
thanks.
