### ISSUE TITLE
Inserting a widget with position:absolute can cause a line to collapse in firefox

### ISSUE THREAD

**Issue by marcelklehr** [codemirror/CodeMirror#3928]
I added a widget with position absolute (in order to not affect the position of the text). When added to an empty line, the line will collapse in Firefox.

The picture shows the result in Chromium (left) and firefox (right):

![screenshot from 2016-03-31 18-25-34](https://cloud.githubusercontent.com/assets/986878/14183035/65c7e798-f76e-11e5-971c-681625e99fa0.png)

I'm not sure if this is a bug (since using position:absolute on a widget is probably unusual), but I wanted to let you know. Perhaps you could mention it in the docs.

**Comment by marijnh** [comment]
Maybe wrap it in a relatively-positioned zero-width overflow-visible element? In any case, as you said, this isn't something that the library aims to support
