### ISSUE TITLE
Sublime demo is not working

### ISSUE THREAD

**Issue by coolwidgets** [codemirror/CodeMirror#3930]
I copied all code from demo/sublime.html but its not working on my localhost. However basic demo is working.

Here is my code- 

                           <link rel="stylesheet" href="aryan/assets/codemirror/codemirror.css">
                            <link rel="stylesheet" href="aryan/assets/codemirror/foldgutter.css">
                            <link rel="stylesheet" href="aryan/assets/codemirror/dialog.css">
                            <link rel="stylesheet" href="aryan/assets/codemirror/monokai.css">
                            <script src="aryan/assets/codemirror/codemirror.js"></script>
                            <script src="aryan/assets/codemirror/searchcursor.js"></script>
                            <script src="aryan/assets/codemirror/search.js"></script>
                            <script src="aryan/assets/codemirror/dialog.js"></script>
                            <script src="aryan/assets/codemirror/matchbrackets.js"></script>
                            <script src="aryan/assets/codemirror/closebrackets.js"></script>
                            <script src="aryan/assets/codemirror/comment.js"></script>
                            <script src="aryan/assets/codemirror/hardwrap.js"></script>
                            <script src="aryan/assets/codemirror/foldcode.js"></script>
                            <script src="aryan/assets/codemirror/brace-fold.js"></script>
                            <script src="aryan/assets/codemirror/javascript.js"></script>
                            <script src="aryan/assets/codemirror/sublime.js"></script>
                          <script type="text/javascript">
                         var editor = CodeMirror.fromTextArea(document.getElementById("editor"), {
                              lineNumbers: true,
                              //mode: "text/html",
                              matchBrackets: true
                            });
                          // var value = "// The bindings defined specifically in the Sublime Text mode\nvar bindings = {\n";
                          // var map = CodeMirror.keyMap.sublime;
                          // for (var key in map) {
                          //   var val = map[key];
                          //   if (key != "fallthrough" && val != "..." && (!/find/.test(val) || /findUnder/.test(val)))
                          //     value += "  \"" + key + "\": \"" + val + "\",\n";
                          // }
                          // value += "}\n\n// The implementation of joinLines\n";
                          // value += CodeMirror.commands.joinLines.toString().replace(/^function\s*\(/, "function joinLines(").replace(/\n  /g, "\n") + "\n";
                          // var editor = CodeMirror(document.getElementById("editor"), {
                          //   value: value,
                          //   lineNumbers: true,
                          //   mode: "javascript",
                          //   keyMap: "sublime",
                          //   autoCloseBrackets: true,
                          //   matchBrackets: true,
                          //   showCursorWhenSelecting: true,
                          //   theme: "monokai",
                          //   tabSize: 2
                          // });
                        </script>

**Comment by vincentwoo** [comment]
You uh... commented out everything? `keyMap: "sublime",` is what triggers the sublime key mapping.

**Comment by coolwidgets** [comment]
No I just commented out because it didn't work. So I added code  for basic highlighting and commented out codes for sublime text features. Below code is working

        var editor = CodeMirror.fromTextArea(document.getElementById("editor"), {
                          lineNumbers: true,
                          //mode: "text/html",
                          matchBrackets: true
                        });

while this code is not working that's why I commented out-

                      var value = " The bindings defined specifically in the Sublime Text mode\nvar bindings = {\n";
                       var map = CodeMirror.keyMap.sublime;
                       for (var key in map) {
                         var val = map[key];
                         if (key != "fallthrough" && val != "..." && (!/find/.test(val) || /findUnder/.test(val)))
                           value += "  \"" + key + "\": \"" + val + "\",\n";
                       }
                       value += "}\n\n// The implementation of joinLines\n";
                       value += CodeMirror.commands.joinLines.toString().replace(/^function\s*\(/, "function joinLines(").replace(/\n  /g, "\n") + "\n";
                       var editor = CodeMirror(document.getElementById("editor"), {
                         value: value,
                         lineNumbers: true,
                         mode: "javascript",
                         keyMap: "sublime",
                         autoCloseBrackets: true,
                         matchBrackets: true,
                         showCursorWhenSelecting: true,
                         theme: "monokai",
                         tabSize: 2
                      });

**Comment by vincentwoo** [comment]
You probably did something else wrong. Can you make a jsfiddle or codepen? Literally all you have to do is include the extra sublime.js file and specify the `keyMap` option.

**Comment by coolwidgets** [comment]
Hi,

I've created a jsfiddle for this.

https://jsfiddle.net/rnkushwaha022/mj8Lh59n/5/

Please see how its not working.

**Comment by coolwidgets** [comment]
Hi,

I've created a jsfiddle for this.

https://jsfiddle.net/rnkushwaha022/mj8Lh59n/5/

Please see why its not working.

**Comment by vincentwoo** [comment]
You just randomly pasted some stuff in a codepen. You need to actually include JS libraries, etc. I recommend you learn basic HTML/JS before attempting to use a third party library like CodeMirror.

**Comment by coolwidgets** [comment]
Its not random data pasted. Its from demo of codemirror site. I have
included all required libraries in external Resources section. Here is the
screenshot http://prntscr.com/anyb38.

I know html/js very well and I am also a jQuery plugin developer.

However my actual code is here-

<!DOCTYPE HTML> <html> <head> <title>Files on Localhost</title> <meta
charset="utf-8" />  <style> .command {font-size: 15px;}</style>
<link rel="stylesheet" href="aryan/assets/codemirror/codemirror.css">
<link rel="stylesheet" href="aryan/assets/codemirror/foldgutter.css">
<link rel="stylesheet" href="aryan/assets/codemirror/dialog.css">
<link rel="stylesheet" href="aryan/assets/codemirror/monokai.css">
<link rel="stylesheet" href="aryan/assets/codemirror/show-hint.css">
<script src="aryan/assets/codemirror/codemirror.js"></script>
<script src="aryan/assets/codemirror/show-hint.js"></script>
<script src="aryan/assets/codemirror/javascript-hint.js"></script>
<script src="aryan/assets/codemirror/css-hint.js"></script>
<script src="aryan/assets/codemirror/html-hint.js"></script>
<script src="aryan/assets/codemirror/searchcursor.js"></script>
<script src="aryan/assets/codemirror/search.js"></script>
<script src="aryan/assets/codemirror/dialog.js"></script>
<script src="aryan/assets/codemirror/matchbrackets.js"></script>
<script src="aryan/assets/codemirror/closebrackets.js"></script>
<script src="aryan/assets/codemirror/comment.js"></script>
<script src="aryan/assets/codemirror/hardwrap.js"></script>
<script src="aryan/assets/codemirror/foldcode.js"></script>
<script src="aryan/assets/codemirror/brace-fold.js"></script>
<script src="aryan/assets/codemirror/javascript.js"></script>
<script src="aryan/assets/codemirror/sublime.js"></script>
</head> <body> <p><b>Editing File:</b>
var/www/html/commloan/components/com_lender/lender.php</p> <br/>
<textarea style="margin:10px 20px;width:95%;height:600px" id="editor"
name="editor">
<?php
//--No direct access
defined('_JEXEC') or die('=;)');
if (!defined( 'DS' )) define('DS',DIRECTORY_SEPARATOR);
// Require the base controller
require_once( JPATH_COMPONENT.DS.'controller.php' );
jimport('joomla.application.component.model');
jimport( 'joomla.application.component.view' );
jimport('joomla.application.component.helper');
JHTML::addIncludePath(JPATH_COMPONENT_ADMINISTRATOR.DS.'helpers' );

$jsFIleURl       = $component_apath.'assets/js/';
$cssFIleURl      = $component_apath.'assets/css/';
$limit             = 20;

// Create the controller
$classname    = 'TestController'.$controller;
$controller   = new $classname($ControllerConfig );

// Perform the Request task
$controller->execute( JRequest::getVar( 'task' ) );

// Redirect if set by the controller
$controller->redirect();
</textarea>
</body>
<style type="text/css">
.CodeMirror {border-top: 1px solid #eee; border-bottom: 1px solid #eee;
line-height: 1.3; height: 500px} .CodeMirror-linenumbers { padding: 0 8px; }
</style>
<script type="text/javascript">
  var value = "// The bindings defined specifically in the Sublime Text
mode\nvar bindings = {\n";
  var map = CodeMirror.keyMap.sublime;
  for (var key in map) {
    var val = map[key];
    if (key != "fallthrough" && val != "..." && (!/find/.test(val) ||
/findUnder/.test(val)))
      value += "  \"" + key + "\": \"" + val + "\",\n";
  }
  value += "}\n\n// The implementation of joinLines\n";
  value +=
CodeMirror.commands.joinLines.toString().replace(/^function\s*\(/,
"function joinLines(").replace(/\n  /g, "\n") + "\n";
  var editor = CodeMirror(document.getElementById("editor"), {
    value: value,
    lineNumbers: true,
    mode: "javascript",
    keyMap: "sublime",
    autoCloseBrackets: true,
    matchBrackets: true,
    showCursorWhenSelecting: true,
    theme: "monokai",
    tabSize: 2
  });
</script></html>

**Comment by matthias-vogt** [comment]
Just an SSL issue, you included `codemirror.css` over `http://` on jsfiddle, which uses https.
Use `//` or `https://` instead and you'll be fine.
https://jsfiddle.net/mj8Lh59n/8/
