### ISSUE TITLE
Some error within the core.

### ISSUE THREAD

**Issue by slavidodo** [codemirror/CodeMirror#3931]
```Uncaught TypeError: Cannot read property 'first' of undefined```

Exactly, the problem is in that line

Line *187* : 
```javascript
d.viewFrom = d.viewTo = doc.first;
```

- What code did I use ?
The simplest ever.
```html
<div id="editor"></div>
<link rel="stylesheet" href="lib/codemirror.css">
<script src="lib/codemirror.js"></script>
<script>
  var editor = CodeMirror.fromTextArea(document.getElementById('editor'), {
    lineNumbers: true
  });
</script>
````
What could be causing it?

**Comment by marijnh** [comment]
The element with id `editor` is not a textarea, causing its `value` property to be undefined, which causes this error. `fromTextArea` expects a `<textarea>` node, not any dom node.
