### ISSUE TITLE
Python triple quotes rendering is sometimes screwed

### ISSUE THREAD

**Issue by codyc4321** [codemirror/CodeMirror#3936]
#!/usr/bin/env python

""" 
just install in crontab:
    
    crontab -e
    
    * * * * * /usr/bin/python ~/path/update_files.py
"""
files = [{'real_path': '.bash_profile', 'repo_path': 'bash/bash_profile.sh'},]

to 

#!/usr/bin/env python

& quot;& quot;& quot; 
just install in crontab:
    
    crontab -e
    
    * * * * * /usr/bin/python ~/path/update_files.py
& quot;& quot;& quot;

from my_scripting_library import update_file

files = [{& #39;real_path& #39;: & #39;.bash_profile& #39;, & #39;repo_path& #39;: & #39;bash/bash_profile.sh& #39;},
         {& #39;real_path& #39;: & #39;.atom/snippets.cson& #39;, & #39;repo_path& #39;: & #39;atom_files/snippets.cson& #39;},
         {&#39;real_path&#39;: &#39;.atom/config.cson&#39;, &#39;repo_path&#39;: &#39;atom_files/config.cson&#39;}]

even after setting input string to raw string

**Comment by marijnh** [comment]
If I paste that into http://codemirror.net/mode/python/ the highlighting looks fine. Could you describe the problem in more detail?

**Comment by codyc4321** [comment]
when feeding from django views to the template, codemirror does not handle quotes. I tried feeding it a normal python string, a raw string, and a string with html elements like "&#39;", no dice. Does anyone know the standard path using django/python to feed your HTML template a correct string for codemirror, or is it just a flag within codemirror?

**Comment by marijnh** [comment]
I don't know anything about django views. If this is something you can reproduce with our code, feel free to comment here, but until them, I'm closing this.
