### ISSUE TITLE
NPM package codemirror@5.13.2 is missing the LICENSE file

### ISSUE THREAD

**Issue by Dominator008** [codemirror/CodeMirror#3940]
Repro:
```sh
npm install codemirror@5.13.2
cd node_modules/codemirror/ && ls LICENSE
```
Output:
```
ls: cannot access LICENSE: No such file or directory
```
5.13.0 has it. For some reason 5.13.2 is missing it.

Should we do a 5.13.3 release to fix this?

**Comment by marijnh** [comment]
Verified that it's missing. But I could not figure out how that happened -- at no point was it missing from the respository, it hasn't been added to `.npmignore`, and I don't remember doing anything strange when publishing.

`npm publish` doesn't seem to have a dry-run option, so I'm unsure how to debug this. Any ideas?

**Comment by Dominator008** [comment]
@marijnh Yeah that's confusing and does seem like a bug in NPM. A workaround is using `npm pack` and publishing that tarball instead, not ideal though.

**Comment by marijnh** [comment]
Okay, `npm pack` includes the license properly. I probably managed to do something weird when publishing that release (though I still can't figure out what). Published a 5.13.4 with a `LICENSE` file.

**Comment by Dominator008** [comment]
@marijnh Thanks. However, now `package.json` says 5.13.3 while NPM says 5.13.4. I guess we should fix this discrepancy?

**Comment by marijnh** [comment]
Done.

**Comment by Dominator008** [comment]
Thanks :+1

**Comment by Dominator008** [comment]
Can you do an `npm publish`? It still says 5.13.4 on NPM.

**Comment by marijnh** [comment]
It _should_ say 5.13.4 on NPM, that's the version I released. .5 is just an in-between development version.

**Comment by Dominator008** [comment]
Oh the "version" in 5.13.4's `package.json` does say "5.13.4", so it's correct. Thanks.
