### ISSUE TITLE
markText strange behavior when 'from' and 'to' positions are strings

### ISSUE THREAD

**Issue by jchook** [codemirror/CodeMirror#3953]
In `doc.markText()`, numbers represented as strings only _sometimes_ cause the marked range to be hyperextended until the beginning of the next marked range. It would be better if strings either threw an exception or were handled properly without bugs (e.g. parseInt).

Here is a jsfiddle to demonstrate the bug:
http://jsfiddle.net/p1mdp259/1/

**Comment by marijnh** [comment]
The documentation makes it clear that positions take _numbers_, not strings. If you're passing in invalid values, you can't expect the library to work.
