### ISSUE TITLE
RequireJs definition is unnamed

### ISSUE THREAD

**Issue by ivorobkalo** [codemirror/CodeMirror#3955]
RequireJs throws exception if module is defined through code and without package name.

**Comment by marijnh** [comment]
It would be helpful if you showed the code you're using to define this module. Right now, there's very little I can make of this issue.

**Comment by ivorobkalo** [comment]
Just add a param, so instead of
```javascript
if (typeof define == "function" && define.amd) // AMD
    return define([], mod);
```
write something like

```javascript
if (typeof define == "function" && define.amd) // AMD
    return define("code-mirror", [], mod);
```

**Comment by marijnh** [comment]
Ah, I see what you mean now. How is this a problem?

**Comment by ivorobkalo** [comment]
It throws exception like the following in some cases (use it as a bower dependency and register it via js, not html)

```
require.js:165 Uncaught Error: Mismatched anonymous define() module: function () {
 ...
whole file content
...
  CodeMirror.version = "5.13.4";

  return CodeMirror;
}
http://requirejs.org/docs/errors.html#mismatch
```

**Comment by ivorobkalo** [comment]
However does influence code behaviour only in rare cases but those error in console is annoying

**Comment by marijnh** [comment]
That's an issue in the way you're using the library (see [here](http://requirejs.org/docs/errors.html#mismatch)). I'm not going to include names in my `define` calls to address that.
