### ISSUE TITLE
Rectangular selection not possible on Chrome OS due to alt+click being used by the OS

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3956]
There was an attempt to change the behavior, but it got reverted: https://bugs.chromium.org/p/chromium/issues/detail?id=248762#c60

Any chance some other key combo could also be allocated for this? Either only on CrOS or in general?

What would be really great, of course, is a system of specifying mouse bindings similar to how we can specify keybindings/keymaps. We hack around this for a good amount of functionality right now, and it'd be great to use something internally-supported/consistent.

**Comment by marijnh** [comment]
Any suggestions for an alternative set of modifiers to use for block selection on Chrome OS?

As for making these configurable, that's not a bad idea, but it's not something I'm going to be working on anytime soon.

**Comment by mtaran-google** [comment]
I played with a chromebook, and it looks like meta+click does get propagated to the JS, but even after you meta+click and drag, on keyup the OS functionality of opening a big search popup gets fired, and preventDefault doesn't help. 

But, meta+shift+click does the trick, and since those buttons are physically next to each other (meta is where capslock is on other OSes), I think that would be a reasonable alternative.

**Comment by marijnh** [comment]
Sounds good. Does attached patch work for you? (I don't have a ChromeBook to test on)

**Comment by mtaran-google** [comment]
Yep, that works great! Thanks :)
