### ISSUE TITLE
Firefox on Windows 10 (v43 and above): codemirror Editor is truncated. and there is a black bar on the gutters and horizontal scroll bar  

### ISSUE THREAD

**Issue by palashM** [codemirror/CodeMirror#3962]
Firefox on Windows 10 (v43 and above): codemirror Editor is truncated. and there is a black bar on the gutters and horizontal scroll bar.
This happens on FF v43 and above when the number of lines in the editor is above 602.(total lines i have is 800). 
As you can see in the attached screenshot, the XML after line 602 is not visible and the black bar is visible in place of line numbers.
 
Additional css that I have done are :- 
`.CodeMirror {
    height: auto !important;
} 
.CodeMirror-scroll {
    overflow-y: hidden !important;
    overflow-x: auto !important;
}`
![xmleditior-issue](https://cloud.githubusercontent.com/assets/6646912/14563960/048043e2-0342-11e6-9118-6e0fbd3014eb.PNG)

**Comment by marijnh** [comment]
Don't mess with the overflow properties on `CodeMirror-scroll`. That's not supported.
