### ISSUE TITLE
Automatically unfocused from the editor

### ISSUE THREAD

**Issue by merbin2012** [codemirror/CodeMirror#3967]
My aim is place the end and start html tag in the cursor position, my code is perfectly insert the tags on the cursor position but after placing the text the cursor display 1second and the cursor gone from the editor (automatically unforus) and the **blur** function is called. I call the below function **firstwin(tagstart,endtag);** (<= I cann't write the full line when i write the full HTML line the below javascript code are hide in github)
My code is

```
function firstwin(start,end)
{
	clstagmenu();
	var e1=document.getElementById('iiffrraammee'); //because the codemirror is inside the iframe
	getIframeWindow(e1).settag(start,end); //call code mirror function from parent of the iframe
	return false;
}
----
----
//with codemirror iframe content (external.js)
function settag(starttag,endtag)
{
    editor.replaceRange(starttag+endtag, editor.getCursor());

    var str=endtag;
    var mynum=str.length;
    var start_cursor = editor.getCursor();  //I need to get the cursor position
    console.log(start_cursor);  //Cursor position 
    var cursorLine = start_cursor.line;
    var cursorCh = start_cursor.ch;
    //Code to move cursor back [x] amount of spaces. [x] is the data-val value.
    editor.setCursor({line: cursorLine , ch : cursorCh -mynum });
    return false;
}
editor.on("blur", function(){
    alert("onBlur");
});
</script>
```

**Comment by marijnh** [comment]
This is almost certainly a problem with your code. Possible you're letting the mousedown event through, causing focus to move to the outer frame. CodeMirror doesn't spontaneously unfocus itself.
