### ISSUE TITLE
showHint: allow hint function to return promise ?

### ISSUE THREAD

**Issue by Carreau** [codemirror/CodeMirror#3971]
Does it make sens ?
Would a patch doing that be accepted ?
if so, any requirements beyond the usual ?

**Comment by marijnh** [comment]
Yes, this would make a lot more sense than the current async hack, now that promises are pretty much a part of the language. A clean patch + doc updates (maybe even tests?) would definitely be welcome.

**Comment by Dominator008** [comment]
Note that Promises would need to be polyfilled for browsers like IE <= 11.

**Comment by marijnh** [comment]
Our code wouldn't have to directly mention `Promise`, it'd just check for a `then` method. That way, the decision of whether to use / polyfill them is entirely up to the client code.

**Comment by Carreau** [comment]
Done in #3974, not sure how/where to do tests though. I manually expanded and tested the examples in `completions.html` still.
