### ISSUE TITLE
match-highlighter.js doesn't highlight leading or trailing spaces

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3972]
1. open http://codemirror.net/demo/matchhighlighter.html
2. selet " sit amet, " on line 6

Expected:
on line 12, " sit amet, " is highlighted

Actual:
on line 12, only "sit amet," is highlighted, without the leading and trailing spaces

**Comment by marijnh** [comment]
This appears to be intentional behavior. Attached patch adds an option (`trim`) to turn it off.
