### ISSUE TITLE
Make lineWiseCopyCut function properly

### ISSUE THREAD

**Issue by matthew-hayes** [codemirror/CodeMirror#3983]
I don't even understand how one is supposed to use the current implementation of lineWiseCopyCut conveniently.  
Please make this function similar to how Sublime does it!  It's a great feature when it actually works right :P

Issues:
 - If the cursor is in the middle of a line of text and you do Ctrl+C/Ctrl+V, text is pasted at the current cursor location instead of at the beginning of the next line... How often do you actually want to paste an entire line into the middle of another line?

 - If you're currently at the end of a line and do enter instead of right arrow before Ctrl+C/Ctrl+V to help avoid the above problem, then the resulting pasted line of text has the wrong indentation due to auto-indent of Enter.  It would be nice if Ctrl+V of a whole line undoes any auto-tabbing. 

- After Ctrl+V, cursor should be at corresponding position of the pasted line as either position in current line or position when Ctrl+C/X was applied to get line on clipboard.  

To fix these things all we really need to be able to do is change the user's cursor position before and after the current implementation takes place.  This should be perfectly doable in most modern browsers, e.g.:
http://stackoverflow.com/questions/512528/set-cursor-position-in-html-textbox

I think this would really improve coding workflows that use this feature in CodeMirror, so thank you for any attention this issue gets :D

**Comment by matthew-hayes** [comment]
Broken by 28abd453ff7f6cf9b3ca35f74a2de6ff4e00d339 @marijnh

**Comment by marijnh** [comment]
Argh, sorry, see 20d981f
