### ISSUE TITLE
How could I use two linters in one editor?

### ISSUE THREAD

**Issue by JasinYip** [codemirror/CodeMirror#3984]
I'm trying to add some custom annotations to the editor, which is using another linter already, such as javascript-lint.

For example, I registered a helper like:

```js
CodeMirror.registerHelper('lint', 'myLinter',  function () {
    return [{
      message: 'Hey!',
      from: CodeMirror.Pos(0, 0),
      to: CodeMirror.Pos(1, 2)
    }]
})
```

And I added these scripts into the HTML file:

```html
<script src="./bower_components/codemirror/addon/lint/lint.js"></script>
<script src="./bower_components/codemirror/addon/lint/javascript-lint.js"></script>
```

Finally I render the CodeMirror:

```js
config = {
  lineNumbers: true,
  mode: 'javascript',
  gutters: [
    'CodeMirror-lint-markers',
  ],
  lint: true
}

CodeMirror(DOM_elem, config)
```

So now I got two lint-helpers: javascript and myLinter

But only javascript-lint works. I have no idea how could I make `myLinter` work with `javascript-lint` together...

Could you please tell me what's things I missed?

CodeMirror is an amazing and powerful project, your're awesome! Thank you! 😄

**Comment by marijnh** [comment]
The lint addon doesn't support multiple helpers yet. It could be updated to call `getHelpers` instead of `getHelper`, and combine the messages it gets when there is more than one helper returned. Want to implement that?

**Comment by JasinYip** [comment]
It looks not that simple...

I found that even we call `getHelpers` instead of `getHelper`, it can only return the `javascript-lint`, excluded `myLinter`. Because `getHelpers` will check the mode of the `CodeMirror Doc`(by calling `getModeAt(post)`) and access into `mode.helperType && help[mode.helperType]` code block, then push `help[mode.helperType]` into the variable `found` only one time. I haven't read all of the source code so I can't make sure what's the right way to fix it.

Do you have a good idea for this?

**Comment by marijnh** [comment]
What is your linter for? If it targets a specific language, maybe just wrap the existing linter for the language. If it provides more general linting, maybe register it with `registerGlobalHelper`.

**Comment by Relequestual** [comment]
@marijnh Could you point me towards documentation on how I could go about wrapping an existing linter please? I want to caputre errors and display them elsewhere as well as in the editor.

**Comment by marijnh** [comment]
Linters are just functions that return an array of annotations — see [the manual](https://codemirror.net/doc/manual.html#addon_lint) — so you can wrap them in another function to change or extend what they do.

**Comment by Relequestual** [comment]
Right, I read over the manual closely for this, and created a function.
https://gist.github.com/Relequestual/149bb2503ecf40ed4d66b87e7ae68d56
The logging of the errors displays correctly, but the errors aren't highlighted.
If you're saying it SHOULD, then I'm not sure where to go next to debug this.

**Comment by Relequestual** [comment]
OK, I figured it out.
I was following this SO answer: https://stackoverflow.com/a/43059084
Because it's async, I have to call the passed through function as opposed to return the array.
And that IS documented. Must read docs more carefully!
