### ISSUE TITLE
How to trigger key event 

### ISSUE THREAD

**Issue by phuongtailtranminh** [codemirror/CodeMirror#3985]
Hi,

I'm trying to do co-operate Editor. The problem is, I didn't find anyway to make CodeMirror instance works like I want.

Example: In A's Editor, I send "Backspace" keyCode, now I want B's Editor also execute "Backspace". This not only the value problem.

**Comment by marijnh** [comment]
The approach to collaborative editing you're trying to use isn't going to work. You'll have to build something on top of change events, not keys. Also, you'll need some way to deal with concurrent/conflicting changes. This is out of scope for CodeMirror.

**Comment by phuongtailtranminh** [comment]
All I want is just how to execute keyCode in Code Mirror. Is there anyway to send "Backspace" keyCode or any keyCode to Code Mirror?
