### ISSUE TITLE
Vim prompt wraps text in narrow windows

### ISSUE THREAD

**Issue by dbarnett** [codemirror/CodeMirror#3991]
If you make a CodeMirror editor narrow enough that only ~10 characters can fit in the prompt and then in vim mode press <kbd>/</kbd> or <kbd>:</kbd>, you'll see the cursor is already on a 2nd line, below the prompt leader. CodeMirror should try to prevent line wraps there since they tend to obscure the text in the prompt and make it hard to use.

**Comment by marijnh** [comment]
Fixed in attached patch.
