### ISSUE TITLE
Please publish yourself in JSdelivr

### ISSUE THREAD

**Issue by ricardopolo** [codemirror/CodeMirror#3995]
Today you are in CDNs but you dont have auto update, so your versions in CDNs are very old.

Would be great if you have auto update to https://www.jsdelivr.com/

I am trying to publish you but they are not allowing me because you dont have minified versions in your bower
https://github.com/jsdelivr/jsdelivr/pull/11277

**Comment by marijnh** [comment]
I'm publishing to NPM and that's it. Other people can take up other channels if they want to.
