### ISSUE TITLE
Safari, iOS bug - capital letters won't turn off

### ISSUE THREAD

**Issue by raymestalez** [codemirror/CodeMirror#3997]
I'm using codemirror on my iPad, and I have encountered a strange bug.
 
When you press a shift button on the keyboard, it's supposed to capitalize the next letter you type, and after you've typed it, following letters should go back to being lower case. But instead, after I press shift and type a letter, shift stays turned on, and all the following letters are all capital.

That makes the editor pretty much unusable on mobile.

Can you help me to fix this?

**Comment by marijnh** [comment]
There's more information about this bug at https://github.com/ProseMirror/prosemirror/issues/25 . It's a Mobile Safari bug that's hard to work around in an editor set up like CodeMirror, though I might be able to lessen its impact when I rewrite input handling (which will happen sometime this summer).

**Comment by marijnh** [comment]
Ah, this was already reported as #3403.
