### ISSUE TITLE
markText error when using inclusiveRight/inclusiveLeft with two markers on the same line

### ISSUE THREAD

**Issue by brrd** [codemirror/CodeMirror#3998]
Running this example on CodeMirror's homepage:

```javascript
editor.setValue('a-b');
spanA = document.createElement('span'); spanA.innerText = 'A';
editor.markText({line: 0, ch: 0}, {line: 0, ch: 1}, {replacedWith: spanA, inclusiveRight: true});
spanB = document.createElement('span'); spanB.innerText = 'B';
editor.markText({line: 0, ch: 2}, {line: 0, ch: 3}, {replacedWith: spanB, inclusiveLeft: true});
```

The first marker is correctly rendered.
The second marker is not rendered and an error occurs: "Inserting collapsed marker partially overlapping an existing one".
When removing `inclusiveRight: true` or/and `inclusiveLeft: true` everything works fine.

It seems to be related with #2629.

This error occurs with CodeMirror 5.1.0 and 5.14.3 on Firefox and Chrome.

**Comment by marijnh** [comment]
This is intentional. Collapsed/replaced markers can not partially overlap, and by having them both be inclusive on the side where they touch, they would start overlapping as soon as anything in inserted between them. So that's not allowed.

**Comment by brrd** [comment]
@marijnh Thank you for your very quick reply.

Maybe I am missing something but in this example the two markers are separated by a character "-" (it could have been a longer string, the behaviour remains the same).

Does this mean that we can not render multiple markers on a single line if all of them are `{inclusiveRight: true, inclusiveLeft: true}`?

**Comment by marijnh** [comment]
Oh, if they are not touching this should definitely be valid. I'll look into this later.

**Comment by marijnh** [comment]
Found it. See attached patch.

**Comment by brrd** [comment]
@marijnh thank you
