### ISSUE TITLE
Manual resizing only works in Firefox

### ISSUE THREAD

**Issue by kireerik** [codemirror/CodeMirror#3999]
Using the following CSS style is only works in Firefox:
```
.CodeMirror {
	resize: horizontal;
}
```

Related issue: #850

**Comment by marijnh** [comment]
And even there, it'll cause problems. This isn't something this library aims to support -- if you really want resize handles, you have to write them yourselves and ensure you call `setSize` when changing the editor's size.

**Comment by kireerik** [comment]
Thank you for your feedback!

I thought this is a code editor based on HTML `textarea` elements. Textareas have [resizable](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) feature. So why not this library aims to support this?
Also why works this in Firefox, but not in other browsers. I think this is inconsistent. What is your opinion about this?

Thank you for your reply in advance!
