### ISSUE TITLE
[clike-mode] Unusual indentation after start of template

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4001]
It's pretty common (cf http://asawicki.info/news_1607_syntax_of_c_templates_-_comparison.html) to write out the templates involved in a method/class/etc one per line, all at the same indentation level. C-like mode by default adds an indentation level after a template declaration like `template <int T>`. Is there some parameter to pass to the mode to stop this? Or alternatively, can the mode be made to not add an indentation level in this case? I've not really seen code in the wild where it would be appropriate.

**Comment by marijnh** [comment]
Could you see if attached patch improves the situation?

**Comment by mtaran-google** [comment]
Yes, it does. Thanks!
