### ISSUE TITLE
readOnly option does not seem to work

### ISSUE THREAD

**Issue by criso** [codemirror/CodeMirror#4005]
https://jsfiddle.net/Sk8erPeter/TcqAf/

This is a sample jsfiddle that I've found. In local testing this seems broken to me as well.

**Comment by marijnh** [comment]
There are no CodeMirror instances on that jsfiddle because the includes aren't working (at least, Chrome and Firefox block the scripts). Open the browser console to see the errors below. The lack of highlighting might have also given away that there's a problem.

```
Blocked loading mixed active content "http://codemirror.net/lib/codemirror.css"[Learn More] TcqAf
Blocked loading mixed active content "http://codemirror.net/lib/codemirror.js"[Learn More] TcqAf
Blocked loading mixed active content "http://codemirror.net/addon/edit/matchbrackets.js"[Learn More] TcqAf
Blocked loading mixed active content "http://codemirror.net/addon/edit/continuecomment.js"[Learn More] TcqAf
Blocked loading mixed active content "http://codemirror.net/mode/javascript/javascript.js"[Learn More] TcqAf
ReferenceError: CodeMirror is not defined
```

**Comment by criso** [comment]
Whelp... that was awful. Sorry to have wasted your time. 
Adjusted links and things work. 
So, I'm probably in the middle of some kind of reactjs drama. Thanks for looking into this so quickly!
