### ISSUE TITLE
Double click (dblclick) event does not always fire

### ISSUE THREAD

**Issue by barelyfitz** [codemirror/CodeMirror#4010]
I was trying to use the double click (dblclick) event, but it does not seem to fire reliably. 

The following example shows mousedown and dblclick events, and when I test in Chrome browser I sometimes get two mousedown events followed by a double click event (as expected) but other times I just get the mousedown events without the double click event.

https://jsfiddle.net/patmfitz/brq96tme/3/

This particularly seems to happen when you rapidly perform a double click followed by another. It also appears to possibly be tied to the CodeMirror behavior where double clicking toggles the selection between selecting a word and a full line.

![codemirror_endstyle_problem_-_jsfiddle](https://cloud.githubusercontent.com/assets/185461/15019439/0899cef4-11ec-11e6-8a0e-8092152af804.png)

**Comment by marijnh** [comment]
CodeMirror will `preventDefault` most `mousedown` events, so indeed, the browser's `dblclick` will not fire reliably. That's a side effect that can't be helped.

**Comment by barelyfitz** [comment]
According to the CodeMirror documentation, under "Events" it shows a "dblclick" event, so I assume this means that event is not actually supported?

In any case I have tried to work around this by implementing my own double click detection using the mousedown event. Perhaps something similar can be done within CodeMirror itself to provide a reliable dblclick event.

    // CodeMirror's dblclick event doesn't work reliably,
    // so have to provide our own double click detection
    clicks = 0;
    editor.on('mousedown', function(instance, event) {
        clicks++;
        if (clicks == 1) {
            setTimeout(function(){
                if (clicks > 1) {
                    // Trigger double click now!
                }
                clicks = 0;
            }, 300);
        }
    });

**Comment by marijnh** [comment]
> According to the CodeMirror documentation, under "Events" it shows a "dblclick" event, so I assume this means that event is not actually supported (reliably)?

The browser events are documented as simply forwarding native browser events, giving client code a chance to register custom handlers with higher priority than CodeMirror's built-in behavior. If the browser doesn't fire these, neither will CodeMirror.
