### ISSUE TITLE
Markdown href highlighting is not greedy enough

### ISSUE THREAD

**Issue by jaredleechn** [codemirror/CodeMirror#4013]
![image](https://cloud.githubusercontent.com/assets/5318333/15044308/5f83775e-1306-11e6-92ff-458ef5b28c37.png)

```
![image](http://abcde.png()xyz)
```

only the last `)` should be treated as the end of the tag, I think CM should pattern `)` greedly for hrefs

maybe something like `.*(\))`

refs: https://github.com/codemirror/CodeMirror/blob/master/mode/markdown/markdown.js#L677

**Comment by jaredleechn** [comment]
very appreciate 👍

success with `![image](http://abcde.png()xyz)` 

but fail with `![image](http://abcde.png)))xyz)`

![image](https://cloud.githubusercontent.com/assets/5318333/15067519/8f3e75aa-13a3-11e6-8acc-b81ce116eb19.png)

giving a most complex case:

```
![aaaa](http://services.puml.net/g?
  @startuml
  start
    skinparam shadowing false
  if (multiprocessor?) then (yes)
    fork
      :Treatment 1;
    fork again
      :Treatment 2;
    end fork
  else (monoproc)
    :Treatment 1;
    :Treatment 2;
  endif
  stop
@enduml)
```

**Comment by marijnh** [comment]
> but fail with `![image](http://abcde.png)))xyz)`

Yes, the [spec](http://spec.commonmark.org/0.25/#link-destination) requires us to match only balanced parentheses within a URL. Otherwise, the grammar would be way too ambiguous, and you'd often get problems the other way around -- matching too much.
