### ISSUE TITLE
Hints are behind the editor (z-index issue ?)

### ISSUE THREAD

**Issue by MG73** [codemirror/CodeMirror#4017]
Hi, I'm using codemirror in a dialog window of elfinder (www.elfinder.org).
All works correctly except for the autocomplete hints thar are displayed behind the window containing the codemirror editor...
I put 
`.codeMirror-hints, .CodeMirror-hint, .CodeMirror-hint-active {  z-index:9999999999 !important; }` with no luck...
Help please, thanks

**Comment by marijnh** [comment]
If you want us to look at it, reduce the problem to a minimal HTML file. You're likely to already find the issue yourself if you do that. I'm not going to dig through your application to try and figure out what's going on.
