### ISSUE TITLE
Error in xml-fold

### ISSUE THREAD

**Issue by Gvx-** [codemirror/CodeMirror#4018]
xml-fold generates an error when
`cm.doc.setValue('<!-- anything -->');`

The Firebird console displays this
```
TypeError: iter.text is undefined
      var gt = iter.text.indexOf(">", iter.ch);
```
This line is in
`function toTagEnd`

**Comment by marijnh** [comment]
I'm not seeing this happen when running `editor_html.setValue('<!-- anything -->')` in [this demo](http://codemirror.net/demo/folding.html). What else is required to reproduce it?

**Comment by Gvx-** [comment]
It must be added the addon "matchtags.js" to reproduce the defect

The following code to reproduce the error.

1 / Change textarea
2 / Click the "reset"

result: error

```
<html>
	<head>
		<meta charset="utf-8">
		<title>codemirror</title>
		<link rel="stylesheet" href="codemirror/codemirror.css">
		<script src="codemirror/codemirror.js"></script>
		<script src="codemirror/matchtags.js"></script>
		<script src="codemirror/xml-fold.js"></script>
	<head>
	<body>
		<form>
			<textarea id="code" name="code"></textarea></div>
			<input type="reset" id="reset" value="reset" />
		</form>
		<script type="text/javascript">
			var cm_options = {						// codemirror options
				mode: 'text/html',
				tabSize: 2,
				tabMode: 'indent',
				matchTags: { bothTags: true }
			},
			el= document.getElementById('code'),
			reset = document.getElementById('reset'),
			cm = CodeMirror.fromTextArea(el, cm_options);
			cm.focus();
			cm.doc.setValue('<!-- anything -->');	// OK
			reset.onclick = function() {
				cm.doc.setValue('<!-- anything -->');		// Fail
			}
		</script>
	</body>
</html>

```
[index.zip](https://github.com/codemirror/CodeMirror/files/259127/index.zip)

**Comment by marijnh** [comment]
You index doesn't trigger the error for me either. It also doesn't include `xml.js`, making the `xml-fold` addon do pretty much nothing. But even if I add that, I'm not getting the problem. Are you sure you're using an up-to-date CodeMirror version?

**Comment by Gvx-** [comment]
I use the 5.14.2 release.
Adding xml.js does not solve the problem.
See attached capture.

![capture](https://cloud.githubusercontent.com/assets/10295261/15334152/410505a2-1c6d-11e6-9d4f-d190c52bf77a.PNG)

**Comment by marijnh** [comment]
The problem right now is that I can't reproduce this, and thus can't debug it.

**Comment by alexwerser** [comment]
A year ago, I faced with this. I decided very simply
replace `var gt = iter.text.indexOf(">", iter.ch);`
to `var gt = iter.text ? iter.text.indexOf(">", iter.ch) : -1;`
Since it is made in the following function "toTagStart"

**Comment by dragon-dreamer** [comment]
I can reproduce the issue. You need tag matching be turned on to reproduce it. Take a look at this example, I've added just a single line `editor.setValue("<!--");` to default `matchtags.html` demo:

```
<!doctype html>

<title>CodeMirror: Tag Matcher Demo</title>
<meta charset="utf-8"/>
<link rel=stylesheet href="../doc/docs.css">

<link rel="stylesheet" href="../lib/codemirror.css">
<script src="../lib/codemirror.js"></script>
<script src="../addon/fold/xml-fold.js"></script>
<script src="../addon/edit/matchtags.js"></script>
<script src="../mode/xml/xml.js"></script>
<style type="text/css">
      .CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}
    </style>
<div id=nav>
  <a href="http://codemirror.net"><h1>CodeMirror</h1><img id=logo src="../doc/logo.png"></a>

  <ul>
    <li><a href="../index.html">Home</a>
    <li><a href="../doc/manual.html">Manual</a>
    <li><a href="https://github.com/codemirror/codemirror">Code</a>
  </ul>
  <ul>
    <li><a class=active href="#">Tag Matcher</a>
  </ul>
</div>

<article>
<h2>Tag Matcher Demo</h2>


    <div id="editor"></div>

    <script>
window.onload = function() {
  editor = CodeMirror(document.getElementById("editor"), {
    value: "<html>\n  " + document.documentElement.innerHTML + "\n</html>",
    mode: "text/html",
    matchTags: {bothTags: true},
    extraKeys: {"Ctrl-J": "toMatchingTag"}
  });
  
  editor.setValue("<!--");
};
    </script>

    <p>Put the cursor on or inside a pair of tags to highlight them.
    Press Ctrl-J to jump to the tag that matches the one under the
    cursor.</p>
  </article>
```
