### ISSUE TITLE
Attempting to view a long file triggers unresponsive script alerts

### ISSUE THREAD

**Issue by 2is10** [codemirror/CodeMirror#4021]
Building the initial document tree can take minutes in Chrome and 8-9 seconds in Safari and Firefox for a file with 3 million short lines, even with line wrapping disabled. Unresponsive script alerts appear in Chrome and Firefox.

I understand that this project may not be interested in supporting files of this size, but it turns out that not much code needs to change to bring all three browsers down to a 2-3 second range, and the speedup should also apply to operations on smaller files, especially on devices with less CPU and memory available. I’ll send a pull request momentarily.

Mac OS X El Capitan 10.11.2 (15C50)
Chrome 51.0.2704.36 beta (64-bit)
Firefox 46.0.1
Safari 9.0.2 (11601.3.9)

**Comment by 2is10** [comment]
Here are fiddles [**without the fix**](https://jsfiddle.net/sh183bjs/) and [**with the fix**](https://jsfiddle.net/oacbekvy/).

See the console log for running times. Here’s what I see:

```
           Original    With Fix
           ========    ========
Chrome      14.941s      1.824s
Firefox     19.440s      1.736s
Safari       6.101s      0.862s
```

**Comment by marijnh** [comment]
Thanks! See #4022
