### ISSUE TITLE
[sublime] Backspace for multi-cursor deletion broken for whitespace

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4023]
repro:
1. open https://codemirror.net/demo/sublime.html
2. put cursors right before the starting " marks on two lines
3. press backspace

expected:
both cursors delete one char before

actual:
only the main cursor deletes one char before

**Comment by marijnh** [comment]
Fixed by reverting 8dbb84f4

**Comment by mtaran-google** [comment]
smart backspace is a good idea overall -- why not just apply it to all cursors?

**Comment by marijnh** [comment]
I am not seeing this happen with by default in Sublime Text, and I currently have more pressing things to do than redoing people's pull requests. If someone wants to submit a proper implementation that'd be welcome, though.
