### ISSUE TITLE
Color of warning and errors while hovering over the marker

### ISSUE THREAD

**Issue by karuppiah7890** [codemirror/CodeMirror#4025]
It's really tough to see the "infotext" color on "infobackground" color. Why not just make the color as black on infobackground in the lint.css file ?

**Comment by marijnh** [comment]
It was black on my system, but I guess that's not something you can rely on. Attached patch sets explicit colors.

**Comment by karuppiah7890** [comment]
Okay!

**Comment by karuppiah7890** [comment]
I just noticed that you are the author of the book "Eloquent JavaScript" that I have just started reading! Great to see you! :)

**Comment by mihailik** [comment]
Funny enough, author's name on the cover page is `infotext` on yellow as well ;-)

![Eloquent JavaScript cover](http://eloquentjavascript.net/img/cover.png)

**Comment by karuppiah7890** [comment]
Hehe :P
