### ISSUE TITLE
[Python mode] Bad indent in 'electric char' mode ?

### ISSUE THREAD

**Issue by Carreau** [codemirror/CodeMirror#4027]
with `|` being the cursor, in the following example the new line will have 8 whitespace:
```python
minimize(0,
         1,
         2,|)
```
leading to 
```
minimize(0,
         1,
         2,
        |)
```

```
minimize(0,
         1,
         2,
        this_will_not_be_alligned)
```

While the following will lead to 9:

```
```python
minimize(0,
         1,
         2,|
        )
```
leading to 

```python
minimize(0,
         1,
         2,
         |
        )
```

```python
minimize(0,
         1,
         2,
         this_will_be_aligned|
        )
```

my **guess** is this is due to an effort in aligning close parenthesis with opening one, it seem to annoy some python user. 

I might have a look at the python mode, but just opening the issue before I forget. 

Thanks.

**Comment by marijnh** [comment]
This is intended behavior. The user can press shift-tab to realign. You'll get a similar effect if you press enter before a closing brace any a brace-based language.

**Comment by Carreau** [comment]
Ok, thanks, closing then.
