### ISSUE TITLE
Pasting using ctrl-v doesn't work in codemirror

### ISSUE THREAD

**Issue by yuanz1987** [codemirror/CodeMirror#4030]
It gives an error "codemirror.min.js:79 Uncaught TypeError: Cannot read property 'lineWise' of null"

You can try any demo example on codemirror website, for example http://codemirror.net/demo/activeline.html

Could you fix this soon? It breaks our product. Thanks.

**Comment by matthew-hayes** [comment]
I can't assign myself, but I will fix this and create a pull request -- we just need to fix the initialization of the new variable in https://github.com/codemirror/CodeMirror/commit/889098f1232a1223c52d5f0bbf1631b24b66e79f

**Comment by matthew-hayes** [comment]
Pull request: https://github.com/codemirror/CodeMirror/pull/4031
