### ISSUE TITLE
Caret looks weird on Firefox 48

### ISSUE THREAD

**Issue by captainbrosset** [codemirror/CodeMirror#4039]
Steps to reproduce:
- Open http://codemirror.net/ on Firefox 48
- Click inside the demo codemirror code area
- (you might need to wait a little bit for the cursor to blink a few times, not sure about that step)
- The cursor gets a 2 or 3px rectangle next to it that blinks too.

![caret](https://cloud.githubusercontent.com/assets/1152698/15666473/2ae5f5d4-2711-11e6-9b56-494c49c0c6a6.gif)

Using devtools, I saw that codemirror used a textarea where the cursor is (I guess to receive text inputs), and that what we see in the screen capture above is the textarea.
On Mac, it's a little more of a problem, because the default focus style is a thick blue outline, so it makes the problem more visible:

![stylesheet](https://cloud.githubusercontent.com/assets/1152698/15666513/71eff128-2711-11e6-98cb-07310b46cffc.gif)

The above screen capture was taken in Firefox DevTools, where codemirror is used.

Adding `border:none` to the textarea helps a little (at least on windows), but you can still see the second caret (the one in the textarea) blink next to the codemirror one.

**Comment by marijnh** [comment]
Are you sure that what you're seeing is the textarea? That definitely shouldn't blink (the CSS changes that cause the cursor blinking are applied to a completely different element), so I can't explain why the box in your videos is blinking along with the cursor.

**Comment by marijnh** [comment]
Also, since 48 is not even beta yet, maybe file a report with Firefox about this first, and see if they fix it? If they've made focused textareas un-hideable, that's not something we're going to be able to work around.

**Comment by captainbrosset** [comment]
Closing as this is indeed a Firefox 48 issue. Sorry for the noise.
https://bugzilla.mozilla.org/show_bug.cgi?id=1276467

**Comment by marijnh** [comment]
Thanks for finding the corresponding Firefox issue. Let's see if it gets fixed.

**Comment by yukulele** [comment]
`opacity: 0` fix it
