### ISSUE TITLE
heightAtLine or any line's top position which out of viewport might not accurate

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#4045]
Sorry it's a bit complicated, I will try to explain it all.

1. you need set `wrapLine` true and `viewport` not Infinity and also use `simplescrollbar`
2. pre-make some lines that will be wrapped over and many enough to out of viewport.
3. don't even scroll to those lines and check the heightAtLine on the lines that out of the viewport.
4. You will find out that their height are not very accurate, may lack 1 or 2 lines height.

I don't know how CodeMIrror measure the line height which out of the viewport (not loaded into the DOM yet), but this API is really important to me.
Thanks for helping!

**Comment by marijnh** [comment]
This is by design -- until a line is actually rendered, its height is an approximation of its real height. There's no way around this except for rendering all lines right away, which would completely defeat the lazy-rendering optimization.

**Comment by jackycute** [comment]
Thanks for explanation :smile:
