### ISSUE TITLE
Closebrackets deletion behavior problem

### ISSUE THREAD

**Issue by clockworked247** [codemirror/CodeMirror#4047]
Code:
```
var a = function(i) { return i; };
var b = function(j) { return j; };
console.log(a( b() ));
```
Steps:
1) Place cursor in the line "console.log(a( b() ));" to the left of the right-most paren
2) Backspace until the cursor reached "b("
3) Press Backspace one more time - both the "(" to the left of the cursor and the ")" to the right of the cursor are deleted.

Expected behavior:
The paren to the right of the cursor should not be deleted.

**Comment by marijnh** [comment]
The closebrackets addon is a simple helper, not a clever intention-guessing machine. For what it's worth, Sublime Text behaves the same way. Doing something more advanced is out of scope for my addon (feel free, of course, to implement a more refined alternative addon yourself)
