### ISSUE TITLE
AutoCloseBracket doesn't work on double quotes in some mode

### ISSUE THREAD

**Issue by MissChocoe** [codemirror/CodeMirror#4052]
I tried it on the markdown, xml and on my own mode and in those modes it didn't work. It does work for (,[ and {. 

In javascript it works, but it ignores the string we give it in parameters so I suspect it does some magic on its on.

It also works on css mode.

**Comment by marijnh** [comment]
These require the quoted thing to be tokenized as a string, which generally only happens in programming-type modes.

**Comment by MissChocoe** [comment]
Oh thanks! Now I know how to make them work. Sorry about the false bug report.

**Comment by marijnh** [comment]
No problem! It _is_ confusing, it's just that the closebrackets addon is such a delicate mess of hacks that I'm not terribly motivated to try and further change its behavior.
