### ISSUE TITLE
Question: Can we update the existing widget (markText and Bookmark) position?

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#4055]
Hi, I have question.
I've look up the manual for a while.
But I couldn't find any method that can update the position (from, to) of the existing widget (markText and Bookmark).
Did I miss anything?

It would be really great if we can have that method, then we could update the existing widget without remove/add one.

Thanks for helping!

**Comment by marijnh** [comment]
No, you should delete and re-create your marked range or bookmark.
