### ISSUE TITLE
JSON syntax highlight issue

### ISSUE THREAD

**Issue by tylerlong** [codemirror/CodeMirror#4060]
Take this JSON file for example: http://petstore.swagger.io/v2/swagger.json

Copy and paste the text to https://codemirror.net/demo/theme.html

Only the first half of the text is highlighted.

**Comment by marijnh** [comment]
You're seeing the behavior of the [`maxHighlightLength`](http://codemirror.net/doc/manual.html#option_maxHighlightLength) option, which you can change.
