### ISSUE TITLE
brace-fold doesn't seam to work on css and less files.

### ISSUE THREAD

**Issue by pynej** [codemirror/CodeMirror#4061]
I see same ``fold: "brace"`` line in ``mode/css.js`` that the javascript one has, but in css mode the gutter is added but no folding points are found.

**Comment by marijnh** [comment]
Works for me. Are you sure you loaded the brace-fold addon?

**Comment by pynej** [comment]
Him, I had the brace-fold and fold-gutter.  Maybe the documentation(demo/folding.html) just needs a sample added for css.

**Comment by marijnh** [comment]
What I did to try this out was nothing more than including the CSS mode in demo/folding.html, and setting the mode of the first editor to `"css"`.
