### ISSUE TITLE
Shortcuts interfering with typing characters

### ISSUE THREAD

**Issue by Leandros** [codemirror/CodeMirror#4066]
#### Description:

CodeMirror doesn't allow me to type the character `#`, it's erroneously interpreting the keystroke as `option+f` `/ ⌥ + F`.
#### Steps to reproduce:
- Install and activate [attached keyboard layout](https://github.com/codemirror/CodeMirror/files/309985/files.tar.gz) ([How to install a custom keyboard layout on OS X](http://superuser.com/questions/665494/how-to-make-a-custom-keyboard-layout-in-os-x))
- Open http://codemirror.net
- Press Option + Z (US keyboard) / Option + Y (DE keyboard)

_For verification, open any other text document and press said keys, to see the expected result_
#### Result:

Inputting the `#` character, instead of jumping forwards.
#### Additional information:

Bug found on OS X, using Chrome (any version) or Safari (any version). I haven't tested Firefox, but I'm assuming the situation will be very similar.

**Comment by Leandros** [comment]
My investigations lead me to the [`emacs.js`](http://codemirror.net/keymap/emacs.js) keybindings, which define the keybind `ALT+F` and `ALT+B` for moving a word forward and backwards. I'm assuming disabling the former of these binds will fix the issue.

**Comment by marijnh** [comment]
Yes -- keymaps can be configured, and by default the editor isn't binding Alt-F.

Browsers do not provide a way for JavaScript to inspect keyboard layout or user-defined bindings, so our options for handling this are very limited. I'm not sure why your OS/Browser ends up firing a key event with altKey set to true and F's keycode in this case, but once it does, there's no way for JavaScript code to distinguish it from a real Alt-F press.

**Comment by adrianheine** [comment]
Ok, apparently this is something we have to accept, so I am closing this issue.
