### ISSUE TITLE
hard wrapping sample inconsistent behavior

### ISSUE THREAD

**Issue by nlight-dev** [codemirror/CodeMirror#4069]
Trying the sample at https://codemirror.net/demo/hardwrap.html, it adds a space at the beginning of every next line and generates inconsistent behavior when pasting multiple lines of text.
Pasting below text and then typing another character(i.e. "s") at the end:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890

Results in:
123456789012345678901234567890123456789012345678901234567890
 12345678901234567890123456789012345678901234567890123456789
0
123456789012345678901234567890123456789012345678901234567890
s

**Comment by marijnh** [comment]
Attached patch seems to help.

**Comment by nlight-dev** [comment]
@marijnh, thanks for the patch, it seems to work better as it doesn't add prefix spaces anymore.
One other issue is that it doesn't preserve spaces and enters. Could you take a look at that as well?

For example:
123
456
will become:
123 456 - when wrap is applied, it removes the enters and brings everything on same line

Also the spaces are not preserved. I'm hoping for a behavior closer to native text areas with hard wrap enabled.

Thank you!

**Comment by marijnh** [comment]
> One other issue is that it doesn't preserve spaces and enters.

Of course. That's what this addon does -- it takes a block of text and adjusts its newlines so that it's 'filling' the available columns. It doesn't distinguish between newlines it inserted and newlines inserted by the user.
