### ISSUE TITLE
SVG Highlighting?

### ISSUE THREAD

**Issue by Jolg42** [codemirror/CodeMirror#4070]
Hi!

First, this is a great project 👍 😃

I'm just opening this issue to ask you if you plan to support an SVG highlighting?

**Comment by marijnh** [comment]
Nope, I [don't write modes on demand](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list), but the XML mode will probably get you a long way for SVG.

**Comment by Jolg42** [comment]
Thanks for your response & link!
