### ISSUE TITLE
Opaque performance issue using `.setValue`

### ISSUE THREAD

**Issue by den1k** [codemirror/CodeMirror#4076]
In two separate applications that both make use of `.setValue`, Codemirror **calls different functions internally**.
It's unclear to me why the performance is so radically different. I removed all calls to other functions and am now only calling `.setValue`.

The one thing that is different in both applications are the CSS styles. One uses flexbox, the other fixed heights.

Here is the call-chain of functions called in either version. Can upload profiles as well. @marijnh any ideas?

FAST:

* anonymous
  * anonymous
    * makeChange
      * makeChangeInner
        * makeChangeSingleDoc
          * makeChangeSingleDocInEditor
            * startWorker
              * Delayed.set
                * setTimeout
  * endOperation
    * endOperations
      * endOperation_W1
        * updateDisplayIfNeeded
          * patchDisplay
            * updateForLineChanges
              * updateLineText
                * getLineContent
                  * buildLineContent
                * replaceChild
       * endOperationR2
         * updateHeightsInViewport (selftime: 0.9 ms)

Total Duration: 2.6 ms

SLOW:

* anonymous
  * anonymous
    * makeChange
      * filterChange
        * Codemirror.signal
      * makeChangeInner
        * computeSelAfterChange
          * normalizeSelection
        * addChangeToHistory
          * historyChangeFromChange
            * attachLocalSpans
      * makeChangeSingleDoc
        * makeChangeSingleDocInEditor
          * estimateHeight (selftime: 202 ms)
  * endOperation
    * endOperations
      * endOperation_R2
        * updateHeightsInViewport (selftime: 215 ms)
      * endOperation_finish
        * postUpdateDisplay
          * displayWidth (selftime: 230 ms)

Total Duration: 650 ms

**Comment by den1k** [comment]
The problem was that the Codemirror editor instance's height css property was set to `inherit`. Once we set a fixed height, we got back to FAST speed. A 600 ms slowdown still seems out of ordinary, so I'm leaving this issue open.

**Comment by marijnh** [comment]
CodeMirror achieves its performance by only drawing the part of the DOM that's currently visible. If you make it resize with its content, the whole document will end up visible, and that is going to be a lot more expensive. That's not something that can be helped.

**Comment by den1k** [comment]
@marijnh Resizing is not the issue. It seems that if none of the editor-wrapping instance have a fixed height, i.e. when using flexbox everywhere, codemirror performs different operations than with fixed styles. (I'm putting a note down to prepare and example with the issue this weekend.)

**Comment by edg2s** [comment]
Even with height:auto you can work out which parts of the DOM are visible using viewport dimensions and scroll offset. Where in the code is this computed for fixed height editors?

**Comment by redlolgeerf** [comment]
i've encountered the same problem with very slow updateHeightsInViewport. are there any workarounds?

**Comment by den1k** [comment]
Use fixed width and height on the container of the editor element.

**Comment by redlolgeerf** [comment]
I've tried to set fixed width and height on the parent of the div with class "CodeMirror", but nothing changed. "updateHeightsInViewport" and "displayWidth" are still very slow.

**Comment by marijnh** [comment]
Do you have `vierportMargin` set to a large number?

**Comment by redlolgeerf** [comment]
I have not set vierportMargin.

**Comment by edg2s** [comment]
> If you make it resize with its content, the whole document will end up visible, and that is going to be a lot more expensive. That's not something that can be helped.

This is the part I was replying to - for very long documents only the part of the document in the viewport needs to be rendered. We are integrating CodeMirror highlighting on Wikipedia pages (https://phabricator.wikimedia.org/T161054). Our new editor doesn't use a fixed height text input, but an autosized one with a floating toolbar. It should be fairly easy to modify the code to use the viewport height/scroll offsets for computing which part is visible, instead of the CodeMirror container? We'd be glad to help if you have any pointers.

**Comment by marijnh** [comment]
> It should be fairly easy to modify the code to use the viewport height/scroll offsets for computing which part is visible,

Unfortunately, no. To ensure that things are drawn before they are scrolled into view, CodeMirror uses a [very involved scrolling model](http://marijnhaverbeke.nl/blog/a-pathological-scrolling-model.html) for its container.

**Comment by edg2s** [comment]
> To ensure that things are drawn before they are scrolled into view

Could it work if you allowed users to drop that requirement?

**Comment by marijnh** [comment]
> Could it work if you allowed users to drop that requirement?

Probably, yes. It'd still require changes to some of the more fragile/scary parts of the library, but it should be possible.
