### ISSUE TITLE
[markdown mode] <tags> break formatting

### ISSUE THREAD

**Issue by HoverBaum** [codemirror/CodeMirror#4077]
In the markdown mode using any `<tag>` that is to say something with an opening `<` and closing `>` breaks the formatting of following text.

The [markdown mode on the codemirror website](http://codemirror.net/mode/markdown/) gives me this 'broken' formatting.
![What I see](https://cloud.githubusercontent.com/assets/7557414/16181670/02f7171e-36d0-11e6-969c-9ff03ff95ff8.png)

Here is an example from a different editor showing what I would expect.
![What I would expect to see](https://cloud.githubusercontent.com/assets/7557414/16181672/05f0a85e-36d0-11e6-96af-5464c4ffbb2c.png)

I am on Windows 7 using Google Chrome 51.0.2704.84

**Comment by marijnh** [comment]
Markdown allows inline HTML, and the CodeMirror mode supports this. So your `<h1>` probably doesn't mean what you think it does -- it starts an inline HTML tag, and you have to escape the opening `<` with a backslash to insert the less-than character literally.

**Comment by HoverBaum** [comment]
Ahh looks like I didn't fully think this through, you are absolutely right.
