### ISSUE TITLE
Show-hint overflow in 5.16

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#4080]
Commit df3a0ae0fb7876a4ef58c324878e6eea03b0d66f introduced `max-width: 19em;` to the `.CodeMirror-hints` class, and removed it from the `.CodeMirror-hint` class.

If any user of the dialog has previously styled the dialog with some `width` value, it now has to fight the `max-width` declaration, too. In my app this caused a lot of font overlapping:

![screenshot 2016-06-22 14 17 55](https://cloud.githubusercontent.com/assets/613320/16284071/46d7b096-3884-11e6-8118-7e1da2f78c2a.png)

I sort of get why this change was made, but would it be simpler to just have a normal width declaration?

**Comment by marijnh** [comment]
A plain width property would, depending on the value we give it, either always make the dialog huge, or make it needlessly small for short hints. I don't like that solution very much either. Doesn't just setting `max-width: none` in your CSS provide a proper solution?

**Comment by vincentwoo** [comment]
It does, but it also feels like a bit of a hack. Is no max-width at all a sane default for CodeMirror? If not, why not a much higher one?
