### ISSUE TITLE
markText range not caught by coordsChar when using replacedWith

### ISSUE THREAD

**Issue by RobertDiebels** [codemirror/CodeMirror#4081]
Using this issue as an example: https://github.com/codemirror/CodeMirror/issues/3529

I implemented auto-completion functionality that marks a range of text. and uses replacedWith to replace it with a node.
Now using the code from the issue above I click on the mark but to my surprise I find that coordsChar does not register the node in terms of chars. It basically divides the marker, or in this case the node element I used in replacedWith, in two.

When I click on the marker coordsChar only returns me a position with a ch range of the starting position of the marker to that position + 1.

However when I don't use replacedWith for the marker everything is fine.

The reason this is important is because I use the range of the marker to determine whether or not to show some additional information when that marker is clicked. For instance I don't want to show that information when you click right next to the marker because you could also want to start typing there.

Most important thing here is that coordsChar basically chops up the replacedWith node. Only registering the node as a range of (line.ch, line.ch+1). And as I don't want to show anything when you click right next to the marker I have a problem.

If anyone can shed some light on this that would be great. If you need any other information I would be happy to supply it.

P.S. I tried making a fiddle but I couldn't get it to work properly.

**Comment by marijnh** [comment]
The `replaceWith` option implies the `atomic` option, i.e. when you use that the existing content is no longer in the view, and is represented by a single replacement node. CodeMirror does not know what that node represents. It sounds like you're replacing it with equivalent text, but there's no way for the library to know this, so it can only treat it as a single opaque element.
