### ISSUE TITLE
[Markdown] wrong headings recognized

### ISSUE THREAD

**Issue by lukasoppermann** [codemirror/CodeMirror#4083]
Hey,

I just noticed that both of the following are recognised as a heading.

```markdown
# actual heading

#wrong heading
```

However, the second is not mentioned in the official markdown syntax and is explicitly mentioned to produce a `<p>` in [commonmark](http://spec.commonmark.org/0.25/#example-32).

Could yo maybe change it? This is a problem for me, because the editor shows something as a headline now, which will not be a headline when saved, as I am using the php commonmark package, which parses markdown according to commonmark standards.

Thanks.

**Comment by marijnh** [comment]
There's an `allowAtxHeaderWithoutSpace` in the markdown mode to accept these, but it defaults to off, and that's also the behavior I'm seeing on http://codemirror.net/mode/markdown/ . Could it be that you're using an old version or have this explicitly enabled?

**Comment by lukasoppermann** [comment]
Thank you, I was using an old version, due to some package dependency issues.
