### ISSUE TITLE
Windows/Chrome: Japanese IME suggestion list obscures inputted text

### ISSUE THREAD

**Issue by MickMonaghan** [codemirror/CodeMirror#4089]
**Env**
Windows 10
Chrome v51
Japanese MS IME
CodeMirror: v5.13.2 (also exists in v5.16 - and earlier versions)

**To reproduce:**
- Open a code mirror mirror input area
- activate the Japanese IME
- type "nippon"
- suggestion list appears

**Expected Result:**
- list does not obscure the text that has been entered

**Actual Result:**
- text is significantly obscured.
  ![cm-jaime-obscurestext](https://cloud.githubusercontent.com/assets/16923626/16385824/53d2c3d6-3c5c-11e6-8fc2-3d4b81d60807.png)

**Comment by marijnh** [comment]
I booted windows 7 and enabled Microsoft Japanese IME, and it's allowing me to type Japanese characters, but never pops up a suggestion list (neither in CodeMirror nor anywhere else). Is there something else I need to enable to get that behavior?

**Comment by marijnh** [comment]
Oh, it was pressing space that triggered the menu. Unfortunately, on my system, both in Linux and Windows 7, the resulting widget is perfectly aligned with the bottom of the cursor. This might be related to your CSS -- could you see if it happens on the demo pages on http://codemirror.net on your system? If not, it would be helpful if you could set up a minimal demo page with your CSS in it that allows me to reproduce the issue.

**Comment by marijnh** [comment]
On closer look at the screenshot, that _is_ the project page, so I'll see if I can install windows 10 to see if it reproduces there.

**Comment by marijnh** [comment]
Okay, on Windows 10 with Chrome 51 I could reproduce this. Attached patch works around the issue.

**Comment by marijnh** [comment]
Um, I mean patch 51a1e7d, which I attached to the wrong issue.

**Comment by MickMonaghan** [comment]
Excellent @marijnh - thank you. Looks good to me also.

**Comment by adrianheine** [comment]
Apparently this is fixed, great!
