### ISSUE TITLE
Pasted content is lost after char insertion, when using contentEditable on IE11

### ISSUE THREAD

**Issue by schanzer** [codemirror/CodeMirror#4091]
TO REPRODUCE:
Take any stock mode, and change the input type to contentEditable
In IE11 (tested on win 8.1), paste some content into an empty editor, then hit the space bar (or any key)

EXPECTED:
A space (or the character pressed) appears after the pasted content

ACTUAL:
The pasted content disappears! (the added char remains)

**Comment by schanzer** [comment]
I know you've got a huge amount of work going on, so I hope this doesn't come across as pestering. I wonder, however, if there's a way I might up my monthly contribution as a way of upvoting this bug? As a consumer of this library, it's only reasonable that I pay for your time. *smile*

**Comment by marijnh** [comment]
Could you see if attached patch helps?

**Comment by schanzer** [comment]
It appears to fix things on my IE11 VM - let me do some more testing when I can get my hands on a real machine and post back in 24 hours. Thanks for looking into this!

**Comment by schanzer** [comment]
No dice. :(

I've put up a [test instance](http://www.bootstrapworld.org/preview/testing/codemirror2/mode/scheme/) using the stock Scheme mode and a pull from https://github.com/codemirror/CodeMirror/commit/fafb7dc17d45d24ef5e84d3f61696ae9a4ea28fd. To reproduce (confirmed on IE11.0.9600.18376 and 11.494.10586.0):

* Open the URL: http://www.bootstrapworld.org/preview/testing/codemirror2/mode/scheme/
* Locate the line beginning with `(define BACKGROUND (bitmap/url "...`, and select the contents of the quoted string (the URL)
* Open a new tab and go to any URL. Then copy the URL from the address bar
* Return to the first tab, and paste the clipboard URL on top of the selected URL. Then hit the space bar.

Sometimes the pasted URL disappears, and sometimes it disappears the the old URL comes back.

Toggling `inputStyle` turns this behavior on and off.

**Comment by marijnh** [comment]
I messed up my fix (and somehow, it looked like it worked when I tried it). Attached patch should make it actually do what it was supposed to do.

**Comment by schanzer** [comment]
Confirmed fixed! Thanks so much. Not sure what the right etiquette is for closing, so I'll leave this open until you want to shut it down.

**Comment by marijnh** [comment]
Great, I'll close.
