### ISSUE TITLE
Bug with measuring the size of a character + caret misplaced

### ISSUE THREAD

**Issue by firasdib** [codemirror/CodeMirror#4097]
I've found this bug where the function `charCoords` is telling me the size of a character is the entire line length. And in combination with this, the caret might end up on the very far right of the editor even if there are no characters there. Please see the images attached. 

Note that this is with line-wrapping enabled and the `mode` for `charCoords` is `local`!

1. Editor as normal, typing no problemo. 
<img width="969" alt="screen shot 2016-07-06 at 10 56 20" src="https://cloud.githubusercontent.com/assets/1335165/16612763/e849c6d2-4368-11e6-9b8f-c26cf0c18416.png">

2. Remove all characters until you reach the `!`. Note the caret on the far right.
<img width="974" alt="screen shot 2016-07-06 at 10 56 30" src="https://cloud.githubusercontent.com/assets/1335165/16612777/fbbc8a42-4368-11e6-9e16-687167d4694a.png">

3. Note the odd size of the `!` character (start and end rects), which it claims spans from `0-950px` (ie the entire line)
<img width="695" alt="screen shot 2016-07-06 at 10 58 06" src="https://cloud.githubusercontent.com/assets/1335165/16612793/1ace0d2a-4369-11e6-9741-237af7bae32d.png">

Thanks for maintaining Codemirror!

**Comment by firasdib** [comment]
You can test here: https://codemirror.net/demo/indentwrap.html

**Comment by marijnh** [comment]
I think attached patch helps. Could you confirm?

**Comment by firasdib** [comment]
Thanks, that fixed it @marijnh
