### ISSUE TITLE
Named imports with comma-dangle break syntax highlighting (JS)

### ISSUE THREAD

**Issue by petetnt** [codemirror/CodeMirror#4099]
Quite an edge case, but when doing named imports in ES201X syntax, JavaScript syntax breaks down if the import clause has dangling commas. Not sure if dangling commas are allowed in the spec in the first place, but Babel handles it without sweating and it interferes with `comma-dangle -> always` rule in ESLint used by for example https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base

Test it out on https://codemirror.net/mode/javascript/

### Works
``` js
import { 
  foo,
  bar
} from "bar";

foo
  .bar("biz bas boom")
  .then((foo, bar) => {
  
  })
```

### Breaks

``` js
import { 
  foo,
  bar,
} from "bar";

foo
  .bar("biz bas boom")
  .then((foo, bar) => {
  
  })
```

(The GitHub syntax highlighter seems to handle it though 😸 )

**Comment by marijnh** [comment]
Patch 31eb1b2f0b3 should help
