### ISSUE TITLE
cursor show in middle of two lines

### ISSUE THREAD

**Issue by eitty** [codemirror/CodeMirror#4102]
codemirror version: 5.16.0, mode: velocity
chrome version: 38.0.2125.101

On first loaded, text always cannot loaded entirely, and cursor can show in middle of two lines, cannot position where user want it be.
And after it loaded entirely(should wait some times), cursor work correctly.
Is there any proposal to fix this? Thanks lot for help.

**Comment by eitty** [comment]
and it happens mostly on linux, but little when windows 7

**Comment by eitty** [comment]
it seems work fine by refresh while scroll. Is there any better  proposal?
editor.on('scroll', function() {
    	editor.refresh();
    });

**Comment by marijnh** [comment]
Can you provide a minimal demo that reproduces this?

**Comment by eitty** [comment]
Okay, let me prepare and provide lately. Maybe next Monday.
Thanks for attention.

**Comment by eitty** [comment]
Sorry for late response. 
It is kind of cannot reproduce this in minimal demo. But I think it maybe due to our using method.
We didn't have content while init codemirror for textarea, but use setValue while different grid row being clicked.
And now, it can work fine by refresh while scroll, so I think can close it.
