### ISSUE TITLE
Syntax highlighting a URL (for a URL editor)

### ISSUE THREAD

**Issue by uuf6429** [codemirror/CodeMirror#4103]
It would be useful, in some scenarios, to have syntax highlighting when editing complex URLs (for example, for an API explorer).

Likewise, it would be useful to use it to display highlighted URLs (eg, when displaying payload details).

CodeMirror could easily do the job, given a mode (or one based on simple mode).

I'm considering doing this myself some time in the future (and ofc submitting a patch).

**Comment by marijnh** [comment]
I'm not taking mode feature requests (or even accepting new modes as contribution) -- but you could definitely set up your own repository with such a mode.
