### ISSUE TITLE
Embedded Python (in mixed mode) causes a display critical error

### ISSUE THREAD

**Issue by Frigory33** [codemirror/CodeMirror#4105]
Hi,
I'm using an HTML mixed mode where I can include code snippets with tags.
I write things like this:
```
<python>
# Some Python code
</python>
```
I don't keep an initial indentation for the Python code (according to the tag's position) as my renderer may keep the spaces before the lines (and I didn't develop it — :)).
Well, this code causes the display to crash: when you scroll to this line with the editor, it won't show anything any longer — it will be blank and the below too, but when you scroll back at the top, it works again.

Actually, it will work if you indent the lines according to the tag's position:
```
<python>
    # Indentation with the configured number of spaces
</python>
```
but if any line has less indentation than this ‘initial indent’ (four spaces here), it will throw a JavaScript error and make the editor become blank, from what I could see.
I could overcome the problem by replacing the content of the ‘dedent’ function in python.js with ``return false;`` (actually, I don't want the editor to detect wrong indentation).

I got this error with latest Firefox and Chromium, and I'm using CodeMirror 5.16.

Let me know if I missed a special technique.

**Comment by marijnh** [comment]
I think attached patch will help.

**Comment by Frigory33** [comment]
Thanks for your patch.
I think I tested something similar and had another error, but I'll only be able to test again on next week.
If it still doesn't work, I'll provide a minimal code so that you can test yourself. Did you already?

**Comment by Frigory33** [comment]
You were right, it doesn't crash anymore (but my indentation causes the lines' first word to be red thus I'll keep my solution for now — at least, the bug is fixed).
