### ISSUE TITLE
Get char at end of line

### ISSUE THREAD

**Issue by lukasoppermann** [codemirror/CodeMirror#4111]
Hey, I am trying to get the start and end of a selection. However if the selection is on multiple lines, I want to only get the start and end of line `n`.

However, using `editor.charCoords` I would need the `ch` value of the end of line `n`, using `getCursor` I can only (to may knowledge) get the `ch` value of the start of the selection and the end. But if the end is line `n+X` the `ch` value is useless.

Is there any workaround? Any way I can get this value?

**Comment by marijnh** [comment]
`editor.getLine(n).length` seems to cover this?

**Comment by lukasoppermann** [comment]
Ahh, nice thanks. One more question, is there a way to get a "visual" line? So if the line wraps because it is to long, can I get only the first part until the wrap, so basically to the position `goLineLeft` moves to, but without changing the selection.

**Comment by marijnh** [comment]
There no functionality like that exported at the moment. Once we get around to breaking up CodeMirror into modules, I'll make sure these utilities end up exported. If you need this really urgently, I could see if there's a clean way to export them already.

**Comment by lukasoppermann** [comment]
That would be pretty awesome, if it is not too much trouble. I am trying to write an addon for codemirror and need this for positioning it. 

Btw. is there any best practises for writing reusable addons for cm?

**Comment by marijnh** [comment]
If you want the screen position to the right of the line, as opposed to the last character on the line, that's easier done with taking the y from the charCoords at its start, and the x from `cm.getScrollerElement.getBoundingClientRect().right`. Or do you really want the character?

**Comment by lukasoppermann** [comment]
No, I just need the position basically about where the last character is. I will give it a try.

**Comment by marijnh** [comment]
Well, the thing I described will only get you the right side of the line's bounding box, which is quite a bit away from the last character in most situations. What kind of effect are you trying to achieve?

(As for writing addons, the only available guidance is the code for the addons in the distribution.)

**Comment by lukasoppermann** [comment]
Hey, I need to position an element centered above the first selected "visual" line (or last selected line in some circumstances).

So your solution is not working (I misunderstood you).

Addons: Yeah, okay, I figured, just thought maybe I missed something. :)

**Comment by marijnh** [comment]
Ah, you're not using visual line in the same way that the codebase is. I guess you want to center above the _selected_ part of the line, not the whole line?

I'd do something like:

 - Get `getCursor("from")` to know the low selection bound.

 - Get the coordinates of that position.

 - Call `coordsChar` with the y from those coordinates and an x at the right side of the editor to get the position at the end of the line.

 - Compare `getCursor("to")` with that position to see if you want to use that one or if the cursor is before it.

 - Get the coordinates at the second position, and average the x of the two coordinates.

**Comment by lukasoppermann** [comment]
Hey, yes, this is true. It works fine if I just have 1 line, part of one line or multiple lines. What I have trouble with and what I think (??) your suggestion does not solve, is when I have one "editor-line" (w.g. line 23), which is shown n two lines, due to a wrap.

In the 2 screenshots, I would like to get the center of the first selected "line", but actually multiple "lines" are "editor-line" 23.

<img width="672" alt="screen shot 2016-07-13 at 22 23 08" src="https://cloud.githubusercontent.com/assets/813754/16818503/69cde73a-4948-11e6-956a-be202b27c161.png">
<img width="674" alt="screen shot 2016-07-13 at 22 22 42" src="https://cloud.githubusercontent.com/assets/813754/16818504/69d7be4a-4948-11e6-9c1f-edaeedc0440f.png">

**Comment by marijnh** [comment]
Yes, that's why you use `coordsChar` to get the actual end of the line (see the source for `goLineRight`). That'd give you the position after 'cillum', which is the one you want, if I understand things correctly.

**Comment by lukasoppermann** [comment]
Okay, I will give it a try and report tomorrow. Thank you very much for the help so far.

**Comment by lukasoppermann** [comment]
Yes, it worked, thank you very much.

**Comment by marijnh** [comment]
🎉

**Comment by samarjeetsamar** [comment]
`czczczcz faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` fsfsfsf
