### ISSUE TITLE
Top panels in a merge view offsets connectors

### ISSUE THREAD

**Issue by alur** [codemirror/CodeMirror#4112]
Seems like they simply need to be moved down by the height of the panels.
![1tosv9weqqs](https://cloud.githubusercontent.com/assets/1925047/16818552/2912e132-48fd-11e6-830b-861929506bea.png)

**Comment by marijnh** [comment]
Attached patch should help, but depending on how and when you create the panel, it might not trigger a merge view update, and the connectors might only adjust the next time you do anything. Could you test and see if it works for you?

**Comment by adrianheine** [comment]
Since there was no further feedback indicating the opposite I suppose this is fixed. Please feel free to re-open if that is not the case.
