### ISSUE TITLE
Listening to events from all CodeMirror instances

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#4114]
CodeMirror very usefully provides `CodeMirror.defaults` to set global defaults. I think it would be useful if there was likewise some way to specify default event handlers, or event handlers on a global bus.

If you want to write a `beforeChange` handler that works on all CodeMirror editors on your website, right now you have to carefully make sure you attach the handler to each instance as it is created.

**Comment by vincentwoo** [comment]
Nope, nevermind, I'm a fucking idiot:

> cm.on(type: string, func: (...args))
>   Register an event handler for the given event type (a string) on the editor instance. There is also a CodeMirror.on(object, type, func) version that allows registering of events on any object.

**Comment by vincentwoo** [comment]
Wait, actually, I misunderstood the manual again. Looks like `CodeMirror.on` still requires that you pass in an obj.

I'd love a syntax like `CodeMirror.on('beforeChange', function(instance, changeobj) {`!

**Comment by vincentwoo** [comment]
The undocumented option `finishInit` *almost* works, except for that `CodeMirror.fromTextArea` overrides it.

**Comment by vincentwoo** [comment]
> CodeMirror.defineInitHook(func: function)
> If your extension just needs to run some code whenever a CodeMirror instance is initialized, use > CodeMirror.defineInitHook. Give it a function as its only argument, and from then on, that > function will be called (with the instance as argument) whenever a new CodeMirror instance is initialized.

god, nevermind, why am I so bad at this

**Comment by thomcom** [comment]
Thanks! You showed me something really important. :)

**Comment by tonytlwu** [comment]
I've [created a PR](https://github.com/codemirror/CodeMirror/pull/5358) so that `CodeMirror.fromTextArea` doesn't override user's `options.finishInit` configuration.
