### ISSUE TITLE
Linter demo page is broken

### ISSUE THREAD

**Issue by voidmain** [codemirror/CodeMirror#4123]
Not sure if you guys just did a release or not, but it looks like the Linter Demo page is broken. It seems as though all the JS files are trying to load using CommonJS and `require` but that is failing because `require` is not defined.

**Comment by marijnh** [comment]
That was related to an upgrade (?) in the csslint.js script we hotlinked, which created `exports` and `module` globals (for some reason), breaking our module loaders. I've disabled that css linting demo for now.

**Comment by orionlee** [comment]
@marijnh The lastest csslint (v1.0.3) has the issue resolved.

https://github.com/CSSLint/csslint/pull/672

**Comment by marijnh** [comment]
Great. I've reverted the patch that disabled the CSS demo.
