### ISSUE TITLE
Request to remove "//" styled comment from all javascript files

### ISSUE THREAD

**Issue by razonklnbd** [codemirror/CodeMirror#4125]
Hello CodeMirror,
I'm trying to develop a code that will minify all JavaScript file automatically. When I attempt to do it on CodeMirror files it doesn't work due to "//" styled comment. I request to apply "C" style comment i.e. "/* .... */" when comment need to put.
Thanks & Regards,
Shahadat

**Comment by marijnh** [comment]
No.

**Comment by gloony** [comment]
@razonklnbd 
> I'm trying to develop a code that will minify all JavaScript file automatically. When I attempt to do it on CodeMirror files it doesn't work 

I made a thing like that today and found your topic, I would share my solution if it can help in the futur.
Import a browser version of UglifyJS into your webpage with this tutorial (http://lisperator.net/uglifyjs/)[http://lisperator.net/uglifyjs/]
And you can set your extraKey like that : 
```
"Ctrl-Alt-K": function(cm){
	switch(cm.getOption('mode')){
		case 'text/javascript':
			var ast = UglifyJS.minify(cm.getValue());
			cm.setValue(ast.code);
			break;
	}
},
```
