### ISSUE TITLE
Codemirror hint- selected item not getting changed on mouse movement

### ISSUE THREAD

**Issue by guptvaibhav** [codemirror/CodeMirror#4126]
I am using the latest Codemirror version- 5.17.0
Still I am facing this issue  - https://github.com/codemirror/CodeMirror/pull/3636

![autocomplete](https://cloud.githubusercontent.com/assets/12712833/17020172/db8ca77e-4f5d-11e6-8ef7-29c45390791b.gif)

Could you please tell me how to fix this.

**Comment by vg6193** [comment]
Hi guys , still waiting for a reply from you.Please have a look at this

**Comment by marijnh** [comment]
You could start by actually describing what 'this issue' refers to.

**Comment by vg6193** [comment]
The issue I am facing is while using codemirror hint , I am able to browse through the suggestions using keyboard cursor, but not using mouse. Please have a look at the gif which I have attached. 
So basically the mouse selection is not working for me.
In issue #3636 I could see that there was an exact same problem.

**Comment by marijnh** [comment]
Do you mean clicking the hint doesn't select it? That appears to work for me.

**Comment by vg6193** [comment]
yes and the mouse hover doesn't work as well. Please have a look the the gif file above.

**Comment by vg6193** [comment]
I am using npm codemirror version - 5.17.0

**Comment by marijnh** [comment]
I _did_ have a look at the gif, of course, but a gif is a terrible storyteller, so _use words_ to communicate what your problem is. The select-on-hover behavior was reverted because it caused problems, and clicking to select works fine for me.

**Comment by vg6193** [comment]
So you mean that hover doesn't work but the clicking is alright?
In my case clicking is also not working , what could be the reason ?

**Comment by vincentwoo** [comment]
Clicking works fine for me in my app and in the CodeMirror demo. If you want someone to answer your question you need to provide a reproducible test case. Otherwise, no one is going to be able to help you.

**Comment by adrianheine** [comment]
I'm closing this for now since there's not enough information to reproduce the issue.
