### ISSUE TITLE
Request for comments - alternate (non-DOM) view for the editor 

### ISSUE THREAD

**Issue by unphased** [codemirror/CodeMirror#4132]
I will be building a code editor tool and I am pretty sure that I will be using CodeMirror to implement the main editor component. 

I also plan to build 3D interfaces in order to support innovative new methods of viewing and visualizing source code and this means that having a clean model/view separation would allow for a way to leverage the code instead of starting from scratch. Starting from scratch is entirely fine as well because the ability to edit or really even highlight code is in the "icing on top" featurelist.

I'm curious about how feasible the architecture of CodeMirror is with respect to replacing its "frontend" in this way. What I mean by this is instead of having a document be made up of lines made of `span`s inside of a `pre`, which are all inside of a `div`, and styling done by twiddling classes on them, the characters would be assembled to vertex buffers and sent to the GPU via WebGL instead. The paradigm for styling is entirely different as it will involve vertex metadata and shaders instead of anything resembling cascading style sheets. With that being said, as long as there is enough of an abstract document modeling foundation, the differences are not necessarily very drastic.

Is there a lot of reliance on DOM state and performing mutations on it? Obviously nothing will work out of the box, but I want to try to estimate roughly how "intertwined" the DOM mutation code is to core logic, and also evaluate how much global reliance there is on DOM state (whether there is any periodic "full rendering", or "structured/modular rendering" reminiscent of react or any such, that can help me key off of) to see if there is enough of a usable "core" that I can factor out and make the system agnostic to the use of the browser DOM.

I realize that this question is very vague and what would suffice are general comments or a correspondingly vague answer. it is in no way a feature request or bug report or any such typical issue. If you do not think the question can be answered you may also feel free to close this issue. I do expect that as I learn the code base more as I integrate my project around it, I will be able to answer a lot of these questions myself. 

Thanks.

**Comment by marijnh** [comment]
> I'm curious about how feasible the architecture of CodeMirror is with respect to replacing its "frontend" in this way.

That's not something CodeMirror is written for, and I consider it out of scope for this library.
