### ISSUE TITLE
wrong indentation in js object

### ISSUE THREAD

**Issue by wendy0402** [codemirror/CodeMirror#4133]
I try to create js object but the indentation when it use multiple line:
```javascript

{
  "yes": "true",
    "why": "false",
      "test": "what"
}
```

expected:
```javascript

{
  "yes": "true",
  "why": "false",
  "test": "what"
}
```

what should I do? do I need to add a addon? I use v3 mode `javascript`, addon: `foldcode`, `formatting`, and `overlay`

here how I instantiate codemirror:
```
var myCodeMirror = CodeMirror.fromTextArea(document.getElementById("message-container"),{
  lineNumbers: true,
  tabSize: 2,
  indentWithTabs: false,
  smartIndent: true,
  mode: {name: "java
```

**Comment by marijnh** [comment]
That's not a JS object, that's a JS block. If you want to type JSON, set your mode to `"application/json"`.
