### ISSUE TITLE
Passing an undefined number into setSelection returns unintuitive error

### ISSUE THREAD

**Issue by ebber** [codemirror/CodeMirror#4135]
ENV:
Chrome

The following senario:
var numVar = undefined //In my case, was looking up the number in an object

codeMirror.setSelection({ line: numVar, ch: 0 }, { line: numVal + 1, ch: 0 }, { scroll: true })

gave an error:
"TypeError: Cannot read property 'chunkSize' of undefined"
with a long stack trace

I would recomend just adding a validation check at the start of setSelection where if the input numbers are undefined, throw an exception saying "Line number undefined" or something similar

**Comment by marijnh** [comment]
CodeMirror doesn't do type checking at its API boundaries, as that would incur too much code size and performance impact. So if you violate it's type expectations, you're getting undefined behavior, not custom-crafted error messages.
