### ISSUE TITLE
JSON syntax highlight issue

### ISSUE THREAD

**Issue by ilyazolotarov** [codemirror/CodeMirror#4143]
Sometimes properties have the "cm-property" class, and sometimes they are parsed as plain text (note the difference between the first and subsequent objects in the "Items" array).

![123](https://cloud.githubusercontent.com/assets/10565780/17273528/30016a10-56c0-11e6-9171-4d264559db13.PNG)

**Comment by marijnh** [comment]
Does this still happen on the current master branch, and if so, can you submit the actual _text_ that triggers it, rather than a screenshot?

**Comment by ilyazolotarov** [comment]
Yes, it's all right with the new mode/javascript.js from master brunch. Thank you.
