### ISSUE TITLE
[vim] Y (Yank line) not working as intended

### ISSUE THREAD

**Issue by ekohilas** [codemirror/CodeMirror#4144]
after yanking a line, shift p should be putting above the line, instead it inserts inline.
Have reproduced multiple times.
Windows 10, Chrome Version 52.0.2743.82 m

**Comment by nightwing** [comment]
This is an intentional deviation from vim default see https://github.com/codemirror/CodeMirror/issues/2643.
Y is equivalent to y$ which is not a linewise motion. yy works like Y in vim

**Comment by ekohilas** [comment]
Oh I see
Oh well...
