### ISSUE TITLE
HTML get damaged with replace URL in Editor

### ISSUE THREAD

**Issue by Daijobou** [codemirror/CodeMirror#4145]
I found a issue in CodeMirror. I use CodeMirror for TinyMCE as a replacement for the source-code editor. As basic I used https://github.com/christiaan/tinymce-codemirror with CodeMirror verison 5.17.0.

Without (comment out) CodeMirror that issue is gone.

My TinyMCE settings:
```
            external_plugins: {
				"codemirror": "/tinymce-plugins/codemirror/plugin.min.js",
    		},
			codemirror: {
				indentOnInit: true,
				path: 'codemirror-5.17',
				config: {
					mode: 'htmlmixed',
					lineNumbers: false
				}
			},

```

Here the issue:

I insert in souce-code editor this:
```
<a
   href="URL1" target="_blank">Text</a>
```
Now I replace "URL1" with a real URL. After Submit, I get this result in TinyMCE:
`" target="_blank">URL1`
Reopen CodeMirror, I see this as source:
`<a href="http://domain.tld/file.jpg&lt;span id=">" target="_blank"&gt;URL1</a>`
This not happen, I insert the code with already URL in it.

And... this bug happen only in the last replaced URL. Means:
```
<a
   href="URL1" target="_blank">URL1</a>
<a
   href="URL2" target="_blank">URL2</a>
```
Replace first URL1, only the second URL2 have this issue. Replace first URL2, only the first URL1 have this issue.

There is no issue, when I use a single line:
`<a href="URL1" target="_blank">Text</a>`

**Comment by marijnh** [comment]
The maintainers of this repository have nothing to do with the TinyMCE integration code. I suggest you ask whoever created the integration you're using.
