### ISSUE TITLE
TypeScript: broken function annotation highlighting

### ISSUE THREAD

**Issue by zaggino** [codemirror/CodeMirror#4150]
First variable in function annotation is highlighted, second one is not.
Plus added a comment here: https://github.com/codemirror/CodeMirror/issues/3893

![image](https://cloud.githubusercontent.com/assets/1067319/17441887/82afae88-5b76-11e6-8c2d-ff078c24b6c0.png)

```
const readFile: (path: string, encoding: string) => Promise<any> = Promise.promisify(fs.readFile);
```

**Comment by zaggino** [comment]
Can you let me know how to run tests? I tried running it for latest master so I could fix this one myself (with tests) but it failed quite early:
```
$ npm test

> codemirror@5.17.1 test C:\dev\CodeMirror
> node ./test/run.js

core_measureEndOfLine
assertion failed (not at right)

1 failure

{ Error: Command failed: C:\dev\CodeMirror\node_modules\phantomjs\lib\phantom\phantomjs.exe C:\dev\CodeMirror\test\phantom_driver.js

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\dev\\CodeMirror\\node_modules\\phantomjs\\lib\\phantom\\phantomjs.exe C:\\dev\\CodeMirror\\test\\phantom_driver.js' }
npm ERR! Test failed.  See above for more details.
```

https://github.com/codemirror/CodeMirror/blob/master/CONTRIBUTING.md#contributing-code doesn't say how to run tests, for example if I wanted to run `/mode/javascript/test.js`.

**Comment by marijnh** [comment]
You can open `test/index.html#javascript_*` in your browser to run only the JavaScript mode's tests.
