### ISSUE TITLE
GFM & Markdown mode get wrong syntax highlight when using code block with blockquote

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#4151]
1. Go http://codemirror.net/mode/gfm/
2. Input below codes

``````
> ```
> asdasdasdasd
> ```

asdasdasdasd
``````

You'll see only the first `>` get correct color.
And the syntax highlight not turning back after the code block end.

![image](https://cloud.githubusercontent.com/assets/2639151/17463207/b1aec2ea-5cf3-11e6-9eb5-2e2843132feb.png)

Thank you for helping! Really appreciated!

**Comment by ryancui-** [comment]
Also have a wrong syntax hightlight when typing this:

```
# Title
## title 1

> - aaa

## title 2
```

using list in quote cause a mistake. Thanks for fixing this.

**Comment by dwelle** [comment]
Gonna look into this.

**Comment by dwelle** [comment]
associated commit doesn't really "fix" this, but for now IMO better than nothing  :blush:
