### ISSUE TITLE
[markdown mode] differentiate between heading types

### ISSUE THREAD

**Issue by alinnert** [codemirror/CodeMirror#4157]
My idea is to create a text editor that moves special characters at the beginning of a line in a markdown document to the left (like iA Writer does). Currently it's not possible since both headline types do have the same css class (`cm-header cm-header-1`) (same goes for `cm-header-2`):

~~~markdown
# Title
~~~

~~~markdown
Title
=====
~~~

Is it possible to make them different or better add another class to make it possible to differentiate between the two?

**Comment by Menci** [comment]
Excuse me, how can we move the `#` to the left if we only have the first type headings. Thanks.

**Comment by alinnert** [comment]
One example would be the following CSS:

~~~css
.cm-header-1 {
    margin-left: -2ch;
}

.cm-header-2 {
    margin-left: -3ch;
}

/* etc. */
~~~

I'm not yet sure if this is the best solution but at least it works.

The unit `ch` means "character". It's the width of the `0` (zero) character.
It's very rarely used but very useful in this case.

**Comment by vincentwoo** [comment]
I'm not sure that such a change belongs in `master` for markdown's stylings. If I understand you correctly, you wish to style headlines with `#` and `===` differently?

It's not too hard for you to either modify the markdown mode to [classify them differently](https://github.com/codemirror/CodeMirror/blob/master/mode/markdown/markdown.js#L176), or to write a script in userland that looks for such headers and [mark them with a custom class](https://codemirror.net/doc/manual.html#markText).

**Comment by marijnh** [comment]
I agree, this is too specific to incorporate in the main distribution.
