### ISSUE TITLE
Million of lines breaks scrollbar in Firefox 48.0

### ISSUE THREAD

**Issue by Zalewa** [codemirror/CodeMirror#4160]
Use this minimal example: [index.txt](https://github.com/codemirror/CodeMirror/files/413511/index.txt)

Click "paste text" 6 times. After 6th click the scrolling widget in scrollbar will disappear. If you scroll to the bottom of the editor with CTRL+END you will see that there are 596507 lines displayed. In Google Chrome you can have 745654 lines and the scroll widget in the scrollbar doesn't disappear.

This example has line wrapping enabled which makes the problem appear sooner. If you disable line wrapping you can have about 1.2 million lines before scrollbar breaks and no more lines are displayed. Chrome allows you to have 2.23 million.

Now, I use CodeMirror as a "tail" tool that follows a file that can potentially grow indefinitely. I fully accept that there is a general line (and memory) limit and I prune old lines, but I also want to display as many of them as possible so that user can search the contents. With line wrapping disabled I can set line limit to 1 million and I'll be set. But I also need to use line wrapping, so it's not certain when I'll hit this limit.

What can be done?

**Comment by marijnh** [comment]
I think you're running into [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1205604). Could you confirm that the problem starts occurring when the height crosses 17895698 pixels?

**Comment by Zalewa** [comment]
I confirm. For my case I have settled for displaying max 100 000 lines - it should be a safe limit, considering line wrapping and user-customizable font sizes.

Well, it's good to know the reason of the problem, at least.

**Comment by marijnh** [comment]
All right. Closing as 'Firefox's problem'
