### ISSUE TITLE
Android browser (& Chrome) char input issues

### ISSUE THREAD

**Issue by mattpass** [codemirror/CodeMirror#4161]
A few issues seem to be present on the Android & Chrome browsers I think.

Android - testing against demos on CodeMirror site:
Glitchy cursor position when typing, then when typing a space char it can remove some previous characters. 

Android - own site
When typing chars it mysteriously adds a line return after each

Chrome - testing against demos on CodeMirror site:
Removes space character

Chrome - own site
With line wrapping on it adds 1 char per line till you press space, Enter or tap to set new cursor position.

Tested on Samsung S7 Edge under latest Android OS.

**Comment by mattpass** [comment]
(Note: not expecting anyone to fix the issues on my site, just noting them for reference and fixing bugs seen on CodeMirror hosted demos may help resolve my own. For reference only). :-)

**Comment by kofifus** [comment]
Hi mattpass,

Did you try inputStyle: "textarea" ?

I think it defaults to "contenteditable" on mobiles which can cause such bugs ?

**Comment by marijnh** [comment]
You really don't want to use `textarea` input style on touch screens. It'll break user selections almost entirely.

These reports aren't very specific, but we're aware that there are some issues with IME handling (which is how Android virtual keyboards enter text), see the [IME tag](https://github.com/codemirror/CodeMirror/issues?q=is%3Aissue+is%3Aopen+label%3AIME). If you have a more specific problem that can be reproduced with plain CodeMirror, and isn't already reported, please describe it in a new issue.
