### ISSUE TITLE
Should be possible to turn off match-highlight when cursor hasn't been explicitly set

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4162]
## Repro

1. https://codemirror.net/demo/matchhighlighter.html

## Expected

No word should be match-highlighted, since there's not supposed to be a cursor.

## Actual

The cursor is there at (0,0), just invisible, so the first word is highlighted. This is sort of inconsequential in the demo, but causes a lot of distraction in code, when the first line is e.g. something like `import`, and then all mentions of `import` get highlighted.

**Comment by marijnh** [comment]
Would qualifying the styles added by `cm-matchhighlight` to only be active inside a `CodeMirror-focused` container address this?

**Comment by mtaran-google** [comment]
No, because then when you focus to another window/tab, the highlight will go away, which is counter to what IDEs like intellij, visual studio code etc do.

**Comment by marijnh** [comment]
Then I am unclear what your definition of there being a cursor is. Could you elaborate? (I don't have any of the named IDEs installed.)

**Comment by mtaran-google** [comment]
I've uploaded a video of what the interaction in intellij looks like. But my point is that there shouldn't be a cursor at all (for the purposes of match-highlighting) until the editor gets focus. After that, the cursor should remain (for the purposes of match-highlighting) even when the editor loses focus.

[intellij-highlighting.mp4.zip](https://github.com/codemirror/CodeMirror/files/418678/intellij-highlighting.mp4.zip)

**Comment by marijnh** [comment]
Does making the match-highlighting addon not update its highlighting until the first time the selection changes while the editor is focused sound like a better solution?

**Comment by mtaran-google** [comment]
I think that does sound like it would work!

**Comment by marijnh** [comment]
Please try with attached patch

**Comment by mtaran-google** [comment]
Looks good! Thank you :)
