### ISSUE TITLE
Speciality JSON MIME-types Missing

### ISSUE THREAD

**Issue by xeenon** [codemirror/CodeMirror#4163]
There are over 50 "+json" MIME-types [registered with IANA](http://www.iana.org/assignments/media-types/media-types.xhtml). They should be recognized as JSON like the "+xml" MIME-types are treated as XML in `CodeMirror.resolveMode`.

```javascript
    } else if (typeof spec == "string" && /^[\w\-]+\/[\w\-]+\+xml$/.test(spec)) {
      return CodeMirror.resolveMode("application/xml");
    }
```

**Comment by marijnh** [comment]
Fixed via #4164
