### ISSUE TITLE
Jade has been renamed to Pug

### ISSUE THREAD

**Issue by TimothyGu** [codemirror/CodeMirror#4166]
The CM mode still uses the name "Jade."

**Comment by marijnh** [comment]
@ForbesLindesay Do you agree? Are you still using the mode and will anything break on your side if I do this rename?

**Comment by ForbesLindesay** [comment]
Yes, I agree.  It would probably be best to rename and then add an alias `jade => pug` so that anyone using the name "jade" doesn't suddenly have their stuff break.

**Comment by marijnh** [comment]
Since modes are typically imported by filename, stuff is still likely to break when people try to import mode/jade/jade.js. But yes, I can add an alias in mode/meta.js for those who rely on that.
