### ISSUE TITLE
TypeError: textarea is null 	  options.value = textarea.value; 

### ISSUE THREAD

**Issue by emresaracoglu** [codemirror/CodeMirror#4167]
Hello,

I get this error:

> TypeError: textarea is null 	  options.value = textarea.value; 

What is the reason of this?
Thank you 

_Code.php_

> < textarea name="mquery" id="mquery" rows="6" cols="65" autofocus> < /textarea>

_Header.php_ 

>       <link rel="stylesheet" href="http://codemirror.net/lib/codemirror.css">
> 		<link rel="stylesheet" href="http://codemirror.net/addon/hint/show-hint.css" />
> 		<link rel="stylesheet" href="http://codemirror.net/theme/3024-night.css">
> 		<script src="http://codemirror.net/lib/codemirror.js"></script>
> 		<script src="http://codemirror.net/addon/edit/matchbrackets.js"></script>
> 		<script src="http://codemirror.net/mode/sql/sql.js"></script>
> 		<script src="http://codemirror.net/addon/hint/show-hint.js"></script>
> 		<script src="http://codemirror.net/addon/hint/sql-hint.js"></script>
> 		
> 			<script type="text/javascript"> 
> 				var textArea = document.getElementById('mquery');
> 				var editor = CodeMirror.fromTextArea(textArea);
> 				editor.getDoc().setValue('var msg = "Hi";');
> 			</script>

**Comment by marijnh** [comment]
You're calling `fromTextarea` with `null` as first argument.

**Comment by emresaracoglu** [comment]
Can you help me? 
How do I need to change in code?
