### ISSUE TITLE
[javascript hint] does not include non-enumerable properties

### ISSUE THREAD

**Issue by orionlee** [codemirror/CodeMirror#4171]
In the current implementation (post v5.17.0), javascript hint does not include non-enumerable properties.

### Impact: 
In practice, it means it does not include most top-level classes, at the minimal in recent Chrome environment. 

### How to reproduce:
- Go to autocomplete demo page:  http://codemirror.net/demo/complete.html
- in the top editor, try to auto-complete some top-level classes, e.g., Event, Promise, etc.
- it will not complete (tested on Chrome 51 and 52 on windows 7).

**Comment by orionlee** [comment]
I have a patch in my repository by using Object.getOwnPropertyNames() , supported by most modern browsers. I could create a pull request with the patch. Let me know.

**Comment by marijnh** [comment]
That'd be useful (but make sure to fall back to `for/in` when `getOwnPropertyNames` isn't available)

**Comment by marijnh** [comment]
Fixed via #4175
