### ISSUE TITLE
JS async issue

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#4173]
Case 4 of #4085 still doesn't parse correctly.
```js
let obj = { async foo(args) { return true; } }; // #4
```

**Comment by marijnh** [comment]
What's wrong with it? If you want `async` to show up as a keyword there, that'd require look-ahead, which I think is more trouble than this small adjustment is worth.

**Comment by ficristo** [comment]
Yes, it should be highlighted as a keyword.

**Comment by marijnh** [comment]
I'm not really interested in implementing that. The same behavior exists for `get` and `set`.
