### ISSUE TITLE
python 3.6 string formatting

### ISSUE THREAD

**Issue by myyc** [codemirror/CodeMirror#4176]
Python 3.6 is introducing an extremely useful string formatting syntax: `f"{a} {b}"` instead of `"{a} {b}".format(a=a, b=b)`. It seems at least the `f` is parsed correctly [in the code](https://github.com/codemirror/CodeMirror/blob/master/mode/python/python.js#L65), but `f"blah" + foo + "bar"` looks differently from `b"blah" + foo + "bar"` in the website demo (and on Jupyter notebook, which is where I spotted it).

**Comment by myyc** [comment]
On second thought, it looks like both default to the py2 mode, as `@` doesn't get handled properly either.

**Comment by myyc** [comment]
My bad. This does happen in the website demo but not in another Jupyter notebook I checked. Feel free to close it if you think it's not an issue.

**Comment by marijnh** [comment]
I've made Python 3 the default version for the Python mode in 4f70169
