### ISSUE TITLE
shift + tab remove all tabulation one time

### ISSUE THREAD

**Issue by joubertredrat** [codemirror/CodeMirror#4177]
Hi guys,

on test in https://codemirror.net/mode/php/index.html and https://codemirror.net/mode/javascript/index.html indentation with `tab` works fine as expected, but if you use `shift + tab`, all indentation is removed one time instead to remove one by one while will pressing `shift + tab`.

On IDE and editors, is normal to add one indentation if you press `tab` and remove one indentation if you press `shift + tab`, but here, if I press `tab` 4 times, it correctly add 4 indentation and if I press `shift + tab` 1 time, it remove 4 indentation.

**Comment by marijnh** [comment]
You want ctrl-[. Shift-tab auto-indents the selection.

**Comment by joubertredrat** [comment]
@marijnh I tested here and really `ctrl + [` remove tabulation one by one and `shift + tab` auto-indents the selection.

But this is very strange, on Github, Netbeans, Atom, Sublime Text, PHPStorm and others, all use `shift + tab` for remove tabulation one by one, not for auto-indents the selection.

Then I have a question, CodeMirror supports customize what keys will dispatch actions?

**Comment by marijnh** [comment]
Maybe try the [manual](http://codemirror.net/doc/manual.html#keymaps)

**Comment by joubertredrat** [comment]
@marijnh worked fine here, thanks.
