### ISSUE TITLE
SAS mode malfunction when use empty string or string with only spaces in quote

### ISSUE THREAD

**Issue by xiangzhimeng** [codemirror/CodeMirror#4178]
When I put "" or '' or " " or ' ', the program malfunction. You could try this with the mode demo on the code mirror website.

**Comment by xiangzhimeng** [comment]
Thank you for updating the sas mode, after the commit '', "", ' ', " " are fine but "'" causes problems.

**Comment by marijnh** [comment]
You're right. Attached patch should help.
