### ISSUE TITLE
ES6 string interpolation make TypeScript highlighting go haywire

### ISSUE THREAD

**Issue by joshfriend** [codemirror/CodeMirror#4179]
I'm aware of other similar issues:

* #3536 and #3865, closed as relating to JSX
* #3650, closed as relating to spread operator, seems fixed AFAICT
* #2622, looks like a very similar problem. that particular case was fixed.

Pasting the following into the [typescript mode demo](https://codemirror.net/mode/javascript/typescript.html)

```typescript
export class OrganizationEndpoint extends EndPointBase<Organization> {
  constructor() {}
  
  listAdmins(orgId: number): Observable<User[]> {
    return this.client.get(`${this.endpoint}/${orgId}/admins`)
      .map(response => {
        // oh boy, everything turned red...
      });
  }
}
```

renders like this:

![asdf](https://i.imgur.com/mmfMgxB.png)

Removing the `constructor` or removing `${this.endpoint}` from the template string makes highlighting return to normal

**Comment by marijnh** [comment]
Ah, right, that's a subtle TypeScript incompatibility -- it parses the `extends` clause as a type, rather than an expression. Attached patch should help.

**Comment by joshfriend** [comment]
That was quick! Now I just have to wait for Atlassian to update CodeMirror in Bitbucket Server 😞
