### ISSUE TITLE
codemirror.js:4776 Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by babybigfox** [codemirror/CodeMirror#4180]
Chrome is throwing up the error above in the console when I use the python version of CodeMirror in my textarea. Here are the lines surrounding the error line:

CodeMirror.fromTextArea = function(textarea, options) {
    if (!options) options = {};
    **options.value = textarea.value;**
    if (!options.tabindex && textarea.tabindex)
      options.tabindex = textarea.tabindex;
    if (!options.placeholder && textarea.placeholder)
      options.placeholder = textarea.placeholder;
    // Set autofocus to true if this textarea is focused, or if it has
    // autofocus and no other element is focused.
    if (options.autofocus == null) {
      var hasFocus = activeElt();
      options.autofocus = hasFocus == textarea ||
        textarea.getAttribute("autofocus") != null && hasFocus == document.body;
    }

This is preventing my editor from working.

**Comment by marijnh** [comment]
No, that line doesn't need fixing. Your code needs to pass in an actual textarea rather than null when calling `fromTextArea`.

**Comment by dipaksavaliya02** [comment]
Remove `blackbox` extension and `react development tool` extension from chrome

**Comment by PriteshAkhaja** [comment]
Remove `blackbox` extension or `react development tool` extension from chrome
