### ISSUE TITLE
[search addon] add history support

### ISSUE THREAD

**Issue by orionlee** [codemirror/CodeMirror#4181]
Add history support to search dialog. I have a private patch that can be integrated. Let me know if there will be interest.

My patch treats search history as a form of auto-complete. In search dialog box, the user can press Ctrl-Space to get a list of past searches matching the text entered so far.

Feature-wise, it is a subset of #3478 . 
The implementation is similar to #2591 , but done independently (and no code sharing)

**Comment by marijnh** [comment]
I think the current search addon is kind of at the limit of its complexity budget. What I mean is that a good search interface is a rather huge, open-ended problem, and I'm already stretched too thin to really want to take on maintenance of any more complexity for this addon. I think the best way forward would be a fork of the search addon (or a rewrite, given what a mess it already is), maintained as a separate package, by someone else.

**Comment by orionlee** [comment]
Thanks for the reply. I do agree with your sentiment that the current search addon is a bit too difficult to maintain.  For now I will keep my patch private. 

If I can refactor the addon and supply good unit tests, thereby reducing maintenance budern, would you consider accept it?

**Comment by marijnh** [comment]
No. If you want to refactor the addon so that you can reuse part of it in your extending addon, so that there'd be less duplicate code, I might be interested. But that might be more trouble than a full fork.

**Comment by orionlee** [comment]
@marijnh  I end up doing a fork that provides hooks to support history. The fork emits a few events so that I can implement history. 
- [forked search.js](https://github.com/orionlee/codemirror-plus/blob/add-hooks-to-search/cm-builder/addon/search/search.js)
- [history/autocomplete that uses the events](https://github.com/orionlee/codemirror-plus/blob/add-hooks-to-search/cm-builder/addon/search/search-autocomplete.js)

Diffs with base (temporary link for a month):
https://www.diffchecker.com/t81p8uNw

It might still be help to incorporate the changes back to official. While it creates some complexity, the events it produces could be useful to serve as an public API for the addon that can be tested against when further refactoring is done.
