### ISSUE TITLE
how to save and load rich text format file

### ISSUE THREAD

**Issue by che3vinci** [codemirror/CodeMirror#4186]
I am using codemirror to write a rich text editor .
i use  function markText() with css arguments to rich the text.
but how can i store the text and load the rich text. 

the textarea only has plain text (without format),and I don't want to add format for text in the textarea (such as markdown format)

is there a simple way to save the rich text and load the rich text

**Comment by marijnh** [comment]
No, you'd have to write your own code for that. CodeMirror is built to be a plain text editor.

**Comment by kofifus** [comment]
check FirePad which (among other things) implements that
