### ISSUE TITLE
TypeScript: broken with private, protected and public modifiers

### ISSUE THREAD

**Issue by zaggino** [codemirror/CodeMirror#4188]
ref: https://www.typescriptlang.org/docs/handbook/classes.html#public-private-and-protected-modifiers

![image](https://cloud.githubusercontent.com/assets/1067319/17834725/9d4f291e-6790-11e6-956c-351c8d5a1461.png)

```
class SomeClass {
    private prop1: string;
    protected prop2: string;
    public prop3: string;
}
```

**Comment by DanielRosenwasser** [comment]
The parser needs to understand class field definitions (and that TypeScript may have an accessibility modifier preceding them). I might be willing to help out with this.

**Comment by DanielRosenwasser** [comment]
@marijnh @zaggino I think I got it working, though I'm not sure about how to write tests.

![image](https://cloud.githubusercontent.com/assets/972891/17849083/fb6c4326-680b-11e6-9c6f-cbf910615b9c.png)

**Comment by marijnh** [comment]
Nice! Hold on, I'll create a patch that adds a few TypeScript tests, so that you can add your own by following it as an example.

**Comment by marijnh** [comment]
Attached patch (e387d21) adds two patch. The format for these mode testing functions is that you pass a name and then the body to be highlighted as a series of strings, one per line. Inside the strings the bracket notation is used to denote the highlighting. A plain string means unhighlighted content, `[type content]` means `"content"` tagged with token type `"type"`

**Comment by DanielRosenwasser** [comment]
Nice - we have [a similar approach](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/fourslash/syntacticClassificationsForOfKeyword2.ts)  for our testing harness as well, but I mostly wasn't sure what `MT` and other functions were. Thanks for setting things up for me.
