### ISSUE TITLE
Breaking change due to mode rename

### ISSUE THREAD

**Issue by blink1073** [codemirror/CodeMirror#4190]
The `vue` mode depends explicitly on `jade`.

https://github.com/codemirror/CodeMirror/blob/master/mode/vue/vue.js#L15

We found this when trying to WebPack all of the modes.

**Comment by jasongrout** [comment]
More context - 5.18.0 release today had the note "The mode formerly known as Jade was renamed to Pug.
"

**Comment by blink1073** [comment]
Code (using asynchronous-style WebPack import):

```
require([`codemirror/mode/${mode}/${mode}`], () => {
```

Error:

```
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../jade/jade in /Users/ssilvester/workspace/jupyter/lab/jupyterlab/node_modules/codemirror/mode/vue
```

**Comment by blink1073** [comment]
Confirmed that replacing all occurrences of `jade` with `pug` in `vue.js` fixes the issue.

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch should help.

**Comment by blink1073** [comment]
Thank you for the quick fix, and for CodeMirror in general!
