### ISSUE TITLE
[lint addon / javascript] Produces extraneous messages when option is specified

### ISSUE THREAD

**Issue by orionlee** [codemirror/CodeMirror#4198]
For example, for the supplied [demo](http://codemirror.net/demo/lint.html), if I modify the lint config to use lint option onUpdateListing:
```
  var editor = CodeMirror.fromTextArea(document.getElementById("code-js"), {
    lineNumbers: true,
    mode: "javascript",
    gutters: ["CodeMirror-lint-markers"],
    lint: { onUpdateLinting:  function onUpdateLinting(annotationsNotSorted, annotations, cm) {
      console.log(annotationsNotSorted);
    } }
  });
```
The `annotationsNotSorted` returned will have an extraneous annotation `"Bad option: onUpdateLinting"` that does not match the editor.

The underlying JSHINT is returning the annotation because CodeMirror addon javascript-hint is passing on non-JSHINT option to JSHINT.  See [startLinting() in lint.js](https://github.com/codemirror/CodeMirror/blob/5.18.2/addon/lint/lint.js#L137) .

Would there be any interest to accept a patch for this?

I am working on a fix, filtering out lint addon's own option before passing to mode-specific helper.

**Comment by marijnh** [comment]
Don't mix the jshint options with the options to the lint addon. Instead, put them in an `options` property in the outer options object, and only those will be passed to jshint.

**Comment by orionlee** [comment]
@marijnh  Ah, in that case:

- in the example above, when lint only has lint-addon option (`onUpdateLinting`), but no `options` propterty, the current [lint.js](/codemirror/CodeMirror/blob/5.18.2/addon/lint/lint.js#L137) behavior is to pass the lint-addon option object to javascript-hint helper, and ultimately to jshint.

In example code:
```
   lint: { onUpdateLinting:  function onUpdateLinting(annotationsNotSorted, annotations, cm) {
      console.log(annotationsNotSorted);
    } }
```

In [lint.js:137](/codemirror/CodeMirror/blob/5.18.2/addon/lint/lint.js#L137)
```
    var passOptions = options.options || options; // Support deprecated passing of `options` property in options
```


-  The comment in [lint.js:137](/codemirror/CodeMirror/blob/5.18.2/addon/lint/lint.js#L137)  is outdated. It states passing of `options` property is deprecated. From what you stated, it is the other wary around.

**Comment by marijnh** [comment]
Yes, that's to preserve backwards-compatible behavior. Add an `options` property to work around it.

**Comment by JulianPinzaru** [comment]
> Yes, that's to preserve backwards-compatible behavior. Add an `options` property to work around it.

Thank you! 
It helped me dealing with the following console warning:
`Cannot display JSHint error (invalid line 0) {id: "(error)", raw: "Bad {a}option: '{b}'.", code: "E001", evidence: "", line: 0, …}`
Leaving it here for anyone else who might encounter the same problem.
So what I did I passed an empty array to options in the lint object, like that:

>  //... other codemirror settings above
> 'lint': {
>              onUpdateLinting: function onUpdateLinting(annotationsNotSorted, annotations, cm) {  
> 				console.log(annotationsNotSorted);  
> 		},
> 		options: []  
> },  
> //... other codemirror settings below

**Comment by peter100u** [comment]
I used jshint js , javascriput-hint. js,lint. JS, resulting in my JavaScript hint JS can't be used. It can't complete the automatic prompt function. Have you encountered it? If so, please tell me how to deal with it
