### ISSUE TITLE
[lint addon] custom tooltip message

### ISSUE THREAD

**Issue by orionlee** [codemirror/CodeMirror#4199]
For lint's tooltip, I'd like to customize it.  In my case, I'd like to add a link to search the web for information relevant to the warning/error.

I have a work-in-progress private fork that will do it. Would be any interest to accept it back, either with the changes built-in, or a hook to accept the changes?

---
Modification outlines in lint.js:

- [annotationTooltip()](https://github.com/codemirror/CodeMirror/blob/5.18.2/addon/lint/lint.js#L110) : change the content of `tip` (the tooltip <div&gt; DOM) , either directly, or an extra lint option `customRenderTooltip` .
- [showTooltipFor()](https://github.com/codemirror/CodeMirror/blob/5.18.2/addon/lint/lint.js#L41) : it needs to be modified so that the tooltip stays on if the mouse moves away from the gutter and to the tooltip itself.

**Comment by marijnh** [comment]
No, I'm not interested in adding extra complexity to addons like lint, because it'd be hard to know where to stop. I prefer for someone to maintain a more powerful lint addon separately, so that the maintenance burden doesn't end up falling on me.
