### ISSUE TITLE
lineSeparator option not working as described

### ISSUE THREAD

**Issue by silverwind** [codemirror/CodeMirror#4204]
The option say:

> Explicitly set the line separator for the editor. By default (value null), the document will be split on CRLFs as well as lone CRs and LFs, and a single LF will be used as line separator in all output (such as getValue). When a specific string is given, lines will only be split on that string, **and output will, by default, use that same separator**.

Specifically the last sentence above is the issue. The output (`getValue`) seems to wrongly split on `\n` even with the option set:
```js
editor.lineSeparator = "\r\n"
editor.setValue("a\r\nb\r\nc")
editor.getValue().split("\r\n")
// [ "a b c" ]
editor.getValue("\r\n").split("\r\n")
// [ "a", "b", "c" ]
```
If this is intended, maybe the documentation should be changed to say it only affects input, not output.

Ref: https://github.com/gogits/gogs/issues/3516

**Comment by marijnh** [comment]
Doing `editor.lineSeparator = ...` is not the way to set the editor's line separator. Use `setOption`.

**Comment by silverwind** [comment]
Indeed it's working as advertized using `setOption`. Sorry for bothering you.
