### ISSUE TITLE
Cannot type into editor after regaining focus on Chrome

### ISSUE THREAD

**Issue by gera2ld** [codemirror/CodeMirror#4205]
Steps to reproduce the issue:

1. visit <https://codemirror.net/>.
1. first time focus to codemirror editor, everything works.
1. click outside the editor, then click inside to regain focus.

Now the cursor is blinking, but nothing can be typed into the editor. It seems the editor is actually not focused because when I press space, the page scrolls down. I can type again if a selection is made with `Shift + Arrows`.

The issue appears on Chrome 52, Window 10 and OS X 10.11.6. Everything works on Firefox.

**Comment by marijnh** [comment]
I can not reproduce this with Chrome 52 on Linux. Are you clicking anywhere specific when focusing and unfocusing, or doing something else that might be relevant?

**Comment by gera2ld** [comment]
Finally found the problem, it was caused by an injected script. Sorry for bothering.
