### ISSUE TITLE
PageUp event being sent to hidden textarea

### ISSUE THREAD

**Issue by JoelEinbinder** [codemirror/CodeMirror#4209]
My CodeMirror is inside of a scrollable div, and I want PageUp/PageDown events to scroll the entire div instead of CodeMirror. Instead, the hidden text area is being scrolled.

I can fix this on Chrome by adding `resize:none` and `overflow:hidden` to the text area. It doesn't fix it on Firefox, and I am scared to touch the `height` or `font-size` of the textarea for fear of unintended consequences.

**Comment by sedwards2009** [comment]
Just stick grab the keyboard events on your Div in the event capture phase. There you can prevent any PageUp or PageDowns from reaching codemirror and manually scroll your div.

**Comment by marijnh** [comment]
You don't even have to use the capture phase -- key events are propagated out of CodeMirror, so you can just handle them with your own code.
