### ISSUE TITLE
[codemirror.css] is not validated

### ISSUE THREAD

**Issue by nvyush** [codemirror/CodeMirror#4210]
The file 'CodeMirror/lib/codemirror.css' is not validated on https://jigsaw.w3.org/css-validator/validator.html.en#validate_by_input

**Comment by marijnh** [comment]
That's true. And it's also not a goal for it to be valid like that.

**Comment by nvyush** [comment]
Do browsers understand not valid css as required?

**Comment by marijnh** [comment]
In this case they do.
