### ISSUE TITLE
PageUp/PageDown don't work in single line CodeMirror

### ISSUE THREAD

**Issue by JoelEinbinder** [codemirror/CodeMirror#4213]
1. Go to https://codemirror.net/demo/resize.html
2. Set the content of the editor to be `123`
3. Put your cursor at the end of the editor and press page up.
    * The cursor unexpectedly stays at the end of the editor
4. Set the content of the editor to be two lines:
```
123
456
```
5. Put your cursor at the end of the first line and press page up
    * The cursor moves to the start of the editor as expected.

This appears to be dependent on the CSS applied to the editor. It doesn't happen in the main editor on the CodeMirror.net home page.

Tested in Chrome and Firefox.
Thanks!

**Comment by aslushnikov** [comment]
This issue bites us a lot =/

**Comment by marijnh** [comment]
Fixed via #4215
