### ISSUE TITLE
Missing origin of changes with replaceRange()

### ISSUE THREAD

**Issue by NessBird** [codemirror/CodeMirror#4216]
Browser: Chrome 51.0.2704.103 (64-bit)
CM: 5.18.2

I'm using the origin parameter on replaceRange to filter changes because I want to react to changes made by the user and not those made by my own code.  Here's the call:

editor.replaceRange(t, {line: i, ch: 0}, {line: i, ch: CM_editor.getLine(i).length}, 'PCP');

This triggers my onChange function:

onChanges = function(cm, changes) {
    // If the origin is 'PCP', we don't want to react -- in that case, this is being triggered
    // by our code, usually the lesson.
    if (changes[0] && changes[0].origin != 'PCP') {

...Unfortunately, in some cases, as with the call above, changes[0].origin is undefined when it arrives. 

Tracing the problem in the Chrome debugger, I can see it in the code below, in codemirror.js.  When it reaches this operation function, cm.curOp is null, so it ends up calling endOperation, which is what triggers my onChanges function.  When endOperation is called, the origin, which is in the arguments, is not passed in, hence my problem.  The problem does occur when the content has been changed by the replaceRange, as well as when it has not.

  // Wraps a function in an operation. Returns the wrapped function.
  function operation(cm, f) {
    return function() {
      if (cm.curOp) return f.apply(cm, arguments);
      startOperation(cm);
      try { return f.apply(cm, arguments); }
  -->    finally { endOperation(cm); }
    };
  }

Thanks as always for a fantastic system!  Ness

**Comment by marijnh** [comment]
Why are you only looking at `changes[0]`? Could it be that the change you're looking for is at another array position in `changes`?

**Comment by NessBird** [comment]
I'm not looking for a particular change, just seeing if any change has been made by the user.  I am using onChanges instead of onChange so changes will be batched and it doesn't call the function multiple times when a user action triggers multiple changes.

Why would it be possible to have multiple changes in the changes[] array that have different origins when I'm not using cm.operation()?  The manual says changes are batched by operation...and presumably the operation is triggered by a single event...?

Maybe I'm not understanding the docs?

**Comment by marijnh** [comment]
Can you produce a self-contained piece of code that demonstrates the problem?

**Comment by taslterminal** [comment]
This is probably caused by read-only texts.

I found a problem in **src/model/changes.js**.

```javascript
  // Possibly split or suppress the update based on the presence
  // of read-only spans in its range.
  let split = sawReadOnlySpans && !ignoreReadOnly && removeReadOnlyRanges(doc, change.from, change.to)
  if (split) {
    for (let i = split.length - 1; i >= 0; --i)
      makeChangeInner(doc, {from: split[i].from, to: split[i].to, text: i ? [""] : change.text})
  } else {
    makeChangeInner(doc, change)
  }
```

As you can see, the **makeChangeInner** call in the for loop here was done without copying over **change.origin** property so it ended up as **undefined**.
This also seem to prevent changes grouping in undo history as well.

**Comment by marijnh** [comment]
@taslterminal Thanks for spotting that! Patch 4c3d3c79 should help

**Comment by adrianheine** [comment]
Probably fixed, yay! (Feel free to re-open or comment if that is not the case)
