### ISSUE TITLE
closebrackets incompatible with simplemode demo

### ISSUE THREAD

**Issue by jc275** [codemirror/CodeMirror#4217]
I'm using the `edit/closebrackets` and `mode/simple` addons, with the (unmodified) "simplemode" [example definition](https://codemirror.net/demo/simplemode.html).

Closing brackets are automatically inserted as expected. But double-quote characters are either ignored entirely (maybe intended behaviour? #4052) or----more frustratingly----if they enclose an empty string, a _third_ double-quote character is auto-inserted after it.

(Edit: possible duplicate of #3660)

**Comment by jc275** [comment]
Ok, from #3660 the problem goes away if a "string" state is used, as per the "factor" mode. Maybe overkill for the "simplemode" example definition.

**Comment by marijnh** [comment]
The autoclosebrackets will only close quotes that get the token type string. So it's not necessary to create a `string` state, but you do have to make sure that unclosed quotes get a string style (you could make your regexp go to the next quote _or_ the end of the line, which leaves them relatively simple still).
