### ISSUE TITLE
Diff screen dosent wrap content

### ISSUE THREAD

**Issue by paladox** [codemirror/CodeMirror#4221]
When I view a diff it cuts it off instead of wrapping it.

Please see http://gerrit-test.wmflabs.org/gerrit/#/c/32/2/tests/fixtures/layout-cloner.yaml and http://gerrit-new.wmflabs.org/r/#/c/2/2/tests/fixtures/layout-cloner.yaml

Using gerrit 2.12.4 and gerrit 2.13.

They are using gerrit which switched to codemirror for there diffs and code editing, but if you look at http://gerrit-old.wmflabs.org/gerrit/#/c/5/2/layout-cloner.yaml when they wernt using codemirror the diffs were better and wrapped instead of cutting off.

That's using gerrit 2.8.1.

I know it sounds like this isent the correct place to discuss this but it is codemirror not gerrit causing the problem.

If I add white-space: pre-wrap to .CodeMirror pre

it wraps it but is an ugly work around and you carnt correctly copy or do inline comments then.

**Comment by paladox** [comment]
Strange it seems using spaces and not tabs works.

http://gerrit-old.wmflabs.org/gerrit/#/c/5/2/layout-cloner.yaml

So there seems to be a problem that codemirror dosent work correctly with tabs.

**Comment by paladox** [comment]
Oh tabs arnt the problem.

Look at http://gerrit-test.wmflabs.org/gerrit/#/c/62/3/tests/fixtures/layout-cloner.yaml

it seems that me adding the extra stuff fixes it. So it seems there is a limit for the width before it gets pushed out.

**Comment by marijnh** [comment]
This appears to be related to the Gerrit integration, which I'm not responsible for.
