### ISSUE TITLE
Overlapping text markers - conflicting title property

### ISSUE THREAD

**Issue by abhigan** [codemirror/CodeMirror#4226]
Hi,

Please review this: https://jsfiddle.net/7sy8smma/1/

We have two overlapping markers. Both have titles which browsers show on tooltip. On the overlapping segment, comdemirror uses the marker which came first. Shouldnt it use the marker which came last? In the attached jsfiddle, the bold section should have title 'span-2' and the underlying section should have title 'span-1'.

I believe this is a bug. Am i missing something?

Thanks and regards
Abhishek Ganguly

**Comment by marijnh** [comment]
Markers aren't really ordered/layered in CodeMirror's model, and since a DOM element can have only one title, any tie-breaking solution seems acceptable. So I'm going to call this the intended behavior.
