### ISSUE TITLE
Pure XML parser enable non-standard entities

### ISSUE THREAD

**Issue by fsologureng** [codemirror/CodeMirror#4228]
In [line 106 of xml.js](https://github.com/codemirror/CodeMirror/blob/master/mode/xml/xml.js#L106) is enabled parsing of any non-numeric entity. This behaviour must occur only when htmlMode is enabled, in pure XML mode, only five non-numeric entities must be valid: amp; lt, gt, apos and quot.

Please consider differentiate both cases.

**Comment by marijnh** [comment]
This is a highlighter, not a validating parser. You can submit a patch that does this if you want (make sure to handle all valid forms of numeric entities), but in the meantime I don't consider this a bug.
