### ISSUE TITLE
full screen of codemirror editor in jquery ui dialog fails on Internet Explroer

### ISSUE THREAD

**Issue by bhattkishan009** [codemirror/CodeMirror#4231]
I am using codemirror editor in jquery ui dialog. It works fine on chrome and firefox but the moment I use it in internet explorer(9,10) and  edge, it spoils UI of ful lscreen.

**Comment by marijnh** [comment]
Does the problem occur in the [full screen demo](http://codemirror.net/demo/fullscreen.html)? Can you describe it a little more precisely than 'spoils UI'?

**Comment by bhattkishan009** [comment]
I am sorry for the improper details marijnh.
No this problem does not occur on full screen demo and not even on normal page on internet explorer.
I will write steps to regenerate issues

1. Use codemirror editor in [jquery ui dialog](https://jqueryui.com/dialog/#modal-form)
2. Open modal popup using a button so the editor gets loaded in dialog.
3. Go full screen in editor

This will set a transparent layer instead of white background in default theme.
Text will be visible but on top of webpage beneath dialog.

I hope this helps.

**Comment by marijnh** [comment]
If other components need to be involved to trigger the problem, it's up to you to either reduce this bug to a more primitive situation (or to arrange things in your app to avoid the issue). I'm not willing to debug jQuery dialogs.

**Comment by bhattkishan009** [comment]
No problem
Thanks for you reply.
I will close the issue.
Kind regards
