### ISSUE TITLE
[core] Long (several thousand char) lines get incorrect cursor position

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4233]
It seems like a rounding error that gets magnified enough to be visible at around 5000-15000 columns. How feasible would it be to fix?

**Comment by marijnh** [comment]
Which browser, and which font? I can't reproduce this on the demo pages in Chrome 52

**Comment by mtaran-google** [comment]
Sorry, it appears to depend on what string you use. I couldn't repro it with just a string of `a`s, but the following works on codemirror.net:

```js
document.querySelector('#demolist').style.display = 'none';
let val = 'long ';
while (val.length < 20000) { val += val; }
editor.setValue(val);
editor.setCursor({line: 0, ch: 8000});
```

If you then click in the editor, you should see the cursor in the middle of the character.

**Comment by marijnh** [comment]
It seems to only happen on Chrome, inside extremely long text nodes (i.e. lines without highlighting, or with a single style throughout). So the ultimately responsible party here is Chrome for returning inaccurate client rects for text in such long text nodes.

There was already a ceiling on the size of a token, to work around another Webkit issue where it would just fail to render text nodes longer than 57444 chars. Attached patch lowers that to 5000, which seems to resolve this issue.
