### ISSUE TITLE
How to put second custom cursor in the editor ?

### ISSUE THREAD

**Issue by rajasimon** [codemirror/CodeMirror#4234]
Hi all,

I wanted to put second custom cursor in the same editor. And I will change the cursor position frequently to wherever I want. Please give me the advice where to start ?.

**Comment by marijnh** [comment]
This is a bug tracker, not a [support forum](https://discuss.codemirror.net). So I'm closing this, but you can start by looking at [`setBookmark`](http://codemirror.net/doc/manual.html#setBookmark) and its `widget` option.
