### ISSUE TITLE
Problem with apostrophe entity

### ISSUE THREAD

**Issue by chack1172** [codemirror/CodeMirror#4235]
I have a problem with codemirror. It changes `&#039;` width `'`. I need to insert this value or the script doen't work.
I've tried with text/html and text/javascript but I have the same problem.

**Comment by WebVeteran** [comment]
Have you tried `&amp;#039;`?

**Comment by marijnh** [comment]
This is almost certainly a misunderstanding of the way HTML parsers read `<textarea>` tags, and not something CodeMirror related.
