### ISSUE TITLE
Ways to identify the DOM element the cursor points at?

### ISSUE THREAD

**Issue by orionlee** [codemirror/CodeMirror#4236]
Consider the following markdown text excerpt
```
...
- see: [CodeMirror doc](http://codemirror.net/doc/manual.html) for more information.
```

When the user moves the cursor to any position, I'd like to be able to identify the correspond DOM element. E.g., if the cursor moves to the `http://...` url,, I'd like to be able to identify the correspond `<span class="cm-url">(http://...)</span>` element.

Motivational use case:
I am extending markdown mode, so that links (`span.cm-url`) will be shortened in normal case, except when the user moves the cursor or mouse over it, the full link will be shown (and can be edited).

Possible solutions:
- the DOM element of where the cursor is is marked with a new css class, e.g., cm-current-cursor. In the example above the `<span class="cm-url">..</span>` will become `<span class="cm-current-cursor cm-url">...</span>` .  I can then identify it in css to display the link differently.
- CM provides a method `getDOMElementAt(Pos)`. So programmatically I can access the element by calling  `cm.getDOMElementAt(cm.getCursor()) ` .

Let me know your thoughts. Thanks.

**Comment by marijnh** [comment]
Don't use the DOM for this. Add a class with `markText` when the cursor enters such a link. Directly manipulating DOM nodes owned by CodeMirror isn't supported and will cause all kinds of problems.

**Comment by orionlee** [comment]
@marijnh  Thanks - along with 'cursorActivity' event the issue is resolved.
