### ISSUE TITLE
Multi-line paste resizes CodeMirror instead of creating a scrollbar

### ISSUE THREAD

**Issue by JanWielemaker** [codemirror/CodeMirror#4239]
When pasting content with many lines into a CodeMirror instance, the instance is enlarged instead of creating a scrollbar.   Happens in at least in FF, Chrome and Safari.   Tested using CodeMirror 5.18 and various older versions.

You can see it happening by pasting (^V) enough (say 20 lines) into the bottom-right pane at http://swish.swi-prolog.org/

I assume your test environment easily reproduces this.  If not, I'll try to make a stand-alone page to reproduce the problem.

**Comment by marijnh** [comment]
No, this does not happen in the demos. It only happens when you explicitly make it happen, as in [this demo](http://codemirror.net/demo/resize.html).

**Comment by JanWielemaker** [comment]
Thanks.  You are right.  The editor is displayed inside a `<td>` with height 100%.  In the end I couldn't find a pure CSS way to get everything right and now use some JavaScript intervention that sets the explicit height of CodeMirror and calls a `refresh()` on it.   Not so nice, but not your fault.
