### ISSUE TITLE
VB code formatter

### ISSUE THREAD

**Issue by pedrotvr** [codemirror/CodeMirror#4241]
Hello,

I've been using your plugin in my project to be able to use several language codes in my textarea,

I've implemented the format extension that you have as an example here: http://codemirror.net/2/demo/formatting.html

I would like to have this feature as well for VB.NET code, but I'm having some trouble implementing it.

I'm trying to extend the plugin by using the following code:
`CodeMirror.extendMode("vb", {
    commentStart: "'",
    commentEnd: "'",
    newlineAfterToken: function(type, content, textAfter, state) {
        return /^[\[,{]$/.test(content) || /^}/.test(textAfter);
    }
  });`
  

I understand that you are using a regex expression to achieve the line break but I'm unable to do it for VB.

Thanks in advance for your help

**Comment by marijnh** [comment]
CodeMirror doesn't format code anymore. I don't remember how the old addon that did worked, and I don't support it anymore.
