### ISSUE TITLE
Start in Vim insert mode by default

### ISSUE THREAD

**Issue by manh91** [codemirror/CodeMirror#4246]
I am making Online PHP Debugger using Vim mod. ([http://phpio.net/](http://phpio.net/))

Could you please tell me how to start in Vim insert mode by default?

Thanks in advance.

**Comment by marijnh** [comment]
This isn't the place for support requests. Try the [forum](https://discuss.codemirror.net) for that. 

That being said, the [vim demo](http://codemirror.net/demo/vim.html) is pretty clear:

> The vim keybindings are enabled by including keymap/vim.js and setting the keyMap option to vim.
