### ISSUE TITLE
Scrolling-Width is wrong

### ISSUE THREAD

**Issue by Cr4xy** [codemirror/CodeMirror#4247]
I have the following problem:
![image](https://cloud.githubusercontent.com/assets/6566889/18680345/92db6b10-7f63-11e6-9321-2656a4bc0e36.png)
The scrollbar width is not enough, please help.

**Comment by marijnh** [comment]
What triggers it? Can you give me a minimal HTML page that reproduces the issue?

**Comment by Cr4xy** [comment]
Yes, I uploaded it to http://cr4xy.square7.ch

Thanks for your fast response!

**Comment by Cr4xy** [comment]
Any idea?

**Comment by vincentwoo** [comment]
I suspect this to be related to the bootstrap css you've included - when deleted, I don't see the issue. May be related to border-box, etc.

**Comment by marijnh** [comment]
I'm not seeing anything useful at the URL you linked anymore. If you narrow this down to a specific piece of external CSS, feel free to comment, and I'll investigate further. For now, I'm closing the issue.
