### ISSUE TITLE
Pressing backspace triggers onKeyPress. MS Edge - Windows Mobile 10

### ISSUE THREAD

**Issue by peebeebee** [codemirror/CodeMirror#4253]
Doing a backspace in MS Edge on Windows Mobile 10 triggers `onKeyPress` function with keyCode `8`. This triggers the `updateLineForChanges` and results in `defaultSpecialCharPlaceholder` getting called which adds a `\u8` char that is represented in the editor as a red • 

I might do some more debugging and maybe a bug-fix when I have the time.

**Comment by vtnorton** [comment]
Same here, only on mobile.

**Comment by peebeebee** [comment]
@marijnh : are you sure this solves the bug? 
I haven't checked myself, but I know the following JsBin does not alert while pressing backspace on Edge Mobile: http://jsbin.com/tomoyeliwu/

**Comment by marijnh** [comment]
I am not, but if you describe the bug as a backspace character ending up in the document, it does sound like CodeMirror's keypress handler is running.

**Comment by peebeebee** [comment]
Just checked it out, and it fixes the bug above. but as a whole it is still a buggy experience.
I'll try to do some work on it when I have the time.
