### ISSUE TITLE
Demos on codemirror.org seem to be broken

### ISSUE THREAD

**Issue by floledermann** [codemirror/CodeMirror#4258]
Since a short while, none of the demos on codemirror.org work for me.

E.g. http://codemirror.net/demo/activeline.html - when I click into the editor, nothing happens and in the console I get `Uncaught TypeError: Illegal constructor` in `codemirror.js:6801`.

I checked in current versions of Chrome (53.0.2785.116) and Firefox (47.0.1). Maybe there's something seriously wrong with my setup here, else it's probably a regression affecting all demos.

**Comment by marijnh** [comment]
cc @adrianheine Looks like some import might have gotten crossed?

**Comment by marijnh** [comment]
Since `Selection` is also a built-in global in the browser, our linter didn't catch that missing import.

**Comment by adrianheine** [comment]
That happened to me multiple times while working on the split. Thanks for fixing it!
