### ISSUE TITLE
Question: Inserting files

### ISSUE THREAD

**Issue by skillzzjesse** [codemirror/CodeMirror#4262]
Is it possible to insert a file into the CodeMirror? 

I know there is a method for inserting a string: ```setValue(string)``` But I would like to insert an entire file (such as: ```script.js```), including line numbers etc.

Is this possible?

**Comment by marijnh** [comment]
This is a bug tracker. The place for questions is the [forum](https://discuss.codemirror.net). As for your question, I'm not sure why `setValue` wouldn't work for an entire file.
