### ISSUE TITLE
Suggestion: Search starting right after the result, on repeated Ctrl+F

### ISSUE THREAD

**Issue by dandv** [codemirror/CodeMirror#4263]
After GitHub switched from Ace Editor to CodeMirror, I found it difficult to search for multiple occurrences of the same string. The primary reason is the lack of UI affordances - there are no up/down arrows to go to the previous/next search result (for an example of this UI, see Chrome's Find in page).

Due to a lack of UI and not being familiar with the Ctrl+G shortcut, I would press Ctrl+F again, then Enter. This keeps finding the current result however. IMO it would be more useful if repeated invocations of Ctrl+F would find the *next* result.

**Comment by marijnh** [comment]
CodeMirror's default search addon has a persistent search feature which is more like the browser's default search box. What Github decided to bind to Ctrl-F is not something I can control.
