### ISSUE TITLE
[javascript mode] top-scope declarations are not properly colored later

### ISSUE THREAD

**Issue by leeoniya** [codemirror/CodeMirror#4264]
Hi @marijnh,

In javascript mode, `cm-variable-1` appears to apply to not-yet-known symbols. It looks like this works at function nesting levels > 0 but not at the root level. Here are some examples of `cm-variable-1` that should be marked `cm-variable-2` since they have already been declared in the top scope.

This bug prevents being able to visually catch undeclared/accidental globals.

Hopefully an easy fix, thanks!

![jsvars](https://cloud.githubusercontent.com/assets/43234/18900688/b5b48d8c-8509-11e6-9191-42d6a0c438d1.png)

**Comment by marijnh** [comment]
Pass a `globalVars` option to your JavaScript mode config, and I think you get what you're asking for here.

**Comment by leeoniya** [comment]
@marijnh can you kindly provide and example of how to pass through a `parserConfig` to a specific existing mode at runtime? there is only a single mention of this variable in the manual which relates to authoring new modes. do i need to make a `javascript2` overlay mode like [1] to get this working?

[1] https://github.com/codemirror/CodeMirror/issues/3292#issuecomment-180016581

**Comment by marijnh** [comment]
Set your mode option to `{name: "javascript", localVars: true}`

**Comment by leeoniya** [comment]
got it, thanks for your help.
