### ISSUE TITLE
[javascript mode] declaration hoisting?

### ISSUE THREAD

**Issue by leeoniya** [codemirror/CodeMirror#4265]
Somewhat related to #4264, but this is an enhancment rather than a bug.

Would it be prohibitively expensive to hoist function/var/let/const declarations during parsing so that `cm-variable-1` could be promoted to `cm-variable-2` even when things are out of order?

```js
setTimeout(foo, 100);    // foo should be cm-variable-2

function foo() {  // foo should be cm-def
  x++     // x should be cm-variable-2
}

var x = 0;   // x should be cm-def
```

If it's expensive but simple to add, it could be gated behind a default-off config.

**Comment by marijnh** [comment]
Yes, it would. CodeMirror modes work start-to-end, so there's no way to look ahead.
