### ISSUE TITLE
Ctrl+Space does not trigger the autocomplete anymore.

### ISSUE THREAD

**Issue by amshali** [codemirror/CodeMirror#4270]
Auto complete demos have stopped working. I tried Ctrl+Space on other commands. They don't work either. I could not figure out why.

**Comment by adrianheine** [comment]
Which browser do you use? The autocompletion examples on prosemirror.net work for me in Firefox 49.

**Comment by marijnh** [comment]
(Also in Chrome 52.)

**Comment by amshali** [comment]
Using Chrome 53. This is a very bizarre behavior. I opened an incognito tab just to make sure it's not any of my settings and still doesn't work. That is on my laptop. On my desktop machine it works fine.
I am gonna close this issue since it seems like something specific to my laptop. Sorry.

**Comment by NameIsEward** [comment]
win10 ?

**Comment by aanari** [comment]
Also not working for me in Chrome 63 :(
