### ISSUE TITLE
specialChars not identifying correct regular expression

### ISSUE THREAD

**Issue by drawmyattention** [codemirror/CodeMirror#4271]
I have the following regular expression:

    /\[\[\s?date\(\'([0-9a-zA-Z\s\:\-\+]*)\'(\s?,\s?\'([a-zA-Z \-\:]*)\')?\)\s?\]\]/g

Which matches the following string:

    I went for a walk on '[[date('last week', 'Y-m-d')]]' and '[[ date('today') ]]'

Results can be seen here:

https://regex101.com/r/XC8gQT/2

However, when I try to use the regular expression with ```specialChars```, the text is not replaced as I would expect.

The code I've used is:

```
window.onload = function() {
        editor = CodeMirror.fromTextArea(document.getElementById("query"), {
            lineNumbers: true,
            mode: "text/x-mysql",
            matchBrackets: true,
            specialChars: /\[\[\s?date\(\'([0-9a-zA-Z\s\:\-\+]*)\'(\s?,\s?\'([a-zA-Z \-\:]*)\')?\)\s?\]\]/g,
            specialCharPlaceholder: function(ch) {
                var node = document.createElement("span");
                node.innerHTML = 'it-works';
                node.className = "special";
                node.title = 'It works!';
                return node;
            }
        });
    };
````

**Comment by marijnh** [comment]
`specialChars` should match a _single_ character. I'm not sure what you are aiming for, but replacing a whole sentence with a red dot doesn't seem like useful behavior, so `specialChars` is probably not what you're looking for.

**Comment by drawmyattention** [comment]
Is there something like specialChars that can match a phrase or anything longer than a single character?

The code I have has placeholders, which i'd like to apply some CSS to or add a class. Such a placeholder would be any text between the (bespoke) [[ ]] tags.

**Comment by marijnh** [comment]
You'd use an overlay or a custom mode for that.

**Comment by drawmyattention** [comment]
Could you provide a small code sample to get me started?

**Comment by marijnh** [comment]
Nope, sorry, I am not being paid enough to act as a help desk.
