### ISSUE TITLE
Tabs are lost when hitting enter

### ISSUE THREAD

**Issue by firasdib** [codemirror/CodeMirror#4272]
If you have a string with tabs in it, place the cursor before any tab, and hit enter, the tabs are removed.

![vzh0gd0](https://cloud.githubusercontent.com/assets/1335165/18987824/dfb365d0-8703-11e6-9fe0-a00620de65d8.gif)

I was able to reproduce both on the codemirror website and my own editor.

Is this intended behavior? And if so, can you disable it? Thanks!

**Comment by marijnh** [comment]
The default command bound to enter, `newlineAndIndent`, will reindent the newly created line. If that's not what you want, bind enter to something else.
