### ISSUE TITLE
mode/powershell/powershell.js breaks minification

### ISSUE THREAD

**Issue by jonnybradley** [codemirror/CodeMirror#4274]
Hi,

Small thing, but there is a semicolon missing from mode/powershell/powershell.js on line 34 which breaks javascript minification in our integration of codemirror (in [Tiki](https://tiki.org)).

This is present in 5.19.0 and dev-master, but at least nice and easy to fix! :)

Thanks in advance

**Comment by jonnybradley** [comment]
Sorry, found another one, mode/swift/swift.js has hardly any semicolons in at all :(

P.S. We just updated from version 4.x where everything minified ok, thanks

**Comment by adrianheine** [comment]
That's perfectly correct JavaScript syntax. We are actually moving towards that code-style: #4259. What are you using for minification?

**Comment by jonnybradley** [comment]
Hmm, were still using https://github.com/rgrove/jsmin-php/ and that's really out of date and unmaintained now, guess we need to rebuild our minify system (but not for the current release now, sadly)

Thanks for your reply :)
