### ISSUE TITLE
Haskell mode with autoCloseBrackets appends extra quotes

### ISSUE THREAD

**Issue by DrXyzzy** [codemirror/CodeMirror#4277]
As reported in sagemathinc/smc#972, entering a string into editor while in haskell mode with autoCloseBrackets enabled will cause an extra quotation mark at end of line. Verified that problem exists in CodeMirror version 5.19.0 in Chrome and Firefox.

<img width="255" alt="haskell-quote" src="https://cloud.githubusercontent.com/assets/528072/19018601/738d9c50-882e-11e6-8a24-5194a20bf0cc.png">

**Comment by adrianheine** [comment]
I can reproduce that on the haskell demo with `addon/edit/closebrackets.js` loaded and option `autoCloseBrackets: true`.
