### ISSUE TITLE
Searching across multiple CodeMirror instances

### ISSUE THREAD

**Issue by rgbkrk** [codemirror/CodeMirror#4282]
Are there hooks that would allow me to enable search/replace across multiple CodeMirror instances on a single page?

Let's say I have the following simple page with two CodeMirror instances:

```js
const body = document.querySelector('body')
    
const title = document.createElement('h1')
title.textContent = 'This is a document with multiple CodeMirrors'
body.appendChild(title);
    
const area1 = document.createElement('textarea')
body.appendChild(area1)
const editor1 = CodeMirror.fromTextArea(area1, {
  lineNumbers: true,
})
    
const segway = document.createElement('h2')
segway.textContent = 'Moving on to another editor'
body.appendChild(segway)
    
    
const area2 = document.createElement('textarea')
body.appendChild(area2)
const editor2 = CodeMirror.fromTextArea(area2, {
  lineNumbers: true,
})
```

and that I've included

* `codemirror/addon/search/search`
* `codemirror/addon/search/searchcursor`
* `codemirror/addon/dialog/dialog`

Each CodeMirror instance now has their own search handler when focused on the editor (triggered via ctrl/cmd-f). How could I implement search/replace that works across multiple CodeMirror instances?

There's at least a way to execute a `find` on each editor: `editor.execCommand`. I'm not seeing a way to pass through to it, or to query about what results are available.

[CodePen with example code and imports](http://codepen.io/rgbkrk/pen/yazobB?editors=0010)

[StackOverflow issue with (roughly) the same post](http://stackoverflow.com/questions/39812210/how-can-i-search-across-multiple-codemirror-instances)

[Issue on nteract](https://github.com/nteract/nteract/issues/878)

**Comment by marijnh** [comment]
Nope. You'll have to code that up yourself.

**Comment by rgbkrk** [comment]
I'm happy coding it up, I'm mostly unsure about how to access search across each instance. I suppose I need to look at this as if it's a new addon, following on from `codemirror/addon/search/search`?

**Comment by fonsp** [comment]
(The discussion was continued here: [https://stackoverflow.com/questions/39812210/how-can-i-search-across-multiple-codemirror-instances](https://stackoverflow.com/questions/39812210/how-can-i-search-across-multiple-codemirror-instances))
