### ISSUE TITLE
Markdown mode: setext heading underline not given correct token

### ISSUE THREAD

**Issue by jackycute** [codemirror/CodeMirror#4283]
As CommonMark specified here: http://spec.commonmark.org/0.26/#setext-heading
The setext heading underline is like:
```
title
===
```
or 
```
title
---
```
The "title" text above should also given `cm-heading` token.

This will help us to do style a lot better!
Thanks again.

**Comment by leeoniya** [comment]
see https://github.com/codemirror/CodeMirror/issues/839

**Comment by jackycute** [comment]
@leeoniya Thanks for heads up!
