### ISSUE TITLE
Semantic meaning of applied token classes vary wildly between modes.

### ISSUE THREAD

**Issue by leeoniya** [codemirror/CodeMirror#4284]
I'm discovering while working with javascript & php that the parsers have surprising differences with how they categorize semantically similar tokens. This makes it impossible to rely on a single theme to deliver a uniform experience across multiple languages.

The javascript mode does more-or-less the correct thing. In php `$abc` is a basic variable, but is categorized as `cm-variable-2`, function arguments also get categorized as `cm-variable-2` rather than `cm-def`, `->abc` gets `cm-variable` but should be `cm-property`. javascript mode has no `cm-builtin` classification, for `parseInt`, `Math`, etc.

Is there any interest in adjusting the modes to provide better normalization? Would a pull request be considered for merging if it has to modify existing tests and cause style-related BC?

**Comment by marijnh** [comment]
Improvements to the way the modes categorize things are welcome (such as making PHP properties actually use the property style). But langauges _are_ different, and as such, there's no single consistent way to tokenize them. The PHP mode uses `variable` for function names, and I don't think it's necessarily a bad idea to give $-prefixed variables a different style. The JS mode understands the difference between local and global variables, and uses `variable-2` for that. This is, I think, okay.
