### ISSUE TITLE
Auto indentation doesn't work with K&R C

### ISSUE THREAD

**Issue by lautis0503** [codemirror/CodeMirror#4285]
Code Example:
```
int main(argc, argv)
int argc;
char* argv[];
{
    return(0);
}
```

The indentation of return is manually added.
And there will be no auto indentation all through the function unless in statements like while etc.
This bug should be existed in all the browser.

**Comment by marijnh** [comment]
Confirmed. But since this style has been obsolete for over 20 years, I don't consider it a big problem. If you do, you can try submitting a patch that improves this.
