### ISSUE TITLE
`flattenSpans` affects entire editor and not just specific mode

### ISSUE THREAD

**Issue by firasdib** [codemirror/CodeMirror#4286]
It seems that this _mode specific_ options affects ALL modes and the entire editor, not just that mode. I have several modes running, and an overlay. With the modes that are running I want to combine equal spans, to not create too many in the editor. The overlay however I do not want to do this, so I set `flattenSpans: false` for that overlay mode. However, this seems to affect all marks, modes and overlays. I would have expected this to _only_ affect the rules provided from the overlay with this option set to false.

**Comment by marijnh** [comment]
Multiple modes wrapped in an overlay count as a _single_ mode as far as the editor is concerned, so yes, you can't have one of your overlaid modes have a different behavior wrt this option than the rest.

**Comment by firasdib** [comment]
What about text markers? They are also affected.

**Comment by marijnh** [comment]
`markText` ranges are never flattened, so I'm not sure what you mean by that.

**Comment by firasdib** [comment]
If I mark `{ line: 0, ch: 0 }` until `{ line: 0, ch: 5 }` with the class `foo` the following happens:

1. With a mode that has `flattenSpans: false`: each character in the pos 0-5 is given a span with the class `foo`.
<img width="753" alt="screen shot 2016-10-06 at 20 42 16" src="https://cloud.githubusercontent.com/assets/1335165/19165788/70a8fbee-8c05-11e6-9415-d1b15d24d40e.png">

2. Without a mode that has `flattenSpans: false`: a single span added around the characters at pos 0-5 with the class `foo`.
<img width="735" alt="screen shot 2016-10-06 at 20 42 32" src="https://cloud.githubusercontent.com/assets/1335165/19165792/742317c8-8c05-11e6-95a1-b533979d78d9.png">

**Comment by marijnh** [comment]
Marked classes are added per token, so yes, if you get different tokens, your dom structure will be different.

**Comment by firasdib** [comment]
Ah, I suppose returning null from a overlay (ie, I don't want to style it) makes it a "token" still?

**Comment by marijnh** [comment]
Yes (if you consumed any characters)

**Comment by firasdib** [comment]
Ah, that explains it. Thank you.
