### ISSUE TITLE
Bug: when editing text, quote should only skip if it's the second of a matched pair.

### ISSUE THREAD

**Issue by themrmax** [codemirror/CodeMirror#4287]
I like the auto-insert of matching quotes, and I think it's the desired behaviour to have pressing quote skip over the second of a matching pair, but it's not good (also non-standard afaik, at least in emacs it doesn't do this) to have it for the first, it makes it hard to insert new elements in arrays of strings. To illustrate:

Desired:

    ['i want the cursor to skip over the quote when i'm done']
                                              cursor ->    ^
Undesired:

    ['<-- i am trying to insert a new string in my array to the left here']
    ^ <- cursor

**Comment by marijnh** [comment]
Which mode are you using?

**Comment by takluyver** [comment]
Jumping in on OP's behalf: he is most likely using the Python mode as he originally reported it on Jupyter. I also replicated the behaviour in [this demo](http://codemirror.net/demo/closebrackets.html), which is Javascript.
