### ISSUE TITLE
Add Support for the Color Basic Programming Language

### ISSUE THREAD

**Issue by vincrusher** [codemirror/CodeMirror#4296]
I think support for the Color Basic Programming Language will be great. Color Basic has some easy syntax and it's a programming language I would like to see on Modern Computers.

PS: Adding Extended Color Basic will be awesome as well.

**Comment by marijnh** [comment]
We're not taking feature requests for modes (and are, in fact, moving to have less modes in the main distribution and more of them maintained externally)
