### ISSUE TITLE
[java] enum indentation regression

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4310]
Pressing enter after the comma sets the next line's indentation as 6 spaces rather than the expected 2.

```java

public enum Enum {
  VAL1,
}
```

I am led to believe this is a relatively recent regression (order of weeks or months).

**Comment by marijnh** [comment]
This broke due to patch 8a48219a5ec for #3558, a year ago. Let me see if I can find a workaround.
