### ISSUE TITLE
[merge] revert arrows should be sticky and not scroll off the visible area if the diff is still visible

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4314]
Repro:
1. Visit http://codemirror.net/demo/merge.html
2. scroll slightly so that the top of the first multiline diff is off the top of the screen.
3. Click on "align" so that the connect option is set to "align".

Expected:
Merge arrows should not scroll off the top of the screen.

Actual:
They scroll off the top of the screen. The visual impact is worse when connect set to "align".

**Comment by takamori** [comment]
(also, the impact is worse with a large diff chunk)

**Comment by marijnh** [comment]
This'd be a bit of a pain to implement, and it's not terribly problematic (scroll to the top of the chunk to revert it), so I don't agree with your '_should_'. A pull request (if clean) would be welcome, though.
