### ISSUE TITLE
[merge] diff region connectors don't display with connect option set to "align"

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4316]
Repro steps:
1. Open http://codemirror.net/demo/merge.html
2. Note curved diff region connectors.
3. Click on "align"

Expected:
- Connectors still appear as rectangular indicators.

Actual:
- Connectors are not rendered.

This can make it harder to spot differences between files, especially if there is whitespace below the region of the diff on the side where there are fewer lines.

**Comment by marijnh** [comment]
Doesn't the styling on the changed chunks make it rather easy to spot changes? If you want to submit a PR for this, sure, but I don't consider this a big enough problem to work on it myself.
