### ISSUE TITLE
CSS submode text/x-gss doesn't indent inside @component

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4324]
Inside of an @component context, the contents should be indented, but do not do so. For instance, within the following, pressing enter after the curly brace should indent, but currently do not:

@component {
}

**Comment by marijnh** [comment]
@dbarnett Want to take a look at this?

**Comment by dbarnett** [comment]
Intentional behavior.

"the contents should be indented" — you mean because of some spec, or because you just expect things inside of curly braces to be indented? Not indenting inside \@component is an intentional choice, and at least in Google's GSS code that's standard convention.

**Comment by takamori** [comment]
ah, you're right. I should have checked on convention first, thanks.
