### ISSUE TITLE
Language Server Protocol Integration

### ISSUE THREAD

**Issue by akosyakov** [codemirror/CodeMirror#4326]
Microsoft has announced [Language Server Protocol](https://github.com/Microsoft/language-server-protocol). Is there any plans to provide integration with it?

**Comment by marijnh** [comment]
Not on my end. If Tern's functionality can be expressed in the vocabulary of that protocol, I'd be neat if someone writes a wrapper, but I'm not going to be the one to do that.

**Comment by akosyakov** [comment]
@marijnh maybe i misunderstood you, but I did not mean to server Tern as a language server but rather let CodeMirror make use of [other language servers](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations#language-servers).

**Comment by marijnh** [comment]
Ah, I see, that would also be possible, I guess, but you'd probably want to write a completely new plugin for it.

**Comment by akosyakov** [comment]
Could we have it open and see whether somebody will step forward to implement such plugin?

**Comment by marijnh** [comment]
No. I am not accepting new plugins into the main distribution, so it'd have to be done as a separate project.

**Comment by thorade** [comment]
@akosyakov do you know whether such a plugin is by now available somewhere?

**Comment by ManishAgrawal1410** [comment]
Codemirror is planning to integrate with LSP server near future ? Can anyone update?

**Comment by thorade** [comment]
Here is a blog post and github repo by Wylie Conlon, 
describing some work on teaching LSP to CodeMirror:
http://www.blog.wylie.su/codemirror-lsp
https://github.com/wylieconlon/lsp-editor-adapter

**Comment by gsw945** [comment]
for CodeMirror 6, I found [Language Server Plugin for CodeMirror 6](https://github.com/FurqanSoftware/codemirror-languageserver)
