### ISSUE TITLE
Bower does not work anymore after updating to 5.20.0

### ISSUE THREAD

**Issue by bogdanalexe90** [codemirror/CodeMirror#4327]

**Comment by marijnh** [comment]
That's because bower's approach of installing directly from github is fundamentally unsuited for most modern JS projects. If someone wants to set up a workaround (outside of this repo), that'd be nice. If not, I'll just get rid of bower.json as well.

**Comment by bogdanalexe90** [comment]
Agree with you about the broken mechanism. 
But you should at least mark this change as a breaking change since it will break apps that rely on bower.

**Comment by marijnh** [comment]
As in doing a major version bump? Despite accepting bower.json, we never committed to supporting Bower, so I don't think this is worth bumping to 6.0.
