### ISSUE TITLE
lib/codemirror.js is missing

### ISSUE THREAD

**Issue by BorisTB** [codemirror/CodeMirror#4330]
I think lib/codemirror.js is missing in the latest version

**Comment by marijnh** [comment]
See the [release announcement](https://discuss.codemirror.net/t/release-5-20-0/961) and #4328

**Comment by BorisTB** [comment]
Oh I'm sorry I've missed that. Our build failed on it so I guess we'll have to use 5.19 until we change our build code.

Thanks for fast response :)
