### ISSUE TITLE
Version 5.20.0 breaks bower installation

### ISSUE THREAD

**Issue by mattgodbolt** [codemirror/CodeMirror#4331]
I use CodeMirror with requirejs and the following config (as recommended in the docs):

    packages: [{
        name: "codemirror",
        location: "ext/codemirror",
        main: "lib/codemirror"
    }],

Since upgrading to 5.20, I now get errors of the form:

```
Tracing dependencies for: main
Error: ENOENT: no such file or directory, open '/home/mgodbolt/dev/gcc-explorer/out/dist/ext/codemirror/lib/codemirror.js'
In module tree:
    main
      compiler
```

Is there a quick fix for this? Maybe the `packages` list needs an update, but I'm not sure quite how that part of requirejs works.

Thanks!

**Comment by marijnh** [comment]
Bower is broken with packages that have a build step. See #4328
