### ISSUE TITLE
documented build method is insufficient

### ISSUE THREAD

**Issue by michael-ts** [codemirror/CodeMirror#4333]
Ok, so in the distant past I downloaded a codemirror.js file (version 4.0.4) and was well on my way to using it.  Today I decided I should probably update to the latest version, and apparently it is no longer so easy to start using CodeMirror.

The quickstart is insufficient for me to figure out what I am supposed to do.  Happily I already have node 6.6 installed, but "npm install && npm build" don't look right to me.  I have just enough experience with using npm to know that "install" always requires an argument (and not enough to know what it means when you don't specify an argument).  However, it appears that I can "npm install https://github.com/codemirror/codemirror".  When I do this it actually appears to install correctly under my node_modules subdirectory.

However, I haven't been able to actually build the "lib/codemirror.js" file.  I have tried "npm build" by itself.  This took almost no time to run, and resulted in nothing happening as far as I could tell.  I tried "npm build https://github.com/codemirror/codemirror" but this produced errors as it thought the URL was a sub-directory.  I tried "npm build codemirror" but it seemed to think codemirror was a direct sub-directory so I tried "npm build node_modules/codemirror".   This ran almost instantly with no messages and appears to have done nothing.

So, how do I actually build codemirror?  It would be helpful if the documentation was updated with commands that would actually work.

**Comment by bvs90** [comment]
We use Angular-UI-Codemirror and the codemirror.js file is not being created and hence breaking our builds.

**Comment by pselden** [comment]
https://github.com/codemirror/CodeMirror/issues/4333#issuecomment-255184832: I think it has to do with #4334

**Comment by michael-ts** [comment]
@pselden Is the documented build method making some assumptions about what build process you are using?  I'm not using anything like bower (that I'm aware of), only npm - I'm just literally (trying) following the directions on the main page.

**Comment by pselden** [comment]
@michael-ts -- if you install via npm -- "npm install codemirror" it will install the pre-built version into your node_modules folder (should have a file at lib/codemirror.js).

It's only if you install via the url directly (or clone from git) that you need to run the build process.

If you _do_ want to run the build process, you'll have to change directories to be inside of codemirror and then run "npm install && npm run build"

(the npm install without an argument tells npm to look at the package.json for dependencies).

However, in your case just run `npm install codemirror` and see that it's prebuilt

**Comment by marijnh** [comment]
There was a typo in the README, the correct command to build is `npm run build`. Attached patch corrects this.

As for the bower issues, see #4328

**Comment by michael-ts** [comment]
@pselden thanks, the part of having to run it directly in the node_modules/codemirror directory was the big one I wasn't aware of.
