### ISSUE TITLE
lib/codemirror.js is missing?

### ISSUE THREAD

**Issue by ultrablue** [codemirror/CodeMirror#4337]
Hi:

The file I got from here:
http://codemirror.net/codemirror.zip

and here:
https://github.com/codemirror/CodeMirror/archive/master.zip

Are both missing lib/codemirror.js

```
$ unzip codemirror.zip
.
.
.
$ ls codemirror-5.20.0/lib/
codemirror.css
```

Thanks!
Greg

**Comment by marijnh** [comment]
> http://codemirror.net/codemirror.zip

This one's fixed. The file from github is a zip of the repository, so it indeed won't have the built file.

**Comment by ultrablue** [comment]
Confirmed, thank you!!!!!!!!!
