### ISSUE TITLE
Remove all references to marker-offset

### ISSUE THREAD

**Issue by Manishearth** [codemirror/CodeMirror#4340]
It's a property from an old draft spec that nobody implements (Firefox only parses it, doesn't do anything with it). Being removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1311959

**Comment by marijnh** [comment]
You're suggesting that we remove the (single) occurrence of this from `mode/css/css.js`, or is there anything more to it?

**Comment by Manishearth** [comment]
Nah, just the one it seems.
