### ISSUE TITLE
No file in the archive "lib/codemirror.js"

### ISSUE THREAD

**Issue by shvad** [codemirror/CodeMirror#4342]
## No file in the archive "lib/codemirror.js" !

**Comment by leeoniya** [comment]
https://github.com/codemirror/CodeMirror/issues?q=is%3Aissue+is%3Aclosed

**Comment by leeoniya** [comment]
@marijnh you should probably keep one of these issues open so it acts as a PSA until things settle.

**Comment by marijnh** [comment]
See #4328
