### ISSUE TITLE
Wrong automatic indentation on Ruby `elsif`

### ISSUE THREAD

**Issue by JasinYip** [codemirror/CodeMirror#4345]
Good day!

Automatic indentation is an amazing feature, but there is something unexpect...

When I use `if .. elsif`, it would not be retracted automaticly:

``` ruby
if foo
  bar
  elsif foofoo
  barbar
end
```

It should be looks like this:

``` ruby
if foo
  bar
elsif foofoo
  barbar
end
```

**Comment by Foolyou** [comment]
https://github.com/codemirror/CodeMirror/blob/master/mode/ruby/ruby.js#L278

It seems there should be some `elsif`,`when` things here.

**Comment by marijnh** [comment]
If I paste your example into http://codemirror.net/mode/ruby/ , select all, and press shift-tab, it indents correctly.

**Comment by JasinYip** [comment]
Maybe I didn't express cleanly...What I mean is when I pressed `elsif`, it should indents automaticaly, not copy-paste thing...
