### ISSUE TITLE
Programmatically insert a gutter

### ISSUE THREAD

**Issue by PirtleShell** [codemirror/CodeMirror#4350]
I'm writing a plugin that I'd like to add a gutter to the CodeMirror instance that's passed to it. I've read around, but this is the only way I can think of to do this:

I can insert one manually into the CodeMirror object:
```js
if (cm.options.gutters) {
    cm.options.gutters.push('myGutter');
} else {
     // there aren't any other gutters
    cm.options.gutters = ['myGutter'];
}
```
and then manually get it to show itself:

1. find the `.Codemirror-gutters` element
2. ensure it's `display` value isn't `none`
3. create and insert into it a `div` with `class='Codemirror-gutter myGutter'`
4. hope it still functions the way gutters inserted with initiating settings work.

Is there a better way to do this? Will this way even work?

**Comment by marijnh** [comment]
You want `cm.setOption("gutters", cm.getOption("gutters").concat("myGutter"))`

**Comment by PirtleShell** [comment]
Thanks! That's much easier. I was too focused on the gutter-specific docs... I should have recognized general option setting was what I needed.

Awesome codebase, BTW! Thank you!
