### ISSUE TITLE
[lint] async linter will crash "change" event handlers if setValue() is called before initial lint completes

### ISSUE THREAD

**Issue by Zalewa** [codemirror/CodeMirror#4351]
Minimal presentation with 3 variants: [lint_async_bug.tar.gz](https://github.com/codemirror/CodeMirror/files/553144/lint_async_bug.tar.gz)

There's a call to undefined function when handling "change" events on setValue() when an async lint is in progress. The conditions for this to occur must be following:
1. Current mode must use a linter that uses 'async' mode.
2. Linter must take some amount of time to execute, ie. the lint function cannot directly call the callback(), but at least must sleep a little with setTimeout().
3. A on("change") handler must be set on the CodeMirror instance
4. setValue() must be called on the CodeMirror instance, but it must be called before the initial lint completes.

The provided example has 3 index.html files, 1 provides example of the crash, 2 others either disable the "change" handler or make the setValue() occur after the lint completes, thus avoiding the crash. I have created a fake async inter that sleeps for 200ms before calling the callback().

**Comment by marijnh** [comment]
Patch d7b1370ca45d seems to solve this.
