### ISSUE TITLE
[merge] Connect='align' does not align properly sometimes in 3-way merge

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4353]
With the following content in a 3-way merge:
LEFT: Ant, Camel, Deer  (each on separate lines)
CENTER: Ant, Bear, Camel, Deer
RIGHT: Ant, Deer

The resulting alignment is:
LEFT..... | CENTER | RIGHT
1 Ant..... | 1 Ant..... | 1 Ant
............. | 2 Bear... |
2 Camel | 3 Camel |
............. | 4 Deer.. | 2 Deer
3 Deer

rather than the expected alignment
LEFT..... | CENTER | RIGHT
1 Ant..... | 1 Ant..... | 1 Ant
............. | 2 Bear... |
2 Camel | 3 Camel |
3 Deer... | 4 Deer.. | 2 Deer

and with a larger gap, the effect gets worse; if the content is
LEFT: Ant, Deer, Elk
CENTER: Ant, Bear, Camel, Deer, Elk
RIGHT: Ant, Elk

Then on the left side, the gap between Deer and Elk turns into 2 spaces.

**Comment by takamori** [comment]
The same issue also occurs for the center if you swap left and center in the examples above. The issue does **not** occur if you swap the left and right, however.

**Comment by takamori** [comment]
Thanks, but unfortunately, this still repros after the above commits with the following attached files (sorry, but these are obfuscated and rather large). 

Left line 104, Center line 169, and Right line 168 have the same content, but are
1) placed separately, and
2) have a large gap inserted in the middle spanning all three panes, weirdly.

Oddly, adding a single line of diff to the top (e.g. LEFT, CENTER, RIGHT) makes the gap go away, so unfortunately it seems pretty hard to create a simple repro (I wasn't able to create one based on my prior example, but maybe I missed the key factors that made a difference).

[left.txt](https://github.com/codemirror/CodeMirror/files/565389/left.txt)
[center.txt](https://github.com/codemirror/CodeMirror/files/565390/center.txt)
[right.txt](https://github.com/codemirror/CodeMirror/files/565391/right.txt)

**Comment by takamori** [comment]
Looks like I managed to create a case where it's not aligned while working on creating a test case for my other bug: https://jsfiddle.net/Lyeykf0w/

**Comment by marijnh** [comment]
Apologies. My fix broke the code in a new way. The new patch I attached should solve that.

**Comment by takamori** [comment]
Yep, it looks fixed now.
