### ISSUE TITLE
[markdown] List indentation with tab

### ISSUE THREAD

**Issue by joel-porquet** [codemirror/CodeMirror#4355]
Hi,

I've started the Laverna note-taking webapp, which uses CodeMirror as its markdown editor. I noticed a behavior that seems to come from CodeMirror since I can reproduce it in the markdown demo.

Basically, when I'm writing a bullet list, pressing `<enter>` at the end of an item generates a new item below, which also starts with a bullet. Eg:

```
* my first item<enter>
* <cursor>
```

Currently, pressing `<tab>` only pushed the cursor further, without touching the bullet item:

```
* my first item
*    <cursor>
```

Now, it would be great if pressing `<tab>` could indent this new bullet item so that it actually becomes a sub-item:

```
* my first item
    * <cursor>
```

And conversely, pressing `<shift-tab>` would unindent the bullet item.

Thanks!

**Comment by sbruchmann** [comment]
The [continuelist addon](https://codemirror.net/addon/edit/continuelist.js) should be a good starting point for an implementation of the requested behavior.

**Comment by marijnh** [comment]
Indeed, you can add this as optional behavior to continuelist if you want, and submit a pull request, but I'm not taking feature requests, so I'm closing this issue.
