### ISSUE TITLE
Incorrect indentation in Julia v0.5

### ISSUE THREAD

**Issue by juliohm** [codemirror/CodeMirror#4356]
In Julia v0.5 we can write:

``` julia
a = indmax(rand() for i=1:3)
```

that is, we can avoid allocating memory in an array as it used to be the case in Julia v0.4:

``` julia
a = indmax([rand() for i=1:3])
```

The new syntax causes incorrect indentation when the ENTER key is pressed:

``` julia
a = indmax(rand() for i=1:3)
    # incorrect indentation
```

**Comment by marijnh** [comment]
@malmaud or @pabloferz,  want to take a look at this?

**Comment by juliohm** [comment]
BTW, this issue is annoying for everyone using Jupyter notebooks with Julia v0.5.

**Comment by juliohm** [comment]
Can this issue be closed?

**Comment by marijnh** [comment]
Looks like it!
