### ISSUE TITLE
How to use bare parser?

### ISSUE THREAD

**Issue by nickkolok** [codemirror/CodeMirror#4360]
Greetings from Russia, comrads!

CodeMirror parses code to highlight it. So, how can I get intermediate result of parsing - only list or tree of nodes? For example, for LaTeX:

```
[
   {type: 'tag',text:'\textbf'},
   {type: 'plain', text: 'word'},
]
```

**Comment by marijnh** [comment]
The [runmode addon](http://codemirror.net/doc/manual.html#addon_runmode).
