### ISSUE TITLE
codeMirror.mergeView is not a function in react and ant-design

### ISSUE THREAD

**Issue by zoufegnrui921017** [codemirror/CodeMirror#4362]
what i imported in my project are:
`require('../../../common/codemirror/lib/codemirror.css');
require ('../../../common/codemirror/lib/codemirror.js');
require('../../../common/codemirror/lib/diff_match_patch.js');
const codeMirror = require('../../../common/codemirror/lib/merge.js');
require('../../../common/codemirror/mode/clike/clike.js');
require('../../../common/codemirror/lib/merge.css');`

and using:
`const target = document.getElementById('viewCompare');
    codeMirror.mergeView(target, {
      value: this.state.data.branchCtx,
      origLeft: null,
      orig: this.state.data.trunkCtx,
      lineNumbers: true,
      mode: 'text/x-java',
      highlightDifferences: true,
      lineWrapping: true,
      readOnly: true,
    });
`
before i writed this codes with ES6,i used writed the same codes with ES5, and one more different is to ues es5,i using codemirror.js  in a unique web,but now i writed in a modules ,so, it here wrong??

**Comment by marijnh** [comment]
> `const codeMirror = require('../../../common/codemirror/lib/merge.js');`

That's not how the merge view works. It extends the existing `CodeMirror` module, so you'll want to save the result of requiring `codemirror.js`.
