### ISSUE TITLE
C++ mode treats // in include paths as a comment.

### ISSUE THREAD

**Issue by alur** [codemirror/CodeMirror#4363]
Modifying the C++ example on https://codemirror.net/mode/clike/index.html a little,
![screenshot from 2016-11-01 14 57 24](https://cloud.githubusercontent.com/assets/1925047/19909233/e44e4c14-a043-11e6-98d2-e3e0ade59388.png)
Mistakenly treats //util.h as a comment.

Not that there is a good reason to have // in a file path, but it's a little distracting while editing :)

**Comment by marijnh** [comment]
The mode doesn't tokenize strings in preprocessor directives, since it's not clear how those are going to be used. I think this minor quirk isn't enough of a reason to start trying to do that.
