### ISSUE TITLE
[merge] revert arrows aren't aligned properly sometimes

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4364]
Sometimes, the arrows are placed in weird places. See https://jsfiddle.net/Lyeykf0w/

In the left side, the 2nd arrow is for the bottom diff but is not aligned anywhere near the bottom diff.
In the right side, the 2nd arrow is for the bottom diff but is placed somewhat higher than one might expect.

**Comment by takamori** [comment]
I forgot to note that if you further click on the bottom left revert arrow, the arrow's new position also seems odd.

**Comment by marijnh** [comment]
Could you see whether attached patches help?

**Comment by takamori** [comment]
As far as I can tell, it looks much better, thanks!
