### ISSUE TITLE
cm.setGutterMarker and cm.clearGutter seem like doc methods, not cm methods

### ISSUE THREAD

**Issue by tberman** [codemirror/CodeMirror#4369]
I can move them myself if the patch would be accepted, opening the issue to get a 👍 before doing it and to check to see if I am missing something that keeps them on the editor.

**Comment by tberman** [comment]
cm.lineInfo and maybe cm.addWidget (although the scrollIntoView bit only makes sense on the editor)

**Comment by marijnh** [comment]
`addWidget` should definitely stay in the `CodeMirror` class, since it directly manipulates the DOM. The others, I think you're right, and I'd accept a PR that moves them and updates the docs.

**Comment by marijnh** [comment]
Done in #4372
