### ISSUE TITLE
load from file path

### ISSUE THREAD

**Issue by Alidad3250** [codemirror/CodeMirror#4373]
Hi, can someone help me with code, 	
I have a PHP file that involved with codemirror which works great, but I want each text area to load the code from other file using PHP like index.php, main.css, main.js, and show preview from all of those files to combines.

I have tried everything I could even try with .js codemirror js file, but not successful. 

My question is that how can write that code inside of each text area to link another page! 

many thanks.

AM

**Comment by marijnh** [comment]
Hi. I don't quite understand your question, but it looks like a request for help, rather than a bug report. This isn't the place for that. Maybe try stackoverflow.com

**Comment by Alidad3250** [comment]
sorry fro confusing...I reported to the stackoverflow.com please see that page...
http://stackoverflow.com/questions/40493728/how-to-load-code-using-codemirror

What I'm trying to say is that let say that I have .css file name shopping.css, and I want .css text area from codemirror to load the code from shopping.css for me to see or change. 

somewhere where I need to put file path name to link to another page ...

hope is clear what I'm trying to say!

AM
