### ISSUE TITLE
preview breaks page by reloading page all the time

### ISSUE THREAD

**Issue by enemijs1** [codemirror/CodeMirror#4377]
Hi, the problem is associated with a preview visualisation when I have **predefined html with head tags** in textarea block, it constantly keeps reloading the page. 
If i dont have predefined html, and later on paste it manually, it shows preview just fine. 
And if i use predefined content **without head tags**, it works just fine.
What would cause the problem?

` <form><textarea id="code" name="code" placeholder="Paste your code here"><html><head></head></html></textarea></form>`

`this.editor = CodeMirror.fromTextArea(
                document.getElementById('code'), {
                    mode: 'htmlmixed',
                    tabsize: 4,
                    lineNumbers: true,
                }
);`

**Comment by marijnh** [comment]
CodeMirror doesn't reload the page it's in, so the problem is most likely elsewhere.
