### ISSUE TITLE
doc.indexFromPos fails on change.to at end-of-line

### ISSUE THREAD

**Issue by ian-r-rose** [codemirror/CodeMirror#4378]
I want to get the absolute indices of `change.from` and `change.to` upon changes to the document.
A minimal example is given here:

```
<link rel="stylesheet" href="lib/codemirror.css">
<script src="lib/codemirror.js"></script>
<form style="position: relative; margin-top: .5em;"><textarea id=demotext>
Helloo worldd
</textarea>
<script>
  var editor = CodeMirror.fromTextArea(demotext, {
          lineNumbers: true
            });
  doc = editor.getDoc();
  CodeMirror.on(doc, 'change', (instance, change)=> {
    console.log(doc.indexFromPos(change.from), doc.indexFromPos(change.to));
  });
</script>
```
According to the documentation, the change positions are given in the pre-change coordinate system,
and this is true. However, when converting to the absolute index, these change positions are clipped to 
the post-change coordinate system, which can give the wrong result.

By way of example, deleting the second `o` in `Helloo` gives the output
```
5 6
```
as expected. But deleting the second `d` in `worldd` gives the output
```
12 12
```
which is not correct.

**Comment by marijnh** [comment]
>  However, when converting to the absolute index, these change positions are clipped to the post-change coordinate system, which can give the wrong result.

Yes, changing to indices uses the current document, which will be the wrong document for the old position. This isn't something CodeMirror can help -- you need the proper document to be able to map from a position to an index.
