### ISSUE TITLE
Incorrect class names

### ISSUE THREAD

**Issue by simonlast** [codemirror/CodeMirror#4379]
I am embedding code mirror, version 5.20.2, and am seeing strange class names. I never see .cm-variable-2, .cm-variable-3, or .cm-def, as in the example on the site for clike mode.
My embed:
![image](https://cloud.githubusercontent.com/assets/1704018/20199830/287ddf38-a762-11e6-9dda-f3e34f1dfc07.png)
The site:
![image](https://cloud.githubusercontent.com/assets/1704018/20199839/35e7271a-a762-11e6-985b-75ec7af759b7.png)

These are my codemirror options:

		{
		  "lineNumbers": true,
		  "lineWrapping": true,
		  "fixedGutter": false,
		  "theme": "eclipse",
		  "inputStyle": "textarea",
		  "tabSize": 2,
		  "value": "",
		  "mode": "clike",
		  "indentUnit": 2,
		  "indentWithTabs": false,
		  "smartIndent": true,
		  "lineSeparator": null,
		  "specialChars": {},
		  "electricChars": true,
		  "spellcheck": false,
		  "rtlMoveVisually": true,
		  "wholeLineUpdateBefore": true,
		  "keyMap": "default",
		  "extraKeys": null,
		  "gutters": [
		    "CodeMirror-linenumbers"
		  ],
		  "coverGutterNextToScrollbar": false,
		  "scrollbarStyle": "native",
		  "firstLineNumber": 1,
		  "showCursorWhenSelecting": false,
		  "resetSelectionOnContextMenu": true,
		  "lineWiseCopyCut": true,
		  "readOnly": false,
		  "disableInput": false,
		  "dragDrop": true,
		  "allowDropFileTypes": null,
		  "cursorBlinkRate": 530,
		  "cursorScrollMargin": 0,
		  "cursorHeight": 1,
		  "singleCursorHeightPerLine": true,
		  "workTime": 100,
		  "workDelay": 100,
		  "flattenSpans": true,
		  "addModeClass": false,
		  "pollInterval": 100,
		  "undoDepth": 200,
		  "historyEventDelay": 1250,
		  "viewportMargin": 10,
		  "maxHighlightLength": 10000,
		  "moveInputWithCursor": true,
		  "tabindex": null,
		  "autofocus": null
		}

Am I doing something wrong?

**Comment by simonlast** [comment]
These are my codemirror options:

`{
  "lineNumbers": true,
  "lineWrapping": true,
  "fixedGutter": false,
  "theme": "eclipse",
  "inputStyle": "textarea",
  "tabSize": 2,
  "value": "",
  "mode": "clike",
  "indentUnit": 2,
  "indentWithTabs": false,
  "smartIndent": true,
  "lineSeparator": null,
  "specialChars": {},
  "electricChars": true,
  "spellcheck": false,
  "rtlMoveVisually": true,
  "wholeLineUpdateBefore": true,
  "keyMap": "default",
  "extraKeys": null,
  "gutters": [
    "CodeMirror-linenumbers"
  ],
  "coverGutterNextToScrollbar": false,
  "scrollbarStyle": "native",
  "firstLineNumber": 1,
  "showCursorWhenSelecting": false,
  "resetSelectionOnContextMenu": true,
  "lineWiseCopyCut": true,
  "readOnly": false,
  "disableInput": false,
  "dragDrop": true,
  "allowDropFileTypes": null,
  "cursorBlinkRate": 530,
  "cursorScrollMargin": 0,
  "cursorHeight": 1,
  "singleCursorHeightPerLine": true,
  "workTime": 100,
  "workDelay": 100,
  "flattenSpans": true,
  "addModeClass": false,
  "pollInterval": 100,
  "undoDepth": 200,
  "historyEventDelay": 1250,
  "viewportMargin": 10,
  "maxHighlightLength": 10000,
  "moveInputWithCursor": true,
  "tabindex": null,
  "autofocus": null
}`

**Comment by marijnh** [comment]
What is strange about these class names? They look like everything is working fine.

**Comment by vincentwoo** [comment]
@simonlast you need to set `mode: "text/x-c++src"`, not just `clike`. `clike` is a general purpose class for highlighting many languages syntactically similar to C, but you have to specify which one you want, still.

**Comment by simonlast** [comment]
Ah, great thank you. That worked.
