### ISSUE TITLE
Julia: end of command literals not recognized

### ISSUE THREAD

**Issue by phipsgabler** [codemirror/CodeMirror#4381]
In Julia mode, the backtick closing a [command literal](http://docs.julialang.org/en/release-0.5/manual/running-external-programs/) seems not to be recognized as such; instead, the rest of the text is treated like a continuation of the literal, like a string:

```
readchomp(`pwd`) * "/bla"
    dostuff()
```

Furthermore, since the closing `)` is ignored, the second line here is automatically indented.

In jupyter, where I discovered this, the next line is at least highlighted normally, although the `)` is still not recognized; in the [web showcase](https://codemirror.net/mode/julia/index.html), the whole rest becomes red.

**Comment by marijnh** [comment]
@pabloferz Could you take a look?

**Comment by marijnh** [comment]
Solved via #4383
