### ISSUE TITLE
How to disable the system alert sound associated with some key binding?

### ISSUE THREAD

**Issue by tamakisquare** [codemirror/CodeMirror#4384]
Not sure if there are any other key binding that does this. But, in my case (Mac OSX), **"ctrl-cmd-Down"** is the particular key binding that triggers an undesirable system alert sound. According to the manual, this key binding isn't used by default, and thus I am puzzled as to what causes the alert sound. And most importantly, I would like to know how to disable it. Thanks.

**Comment by marijnh** [comment]
CodeMirror never plays any sounds, nor does it do anything for ctrl-cmd-down, so I think this is a default behavior of your platform.
