### ISSUE TITLE
npm test & open demo page 404 error

### ISSUE THREAD

**Issue by BernardZhang** [codemirror/CodeMirror#4387]
Hi ,
When I try to build the project as follow steps and occur an issue as the screenshot.
1. npm run install & npm run build 
2. npm test
3. visit demo/lint.html page then occur the error as follow
![image](https://cloud.githubusercontent.com/assets/3273449/20254912/870a2d7c-aa73-11e6-80ae-340bc48991fa.png)

**Comment by marijnh** [comment]
Do `npm install`, not `npm run install`.

**Comment by BernardZhang** [comment]
Hi marijnh,

Do npm install && npm run build also occur the error(404). I think it's not the reason cause the issue.

**Comment by marijnh** [comment]
Works for me. Though note that the error has absolutely nothing to do with you visiting `demo/lint.html`, and I am wondering why you described it that way. That looks like output from `npm test`.

Which node/npm version are you on?

**Comment by BernardZhang** [comment]
Sorry~~, demo/lint.html  just for an example page, others pages under demo folder also occur the issue. Actually i also can show the page normally but after visit the page the node server throws the  404 error which make the node server crashed...
![image](https://cloud.githubusercontent.com/assets/3273449/20263397/74d7ebca-aaa1-11e6-95f3-3a4c23e8c5f3.png)

Node version: v7.0.0

**Comment by marijnh** [comment]
`npm test` runs the test suite, it doesn't start a server you can use from your browser. To view test pages, just open them using the `file:` protocol.

**Comment by BernardZhang** [comment]
Oh~~~ What a foolish issue I asked. Sorry for wasting your time and thanks for your patient reply.
