### ISSUE TITLE
How to make vim mode work with pentadactyl?

### ISSUE THREAD

**Issue by Jichao** [codemirror/CodeMirror#4391]
Firefox vim-link plugin `pentadactyl` capture `esc` , which is conflict to vim mode. Is there any way to get around this?

**Comment by leftaroundabout** [comment]
You can also escape with ctrl-[. Alternatively, in Vimperator, you can press shift+esc to disable all Vimperator keys, then esc to escape the codemirror-vim input mode, then (optional) shift+esc again do activate vimperator. Not optimal and not sure if it also works in Pentadactyl.

**Comment by adrianheine** [comment]
Thanks for the suggestions, @leftaroundabout. I have no idea what we could do in CodeMirror to further mitigate this problem, so I am closing this issue for now. Feel free to comment or reopen if you have a suggestion what we could do :)
