### ISSUE TITLE
Resizing selected text should move the start-marker when the pointer is before the midpoint

### ISSUE THREAD

**Issue by themrmax** [codemirror/CodeMirror#4394]
Raised in http://stackoverflow.com/questions/40609738/how-to-unselect-selected-text-in-jupyter-or-how-to-make-click-drag-always-sele/40622168

If I have this text selected and I Shift-click to the right of the word "link":

![image](https://cloud.githubusercontent.com/assets/8220288/20335467/ed8c8776-ac16-11e6-8395-d20197b18b54.png)

The selected region to changes to 

![image](https://cloud.githubusercontent.com/assets/8220288/20335486/20ca3d54-ac17-11e6-93df-6760c6a464e7.png)

Whereas the usual behaviour I think would be to resize to 

![image](https://cloud.githubusercontent.com/assets/8220288/20335498/3aae2802-ac17-11e6-8bda-c4bf5eb7d8a0.png)
 
using the midpoint of the selected region to decide whether you're trying to trim the front or the back of the selected region.

**Comment by marijnh** [comment]
No, that's not how CodeMirror selections work (not is it how native selections work). The direction you drag in to create the original selection determines which side of the selection is the head, and which is the anchor. The anchor is the point where you started dragging. When you then resize the selection, the head moves, and the anchor stays in place.

**Comment by themrmax** [comment]
@marijnh hmm it's how native selections work on Mac, maybe it's different on Linux/Windows?

**Comment by marijnh** [comment]
Oh, you're right. That's interesting. But CodeMirror is following the head-anchor model.
