### ISSUE TITLE
gfm does not highlight lists without blank line

### ISSUE THREAD

**Issue by noerw** [codemirror/CodeMirror#4395]
`codemirror 5.19.0`

gfm allows lists without a blank line in front of it:

```markdown
im a sentence.
- item 1
- item 2
```

the list highlighting gets applied only with a blank line in front of a list.

**Comment by marijnh** [comment]
CommonMark also [allows](http://spec.commonmark.org/0.27/#example-264) this, so it should be handled in the `markdown` mode. See attached patch.
