### ISSUE TITLE
I can't change the mode

### ISSUE THREAD

**Issue by 7sixer** [codemirror/CodeMirror#4398]
I try to use   `myeditor.setOption('mode','javascript')` for change the mode of my editor but this not work. I read some similars problems in SO [(Like this)](http://stackoverflow.com/questions/19871552/change-codemirror-mode-on-the-fly-through-a-select-menu) but exist a oficial solution ?

I can use other options nice for example: `myeditor.setOption('lineNumbers',true)` work !

**Comment by marijnh** [comment]
Look, unless we know what the problem is, we can't give you a solution. And using `setOption` like that definitely works, if the mode you're enabling is loaded, so double-check that it is, and if that fails, read the manual more carefully.

**Comment by 7sixer** [comment]
Well I try to use Code Mirror with Electron... Perhaps this causes compatibility problems because I only have problems with that function everything else works fine

**Comment by sbruchmann** [comment]
@7sixer I use CodeMirror in Electron without any issues. I’m loading modes via `require`.
