### ISSUE TITLE
CodeMirror.defineSimpleMode is undefined?

### ISSUE THREAD

**Issue by josephrocca** [codemirror/CodeMirror#4399]
Hello :)

I'm trying to get a really simple custom syntax highlighter going, and I found this guide:

https://codemirror.net/demo/simplemode.html

But when I call `CodeMirror.defineSimpleMode`, it's undefined. Here's a jsbin reproducing the problem:

http://jsbin.com/hekibuweve/edit?html,console

Has the simple mode been depreciated or something?

Thanks!

**Comment by marijnh** [comment]
You need to load `addon/mode/simple.js`

**Comment by josephrocca** [comment]
Sorry! I really should have read the first sentence of that guide a bit better. Thanks for the amazing lib.
