### ISSUE TITLE
Syntax highlighting is not working in iPad (Mobile Safari)

### ISSUE THREAD

**Issue by ShawnBaek** [codemirror/CodeMirror#4406]
Syntax highlighting is not working in iPad Safari.

Could you have plan to fix this problem?

**Comment by marijnh** [comment]
If I go to http://codemirror.net with Mobile Safari, the highlighting in the demo works just fine. Where are you testing, and do you get any JavaScript errors?

**Comment by adrianheine** [comment]
Closing this since we cannot reproduce the problem and there was no further feedback.
