### ISSUE TITLE
bower.json is gone

### ISSUE THREAD

**Issue by alexkieling** [codemirror/CodeMirror#4409]
Why has bower.json been removed from the project? Is Bower still a supported way to import the library?

**Comment by marijnh** [comment]
This repository is not a bower distro. You want https://github.com/components/codemirror (though that currently doesn't seem to have a bower.json either).

**Comment by alexkieling** [comment]
Then the Bower registry is misconfigured. It's currently pointing to git://github.com/marijnh/CodeMirror.git, which does not have a bower.json. There was a bower.json on version 5.20.0 of that repository. It's been removed in version 5.20.2. Something is not right.

**Comment by marijnh** [comment]
If I run `bower info codemirror`, it shows me the /components/ repository. Where are you looking?

**Comment by alexkieling** [comment]
I'm looking at the Bower website. Using `bower info codemirror` is a better way to check the repository's URL.
Did you notice that bower.json has been removed in version 5.20.2?

**Comment by marijnh** [comment]
Yes. I removed it, since at that point bower-installing codemirror from the git repo stopped working anyway.

**Comment by alexkieling** [comment]
I have an app that imports codemirror using Bower at the moment. What do you suggest I should do?

**Comment by ex37** [comment]
@marijnh my app was using bower as well, it's very handy using the main field of bower.json to automatically including main files. And it was working very well, till the file was not removed from the repo.
