### ISSUE TITLE
[merge] inconsistent diff chunk calculation between left and right side

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4410]
When the the following 3 files are used in the 3-way merge view, inconsistent alignment is seen when connect='align' and with a missing diff on the right side when connect is not set to 'align'.

Line 3 on the left corresponds to line 5 in the middle and line 3 on the right. But in the 3-way view, with connect=align, line 3 on the left is aligned with line 3 in the middle, but line 3 on the right is aligned with line 5 in the middle. Without connect=align, line 3 on the left matches to lines 3-5 in the center, and line 3-4 in the middle matches to an empty chunk just before line 3 on the right.

It seems to me that this layout is occurring because the diff isn't noticing that line 5 in the middle is the same as line 3 on both the left and right; it only sees it on the right side.

[20161129-left.txt](https://github.com/codemirror/CodeMirror/files/620655/20161129-left.txt)
[20161129-middle.txt](https://github.com/codemirror/CodeMirror/files/620654/20161129-middle.txt)
[20161129-right.txt](https://github.com/codemirror/CodeMirror/files/620653/20161129-right.txt)

**Comment by marijnh** [comment]
This appears to be a bug in the diff_match_patch library. It goes away if I avoid calling the `diff_cleanupSemantic`, which I mostly did because it sounded like the right thing, so attached patch drops that call.

**Comment by jackycute** [comment]
This might related to https://code.google.com/p/google-diff-match-patch/issues/detail?id=67

**Comment by marijnh** [comment]
Probably. That project seems quite dead now, but unfortunately it's still _much_ faster than any alternatives I could find, so switching isn't easy.

**Comment by jackycute** [comment]
I know, just as a reminder 😄
