### ISSUE TITLE
code on multiple lines but one cursor for all of them

### ISSUE THREAD

**Issue by enemijs1** [codemirror/CodeMirror#4411]
Hi, my code splits on multiple lines, but the cursor selects it as one line. What could cause to do like so ?
I need it so the cursor can't select each line separately.

![codemiror1111](https://cloud.githubusercontent.com/assets/6883349/20752332/824527fe-b709-11e6-8535-9520d3226517.png)

**Comment by marijnh** [comment]
Did you enable lineWrapping in the editor, or could it be that you have a CSS style that's overriding CodeMirror's own white-space rule?

**Comment by enemijs1** [comment]
Solution for this, is to add *`lineWrapping: true`,* param for CodeMirror ;)
