### ISSUE TITLE
[Question] Does code mirror support different font size?

### ISSUE THREAD

**Issue by bigopon** [codemirror/CodeMirror#4415]
Sorry if duplicate. If so please provide some links and close.
Suppose I have following block:
```
i want this *BIG* and this -small-
```

in the above block, `*BIG*` would have bigger font size and `-small-` would have smaller font size. Is it doable with codemirror ?

**Comment by marijnh** [comment]
Yes, see http://codemirror.net/demo/variableheight.html

**Comment by bigopon** [comment]
Thanks, what a bout both different height and color for certain block of text ?
