### ISSUE TITLE
Is there an event that indicates mode change for a document?

### ISSUE THREAD

**Issue by akosyakov** [codemirror/CodeMirror#4417]
If not how one can be notified when a mode is changed?

**Comment by vincentwoo** [comment]
Isn't the programmer implementing CodeMirror fully in control of when the mode changes? The mode should only change when you tell it to with `setOption`, no? Why do you need an event?

**Comment by akosyakov** [comment]
@vincentwoo nope, if you are building complex system and plugins can change a mime type and you should react on it

generally it would be nice to have an event that options changed

**Comment by marijnh** [comment]
Attached patch adds an [`optionChange` event](http://codemirror.net/doc/manual.html#event_optionChange) for this purpose.
