### ISSUE TITLE
Shift Tab will decrease indent but only preserves auto-indented code, not manual tab or space indents

### ISSUE THREAD

**Issue by MattQlik** [codemirror/CodeMirror#4420]
![shifttabcodemirror2](https://cloud.githubusercontent.com/assets/15639776/20899054/c90cdcae-baf6-11e6-8b61-1fc1a1fa0571.gif)

As you can see in the gif above, all indentation is preserved when tabbing the whole selection to the right but when shift tabbing back again the manually indented text is all moved to the left with no preservation of the original indentation. This is Chrome on Mac but I've also tested Edge on Win10 and found the same issue.

**Comment by marijnh** [comment]
You're not 'shift tabbing back', you're pressing shift-tab, which is bound to `indentAuto` by default. You can change keybindings in your own setup (you want the `indentLess` command, which is ctrl-[ by default).
