### ISSUE TITLE
Syntax Highlight: Xojo

### ISSUE THREAD

**Issue by neu1886** [codemirror/CodeMirror#4422]
Xojo is a more advanced Basic Language. Wohls be nice to have a Syntax highlight Support for it. www.xojo.com

https://github.com/thommcgrath/XojoSyntaxColorizer

**Comment by marijnh** [comment]
We're not adding new languages. If you need this, your best bet is to write it yourself and publish it as a separate package.

**Comment by neu1886** [comment]
I would love, but how can i integrate it by myself?

**Comment by marijnh** [comment]
What do you mean by 'integrate'?

**Comment by neu1886** [comment]
I work with the Typora Markdown-Editor. And they use CodeMirror for syntax highlight. Here is a list of supported Languages [http://support.typora.io/Code-Fences-Language-Support/](http://support.typora.io/Code-Fences-Language-Support/). At the end of the page, they wrote

> If the language is not supported on http://codemirror.net/mode/, please check https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list for adding syntax highlight on CodeMirror. After it is supported by CodeMirror, Typora will follow.

And it would be very nice, if i can highlight Xojo-Sourcecode.

**Comment by marijnh** [comment]
Yeah, they're going to have to change their approach. Putting the burden of maintaining modes for every language under the sun on me isn't scaling very well, so I'm moving to a model where I encourage people to maintain language modes _separately_.
