### ISSUE TITLE
SQL-hint: A way to define nested columns for hintOptions

### ISSUE THREAD

**Issue by v-gerasimov** [codemirror/CodeMirror#4430]
I have the next table that name is "foo":
|&nbsp;a&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;c&nbsp;|&nbsp;d&nbsp;|
|&nbsp;1&nbsp;|&nbsp;2&nbsp;|&nbsp;3&nbsp;|

`c` and `d` are nested columns of `b`. So when I use SQL-hint I can get a hint only for first level column e.g. "foo.a" or "foo.b", but when I try to get a hint of the second level column I don't get any hints. 

I think it would be great to define `tables` like that:
```javascript
{
  tables: {
    "a": [],
    "b": ["c", "d"]
  }
}
```

What do you think? It's a feature request.

**Comment by marijnh** [comment]
I'm not adding features to the sql-hint module -- it's not my own code, and it's already awfully complicated as it is. If you want to work on this, you'll have to fork the addon.
