### ISSUE TITLE
Chrome - Undo/Redo context menu doesn't work

### ISSUE THREAD

**Issue by arbmk** [codemirror/CodeMirror#4433]
In Chrome, when you select Undo or Redo option in RMB context menu, it doesn't work and text in editor stays unchanged. Keyboard shortcuts CTRL+Z and CTRL+Y work fine.
In IE 11 both ways, context menu and keyboard shortcuts, work fine.

Tested on https://codemirror.net/ homepage demo.

**Comment by marijnh** [comment]
This is expected. We can't suppress or rebind the undo/redo items in the context menu, even though they don't work with CodeMirror. Use Ctrl-z/y
