### ISSUE TITLE
Uncaught TypeError - Cannot read property 'focused' of undefined

### ISSUE THREAD

**Issue by jonhue** [codemirror/CodeMirror#4439]
### This issue only occures with version 5.21.0, 5.20.2 runs fine

I have a simple html site including CodeMirror.

https://jsfiddle.net/xsxo0xmd/

Unfortunately I keep getting this error:

    Uncaught TypeError: Cannot read property 'focused' of undefined
    at Yo.prepareSelection (codemirror.js:8236)
    at Yo.focus (codemirror.js:8321)
    at new Po (codemirror.js:7266)
    at Po (codemirror.js:7248)
    at fiddle.jshell.net/:61

The issue is in the third line of the following code (codemirror.js:8236):

    prepareSelection: function() {
        var result = prepareSelection(this.cm, false)
        result.focus = this.cm.state.focused
        return result
    },

It conflicts with `.state.focused`

**Comment by marijnh** [comment]
Attached patch should help.
