### ISSUE TITLE
matchClosing XML mode param

### ISSUE THREAD

**Issue by SnafuB** [codemirror/CodeMirror#4440]
Hi, first of all thank you very much for codemirror, it's a very useful editor !

I would like to edit dust files (Sadly there is no mode for dust templating :/) and I have an issue with the xml - text/html mode, because of dust it cause cm-error in the html and set some line with red background. I see that the param matchClosing exist in the XML mode parameters but I didnt found how to set it to false. I tried a lot of different things but the red background is still here.

```
var mode = {
	name: "text/html",
        matchClosing: false
};
myEditor.setOption("mode", mode);
```

```
{<modules} <!-- Here is the dust js -->
<select id="dynamic_select" class="form-control select" onchange="navigate()"> <!-- All the line is red because it think that there is an error -->
```

Thank you

**Comment by marijnh** [comment]
You have to use `{name: "xml", htmlMode: true, matchClosing: false}`. If you provide a MIME type, the other config params will be forgotten as it is translated to the config registered for that MIME.
