### ISSUE TITLE
Unable to select text

### ISSUE THREAD

**Issue by ramin25** [codemirror/CodeMirror#4445]
I'm having an issue where I am unable to select text in the editor (e.g drag across multiple words or lines). I'm initializing it with `CodeMirror.fromTextArea`. Also I'm using bower to install it. 

Any ideas why this may be the case?

**Comment by marijnh** [comment]
Nope, but if you can submit a minimal demo of the problem, we might be able to figure it out.

**Comment by adrianheine** [comment]
I'm closing this until there's some code to reproduce the issue.
