### ISSUE TITLE
Support for auto line break

### ISSUE THREAD

**Issue by davido** [codemirror/CodeMirror#4446]
We use CodeMirror in Gerrit Code Review for inline edit feature,
where a user can change the commit content in browser. As a part
of this task, it's possible to change commit message. We are restricting
the line length to 80 char and showing vertical line. It would be nice to
auto break the line as it done in vim, once the line is longer than 80 chars
during typing.

To better understand this feature request, I would like that "stable" word in
this editor session in Gerrit Code Review is auto breaked to the next line
by CodeMirror for me during typing: [1].

* [1] http://imgur.com/a/id8S4

**Comment by marijnh** [comment]
You can show lines with the [rulers addon](http://codemirror.net/doc/manual.html#addon_rulers), and might be able to set up the wrapping the way you want using the [hardwrap addon](http://codemirror.net/doc/manual.html#addon_hardwrap).
