### ISSUE TITLE
Linenumber rendering issue

### ISSUE THREAD

**Issue by jonhue** [codemirror/CodeMirror#4449]
_Because all other issues regarding this topic were closed, I opened this new issue._

This is my CodeMirror instance:
[codemirror.txt](https://github.com/JedWatson/react-codemirror/files/661603/codemirror.txt)

I am using autorefresh and simplescrollbars.

I recorded the issue I am experiencing:
[Video](https://vimeo.com/196305264)

When starting the editor, the linenumbers look like:
[Image](https://cloud.githubusercontent.com/assets/2908235/8292513/b467dd48-18f5-11e5-8844-448703f5afc1.png)

**Comment by marijnh** [comment]
Please don't give me videos or an unusable snippet of PHP. Put together a _minimal_ HTML demo that helps me reproduce the problem, so that I can actually debug it.

**Comment by jonhue** [comment]
This piece of css is causing it:
`* { transition: all .15s ease-in; }`

Why does that impact the positioning of the linenumbers?

**Comment by marijnh** [comment]
Because when the editor measures the size of the gutter, it's going to get some in-transition values that don't correspond to the actual layout. You'll want to either disable your transition or call CodeMirror's `refresh` method when it finishes.
