### ISSUE TITLE
Typescript: Broken highlighting of template literals

### ISSUE THREAD

**Issue by JoelEinbinder** [codemirror/CodeMirror#4450]
This code doesn't appear to highlight properly:
```typescript
function test(): Promise<void> {
	var value = 123;
	console.log(`Test [${value}]`);
	return Promise.resolve();
}
```

![image](https://cloud.githubusercontent.com/assets/4624233/21332103/27333634-c5fb-11e6-9c28-3fd5e86a4fd3.png)

**Comment by marijnh** [comment]
It appears to work fine with the current code: http://cm/mode/javascript/typescript.html

**Comment by yesman85** [comment]
@marijnh it's still an issue:

![image](https://user-images.githubusercontent.com/1142915/32009595-c01c4c68-b96c-11e7-954a-9193e905be42.png)

Template literals are valid in ES6 not just TypeScript.

**Comment by zakhenry** [comment]
@yesman85 oddly the issue is somewhat more nuanced - in the example above, if you remove the return type declaration from the TS code, it is ok.

This does not work:
```ts
export class Class2 {

}

export class Class1 implements Class2 {
    private test1(test: string): void {
        return null;
    }

    public async test2(): Promise<void> {
        console.log('destroying tables');

        for (let i = 0; i < 1; i++) {

            const assignment = i;

            const line = `Test [${assignment}]`;

            let a = 0;
        }

        console.log('another log');
    }
}
```

But this does:
```js
export class Class2 {

}

export class Class1 implements Class2 {
    private test1(test: string): void {
        return null;
    }

    public async test2() { // <------ : Promise<void> removed here
        console.log('destroying tables');

        for (let i = 0; i < 1; i++) {

            const assignment = i;

            const line = `Test [${assignment}]`;

            let a = 0;
        }

        console.log('another log');
    }
}
```

**Comment by zakhenry** [comment]
This finding further suggests that Chrome is actually passing the wrong mode to CodeMirror. 

In saying that, I suspect that there is still a bug with CodeMirror as removing one (but not all) of the typescript return types causes unexpected behaviour.

It may be that CodeMirror has undefined behaviour when displaying Typescript as Javascript though, which I suppose is ok too

**Comment by marijnh** [comment]
> In saying that, I suspect that there is still a bug with CodeMirror as removing one (but not all) of the typescript return types causes unexpected behaviour.

No, it isn't.

**Comment by adrianheine** [comment]
I couldn't find a problem with any of the samples on https://codemirror.net/mode/javascript/typescript.html.

**Comment by marijnh** [comment]
Did you intentionally reopen?

**Comment by adrianheine** [comment]
No, I thought I closed, but apparently it has been closed for a year, so ignore my comment.
