### ISSUE TITLE
[javascript mode] RegExp is not highlighted in export statements

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/CodeMirror#4452]
CodeMirror at d756ea1 does not syntax highlight RegExps in export statements:

```js
x = /regex/; // Correct
export /regex/;
export default /regex/;
```

Note: It appears GitHub has the same issue!

**Comment by JosephPecoraro** [comment]
This is probably a pretty rare case to handle, but since I came across it I thought I'd mention it.

**Comment by Victorystick** [comment]
@JosephPecoraro Your second example is invalid syntax, although I understand that you might want the regex to be highlighted regardless. :smiley: 

```js
export /regex/;               // This is a syntax error. What is exported?
export const regex = /regex/; // Valid
export default /regex/;       // Valid
```

**Comment by JosephPecoraro** [comment]
Good point.

Thanks for the quick fixes marijnh!
