### ISSUE TITLE
CodeMirror>5.16 & Safari 10: Strange behavior with spaces

### ISSUE THREAD

**Issue by gnestor** [codemirror/CodeMirror#4454]
After upgrading CodeMirror to 5.21 (from 5.8) in [jupyter/notebook](https://github.com/jupyter/notebook), users started encountering a strange bug on Safari 10. I did some investigating and found that this bug starting affecting notebook when upgrading from CodeMirror 5.16 to 5.17. 

Demo:

![jupytercode_spacing](https://cloud.githubusercontent.com/assets/8238804/21085541/7f410ade-c067-11e6-8dc1-f2c6660b1f47.gif)

One of the users determined that code cells (Python syntax, etc.) exhibit this behavior:

* Immediately after any delimiter
  * e.g. `=`, `,`, `.`, `(`, `)`, `[`, `]`, `{`, `}`, `"`, `'`, etc.
* Not within closed delimiters
* Not within compound statement if closed by `:`
  * e.g. it will occur here `if x =={cursor}`, but not here`if x =={cursor}:`

Markdown cells (Markdown syntax) exhibit this behavior when typing a single space:

* Unless cursor is at start of a new line
* Unless cursor is placed immediately after closed markup delimiter (e.g. `*text*{cursor}`)
* Unless within markup delimiters (e.g. `*text{cursor}*`)

Here is a list commits included in 5.17: https://github.com/codemirror/CodeMirror/commits/master?after=Y3Vyc29yOjiTKo4zLKAvc9OV%2BJnP36dpIuEyKzIwOQ%3D%3D

I have a feeling that this commit might be the culprit although I haven't been able to resolve this by simply reversing the changes in this commit: https://github.com/codemirror/CodeMirror/commit/2c913e5d2914fdc64df80031544a384940006feb

**Comment by marijnh** [comment]
Mind telling us what behavior you're actually referring to? A video isn't much of an explanation -- I see some editing going on, but I have no idea why any of it would be unexpected.

**Comment by minrk** [comment]
The issue is that inserting spaces after certain characters (e.g. `=`) doesn't move the cursor, so it appears that there is no space. As soon as the first non-space character is inserted, the cursor shows up in the right place. The video above illustrates the cursor appearing after `=`, whether the cursor is actually positioned there or one space to the right.

This doesn't happen for everyone or all the time (I've seen it, but can't reproduce it right now), but others can reproduce it reliably right now.

**Comment by gnestor** [comment]
Thanks @minrk. Do you know of any tmpnb or jupyterhub instances that are running 4.3 that would allow @marijnh to reproduce this?

**Comment by jasongrout** [comment]
@gnestor - can you reproduce the behavior in the standard CodeMirror examples, i.e., https://codemirror.net/mode/python/index.html? Also, CodeMirror is now at 5.22.1 - does upgrading Jupyter to 5.22.1 also show the issue?

**Comment by gnestor** [comment]
Nope, I can't reproduce in the CM examples. It's currently not affecting me in notebook 4.3 or master after [downgrading CM to 5.16](https://github.com/jupyter/notebook/pull/2004). 5.22.1 is not available via bower...

**Comment by minrk** [comment]
5.22.1 doesn't appear to exist, but 5.22.2 is on bower now, the first release produced by the automated bower packaging.

**Comment by gnestor** [comment]
I [just tested 5.22.2](https://github.com/jupyter/notebook/issues/2037#issuecomment-272486178) and no luck...

**Comment by gnestor** [comment]
I was able to isolate this bug to this commit: https://github.com/codemirror/CodeMirror/commit/e60f4b7dd88b71e227f79200932c028ca047d78e

@marijnh Any idea why this commit would cause the insertion of single spaces to not move the cursor (and then the cursor jumps to the proper position on a subsequent space)?
