### ISSUE TITLE
Don't highlight keywords that are parts of other words

### ISSUE THREAD

**Issue by Victorystick** [codemirror/CodeMirror#4468]
2bed274 had the side-effect of hightlighting parts of `worrying` in the example below.

![example-soy](https://cloud.githubusercontent.com/assets/703602/21522364/38294260-cd05-11e6-81eb-41f2db72309c.png)

**Comment by dbarnett** [comment]
Looks like you just need to use `\b` in the regex and add a test.

**Comment by Victorystick** [comment]
@dbarnett Right you are.
