### ISSUE TITLE
Potential addon: lint-fix

### ISSUE THREAD

**Issue by ashmind** [codemirror/CodeMirror#4471]
I've made an [addon](https://github.com/ashmind/codemirror-addon-lint-fix) that lets you associate fixes with lint results, and provides UI to invoke these fixes.

Demo:
![codemirror-lint-fix-demo](https://cloud.githubusercontent.com/assets/166396/21532881/bacbf244-cdb9-11e6-842f-305c549c2fe5.gif)
https://ashmind.github.io/codemirror-addon-lint-fix/demo/lint-fix.html

Is this something you would be interested in merging into core?  
Current version has few minor design issues (mostly missing extensibility in `lint`), but I can fix them if I make a PR.

**Comment by marijnh** [comment]
Nice. I'm not accepting any more addons like this into the main distribution, but I encourage you to put it on NPM yourself, as a separate package.

**Comment by ashmind** [comment]
@marijnh Thanks, that was my backup plan.
