### ISSUE TITLE
[shell] outer parentheses don't match in $(( expression )) arithmetic expansion expressions

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4472]
An expression such as $(( $i + 1 )) will not match the outer parenthesis; repro's at http://codemirror.net/mode/shell/index.html

These expressions are mentioned here: https://www.gnu.org/software/bash/manual/html_node/Arithmetic-Expansion.html#Arithmetic-Expansion

**Comment by mtaran-google** [comment]
friendly ping (this should fall under our support contract :)
