### ISSUE TITLE
How to modify the default value for autoCloseBrackets?

### ISSUE THREAD

**Issue by inad9300** [codemirror/CodeMirror#4478]
I'm unable to modify the defaults for the `autoCloseBrackets` option. In particular, I want to include the parenthesis (`()`) on the `explode` list, and include the backticks (`` ` ` ``) in the `pairs` list.

Here is a JSFiddle showing my failing attempt: https://jsfiddle.net/inad9300/1pn46vnn/

**Comment by marijnh** [comment]
Mode-specific configuration (in this case, the one from the JavaScript mode) override the (assumedly language-neutral) settings given in the option. Attached patch adds support for an `override` option that you can enable to prevent this.
