### ISSUE TITLE
Mark `mousewheel` event passive

### ISSUE THREAD

**Issue by yonilerner** [codemirror/CodeMirror#4479]
In recent versions of most popular browsers (I'm currently using Chrome 55.0.2883.95), Passive Event Listeners have been implemented, and it would be nice if some of the CodeMirror events were marked as passive, specifically the `mousewheel` event.

Edit: This will conflict with existing `preventDefault` behavior in event handlers. Maybe its just not possible.

**Comment by marijnh** [comment]
We still need that `preventDefault` for horizontal wheel scrolling, so this isn't that simple.

**Comment by yonilerner** [comment]
Understood.
