### ISSUE TITLE
Cannot move cursor up after soft wrap on punctuation

### ISSUE THREAD

**Issue by jdleesmiller** [codemirror/CodeMirror#4486]
*Steps to reproduce*:

1. Go to http://codemirror.net/demo/variableheight.html (which has soft line wrapping turned on).

2. Enter this string
   ```
   aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
   ```

3. It will wrap:
![image](https://cloud.githubusercontent.com/assets/160829/21717133/f37cf8ec-d406-11e6-82b0-3b93afe04eba.png)

4. Put your cursor after any of the `c`s and press the up arrow.

*Expected behaviour*: cursor goes onto the line above (with the `a`s).

*Observed behaviour*: cursor goes to the start of the line, and pressing the up arrow again does not move the cursor (cursor gets stuck).

If the cursor starts after any of the `b`s, the behaviour is as expected.

If, once the cursor is stuck, you press left or right, the behaviour is as expected after that.

The behaviour seems consistent across Firefox, Chrome and Safari on Mac.

The original use case was a long LaTeX equation with no spaces, and the problem originally occurred when the line soft wrapped on `}{`, rather than a hyphen; it seems that parentheses `)(` will also cause the problem. So, these strings show the same behaviour:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}{bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
```

It's clearly not the end of the world, but it does seem like a bug. HTH!

**Comment by marijnh** [comment]
This is now fixed in the current master branch.
