### ISSUE TITLE
Nested flexbox makes the editors width fail

### ISSUE THREAD

**Issue by teolag** [codemirror/CodeMirror#4487]
When having an editor inside multiple flexbox elements, the editor fails to contain itself inside the parent element.

Check out my [fiddle](https://jsfiddle.net/hhjdx4ze/) to see what I mean.

**Comment by marijnh** [comment]
The exact same problem occurs when you replace the code that creates the editor with

```
document.getElementById("editor").textContent = new Array(1000).join("x")
```

So I don't think you can hold CodeMirror responsible for this. If you don't want it to happen, wrap the editor in a fixed-size element.

**Comment by teolag** [comment]
Hmm... You are right. This seems to be a thing in the browser. Can it be a bug in the implementation of flexbox or am I missing something?

**Comment by marijnh** [comment]
I'm not sure what the behavior is supposed to be in this case, I haven't worked with flexbox enough yet, but I agree that what happens is annoying.

**Comment by Galadirith** [comment]
@teolag @marijnh I've also been experiencing this problem and found this

> By default, flex items won’t shrink below their minimum content size (the length of the longest word or fixed-size element). To change this, set the [min-width](https://www.w3.org/TR/CSS21/visudet.html#propdef-min-width) or [min-height](https://www.w3.org/TR/CSS21/visudet.html#propdef-min-height) property. (See [§4.5 Implied Minimum Size of Flex Items](https://www.w3.org/TR/css-flexbox-1/#min-size-auto).)
> 
> \- [www.w3.org](https://www.w3.org/TR/css-flexbox-1/#flex-common) (original source [matharden](http://stackoverflow.com/questions/12022288/how-to-keep-a-flex-item-from-overflowing-due-to-its-text/12131365#12131365))

This suggests setting `min-width: 0px` would fix this. However it still seems there may be an implementation bug (at least in Chrome) as setting `min-width` doesn't seem to work, however setting `width` does

```css
<nested-flexbox-element-selector> {
  flex: 1 1 auto;
  width: 0px;
}
```

Heres a couple of code pens, the first has a nested flexbox element that should scroll the overflow but doesn't (on Chrome) (http://codepen.io/Galadirith/pen/PpddBM) and heres a fix that does scroll the nested flexbox that overflows (http://codepen.io/Galadirith/pen/aJaaej). The change is on L24 of the css.

I hope that helps.

**Comment by Galadirith** [comment]
@teolag Sorry I completely missed your fiddle. It seems in your case you can fix this with a `min-width:0px` on the `#page` element (https://jsfiddle.net/cvyanjs7/) :D

**Comment by teolag** [comment]
Oh! Thank you @Galadirith!
`min-width: 0` Works great!
(0 is a unit less value and should not have px, em or any unit attached to it)

**Comment by Galadirith** [comment]
> 0 is a unit less value and should not have px, em or any unit attached to it

Thanks so much for the info @teolag I didn't know that. I'm glad the `min-width` worked.
