### ISSUE TITLE
htmlmixed - single elements like <br> aren't recognized

### ISSUE THREAD

**Issue by Aloso** [codemirror/CodeMirror#4489]
Codemirror htmlmixed expects that elements like `<br>`, `<hr>`, `<img>` or `<input>` should be closed, if the tag name is not followed by a slash (`<br/>`).

Note that
```html
<br>
```
is correct html syntax: http://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

Also
```html
<ul>
    <li>List item 1
    <li>List item 2
    <li>List item 3
</ul>
```
doesn't work.

**Comment by marijnh** [comment]
The HTML mode is well aware of self-closing elements. Can you show an example of code that indents badly on http://codemirror.net/mode/htmlmixed/ ?

**Comment by Aloso** [comment]
I figured it out myself - the bug depends on the order in which the js files are included:

    <script type="text/javascript" src="codemirror-5.22.0/mode/xml/xml.js"></script>
    <script type="text/javascript" src="codemirror-5.22.0/mode/htmlmixed/htmlmixed.js"></script>

In this case, the editor renders XML instead of HTML. Since the difference is subtle, it's not that obvious.

**This should be mentioned in the documentation!**

**Comment by marijnh** [comment]
I don't think that's true. If I flip the order in the htmlmixed mode demo, it still works. The problem might be that you're not setting a mode option at all, in which case the editor will default to the first mode that was loaded.

**Comment by Aloso** [comment]
Here's the code I used:

	var myModeSpec = {
		name: "htmlmixed",
		indentUnit: 4,
		tabSize: 4,
		indentWithTabs: false,
		lineNumbers: true,
		autofocus: true
	};

	var myCodeMirror = CodeMirror.fromTextArea(code, myModeSpec);

**Comment by marijnh** [comment]
I think you want 

```
var myOptions = {
    mode: "htmlmixed",
    indentUnit: 4,
    tabSize: 4,
    indentWithTabs: false,
    lineNumbers: true,
    autofocus: true
};

var myCodeMirror = CodeMirror.fromTextArea(code, myOptions);
```

I.e. the second argument to `fromTextArea` is a set of editor options, not a mode spec.
