### ISSUE TITLE
[merge] copy arrow positioned poorly for a deletion

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4492]
The arrow for copying on the right side is positioned way at the bottom of the right divider, after line 176 in the center. It would be more sensible if it appeared aligned with line 153 in the center.

[left.txt](https://github.com/codemirror/CodeMirror/files/700446/left.txt)
[center.txt](https://github.com/codemirror/CodeMirror/files/700447/center.txt)
[right.txt](https://github.com/codemirror/CodeMirror/files/700448/right.txt)

**Comment by marijnh** [comment]
Does attached patch solve the issue for you?

**Comment by takamori** [comment]
I left a comment on the patch; reversing the comparison makes it look correct.

**Comment by takamori** [comment]
thx for the fix!
