### ISSUE TITLE
Live search

### ISSUE THREAD

**Issue by edemaine** [codemirror/CodeMirror#4496]
I really like how search works in the VIM keymap (and as in VIM itself), which I would call "**live search**": as you type the search query, it jumps to the first match, and the dialog exits when you hit enter.  By contrast, the current search module requires you to press enter before it shows you any feedback -- much harder to notice typos this way.

I could also see a "persistent search" version of live search, where you get the live feedback typing, and pressing enter repeatedly goes to following matches.  This is how search works in Chrome, for example.

Is this something that you're working / would you have interest in implementing it / would you like a PR?  Presumably this would be a different search add-on, or an option added to the current one.

**Comment by marijnh** [comment]
I think this should be a different seach addon, and I'd prefer for it to be implemented as a separate module, so that the maintenance burden doesn't fall on me (the search addon is already a monster of different use cases, and adding more stuff to it would require a serious rethink -- doing this from scratch is probably cleaner)

**Comment by Shade-** [comment]
If anyone's interested into live searching, here's what I've got by editing the current search addon:

Find:
```javascript
       persistentDialog(cm, queryDialog, q, searchNext, function(event, query) {
        var keyName = CodeMirror.keyName(event)
        var extra = cm.getOption('extraKeys'), cmd = (extra && extra[keyName]) || CodeMirror.keyMap[cm.getOption("keyMap")][keyName]
        if (cmd == "findNext" || cmd == "findPrev" ||
          cmd == "findPersistentNext" || cmd == "findPersistentPrev") {
          CodeMirror.e_stop(event);
          startSearch(cm, getSearchState(cm), query);
          cm.execCommand(cmd);
        } else if (cmd == "find" || cmd == "findPersistent") {
          CodeMirror.e_stop(event);
          searchNext(query, event);
        }
      });
```

Replace with:
```javascript
      persistentDialog(cm, queryDialog, q, searchNext, function(event, query) {
        var keyName = CodeMirror.keyName(event)
        if (keyName != 'Enter' && query != state.queryText) {
          startSearch(cm, state, query);
          state.posFrom = state.posTo = cm.getCursor();
        }
        var extra = cm.getOption('extraKeys'), cmd = (extra && extra[keyName]) || CodeMirror.keyMap[cm.getOption("keyMap")][keyName]
        if (cmd == "findNext" || cmd == "findPrev" ||
          cmd == "findPersistentNext" || cmd == "findPersistentPrev") {
          CodeMirror.e_stop(event);
          startSearch(cm, getSearchState(cm), query);
          cm.execCommand(cmd);
        } else if (cmd == "find" || cmd == "findPersistent") {
          CodeMirror.e_stop(event);
          searchNext(query, event);
        }
      });
```

Find:
```javascript
  function persistentDialog(cm, text, deflt, onEnter, onKeyDown) {
    cm.openDialog(text, onEnter, {
      value: deflt,
      selectValueOnOpen: true,
      closeOnEnter: false,
      onClose: function() { clearSearch(cm); },
      onKeyDown: onKeyDown
    });
  }
```

Replace with:
```javascript
  function persistentDialog(cm, text, deflt, onEnter, onKeyUp) {
    cm.openDialog(text, onEnter, {
      value: deflt,
      selectValueOnOpen: true,
      closeOnEnter: false,
      onClose: function() { clearSearch(cm); },
      onKeyUp: onKeyUp
    });
  }
```

It simply change the bound event to keyUp (so we have the actual input value) and starts searching every time a char is entered (except when clicking on the enter char – which triggers the searchNext function.
