### ISSUE TITLE
styleActiveLine breaks Android

### ISSUE THREAD

**Issue by edemaine** [codemirror/CodeMirror#4500]
With `styleActiveLine` set to true, on Android's Chrome, CodeMirror's gains a strange editing behavior: typing a character on any line inserts that character where intended, but *also* inserts a blank line immediately before this line.

**Comment by novemember1985** [comment]
none of my sites r showing up for Android but for computer

**Comment by vincentwoo** [comment]
This is probably related to #4194

**Comment by etamponi** [comment]
I had the same problem. The only way I could fix it is to use `cm.setOption("inputStyle", "textarea")`. Unfortunately this breaks other things (like selection). My current solution is to use the input style option and a custom keyboard with arrow keys and the other special keys.

**Comment by edemaine** [comment]
`styleActiveLine` has definitely improved on Android!  However, it still fails in this case: if I go to the end of a line (except the first?), and type a character, then the character gets inserted where it should, but the cursor also gets moved to the next line (so if you kept typing, it goes on the next line).  This seems to be some kind of "temporary" issue, though, because repeating the process, or trying it on a different line, doesn't reproduce the error; I need to reload to get it to happen again.

This behavior seems localized to styleActiveLine, because it doesn't happen with e.g. `demo/marker.html`.

**Comment by marijnh** [comment]
I spent a while trying to reproduce this (with Chrome Android), but it never happened for me. Which line did you put the cursor on, and what did you type?

**Comment by edemaine** [comment]
Given your failure to reproduce, I investigated further.  Looks like this behavior is localized to the SwiftKey keyboard entry.  (Both Samsung keyboard and Hacker's Keyboard didn't have this behavior.)  Not sure how to figure out what keystrokes SwiftKey is actually sending when typing a single character...

Here are screenshots when, with SwiftKey, I click on the end of the second line, then type the letter "x".  (The second and third screenshots would normally have a keyboard up, but I couldn't easily take a screenshot with the keyboard up.)

![screenshot_2017-03-09-10-03-48](https://cloud.githubusercontent.com/assets/2218736/23756046/709cf8b6-04b0-11e7-9c3f-cfd300d3370e.png)
![screenshot_2017-03-09-10-04-34](https://cloud.githubusercontent.com/assets/2218736/23756055/746d2858-04b0-11e7-99b2-b7c5dad267e8.png)
![screenshot_2017-03-09-10-04-42](https://cloud.githubusercontent.com/assets/2218736/23756057/761c78f2-04b0-11e7-928c-bb69dd0d17a1.png)
