### ISSUE TITLE
Duplicate named files

### ISSUE THREAD

**Issue by mnmercer** [codemirror/CodeMirror#4503]
I use this library via its NPM module and grab the files I need for a build process within a Gulp task using glob pattern matching. In the interest of not depending on the specific file structure of the library, I simply use `node_modules/codemirror/**/codemirror.js` which worked fine for a long while. However in a recent update, there are now two files titled `codemirror.js` within the project which makes glob pattern matching slightly more annoying. Not a high priority, but out of curiosity any particular reason why the source file was named the same as the main library file?

**Comment by marijnh** [comment]
Because we didn't anticipate anyone loading the files by glob pattern. Just refer directly to `lib/codemirror.js`, that's much more robust.
