### ISSUE TITLE
Python 3.6 underscores in numeric literals are not highlighted correctly

### ISSUE THREAD

**Issue by Nagasaki45** [codemirror/CodeMirror#4506]
Python 3.6 supports underscores in numeric literals ([PEP 515](https://www.python.org/dev/peps/pep-0515/)). They are currently not highlighted correctly:

![Python 3.6 underscores in numeric literal highlighting problem](https://cloud.githubusercontent.com/assets/2564187/22151417/cdcd71b6-df15-11e6-85eb-68598077a08f.png)

The above image is from the [demo page](https://codemirror.net/mode/python/index.html). I don't know the exact CodeMirror version that runs there.

**Current output:** Only the part before the underscore is painted in green.
**Expected output:** The entire numeric literal should be green.
**CodeMirror version:** 5.16 (through jupyter notebook 4.3.1).
**Browser:** Firefox 50.1.0.

**Comment by spaider88** [comment]
Underscore literals were introduced in Python version 3.6. Before there was no such construction. At least 'py3' should be check before '// Handle Number Literals'. [https://www.python.org/dev/peps/pep-0515/](https://www.python.org/dev/peps/pep-0515/)
