### ISSUE TITLE
"change" event is triggered 1000 times for a 1000-line multi-line indent operation

### ISSUE THREAD

**Issue by josephrocca** [codemirror/CodeMirror#4507]
When highlighting 1000 lines of text and indenting/dedenting it all at once with `tab` or `shift+tab`, codemirror appears to be triggering the `change` event 1000 times instead of just once.

Is this expected behaviour? If so, is there another event which considers the multi-line indent operation as a single "change"? It'd be great to be able to handle a couple of thousand lines in the editor, but as it currently is the whole page hangs for several seconds when indenting.

**Comment by marijnh** [comment]
Yes, this is the expected behavior. You can listen to the `"changes"` event to get a single event with an array of changes.

**Comment by josephrocca** [comment]
Thanks, marijnh!
