### ISSUE TITLE
LESS and SCSS modes don't define lineComment, so toggle comment command only ever creates block comments

### ISSUE THREAD

**Issue by geordiemhall** [codemirror/CodeMirror#4509]
Not sure if this was ever working, but I recently upgraded the version of CodeMirror we use in our LESS editor, and noticed that without some previous customisations the ability toggle a line comments using a keyboard shortcut stopped working in some cases, and created block comments in others.

Dug a bit deeper and saw that we'd customised `mode/css.js` to add a `lineComment: "//"` declaration for the LESS and SCSS modes (it only has `blockCommentStart`/`End` currently). 

The `toggleComment`command tries to do a line comment first, and since LESS and SCSS support line comments I'd expect one to be used, rather than a `/* block comment */`.

Not sure if this has been brought up before and knocked back by some arguing that block comments are more common in preprocessors or something or if it's just an oversight, but either way it'd be nice to at least have _some_ way to get this behaviour out of the box (eg. a global option), rather than needing to alter the mode file.

Adding the `lineComment` definition into the css mode for LESS and SCSS mime types restored my desired behaviour.

Tested on CodeMirror 5.23.0, in Chrome 55 on macOS Sierra.

**Comment by vincentwoo** [comment]
This seems like a great opportunity for a PR! If LESS and SCSS officially support line commenting, I don't see any reason why that shouldn't be merged into the handlers for those modes.

**Comment by geordiemhall** [comment]
No problem, have made a PR. Let me know if changes required :)

**Comment by marijnh** [comment]
Fixed via #4510
