### ISSUE TITLE
codemirror.js was removed from /lib

### ISSUE THREAD

**Issue by sysiler** [codemirror/CodeMirror#4512]
Disappeared after version 5.19.1, was this intentional?

**Comment by sbruchmann** [comment]
[Yes](https://github.com/codemirror/CodeMirror/releases/tag/5.20.0).

> New features
>
> The core is now maintained as a number of small files, using ES6 syntax and modules, under the
> src/ directory. A git checkout no longer contains a working codemirror.js until you npm build (but
> when installing from NPM, it is included).
