### ISSUE TITLE
`Ctrl-Space` triggered hinter causes a "space" to be inserted in Firefox & Edge, but not in Chrome

### ISSUE THREAD

**Issue by BigBlueHat** [codemirror/CodeMirror#4513]
I'm working on a new [JSON-LD](http://json-ld.org/) hinting CodeMirror add-on (which I hope to contribute here once it's "ready). However, I've hit a weird bug.

Using [this demo](https://wileylabs.github.io/codemirror-jsonld-hint/), pressing `@` or `Ctrl+Space` within a key opens the auto-complete for the reserved JSON-LD keywords. However, if you use `Ctrl+Space` in Firefox or Edge an space is inserted...but not in Chrome...strangely.

It's possible it's my code (this is my first such thing and it's based off of reading lots of hinter variations--both core and community written). That said, it only breaks in FF and Edge (in my tests)...so...maybe it's not? 😕 

Thanks!
🎩

**Comment by marijnh** [comment]
This is too vague and tied to your code for us to treat it as a CodeMirror bug. If you can narrow it down to a specific thing that CodeMirror does, in a minimal, reduced program, please open a new issue with more details.

**Comment by BigBlueHat** [comment]
@marijnh apologies. It is probably a better fit for the forums than this issue tracker. My bad. Thanks for the reply!
