### ISSUE TITLE
html-hint shows autocompletion suggestions on every letter

### ISSUE THREAD

**Issue by chinchang** [codemirror/CodeMirror#4516]
### Setup

Mode: htmlmixed
I wanted hint to show up automatically instead of a manual keyboard shortcut. So I have this:

```
cm.on('inputRead', function onChange(editor, input) {
 if (input.text[0] === ';' || input.text[0] === ' ') { return; }
 CodeMirror.commands.autocomplete(cm, null, { completeSingle: false })
});
```

### Steps to reproduce

- In a htmlmixed codemirror instance, type any letter
Codemirror will show up the hint popup giving invalid suggestions. Also, while typing text content inside a tag, the popup shows up continuously.

![screenshot 2017-01-28 01 20 48](https://cloud.githubusercontent.com/assets/379918/22385348/414117fa-e4f8-11e6-8a6d-6fc861f32e6d.png)

### Expected behavior

It should show tag/attribute suggestions only when writing a tag (after <) or inside a tag.

**Comment by marijnh** [comment]
The mode itself does not do any kind of completion, so you must be doing something in addition to setting the mode to htmlmixed.

**Comment by chinchang** [comment]
Yes. I wanted hint to show up automatically instead of a manual keyboard shortcut. So I have this:

```
cm.on('inputRead', function onChange(editor, input) {
 if (input.text[0] === ';' || input.text[0] === ' ') { return; }
 CodeMirror.commands.autocomplete(cm, null, { completeSingle: false })
});
```

Is this the right way to show automatic completion hints?

**Comment by marijnh** [comment]
Well, your code is popping up autocompletion on every character, so that's what you get. I'm not sure what you consider wrong about the suggestions in your screenshot, but they all appear to be valid tags there. If you want to only complete when the cursor is in a tag name or after a `<`, you'll have to program your completion logic that way.

**Comment by chinchang** [comment]
I get it. Thanks @marijnh
