### ISSUE TITLE
Allow returning multiple styles from a mode

### ISSUE THREAD

**Issue by jcking** [codemirror/CodeMirror#4518]
https://github.com/codemirror/CodeMirror/blob/3dc1a5db143bd99fd3a1a9bca1ee1005ef5c828d/src/line/line_data.js#L48 implies that multiple styles can be returned, reading that function seems to imply otherwise (or I am looking in the wrong place). Editors like Visual Studio Code and Brackets add multiple styles to each token. For example it will add the CSS classes ['token', 'js', 'meta', 'function', 'block', 'entity', 'name'] to a function name. Can we add the ability to return an array of CSS styles from a mode? These would then be iterated over and have 'cm-' prefixed to them? This would also allow for more complex modes and styles.

**Comment by marijnh** [comment]
You can already return a space-separated string of styles.
