### ISSUE TITLE
`elseif` not indented properly in Julia code

### ISSUE THREAD

**Issue by ianshmean** [codemirror/CodeMirror#4519]
Typing out the following Julia language example highlights the issue, where `elseif` isn't indented appropriately

```
if somecondition
    somecode
    elseif someothercondition
else
end
```

**Comment by marijnh** [comment]
@pabloferz Do you want to take a look?

**Comment by pabloferz** [comment]
@ianshmean Did you try typing you code over http://codemirror.net/mode/julia/? If you see the problem over there could you describe exactly how you are typing? Or are you pasting it and trying to format it?

**Comment by ianshmean** [comment]
I'm very puzzled by this bug.. Using the codemirror example, while manually typing this out the indentation is correct, but once I complete the structure, if I go back and edit the elseif doesn't indent properly. Can you confirm that behavior?

The thing that puzzles me is that sometimes I get that behavior during typing the structure.. But perhaps that's linked to times when it's encapsulated in a non-complete structure

**Comment by marijnh** [comment]
It seems that when you type, you go through 'else', which _is_ indented properly, but once the word `elseif` is typed, it no longer matches `else`, so the indentation was off. Attached patch handles `elseif` properly.

**Comment by pabloferz** [comment]
Oh, right. Thanks of that @marijnh

**Comment by ianshmean** [comment]
Great thanks @marijnh @pabloferz
