### ISSUE TITLE
end of the line

### ISSUE THREAD

**Issue by merteroglu01** [codemirror/CodeMirror#4522]
when i type aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
for example,

it doesnt go to newline. the line width expand to infinite.and where is the line in codemirror.js that adds min height and min width to codemirror-sizer div ?

Best regards.

**Comment by marijnh** [comment]
Did you enable `lineWrapping`? If yes, which browser are you using and could it be that your editor is in a container without a fixed width, and you're not giving it a width in your CSS?

**Comment by merteroglu01** [comment]
i didnt enable.My bad.I am sorry.
