### ISSUE TITLE
[markdown] Typing > and enter makes the > disappear

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4526]
repro in https://codemirror.net/mode/markdown/

1. type >
2. enter
3. > disappears

**Comment by marijnh** [comment]
That's the `continuelist` addon seeing that you're leaving an empty blockquote line and helpfully cleaning up the blockquote for you. I'd say this is desired behavior, most of the time, since I don't know of a reason to have an empty line in a Markdown blockquote.

**Comment by mtaran-google** [comment]
This also happens at the end of 

```md
> foo
>
```

This is useful when you want to make a block quote contain two paragraphs, which per CommonMark require a line with just a > between them: http://spec.commonmark.org/0.12/#example-153

**Comment by marijnh** [comment]
That's a good point. Attached patch disables the behavior for `>` quotes.
