### ISSUE TITLE
[merge] Request a means to easily merge content in 3-way merge from both the left and right sides

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4529]
In the merge addon, one can copy content from the left or right side into the middle editor. However, there's no mechanism to allow for copying content in from both sides- in particular as the difference updates immediately upon any change in the center editor. Having a mechanism for inserting content from both sides could be useful in a 3-way merge in case content modifications from both versions is desired.

Example: https://jsfiddle.net/pb163xmu/3/

**Comment by marijnh** [comment]
That'd be a new, non-trivial feature (it'd require some kind of merge algorithm), which I'm not interested in adding to this addon at the moment.
