### ISSUE TITLE
[merge] Request ability to disable immediate updating of diff as content is edited

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4531]
It could be useful to change the behavior of the merge so that the diff highlighting and calculated diff chunks do not change immediately upon a change in the center panel.  Together with issue #4530 this could potentially allow for selecting individual changes for update without affecting the remaining UI in a means that turns the diff changes into a checklist of changes for the user to consider or reject.

**Comment by marijnh** [comment]
Interesting idea, but out of scope for the current addon, which is already straining under trying to support a lot of different configurations and use cases.
