### ISSUE TITLE
[merge] Make it easier to style/color the merge spacers in a diff/merge when connect='align'.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4536]
It's currently a bit difficult to style/color merge spacers in a diff/merge when connect is set to 'align'. The merge spacers are generally created as line widgets on the line at the end of a missing section, and are positioned to be above that line; this means that if the merge spacers is at the end of a diff, it's created on the line after diff chunk's end. An exception to this rule is when the gap is at the end of the file, in which case it's created on the last line and is positioned to be below the line (as seen in the padAbove() method in merge.js).

To create a graphical indicator of the height of the diff chunk, we've been creating annotations on the lines that live in the gutter. That doesn't work for the merge spacer, though, since it's usually placed on the line after the diff region. But we can't rely on that always being the case either, since at the end of a file this merge spacer can be positioned below the last line of the diff instead.

It would be helpful if there were a simple way to illustrate this (either via API or a structure that makes CSS styling of this more amenable). Alternatively, is there a more reliable (but still scalable) mechanism for this that you would recommend here?

**Comment by marijnh** [comment]
What kind of graphical indicator are you trying to add? And isn't it possible to just use the same rules (above line in common case, below line at end) when adding your gutter marker?

**Comment by takamori** [comment]
See the gutter annotations in https://jsfiddle.net/xzjrywLk/4/ and the CSS calc() hack I have on highlight-diff-end::after
which it turns out is insufficient- if lineWrapping is enabled, the hack doesn't work see line 29 in the center of: https://jsfiddle.net/xzjrywLk/5/

Also, it would be difficult to make the borders (see line 9 in the left, for instance) look right, so currently we just disable them, but it would better if we could make them just work.

**Comment by marijnh** [comment]
It would be easy to make the spacers cover the gutter, at which point you can give them a border. Would that help?

What is the fact that the changed chunks get a similar bar on the left as the spacers trying to express? Do you have a mockup or sketch of the style you're trying to create?

**Comment by takamori** [comment]
Sorry for the late response. So- we had a slightly different diff algorithm going on that we wanted to render results for as well, which we were rendering w/ the gutter annotations. But it looks like we can avoid needing to have the separate rendering in the gutter vs the background highlighting, and coloring the merge spacer itself should be an easier task, so I believe we can go w/ that instead.

**Comment by marijnh** [comment]
Sounds good
