### ISSUE TITLE
Typo in mode/commonlisp/commonlisp.js

### ISSUE THREAD

**Issue by Matceporial** [codemirror/CodeMirror#4545]
There is a typo in mode/commonlisp/commonlisp.js, around line 46, here is the fix:

```
       else { stream.skipToEnd(); return "error"; }
      } else if (ch == "#") {
        var ch = stream.next();
 -      if (ch == "[") { type = "open"; return "bracket"; }
 +      if (ch == "(") { type = "open"; return "bracket"; }
        else if (/[+\-=\.']/.test(ch)) return null;
        else if (/\d/.test(ch) && stream.match(/^\d*#/)) return null;
        else if (ch == "|") return (state.tokenize = inComment)(stream, state);
```
I think this is too little of an issue to make a pull-request, but to other contributors, fix it in your forks if you are going to make bigger changes, please.

Details:
The code treats `#[` as a bracket, but in Common Lisp , `#[` is undefined.  The `#(`, on the other hand, is the syntax for arrays, and it would be logical to treat them like lists, which have the bracket syntax, which the incorrect code interpreted `#[` as.

**Comment by marijnh** [comment]
Thanks. Fixed in attached patch.

Lumping unrelated changes into pull requests is discouraged, so opening one for a single specific change like this is perfectly okay.
