### ISSUE TITLE
PHP mode: use single quote in strings with variables and closebrackets addon

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#4549]
If you insert a single quote (`'`), in the example below, before the word `test` and then insert one after it codemirror correctly insert only one.
If you add a single quote before the variable `$bar` inside the string and then try to insert one after it, codemirror add two single quotes.

Reported at https://github.com/adobe/brackets/issues/13081

```html
<!doctype html>
<meta charset="utf-8"/>
<link rel="stylesheet" href="node_modules/codemirror/lib/codemirror.css">
<script src="node_modules/codemirror/lib/codemirror.js"></script>
<script src="node_modules/codemirror/addon/edit/closebrackets.js"></script>
<script src="node_modules/codemirror/mode/xml/xml.js"></script>
<script src="node_modules/codemirror/mode/clike/clike.js"></script>
<script src="node_modules/codemirror/mode/php/php.js"></script>
<textarea id="code" name="code">
<?php
$foo = "test $bar"
?>
</textarea>
<script>
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
    lineNumbers: true,
    mode: "application/x-httpd-php",
    autoCloseBrackets: true
});
</script>
```

**Comment by marijnh** [comment]
What I'm seeing is that when I type a quote before the `$` character, one quote is inserted, and when I type another, another quote is inserted. Is that what you mean, or are you seeing something different?

Autoclosing is intentionally disabled inside strings (so that you can type _can't_ without getting _can't'_).

**Comment by marijnh** [comment]
Ah, right, I can confirm that -- that's an effect of the way the bracket addon was determining whether it was in a string. Attached patch seems to help.

**Comment by ficristo** [comment]
Thank you.
