### ISSUE TITLE
PHP mode: Heredoc strings and syntax highlighting

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#4550]
When you start a heredoc string with an identifier which is a mode name,
it would be nice to syntax highlight the string with that mode.
GitHub and Sublime3 seems to support this.

Reported at https://github.com/adobe/brackets/issues/13062

```php
<?php
$foo = "this is a string"
$foo = <<<END
  this is a string
END;
$foo = <<<HTML
  <p class="class">test {$var}</p>
HTML;
$foo = <<<JAVASCRIPT
  function bar() {}
JAVASCRIPT;
$foo = <<<SQL
  select * from baz where id = 1
SQL;
$foo = <<<DOC
  this is also a string
DOC;
?>
```

**Comment by marijnh** [comment]
I guess that would be nice, if people are widely using heredoc strings in PHP like that. But it's a completely new non-trivial feature to add to the mode, and I'm not taking feature requests. You could consider trying to do it yourself (maybe look at the way the markdown mode highlights code blocks for inspiration) and submit a pull request.
