### ISSUE TITLE
[merge][annotatescrollbar] Annotating scrollbar doesn't always account for merge gap height properly

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4554]
In https://jsfiddle.net/o5cta772/1/ the diff chunks are being annotated. In some cases, we'd like to annotate some range beyond the end gap of a given diff chunk. However, it turns out that this sometimes will merge annotation ranges where the ranges do not actually overlap. This can be seen if one deletes line 13 on the right "* NEW 4" and observes that a new annotation range suddenly appears.

A bit of debugging reveals that the reason is that getY() inside of Annotation.prototype.redraw() isn't aware that the merge gap is being rendered above the line, rather than below, with the result that it believes that the line's bottom is much lower than it actually is. On the other hand, the line for the next range is positioned properly, so the comparison inside the while loop thinks that the subsequent range overlaps, when in truth it doesn't.

**Comment by marijnh** [comment]
Attached patch should help with this.
