### ISSUE TITLE
Improve support for LaTeX in Markdown: no markup inside math blocks

### ISSUE THREAD

**Issue by Naereen** [codemirror/CodeMirror#4555]
Hi,
First, :clap: because CodeMirror is awesome. Thanks for this great software!

Second, I was wondering if it could be possible to improve the support for LaTeX in the editor Markdown mode, specially the way it parses Markdown special characters inside `$ ... $` or `$$ ... $$` or `\( ... \)` or `\[ ... \]` (LaTeX math blocks).

Basically, LaTeX can use `*`, `_` (and every possible Markdown syntax) inside a math block, but it should *not* be understood as Markdown markup if it's *inside* a math block. For instance, `$ **x** $` should *not* show `x` in bold.

## Example
For instance, the following Markdown code:
```markdown
- Example of math using an underscore: $a_i \in \mathcal{A}_i$
- Now the rest of the text is highlighted in italic, as this $y_j$ underscore was understood as "start italic"...
- And only this will close the underscore $a_i \in \mathcal{A}_i$ underscore was understood as "start italic"...
```
In GitHub, this bug is not present:
- Example of math using an underscore: $a_i \in \mathcal{A}_i$
- Now the rest of the text is highlighted in italic, as this $y_j$ underscore was understood as "start italic"...
- And only this will close the underscore $a_i \in \mathcal{A}_i$ underscore was understood as "start italic"...

But in CodeMirror, it is:
![example bug CodeMirror](https://cloud.githubusercontent.com/assets/11994719/22694892/34131a66-ed49-11e6-8ee6-eeba901c36ce.png)

----
## Note:
I encountered this bug by using [Marp](https://github.com/yhatt/marp/), see [@yhatt/marp#149](https://github.com/yhatt/marp/issues/149#issuecomment-278576967), and it uses CodeMirror v5.11 ([see here](https://github.com/yhatt/marp/blob/master/package.json#L41)) inside a Electron app.

> Many thanks in advance.

**Comment by Naereen** [comment]
Marp uses pure the `gfm` mode, ([cf. here](https://github.com/yhatt/marp/blob/master/coffee/index.coffee#L12)).
> Disclaimer: I am *not* Marp's developer, just a happy user of Marp (and CodeMirror)!

**Comment by Naereen** [comment]
I don't see any special handling of `\$` or `\(` or `\[` in [`gfm.js`](https://github.com/codemirror/CodeMirror/blob/master/mode/gfm/gfm.js), nor in [`markdown.js`](https://github.com/codemirror/CodeMirror/blob/master/mode/markdown/markdown.js).

Does any one know if this feature has already been added? or if this bug was already known?

**Comment by marijnh** [comment]
Hi. Markdown does not, in itself, have anything to do with TeX. You could try to create a wrapping mode that handles this (see also the discussion [here](https://github.com/codemirror/CodeMirror/issues/2942)), but I don't consider the fact that the Markdown/GFM modes don't handle this themselves a bug.

**Comment by Naereen** [comment]
I agree, but the goal of GFM mode is, as its name suggests, to mimic GitHub way of showing Markdown code, and Markdown markup inside TeX blocks are correctly escaped by GitHub.

**Comment by Naereen** [comment]
It seems that the other thread also reached the conclusion that CodeMirror's maintainers do not care about this possible improvement of the GFM mode, that's unfortunate. :sad:

**Comment by marijnh** [comment]
This is not an improvement to the GFM mode, this is a separate language that one could write a mode for _on top of_ the GFM mode. Since the CodeMirror maintainers have more than enough on their hands already, we're encouraging people to build and maintain new modes as separate packages, which should scale better than putting everything on the shoulders of the people maintaining the core library.

**Comment by Naereen** [comment]
OK.
