### ISSUE TITLE
[merge] Adding lines at the end of a 3-way merge in align mode doesn't scroll right

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4556]
1. Open the merge demo
2. `dv.rightOriginal().setOption('readOnly', false)&& dv.leftOriginal().setOption('readOnly', false)&& dv.editor().setOption('readOnly', false)`
3. Scroll to the bottom
4. Add lines to the bottom of any of the three panels

Expected: All three panels scroll down

Actual: Only the panel you're on scrolls down

**Comment by mtaran-google** [comment]
1.5: Set align mode, and 3-way :)

**Comment by marijnh** [comment]
If I add lines to one of the editors, while all are scrolled down, there isn't any content to scroll into view in the other editors, so they can't scroll down. And even if they could (with the scrollpastend addon, for example), there's nothing there to scroll into view, so I'm not sure why you are expecting this behavior.

**Comment by marijnh** [comment]
Ah, hold on, connect=align is enabled -- now it makes more sense

**Comment by marijnh** [comment]
Attached patch should help. The issue was that when scrolling happens directly after a change, the addon didn't have an up-to-date diff and thus punted on the scroll syncing. It now sets a flag to retry the sync when the update has been handled.
