### ISSUE TITLE
[merge] scrolling of the panes can get disconnected

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4557]
1. demo/merge.html
2. 3-way & mode = align
3. Add 7 newlines on line 118 after \</article> in the middle pane
4. Add 9 newlines on line 122 after \</body> in the right pane
5. Scroll wheel while over the right pane

Expected: All panels move in sync
Actual: When you scroll down low enough, only the middle and right panels are connected and the left one stays at a higher point. Looks like it doesn't get a spacer added at the bottom.

**Comment by marijnh** [comment]
I wasn't able to reproduce this. I could see the scroll to out of sync when adding the newlines, but that was #4556. When scrolling after that, the editors stay in sync.

Can you reproduce this if you make some changes to `demo/merge.html` to immediately create the problematic situation on startup? If so, could you give me the updated demo file?

**Comment by mtaran-google** [comment]
Sorry, my script tags in the repro steps got eaten by markdown processing :)

It repros with the attached file. Scroll to the bottom, over the right panel.
[merge.html.zip](https://github.com/codemirror/CodeMirror/files/767504/merge.html.zip)

**Comment by marijnh** [comment]
Does attached patch fix this for you? What I was seeing is that the two rightmost editors got a incorrectly large margin at their bottom, making them higher than the left editor, so that the left editor simply couldn't scroll as far down as they could.

**Comment by mtaran-google** [comment]
Yes, I believe that fixes it. Thank you!
