### ISSUE TITLE
TypeError: place is not a function

### ISSUE THREAD

**Issue by the7erm** [codemirror/CodeMirror#4558]
Hello,

I'm using `react-codemirror` and I've installed code mirror with `npm i -S codemirror` 

TypeError: place is not a function
```javascript
	  if (place) {
	    if (place.appendChild) { place.appendChild(d.wrapper) }
	    else { place(d.wrapper) }
	  }
```

`else { place(d.wrapper) }` is throwing the error.  Is this a `react-codemirror` bug or a `codemirror` bug?

The header for that section of code has `// CodeMirror, copyright (c) by Marijn Haverbeke and others`  am I missing a library?
```
├── codemirror@5.23.0
├─┬ react-codemirror@0.3.0
│ ├── classnames@2.2.5
│ └── lodash.debounce@4.0.8
```

**Comment by marijnh** [comment]
You're passing a value of the wrong type to the CodeMirror constructor. This is not a CodeMirror bug -- it might be a react-codemirror bug or a problem in the way you're using the library
