### ISSUE TITLE
[merge] monotonic mouse wheel movement produces non-monotonic scrolling

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4559]
1. demo/merge.html
2. 3-way & mode = aligned
3. Use mouse wheel to scroll down from the top of the right pane to the bottom

Expected: smooth scrolling of left pane

Actual: left pane mostly moves downward, but sometimes jumps up (and then moves down)

To verify:
1. Run `dv.leftOriginal().id = 'L';`
2. In the sources panel of dev tools, add a conditional breakpoint to the first line of the scrollTo: methodOp, and set it to break when `'L' && console.log(y)`.
3. Perform the scrolling.
4. Observe that the numbers are generally smoothly increasing, but sometimes jump up and then back down to continue the increasing trend.

**Comment by mtaran-google** [comment]
The same kind of issue (with same verification steps) happens on the left pane if you're scrolling the left pane by dragging its scroll bar.

**Comment by marijnh** [comment]
On Chrome, I'm seeing the scroll position monotonically increase and never decrease when I do this. Which browsers did you test?

**Comment by mtaran-google** [comment]
It's a little tricky, but here are two files which repro it for me on merge.html. Put them into the left & right panes, and then *quickly* drag the left scroll bar down. Put a breakpoint on the first line of `NativeScrollbars.prototype.setScrollTop` conditional on `this.vert.scrollTop > pos`. When I did this, I caught it stopping with the following stack trace:

```
NativeScrollbars.setScrollTop (codemirror.js:3447)
endOperation_finish (codemirror.js:3801)
endOperations (codemirror.js:3723)
(anonymous) (codemirror.js:3706)
finishOperation (codemirror.js:2124)
endOperation (codemirror.js:3703)
(anonymous) (codemirror.js:3858)
syncScroll (merge.js:191)
(anonymous) (merge.js:147)
signal (codemirror.js:1246)
(anonymous) (codemirror.js:7497)
scroll (async)
endOperation_finish (codemirror.js:3802)
endOperations (codemirror.js:3723)
(anonymous) (codemirror.js:3706)
finishOperation (codemirror.js:2124)
endOperation (codemirror.js:3703)
(anonymous) (codemirror.js:3858)
syncScroll (merge.js:191)
(anonymous) (merge.js:144)
signal (codemirror.js:1246)
(anonymous) (codemirror.js:7497)
scroll (async)
setScrollTop (codemirror.js:3239)
(anonymous) (codemirror.js:3541)
(anonymous) (codemirror.js:3393)
```

It's interesting to me here that it has *two* async scroll event boundaries in the trace...

[left-ex.txt](https://github.com/codemirror/CodeMirror/files/772780/left-ex.txt)
[right-ex.txt](https://github.com/codemirror/CodeMirror/files/772781/right-ex.txt)

**Comment by marijnh** [comment]
I'm seeing the jumps now, but only in the editor that I'm scrolling -- I was only testing the other one before, going on your description. Still, that doesn't look right, so I'm going to try to figure out why it happens.

**Comment by marijnh** [comment]
That appeared to be caused by an issue in the way scrolling syncing tries to be one-directional (i.e. to prevent feedback cycles between the editors). Attached patch makes the jumps go away for me, could you see if it also solves your issue?

**Comment by mtaran-google** [comment]
Beautiful! Yes, now I don't see any of these issues. Thank you :)
