### ISSUE TITLE
Freemarker Mode Request

### ISSUE THREAD

**Issue by melloware** [codemirror/CodeMirror#4564]
I see CodeMirror 1 had a Freemarker mode:  http://codemirror.net/1/contrib/freemarker/

Any chance of that for CodeMirror 2?  I found two on Github but neither pass the test...

https://github.com/liuxiaole/codemirror-mode-freemarker

https://gist.github.com/xingjia/fb9e5cf03d3a3d7d47ca

**Comment by marijnh** [comment]
Hi. We're not taking mode requests. If you need it, you'll have to develop it yourself.

**Comment by melloware** [comment]
Understood.  If I fix all the issues with it and submit a PR would you consider adding it?

**Comment by marijnh** [comment]
No, but it'd be wonderful if you publish it yourself, as a separate NPM module (say codemirror-mode-freemarker)

**Comment by melloware** [comment]
Understood for now I will keep it in my own GitHub fork and see if get around to an NPM in the future.  Great work on CodeMirror!

**Comment by sanluan** [comment]
https://github.com/sanluan/codemirror-freemarker

**Comment by bawa** [comment]
> Understood for now I will keep it in my own GitHub fork and see if get around to an NPM in the future. Great work on CodeMirror!

hi,

did You manage to write this freemarker mode?
Is it perhaps published somewhere?

thanks
bartek

**Comment by melloware** [comment]
@bawa I have switched to Monaco Editor and has FreeMarker suppport see here: https://www.primefaces.org/showcase-ext/sections/monacoEditor/basicUsage.jsf and pick FreeMarker.

**Comment by bawa** [comment]
> @bawa I have switched to Monaco Editor and has FreeMarker support see here: https://www.primefaces.org/showcase-ext/sections/monacoEditor/basicUsage.jsf and pick FreeMarker.

thx :)

**Comment by sanluan** [comment]
> did You manage to write this freemarker mode?
> Is it perhaps published somewhere?

It has been used in my own product, you can use it like this

```
<link rel="stylesheet" type="text/css" href="codemirror/lib/codemirror.css" />
<script src="codemirror/lib/codemirror.js"></script>
<script src="codemirror/mode/xml/xml.js"></script>
<script src="codemirror/mode/javascript/javascript.js"></script>
<script src="codemirror/mode/css/css.js"></script>
<script src="codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="codemirror/mode/freemarker/freemarker.js"></script>
<script src="codemirror/mode/freemarkermixed/freemarkermixed.js"></script>
<textarea id="code" name="template">&lt;#assign data={&quot;aa&quot;: .now ,&quot;cc&quot;:&quot;dd&quot;}/&gt;${data.aa!}</textarea>
<script>
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
   mode: "freemarkermixed",
   lineNumbers: true
});
</script>
```

![QQ截图20221004194814](https://user-images.githubusercontent.com/12441887/193812167-0dfc13ab-7d4f-40b6-b863-5ec54e6a3c1c.jpg)

**Comment by bawa** [comment]
@sanluan thx, but this seems to be an example for codemirror5 and we need this mode to be native for codemirror6. ATM I am trying to simply use the legacy approach based on StreamLanguage but this is workaround
