### ISSUE TITLE
Alt-tab replaces select-all with "-"

### ISSUE THREAD

**Issue by reecer** [codemirror/CodeMirror#4569]
I was able to reproduced on the [simple mode demo](https://codemirror.net/demo/simplemode.html) using latest version of either Firefox or Chrome on Windows 10.

1. Right-click -> Select-All.
2. Right-click -> Copy.
3. Alt-tab to non-browser window (wait here for at least 1 second).
4. Alt-tabbing back to the browser will replace all the previously selected text with a single "-".

It is difficult to reproduce consistently and may take a couple attempts -- sometimes repeating steps 3-4 will cause the issue. It seems specific to copying via the context (right-click) menu.

**Comment by marijnh** [comment]
Attached patch seems to fix this (though reproducing it wasn't reliable, so, though I did try for a while, it might be that it just randomly didn't happen when testing the fix -- let me know if you can still reproduce it)

**Comment by reecer** [comment]
LGTM. Thanks for your efforts!
