### ISSUE TITLE
[merge] collapsing/uncollapsing folded text should trigger a realign when mode = aligned

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4571]
Currently, collapsing/uncollapsing text results in the alignment being broken.

**Comment by marijnh** [comment]
There is code specifically handling this, and when I collapse a piece of code in the merge demo, I see the alignment updating. Can you give a more detailed set of instructions to reproduce?

**Comment by marijnh** [comment]
I guess this is the same issue as #4575 -- when the change in height occurs in a piece of unchanged code, the aligning doesn't re-align on that point.
