### ISSUE TITLE
[merge] inconsistent handling of differences in trailing newline

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4572]
All of these assume a two-way merge.html, with mode = align

![ex1](https://cloud.githubusercontent.com/assets/5050719/22913140/f0ec5d36-f21d-11e6-9209-e8cd5ce0adbd.png)

![ex2](https://cloud.githubusercontent.com/assets/5050719/22913143/f2c5bf3a-f21d-11e6-8d80-7423c399d8bd.png)

![ex3](https://cloud.githubusercontent.com/assets/5050719/22913144/f46e3d6c-f21d-11e6-8816-286a0ebac8b8.png)

![ex4](https://cloud.githubusercontent.com/assets/5050719/22913145/f5bd2232-f21d-11e6-851d-5c995827e389.png)

In most of the above screenshots, the line that differs by the presence/absence of a trailing newline is **not** highlighted as being different. The highlighting only occurs in the last example, where the *only* difference between the two sides is the presence of the last newline in the document.

**Comment by marijnh** [comment]
I found two issues in the way chunks are drawn near the end of the document. The drawing should be more consistent now -- take a look.

**Comment by mtaran-google** [comment]
Thank you, yes these work great.
