### ISSUE TITLE
[merge] inserting line widgets messes up connect = align

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4575]
1. merge.html
2. run `d = document.createElement('DIV'), d.style.height = '100px', dv.editor().addLineWidget(118, d)`
3. scroll the left pane to the bottom and observe that it scrolls farther than the right pane

**Comment by marijnh** [comment]
What the addon does is align every line below a changed chunk. Attached patch sets up the merge addon to listen to changes in line widgets and realign in that case, but that doesn't really solve what you're seeing here. -- I guess you're expecting _every_ line to be aligned with the corresponding line in the other editor. But doing that is quite expensive if done naively, and awkward if done intelligently (which would require tracking all line widgets in the editors, figuring out whether they are in changed chunks or in unchanged chunks, and adding corresponding placeholder spacers to the other editor). Are you sure that is what you need, or is it possible to just manually add a corresponding spacer to the other editor when you insert a line widget?

**Comment by mtaran-google** [comment]
Yes, I think the solution you describe ("done intelligently") would be the preferred way out of this.

Our interactions with CodeMirror are already complicated enough, especially when dealing with two and three pane scenarios, so adding spacers manually isn't really an option.

FYI: The use case for us with the line widgets is showing code-review comments inline. You can also reply to those comments, etc. so it'd be great if the .changed() method on the LineWidget also properly updated the sizing of the corresponding spacer.

**Comment by marijnh** [comment]
All right, I'll try to make time to look into this soon.

**Comment by mtaran-google** [comment]
it mostly works, but this seems to still break it:

1. 3 pane & aligned
2. h = dv.editor().addLineWidget(118, document.createElement('div'))
3. set height:100px on the new div in the inspector
4. call h.changed()
5. scroll the middle pane down

actual: scrolling of the middle pane gets disconnected

expected: stays connected

**Comment by marijnh** [comment]
Right. Attached patch should help with that.

**Comment by mtaran-google** [comment]
I still repro the same issue, even without .changed()

1. 3 pane & aligned
2. `d = document.createElement('div'); d.style.height = '100px'; h = dv.editor().addLineWidget(118, d)` (line 120 locally when I just git cloned)
3. scroll middle panel all the way down

actual: scrolling of the middle pane gets disconnected from the left/right

expected: stays connected

**Comment by marijnh** [comment]
Yes, there was an issue on chunk or end-of-doc boundaries. Try with attached patch.
