### ISSUE TITLE
[annotatescrollbar] If annotation ranges are not in top-to-bottom order, annotations can get clipped or dropped.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4576]
If the annotations are not in order, then the annotations can be clipped. This can be observed by comparing
  https://jsfiddle.net/9s5dLwv4/
against
  https://jsfiddle.net/o5cta772/1/
where the former randomly shuffles the annotation ranges to be out of order.

If this is WAI, then the documentation should probably be updated to mention that the annotation ranges must be in order.
  http://codemirror.net/doc/manual.html#addon_annotatescrollbar

**Comment by adrianheine** [comment]
From a quick look at [annotatescrollbar.js](https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/annotatescrollbar.js) it seems like `Annotation.prototype.redraw` indeed expects them to be in order.
