### ISSUE TITLE
Syntax highlight in a specific region

### ISSUE THREAD

**Issue by user-de-git** [codemirror/CodeMirror#4578]
Is it possible to apply syntax highlight only between specific regions of code, say

`Var x
Sub routineName ( temp as Object )
    x= temp
End Sub

x = temp`

In the above 'temp' should be color-coded/higlighted only in the sub and not on the outside. 
The last line 'temp' should not be color coded.

I guess i will need to know line numbers based on stream (https://github.com/codemirror/CodeMirror/issues/1340)

**Comment by marijnh** [comment]
You don't need line numbers, you need to keep mode state that indicates whether you are in a sub and which local variables are known. The JavaScript mode does this, for example.

Closing, as this is a question, and not an issue. Please use [the forum](https://discuss.codemirror.net/) for those in the future.
