### ISSUE TITLE
indentAuto is broken for JavaScript

### ISSUE THREAD

**Issue by m0sa** [codemirror/CodeMirror#4580]
Version: `5.23.0`
Options: `{ mode: 'javascript', electricChars: false, lineNumbers: true, lineWrapping: true }`

Executing `CodeMirror.commands.indentAuto` for the following code

```
(function() {
  console.log(foo + "=>");
})();
```

results in

```
(function() {
  console.log(foo + "=>");
              })();
```

http://meta.stackoverflow.com/q/339779/155005

**Comment by marijnh** [comment]
I can't see this on http://codemirror.net/mode/javascript/

**Comment by m0sa** [comment]
You're right, I forgot to update the javascript mode file when updating CodeMirror, and I didn't know about the codemirror.net/mode/ sites to test it there.
