### ISSUE TITLE
Marking text seems inconsistent when overlapping sections

### ISSUE THREAD

**Issue by bmass02** [codemirror/CodeMirror#4582]
# Problem
When marking text that overlaps one another, some inconsistencies arise. If an encompassing text is marked after an inner text, then it seems deleting any text that includes editable text deletes the uneditable text also. However, the only uneditable text that is deleted is text that follows the editable text.

# Solution
If you change the order of marking the text (i.e. mark the encompassing text first) then the marked text acts as expected (i.e. uneditable text isn't edited).

I'm not sure if this functionality is intended. If so, maybe updating the docs on marking text would help.

# Reproduction
https://jsfiddle.net/udskry4v/19/

The first CodeMirror editor has the problem.
The second has the fix.

Thanks for the great software!

**Comment by bmass02** [comment]
After further looking into it, this is only the case when both marked texts have "readOnly" set to true.

**Comment by marijnh** [comment]
The problem appears to go away when I run this outside of jsfiddle, with the current version of CodeMirror. If you can reproduce it as a stand-alone HTML file (preferably without jQuery or superfluous searchCursors), that'd help.

**Comment by bmass02** [comment]
Here is a gist(https://gist.github.com/bmass02/0f40a6ee3dea2236b7214bd1abedfc94) I created using CodeMirror v5.23.0 with only codemirror.js and codemirror.css. It still behaves the same. Although I did notice that the inner text does not get deleted. So maybe creating the outer marked text failed silently? Thanks for the quick response!

**Comment by bmass02** [comment]
Alright, I did some more digging and the problem seems to come from the "removeReadOnlyChanges" function. When attempting to remove a section of text that starts inside an editable range but finishes past the inner marked text, there are 2 part objects returned for the failing setup and only 1 for the solution setup. I'll continue to look into exactly where the problem is.

**Comment by marijnh** [comment]
Fixed via #4588
