### ISSUE TITLE
Why ES6?

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [codemirror/CodeMirror#4584]
I have a 'pure Javascript' project with minimal dependencies.
CodeMirror is working great, until I tried to upgrade to the latest version in which you are using imports and the codemirror.js is:

import { CodeMirror } from "./edit/main"
export default CodeMirror

This simply fails in our environment which expects pure JS files in a folder structure we control.

My question is why did you start using ES6 without consulting your customers/donators?

**Comment by marijnh** [comment]
`lib/codemirror.js` works _exactly_ the same as it did in earlier releases. If you're cloning the repository without building it, then stop doing that and use the package from NPM or the zip from the website.
