### ISSUE TITLE
Well formed XML is displayed as invalid

### ISSUE THREAD

**Issue by ashitvora** [codemirror/CodeMirror#4586]
I have an XML file which is passing validation rules but code mirror is throwing an error as not well-formed XML.

Here's the link to XML file https://paste.laravel.io/gQD5r

**Comment by marijnh** [comment]
That contains a line so long that CodeMirror decides not to fully highlight it. See the [`maxHighlightLength`](http://codemirror.net/doc/manual.html#option_maxHighlightLength) option for configuring that behavior.
