### ISSUE TITLE
TypeError: Cannot read property 'propertyKeywords' of undefined

### ISSUE THREAD

**Issue by tscislo** [codemirror/CodeMirror#4592]
I got this defect today:

`[ERROR]   var propertyKeywords = cssMode.propertyKeywords || {},
[ERROR]                                 ^
[ERROR] TypeError: Cannot read property 'propertyKeywords' of undefined
[ERROR]     at evalmachine.<anonymous>:16:33
[ERROR]     at Object.exports.getMode (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\codemirror\addon\runmode\runmode.node.js:145:17)
[ERROR]     at Object.exports.runMode (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\codemirror\addon\runmode\runmode.node.js:164:22)
[ERROR]     at TokenizerCodeMirror.tokenize (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\jscpd\lib\tokenizer\TokenizerCodeMirror.js:67:18)
[ERROR]     at TokenizerCodeMirror.tokenize (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\jscpd\lib\tokenizer\TokenizerCodeMirror.js:4:59)
[ERROR]     at Strategy.detect (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\jscpd\lib\strategy.js:39:23)
[ERROR]     at Detector.start (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\jscpd\lib\detector.js:26:23)
[ERROR]     at JsCpd.run (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\jscpd\lib\jscpd.js:50:28)
[ERROR]     at Object.<anonymous> (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\jscpd\lib\cli\cli.js:43:11)
[ERROR]     at Object.cli.main (G:\tools\Jenkins\workspace\misc.goldenEye.mobile - review build\node_modules\cli\cli.js:957:14)`

Anyone got this defect?
Any solutions?

Thank you!

**Comment by marijnh** [comment]
The SASS mode started depending on the CSS mode (to get a full list of property and keyword names), so you have to make sure `mode/css/css.js` is loaded if you want to use the SASS mode.

**Comment by tscislo** [comment]
Only the newest version is affected by this? Is there any version which is
not affected by this issue? Thanks!

Kind regards / Pozdrawiam
Tomasz Scislo
scislot@gmail.com
http://scislo.eu
http://mobilenext.scislo.eu

**Comment by marijnh** [comment]
You can stay on version 5.23.0 if loading an extra mode is, for whichever reason, a hard thing
