### ISSUE TITLE
Is there a RegEx mode highlighting?

### ISSUE THREAD

**Issue by wufeifei** [codemirror/CodeMirror#4593]
I have a textarea, the value is RegEx.
```
<textarea>shell_exec\s*\(\s*(.+?)\s*\)</textarea>
```

I hope the can highlighting, What `mode` should I choose?

Thanks.

**Comment by marijnh** [comment]
We don't have a regexp mode in the main distribution. There seems to be a crude one [here](https://github.com/uccser/cs-field-guide/blob/25d1e084f701087ad9497d29d2a508629ba536a7/interactives/base-files/js/third-party/codemirror-mode-regex.js), but note that that one doesn't use standard token types so you need custom CSS to actually see the highlighting it produces.

**Comment by wufeifei** [comment]
Thanks a lot!
