### ISSUE TITLE
coloring the gutter doesn't play well with line widgets and wrapping

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4596]
Our use case is that we want to color the left-hand gutter to reflect some info about the code. In particular, we try to add a thin vertical line in the gutter for regions that have been changed or added. We use .setGutterMarker with a div that has height 100%, with a background color specified.

This normally works well and looks good. But, if the code wraps (lineWrapping = true) or if we add some line widgets to the code, or if the merge mode adds some aligners, the solid vertical line we were having in the gutter becomes broken.

This is essentially the same issue we were reporting in #4536 but we've discovered that our workaround for it was causing some other hard-to-diagnose scrolling problems, so I'm reporting it again/separately. You can see some of the scrolling problems with that workaround in http://jsfiddle.net/xzjrywLk/5/ -- if you resize the right panel so that each CodeMirror can only fit 2 chars on a line, when you try scrolling the different panels their scrolling can get detached when scrolled down to the bottom.

Let me know if we can provide a better description of the issue.

**Comment by marijnh** [comment]
Hi. I understand the issue, but this is just not a feature that currently exists, and as such isn't something you can just ask for, under our existing contract.

**Comment by mtaran-google** [comment]
Then please add some documentation in the manual section for doc.setGutterMarker specifying that trying to color contiguous sections of the gutter is not supported, because this is just not a warning that currently exists, and as such isn't something that your users will just know not to do.

**Comment by marijnh** [comment]
I'm sorry, but enumerating every use case that is not supported in the docs does seem a little much to ask.

**Comment by mtaran-google** [comment]
Our contract includes "Ensuring that the CodeMirror website is kept accurate and accessible". 

If you insist that this use case is unsupported, it should be noted as such on the site.

**Comment by marijnh** [comment]
What I mean is that there are an infinite number of things that CodeMirror does not do, and trying to enumerate every specialized thing that it doesn't do in the docs would be a ridiculous exercise. I'm really can't understand why you are pressing for this.

**Comment by mtaran-google** [comment]
Because on our end this was something that did appear to work for all use cases for many years, and you now saying that it's "not supported" is of little help to us.

The question here is not about the "infinite number of things that CodeMirror does not do", but about this specific usage of gutter marking. For most of those other things that CodeMirror can't do, if someone tries to make CodeMirror do them, they'll see an error or just not observe the right behavior, and then either give up or ask for help. Whereas with this, if you just set the background color on a gutter marker, it'll appear to work fine in almost all normal cases.

That's the kind of gotcha that really needs to be documented.

**Comment by marijnh** [comment]
Have you tried `editor.addLineClass(line, "gutter", "my-class-with-a-border")`, by the way? That won't end up in a specific gutter, but might still provide a decent way to put a line in there.

Or maybe set a `.CodeMirror-gutter-wrapper { height: 100% }` style, to allow the 100% in your marker style to actually refer to the whole line height?

**Comment by mtaran-google** [comment]
This isn't really about a line, it's more about generally trying to make a UI that continuously colors a swath of the gutter using gutter markers. It appears you're saying that's the unsupported use case.

We do set height=100% on the gutter wrapper. That results in broken alignment in merge mode.
