### ISSUE TITLE
Unexpected indentation using R after if statement without braces

### ISSUE THREAD

**Issue by NiallC** [codemirror/CodeMirror#4603]
Problem: When using R syntax help there's a minor indentation bug.
If an if statement is given without braces than all subsequent lines are indented.
More specifically:

**Expected:**
No indentation due to if statement without braces (except for immediately succeeding line)
**Actual:** 
All lines below the if statement get indented, though they have nothing to do with that if statement.

System: This has been reproduced on a number of browsers on mac and Linux. Right now I'm using Linux with Chrome Version 56.0.2924.87 (64-bit)

I have confirmed that this bug reproduces at https://codemirror.net/mode/r/index.html

----------------------

To reproduce this:
1. Go to https://codemirror.net/mode/r/index.html
2. Enter the following code:

```
if (TRUE) {
  cat("I used braces, so cider intents lower code normally.\n")
}

cat("Here's a normal statement.\n")
cat("This line did not get indented on enter.\n")

if (TRUE)
  cat("I didn't use braces, so cider now indents 1 block lower down.\n")

cat("Here's a normal statement.\n")
  cat("This line got indented on enter due to braceless if statement above.\n")
```

Observe that the final line always gets indented on enter, or if you start a new line, note that it gets indented.

**Comment by mtaran-google** [comment]
Btw, NiallC is in Google so this should fall under our support contract (just noting since he's not in the Github org yet).

**Comment by marijnh** [comment]
Attached patches make the R mode handle semicolon-less,  brace-less blocks better. They use a rather rough heuristic, because completely accurately determining end-of-statement would require a pretty much full parse, which would require a much more complicated mode, but I think they should work well in normal code. Take a look.

**Comment by NiallC** [comment]
(Who do you want to take a look? I don't know how to patch the system. I've actually never used it directly)

**Comment by mtaran-google** [comment]
the patches are generally immediately visible on the codemirror site, so in this case it would be at http://codemirror.net/mode/r/

seems to work well there :)

**Comment by NiallC** [comment]
I agree, this looks great.

Thanks!

**Comment by marijnh** [comment]
Great.
