### ISSUE TITLE
[merge addon] Chunks sometimes have editFrom > editTo

### ISSUE THREAD

**Issue by alur** [codemirror/CodeMirror#4607]
We use a different diff algorithm with the merge addon, so I don't have a super-clean repro. It still returns a DMP-style diff, but it sometimes varies a bit in how it segments the result.

There seems to be some issue when text with newlines on both ends is deleted. For example, with the original content being `"x\n\na\n\nx"` and the new content being `"x\n\nx"` our diff returns `[[0,"x\n"],[-1,"\na\n"],[0,"\nx"]]` (DMP returns `[[0,"x\n\n"],[-1,"a\n\n"],[0,"x"]]` in this case, basically just considering different newlines deleted).

For some reason the merge mode's getChunks method returns this: `[{"origFrom":2,"origTo":3,"editFrom":2,"editTo":1}]`

I'm guessing it's related to the startOfLineClean/endOfLineClean methods somehow, but I'm not entirely clear what you're trying to do with those.

**Comment by marijnh** [comment]
Attached patch fixes that test case. Could you see if it solves the issue generally for you?

(Is the alternative diff implementation you're using open source? I've been intending to move away from the, apparently unmaintained, diff-match-patch, but haven't been able to find anything that comes close in speed.)

**Comment by alur** [comment]
That does seem to fix it. Thank you!

Unfortunately, no, it's not open source. Though I'm not sure there is any reason it couldn't be. I'll look into it.
