### ISSUE TITLE
[css-mode] Add "system-ui" as a value keyword

### ISSUE THREAD

**Issue by legion80** [codemirror/CodeMirror#4609]
Add "system-ui" as a value keyword

https://drafts.csswg.org/css-fonts-4/#valdef-font-family-system-ui
https://www.w3.org/blog/CSS/2015/11/19/minutes-telecon-267/

**Comment by adrianheine** [comment]
What about the other 3 generic font families mentioned in the draft?

**Comment by legion80** [comment]
They could be included, but I'm unsure about how wide support there is across browsers for those values at the moment. `system-ui` I know is available in Chrome and Safari.
