### ISSUE TITLE
shift-select with contentEditable drops part of selection

### ISSUE THREAD

**Issue by relkinnikler** [codemirror/CodeMirror#4625]
See https://plnkr.co/edit/lKjgmiRDdLuhM7btVWc9?p=preview

Put your cursor at the start of the code editor, then scroll down to the bottom, then shift click to select all the text. Now press delete. Notice that the entire selection is not deleted. (Alternatively, instead of pressing delete, scroll up, you'll see the selection is cut off.

The same problem seems to occur if you ctrl-A to select all, but it's less consistent. (Sometimes it works. Sometimes it doesn't seem to select anything at all.)

Turning off contenteditable seems to fix this problem. 

Setting viewportMargin to Infinity also seems to fix this problem, so it seems related to the viewport in some way.

**Comment by marijnh** [comment]
Attached patch should help here.

**Comment by mce2** [comment]
Unfortunately this fix does not solve the problem completely. I faced the same problem, and it appears that in _contenteditable_ mode selection cannot be longer than approximately 40 lines (with default _viewportMargin_). When I press Ctrl-A with a long text, the whole text gets selected (I can copy it and paste elsewhere), but only first lines can be higlighted, and if initial scroll position is not in the beginning of the document, selection is invisible.

**Comment by marijnh** [comment]
Good point. Attached patch should improve things further.

**Comment by mce2** [comment]
Yes, my test case works fine now! Thanks!
