### ISSUE TITLE
[merge] Nested gaps in 3-way merge can result in unneeded gaps.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4627]
See https://jsfiddle.net/c3rjpdxg/1/

I've tracked it down to seeing that `chunk.editTo > rLine` is true at the following line when the nested gap is encountered:
https://github.com/codemirror/CodeMirror/blob/master/addon/merge/merge.js#L382
It should account for the possibility of the gap having been nested.

**Comment by marijnh** [comment]
What I'm seeing is (with the gaps styled as yellow):

![gaps](http://marijnhaverbeke.nl/upload/gaps.png)

The gap that you appear to have labeled 'MISALIGNED GAP' is necessary to make the 'Horse' line in the center and right editors line up. I.e. that part of the right document doesn't have gaps, so the gaps in the middle and left one are needed to make things align.

Or am I not understanding the issue correctly?

**Comment by takamori** [comment]
Sorry, I didn't clarify that the *left* pane has the bad gap in the jsfiddle. The problem is seen user-visible via the gap above "BAD GAP ABOVE" in the left pane. The MISALIGNED GAP in the center highlights the origin of the bad gap, which is why I pointed out the code block I mentioned as being the source of the error.

**Comment by takamori** [comment]
Here's a simplified version: https://jsfiddle.net/c3rjpdxg/2/

<img width="854" alt="screen shot 2017-03-06 at 5 44 32 am" src="https://cloud.githubusercontent.com/assets/54738/23612379/1e26a50a-0230-11e7-859d-7299926a1e3a.png">

Where I've marked the two lines in between no gap is expected. The origin of the gap is the line below "Frog" in the center; it doesn't account for that there is no alignment needed since there's already a gap next to the gap, and instead offsets from the bottom of the left gap, which is why it's 6 lines below.

**Comment by marijnh** [comment]
Right, I see what you mean now. Attached patch seems to solve the issue for me. Could you verify that it works for you?

**Comment by takamori** [comment]
sorry, I forgot to update this bug; yes, that fixes it.
