### ISSUE TITLE
Pasting from Notepad++ removes all line endings

### ISSUE THREAD

**Issue by shawnajean** [codemirror/CodeMirror#4632]
We had a user recently report that pasting into GitHub's editor from Notepad++ on Windows 10 in Firefox 51 removes all line endings from the content. We tried changing the line endings setting in Notepad++, but all options gave the same result.

We were able to reproduce this on Windows 10 in Firefox 51.

**Comment by marijnh** [comment]
Can you reproduce the issue in the demos on http://codemirror.net ? Do you know the precise text that Nodepad++ puts on the clipboard?

**Comment by shawnajean** [comment]
> Can you reproduce the issue in the demos on http://codemirror.net ?

We were not able to repro on codemirror.net, but checking in with our developers led us to file here. We do use the contentEditable inputStyle on GitHub, which I forgot to mention in my initial comment.

> Do you know the precise text that Nodepad++ puts on the clipboard?

I don't, so I've asked my teammate who was able to repro this to chime in here, as I personally don't have Windows.

**Comment by JoelEinbinder** [comment]
I can't reproduce this with Firefox 52, Windows 10, with contentEditable mode on my local CodeMirror nor with GitHub's editor. Maybe there is another factor?

**Comment by marijnh** [comment]
Thanks for providing a data point.

**Comment by shawnajean** [comment]
Thanks for the bump! We recently updated the version of CodeMirror on GitHub and we haven't been able to repro since. We've asked the reporting user to let us know if this is still an issue for them, but haven't heard back yet.

I'll close this out since it seems to be resolved!

**Comment by coolziroonezero** [comment]
> 

> [``]( #http://coolziro.com)
