### ISSUE TITLE
Cmd/Ctrl+X cuts a line even when there's no selection

### ISSUE THREAD

**Issue by afercia** [codemirror/CodeMirror#4633]
Hello :)
Not sure if it's the intended behaviour or maybe a bug, but doesn't look right to me. Tested on the [main demo](https://codemirror.net/index.html) on both macOS Sierra and Windows 10 in different browsers.

Pressing Cmd/Ctrl+X cuts a whole line even if the line is not selected. Seems to me a bit counterintuitive, since cut operations should happen only when there's some selection.
Thanks!

**Comment by marijnh** [comment]
This is a feature. You can turn it off with [this option](http://codemirror.net/doc/manual.html#option_lineWiseCopyCut) if you want.

**Comment by afercia** [comment]
Thanks @marijnh !
