### ISSUE TITLE
Backspacing across lines on Android is broken

### ISSUE THREAD

**Issue by marijnh** [codemirror/CodeMirror#4637]
Specifically, when there is a gutter, trying to backspace at the start of the line removes the virtual keyboard and does nothing.

The issue appears to be a mobile Chrome bug which, in this HTML (which is a simplification of what CodeMirror creates when there is a gutter)

```html
<div contenteditable=true>
  <pre>foo</pre>
  <div contenteditable="false">(gutter)</div>
  <pre>bar</pre>
</div>
```

if you put the cursor before 'bar' and press backspace, the document isn't changed, but the selection is moved into the non-editable `div`, and thus the virtual keyboard disappears.

**Comment by marijnh** [comment]
Attached humongous hack works around this

**Comment by edemaine** [comment]
For what it's worth, this issue remains unfixed with the popular SwiftKey Android keyboard.  You do seem to have fixed it on e.g. Samsung's keyboard though -- thanks!

**Comment by marijnh** [comment]
Android keyboards considered harmful

**Comment by marijnh** [comment]
I installed SwiftKey, and didn't see any issues. Could you be more specific about the problem you're seeing?

**Comment by edemaine** [comment]
Hmm, I just tested again on the `codemirror.net` demos, and I concur: it seems to work fine now.  Specifically, when backspacing at the beginning of a line, the keyboard disappears briefly, but comes back.

There may have been a SwiftKey update recently that fixed this.  Anyway, I think you can close the issue again.  Sorry for the hassle!
