### ISSUE TITLE
[md mode] bad highlighting with fencedCodeBlocks: true

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4639]
1.         fencedCodeBlocks: true,
2. paste in the following:
~~~markdown
```shell
```

*   foo

    *   bar
~~~

expected: the bullets are highlighted like bullets (or just text)
actual: the bullets are highlighted like code

compare to how it works in http://spec.commonmark.org/dingus/ for example

**Comment by marijnh** [comment]
Could it be that this was already fixed by 7580a1dc1d7ce1ab? I can reproduce in 5.24.2, but not in master.

**Comment by mtaran-google** [comment]
Yep, I believe we're good now.
