### ISSUE TITLE
Should indentation be applied to text in html or xml modes by default?

### ISSUE THREAD

**Issue by GreatEarl** [codemirror/CodeMirror#4640]
I have block of text like 
`<div id=“wrap”><div class=“item”><h1>Hello World!</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim nisi quis est fringilla semper.</p><p><a href="http://www.google.com.au" target="_blank">Visit Google</a></p><ul><li>Phasellus et maximus nunc.</li><li>Morbi sapien arcu, blandit vel nibh sed, sagittis finibus ex.</li><li>Pellentesque sollicitudin tincidunt metus sed convallis.</li><li>Aliquam erat volutpat.</li></ul></div></div></p>`

When I put it to editor - I see the same text with coloured (according to theme) html-tags but without indentation. All examples in docs are shown with indentation. 
My code is below
` var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
       lineNumbers: true,
        styleActiveLine: true,
        matchBrackets: true,
        mode : "xml",
        lineWrapping: true,
        htmlMode: true,
        indentUnit: 4, 
        indentWithTabs: true
       });
 var theme = "colorforth";
  editor.setOption("theme", theme);`
May be I missed something?
xml.js is included.

**Comment by marijnh** [comment]
CodeMirror doesn't format your code for you. It can auto-indent (shift-tab in the default keymap), but it won't insert newlines.

**Comment by GreatEarl** [comment]
Ok, thank you. Now it is clear. Actually, I need to select all editor content and auto-indent it programmatically. Is it mentioned in Programming API?
