### ISSUE TITLE
cm-invalidchar using include file with html template

### ISSUE THREAD

**Issue by nunos7** [codemirror/CodeMirror#4642]
Hi, 
There is a way to load html to codemirror using </textarea>
            </form>`

but get a span with a cm-invalidchar!

Thanks,
NS

**Comment by marijnh** [comment]
I have no idea what `<!--#include` is, so this is probably the wrong place to ask.

**Comment by nunos7** [comment]
I use codemirror to show and copy blocks of html and javascript code.
In this case i need to load that block of html from a file...

In my other cases i use this:
`<form><textarea><div class="demo">hello world!</div></textarea></form>`

But here i need to load the code from a template page.

**Comment by nunos7** [comment]
Problem solved... 
My template was saved with Unicode (UTF-8 with signature) - Codepage 65001, i changed to Unicode (UTF-8 without signature) - Codepage 65001 and that's it.
