### ISSUE TITLE
5.22.0 broke my usage of JavaScript mode syntax highlighting

### ISSUE THREAD

**Issue by kentcdodds** [codemirror/CodeMirror#4645]
Somewhere in [these changes](https://github.com/codemirror/CodeMirror/compare/5.21.0...5.22.0). Syntax highlighting was broken:

**v5.21.0**

![screen shot 2017-03-16 at 6 34 50 am](https://cloud.githubusercontent.com/assets/1500684/23996348/ace1f8aa-0a12-11e7-9322-0068cdfde0bf.png)

**v5.22.0**

![screen shot 2017-03-16 at 6 35 16 am](https://cloud.githubusercontent.com/assets/1500684/23996369/ba8e3298-0a12-11e7-84ca-fd61eb95d62a.png)

I'm not sure what caused this. I'm not getting any error messages in the console (before or after) and I'm not changing any of my code.

My usage is fairly straightforward. I am using [`react-codemirror`](https://github.com/JedWatson/react-codemirror) but I've verified that it's simply forwarding my options. I'm including:

```html
<link href="node_modules/codemirror/lib/codemirror.css" rel="stylesheet">
```

on my page and I'm importing:

```javascript
import 'codemirror/mode/javascript/javascript'
```

My options are:

```javascript
{
  lineNumbers: true,
  mode: 'javascript',
}
```

I hope that's helpful. Let me know what else I can do to help debug this issue. Thanks!

**Comment by marijnh** [comment]
> I'm not sure what caused this. 

Neither are we, and the report doesn't contain enough information to act on.
