### ISSUE TITLE
React Native source is not highlighted properly

### ISSUE THREAD

**Issue by joshfriend** [codemirror/CodeMirror#4650]
React native [refuses to recognize `*.jsx` files](https://github.com/facebook/react-native/pull/5296), So all react native source has a `*.js` extension. This is causing highlighting issues with code like this:

```js
// example.js
class Example extends React.Component {
   render() {
    return (
      <View>
        <Text>{`${this.props.startDate}`}</Text>
      </View>
    );
  }
}
```

Is rendered by [javascript mode](https://codemirror.net/mode/javascript/index.html) like this:
![atlfgrg](https://cloud.githubusercontent.com/assets/885137/24044571/3c52ecc6-0af2-11e7-8eee-2d6951e1d9cd.png)

I'm not sure if there's actually a bug here or not (since it renders OK with JSX mode). AFAICT, JSX won't be part of the ECMAScript spec. Maybe there's still something that can happen in CodeMirror to help alleviate this unfortunate design decision in React Native?

**Comment by marijnh** [comment]
This is a problem of deriving the language from the extension, and then using extensions that are usually associated with another language. I don't think CodeMirror can be expected to automatically handle that. The solution is probably set up your editor to use jsx mode for .js files.

**Comment by joshfriend** [comment]
Hmm, that's too bad, I don't have control over the render mode on Bitbucket Server.
