### ISSUE TITLE
htmlmixed mode reports inner mode too early

### ISSUE THREAD

**Issue by thehogfather** [codemirror/CodeMirror#4651]
In the htmlmixed mode, the attribution of a given inner mode however starts too early- i.e.,  at the opening tag of the html element (instead of its content). Take the following as an example:

```html
1 <html>
2  <head>
3    <style>
4      .foo {
5        color: red;
6      }
7    </style>
8  <head>
9 </html>
```

Lines 1, and 2 correctly return the `xml` mode. Line 3 however returns a mode of `css` - despite it only containing an opening html tag. One would expect the `css` mode occurs between line 4 - 6.

The context for this is in codefolding, where it might be useful to detect the appropriate fold helper based on the mode at a line or position.

Update: Affected version: `5.24.2`

**Comment by marijnh** [comment]
What exactly are the symptoms of the problem? I've added some nested CSS to the [folding demo](http://codemirror.net/demo/folding.html) and folding around it seems to work fine -- you can fold both the whole `<style>` tag, and the braces inside of it.

**Comment by thehogfather** [comment]
The issue was mine. The `ch:` property of `Pos` that I passed into `cm.getModeAt` was undefined. Consequently, the mode returned for the given lines were not what I expected (i.e., line 3 in the example above returned mode `css` instead of `xml`.

Closing. Thanks for the quick feedback.
