### ISSUE TITLE
th evalue of textearea is not returning with getValue()

### ISSUE THREAD

**Issue by chemseddineZ** [codemirror/CodeMirror#4652]
I can't get the value of the `textarea` with `getValue()`, in fact any method i try either `getValue`() or `setValue()` i get the same error saying that 

> TypeError: editor.getValue is not a function

the code that i've tried so far
`  var editor =  CodeMirror.fromTextArea(document.getElementById('editor'), {
          lineNumbers :true,
          indentUnit: 4,
          matchBrackets: true
        });`

**EDIT**
and i'm getting the value with 
`var editor_value = editor.getValue();`

**Comment by marijnh** [comment]
What is `editor` bound to when you call `editor.getValue()`? If it's the instance returned by `CodeMirror.fromTextArea`, it would definitely work. Are you trying to call those methods on a DOM textarea element?

**Comment by chemseddineZ** [comment]
`editor` is bound to `CodeMirror.fromTextArea` as in the code 
`var editor = CodeMirror.fromTextArea(document.getElementById('editor'), { lineNumbers :true, indentUnit: 4, matchBrackets: true });`

**Comment by marijnh** [comment]
Great, then what you're doing there is correct, and the problem exists elsewhere.

**Comment by chemseddineZ** [comment]
even when i try `editor.setValue()` it fails with error saying 

> TypeError: editor.setValue is not a function
