### ISSUE TITLE
how to hide scroll bar 

### ISSUE THREAD

**Issue by Jiaojunjun** [codemirror/CodeMirror#4654]
code:
  <textarea id="input" autofocus style="background-color:transparent;height:100px;width:300px;font-size:25px;overflow-x:hidden;border:0;margin:0;color:green;text-indent:0px;"
             onkeydown='if(event.keyCode==17){PrefixInteger()}';></textarea>
    <script type="text/javascript">
    var myCodeMirror = CodeMirror.fromTextArea(document.getElementById("input"), {
      mode:"text/javascript",
	  theme:"mainframe",
	  lineNumbers:true,
	  lineNumberFormatter:PrefixInteger,
	  scrollbarStyle: "null"
![1](https://cloud.githubusercontent.com/assets/26647330/24287600/444cb858-10b5-11e7-8676-8c903c253ea0.jpg)

	  });

**Comment by marijnh** [comment]
It's in [the docs](http://codemirror.net/doc/manual.html#option_scrollbarStyle).

**Comment by Jiaojunjun** [comment]
but null is not effective

**Comment by marijnh** [comment]
Looks like you have some kind of CSS issue, and the editor's internal hidden scrollbars are becoming visible.

**Comment by Jiaojunjun** [comment]
@marijnh I search the codemirror 5.13.2 library, there is no null or native file

**Comment by Jiaojunjun** [comment]
resolved, change the .CodeMirror-scroll overflow to hidden.
