### ISSUE TITLE
Close Tag addon doesn't work properly

### ISSUE THREAD

**Issue by aweimeow** [codemirror/CodeMirror#4655]
Hi, 
I found this bug in another project: hackmdio/hackmd#400.

Developer of `HackMD` said this bug may cause by `CodeMirror's Close Tag addon`, 
[this link](https://hackmd.io/GYI2AYE4GYCYBYC05aRI+BTTtEEM8BGAVkQA5JYATYSzEeScIA==) is a demo page in **HackMD** for reproduce the bug.

### About the bug

* If I type someword I want to delete: 
    I want to have delete line on this sentence.

* And I put `<s>` in the beginning like following: 
    \<s>I want to have delete line on this sentence.

* Here will automatically show the close tag with inproperly content like following: 
    \<s>\<\/sI>I want to have delete line on this sentence.

> I thought the word `I` shouldn't appear in closetag \</s>

Thanks a lot 😄

**Comment by marijnh** [comment]
This doesn't appear to be happening on http://codemirror.net/demo/closetag.html , so I guess HackMD is running an old or modified version of the code.
