### ISSUE TITLE
Improve search dialog.

### ISSUE THREAD

**Issue by MariasStory** [codemirror/CodeMirror#4656]
Can you pleas improve the search dialog.
For reference please see:
https://microsoft.github.io/monaco-editor/index.html

![image](https://cloud.githubusercontent.com/assets/6576335/24360699/619eb42e-1308-11e7-9589-f903176ea42b.png)

And it would be nice to have the option to search as you type.

**Comment by marijnh** [comment]
No, I'm not going to do this. But you are very much encouraged to fork that addon and distribute an improved version.

**Comment by MariasStory** [comment]
Hi,

Maybe someone else is interested in this feature?

Greetings.
