### ISSUE TITLE
match-highlighter.js: add an option to skip single-match case

### ISSUE THREAD

**Issue by tophf** [codemirror/CodeMirror#4661]
Currently, at CodeMirror 5.24, the [match-highlighter.js](https://github.com/codemirror/CodeMirror/blob/1e072d52a62f2bd359d61704c7eade2c35b0062d/addon/search/match-highlighter.js) addon unconditionally highlights a single match occurrence which is IMHO very misleading and confusing.

It'd be nice if there was an option to avoid highlighting when only one match is found.

FWIW, below is my lame hack (from what I understood in CM source code there's no way to avoid a sliding timer):

```diff
@@ -89,6 +89,6 @@
   function addOverlay(cm, query, hasBoundary, style) {
     var state = cm.state.matchHighlighter;
-    cm.addOverlay(state.overlay = makeOverlay(query, hasBoundary, style));
+    cm.addOverlay(state.overlay = makeOverlay(cm, query, hasBoundary, style));
     if (state.options.annotateScrollbar && cm.showMatchesOnScrollbar) {
       var searchFor = hasBoundary ? new RegExp("\\b" + query + "\\b") : query;
       state.matchesonscroll = cm.showMatchesOnScrollbar(searchFor, false,
@@ -156,8 +156,23 @@
-  function makeOverlay(query, hasBoundary, style) {
+  function makeOverlay(cm, query, hasBoundary, style) {
+    const approvedClassName = `cm-${style}-approved`;
+    let timer;
+    let occurrences = 0;
     return {token: function(stream) {
+      clearTimeout(timer);
+      timer = setTimeout(() => {
+        occurrences = 0;
+        timer = null;
+      });
       if (stream.match(query) &&
-          (!hasBoundary || boundariesAround(stream, hasBoundary)))
+          (!hasBoundary || boundariesAround(stream, hasBoundary))) {
+        occurrences++;
+        if (occurrences == 1) {
+          cm.display.wrapper.classList.remove(approvedClassName);
+        } else if (occurrences == 2) {
+          cm.display.wrapper.classList.add(approvedClassName);
+        }
         return style;
+      }
       stream.next();
       stream.skipTo(query.charAt(0)) || stream.skipToEnd();
     }};

```

And for the hack I use this CSS:

```css
.cm-matchhighlight-approved .cm-matchhighlight,
.CodeMirror-selection-highlight-scrollbar {
  background-color: rgba(1, 151, 193, 0.1);
}
```

Edit: reworked the code.

**Comment by marijnh** [comment]
Overlays should not have side effects, so you can't use them to do what you're trying to do here. I'm okay with the current behavior, so if you want something else, you'll have to create your own fork of the addon.

**Comment by tophf** [comment]
The "side effect" refers only to my hacky implementation which has nothing to do with the feature if I understand your objection correctly. You can simply disregard that code and what it implies. 

The idea per se may be implemented properly if you can extend CodeMirror's overlay API so that when token() is invoked from highlightWorker's doc.iter it receives an additional parameter to indicate start/stop of the iteration in this run of highlightWorker and a parameter to indicate the overall completion.

**Comment by marijnh** [comment]
No, that's fundamentally not how overlays work. They take text input and output styling _without_ knowing about anything else. That's how they can be cheap and efficient, and it's not changing.

**Comment by tophf** [comment]
Not knowing the stage of processing is not what makes overlays fast, obviously, and I don't know why you appear to think there's a direct connection. 

On the other hand, knowing the processing state would open more possibilities at an effectively zero cost of comparing a boolean parameter or a line index number. For example, with the latter it would be possible to alter overlay behavior based on proximity to the active line. And that's just one example off the top of my head.

**Comment by marijnh** [comment]
> Not knowing the stage of processing is not what makes overlays fast, obviously, and I don't know why you appear to think there's a direct connection.

Because I designed and wrote this code. But thanks for explaining it to me.

**Comment by tophf** [comment]
That ironic retort sounds like you didn't read the second paragraph. Welp, I guess I'm not good at selling ideas so I see no point of pursuing this further.
