### ISSUE TITLE
Problems just getting the zipped download to work

### ISSUE THREAD

**Issue by rsz2040** [codemirror/CodeMirror#4663]
The repository as downloaded into my apache htdoc folder not working, what I am doing wrong?  When I navigate to the codemirror directory, the index.html page comes up just like the website but it can not find codemirror.js because

<script src="lib/codemirror.js"></script>    and codemirror.js is in the /src/ directory, not the /lib directory.

If I change the line to src/codemirror.js then it finds it but then I get the JS error:

SyntaxError: import declarations may only appear at top level of a module

**Comment by marijnh** [comment]
Which zip, exactly, are you downloading?

**Comment by rsz2040** [comment]
The one right here on github

https://github.com/codemirror/CodeMirror

Green button on the upper right "Clone or download",  click on it, then at the bottom of the little dropdown "Download Zip"  link.

![zipdl](https://cloud.githubusercontent.com/assets/6885664/24501881/6aebb50a-1519-11e7-83a1-820d07bf7bfc.png)

**Comment by marijnh** [comment]
Ah, that's the repository, not a built package. Get it from [the website](http://codemirror.net/codemirror.zip) or NPM instead.
