### ISSUE TITLE
Support highlighting for Terraform files

### ISSUE THREAD

**Issue by mkobit** [codemirror/CodeMirror#4667]
https://www.terraform.io/

Would be awesome to see support for the `.tf`  and `.tfvars` file extensions used with Terraform

**Comment by marijnh** [comment]
We're not taking mode feature requests, or even new modes, so the way to proceed would be to write such a mode and distribute it separately.

**Comment by mkobit** [comment]
My fault! @marijnh where would I find that? Would it make sense to add an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) so others don't make the same mistake I did?
