### ISSUE TITLE
[typescript] overflow of `` quoting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4668]
1. https://codemirror.net/mode/javascript/typescript.html
2. paste in
```typescript
function b(@C() d: E): f<G> {
  return `${h}`;
}
```

**Comment by marijnh** [comment]
`@` is not part of any JavaScript dialect that the JavaScript mode parses (I guess it's supposed to be an annotation here?)

**Comment by marijnh** [comment]
Patch fa69bef4 adds decorator support.
