### ISSUE TITLE
The showHint function doesn't work well for customised properties

### ISSUE THREAD

**Issue by zhaoyi0113** [codemirror/CodeMirror#4673]
I am using CodeMirror.showHint function to popup a list of commands for auto-completion. Below is the code I have. The `hint` function works great and the commands in the list can be shown on code mirror editor. but the `displayText` and `text` doesn't have any impact. And the `render` function is not called. The manual I am reading is from https://codemirror.net/doc/manual.html#api `hint/show-hint.js` section. Is this the correct place I need to look at? And I want to replace the current content with auto completion command but currently it only appends on the end of my input. How can I implement this with CodeMirror auto-completion?

```
const options = {
            displayText:'Mongo Commands',
            text: 'text',
            hint () {
              return {
                from: cm.getDoc().getCursor(),
                to: cm.getDoc().getCursor(),
                list: commandList
              };
            },
            render: (Element, self, data) => {
              console.log('@@@@@')
            }
          };
          cm.showHint(options)
```

**Comment by marijnh** [comment]
The `render` method (as well as `displayText`) goes into the individual items, they are not options. If you want to replace a piece of the document, make sure that `from` and `to` are different. In general, spend a bit more time [reading the manual](http://cm/doc/manual.html#addon_show-hint) before opening an issue.

**Comment by zhaoyi0113** [comment]
I am reading the manual from here: https://codemirror.net/doc/manual.html#addon_lint. And whether there is an example on how to use it?

**Comment by zhaoyi0113** [comment]
The `from` and `to` don't work as expected. For example, if I type `db` and trigger the auto-completion popup, it will show the popup after the cursor. When I select one item from the popup list, the selected text will be inserted at the cursor. When i need is to replace the `db` word with the selected text. If I change the `from` to be 2 positions ahead of the current cursor, the popup doesn't show at all and the `db` characters are removed immediately.

**Comment by marijnh** [comment]
> If I change the from to be 2 positions ahead of the current cursor,

`from` should be _before_ `to`

**Comment by zhaoyi0113** [comment]
Yes I didn't change `to`. I just minus the `from.ch` by 2. Below is the code I am using. You can see that the `curWord` is the one I need to replace. I minus the `from.ch` by the length of `curWord`. But after doing this, the popup doesn't show and the `curWord` is removed from editor.

```
const cursor = cm.getDoc().getCursor();
          cursor.ch -= curWord.length;
          const options = {
            hint() {
              return {
                to: cm.getDoc().getCursor(),
                from: cursor,
                list: res
              };
            },
          };
          cm.showHint(options);
```

**Comment by marijnh** [comment]
> cursor.ch -= curWord.length;

You're mutating an object owned by the editor. Don't do that.

**Comment by zhaoyi0113** [comment]
what is the correct way to do that?

**Comment by marijnh** [comment]
`new CodeMirror.Pos(cursor.line, cursor.ch - 2)`

**Comment by zhaoyi0113** [comment]
Thanks it works. Regarding to your first reply, `The render method (as well as displayText) goes into the individual items`. Could you give me an example to explain what does `go into the individual items` mean? I have a lot requirements on auto-complete and want to understand how to make use of all code mirror features. But the manual only gives an API explanation doesn't give an example on that.
