### ISSUE TITLE
I built a sass/scss-lint for CM

### ISSUE THREAD

**Issue by blackmiaool** [codemirror/CodeMirror#4674]
[The introduction of it](http://stackoverflow.com/questions/43127937/scss-linter-for-codemirror/43203069#43203069)

As I said in the answer above, it's mainly based on [**sass-lint**](https://github.com/sasstools/sass-lint). Do you think the linter can be in this repo?

**Comment by marijnh** [comment]
No, I'm not accepting new addons into the main distribution. Please distribute this as a separate NPM package.
