### ISSUE TITLE
Selection is not getting removed on clicking

### ISSUE THREAD

**Issue by AasmaGarg** [codemirror/CodeMirror#4677]
We have upgraded CEF version from 2526 to 2840. With this upgrade, we are facing one issue in CodeMirror where selection is not getting removed on clicking.

Steps to Reproduce:
1. Select the complete text inside the editor
2. Click again to deselect

Expected behavior:
Selection should be removed

Result:
Selection retained.

Platform: Mac
OS version: 10.12

Attaching a video:
![test](https://cloud.githubusercontent.com/assets/8016570/24752560/0dfd0cb2-1aec-11e7-90e5-c0aba173106d.gif)

**Comment by AasmaGarg** [comment]
While debugging I found that, in CodeMirror.js SetSelection was not getting called. And the reason was the time difference between dragEnd and dragStart is more than 200 ms in leftButtonStartDrag function.

**Comment by marijnh** [comment]
I don't know what CEF is, but I could reproduce this in the plain editor, and attached patch should fix it.
