### ISSUE TITLE
How can I position a gutter to right?

### ISSUE THREAD

**Issue by chsch911028** [codemirror/CodeMirror#4681]
is this possible to make a gutter on the right side of the codemirror?

![gutter-question](https://cloud.githubusercontent.com/assets/20242070/24827698/13d61c88-1c8a-11e7-881f-b5393099044c.png)

**Comment by marijnh** [comment]
Nope, that's not something the library supports.

**Comment by kultuk** [comment]
is there a way for it to be supported?

**Comment by marijnh** [comment]
We're taking it into account as a desirable feature in the next version, but for now, no
