### ISSUE TITLE
Tokenizer issue in SCSS mode

### ISSUE THREAD

**Issue by swmitra** [codemirror/CodeMirror#4688]
Consider the following snippet of SCSS rule definition ( cursor is marked using a pipe char )
```
.test:|
```
Calling `getTokenAt` with the cursor position marked above returns the token state as `pseudo` and the token string as `":"` which is as expected. But consider the following snippet with the cursor placed at the same position -
```
.test:| {
}
```
Calling `getTokenAt` with the cursor position marked above returns the token state as `block` instead of `pseudo` and the token string as `": {"` . This results into ambiguity in inspecting the current token state. The same scenarios in CSS is consistent though with current token string and state as `":"` and  `pseudo` respectively. 

Question: Is this expected? If yes, how should we reliably find out whether the current context is `pseudo`?

**Comment by marijnh** [comment]
The issue was that adjacent tokens with the same style (in this case, null style) are merged to avoid creating too many DOM nodes. Attached patch adjusts the CSS mode to attach a non-null style to colon characters, to avoid the issue in this case. Does that help?

**Comment by swmitra** [comment]
Just tried the patch in SCSS mode, I could still see the same issue where `:` and the trailing space along with the `{` is captured in a single token.

**Comment by marijnh** [comment]
Argh. I misdiagnosed the problem -- the SCSS mode seems to explicitly be tokenizing `:\s*{` as a single token (line 753 in css.js). I have no idea what `: {` means in SCSS, and there's no tests covering it, so I'm hesitant to touch that.

**Comment by swmitra** [comment]
I was excited to see the commit and the issue getting closed. It's not exactly fixed the problem here. The token string is `:` though, but state has not changed.

**Comment by marijnh** [comment]
There is no state that corresponds to SCSS-just-before-property-block in the CSS mode's state machine.

**Comment by swmitra** [comment]
Thanks a lot @marijnh . I got it to work now 👍
