### ISSUE TITLE
coordsChar is slow with long bidi lines

### ISSUE THREAD

**Issue by JoelEinbinder** [codemirror/CodeMirror#4691]
When moving the cursor in a line with rtl characters and greater than ~5,000 lines, coordsChar is very slow. The behavior appears after 864a681b4d57823687c2

**Comment by marijnh** [comment]
@adrianheine Do you have time to take a look at this?

**Comment by JoelEinbinder** [comment]
Sorry I pasted the wrong has. It was 864a681b4d57823687c2

**Comment by marijnh** [comment]
So the proposed patch is apparently not entirely correct. Having the non-fast-path code be this slow is a fairly serious problem, though. Any chance you could allocate some more time for this, @adrianheine ?
