### ISSUE TITLE
Remote Autocomplete Hint

### ISSUE THREAD

**Issue by Monds** [codemirror/CodeMirror#4704]
Does has an example of a remote autocompletion hint with codemirror?
(using CodeMirror.registerHelper with ajax?)

**Comment by marijnh** [comment]
The [tern addon](http://codemirror.net/demo/tern.html) works asynchronously to be able to use a web worker backend -- it's not _remote_, but the techniques involved are the same.

This here, by the way, is the bug tracker, not a discussion forum. Please post things like these [here](https://discuss.codemirror.net/) in the future.
