### ISSUE TITLE
setValue doesn't update the view when element is hidden

### ISSUE THREAD

**Issue by lostincomputer** [codemirror/CodeMirror#4708]
setValue doesn't update the view when the element is hidden. The view only gets updated when the user clicks the editor.

**Steps to reproduce**

1. Hide the editor
2. Call setValue
2. Show the editor

Old value is still being displayed until the user clicks the editor

http://jsbin.com/mowejurama/edit?html,output

**Version**
5.25.2

**Browsers**
Tested in two browsers and the bug can be reproduced in both
Chrome 57.0.2987.133
IE 11

**OS**
Windows 7

**Comment by marijnh** [comment]
This is intentional. Call `refresh` on the editor when you show it.
