### ISSUE TITLE
Code split view Feature in Codemirror

### ISSUE THREAD

**Issue by Abubakar63** [codemirror/CodeMirror#4717]
<img width="991" alt="screen shot 2017-04-06 at 4 14 41 am" src="https://cloud.githubusercontent.com/assets/7919866/25485138/380b6ff4-2b76-11e7-9b36-4ade6b671618.png">
I need to add some functionality to split my screen so that I can see & work on 2 files simultaneously. Does codemirror have any addon for this feature.

Thanks.

**Comment by marijnh** [comment]
There's no addon, but it is possible to build such a thing with the core API. See [this demo](http://codemirror.net/demo/buffers.html).

Also, please don't ask questions in the bug tracker. Use [the forum](https://discuss.codemirror.net/) for that.
