### ISSUE TITLE
Custom scroll doesnt work with mouse wheel

### ISSUE THREAD

**Issue by PatrickMevia** [codemirror/CodeMirror#4718]
Since day or two there is a problem with custom scroll feature, mouse wheel doesnt affect scroll handle and also content scrolled by mousewheel is glitchy and doesnt work. I thought it may be my application went bad, but it also doesnt work on demo page.

**Comment by marijnh** [comment]
Is this maybe a duplicate of #4713? Does the patch provided there help?

**Comment by PatrickMevia** [comment]
well coud be, blinking is also there, i dont see any patch, i am connected to latest github repo and problem is still there, and not just for me.

**Comment by marijnh** [comment]
I can't reproduce it anymore. The patch (c98bd2205625c1358e003f0a3d0) was only added an hour ago. Make sure you have it and have rebuilt the library.

**Comment by adrianheine** [comment]
I'm closing this for now. Feel free to re-open if the patch didn't fix the issue.
