### ISSUE TITLE
Update cursor position while dragging (or get cursor position on-demand)

### ISSUE THREAD

**Issue by mindplay-dk** [codemirror/CodeMirror#4719]
I'm trying to implement drag-and-drop file-upload for a Markdown editor.

I've tried both [this](https://github.com/asika32764/inline-uploader) and [this](https://github.com/Rovak/InlineAttachment/blob/master/src/inline-attachment.js), but neither of those drop into the correct position - that is, CodeMirror will [indicate](https://github.com/codemirror/CodeMirror/issues/2645) the drag destination, but there doesn't seem to be any way to obtain that position via the API?

I've tried listening for the `dragover` event:

```js
cm.on('dragover', function () {
    console.log(cm.getDoc().getCursor());
});
```

But the cursor position doesn't update.

There's an [internal `posFromMouse`](https://github.com/codemirror/CodeMirror/blob/96cd8885ad759350273c71235493f6b225590442/src/measurement/position_measurement.js#L556) function, but it doesn't appear to be exposed via the public API?

If it were, I would be able to pass the mouse event to it and find the drag destination.

But as things are now, it doesn't look like there's any way to implement this?

**Comment by marijnh** [comment]
Use [`coordsChar`](http://codemirror.net/doc/manual.html#coordsChar).

**Comment by HelgeSverre** [comment]
Example of the answer from @marijnh 


```javascript
editor.on("drop", function (cm, event) {
    var coords = cm.coordsChar({
        left: event.x,
        top: event.y
    });

    cm.replaceRange("Some Text", coords);
});
```

**Comment by nomad5** [comment]
@HelgeSverre When I use this it only works when the page's scroll is at the top. When the page is scrolled down even just a little the drop location is incorrect, it goes some lines above where the drop was intended. It seems to drop further upwards the more the page is scrolled down.

**Comment by sn3p** [comment]
@nomad5 I think the event coords are relative to the window.

You should be able to solve this by passing `"window"` as `mode` param:

```js
var coords = cm.coordsChar({
  left: event.x,
  top: event.y
}, "window");
```

See https://codemirror.net/5/doc/manual.html#markText

> The optional `mode` parameter determines relative to what the coordinates are interpreted. It may be `"window"`, `"page"` (the default), or `"local"`.
