### ISSUE TITLE
Mode auto detection

### ISSUE THREAD

**Issue by jspn500** [codemirror/CodeMirror#4722]
I'm currently working on merging CodeMirror with ProseMirror and I was wondering if there is any possible way to auto-detect the mode of pasted code so that I could auto highlight it on pasting? Thanks.

**Comment by jspn500** [comment]
I'm thinking about using https://github.com/github/linguist as a backend service for language detection. It allows us to parse the string, split it into tokens and classify the languages. I wonder if there is a similar functionality in CodeMirror that I could use to detect the language on client side.

**Comment by peterkroon** [comment]
Not sure about ProseMirror but here is a demo for CodeMirror: http://codemirror.net/demo/changemode.html

**Comment by marijnh** [comment]
There's nothing like that in CodeMirror. You might be able to find a solution in JavaScript, since finding the language for a string has nothing to do with editing. It seems https://highlightjs.org/ can detect languages, but I'm not sure whether that part is available as a separate module.
