### ISSUE TITLE
IME is at abnormal status if something is inserted while composition.

### ISSUE THREAD

**Issue by gaokunbuaa** [codemirror/CodeMirror#4726]
Hi:
I am using codemirror as editor for sharedb, and found one issue about IME as below:

1. Open two editors on two separated PC to do collaborative edit.
2. In one editor switch input method to Chinese, type something and leave it as composition status;
3. In another editor (on another computer) type something within the same area of the first editor( or the same line)

At this condition, I can't input more Chinese in the first editor. 
Does this mean the input composition can't be interrupted?

thanks

**Comment by marijnh** [comment]
Does patch ea8aa6b help with this?

**Comment by gaokunbuaa** [comment]
Great. This patch works very well for me.
Thanks a lot.
