### ISSUE TITLE
[markdown] link with a line break in square brakcets gets highlighted wrong

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4735]
e.g. 

1. https://codemirror.net/mode/markdown/
2.
```markdown
[foo
bar](https://foo#_a)
should not be italics
```

expected: last line not italicized
actual: last line italicized

(interestingly, github gets this wrong too. but it works as intended in try.commonmark.org)

**Comment by marijnh** [comment]
Attached patch should help. It's also likely to produce false-positives for link highlighting if you're relying on brackets that don't look like links not highlighting, but given CodeMirror's limited lookahead, we can't have it both ways.
