### ISSUE TITLE
[merge] Merge mode doesn't play well with line wrapping

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4736]
1. https://codemirror.net/demo/merge.html
1. Click 'align'
2. `dv.right.orig.setOption('lineWrapping', true) && dv.edit.setOption('lineWrapping', true)`
3. Drag the left scrollbar down

expected: alignment persists, or at least is not totally broken

actual: alignment is totally broken

Bad things also happen if you don't have align on.

**Comment by marijnh** [comment]
Can you define 'totally broken' and 'bad things' a bit more precisely? Trying this (I had to replace `&&` with `;` because `setOption` doesn't return anything), I couldn't see any problems during a few minutes of playing around (Chrome, Linux).

**Comment by mtaran-google** [comment]
Ah, that issue with && was my problem. I'll reopen or file a separate bug if I come up with a better case :)
