### ISSUE TITLE
Electric chars shouldn't trigger in (multi-line) string context

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4739]
E.g. right now in the Go mode, whenever you are writing a multiline string and type a :, it gets indented to the left.

**Comment by mtaran-google** [comment]
E.g. right now in the Go mode, whenever you are writing a multiline string and type a :, it gets indented to the left.

**Comment by marijnh** [comment]
The usual solution for this used by other modes is to not have `indent` mess with indentation inside strings or comments. Attached patch fixes this for Go.
