### ISSUE TITLE
Indention Markers

### ISSUE THREAD

**Issue by amcdnl** [codemirror/CodeMirror#4751]
I'm trying to add indentation markers for CodeMirror. You can see below an example of this being accomplished in the RAML editor ( which uses codemirror ).

![raml](https://i.stack.imgur.com/xDT0U.png)

Taking a look at the code there is a `cm-indent` class added thats applying this style:

![code](https://i.stack.imgur.com/eE0WT.png)

I've searched through the code base looking for this css class and the docs but don't see a plugin for this capability. 

There is a [rulers](https://codemirror.net/demo/rulers.html) plugin that allows you to add markers vertically but these don't align with indentions like the example above.

Does anyone know if some way to accomplish this?

**Comment by marijnh** [comment]
I am not aware of a CodeMirror addn that does this. There exists a [Brackets plugin](https://github.com/lkcampbell/brackets-indent-guides), though. Since Brackets is based on CodeMirror, you might be able to get useful inspiration from that.

**Comment by amcdnl** [comment]
@marijnh - this is what i was looking for. thank you!

**Comment by Longgererer** [comment]
Wow, I have the same problem, it is a good solution!
