### ISSUE TITLE
Issue with findModeByExtension function in mode/meta.js

### ISSUE THREAD

**Issue by christosnc** [codemirror/CodeMirror#4752]
In **mode/meta.js** file, the **findModeByExtension** function doesn't return anything if a match wasn't found.

e.x. if you try the code:

`editor.setOption("mode", CodeMirror.findModeByFileName(this.querySelector('.filename').innerHTML).mode);`

will work on every supported filename but on unsupported ones will return undefined

This issue can be **resolved** easily by placing return("null"); as the last line of the findModeByExtension function.

**Comment by marijnh** [comment]
JavaScript functions will return undefined if they fall off the bottom of the function body, so there's no need to add an explicit return statement when undefined is an acceptable return value.
