### ISSUE TITLE
Add Hg to the command set for the Shell Mode

### ISSUE THREAD

**Issue by KyleMcNutt** [codemirror/CodeMirror#4763]

**Comment by marijnh** [comment]
Could you elaborate? As it is, I have no idea what you mean.

**Comment by KyleMcNutt** [comment]
@marijnh I mean, that it would be nice to have `hg` be a highlighted command in the shell.js mode

**Comment by KyleMcNutt** [comment]
@marijnh Opened PR #4764 to address this

**Comment by marijnh** [comment]
Solved via #4764
