### ISSUE TITLE
Large code blocks cannot be searched through with browser search

### ISSUE THREAD

**Issue by andlabs** [codemirror/CodeMirror#4766]
I am passing some JavaScript through code formatters that expand it significantly (to upwards of 20,000 lines). At that point, if I try to find a specific function in that JavaScript by using the browser's search (as all built-in features of CodeMirror are disabled on these websites), the browser fails to find anything until the function is scrolled into view, which doesn't help.

Trying to copy and paste fails; it just copies an em dash or something like it into the clipboard instead. (This might have to do with me deliberately disabling the DOM clipboard functions; if it is, not having that issue is probably a separate issue. Strangely, this doesn't happen with the version of CodeMirror used by GitHub Gists anymore; I wonder if they made a local change...)

Browser: Firefox Nightly 55.0a1 2017-05-21 64-bit on OS X 10.11. I do not know which releases of CodeMirror are affected because I do not maintain the websites that use them, but I can name the ones I tried as jsbeautifier.org and www.danstools.com/javascript-beautify.

Thanks.

**Comment by marijnh** [comment]
This is a necessary effect of CodeMirror architecture. See #221
