### ISSUE TITLE
indent wrapped lines to match the indent of given line

### ISSUE THREAD

**Issue by dwelle** [codemirror/CodeMirror#4769]
IMO wrapped lines should match the indent of the line that's being wrapped, to make them easier to read.

codemirror behavior:

![image](https://cloud.githubusercontent.com/assets/5153846/26579422/14279928-4534-11e7-8e22-3e2c5379b034.png)

sublime text/atom/notepad++/[ace editor](https://github.com/ajaxorg/ace/pull/2187) behavior:

![image](https://cloud.githubusercontent.com/assets/5153846/26579418/0e37b00c-4534-11e7-9242-3888b210a385.png)

Also, optionally indent by `orig_indent + 1 extra`:

![image](https://cloud.githubusercontent.com/assets/5153846/26579646/e8fccbe6-4534-11e7-8ac7-f7adf1788f5a.png)

**Comment by marijnh** [comment]
There's a [demo](http://codemirror.net/demo/indentwrap.html) showing how to do this on the website, but this isn't going to be the default behavior.
