### ISSUE TITLE
Unexpected behavior in chrome based browsers after using markText-function in bidirectional input (in a corner case)

### ISSUE THREAD

**Issue by IrinaGlushanok** [codemirror/CodeMirror#4770]
Hello!
There is a problem, which occurs in Chrome based browsers when using markText-function.  In order to tailor the bidi-algorithm I insert an LRM (left-right-mark) in certain positions (always before a quotation mark) of the bidirectional input string and then use  the markText-function to make these both characters (the LRM and the following quotation mark) atomic. This works fine in Firefox, IE, Edge and Safari, but fails in a one special case in Chrome Version 58.0.3029.110, Chromium and Vivaldi. If the arabic input string contains the substring ال (unicode  \u0627\u0644), it seems like the browser wouldn't see the character \u0627. The cursor position in this case is always before the last character, not behind as expected, so the following quotation mark is displayed on the same position as \u0627. I suppose, this is the cause. I'm using the codemirror version 5.7.0. With the current version there is the same problem.

Expected rendering:
![right_rendering](https://cloud.githubusercontent.com/assets/13150210/26582678/4e4543ea-4542-11e7-9e1d-6c8621a85f4f.png)

In Chrome:
![wrong_rendering](https://cloud.githubusercontent.com/assets/13150210/26582710/6dbb8e8c-4542-11e7-85d6-153037ea7284.png)

Right cursor position:
![right_cursor_position](https://cloud.githubusercontent.com/assets/13150210/26582737/82a9ff18-4542-11e7-9866-1a10bd0cbfea.png)

Wrong cursor position:
![wrong_cursor_position](https://cloud.githubusercontent.com/assets/13150210/26582754/9093afca-4542-11e7-8bda-6b9816c289c6.png)

Here the sample code, that I used:
[test_insert_lrm.zip](https://github.com/codemirror/CodeMirror/files/1038235/test_insert_lrm.zip)

Best regards

**Comment by adrianheine** [comment]
Hi, thanks for your report. CodeMirror's bidi algorithm does not take directionality markers into account. I can reproduce this issue in my Chromium 58. The Chromium developer tools have the same problem, too. I think this is a browser bug.

**Comment by IrinaGlushanok** [comment]
Ok. Thank you for your reply!

**Comment by IrinaGlushanok** [comment]
Hi! I've tried it in Chrome 59 and it works well.
