### ISSUE TITLE
Request: more graceful Vim error handling

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#4771]
cc @mightyguava 

In CodeMirror's bundled Vim mode, users aren't given a lot of guidance on what options will work or not. Users on my site often just try various options. Unfortunately, whenever this happens, CodeMirror will throw an exception: https://github.com/codemirror/CodeMirror/blob/c81cba4d351ee4a51a5994b446decc4c5438ac31/keymap/vim.js#L414.

I think this is probably not the right thing to do. I don't think attempting to get/set an unavailable option counts as a runtime error, and this definitely blows up our error reporting. We could try to install a try/catch, but it's not clear where that should go. Also, the Vim mode doesn't throw a specific kind of error, so you'd have to parse the messages on all errors caught.

I propose that the Vim mode instead simply just display a message to the user that the option is not yet implemented and leave it at that.

**Comment by marijnh** [comment]
This sounds like a good idea, but you'd probably have to implement it yourself and submit a PR, since no one is actively maintaining the vim bindings.

**Comment by marijnh** [comment]
Solved via #4775
