### ISSUE TITLE
"text/x-bigquery" mime type

### ISSUE THREAD

**Issue by gyamxxx** [codemirror/CodeMirror#4778]
Sorry, I'm not good at English.
Could you support "text/x-bigquery" mime type ?
http://codemirror.net/mode/sql/index.html

**Comment by Paul-Cunningham** [comment]
+1 for BigQuery support please.
Also, Jinja2-laced SQL, as used by dbt

**Comment by marijnh** [comment]
We're not adding more language modes to the main distribution. So if you want something like to exist, the approach would be to implement and distribute it yourself as a separate package.
