### ISSUE TITLE
Support payloads in text markings

### ISSUE THREAD

**Issue by viridium** [codemirror/CodeMirror#4779]
Text marking objects are persistent between edits and we can store our own payloads in those objects, but the feature is not documented or standardized, and we could always break CodeMirror by accidentally putting our payloads in an internal property on the TextMarking object.

Can we support (and document) a "payload" property on TextMarking, or corresponding accessors?

See also: https://discuss.codemirror.net/t/payloads-in-text-markings/1270.

**Comment by marijnh** [comment]
_Please_ don't ask the same question here and on the forum, that just fills my mailbox and this bug tracker with duplicate junk.

Ref: https://discuss.codemirror.net/t/payloads-in-text-markings/1270

**Comment by viridium** [comment]
I'm starting to see a pattern of quick rejection of my tickets. That is not constructive. If you don't like my suggestions, I'm going to stop making them.

The question was the wrong way to go. A bug is the better way, because this is a feature request. I realized this after writing the suggestions; I'm sorry the world isn't perfect…
