### ISSUE TITLE
Allow placement of cursor inside of atomic markings

### ISSUE THREAD

**Issue by viridium** [codemirror/CodeMirror#4780]
Can we change the behavior of atomic to allow placement of the cursor inside the marking, but prevent editing? This would make it more intuitive to work with such markings. For instance, we want our users to click or otherwise put the cursor inside the marking in order to get information about it. The UX is weird when the cursor refuses to go in.

Better yet, maybe the cursor should turn into a selection on that whole marking, indicating what would happen if Backspace were hit.

**Comment by marijnh** [comment]
> Can we change the behavior of atomic to allow placement of the cursor inside the marking, but prevent editing?

No, that's what readOnly does.

**Comment by viridium** [comment]
Except that:
- readOnly acts on the whole text
- readOnly doesn't allow you to edit any of the text

**Comment by marijnh** [comment]
No, I mean the `readOnly` option to [`markText`](http://codemirror.net/doc/manual.html#markText)

**Comment by viridium** [comment]
I see. I've just tested it, and, with `readOnly`, the marked text cannot be removed.
