### ISSUE TITLE
Double-clicking on a text marking should select it

### ISSUE THREAD

**Issue by viridium** [codemirror/CodeMirror#4781]
Instead, the cursor moves to either the left or the right.

**Comment by marijnh** [comment]
You can add your own handlers on the marker to make it behave like this. That's not going to be the default behavior, because for a lot of markers it makes no sense.

**Comment by viridium** [comment]
How so? If I double-click any text in any browser or OS, the prevailing intuition is that it gets selected. Why would it not make sense for a lot of the markers? Why would marked text get in the way of that?

**Comment by schanzer** [comment]
@viridium , TextMarkers are used for all sorts of things, and it would be semantically incorrect in many of those contexts to have a marker select the text it contains. As @marijnh says, they are flexible enough to allow you to do exactly what you desire. Changing the default to be your particular preference makes sense for _you_, but not for everyone else. Is an extra line of code such a high price to pay for the API not being tailored to your particular preference?

**Comment by viridium** [comment]
What is an example such context where putting the cursor at the end of the marker instead of selecting the marker is the better approach? I'd like to leave this bug behind convinced. :)

**Comment by schanzer** [comment]
Perhaps I'd like to replace a hex value in a CSS file with some kind of widget, presenting the user with a color picker onDblclick().

**Comment by viridium** [comment]
A few remarks and questions:

- Is moving the cursor to the end of the placeholder, versus hiding the cursor or extending a selection over the item, really the better choice?

- Is that really the more common situation, or is it a fringe situation?

- The current behavior needn't be removed: it can be kept, with one default and one hidden behind an option.

**Comment by schanzer** [comment]
`TextMarker`s are designed to be maximally general, and their default behavior should support that. Changing the default effectively changes the semantics of the feature. Yes, "you can always override the default to do what you want"...but then again, so can you. :)

And if you don't buy the "keep the default behavior general" argument, consider this: Changing the default behavior the way you suggest would break large amounts of existing code. Do you really want to break other people's codebases just to save one line of event-handle code in your own?

**Comment by viridium** [comment]
I'm not stuck on changing the default. But the requested behavior is also general enough, so providing it out of the box hidden behind an option sounds reasonable to me.
