### ISSUE TITLE
Infinite loop in coordsCharInner with RTL & LTR text

### ISSUE THREAD

**Issue by alur** [codemirror/CodeMirror#4786]
I tested with this text I found through a quick search for RTL:
> Najib said "السلام عليكم" (as-salaam alaykum] to me.
> Najib said "السلام عليكم" (as-salaam alaykum] to me.

Navigate around  using the arrow keys a little and the browser should freeze up. I'm running Chrome 58 on a mac right now.

The code is stuck in this loop:
https://github.com/codemirror/CodeMirror/blob/2ba7b2c3daafbfda05d4f25aba03eb6422d3b1d7/src/measurement/position_measurement.js#L464

Stack trace:
```
coordsCharInner (codemirror.js:2843)
coordsChar (codemirror.js:2786)
findPosV (codemirror.js:8396)
(anonymous) (codemirror.js:8188)
map (codemirror.js:226)
(anonymous) (codemirror.js:6018)
(anonymous) (codemirror.js:3796)
(anonymous) (codemirror.js:8182)
(anonymous) (codemirror.js:3787)
goLineUp (codemirror.js:6724)
doHandleBinding (codemirror.js:6842)
(anonymous) (codemirror.js:6909)
lookupKey (codemirror.js:6597)
lookupKey (codemirror.js:6603)
lookupKeyForEditor (codemirror.js:6856)
dispatchKey (codemirror.js:6875)
handleKeyBinding (codemirror.js:6909)
onKeyDown (codemirror.js:6927)
(anonymous) (codemirror.js:3779)
```

I dumped the locals at the end of the loop. They stay the same through each iteration:
```
assign: undefined
begin: 0
beginLeft: undefined
ch: undefined
cm: CodeMirror
coords: undefined
diff: 0
diff_change_per_step: undefined
dir: -1
end: 52
i: 0
lineNo: undefined
lineObj: Line
order: undefined
pos: Pos
  ch: 33
  line: 0
  sticky: "after"
preparedMeasure: Object
prevDiff: 0
prevPos: Pos
  ch: 33
  line: 0
  sticky: "after"
prevPos$1: undefined
steps: 0
x: 257
y: 13
```

**Comment by adrianheine** [comment]
Thanks, I will look into it.

**Comment by adrianheine** [comment]
6606ba4930ca8356d4871698e95c80c374e14829 fixed it for me.

**Comment by takamori** [comment]
Repro's if you have the text "yılbaşı" in the doc.
