### ISSUE TITLE
Simple mode - choose token at runtime with callback

### ISSUE THREAD

**Issue by activeperception** [codemirror/CodeMirror#4787]
Hi, 

Is it possible to pass a function as token in simple modes? The function parameters should probably be the return value of stream.match.

In my specific case it would greatly simplify the regular expressions and allow for logic otherwise impossible with REs only. 

Thanks,
 Raffaele

**Comment by marijnh** [comment]
Could you be more specific about what you mean by passing a function as token, and what the use case you need it is like?

**Comment by activeperception** [comment]
```javascript

CodeMirror.defineSimpleMode("simplemode", {
  start: [
     // highlight numbers divisible by 7 
    {regex: /\d+/, token: (match) => match[0]%7==0 ? 'divisible-by-seven'},
     // highlight plural and singular words differently 
    {regex: /\w+/, token: (match) => {
        if (externalLib.isWordPlural(match[0]))
             return 'plural'; 
        return 'singular'
        }
    },
]})
```

These examples are a bit lame but it should give you the idea.

One further improvement would be for the function to return the tuple [match, list-of-token-string], instead of token-string only, so that you can modify the match found by stream.match. 
It could be very useful for example to split the match further and return multiple tokens, one for each new part. (a bit like you do now when you have regex with multiple capturing groups)

For example
```javascript
     // highlight word stems and rest of word differently
     {regex: /\w+/, token: (match) => {
        var [stem, rest] = externalLibrary.stemWord(match[0]);
        // not sure if just pushing is enough, maybe we have to add more info like starting indexes and length of matches like an regexp.match would do
        match[0] = stem;
        match.push(rest);
        return [match, ['stem', 'rest-of-word']];
        }
    },
````

**Comment by marijnh** [comment]
Does attached patch work for you?

**Comment by activeperception** [comment]
Yes! 👍
