### ISSUE TITLE
selection layer does not respect line padding

### ISSUE THREAD

**Issue by dwelle** [codemirror/CodeMirror#4791]
When setting `padding` of lines in the `renderLine` event handler (e.g. as in [indentwrap](http://codemirror.net/demo/indentwrap.html) demo), it correctly sets the line padding, but when text is selected, the `.CodeMirror-selected` does not respect it, resulting in:

when padding is positive:

![image](https://user-images.githubusercontent.com/5153846/27010927-5817300a-4eb0-11e7-8a7a-f5b3a7d555c7.png)

![image](https://user-images.githubusercontent.com/5153846/27010901-ec7ae76a-4eaf-11e7-9743-5502d24345a9.png)

when padding is 0:

![image](https://user-images.githubusercontent.com/5153846/27010902-edd6025c-4eaf-11e7-9f89-e855dde27246.png)

IMO, the selection should take the padding (both `padding-left` & `padding-right`) into account and clip.

**Comment by marijnh** [comment]
Continued selection lines intentionally start from the very left of the editor content view, and even in this case, that seems like the appropriate behavior. Why is this a problem?

**Comment by dwelle** [comment]
Mainly styling issue. I purposefully enabled gutter to illustrate, but we keep the gutter disabled and in certain cases having padding in the hundreds of pixels, which makes it very ugly when selecting lines.

In the first 2 screens I see no point why the selection should span to the start -- it may make some sense when the padding is 5-10px, but when it's more, it's more distracting than not.

3rd screen seems like a bug altogether since the selection _does not_ start from the beginning, while the text _does_. I mean, there's at 2-3px offset of the selection from the start of the editor, which shouldn't be the case (or at least the text shouldn't be allowed to start right off the border, even if `paddingLeft` is set to 0, same as the selection layer isn't).

Either way, how about we add an option `clipSelectionToContentBox` to support this behavior?

**Comment by marijnh** [comment]
> having padding in the hundreds of pixels,

What for? In general, random re-styling through renderLine, such as for example making the padding smaller than the default padding, isn't something that's supported.

**Comment by dwelle** [comment]
> What for?

To make the editor in the center of the screen while making it possible to click outside the bounds to the left/right to put the cursor on respective line.

This is how we've done it previously with ace, and both in ace and cm it works superb (except ace's visual glitch).

**Comment by marijnh** [comment]
Well, you're telling CodeMirror that this space is part of its lines, and it'll draw the selection accordingly. My recommendation would be to either create a narrower editor and just handle clicks on the sides manually, or to generate a single CSS rule that overrides the padding for the whole editor at once. I'm not willing to complicate selection rendering for such an obscure case.
