### ISSUE TITLE
Show-hint does not display suggestions if 'previous' suggestion starts at char 0

### ISSUE THREAD

**Issue by fwielstra** [codemirror/CodeMirror#4792]
I'm working on an autocompletion that should complete an object's properties after pressing the '.' character. In a nutshell, my autocomplete function does the following:

 * Take the current line up until the cursor
 * If there is no dot character in the line, return a list of first-level properties, with property `from` set to 0 (start of line), `end` to `cursor.ch` (current cursor position).
 * If there is a dot character in the line, look up the properties for the object before the dot, return the list with property `from` set to the position of the dot, `to` to end of line.

However, when transitioning from the 'first level' to 'second-level', the suggestions do not pop up. I think I've isolated the cause to the result of the previous completion result (`from = 0` and the second (`from = 3` for example). This issue occurs when fully typing the first string (e.g. `foo.`); it does NOT trigger when having selected the `foo` suggestion from the list and triggering the autocompletion result.

I have a working (or, not working) example here: http://jsbin.com/kisaxefulo/edit

Expected: type `foo.`, get a suggestion list displayed of 'foo', 'bar' and 'baz'.
Actual: type `foo.`, get nothing. Type `foo`, select one option from the list, type `.`, and the list is displayed. The list does appear after typing more than 2 characters after the dot, e.g. `foo.bar.

What am I missing? I feel like I'm returning the right object and properties. I did see a function `isNewCompletion` (https://github.com/codemirror/CodeMirror/blob/master/addon/hint/show-hint.js#L138) which may be related, but I can't see the issue myself. The documentation also doesn't note anything particular about what the hinting function should return in what situations.

**Comment by marijnh** [comment]
I think you should scan backwards from the cursor position, rather than looking at the current line as a whole, but I don't understand the specific issue here. It does sound more like a client code problem than a CodeMirror problem though, so I'm going to close this issue. If you can reduce it to a simple case that shows the library malfunctioning, feel free to add further information.

**Comment by baoshan** [comment]
I'm facing the exactly same issue I guess. Hint not showing due to `isNewCompletion`. I wonder if @marijnh can kindly explain what the line means:

```
if (data && this.data && isNewCompletion(this.data, data)) return;
```

What's the semantics of a `new completion`? Why new completion are not shown? The answer may help other potential contributors (me including) better understand the design.

Thanks!

**Comment by marijnh** [comment]
Git blame can be useful for things like that. It points at f95803c2997b288ed2d7 which in turn points at #3849

**Comment by baoshan** [comment]
Sorry, will do my own homework next time. But for the concrete case, I mean `isNewCompletion` here. If I remove the line:

```
if (data && this.data && isNewCompletion(this.data, data)) return;
```

#3849 seems no problem, works well, the autocomplete suggestions move with the cursor & token in the `/demo/complete.html`. Also my issue and @fwielstra 's issue can be solved. Can you confirm this line still deserves its position?

Thank you and please lead me if I could do more.

**Comment by marijnh** [comment]
I agree that the code does look very suspicious, and doesn't seem to help with the original issue. The state management in this plugin is a mess, and should at some point be cleaned up, but for now we can just drop that line and see if anyone complains. See attached patch.

**Comment by baoshan** [comment]
Thanks for the patch! Will do my job in case of anything strange.
