### ISSUE TITLE
Memory Leaks from Global Event Listerners

### ISSUE THREAD

**Issue by saadataz** [codemirror/CodeMirror#4793]
It looks like these global event listeners attached to window never get removed. 
https://github.com/codemirror/CodeMirror/blob/master/src/edit/global_events.js#L26
https://github.com/codemirror/CodeMirror/blob/master/src/edit/global_events.js#L33

This is causing CodeMirror to never get Garbage Collected. Is there a destroy method/event I can use to clean those up?

**Comment by marijnh** [comment]
> This is causing CodeMirror to never get Garbage Collected.

What leads you to that conclusion? There's nothing in that event handler that's holding onto editor instances.

Or are you hoping for the _library code_ to be garbage collected? If so, what module loader setup are you using, that would even make this possible?

**Comment by saadataz** [comment]
Hey @marijnh. Thanks for the response.
I am using Angular2 (using Zonejs) with webpack. Looking at the heap snapshot, I am seeing detached DOM nodes appended to memoryText eventually referenced by window resize callback even though code mirror has been removed from DOM. I was hoping if there is a destroy method to clean up these global listeners

![image](https://user-images.githubusercontent.com/20386083/27159217-45150c3a-5120-11e7-8a1b-5f2ef9fb4193.png)

**Comment by vincentwoo** [comment]
It might be because of onBlur holding context of the CM instance variable.

@saadataz: if you remove the global listeners manually, do you see these elements freed?

**Comment by marijnh** [comment]
No, there is no way to unregister this callback. But again, if you look at its source, it isn't holding any references to CodeMirror instances, since it uses `getElementsByClassName` to access them on-demand.

**Comment by saadataz** [comment]
Looks like its the callback arrow function keeping the reference of its context. I cannot remove the eventlistener unless I have reference of the callback (which is anonymous)

**Comment by marijnh** [comment]
> Looks like its the callback arrow function keeping the reference of its context.

Which callback arrow function? `registerGlobalHandlers` doesn't _have_ any editor instances in its context, so it can't close over any.

**Comment by saadataz** [comment]
Wont this chain of call keep the reference of CodeMirror instance?
CodeMirror -> ensureGlobalHandlers -> registerGlobalHandlers -> on resize event handler (arrow function)

**Comment by marijnh** [comment]
No, that's not how closures work. I'm going to close this, since I see no evidence for an actual leak here, but if you have further (_concrete_) evidence, feel free to add a comment.

**Comment by ZhangPingFan** [comment]
@saadataz How did you solve this problem finally？I found the same problem when I use vue with webpack and I can see the heap grows everytime I refresh the Chrome.It seems to be related to module in es6 or using as components?Cuz I find it would not happen when I use codemirror by including it in the page.
