### ISSUE TITLE
Yank and Record are written to the same register

### ISSUE THREAD

**Issue by hamir** [codemirror/CodeMirror#4794]
It seems that recordings are being written to the same register as yank.

You can repro by going to https://codemirror.net/demo/vim.html and in the editor, trying the following:

1. go to line 5
2. hit q + ' (you should now see "(recording)[']" at the bottom of the demo widget)
3. left arrow
4. p
5. you'll notice that "LEFT" gets printed (seems recordings are being written to the same register as yank)

**Comment by heppe** [comment]
I captured this in a vim unit test

testVim('macro_yank_tick', function(cm, vim, helpers) {
  cm.setCursor(0, 0);
  // Start recording a macro into the \' register.
  helpers.doKeys('q', '\'');
  helpers.doKeys('y', '<Right>', '<Right>', '<Right>', '<Right>', 'p');
  helpers.assertCursorAt(0,4);
  eq('the tex parrot', cm.getValue());
}, { value: 'the ex parrot'});

The next step is to actually fix it.  Working on that now.

**Comment by heppe** [comment]
a backslash on one of the quotes in the first call to helpers.doKeys got swallowed.

**Comment by heppe** [comment]
This is complete.  Am I able to close it, or do I need to have someone do it for me?

**Comment by marijnh** [comment]
You can close issue if you consider them solved. Closing this one.
