### ISSUE TITLE
HTML element as linenumber

### ISSUE THREAD

**Issue by morpheus-87** [codemirror/CodeMirror#4798]
I'm using the latest release of CodeMirror (5.26.0) and met a problem, when I want to add e.g. a link to the linenumbers. [This line of code](https://github.com/codemirror/CodeMirror/blob/master/src/line/utils_line.js#L84) is responsible for converting every string containing HTML into a normal string. Is this really necessary?

**Comment by marijnh** [comment]
Yes, to be able to cheaply estimate whether a line number requires the number gutter to be wider or narrower than it currently is, the library requires line numbers to be plain text.
