### ISSUE TITLE
Leave vim's command bar open even after screen losing focus

### ISSUE THREAD

**Issue by hamir** [codemirror/CodeMirror#4804]
1. Open https://codemirror.net/demo/vim.html
2. Type ":" and notice the command bar pop up
3. Switch windows or tabs, and notice that the command bar disappears

Expected:
The command bar should remain active even after switching windows. For example often if i'm doing :%s/foo/bar, I will switch windows to figure out what i want foo and bar to be - it's super annoying when it disappears so that I have to start all over with my vim command.

**Comment by marijnh** [comment]
Fixed by #6185
