### ISSUE TITLE
alphabetically order the API docs

### ISSUE THREAD

**Issue by Pomax** [codemirror/CodeMirror#4806]
right now the API documentation is a long list of seemingly randomly ordered function calls that can be used - it would be incredibly useful if that could be alphabetically sorted instead, so that `indentUnit` comes before `theme`, and sits next to `indentWithTabs`, etc. It's a small improvement, but for people who are told to "read the f'ing manual" (with or without explitive =), it makes a huge difference

**Comment by marijnh** [comment]
Things that are related are listed next to each other. You can use Ctrl-F to find something if you know its name.
