### ISSUE TITLE
[vim] cursor moves when switching to insert mode and back

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4812]
1. https://codemirror.net/demo/vim.html
2. focus the editor
3. press `i`, then `esc`

expected: cursor is where it started

actual: cursor is one character left of where it started

**Comment by marijnh** [comment]
I agree this is strange, but this is how regular vim behaves as well, so for a vim emulation mode it is appropriate.

**Comment by mtaran-google** [comment]
Ha! I hadn't actually checked, but you're right that's what it does. Oh well :)
