### ISSUE TITLE
Adding support for newly added SQL keywords in Postgres 9.6 and Postgres 10

### ISSUE THREAD

**Issue by mzabuawala** [codemirror/CodeMirror#4813]
Please add support for newly added keywords in Postgres 9.6 and Postgres 10 versions.

For example: PARALLEL RESTRICTED

[http://imgur.com/a/EKBES](url)

**Comment by marijnh** [comment]
Done in attached patch. Next time, for simple changes like this, I'd appreciate a pull request instead
