### ISSUE TITLE
SQL - Hash tag syntax highlighting incorrect

### ISSUE THREAD

**Issue by mzabuawala** [codemirror/CodeMirror#4815]
Hi,

Syntax highlighting for hash signs looks incorrect.

example query
-- Remove single tag element by path
update tableA set jsonb_field = jsonb_field #- '{key_name}' where fieldA = 'test'

All the text following the # is highlighted in the brown colour, like comments, and loses its correct highlighting.

The issue is that this is a valid query for json data in PostgreSQL.

Please refer : [http://imgur.com/a/NLi4c](url)

**Comment by marijnh** [comment]
Are you using the `text/x-pgsql` mime type? Some dialects (mysql/mariadb) do support line comments starting with a `#`, but this is turned off for the Postgres dialect, so you shouldn't be seeing this if you enable that mime type?

**Comment by mzabuawala** [comment]
Yes, I am using 'pgsql' only, Please refer my CodeMirror definition,
[http://imgur.com/a/z7ED0](url)

**Comment by marijnh** [comment]
That's a 404, but when I go to http://codemirror.net/mode/sql/ and run `editor.setOption("mode", "text/x-pgsql")`, I don't see this issue.

**Comment by mzabuawala** [comment]
Github is redirecting on wrong URL, Please check: http://imgur.com/a/z7ED0

**Comment by marijnh** [comment]
Okay, sure, but as I said, I can't reproduce that. Maybe set up a jsbin/jsfiddle that shows the problem?

**Comment by mzabuawala** [comment]
It has been fixed with latest pull.
