### ISSUE TITLE
empty line has different height in FF, causing jump

### ISSUE THREAD

**Issue by dwelle** [codemirror/CodeMirror#4816]
FF 54, win 10. Cannot repro on codemirror.net FSR. Can repro here: http://jsfiddle.net/yvt20wvq/2/

Causes lines _after_ the active line to jump due to height of active line collapsing by ~1px.. 

![empty_line_ff_jump](https://user-images.githubusercontent.com/5153846/27381107-cf581868-5681-11e7-9631-efc46896aaaf.gif)

**Comment by marijnh** [comment]
Doesn't seem to happen on FF 56 Linux. Could you try to figure out why it doesn't occur in the demos but does in some other situations? One possibility would be that it's related to the font.

**Comment by dwelle** [comment]
Seems it comes down to `line-height` of `pre` elements... It's set to `inherit` by default but if the document doesn't set it anywhere, FF sets it (in this case) to some value which I have no idea where it got from (there's no `line-height` set anywhere in the ancestry tree AFAIK).

In the demos, `line-height` is inherited from `body` defined in `docs.css`.

[Setting it solves the issue](http://jsfiddle.net/yvt20wvq/3/).
