### ISSUE TITLE
simple.js mode is broken

### ISSUE THREAD

**Issue by carueda** [codemirror/CodeMirror#4819]
## Reproducing

Just open https://codemirror.net/demo/simplemode.html

> 
![image](https://user-images.githubusercontent.com/556505/27451571-48afedb8-5744-11e7-84d2-2cff99a3d520.png)

> 
![image](https://user-images.githubusercontent.com/556505/27451614-7879a886-5744-11e7-9f3b-1d04b6a6affd.png)

Seems arising from the recent changes https://github.com/codemirror/CodeMirror/commit/db1908a6ef80c3a712dc9a20ab914a4fc97e4276 related with "[mode/simple addon] Allow token source to be a function."

**Comment by marijnh** [comment]
Thanks for letting me know! I've released 5.27.2 with a fix.
