### ISSUE TITLE
How can I change to vim mode on an exists CodeMirror instance?

### ISSUE THREAD

**Issue by qzshadow** [codemirror/CodeMirror#4830]
The webpage developer did not initialize 'keyMap' option when they use 'fromTextArea' function to generate a CodeMirror instance. So the 'keyMap' option is 'default' now. I want to change the 'keyMap' to vim mode so I try to get the instance of CodeMirror editor by
`var editor = $('.CodeMirror')[0].CodeMirror`, it works.
Then I try to modify options of this editor by
`editor.options.keyMap = 'vim'`
but it does not work, the editor is frozen (the cursor is not blinking any more).
I am new to CodeMirror, thanks for any help!

**Comment by marijnh** [comment]
Use `setOption`. But that will only work when the vim bindings have actually been loaded which, if this is a random page that doesn't supply them as a user-facing option, they probably aren't.

**Comment by CrashLaker** [comment]
hi @marijnh,
do you happen to have an example of this?
thanks,c.
