### ISSUE TITLE
npm test failed @5.27.4

### ISSUE THREAD

**Issue by ageback** [codemirror/CodeMirror#4831]
I run building on Windows x64 7 and Windows x64 2008 R2. But both failed.

> D:\NewOA\CodeMirror>npm test
> codemirror@5.27.5 test D:\NewOA\CodeMirror
> node ./test/run.js
> { status: 404,
>   headers: { Server: 'node-static/0.6.0' },
>   message: 'Not Found' }
> npm ERR! Test failed.  See above for more details.

**Comment by marijnh** [comment]
Did you `npm install` first?

**Comment by ageback** [comment]
Yes I did. But `npm install` did not generate \lib\CodeMirror.js.

**Comment by marijnh** [comment]
Which npm version are you using?

**Comment by ageback** [comment]
node-v6.11.0-x64.msi

**Comment by marijnh** [comment]
You need at least NPM 3, since we're now using a `prepare` rather than a `prepublish` script. (Or, you know, just manually do `npm run prepare` to build)

**Comment by ageback** [comment]
Well, I upgrade to node-v8.1.3-x64.msi instead. And now `npm install` can build the target file. Also `npm test` runs OK.
