### ISSUE TITLE
indentingWithTabs should work when pressing the ] button on the mac

### ISSUE THREAD

**Issue by paladox** [codemirror/CodeMirror#4832]
Hi, when someone presses a button that should indent the lines, if they have indentWithTabs on it should work without having to keep pressing it to the tab width you provided.

Example

echo "";

if you press ] on the mac and the indentWithTabs is on it should indent that with tabs immediately and not wait for the the tab width to be reached.

**Comment by marijnh** [comment]
Are `indentUnit` and `tabSize` set to the same value?

**Comment by paladox** [comment]
Nope, dosen't look like it is. I see indentUnit set at 2 and tabSize at 8.

**Comment by marijnh** [comment]
The command bound to ctrl-] is defined to add one indentUnit of indentation. If you want that to be a tab, make sure those two options have the same value.
