### ISSUE TITLE
How to handle F5 on extraKeys and prevent browser reload

### ISSUE THREAD

**Issue by jacargentina** [codemirror/CodeMirror#4837]
I'm trying to implement a SQL query runner with CodeMirror, and i want that F5 inside the CodeMirror instance to run the query, and not refresh the browser (the default on Chrome at least, and i think Firefox too)

I'm using this:

```javascript
    this.editorOptions = {
      lineNumbers: true,
      mode: 'text/x-mssql',
      theme: 'material',
      extraKeys: {
        'F5': (args) => {
          // code to run the SQL query
        }
      }
    };
```
How must i prevent the default browser reload on the event handler?

**Comment by marijnh** [comment]
That should work (and does work for me, on Chrome).

**Comment by jacargentina** [comment]
Sorry, it works; sure was not binding the handler right.
