### ISSUE TITLE
Infinite loop in adjustPos with non-Ascii text (Related to 4786)

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4839]
1. Go to http://codemirror.net/demo/search.html
2. Enter yılbaşı somewhere in the page.
3. Cmd-F
4. Type 's' and hit Enter.

It hangs in adjustPos flipping back and forth between offsets.

**Comment by adrianheine** [comment]
Thanks for your report! I'm sorry this code still produces hangs :( I'll look into it today or beginning of next week.

**Comment by mtaran-google** [comment]
@marijnh if adrianheine doesn't fix this within the next day or so, we'd appreciate a roll-back

**Comment by vincentwoo** [comment]
What is a roll-back in this context?

**Comment by mtaran-google** [comment]
Reset the relevant code (I'd say search cursor etc.) to the state where this bug was not present.

**Comment by takamori** [comment]
Also repros with text "수 있을까" and searching for '이'.

**Comment by marijnh** [comment]
Attached patch fixes this by switching the folding-compensation-code from a bidirectional search (which got stuck constantly overshooting its goal when the match started or ended inside a composed character) from a binary one directional search.

**Comment by takamori** [comment]
hmm, this can still repro with "Le taux d'humidité à London" and searching for "a"

**Comment by marijnh** [comment]
Ah, sorry, binary search is really easy to get wrong. Attached patch should help with that (and adds a test with that input).
