### ISSUE TITLE
goLineLeft behaving incorrectly for wrapped lines

### ISSUE THREAD

**Issue by dwelle** [codemirror/CodeMirror#4840]
When `goLineLeft` executed when cursor at the end of the visual line, it tends to go to the beginning of next one.

steps to repro:

1. go to http://codemirror.net/demo/indentwrap.html (again, demonstrating on indentwrap due to lack of pure lineWrapping demo, but applies to both)
2. paste this into console and click back inside the editor within the 2s period

    ```
    setTimeout(() => { editor.setCursor({line: 4, ch: 71}); editor.execCommand("goLineLeft"); }, 2000 );
    ```

![image](https://user-images.githubusercontent.com/5153846/27907559-68dbe664-6248-11e7-8e89-0a90ecce81af.png)

Similarly (but much less aggravating.. in fact I think it's a nice behavior), if `goLineRight` is executed at the end of a visual line, it goes to the end of the next visual line.

**Comment by dwelle** [comment]
Also would add that the above behavior happens when using `textarea` inputStyle.

In `contenteditable`, the bug works in the opposite way: `goLineLeft` works well, but with `goLineRight`  the cursor always (irrespective to it's initial position on that line) ends up on the beginning of __next__ line.

For the `contenteditable` behavior, I used CM `5.26.0`. For the original bug, `5.27.x` (or whatever is on the demo page).

**Comment by dwelle** [comment]
The initial bug seems to be caused by `charCoords()` reporting wrong `top` position - returns next (visual) line, when the cursor is at the end of previous line.

Using `cursorCoords()` instead seems to work fine, tho I didn't look into why.

```
// amended `goLineLeft`
cm.extendSelectionsBy(() => {
    const top = cm.cursorCoords( false, "div" ).top + 5;
    return cm.coordsChar({ left: 0, top }, "div")
});
```

**Comment by marijnh** [comment]
The output of `charCoords` for wrapped characters is pretty much undefined, since browsers do wildly different weird things for those. This is why we have `cursorCoords`, which gives you the coordinates of an actual cursor position, which is easier to define.

Attached patch makes `goLineRight` stable (i.e. it stops advancing when the cursor is already at the end of the line). Does that solve the problem for you?

**Comment by dwelle** [comment]
Yep, I patched it the same way in my fork.

**Comment by dwelle** [comment]
WTBS, `goLineLeftSmart` should use the same.
