### ISSUE TITLE
New highlighter provided for Pro/5 Business Basic

### ISSUE THREAD

**Issue by severach** [codemirror/CodeMirror#4843]
[Codemirror_highlighter_BusinessBasicPro5.zip](https://github.com/codemirror/CodeMirror/files/1136802/Codemirror_highlighter_BusinessBasicPro5.zip)

**Comment by marijnh** [comment]
We're not accepting new modes into the main distribution anymore. The recommended way to distribute extra modes is as separate NPM packages, see for example the [elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir).
