### ISSUE TITLE
TernServer.jumpToDef() not working when providing option getFile()

### ISSUE THREAD

**Issue by nickasd** [codemirror/CodeMirror#4844]
Thanks a lot for this amazing editor and all the available plugins.
My scenario: I have a sidebar containing a set of files and a single CodeMirror instance which shows the currently selected file. I've been experimenting with Tern recently and wanted to let the Tern server know about all these files, so that when using the Alt-. shortcut on a variable CodeMirror would show the file containing the definition.
The shortcut works fine unless I provide the `getFile` option to the `CodeMirror.TernServer`. I think the problem might be that not all documents have been added to CodeMirror. The problem can be reproduced by replacing line 113 in `demo/tern.html` with the following lines:
```
server = new CodeMirror.TernServer({defs: [JSON.parse(code)],
    getFile: (name, callback) => { console.log(name); callback(null, 'var asd = 1;'); },
    switchToDoc: (name, doc) => { console.log('This never gets printed'); }
});
server.server.addFile('asd.js');
```
In the demo window, write `console.log(asd);` somewhere in the textarea, put the cursor on the `asd` variable, press Alt-. and the error message `Could not find a definition` appears.
The Ctrl-I and Ctrl-O shortcuts work fine.
I would expect the `switchToDoc()` function to be called but this does not happen. Is this a bug or am I doing something wrong?

**Comment by marijnh** [comment]
Since it works in the demo, I expect you're doing something wrong, or at least unanticipated, but it's been ages since I worked with this code, so I'm not sure what.

**Comment by nickasd** [comment]
I think you misunderstood, the demo doesn't work when adding the above lines. Other commands work, but not the "go to definition" one.

**Comment by marijnh** [comment]
The demo in the CodeMirror website? That one doesn't support multiple-file projects, i.e. it will never add a second file, so neither `getFile` not `switchToDoc` are of any use. Adding those lines does not break jumping to definition for me. It doesn't make jumping to `asd` work, since the server never loads a file which defines `asd`, but that's correct.

**Comment by nickasd** [comment]
Actually that's what I thought would make it work: `server.server.addFile('asd.js');`. I thought that adding a file this way would cause the `switchToDoc` function to be called. Am I misunderstanding the role of that function?

**Comment by marijnh** [comment]
Try `server.addDoc('asd.js', new CodeMirror.Doc('var asd = 1;'));` (and remove the `getFile` option).

**Comment by nickasd** [comment]
Yes, that would work, but I was looking for a way to add documents without having to add them to CodeMirror first, since there could be a lot of them. Would it be a performance issue? Does creating a new document involves some significant parsing even before displaying it?

**Comment by marijnh** [comment]
I don't expect it'd be a performance issue -- the data structure CodeMirror creates for a document isn't huge, and unless you have many megabytes of code, you shouldn't worry about this.

**Comment by nickasd** [comment]
Potentially there could be hundreds of documents and only a couple of them could ever be opened, that's why I was looking for a more efficient way. If not for a scenario like this, I don't really get what the `getFile` option could be useful for, since one could simply add all the documents at the beginning. In my opinion, `switchToDoc` would be the perfect place to create the new CodeMirror document if it didn't exist yet.

**Comment by PradeepPsudo** [comment]
Hi, 

I am working with object oriented JavaScript.

Is it possible to pass Object to server.addDoc(fileName,fileContent) function instead of String in the place of fileContent parameter.

Kindly help me with this.
