### ISSUE TITLE
Initial cursor postion is appearing between lines, before any key press.

### ISSUE THREAD

**Issue by RajakumarSidhan** [codemirror/CodeMirror#4847]
![image](https://user-images.githubusercontent.com/22787486/28104731-25d2aad6-66fa-11e7-9699-9edc963df43a.png)

on text selection, the text is not selected properly
![image](https://user-images.githubusercontent.com/22787486/28104355-4393eec4-66f8-11e7-8d50-92bc585f976a.png)
on any key press, the cursor position is changed to correct location.
![image](https://user-images.githubusercontent.com/22787486/28104507-fe64469a-66f8-11e7-9374-adbedecad067.png)
This issue is actually happening in an angular 2 application, I have used ng2-codemirror package along with the code mirror package

Note: when there is a huge number of lines it is showing incorrect cursor position on down/ up arrow key press.
I tried with chrome and mozilla firefox , in both browsers I see this issue.

**Comment by marijnh** [comment]
Most likely you have custom fonts loading after the editor has already initialized, causing its layout to change after it's computed the cursor position. The solution is to call `.refresh()` on the editor instance after everything has finished loading, or to delay initialization of the editor until that point.
