### ISSUE TITLE
Ctrl-Shift-Up/Down hotkey for adding cursor

### ISSUE THREAD

**Issue by nickasd** [codemirror/CodeMirror#4850]
I noticed there is no hotkey yet for adding a cursor one line up or down like in Sublime. Here is a quick implementation that can be added to the `extraKeys` option:
```
'Shift-Alt-Down': (codeMirror) => {
    var selections = cm.listSelections();
    var lastSelection = selections[selections.length - 1];
    cm.setSelection(lastSelection.anchor, lastSelection.head);
    cm.execCommand('goLineDown');
    var newSelection = cm.listSelections()[0];
    cm.setSelections(selections);
    cm.addSelection(newSelection.anchor, newSelection.head);
}
```
It would be nice if something like this could be added to the Sublime keymap. There may be a better way to do it, but I couldn't find a method to get the position immediately above the cursor, so that's why I used the `goLineDown` command.

**Comment by dwelle** [comment]
You can simply do `cm.getCursor().line - 1`. I have a pretty solid (IMO) implementation of this and can issue a PR if there's interest.

(can't post a link to a fork, coz I have it implemented as a part of a wrapper lib for cm editor, so would require a bit more work to separate it into a standalone feature and put into a fork for PR).

**Comment by nickasd** [comment]
That's what I thought at first, but what if you have wrapped lines? I don't use Sublime myself so I don't know what the default behavior is (whether to add the cursor to the next line or to the position immediately below which might be on the same wrapped line). Anyone knows this?

**Comment by dwelle** [comment]
Right on.. I personally don't like the behavior of putting next cursor on a wrapped line, so I didn't bother with that case. WTBS if that's a standard behavior, we should probably stick with that (or let user choose).

For that purpose, I'd do what cm does and use `findPosV`

**Comment by nickasd** [comment]
Right, didn't see that method. Now it's as easy as
```
cm.addSelection(cm.findPosV(cm.getCursor(), 1, 'line'));
```
Although for the case where you want to add the cursor to the next logical line (i.e. ignore wrapped lines), this doesn't work, since `cm.findPosV()` returns the visual vertical position. Maybe an optional `visually` parameter could be added as in `cm.findPosH()`?

**Comment by marijnh** [comment]
A pull request that adds these bindings to `keymap/sublime.js` would be great. I'd prefer to just do what Sublime Text does, without additional configuration.

**Comment by dwelle** [comment]
also would ensure it accounts for when text is selected and tries to select same amount of columns (ST doesn't do that, but it seems to be fairly standard--and useful--behavior nowdays)

**Comment by nickasd** [comment]
So apparently after downloading the trial version of Sublime I found that it has the Ctrl-Shift-Up/Down hotkey (and not Shift-Alt-Up/Down as I first thought). Since Sublime has no wrapping lines, there should be a way to have `cm.findPosV()` find the logical next line and not the visual (possibly wrapped) one. Can this be done (like I suggested above)?

**Comment by dwelle** [comment]
>  I found that it has the Ctrl-Shift-Up/Down hotkey 

Actually, it uses `ctrl+alt+down/up` (which is standard -- ace, atom do the same)

> Since Sublime has no wrapping lines, there should be a way to have cm.findPosV() find the logical next line and not the visual (possibly wrapped) one. 

It has line wrapping (and if not by default, it can be easily set). But common behavior _is_ for the cursor to extend to the _visual_ (wrapped) line first, so you do want to use the `cm.findPosV`

**Comment by nickasd** [comment]
> Actually, it uses ctrl+alt+down/up (which is standard -- ace, atom do the same)

In Sublime 3 on the Mac the command is called "Add previous/next line" and it uses `Ctrl-Shift-Up/Down`. Which system are you using?

> But common behavior is for the cursor to extend to the visual (wrapped) line first, so you do want to use the `cm.findPosV`

Ok, now I can confirm this. Although this is not standard behavior for all IDEs (see Brackets for example), Sublime adds the cursor to the next visual line.

**Comment by marijnh** [comment]
If Brackets (which is CodeMirror) already supports this, a good start might be to look at their implementation.

**Comment by nickasd** [comment]
Brackets has the `Alt-Shift-Up/Down` shortcut instead. I also noticed the somehow unintuitive behavior that if the cursor is on the first visual line of a wrapped line, after adding a cursor to the line below (the next logical line), moving the cursors down with the keyboard will keep the same distance even if the following lines are not wrapped.
Just to be sure: we still want the Sublime behavior (since it's the Sublime key map)?

**Comment by marijnh** [comment]
Yeah, the sublime keymap should definitely implement what sublime does.

**Comment by jishi9** [comment]
Actually Sublime text has different shortcuts for different OS'es.

The following documentation pages:
https://www.sublimetext.com/docs/2/multiple_selection_with_the_keyboard.html
https://www.sublimetext.com/docs/3/multiple_selection_with_the_keyboard.html
claim that the shortcuts are:
```
Windows/Linux: Ctrl+Alt+⬆ and Ctrl+Alt+⬇
Mac: ⌃+⇧+⬆ and ⌃+⇧+⬇
```

But this is actually incorrect for linux. If you download a copy of sublime from https://www.sublimetext.com/3  (e.g. 64 bit tarball for linux), and unzip the file ./Packages/Default.sublime-package , you will find the following default shortcuts:
```
./Default (Linux).sublime-keymap:	{ "keys": ["alt+shift+up"], "command": "select_lines", "args": {"forward": false} },
./Default (Linux).sublime-keymap:	{ "keys": ["alt+shift+down"], "command": "select_lines", "args": {"forward": true} },
./Default (Windows).sublime-keymap:	{ "keys": ["ctrl+alt+up"], "command": "select_lines", "args": {"forward": false} },
./Default (Windows).sublime-keymap:	{ "keys": ["ctrl+alt+down"], "command": "select_lines", "args": {"forward": true} },
./Default (OSX).sublime-keymap:	{ "keys": ["ctrl+shift+up"], "command": "select_lines", "args": {"forward": false} },
./Default (OSX).sublime-keymap:	{ "keys": ["ctrl+shift+down"], "command": "select_lines", "args": {"forward": true} },
```
