### ISSUE TITLE
SUGGESTION: (MarkDown mode) Colorize Math LaTeX expressions

### ISSUE THREAD

**Issue by jlchereau** [codemirror/CodeMirror#4857]
Use delimiters:
- `$...$` or `\(...\)` for inline = vertically minimized to stand within multiline text and not break line heights
- `$$...$$` or `\[...\]` for display = vertically expanded for better layout displayed on its own line without text

See:

- http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters
- https://github.com/Khan/KaTeX/issues/712

**Comment by marijnh** [comment]
LaTeX is not part of Markdown, so this doesn't really belong in the Markdown mode. You can set something up with a multiplexing mode, see [this comment](https://github.com/codemirror/CodeMirror/issues/2942#issuecomment-64483899) for an example.
