### ISSUE TITLE
SUGGESTION: (MarkDown mode) Colorize Emoji Names (or better display a emoji)

### ISSUE THREAD

**Issue by jlchereau** [codemirror/CodeMirror#4858]
Emojis names are displayed within colons as in `:...:`.
`:smile:` actually gives :smile:

**Comment by dwelle** [comment]
Sounds like a good idea. Should not be part of plain markdown, but gfm [specifies](https://guides.github.com/features/mastering-markdown/) emojis so I'd put it there.

I can look at it next week.

/cc @marijnh

**Comment by dwelle** [comment]
The basic functionality has been implemented, so can be closed - I don't think the replace-emoji-markup-with-actual-emoji is applicable for markdown mode, at this time.

**Comment by javisperez** [comment]
Hey @dwelle ! 👋Thanks for this update, I'm trying to implement the `replace-emoji-markup-with-actual-emoji` part, do you have any help on how to replace the text on the mode itself? my idea so far is to read all lines on the content, match everything between `:` (e.g. `:thinking_face:`) and replace it with the proper unicode character, but that sounds slow.

Is there anyway to replace the text when the token is matched? like, token by token?

**Comment by dwelle** [comment]
I don't think syntax mode is made for replacing text. If you register a `change` handler and scan only what's been written (current line), or pasted (block of lines), then perf shouldn't be an issue.

**Comment by javisperez** [comment]
Thanks @dwelle yeah, i imagined the mode limitations but I didn't know you could actually scan only what's been written from the `change` event, will dig a bit more into that as my first idea was to use `regexp` to match emoji "names" and replace the whole content, which sounds like not ideal for me. 

Thank you for the tip, any other tip is more than welcome :)

Have a great day!
