### ISSUE TITLE
There is no Codemirror event/add-on which signals to event handler after picking completion in autocomplete.

### ISSUE THREAD

**Issue by anjaliwalke11** [codemirror/CodeMirror#4859]
**Description**:
There is no event or add-on which Codemirror signals to the event handler function, which could execute a set of code, after picking of a completion is done in Codemirror autocomplete.
So, just need Codemirror to signal an event for handler after completion is picked.

**Steps to reproduce:**
1. Type a character and press ctrl-space to open autocomplete
2. Select an option from the autocomplete 
3. In the file show-hint.js, using the debugger breakpoints, you can see that the breakpoint first goes on pick function under Widget.prototype which calls for pick function under Completion.prototype, in which the steps to pick a completion are carried out. After its done, the breakpoint goes back to the pick function under Widget.prototype, in which there is no event which is being signal by Codemirror for handler to carry out any function after completion is picked.

**Fix**:
In the file show-hint.js, just need to add **CodeMirror.signal(this.completion.cm, "pickCompletion", this.cm);** in the **pick** function under **Widget.prototype**. 
This would signal an event "pickCompletion" to the handler to execute what needs to be done after a completion is picked.

Codemirror version: 5.24.2

**Comment by marijnh** [comment]
There's an `endCompletion` event that fires when the completion widget closes. Since you don't know anything about the completion that happened, I don't think having an additional `pickCompletion` would help.

**Comment by anjaliwalke11** [comment]
@marijnh : Thank you so much Marijn!! It is working for me. +1. 
Hence closing this issue. 
Thanks.
