### ISSUE TITLE
HTML code in markdown editor is excuting automatically

### ISSUE THREAD

**Issue by dev-drprasad** [codemirror/CodeMirror#4863]
I am really happy with CodeMirror, i wanted to integrate to my personal blog. I integrated CodeMirror in Django admin in Markdown mode. Everything is perfectly working. There is small issue when i paste the code in markdown editor. I searched all over internet but I am unable to see any issue like that before.

The code I am pasting is:
```
class MarkdownEditor(forms.Widget):
    """
    Code Editor built upon Javascript editor:CodeMirror
    """
    class Media:
        css = {
            'all': (
                'codemirror/codemirror.css',
                'codemirror/mdn-like.css',
            )
        }

        js = ('codemirror/codemirror.js', 'codemirror/mode/markdown/markdown.js')

    def render(self, name, value, attrs=None, renderer=None):

        template = '''
            <textarea name="%(name)s" id="id_%(name)s" required="" class="vLargeTextField">%(value)s</textarea>
            <style>
                .CodeMirror {
                    height: auto;
                }
                .CodeMirror-scroll {
                    min-height: 300px;
                }
            </style>
            <script>
                var editorElem = document.querySelector("#id_%(name)s");
                var editor = CodeMirror.fromTextArea(editorElem, {
                    lineWrapping: true,
                    theme: 'mdn-like',
                    lineNumbers: true,
                });
            </script>
        '''
        return mark_safe(template % {'name': name, 'value': value or ''})
```

Whenever i paste the code, it is showing properly in editor, after save It is misbehaving. editor showing upto line `<textarea name="%(name)s" ...........` after that nothing is showing. I have seen in browser console that next block to that line <style>, <script> tags are excuting automatically. Thatswhy there are not showing in editor. I can't share live preview. but here i am sharing saved html page of that error.
[codemirror_issue.tar.gz](http://reddyprasad.me/files/codemirror_issue.tar.gz)

I am using ubuntu 16.04 and chrome browser v59.0

**Comment by marijnh** [comment]
This has nothing to do with CodeMirror -- you're not escaping the code when you put it into your HTML, which will cause `</textarea>` to close the textarea it's supposed to be part of.

**Comment by dev-drprasad** [comment]
Sorry my mistake :disappointed: . Thanks for pointing it out.
