### ISSUE TITLE
Multiplex Parser not ignoring quoted strings

### ISSUE THREAD

**Issue by b32** [codemirror/CodeMirror#4867]
While using the multiplexer function (v5.26.0), we noticed that strings that were quoted were not being escaped.  This led to non-matching closing tags and incorrect mismatch errors.  This also seems to occur when in text/html mode. 

example: text/html mode
```
<script type="text/javascript">
	var s = "</script>";
</script>
```
<img width="279" alt="screen shot 2017-07-21 at 12 12 26 pm" src="https://user-images.githubusercontent.com/6474248/28472265-e89bc196-6e0d-11e7-8cf2-ddece195b9f3.png">

**Comment by marijnh** [comment]
Have you tried running that script in a browser? The browser will also end the `<script>` tag at the first `</script>` it sees, regardless of whether that's in a string or comment or whatever, so at least in the case of script tags, the behavior you are reporting is the correct behavior.

**Comment by b32** [comment]
Perhaps I used a bad example and I should have included the exact snippet we are having issues with, as it is part of a multiplexor mode that we wrote.  In our template language, we use {{ for opening tags  and  }} for closing tags.  Within these tags we allow the closing tag as long as it is part of a string.  Would it be possible for us to ignore quoted or nested closing tags?

Our snippet:

<div id=“price-usd”>{{ out(‘{{=price_usd}}’)</div>

**Comment by marijnh** [comment]
> Would it be possible for us to ignore quoted or nested closing tags?

Not with the the multiplex helper -- that one will eagerly look for the closing match you gave it, and stop using the inner mode as soon as it finds it. You'd have to write the wrapping mode yourself to do something like this.
