### ISSUE TITLE
Stream.lookAhead() doesn't work in mode tests

### ISSUE THREAD

**Issue by dwelle** [codemirror/CodeMirror#4868]
When running tests, calling `stream.lookAhead( n )` always returns `undefined` because apparently the `lineOracle` isn't defined for given `StringStream` (i.e. the `mode_test.js` [doesn't pass `context` when creating StringStream](https://github.com/codemirror/CodeMirror/blob/3dd914dc98ddff0dc149ae4e6a3f26709cd71a47/test/mode_test.js#L131))..

~~WTBS, the `stream.lookAhead` is [tested itself](https://github.com/codemirror/CodeMirror/blob/master/test/test.js#L2478) so no idea what's going on here.~~ never mind -- that's not a mode test a seems to be using default behavior

**Comment by marijnh** [comment]
Attached patch should address this.
