### ISSUE TITLE
Thank you Thank You Thank You

### ISSUE THREAD

**Issue by EverNewJoy** [codemirror/CodeMirror#4871]
Dear Marijn and other CM contributors,

I just wanted to write this to thank you oh so much for making Code Mirror available, it is an incredible gift to the world!

Thank you!

♥

Rama

**Comment by marijnh** [comment]
You're very welcome!

(Consider using the [forum](https://discuss.codemirror.net/), not the issue tracker, for this kind of communication, though.)

**Comment by EverNewJoy** [comment]
Forum:
https://discuss.codemirror.net/t/thank-you-for-code-mirror/1319

♥

Rama
