### ISSUE TITLE
No lib/codemirror.js in latest release?

### ISSUE THREAD

**Issue by Niharika29** [codemirror/CodeMirror#4875]
Hi, I'm using 5.28.0 and there's no lib/codemirror.js in that release. That file still seems to be referenced from a few other files and the docs. What am I missing?

**Comment by leeoniya** [comment]
https://github.com/codemirror/CodeMirror/issues/4512

**Comment by Niharika29** [comment]
Oh, thanks for that. I'll npm build it then.
