### ISSUE TITLE
Visual cursor movement broken with RTL text with LTR text in it

### ISSUE THREAD

**Issue by Niharika29** [codemirror/CodeMirror#4878]
I'm going off of the latest release. I've reproduced this issue with the demo on the website. Steps to reproduce:
1. On https://codemirror.net/demo/bidi.html, add a URL (English) somewhere between two chunks of Hebrew text.
2. Make sure "Use visual order for arrow key movement" is checked.
3. Start with the line below the one with the URL and move your cursor left. It skips the URL and moves to the end of the line when it comes to that line and unexpectedly jumps a few other spots. 
4. Try selecting text. Similar problems.

I am also explicitly setting "rtlMoveVisually: true" in my initialization config. It didn't help. 
I think the ideal solution would be to add a config option to let the browser handle cursor movements. I am aware it's not consistent but at least it wouldn't be inconsistent compared to other websites.

**Comment by Niharika29** [comment]
I noticed there is a ~3 years old 'direction' branch of code. Do you think it'll work better? I can try to rebase, if so.

**Comment by adrianheine** [comment]
Thanks for your report! I can confirm that the position after moving left until the cursor jumps a line is wrong in your example. I'll have a look. The `direction` branch is mostly obsolete and un-rebaseable.

**Comment by Niharika29** [comment]
That'd be great, @adrianheine. Thank you.

**Comment by marijnh** [comment]
This seems to only occur (or at least be much easier to reproduce) when the editor's direction is set to RTL. @adrianheine Do you still have plans to look at it?

**Comment by firasdib** [comment]
I think this issue is back.
