### ISSUE TITLE
wrap on column size

### ISSUE THREAD

**Issue by nlight-jdev** [codemirror/CodeMirror#4885]
Similar to the native textarea, is it possible to setup CodeMirror to wrap(lineWrapping:true) after an exact number of characters?
Can this work in all browsers?
Is there any clean way to achieve this and work well with UTF-8 charsets and variable width fonts?

**Already tried:**
1. setSize to "columns * editor.defaultCharWidth()" but this wraps at wrong positions

2. use the same calculation as the rulers.js addon to calculate width, then use this for setSize().
Result: editable area is smaller than desired number of chars. Also, without setting any size, the ruler's limit is exceeded when using Chinese characters

3. write my own wrapping algorithm and apply it at onChange event
Result: it works well to do soft and hard wrapping but having used CodeMirror#replaceRange(...) to do wrap the lines, pollutes the undo buffer and undoing would actually try to unwrap the lines, creating inconsistencies.

**Comment by dwelle** [comment]
Are you talking about [hard wrapping](http://codemirror.net/demo/hardwrap.html)?

**Comment by nlight-jdev** [comment]
yes, even in your link's demo, undo will incorrectly unwrap the line(and join with previous line). 
Then the wrap timer kicks in and it's rewrapped to next line.

**Comment by marijnh** [comment]
> Similar to the native textarea, is it possible to setup CodeMirror to wrap(lineWrapping:true) after an exact number of characters?

No. You can measure monospace characters and set the width to a multiple, but line wrapping is done by the browser, so variable-width characters won't wrap on character count.
