### ISSUE TITLE
TypeScript: Syntax highlighting broken when initializing member outside constructor.

### ISSUE THREAD

**Issue by alur** [codemirror/CodeMirror#4887]
```
export class SomeClass {
  private map = new Map<string, number>();

  async someFunc(f: boolean): Promise<boolean> {
    return `abcd ${f}`;
    return Promise.resolve(f);
  }
}
```

**Comment by marijnh** [comment]
The problem appears to be the `new X<y>` syntax, which is parsed as `(new X) < y`. I haven't been able to find an actual specification of TypeScript's syntax, so it remains guesswork what is actually allowed. Do you have any link to docs describing the syntax you are using here (angle brackets after `new`)?

**Comment by alur** [comment]
The latest TypeScript spec is a little outdated, but it does include type parameters for new.
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.8.9

**Comment by marijnh** [comment]
That's about type expressions, but I guess https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.14 does describe this. It's interesting that they just went ahead and broke existing syntax (`new Date < something` does happen in real code, for example), but I guess this can be handled. See attached patch.
