### ISSUE TITLE
setBookmark with widget causes errors on mobile

### ISSUE THREAD

**Issue by ashmind** [codemirror/CodeMirror#4889]
**Browser:** Chrome 59.0 (Android)
**CodeMirror:** 5.28.0

**Steps to reproduce:**
1. Go to http://jsbin.com/cisajutaxu/edit?html,output on Android
2. Try to delete number '2' on the second line (or anything else on that line)
3. There is an error in the browser console (can be seen by attaching desktop Chrome)

**Error:**
```
Uncaught TypeError: Cannot read property 'line' of undefined
    at getBetween (VM43 codemirror.js:413)
    at walk (VM43 codemirror.js:8904)
    at walk (VM43 codemirror.js:8911)
    at walk (VM43 codemirror.js:8911)
    at domTextBetween (VM43 codemirror.js:8918)
    at ContentEditableInput.pollContent (VM43 codemirror.js:8761)
    at ContentEditableInput.updateFromDOM (VM43 codemirror.js:8830)
    at VM43 codemirror.js:8823
```

**Some investigation:**
I'm pretty sure it fails because https://github.com/codemirror/CodeMirror/blob/33068f96d148a129d6c12ff647a2fbb3cdb60006/src/input/ContentEditableInput.js#L424 does not expect a bookmark `TextMarker` -- where `find` just returns one `Pos` instead of `{ from, to }`.

**Comment by marijnh** [comment]
Does attached patch help?

**Comment by ashmind** [comment]
@marijnh Yes -- seems to fix it, thanks.

**Comment by marijnh** [comment]
Great!
