### ISSUE TITLE
wrap and scrollbars

### ISSUE THREAD

**Issue by nlight-jdev** [codemirror/CodeMirror#4890]
Currently CodeMirror rewraps the text at different location(shorter) when vertical scrollbar appears.

Is there any way to prevent this? Like pre-allocating some gap on the right side to accomodate for when scrollbar would appear?

**Comment by marijnh** [comment]
This isn't currently supported, but it would be possible to write a variant of the the default (native) scrollbar style that always reserves a gap for the vertical scrollbar. I don't think this is a common enough requirement to include it in the core library, though.

**Comment by nlight-jdev** [comment]
Or is there any quick workaround for reserving that space? via some css or similar?

**Comment by marijnh** [comment]
You could try creating a new subclass of `CodeMirror.scrollbarModel.native`, and overriding its `update` method to always return at least the width of the native scrollbar in the `right` property of the object it returns. To get that width you could read `cm.display.nativeBarWidth` (but that's not guaranteed to stay).

**Comment by nlight-jdev** [comment]
Thanks a lot!
And regarding the update, can this be implemented in a plugin instead?
