### ISSUE TITLE
adjust width to fit n chars

### ISSUE THREAD

**Issue by nlight-jdev** [codemirror/CodeMirror#4891]
Is it possible to call setSize(...) with a width that accomodates for a fixed number of characters?

I've tried with this but the DOM contains several other elements with paddings, etc. and breaks calculation:
```
var gutterWidth = cm.getGutterElement().clientWidth;
var charWidth = cm.defaultCharWidth();
var left = cm.charCoords(CodeMirror.Pos(cm.firstLine(), 0), "div").left;
var width=Math.round(gutterWidth + left + cols * charWidth)
```

Thank you!

**Comment by marijnh** [comment]
This doesn't exists as a feature of the library -- you'll have to compute the width you want by taking padding into account (which you can control using CSS)
