### ISSUE TITLE
Comment brakes @font-face rule syntax highlighting

### ISSUE THREAD

**Issue by bytechess** [codemirror/CodeMirror#4892]
**Description**

When adding a comment and the end of the "@font-face" rule the src property highlights red. The src property works correctly when page is ran, but the syntax is wrong. 

This was found on "Brackets: Release 1.10 build 1.10.0-17483"

**Steps to Reproduce**

1. Create a @font-face rule
2. Add a src property
3. Add a comment after "@font-face"

**Versions**

OS: Windows 7 Professional
![28914390-5f7f5a28-7833-11e7-8ea1-246dd56416c6](https://user-images.githubusercontent.com/22214983/28927415-5ea34144-7862-11e7-931c-6f3ecd4ef35c.png)
![28914391-5f87cf32-7833-11e7-8b38-fa485f951d0b](https://user-images.githubusercontent.com/22214983/28927414-5ea2686e-7862-11e7-830e-b9af6dedc67b.png)

**Comment by marijnh** [comment]
Attached patch should solve this.
