### ISSUE TITLE
Cannot edit ui-codemirror in a taskpane of an add-in in Excel for Windows

### ISSUE THREAD

**Issue by SoftTimur** [codemirror/CodeMirror#4896]
I just realise that we cannot modify texts in code-mirror in a taskpane of an add-in in Excel for Windows. 

I have an Excel add-in built by `mean-stack` and `angular-ui-router`. In a page, I have

    <textarea ng-model='testCM1' ui-codemirror='option'></textarea>
    <ui-codemirror ng-model='testCM2' ui-codemirror-opts='option'></ui-codemirror>
    <div ng-model='testCM3' ui-codemirror='option'></div>
    <textarea ng-model='testTextarea'></textarea>
    
The 4 textareas can well be edited in Chrome, IE, Excel Online, Excel for Mac. However, all the 3 textareas by `ui-codemirror` can not be edited in Excel for Windows, whereas the last textarea is modifiable.

Is anyone aware of this odd behavior? How could we fix this? Is there any workaround?

PS: here is a [JSBin](https://jsbin.com/raqixujozo/1/edit?html,output) for testing, we could link this file to a manifest and try it in Excel for Windows.

**Comment by marijnh** [comment]
I don't have any suggestions (not sure anyone has tried to run the editor in Excel yet), and I'm sorry, but Excel is just not a supported platform, so you're on your own here.
