### ISSUE TITLE
Changing editor default direction in RTL HTML document does not work

### ISSUE THREAD

**Issue by wajnberg** [codemirror/CodeMirror#4897]
In the bidi.html demo file, Change the HTML direction to RTL (<html dir="rtl">)

Then try to change the default directio of the editor.
The direction remains RTL

**Comment by tomerm** [comment]
@BAMIR. FYI.

**Comment by tomerm** [comment]
@amirbrans FYI.

**Comment by tomerm** [comment]
@wajnberg thanks for fixing. Based on the comments in PR it looks like the fix for this issue will be available with CodeMirror 5.29.0 (expected to be released in Aug 2017).
