### ISSUE TITLE
YAML Front-Matter Does Not Recognize `...`

### ISSUE THREAD

**Issue by tovic** [codemirror/CodeMirror#4901]
How to make YAML front-matter supports this block style:

![capture](https://user-images.githubusercontent.com/1669261/29062759-27f10f84-7c4d-11e7-84c3-6c024ebd69e0.png)

I have tried this [here](https://github.com/codemirror/CodeMirror/blob/8b9066a7f9f64474b3f6035de9f6af74c18e96b6/mode/yaml-frontmatter/yaml-frontmatter.js#L48) but still did not work:

~~~ .js
var end = stream.sol() && stream.match(/[.-]{3}/)
~~~

**Comment by marijnh** [comment]
I suppose you'd also have to update the other dashes at line 39. In any case, this isn't a bug, so the issue tracker is not the place for it.

**Comment by tovic** [comment]
So the problem was on the overlay mode. Sorry 😭

![](https://user-images.githubusercontent.com/1669261/29066065-5f6ad21e-7c58-11e7-8f6c-03f964b0185b.PNG)
