### ISSUE TITLE
bash mode doesn't understand that single-quoted strings can be multiline

### ISSUE THREAD

**Issue by srawlins** [codemirror/CodeMirror#4902]
1. http://codemirror.net/mode/shell/
2. paste:

   ```bash
   echo 'hello
   there' > file.txt
   ```

Expected: everything inside the single quotes is colored like a string (red I guess)

Actual: CodeMirror "exits" the string at the newline character, beginning the next line as a new statement, highlighting `there` as a command, and `' > file.txt` as a second string.

**Comment by tcederquist** [comment]
I think better form might be to have a \ to trail the line indicating line continuation. It works either way in modern shells but using this \ form is more syntax correct I think - and the the shell mode works as expected in codemirror.

     echo 'hello \
     there' > file.txt

**Comment by srawlins** [comment]
> It works either way in modern shells but using this \ form is more syntax correct I think

@tcederquist This is wrong.

```bash
$ echo 'hello \
> there'
hello \
there
$ echo 'hello
> there'
hello
there
```

The two forms produce different results, and both are valid bash.

@marijnh Re-open?

**Comment by srawlins** [comment]
@marijnh Oh, lol, you fixed. Thank you!
