### ISSUE TITLE
Settable dialog insert position

### ISSUE THREAD

**Issue by fabiospampinato** [codemirror/CodeMirror#4905]
I want to open dialogs on top of the editor and move the code below it down a bit, how am I supposed to do that cleanly?

The way I'm currently doing it is by overriding `addon/dialog/dialog.js` just for making this change:
```diff
- dialog = wrap.appendChild(document.createElement("div"));
+ dialog = wrap.insertBefore(document.createElement("div"), wrap.firstChild);
```
but this is very hacky and not future proof, shouldn't there be a better way of doing it?

Perhaps defining `dialogDiv` in a way that makes it overridable?
Perhaps supporting a custom function via a new option?

**Comment by marijnh** [comment]
See [this addon](http://cm/doc/manual.html#addon_panel)

**Comment by fabiospampinato** [comment]
Looks good, but I'm also using the search addon, which uses dialogs, not panels. I still need to edit it if I always want to use a panel. 

I wish there was an easier way of doing this.

**Comment by marijnh** [comment]
Ah, right, that's not currently supported, and the way you kludged it in doesn't really work well (the editor will get confused about its size -- it might show empty space when the dialog is removed again, for example). I suspect that for short-lived dialogs like search having the content shift is rather annoying, so I don't consider this a big priority.

**Comment by fabiospampinato** [comment]
I actually haven't found any issue of that sort with my setup, I'm positioning the dialog with `position: fixed` and moving `.CodeMirror-scroll` down a bit with CSS, this is feasible only because the dialogs I'm using always have the same height.

You're right, shifting the content down might look like an annoyance, but what if a match for something I'm searching is in that first line currently hidden below the dialog? IMHO that would be more annoying.
