### ISSUE TITLE
Code coloring issue in JavaScript mode 

### ISSUE THREAD

**Issue by swmitra** [codemirror/CodeMirror#4906]
In JavaScript mode, code coloring looks flat because of same token selector `.cm-variable-2` allocation to call expression and variables. Please consider the following screenshot - 
![image](https://user-images.githubusercontent.com/12087205/29210633-08acb9f4-7eb2-11e7-9c0f-ebffe4f7cc6c.png)
If the token allocation is different for variables and call expressions, it might look better IMO. Consider this screenshot for example - 
![image](https://user-images.githubusercontent.com/12087205/29210773-cf0fb2ae-7eb2-11e7-9209-5f3facc4c160.png)
Is it possible to have a fix for this in CodeMirror instead of writing a custom overlay parser?

**Comment by marijnh** [comment]
You could use the JavaScript mode from the [google mode bundle](https://github.com/codemirror/google-modes) instead, which does this. Since variable and calls have the same syntactic and semantic structure in JavaScript, I'm not really interested in adding this distinction to the built-in JS mode.
