### ISSUE TITLE
[JSX] JavaScript string interpolation breaks on HTML string

### ISSUE THREAD

**Issue by pouwerkerk** [codemirror/CodeMirror#4908]
Interpolated strings containing HTML seem to confuse JSX mode if an HTML tag comes immediately after the interpolated section. For example, the string ``var str = `<div>${anExpression}</div>`` ` is parsed incorrectly. 

Consider the following example:

```jsx
var React = require("react");
var ReactDOMServer = require("react-dom/server");

var innerHTML = `<pre>${JSON.stringify({ a: 123 })}</pre>`;
var myDivElement = <div 
                     className="foo" 
                     dangerouslySetInnerHTML={{ __html: innerHTML }} 
                   />;

ReactDOMServer.renderToStaticMarkup(myDivElement);
```

CodeMirror 5.28.1 on Chrome 60.0.3112.90 renders this with a syntax error on line 4: 

![screen shot 2017-08-12 at 2 41 21 pm](https://user-images.githubusercontent.com/101547/29244511-93fa2d72-7f6e-11e7-9fe7-da8cd9c67ffc.png)

The `</pre>` in ``var innerHTML = `<pre>${JSON.stringify({ a: 123 })}</pre>` `` should be parsed as a normal `string-2`, but because of [this line](https://github.com/codemirror/CodeMirror/blob/2add03c7efbbb1c685e7da0c4c3733778c6f35d9/mode/jsx/jsx.js#L106), CodeMirror switches from JavaScript to XML Mode and interprets the string as a dangling closing tag (and thus, a syntax error).

I've gone ahead and found [a way](https://github.com/pouwerkerk/CodeMirror/commit/63670540cd7150f6c1b243b78c0eeb7f36a65189) to stop this from happening, though maybe there's a better solution? 

You can see the `</pre>` renders correctly here on my branch:

![screen shot 2017-08-12 at 2 44 36 pm](https://user-images.githubusercontent.com/101547/29244510-93f9e948-7f6e-11e7-8d6e-0aa8b7846baf.png)

I tested and was able to reproduce this in CodeMirror 5.28.1 (and 5.15.2) on Chrome 60.0.3112.90 and Safari 10.1.2 (MacOS 10.12.6).

Thanks for looking at this—I'm a huge fan of CodeMirror!

**Comment by marijnh** [comment]
Patch c42322890d75a7 should fix this, and I've merged your test case as a347f5e3cf84eaeb2a
