### ISSUE TITLE
[emacs] ctrl+s only opens the find bar the first time

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4922]
1. https://codemirror.net/demo/emacs.html
1. ctrl+s, then type 'static', press enter
1. ctrl+s

expected: cursor moves and the findbar opens

actual: only cursor moves, findbar doesn't come up again, so you can't actually change the query afterwards

**Comment by marijnh** [comment]
There isn't currently an implementation of emacs-style search, but attached patch binds ctrl-s and ctrl-r to persistent search dialogs, which is a little better at least.
