### ISSUE TITLE
How to append string at the last of codemirror dom and scroll down to the bottom automatically?

### ISSUE THREAD

**Issue by zhaoyi0113** [codemirror/CodeMirror#4925]
I am using `CodeMirror` as an output panel. It will render a lot of messages generated from my server. The requirement for using it as output panel is that whenever UI receives a message from backend server it will append the message at the last of the CodeMirror. The problem I have is that CodeMirror shows the message at the top, not the bottom. How can I scroll down to bottom automatically when a new string get appended at the last?

**Comment by marijnh** [comment]
Try [`scrollIntoView`](http://codemirror.net/doc/manual.html#scrollIntoView)
