### ISSUE TITLE
Backspace can't delete characters on my android phone

### ISSUE THREAD

**Issue by strongrex2001** [codemirror/CodeMirror#4927]
My phone is Android 4.3.
Either the official site or my customed editor has the problem.
It works when I enter something and directly presses backspace.
but when I pressed somewhere else in the code and then move the cursor back, I can't delete anything.

**Comment by strongrex2001** [comment]
It seemed that the IME on the phone doesn't Fire an Backspace Event.
I overrided dispatchKeyEvent in my Activity, and it just didn't catch the Backspace....

**Comment by marijnh** [comment]
Yes, this is a well-known problem with Android. Backspace is handled entirely by the IME subsystem and you don't get a key event for it. CodeMirror has some workarounds that try to detect it, which worked on my phone last time I tried, but they're hacks and I'm not surprised to see they still have problems.

**Comment by strongrex2001** [comment]
What's the solution..? Maybe it works for me too..

**Comment by marijnh** [comment]
It's [in the library](https://github.com/codemirror/CodeMirror/blob/master/src/input/ContentEditableInput.js#L229), so assuming you're not using an old CodeMirror version, apparently it's not working for you.

**Comment by strongrex2001** [comment]
I overrided the onCreateInputConnection function in the WebView now and it works... but when I call the function the soft keyboard disappears... I'm trying some other methods to avoid this

**Comment by strongrex2001** [comment]
I use a variable in Java to record how many times backspace pressed but haven't been processed, and every 50milliseconds in Javascript fetch the variable and process the backspace event.
Now All Right! Thanks!

**Comment by strongrex2001** [comment]
I'm sorry to reopen this... But I've met an unbelievable bug... Today every time I pressed backspace it deleted two characters... I've overrided createinputconnection... I don't know how this could happen
