### ISSUE TITLE
Translate character index to column number.

### ISSUE THREAD

**Issue by nickasd** [codemirror/CodeMirror#4929]
I'm looking for a way to show the column number of the cursor, i.e. the character index of the current line but taking tabs into account. Is there an API for this yet?

**Comment by marijnh** [comment]
Not for the 'show' part, but to compute it, use `CodeMirror.countColumn(string, index, tabSize)`

**Comment by nickasd** [comment]
Thanks for the fast response. I cannot find a documentation for this method in the manual. I guess for `index` I should pass the character index, but what is `string`? And would it be possible to automatically infer `tabSize` from the current settings?

**Comment by marijnh** [comment]
`string` is the line, and since this is a static method, it doesn't have access to settings.

It does indeed appear the method wasn't documented. Patch e49a19f5 fixes that.
