### ISSUE TITLE
vim emulation ctrl-w behavior

### ISSUE THREAD

**Issue by sonnythai** [codemirror/CodeMirror#4931]
ctrl-w usually deletes the previous word correctly, but I noticed that when the word contains a special character, it preserves the special character and moves the cursor behind it.

Example:
foo.bar
foo/bar
foo\bar

If I place the cursor at the end of the line for all of these examples and hit ctrl-w, I end up with

foo.
foo/
foo\

and the cursor is behind the special character.

I would expect either the cursor to be after the special character or to delete the special character.

**Comment by marijnh** [comment]
(No one is actively maintaining the vim bindings, so note that it might take a while before this generates a response.)

**Comment by marijnh** [comment]
Fixed via #4985
