### ISSUE TITLE
Cursor jumps and strange rendering occurs

### ISSUE THREAD

**Issue by saulcosta18** [codemirror/CodeMirror#4932]
We use CodeMirror for [Codevolve](https://www.codevolve.com) (and love it!) and have some users reporting an issue that we're not able to reproduce on any of our machines.

There appears to be a lag in the rendering for the editor, which results in the cursor jumping and text flashing back into view. A screencast is located [here](https://www.screencast.com/t/Es3dDfay8) from a customer that can reliably reproduce it on multiple browser and OS combinations.

I noticed that the faint gray characters show up in all of their screencasts, which makes me think this may be a rendering issue? I'm still not sure why I cannot reproduce it in the exact same environment as our customers.

Any ideas?

**Comment by marijnh** [comment]
I can't view this because the video site requires Flash, which has happily been purged from my system. Could you try hosting it somewhere else?

**Comment by saulcosta18** [comment]
Unfortunately it's a customer reported issue and video. However, our customers are reporting that the issue appears to be resolved, so I'll close this ticket for now, and update with a non-Flash based video if it reoccurs.
