### ISSUE TITLE
Search, Jump-to-line, and the emacs keymap use inline styles

### ISSUE THREAD

**Issue by davidje13** [codemirror/CodeMirror#4937]
The search/search and search/jump-to-line plugins use inline styles on their dialogs. This can cause issues on pages which use a security policy, for example:

1. Add the following meta tag to the Search/Replace example (https://codemirror.net/demo/search.html):

    ```
    <meta http-equiv="content-security-policy" content="style-src 'self';">
    ```

1. Press Ctrl/Cmd+F to begin a search. The console will show permissions errors, and the styling will not be applied (specifically, the hint will not be washed out, and the search box will have a default width).

Other relevant situations would be where a developer wants to override the styling: currently `!important` would be unavoidable.

This is due to inline styles being used. I've checked through the source code and the only places inline styles ever appear (except for a handful in demos & documentation) are:
* https://github.com/codemirror/CodeMirror/blob/master/addon/search/search.js#L102
* https://github.com/codemirror/CodeMirror/blob/master/addon/search/jump-to-line.js#L22
* https://github.com/codemirror/CodeMirror/blob/master/keymap/emacs.js#L238

---

Since inline styles are generally pretty hacky things to use, and the rest of CodeMirror successfully avoids them, it would be nice to swap these with styling via classes in the default stylesheet instead.

The first 2 can be fixed by adding the following to the CSS and removing the inline styles:

```
.CodeMirror-search-field {
	width: 10em;
}

.CodeMirror-search-hint {
	color: #888;
}
```

The third has no existing class, so would need to have a new one created.

**Comment by marijnh** [comment]
> Since inline styles are generally pretty hacky things to use, and the rest of CodeMirror successfully avoids them, it would be nice to swap these with styling via classes in the default stylesheet instead.

There are inline styles all over CodeMirror. This just appears to be the only place where they are used through `innerHTML`.

In any case, no, if you're having trouble with this policy, I suggest turning off the policy. CodeMirror is written against widely understood and standardized browser functionality, and this idea of selectively forbidding random stuff just won't work well when you're using 3rd party code.

**Comment by davidje13** [comment]
@marijnh If you're referring to things like:

```
myElement.style.fooBar = 'baz';
```

That isn't considered an "inline style" by the security policy. It's there specifically to catch injection attacks, so javascript-based mutations aren't blocked (javascript execution implies much bigger problems!)

As far as I can tell, those 3 places really are the only issues. I can run CodeMirror with a *very* restricted security policy and it's fine, except for those (try it yourself with the not-very-strict example I gave).

I've already modified my own copy, so this isn't something I'm desperate for, more an FYI: you can make this library compatible with modern security layering (which has been standardised and is very widely supported) by changing about 6 lines of code.
