### ISSUE TITLE
Installation Documentation?

### ISSUE THREAD

**Issue by glittle** [codemirror/CodeMirror#4939]
On this web page: [Code Mirror - Manual](http://codemirror.net/doc/manual.html#usage)

It says:

> The easiest way to use CodeMirror is to simply load the script and style sheet found under lib/ in the distribution.

However, there is only a CSS file in the lib folder.

Please update instructions to guide people not using npm or any module loaders!

**Comment by marijnh** [comment]
The key term here is **distribution**. You appear to just have gotten the repository, which isn't that. Get it from the [website](http://codemirror.net/codemirror.zip) if you aren't using NPM for whichever reason.

**Comment by glittle** [comment]
Thanks for the ZIP file. Where would I find that? I've looked over the website and could not find any link to download the zip.

Ahh, finally found it: "Get the current version: 5.29.0." 

Might be nice to tweak that wording. Somehow include the word "distribution" or "download"!  It would be fine split the two functions of that line into two locations... a link to download and a display of the version number. 

I also totally missed the word "Download" in the graphic... didn't know it was clickable, and wondered what "Download Fund" meant!
