### ISSUE TITLE
selection is incorrect width.

### ISSUE THREAD

**Issue by chocholand** [codemirror/CodeMirror#4943]
![2017-08-30 9 52 06](https://user-images.githubusercontent.com/6572227/29850511-458ded8c-8d69-11e7-9a91-ee61f11dfa2b.png)

```
 function displayWidth(cm) {
    return cm.display.scroller.clientWidth - scrollGap(cm) - cm.display.barWidth
  }
```

When I remove scrollGap(cm), selection is correct.

**Comment by marijnh** [comment]
Does this happen for you in the demos on http://codemirror.net/? If so, which browser are you using? If not, could you try to figure out which local CSS causes this?

**Comment by chocholand** [comment]
@marijnh I want to remove scrollbar, so I add style.
```
.CodeMirror-scroll {
    height: auto;
    position: static;
    padding: 0;
    margin: 0;
    overflow-y: hidden !important;
    overflow-x: hidden !important;
  }
```

Is there another anything to remove scrollbar?

**Comment by callodacity** [comment]
@chocholand if you want to remove the scrollbar, you should pass `scrollbarStyle: 'null'` as an option when you instantiate your editor. See the [manual](http://codemirror.net/doc/manual.html#config) for details on how to do that.

If you try to remove it manually, you'll end up messing with some of CodeMirror's internals.

**Comment by marijnh** [comment]
> I want to remove scrollbar, so I add style.

Yeah, that's not supported. Don't touch the `overflow` on `CodeMirror-scroll`.
