### ISSUE TITLE
Can't run search addon when in readonly mode

### ISSUE THREAD

**Issue by sarveshbathija** [codemirror/CodeMirror#4949]
When using the the `readOnly: 'nocursor'` option.  The search addon doesn't activate when needed.  When the option is removed. Search works perfectly.  There is no reason to disable a search in readonly mode.  Just disable any text changes if using replace.

**Comment by marijnh** [comment]
You can't focus a `nocursor` editor, so you simply won't be able to send key events to it, and thus using a hotkey to activate search is going to impossible. This is expected behavior.
