### ISSUE TITLE
Add non full line selection to CodeMirror

### ISSUE THREAD

**Issue by callodacity** [codemirror/CodeMirror#4951]
I would just like to preface this issue with a little context on my thoughts about this addition to CodeMirror. I've always been a fan of how CodeMirror V1 performed "non-full-line selection". Here's a screenshot of CodeMirror V1's selection:

<img width="814" alt="screen shot 2017-09-05 at 1 52 25 pm" src="https://user-images.githubusercontent.com/1011648/30044637-aec4c3ca-9241-11e7-96ad-ce7813575807.png">

@marijnh I also know that you weren't [exactly keen on the idea](https://groups.google.com/d/msg/codemirror/2OeFhfSuHzU/VZJbVXRm1UQJ) when CodeMirror V2 was brought out. At the time you said:

> The current model doesn't easily allow supporting both approaches, so there's no option to switch between them.

But having a look at the code now, it looks like the foundation that's there may support both approaches without too much effort. I've actually started to add the non-full-line-selection as an option in [this fork](https://github.com/callodacity/CodeMirror/commits/non-full-line-selection) (you can see the [exact changes here in this commit](https://github.com/callodacity/CodeMirror/commit/f1ab23d054263b1574ef5114d414d777f2127797)).

Here's a quick screenshot of the current fork, with `fullLineSelection` disabled in the top editor:

<img width="629" alt="screen shot 2017-09-05 at 2 35 55 pm" src="https://user-images.githubusercontent.com/1011648/30045437-a4790d4e-9247-11e7-82fa-2295f9edc0e3.png">

Please note, that unfortunately I haven't been able to fully wrap my head around bidirectional text, so my current fork only supports the left-to-right direction. However, I have got it working perfectly with `lineWrapping` and also with code folds.

---

I was also looking at giving the selection a curved border so it would look more aesthetic (like Sublime Text, vscode, etc.), here's an example (from vscode).

<img width="540" alt="screen shot 2017-09-05 at 1 57 38 pm" src="https://user-images.githubusercontent.com/1011648/30044696-35c19146-9242-11e7-82da-b448d5698fd9.png">

I originally thought that adding curved borders would be too difficult in the DOM, but vscode tackles the problem by adding extra elements where the border-radius needs to go the other way - a smart trick, and it works well! Here's what I mean.

<img width="691" alt="screen shot 2017-09-05 at 1 58 26 pm" src="https://user-images.githubusercontent.com/1011648/30044705-5237d8c6-9242-11e7-9b6a-9722068a7280.png">

---

All in all, I'm creating this issue at the moment, for two reasons:

1. I think I may need your help with supporting bidirectional text
2. I don't want to put in heaps of effort if this isn't something you want to have in CodeMirror

All things considered, @marijnh I would like to know your opinions, thoughts, suggestions, etc. on potentially integrating this into CodeMirror.

**Comment by marijnh** [comment]
Have you tried using CSS to hide the built-in selection (`.CodeMirror-selected { display: none }`) and using the [markselection addon](http://codemirror.net/demo/markselection.html) to style your selection?

**Comment by callodacity** [comment]
Hah! I hadn't thought of that. That definitely looks like it works well, but is it possible to highlight past the end of the line with the markselection addon?

e.g., when highlighting just the text, if one highlights past the line an extra distance is highlighted to indicate that the selection is past the end of the line. (Like line 4 in the 2nd screenshot in my original post). Because, if that's not possible, then the user won't be able to distinguish between highlighting just to the end of the line, or highlighting to the start of the next line.

**Comment by marijnh** [comment]
> but is it possible to highlight past the end of the line with the markselection addon?

Not easily. You could add more code to add style non-breaking-space widgets to every line whose end is selected.

**Comment by callodacity** [comment]
Hmm, I'm not sure that's exactly possible. I've tried to give that a shot both with `cm.addWidget` and `cm.markText`. It looks like both those APIs clip the widget to the end of the line - so I can't seem to place the widget *after* the actual line. 

It *may* be possible with `markText` but since the marker wraps with the text is the user has `lineWrapping: true` and the line exceeds the max length then the widget will wrap too.

Unless, of course, I misunderstood how one would go about adding such widgets.

**Comment by marijnh** [comment]
> I can't seem to place the widget after the actual line.

You don't need to -- if you place it _at_ the end of the line, it can take up space and thus extend the line.

**Comment by callodacity** [comment]
Ah, sorry about that -- I must have had something wrong in my tests.
I got it all working now 👍 

Sorry for the trouble, and thanks again 😄
