### ISSUE TITLE
Tern addon fails to complete when initiated from last char of long file

### ISSUE THREAD

**Issue by dave-at-goss** [codemirror/CodeMirror#4954]
reproducible in demo
paste or type JavaScript longer then bigDoc (250+ lines)
on the last line type some code and request a completion
Tern addon will create a fragment in getFragmentAround the returned text has the end Pos set to ch:0 i.e. before the cursor.

when the tern server calls resolvePos the cursor position is beyond the end of the file and an error is thrown "Position x is outside of file."

simple fix in getFragmentAround if cursor is at the and of the last line set text end Pos to the end of the file

NB getFragmentAround uses a constant tabSize would it be better to use the cm option value (tabSize or indentUnit)

**Comment by marijnh** [comment]
Attached patch should help with this.
