### ISSUE TITLE
Unicode "\uFEFF" getting copied from CodeMirror to IDE

### ISSUE THREAD

**Issue by mzabuawala** [codemirror/CodeMirror#4955]
I'm experiencing a strange unicode character being copied over with text from CodeMirror to my IDE.

Here is the SQL window
https://ibb.co/cU1ZRv

And the pasted result in the development IDE:
https://ibb.co/iUuAzF

Any thoughts on what could be causing this?

**Comment by marijnh** [comment]
In which browser is the CodeMirror instance running?

**Comment by mzabuawala** [comment]
We are using our python web app on top of Qt WebEngine 5.9.

**Comment by marijnh** [comment]
That's not one of the supported browsers—if you can reproduce this in a major browser, let me know, but if not, you'll have to try to debug it yourself. (It sounds like CodeMirror's copy handler is somehow not running, and webengine's native copy behavior is happening instead.)

**Comment by mzabuawala** [comment]
Okay, Thanks.
