### ISSUE TITLE
Angular2 - TypeScript: decorator for constructor param

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#4959]
After `@Inject('apiBase')` the code is not highlighted correctly. If I remove it then the code is correct.
```typescript
@Injectable()
export class AuthService {
  private _loginApi = this._apiBase + '/authorize/local';
  constructor(private http: Http, @Inject('apiBase') private _apiBase: string) {}
  redirectUrl: string;
  login(user): Observable<boolean> {
    const body = JSON.stringify(user);
    const headers = new Headers();
  }
}
```

**Comment by marijnh** [comment]
Oh, ugh, TypeScript is very creative. The [decorators proposal](https://tc39.github.io/proposal-decorators/#sec-syntax) doesn't allow decorators on parameters, but it appears [TypeScript](https://www.typescriptlang.org/docs/handbook/decorators.html) does. See attached patch.
