### ISSUE TITLE
Support for uppercase X in GFM task lists

### ISSUE THREAD

**Issue by gbui** [codemirror/CodeMirror#4960]
Based on my limited knowledge after using [Editor.md](https://pandao.github.io/editor.md/en.html) and looking at some code, uppercase X in GFM task lists is currently not supported in CodeMirror.

As far as I know, support for uppercase X should only require RegEx changes.

**Comment by gbui** [comment]
Should this line be changed as well?
https://github.com/codemirror/CodeMirror/blob/2cff704fd44f418eae599ae05ac1547cc8c5e3fa/mode/markdown/markdown.js#L406
Perhaps to this:
````javascript
var taskOpen = stream.match(taskListRE, true)[1].toUpperCase() !== "X"; 

````
(Sorry, I know I said "should only require RegEx changes")

**Comment by marijnh** [comment]
I guess so. See 20f3c354
