### ISSUE TITLE
[emacs][Linux] Typing Ctrl-S twice fast results in the browser Save Page dialog coming up.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4963]
Does not occur w/ Mac since Ctrl-S doesn't have a browser-native binding.

**Comment by takamori** [comment]
Still occurs if you type Ctrl-S twice, click in the editor, and then type Ctrl-S. (tested on http://codemirror.net/demo/emacs.html )

**Comment by marijnh** [comment]
I can't reproduce it anymore. Do you see an stack trace in your dev tools when it happens?

**Comment by takamori** [comment]
hmm, you're right. It looks fine now.
