### ISSUE TITLE
Crash (endless loop) when selecting combination of English, Arabic and numbers

### ISSUE THREAD

**Issue by rasmusvhansen** [codemirror/CodeMirror#4964]
CodeMirror gets stuck in an endless loop when selecting certain combinations of text. 
I have reproduced this on the build running on https://codemirror.net/demo/bidi.html (5.29.1 - but is most likely latest from github) using the following steps:

1. Write "some english text"
2. Switch to arabic keyboard and write "صاشفثرثق"
3. Write "23423"
4. Use the mouse to select the text from right to left (sometimes it takes a few passes)
5. The browser is now unresponsive, stuck in `coordsCharInner` and friends

Browser: Chrome 60 on Windows 8.1

Video capture of reproducing it here: https://screenpresso.com/=LGkid

**Comment by marijnh** [comment]
This has been been fixed as part of #4926, specifically in patch 68b4f44e3c6ea78
