### ISSUE TITLE
Incorrect highlight as hash.

### ISSUE THREAD

**Issue by ParthKolekar** [codemirror/CodeMirror#4966]
https://github.com/codemirror/CodeMirror/blob/79ab976875ea45aaedc060a409ffc0f54fec2d29/mode/gfm/gfm.js#L84

The line above causes words like "feedbac" to be incorrectly rendered as a link. Why is syntax highlight for SHA hashes even required?

**Comment by ParthKolekar** [comment]
#4967 Fixes this issue.

**Comment by ParthKolekar** [comment]
Closed because github has this issue too.

**Comment by marijnh** [comment]
I don't think the PR is correct (see comment there), but maybe we can approximate this by requiring at least one number in the hash? (Letter-only hashes exist, of course, but are relatively rare -- 0.1% of seven-character-hashes)

**Comment by ParthKolekar** [comment]
This issue is incorrect. Please feel free to close this issue.

**Comment by cben** [comment]
Love the intent of an approximation, but this ignores for example `beaaccac1ecfe9489fb51e4869af15a13fc2cd2`.
Let's see, the probability of 1 hex digit beeing [a-f] is 6/10.
The probability of first 6 being [a-f] is (6/10)**6 = 4.6%.
IMHO it's OK to be err on side of "not hash" for short 7-letter words, but for longer it's possible and would be nice to have much lower false negative rate.

**Comment by marijnh** [comment]
If you can find a regular expression that expresses this (without getting ridiculous complex), a pull request would be welcome.
