### ISSUE TITLE
Fold/Unfold code hard to use on mobile

### ISSUE THREAD

**Issue by louisatome** [codemirror/CodeMirror#4969]
On mobile devices (iOS, android) the folding functionality is really hard to use. Even with enlarged fold buttons, the event isn't triggered easily.
After some debug, here's what's going on when tap on the fold button : 
* `touchstart` event listener is called from https://github.com/codemirror/CodeMirror/blob/5a5c75fa68da86f5e0b85551d2282301b2c7c856/src/edit/CodeMirror.js#L145
* the `activeTouch` property is created with the touch informations (except if the radius of the touch is very small. In this case the `activeTouch` won't be created and the fold action will work)
* `touchend` event listener is called from https://github.com/codemirror/CodeMirror/blob/5a5c75fa68da86f5e0b85551d2282301b2c7c856/src/edit/CodeMirror.js#L161
* the `preventDefault` method is called on the event, so the mousedown event won't be triggered and the `clickInGutter` is never called from the mousedown listener https://github.com/codemirror/CodeMirror/blob/5a5c75fa68da86f5e0b85551d2282301b2c7c856/src/edit/mouse_events.js#L58 

Is that a correct behaviour ?

**Comment by marijnh** [comment]
> Is that a correct behaviour ?

No -- the activeTouch behavior should probably not kick in for gutter interaction. I guess we'd need something like the check in `gutterEvent` at the start of the `touchstart` handler, but in a way that works with touch events. Do you want to try to implement that?
