### ISSUE TITLE
Code Snippet in Code Mirror

### ISSUE THREAD

**Issue by aayushpatidar** [codemirror/CodeMirror#4972]
Apart from the keywords, I also want the code snippet of the whole keyword with indentation.
For example if I write while and after clicking on the suggestion of while it should display the syntax of while like in Python - 

while expression:
   statement(s)

and if for Java then,

while(condition){  
//code to be executed  
}  

If any plugins or extensions are there so can you please suggest me.

**Comment by marijnh** [comment]
That doesn't exist in the main distribution, but you can write it as an addon. I think [this](https://github.com/angelozerr/CodeMirror-XQuery/wiki/Completion-with-Templates) already does something like it, but I'm not sure how reusable it is outside of that project.
