### ISSUE TITLE
Connect the repo to Reviewable

### ISSUE THREAD

**Issue by StellarDoor5319** [codemirror/CodeMirror#4976]
Please connect this repo at https://reviewable.io/repositories so that all PRs get linked to reviews. Thanks!

**Comment by adrianheine** [comment]
What exactly does that mean? If I understand [this](/codemirror/CodeMirror/pull/4646#issuecomment-330025372) correctly, you can already use Reviewable for doing reviews?

**Comment by StellarDoor5319** [comment]
I can use it, but connecting the repo means that it syncs automatically (notifying me and other reviewers of new commits), and adds a few other features. Just recommending that you connect it 😀

**Comment by marijnh** [comment]
Sorry, no, I'm not interested in connecting tools I don't use and hadn't even heard of before to my repositories.

**Comment by StellarDoor5319** [comment]
Ok. I can still review with it though. Just a reccomendation
