### ISSUE TITLE
[question] Using Enter in search mode?

### ISSUE THREAD

**Issue by ahmedelgabri** [codemirror/CodeMirror#4977]
I'd like to be able to use <kbd>Enter</kbd> & <kbd>Shift+Enter</kbd> in search mode, so what is the best way to implement this? How can I know if the user is in search mode or not to override the default key mapping & then revert it back after they exit search mode?

So this is the workflow:

- User triggers search mode (<kbd>CTRL/CMD + F</kbd>) => how can I know if this is on/off
- User search for some string
- User wants to go to the next/prev match => here I want to use <kbd>Enter</kbd> instead of the default <kbd>CTRL/CMD+g</kbd>
- User exits search mode => <kbd>Enter</kbd> now adds a new line as before.

**Comment by marijnh** [comment]
CodeMirror's search dialog doesn't work like a persistent dialog, so whenever the editor is focused, it is _not_ searching. For what you're trying to do, it's necessary to write your own search dialog.
