### ISSUE TITLE
Support c# automatic formatting

### ISSUE THREAD

**Issue by zhangzhike** [codemirror/CodeMirror#4989]
Hello, I tried the automatic formatting function, but I found that c # does not support (clike), other support. Please fix it.

**Comment by marijnh** [comment]
What automatic formatting function?

**Comment by zhangzhike** [comment]
I'm using formatting.js from https://codemirror.net/2/demo/formatting.html

**Comment by marijnh** [comment]
That's no longer part of CodeMirror since v3, so I suggest you find another library that does it.
