### ISSUE TITLE
Automatic association function is realized using CodeMirror

### ISSUE THREAD

**Issue by zhangzhike** [codemirror/CodeMirror#4990]
I am using the show-hint.Js to implement automatic associative functionality, but I found that the change event was always called, causing the showHint() method to be called and the browser card dead. Please fix it.

**Comment by marijnh** [comment]
Could you provide example code that leads to this crash/hang?

**Comment by adrianheine** [comment]
I'm closing this issue since it does not contain enough information for us to work with. Please feel free to reopen it when you provide example code!
