### ISSUE TITLE
[HTML/XML] wish tag renaming would result in the corresponding close tag being changed as well

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4991]
If one has the text
`  <div>some content</div>
`
and changes the "`div`" to "`span`", it would be nice if the "`/div`" would simultaneously change to "`/span`" as well.

**Comment by marijnh** [comment]
You could write an addon that does this, but it isn't a feature that's currently provided, so I'm not going to keep an issue open on it.
