### ISSUE TITLE
Contenteditable mode prevents selecting multiple regions (programmatically)

### ISSUE THREAD

**Issue by neochief** [codemirror/CodeMirror#4993]
When in contenteditable mode I try to select multiple regions programmatically, CodeMirror renders only one selection region. It works just fine in the textarea mode.

The reason is the same as in https://github.com/codemirror/CodeMirror/issues/3552

**Comment by marijnh** [comment]
This works for me. Can you submit a code example that reproduces it?

**Comment by neochief** [comment]
Sure! Here's a minimal code to reproduce it:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/codemirror.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/codemirror.js"></script>
</head>
<body>
    <div id="test"></div>
    <script>
        editor = CodeMirror(document.getElementById('test'), {
            value: "123 321"
        });
        editor.setSelections([
            {
                anchor: {line: 0, ch: 0},
                head: {line: 0, ch: 2}
            },
            {
                anchor: {line: 0, ch: 4},
                head: {line: 0, ch: 6}
            }
        ], 0);
    </script>
</body>
</html>
```

**Steps to reproduce:**

1. Create a test.html with the given code.
2. Open it in Chrome. It should produce 2 selections, as expected.
3. Open dev tools, go to the mobile view.
4. Reload the page. Now it will produce only one selection.

As I mentioned before, I managed to track problem down to this:

```
// prepareSelection function
if (primary === false && i == doc.sel.primIndex) continue;
```

```
// In normal mode, the primary variable will be null, thus skipping the code from above.
TextareaInput.prepareSelection(cm);
```

```
// But here it will lead to displaying only primary selection.
ContentEditableInput.prepareSelection(this.cm, false)
```

**Comment by marijnh** [comment]
It does produce two selections, but since the primary selection is rendered as a DOM selection, you're only able to see it when the editor is focused. This is somewhat confusing, I agree, and is due to the way the contentEditable input backend was bolted on to a system that was designed without it in mind, but it's by design.

**Comment by neochief** [comment]
Thanks for the reply, Marijn. I've tried to run a replacement command after selection and it, indeed, replaced both occurrences, even though only one is visually selected.
