### ISSUE TITLE
Cursor is not aligned

### ISSUE THREAD

**Issue by JackieLs** [codemirror/CodeMirror#4997]
![image](https://user-images.githubusercontent.com/14228179/30893259-d807d304-a302-11e7-805f-c7825ccd49ea.png)
```
/* html in vue */
<div class="container"  :class="`cm-s-${$store.state.theme}-code-wrap`" id="code-wrap"></div>
/* js */
CodeMirror(document.getElementById('code-wrap'), {
	mode: 'text/html',
	lineNumbers: true,
	json: true,
	value: myData,
})
/* css */
.container{ width: 100%; height: 100%; }
```
The above is my code.
Just like the picture, when I click some place, the cursor is not aligned with my code.
I try to enter, and found where my cursor stay is not the code's place, but some strange place just like the follow.
![image](https://user-images.githubusercontent.com/14228179/30893474-fa70ba68-a303-11e7-9b9a-36b2c42d19f5.png)

How could this happened ?How to fix this ?

**Comment by badbrainz** [comment]
Have you tried calling the refresh method? In your vue instance you can call it after setting the CodeMirror value and during a resize event. e.g. `this.$nextTick(() => cmInstance.refresh())`

**Comment by JackieLs** [comment]
I try to add the options`{inputStyle: 'contenteditable'}`,and it works well.
I think just because I render the `CodeMirror` with a `<div>`, but the `inputStyle` still `textarea`, the cursor rendered for the `textarea`.So Is this a little bug or I use it in wrong way?

**Comment by marijnh** [comment]
This tends to happen when the layout of your editor changes after it is initialized, for example because a font finishes loading or its css changes. Calling `refresh` when the layout has stabilized is the recommended solution.
