### ISSUE TITLE
Some events not detached potentially causing memory leak

### ISSUE THREAD

**Issue by dwelle** [codemirror/CodeMirror#5000]
Haven't looked into this very close, but running our site through canary's performance monitor, it seems (though not necessarily) that CM leaves behind a lot of event handlers.

Glancing at the code, e.g. `copy`/`paste` events don't seem to be detached, and they both keep `cm` instance in their closure. Am I reading this right?

Even if some event handlers, such as [resize](https://github.com/codemirror/CodeMirror/issues/2559), don't keep `cm` instance in a closure, wouldn't it be better idea to detach all events on removing CM from the DOM (or add a `#destroy` method)?

**Comment by marijnh** [comment]
We're no longer using IE6, so even if you have event handlers on a DOM element, if the element is removed from the DOM those handlers will get garbage-collected. Since copy/paste handlers are registered only on the editor, removing the editor from the DOM is enough to clean them up.
