### ISSUE TITLE
Citing CodeMirror in academic paper

### ISSUE THREAD

**Issue by danr** [codemirror/CodeMirror#5002]
Is there some preferred way to cite CodeMirror in an academic (peer-reviewed) paper? Such as a using a BibTeX entry, or a footnote.

Thanks!

**Comment by marijnh** [comment]
Nope, I don't think this has come up before. I'd cite it as a website, http://codemirror.net, I guess. Something like

```
@online{CodeMirror,
  author = {Marijn Haverbeke},
  title = {CodeMirror},
  year = {2007--2017},
  url = {http://codemirror.net/}
}
```
