### ISSUE TITLE
Selection of BIDI text shows wrong selection 

### ISSUE THREAD

**Issue by rasmusvhansen** [codemirror/CodeMirror#5004]
CodeMirror version 5.30

How to reproduce:

1. Go to https://codemirror.net/demo/bidi.html
2. Type `aش` (english a, and arabic 'a')and hit enter
3. Type `bلا` (english b and arabic 'b') and hit enter
4. Select everything except the `b` and press delete
5. The resulting text is now `bلا`

I think what is deleted is probably correct, but the visualization of the selection is not.

Here is a screen capture:
https://screenpresso.com/=1QXRd

This commit (https://github.com/codemirror/CodeMirror/commit/044850a01718d92fd61673dde3b08b1b07ccceb6) improved the behaviour (it now works if you have all RTL text) but it still fails on lines with both RTL and LTR.

Environment:
Windows 8.1 
Chrome  61.0.3163.91

**Comment by marijnh** [comment]
Acknowledged. This is surprisingly hard to get right. I started on a solution, but I haven't had time to finish it yet -- will get back to it at some point.

**Comment by marijnh** [comment]
With patch 9f7ce5a47de1181, the drawn selection should correspond to the actual selection in this case.
