### ISSUE TITLE
ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by merbin2012** [codemirror/CodeMirror#5005]
When I run this program always I got this error **ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff net::ERR_FILE_NOT_FOUND**, I seen your solution in stackoverflow "https://stackoverflow.com/questions/26718710/my-codemirror-textarea-doesnt-work". But I did not get your point, because already I am using like that
```javascript
var editor=CodeMirror.fromTextArea(document.getElementById("newtxtid"),{styleActiveLine: true,matchBrackets: true,mode:mixedMode,extraKeys: {"Ctrl-Space": "autocomplete"},lineNumbers:true,gutters:["CodeMirror-linenumbers","breakpoints"],lineWrapping:true,autoCloseTags:true,autoCloseBrackets:true,value:"<html>\n  "+ document.documentElement.innerHTML+"\n</html>",matchTags:{bothTags:true},extraKeys:{"Ctrl-J":"toMatchingTag"}});
```

**Comment by marijnh** [comment]
This error does not come from CodeMirror.

**Comment by merbin2012** [comment]
![How this error shown, this error is from your codemirror files](https://user-images.githubusercontent.com/3687184/31304949-f6cfafc2-ab4b-11e7-8d50-e266868ff84d.png)

When I click the external2.js error, it show the following line
``var editor=CodeMirror.fromTextArea(document.getElementById("newtxtid"),{styleActiveLine: true,matchBrackets: true,mode:mixedMode,extraKeys: {"Ctrl-Space": "autocomplete"},lineNumbers:true,gutters:["CodeMirror-linenumbers","breakpoints"],lineWrapping:true,autoCloseTags:true,autoCloseBrackets:true,value:"<html>\n  "+ document.documentElement.innerHTML+"\n</html>",matchTags:{bothTags:true},extraKeys:{"Ctrl-J":"toMatchingTag"}});``

**Comment by SolomonLeon** [comment]
I have found out the error.
It comes form './doc/doce.css':
`@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 400;
  src: local('Source Sans Pro'), local('SourceSansPro-Regular'), url(//themes.googleusercontent.com/static/fonts/sourcesanspro/v5/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
}`
To solve the problem, you can add 'http:' after 'url('
