### ISSUE TITLE
coordsChar is off by half a character

### ISSUE THREAD

**Issue by jayfoad** [codemirror/CodeMirror#5010]
As suggested [else](https://github.com/codemirror/CodeMirror/issues/408#issuecomment-4289954)[where](https://discuss.codemirror.net/t/hover-over-symbol-idea/245) I'm using `cm.coordsChar` to convert mouse coordinates to character positions, in order to implement my own tooltips. But I found that `coordsChar` doesn't always return me the character containing the specifed coordinates; sometimes it returns the character one place to the right.

In practice, if I have the text `foo(bar)` on screen and there is a tooltip for the token `bar`, I have to hover anywhere from half way across the `(` to half way across the `r`.

I guess this is caused by the following code in `coordsCharInner` in `src/measurement/position_measurement.js`:

```
  // If a box around the coordinates was found, use that
  if (boxAround) {
    // Distinguish coordinates nearer to the left or right side of the box
    let atLeft = x - boxAround.left < boxAround.right - x, atStart = atLeft == ltr
    ch = chAround + (atStart ? 0 : 1)
    sticky = atStart ? "after" : "before"
    baseX = atLeft ? boxAround.left : boxAround.right
  } else {
```
But that just seems wrong, at least for my use case.

**Comment by marijnh** [comment]
> But that just seems wrong, at least for my use case.

That may be so, but it's right for most other use cases, since you're usually interested in a document position, not a character box, so this is a feature, not a bug. You could look at the (currently undocumented but unlikely to go away) `xRel` property on the position returned to adjust, if you want.

**Comment by jayfoad** [comment]
> You could look at the (currently undocumented but unlikely to go away) `xRel` property on the position returned to adjust, if you want.

Will do. Thanks.
