### ISSUE TITLE
codemirror.js was not included in the 5.30.0 release in bower

### ISSUE THREAD

**Issue by paladox** [codemirror/CodeMirror#5012]
Hi, when i tryed out codemirror from bower, i am finding codemirror.css is included but codemirror.js is not. Please could this be fixed? :)

bower install CodeMirror/codemirror
bower cached        https://github.com/CodeMirror/codemirror.git#5.30.0
bower validate      5.30.0 against https://github.com/CodeMirror/codemirror.git#*
bower install       codemirror#5.30.0

codemirror#5.30.0 bower_components/codemirror

xxx@XXX-MBP:~/code/bower_components/codemirror/lib$ ls -la
total 24
drwxr-xr-x   3 xxx  staff    96 20 Sep 10:26 .
drwxr-xr-x  26 xxx  staff   832  7 Oct 18:11 ..
-rw-r--r--   1 xxx  staff  8271 20 Sep 10:26 codemirror.css

**Comment by paladox** [comment]
same for 5.29.0 release.

**Comment by schanzer** [comment]
This is not a bug. See the README.

**Comment by paladox** [comment]
It shows lib/codemirror.js here https://codemirror.net/doc/manual.html

**Comment by paladox** [comment]
https://github.com/codemirror/CodeMirror/commit/aa6e9903a786477a789f431c39a8fd030b8046d5#diff-e8acc63b1e238f3255c900eed37254b8 shows a lib/codemirror.js should be generated.

**Comment by paladox** [comment]
and here https://github.com/codemirror/CodeMirror/blob/master/package.json#L4

**Comment by marijnh** [comment]
There is no 'bower release'. Bower is mistakenly pointing at this repository as being a downloadable package, which it isn't, and it doesn't seem the Bower community can get its stuff together to the point of fixing that. I've stopped caring. Use NPM.
