### ISSUE TITLE
JavaScript not highlighted correctly

### ISSUE THREAD

**Issue by loituma-ievan-polkka** [codemirror/CodeMirror#5013]
### Test case

```JavaScript
        v=1,p=           global
      ['process'       ],f=[p=>g`
    `,v=>g(f.m=v),   z=>w(`${++f[(2
  ,'m')]+--z}`),_=> ($=p).exit($[p]^p
 [$])],w=a=>p.stdout.write(a),g=a=>w((
!0&&`#${-~[f[p]^=f[w],f[p]++][0]} ${u()
}: `)),u=a=>eval(`${[...'typeof'].join(
[p[p]])}+a`),p.stdin.on('data',(z=>(z()
 ,z))(a=>f.shift`${[void[[][p]---/\//^
  -~void[_=>{~{*[_*$]([$,_]=a){a:{b:c
   ?d:e}},u:u=>-/.*?/.test(`${-u}${a
    +u^~++b}`),"-a":(y,[...m])=>/Q/
      /~/o/}}]||!f(a=>f.pop(m=g(z
        |z.substr(p,q))&-!g[w])
          ,--a-++b**/**/-c,[a
            %(b--)[s]-[...z
              ()]``(v)],-
                k)]]}`(
                  a))
                   )
```

### How it looks

[Screenshot](https://user-images.githubusercontent.com/32232740/31316915-6ce740bc-ac37-11e7-94b0-ff94ba31b918.png)

### Issue

I don't know JavaScript, I just found this code snippet on internet and pasted it in CodeMirror and noticed wrong highlighting. I have no idea what causes the issue and how to reduce it to simplier test case. Sorry about it.

**Comment by marijnh** [comment]
That's a lot of corner cases in a few lines of code. Attached patches seem to improve the highlighting.
