### ISSUE TITLE
CodeMirror throws a violation

### ISSUE THREAD

**Issue by dxtvdgzr9xil** [codemirror/CodeMirror#5015]
When loaded in a browser, the `codemirror.js` displays three [violations](https://user-images.githubusercontent.com/32622528/31321185-ed0c48e2-ac81-11e7-9e66-e9845b0e0691.png). The target line is

```JavaScript
/* codemirror.js:1122 */ emitter.addEventListener(type, f, false);
```

I suppose it should be "passive", as the message says.

**Comment by marijnh** [comment]
Nope, this is intentional — the behavior in question is indeed potentially scroll blocking, but we need it, whether browsers complain about it or not.
