### ISSUE TITLE
[JavaScript] Incorrectly highlighted regex

### ISSUE THREAD

**Issue by the-pirate-bay** [codemirror/CodeMirror#5016]
### Issue

Thanks for fixing the previous [issue](https://github.com/codemirror/CodeMirror/issues/4981) I've posted. However, there are a few more issues including regular expressions. Again, I must mention that if it is not worth fixing, then don't fix it, because it rarely appears in real code.

### Test cases

The highlighter fails for the following test cases:

```JavaScript
return
{}/\//;

break
{}/\//;

debugger
{}/\//;

````[.0]+++
{[[]]:1e-1}/ /\//;

a/**/=>a;

(a
)=>a;

({a=a
}=a)=>a;

~class extends
{}
{}/ /\//;
```

### Explanation

**Test case 1:** According to the spec, `return` statement breaks the expression on the first possible new line (not like `void` or `typeof`)
**Test case 2:** Same with break
**Test case 3:** Debugger doesn't require arguments
**Test case 4:** Not sure why this one causes a highlighting issue. Tagging teplate literals to template literals is allowed, and the post increment operator is also allowed, because it increments 0th element of the result (which is indeed a valid reference)
**Test case 5-7:** Function arguments are not recongized, but the actual function body is. I think these ones will require a lot of lookahead, so probably you will not fix it, but I'm reporting it anyway
**Test case 8:** This is a negated anonymous class divided by a regex

**Comment by marijnh** [comment]
I've attached some fixes. The remaining cases, I don't care much about (patches welcome, but I'm not writing them).
