### ISSUE TITLE
Code snippet misparsed

### ISSUE THREAD

**Issue by loituma-ievan-polkka** [codemirror/CodeMirror#5018]
### JavaScript code

```JavaScript
o---o    == $
|   o-o  ||
oo    |  oo
 |   oo  ||
 o---/   //`
         \u0064
     O___/
       l
      #`;
```

### How it looks

[Screenshot](https://user-images.githubusercontent.com/32232740/31354888-66238a22-ad38-11e7-9941-4980f5535d4b.png)

### Issue

Again, I don't know JavaScript, I just found this code on internet and noticed that CodeMirror doesn't highlight it properly. The `#` symbol is colored red which represents wrong syntax (I suppose), but it is actually correct syntax.

**Comment by marijnh** [comment]
Where are you even getting these terrible pieces of code? Anyway, I think I just fixed this 5 minutes ago with a patch to another issue full of pathological code (#5016).
