### ISSUE TITLE
getting the pc/mac version of emacs & sublime keymaps at runtime

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5020]
I'd like to be able to get the pc and mac versions of the emacs and sublime keymaps programmatically. Currently, they are written such that they each only produce a single keymap based on the sniffed OS at load time. I'd like to send a PR that changes them to

1. create `macEmacs`/`macSublime` and `pcEmacs`/`pcSublime` keymaps, as well as the current `sublime` and `emacs` ones
1. make the prefixless one point to either the mac or pc version (like you do with `default` + `macDefault`/`pcDefault`)

Would this be acceptable? Or do you have a preferred alternative method for accomplishing this sort of thing?

**Comment by marijnh** [comment]
That sounds like a good idea, yes.

**Comment by adrianheine** [comment]
Fixed in #5022, right?
