### ISSUE TITLE
Spaces inserted instead of tabs after new line

### ISSUE THREAD

**Issue by mzabuawala** [codemirror/CodeMirror#5021]
I'm using codemirror with SQL mode.

I have set my options to use tabs, not spaces for indentation. It works properly when pressing the "tab" key at the beginning of a line. But when I add a new line by pressing "ENTER" at the end of a line the indentation in the new line is filled with normal spaces not tabs.

The first line has tabs which I entered before SQL but the second line automatically use space for indentation, it should be tabs instead.

Please check screenshot: https://ibb.co/nmOwRG

**Comment by marijnh** [comment]
Your screenshot link doesn't work.  But check whether `indentUnit` and `tabSize` are the same.

**Comment by mzabuawala** [comment]
Hi,

I am able to open link in previous post,
I have uploaded it on another website as well, check https://imgur.com/a/Nmvsb

**Comment by marijnh** [comment]
And `indentWithTabs` is true? Because I definitely can not reproduce this (also, the mode has no control over the characters used for indentation, so this isn't related to the SQL mode).

**Comment by mzabuawala** [comment]
Thanks a lot for your time that solved my issue,  I was missing `indentWithTabs` option.

And Sorry for the noise.
