### ISSUE TITLE
CodeMirror.newFoldFunction is not a function

### ISSUE THREAD

**Issue by standus** [codemirror/CodeMirror#5025]
I builded new 5.30.0 on Win10 and using code: 
var foldFunc_html = CodeMirror.newFoldFunction(CodeMirror.tagRangeFinder); is error.
Addon with this function is included.
On my old version 5.19.1 was this OK.

**Comment by marijnh** [comment]
It's defined in addon/fold/foldcode.js — make sure that file is loaded, and that it is accessing the same instance of CodeMirror that your code is (bundles sometimes get confused and include multiple instances of a library).

**Comment by standus** [comment]
This addon is loaded well and in browser i see:
// Clumsy backwards-compatible interface
  CodeMirror.newFoldFunction = function(rangeFinder, widget) {
    return function(cm, pos) { doFold(cm, pos, {rangeFinder: rangeFinder, widget: widget}); };
  };
