### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by standus** [codemirror/CodeMirror#5026]
I builded new 5.30.0 on Win10 and on this line:
var countColumn = exports.countColumn = function(string, end, tabSize, startIndex, startValue)
 is error.
On my old version 5.19.1 was this OK.

**Comment by marijnh** [comment]
You appear to be trying to lode runmode.node.js in the browser. That script is intended only for node.js

**Comment by standus** [comment]
I dont using node.js. Why it worked well in 5.19.1 version?

**Comment by standus** [comment]
Where is defined exports, because I can not find it in /src? Exports is also in other addons!

**Comment by standus** [comment]
And in other words: I can not use require.js, because it will broken my javascripts loading flow.

**Comment by marijnh** [comment]
Look, this never worked, also not in 5.19. `exports` is defined by the CommonJS module system, which Node implements. You're loading a file you shouldn't be loading and I can't fix that for you.

**Comment by standus** [comment]
1.
It means that method described here:
http://codemirror.net/demo/html5complete.html
does not work anymore? 
2.
I want to manage myself what JS files are loaded.
3.
I compiled codemirror from latest GIT zip file and "exports" is not compiled with it. How to do it?

**Comment by standus** [comment]
Dont forget that on many sites and systems is impossible use require.js, it works total differently.

**Comment by standus** [comment]
So tell me what is different between 5.19 and 5.30. I just updated your code, nothing else. So problem is not at my using but at your changes. Are you agree?

**Comment by standus** [comment]
Now I made some tests:
codemirror.js v.5.30
together with modes v.5.30
together with addons v.5.19
and it works as expected.

**Comment by standus** [comment]
OK, so sorry, because before on 5.19 I never used node addon. I removed it and it works as expected.
