### ISSUE TITLE
gutterClick event after adding line-covering widget gives wrong line number

### ISSUE THREAD

**Issue by bjornhansen** [codemirror/CodeMirror#5028]
# Steps to reproduce:

1. Add a line widget to a line.
2. Position the line widget on top of the line and set the line height to be only as tall as the widget.
3. Click on the gutter of a line below the line the widget is now covering. The `gutterClick` handler will return the incorrect line. In the example below, it'll return the line above the line you clicked on.

**Codepen that illustrates the issue**: [https://codepen.io/bjornhansen/pen/EweLPM](https://codepen.io/bjornhansen/pen/EweLPM)

**Seen on**: Windows 10, Chrome 61.0.3163.100, CodeMirror 5.30.0

### Thanks for CodeMirror!

**Comment by marijnh** [comment]
Directly messing with the CSS of an editor like that isn't supported. CodeMirror keeps track of the height of each line, and if you change that, the editor will get confused. You can call `CM.refresh()` to make it update itself, but still, the things you did to DOM nodes that you don't own are likely to be overwritten again when using the editor. So you really shouldn't be doing that.
