### ISSUE TITLE
[JavaScript] Inconsistent behavior with unicode escaped variable names as function parameters

### ISSUE THREAD

**Issue by loituma-ievan-polkka** [codemirror/CodeMirror#5032]
This is an example:

```JavaScript
\u0024=>\u0024
```

The way CodeMirror handles this is inconsistent (it depends on what is typed previously). If you add `++` at the and and then remove it, the function parameter becomes blue. But, if you add `;` at the end and then remove it, the function parameter becomes black. I am pretty sure it is not supposed to behave like so.

Here is the screen recording (the latest "mode/JavaScript/javascript.js" from this repository is used):

![](https://user-images.githubusercontent.com/32232740/31596426-cb4bef7a-b242-11e7-9dff-c79fecdc55b0.gif)

**Comment by marijnh** [comment]
The JavaScript mode doesn't support `\u` escapes in identifiers. This isn't a feature that seems to be used in real code, so it's considered out of scope.
