### ISSUE TITLE
Provide optional minimap scrollbar

### ISSUE THREAD

**Issue by Meai1** [codemirror/CodeMirror#5033]
A minimap like this would be nice for scrolling, just like VSCode/monaco-editor has:

![minimap](https://user-images.githubusercontent.com/1112157/31623867-27acf6e8-b2a1-11e7-9c02-96b7b915abe9.png)

**Comment by marijnh** [comment]
That's out of scope for the main distribution, but could be written and distributed as a separate module. There's one [here](https://github.com/alex-seville/minimap), but I'm not sure it still works with the current code.
