### ISSUE TITLE
Incorrect highlighting of JavaScript with template strings after dangling comma

### ISSUE THREAD

**Issue by marcins** [codemirror/CodeMirror#5036]
I managed to find a case where template string highlighting doesn't "end" properly. Here's the minimal reproduction I was able to boil it down to (tested via https://codemirror.net/mode/javascript/index.html):

```js
fn({
  ...blah,
});

const c = `b${c.d}`;
// ^ semi-colon onwards is "red"
const d = 'foo';
```

It seems to specifically be the combo of a function call, object, destructuring and the dangling comma. Removing any of those parts the highlighting works correctly.

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch should help.

**Comment by marcins** [comment]
Thanks for the quick turnaround!
