### ISSUE TITLE
vim-mode: Unable to switch to normal mode in Firefox 57

### ISSUE THREAD

**Issue by xuhdev** [codemirror/CodeMirror#5038]
On Firefox 57, once entering "insert" mode, it is impossible to enter normal mode again (neither `Esc` nor `Ctrl-[` works). It works well on Firefox 56.

**Comment by marijnh** [comment]
I can't reproduce this in Firefox 57 Linux. Could you try to debug what's going on? I.e. is there an error in the console? What is `cmKey` in keymap/vim.js being called with when you press escape? Etc.

**Comment by xuhdev** [comment]
Hah, I found the reason is that I installed Vimium for Firefox... Thanks!

**Comment by dessalines** [comment]
This is broken again. Neither esc nor control+[ work.

**Comment by xeruf** [comment]
For me the issue was caused by Vim Vixen. Disabling it on the page was in vain, only works when I disable it completely :/
