### ISSUE TITLE
Editor cursor is buggy

### ISSUE THREAD

**Issue by lansana** [codemirror/CodeMirror#5040]
When I use any mode (including yaml mode) with YAML in the editor, the cursor is very buggy for some reason. This does not happen with JSON and javascript mode.

In the example below, you can see I click at the end of line 8, and it puts the cursor somewhere in the middle of that line. I then type a key and the key is not entered where the cursor is, but on the next line. Once that bug occurs once, everything goes back to a working state. I assume it's because the enter key was pressed and sort of refreshed everything.

Why is this happening?

![oct 19 2017 10-02 am - edited](https://user-images.githubusercontent.com/14805022/31774927-24b9e908-b4b5-11e7-8a65-0e08e287a496.gif)

**Comment by marijnh** [comment]
This is unlikely to be related to the mode. Probably, something about the layout of the editor changed (CSS change, font loading, animation) and the editor is still using outdated measurements. Call the `refresh()` method when the editor needs to re-measure its content, and mouse clicks should be properly interpreted.

**Comment by lansana** [comment]
Thanks, calling `refresh` on the editor instance solves the problem.
