### ISSUE TITLE
linting in handlebars mode

### ISSUE THREAD

**Issue by lukas1994** [codemirror/CodeMirror#5041]
Is there a way to make sure that the linting runs only in the parts of the code that are enclosed in `{{ }}`?
I'm using
```
{
  lint: true,
  mode: { name: 'handlebars', base: 'javascript' }
}
```

**Comment by marijnh** [comment]
I guess you could write a [linter function](http://codemirror.net/doc/manual.html#addon_lint) that does this, but there's no such thing in the distribution.
