### ISSUE TITLE
How to set the height （line number）？

### ISSUE THREAD

**Issue by 2013211450** [codemirror/CodeMirror#5043]
Why I only get 23 lines text in the page？
![qq 20171021163451](https://user-images.githubusercontent.com/16376959/31849983-e35055f4-b67d-11e7-9bea-ddfd1d94332d.png)

this is my setting file。
![qq 20171021163627](https://user-images.githubusercontent.com/16376959/31849998-0e6642a8-b67e-11e7-8b1c-4211266da7c5.png)

**Comment by marijnh** [comment]
Please see [the manual](http://codemirror.net/doc/manual.html#styling)
