### ISSUE TITLE
[typescript] type not highlighted in <>s

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5048]
```typescript
this.a<Type>(foo);
```
`Type` should be highlighted

**Comment by marijnh** [comment]
Are you sure that's valid TypeScript? The way I understand it, type parameters in expressions may only appear in `new` expressions. In any case, they'd be very ambiguous with less-than/greater-than operators in an expression like this—`this.a < Type > (foo)` is a valid plain-JavaScript expression.

**Comment by evmar** [comment]
This is the syntax for specifying a generic parameter to a function.  It can be useful in cases where the inferred type is wrong.  Here's a mini example (hover 'unknown' and 'maybeNumber' to see how they have different types).

https://www.typescriptlang.org/play/#src=function%20genericFirst%3CT%3E(x%3A%20T%5B%5D)%3A%20T%7Cnull%20%7B%0D%0A%20%20return%20x.length%20%3E%200%20%3F%20x%5B0%5D%20%3A%20null%3B%0D%0A%7D%0D%0A%0D%0Alet%20unknown%20%3D%20genericFirst(%5B%5D)%3B%0D%0Alet%20maybeNumber%20%3D%20genericFirst%3Cnumber%3E(%5B%5D)%3B%0D%0A

**Comment by adrianheine** [comment]
[Handbook](https://www.typescriptlang.org/docs/handbook/generics.html) confirms that. I'll push a fix.

**Comment by adrianheine** [comment]
And yes, that means that `this.a < Type > (foo);` is something different in JS than TS.

**Comment by marijnh** [comment]
Daniel Rosenwasser pointed me at the relevant [part of the spec](https://github.com/Microsoft/TypeScript/blob/6c4c10c7cf294dc71f943314e29a7dd1b6e88c6a/doc/spec.md#4.15.3) on Twitter, and patch 49065345 implements the disambiguation.
