### ISSUE TITLE
CodeMirror looks buggy on modal with latest chrome version (62)

### ISSUE THREAD

**Issue by nikuelias** [codemirror/CodeMirror#5050]
I have updated the chrome to the latest version (62) and running the Code Mirror inside a modal. It always worked that way without any problem. Now when I scroll it doesn't show properly. I'm attaching a screenshot of what I see now. It is happening me in MAC OS X High Sierra.

<img width="1002" alt="captura 2017-10-24 a la s 07 48 23" src="https://user-images.githubusercontent.com/6386008/31971904-5371726e-b8f4-11e7-8326-9da84e47245a.png">

**Comment by adrianheine** [comment]
Could you provide some example code that reproduces the issue?

**Comment by marijnh** [comment]
That looks like what CodeMirror does when it is missing its stylesheets. Could it be that codemirror.css isn't loaded?
