### ISSUE TITLE
Javascript mode: incorrect highlight of template string 

### ISSUE THREAD

**Issue by apla** [codemirror/CodeMirror#5051]
Hi,

seems like template string renders incorrectly when used in function call within constructor and `export` is misplaced:

```javascript
default export class LRWebSocketConnection extends EventEmitter {
	constructor(socket, id, options) {
		eval(`${thisName} = this;`); // not renders as a comment
	}
}
```

**Comment by adrianheine** [comment]
Thanks for your report! I doubt it makes sense reporting weird highlighting for syntactically wrong code snippets. While this could obviously be highlighted better, there will always be bad cases humans parse better than CodeMirror, and I wouldn't want to touch the highlighting code for such a thing. @marijnh Do you agree?

**Comment by marijnh** [comment]
Yes, agreed -- highlighting on invalid code isn't, generally, something we intend to precisely define.
