### ISSUE TITLE
Wrong insertion of new blank line while refocus on the editor

### ISSUE THREAD

**Issue by whxru** [codemirror/CodeMirror#5055]
I'm trying to implement the function of "Go to line" just like what will happen when you press Ctrl+G in sublime text. Here's the code will be executed after finishing the input:
```javascript
// Get the line number inputted
var input = document.getElementsByClassName("temp-input")[0];
var lineNumber = parseInt(input.value);
// Remove input element
input.parentNode.removeChild(input);
// Focus on the editor and go to line start
document.editor.focus();  // document.editor is an instance of CodeMirror
document.editor.setCursor({line: lineNumber - 1, ch: 0});
```
According to the output of console, the value of input was correct, but there would be a new blank line inserted after the expected line to go and the cursor would be at the start of the new blank. I tried to not set the cursor, then the new blank line would be inserted after the line which was focused before the editor lost focus, the cursor would be at the start of the new blank line too.

The HTML file where the instance of CodeMirror is created will be appended to an BrowserWindow in the form of <iframe> under the framework Electron. 
* Node version: 7.9.0
* Chrome version: 58.0.3029.110
* Electron version: 1.7.8

**Comment by marijnh** [comment]
I suspect the issue is with your event handler -- you're handling the enter event by moving focus to CodeMirror, but without canceling the event, which will then end up in CodeMirror itself.

**Comment by whxru** [comment]
Thanks for your reply, that's exactly what the problem is! I end up inputting line number while the key Enter pressed so that the editor will create a new blank line after executing the keydown event handler. So I added `evt.preventDefault();` at the first line of event handler and everything goes well.
