### ISSUE TITLE
[show-hint.js]:when i keypress a string like "cont" ,it looks not great.

### ISSUE THREAD

**Issue by Kelier** [codemirror/CodeMirror#5057]
in "javascript mode",when i input `var cont`,that will hint me a "continue" word,but actually i dont want that,it just  fill my blank yard automatically，if i keypress another char code , what should i do ,to avoid the appearance of "continue" ?

**Comment by Kelier** [comment]
i just want to create another variable ,like "var context"?

**Comment by marijnh** [comment]
This sounds like you're working in some editor that pops up completions by default. The way completion popups are opened isn't prescribed by the library (most of the demos use a key to open it), so this is something you'll have to take up with whoever set up your editor.

**Comment by Kelier** [comment]
i used “completeSingle” ,but it didnt work
