### ISSUE TITLE
Does CodeMirror have an ECCN?

### ISSUE THREAD

**Issue by otramony** [codemirror/CodeMirror#5062]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption. 

We noticed some references to encryption in source code within the mode directory, so we thought we should ask. Thanks.

**Comment by marijnh** [comment]
There's no encryption, and no ECCN.

**Comment by otramony** [comment]
Thank you.
