### ISSUE TITLE
trying to write code folding for my  custom grammar and i am using Require.js to load dependencies

### ISSUE THREAD

**Issue by alfrye** [codemirror/CodeMirror#5066]
I am not able to get the gutter markers to show for folding for my langauge. I have created the a mylang-fold.js that contains the rules for my grammar. I have created an sample that does not use require.js and everything seems to work but when I try to integrate it with my web application it appears the class CodeMirror-foldgutter is not being inserted into the dom elements.

**Comment by marijnh** [comment]
This doesn't sound like the problem is in the CodeMirror library. Maybe check whether your module loader isn't loading the core library twice (require.js has a tendency to do that when it's included through different paths).

**Comment by alfrye** [comment]
thanks for the quick response! Do you have examples using code mirror with require

**Comment by marijnh** [comment]
http://codemirror.net/demo/requirejs.html
