### ISSUE TITLE
5.31.0 does not include /lib/codemirror.js

### ISSUE THREAD

**Issue by kaljak** [codemirror/CodeMirror#5070]
The codemirror.js is missing in the lib/ folder in the latest release.zip. 

[README.md](/README.md) states that the index.html should work. index.html is also using lib/codemirror.js -> so it doesn't work. The manual also says that it should used from there: https://codemirror.net/doc/manual.html

How do I fix this? Thanks in advance.

**Comment by marijnh** [comment]
Don't get the zip from github. Github is not our distribution channel. Get it from the website or NPM.
