### ISSUE TITLE
[solarized][markdown] bold text in Markdown looks faint in Solarized theme.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#5075]
Looks caused by 
https://github.com/codemirror/CodeMirror/blob/master/theme/solarized.css#L90

**Comment by marijnh** [comment]
Do I understand correctly that this provides too low contrast in the _light_ variant of the theme? Would simply removing that line be an acceptable solution?

**Comment by takamori** [comment]
Ah... yes, this was in regard to the solarized light theme. Interesting; in the dark version, it seems that removing the line could theoretically make it hard to tell the difference between bold and not bold.

But it's worth noting that the dark theme example in http://ethanschoonover.com/solarized for markdown (http://ethanschoonover.com/solarized/img/screen-pandoc-dark.png) does seem to suggest that it should be possible to make a dark variant that doesn't require a color change. IIUC, the philosophy for solarized is that the foreground colors shouldn't need to change when switching between light and dark variants. It doesn't look like #eee is part of the solarized palette, though.

**Comment by takamori** [comment]
Actually, after playing with it more I'd argue it should be fine to simply remove the line.
