### ISSUE TITLE
ES6 JS linter

### ISSUE THREAD

**Issue by themre** [codemirror/CodeMirror#5077]
Hi,
I have javascript-lint added to codemirror and ES6 syntax (const, let, arrow functions) reports error. Is there a way to allow new, ES6 syntax?

**Comment by marijnh** [comment]
The linter uses JSHint internally, and allows you to reconfigure that, so sure, that should be possible.

**Comment by themre** [comment]
i noticed that I got old version od JSHint that didn't had this support. But I enabled it with this:
```
lint: {
    esversion: 6
}
```
Thanks for help!
