### ISSUE TITLE
highlightSelectionMatches is causing changing glyphs upon selection of Arabic text

### ISSUE THREAD

**Issue by nethip** [codemirror/CodeMirror#5080]
_Current Behavior_: Upon selection of Arabic text with `highlightSelectionMatches: true`, the glyphs are getting changed. Please have a look a the video below.

 

![textjump](https://user-images.githubusercontent.com/1577184/32589159-f370c972-c538-11e7-9458-9c85bcc4111e.gif)

_Expected output_: The selection should not change the glyphs.

**Comment by marijnh** [comment]
This appears to be a Chrome bug — Firefox behaves properly in this case, but Chrome renders these characters differently based on whether there's a `<span>` boundary between them. This is unlikely to be something that we can work around inside CodeMirror, so your best bet is to report the issue to the Chrome team (you can reproduce it outside of CodeMirror by adding/removing spans in such text, and noting the difference in text rendering).

**Comment by nethip** [comment]
Apologies for late reply. 

I will log a bug with the Chrome team for this. Thanks!

**Comment by nethip** [comment]
FYI: I have logged a bug with the chromium team for this. 

https://bugs.chromium.org/p/chromium/issues/detail?id=740937

**Comment by marijnh** [comment]
Thanks!
