### ISSUE TITLE
In vuejs project,codemirror format javascript code fail

### ISSUE THREAD

**Issue by coderew** [codemirror/CodeMirror#5081]
In vuejs project, i use the method to read local file,such as html,css,and javascript code

```
require("template/linkage/html.htpl");
require("template/linkage/css.htpl");
require("template/linkage/js.htpl");
```
then, i config the javascript codemirror as follows:
```
 mode: "javascript",
 lineNumbers: true,
 indentUnit: 4  
```
last, the javascript code format result as follows:

[https://segmentfault.com/q/1010000011904901](url)

https://segmentfault.com/q/1010000011904901

the html and css code format is right, but the javascript code result is not i want,i cannot find the problem,please help me.thanks

**Comment by marijnh** [comment]
Those links do not work

**Comment by adrianheine** [comment]
It does work now, but I still don't understand the exact issue. Is it about embedding JS in HTML?

**Comment by adrianheine** [comment]
There was no further feedback, so I'm closing this issue for now.

**Comment by jingyuLin1999** [comment]
I have the same issue，and I resolve it by prettier.
```js
import prettier from "prettier/esm/standalone";
import parserBabel from "prettier/esm/parser-babel.mjs";
const formatCode = prettier.format(code, {
        parser: "babel",
        plugins: [parserBabel],
});
```
