### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by hypersoft** [codemirror/CodeMirror#5082]
Steps to repeat: download release, unpack, enter directory, issue command `npm install`

Result:
![screenshot from 2017-11-09 09-42-20](https://user-images.githubusercontent.com/2527476/32614256-7be58aa6-c532-11e7-87cc-cfa2b9ebca78.png)

Remark: please provide links to pre-built-versions for users who have no interest/skills/respect for npm projects.

**Comment by marijnh** [comment]
That's a file system permission issue you have in your installation directory, not something Acorn can help.

**Comment by hypersoft** [comment]
No, it is not. Quite simply, we do not have the same setup.

I suppose you cannot read because ../acorn/bin/acorn DOES NOT EXIST.

Furthermore:
![screenshot from 2017-11-09 10-06-52](https://user-images.githubusercontent.com/2527476/32615654-e3be7112-c535-11e7-9e33-9e2d05d14fae.png)

[you are an asshole] Please provide links to the pre-built-version, or KINDLY, build one for me.

**Comment by dwaltrip** [comment]
> I suppose you cannot read...
> [you are an asshole]

Please don't do this... Would you want to help someone who makes comments like this to a project you've spent thousands of hours on?

Just because you can't see the other person through your computer screen doesn't mean that they aren't there.
