### ISSUE TITLE
CodeMirror mode run with incorrect state

### ISSUE THREAD

**Issue by JoelEinbinder** [codemirror/CodeMirror#5086]
I have a mode that counts line numbers in its state. Sometimes CodeMirror runs my mode in the middle with the startState when syntax highlighting for measuring the longest line. It looks this is intentional for performance reasons.

Possible solutions:
* If CodeMirror gave me the line number so I could recover on my end.
* If there was an option to get CodeMirror to ignore syntax highlighting for measuring
* If startState got lineNumber passed into it
* If there was an option to always syntax highlight precisely

**Comment by marijnh** [comment]
Modes are intentionally not given information about line numbers and the rest of the document. This is used for several optimizations—by knowing exactly what the mode state depends on, without leaking in further information, it can be reused. This isn't going to change—doing line number-dependent things will have to be done outside of modes.

**Comment by JoelEinbinder** [comment]
I understand why things are how they are, but it is unfortunate that syntax highlighting isn't deterministic.
