### ISSUE TITLE
CodeMirror not building

### ISSUE THREAD

**Issue by TJonesy** [codemirror/CodeMirror#5091]
I downloaded CodeMirror-5.31.0 and extracted it.  Then I entered the root directory of the project ~/CodeMirror-5.31.0/ Once there I ran `npm build` and `npm install` but there is still no codemirror.js file in the lib directory ~/CodeMirror-5.31.0/lib/ Am I doing something wrong or is there an issue with the project?  I am running Ubuntu 17.04 with NodeJS v6.12.0.  There is no errors and best I can tell it runs successfully.

**Comment by adrianheine** [comment]
What was the output of running `npm install` and `npm run build`? Note that you have to run them in that order.

**Comment by TJonesy** [comment]
Npm install showed some output about installing phantomjs but no errors.
npm build didn't give any output.  If I run then again they dont give any
output.

**Comment by adrianheine** [comment]
There has to be some output of `npm run build`. What's the output of `npm -v`?

**Comment by zhaojq-github** [comment]
run **npm install** and **npm run build**, not **npm build**

**Comment by TJonesy** [comment]
Running npm run build did work.  It would be good if you added that to the readme.

**Comment by adrianheine** [comment]
That's just the way [npm works](https://docs.npmjs.com/cli/build).
