### ISSUE TITLE
Scala and Swift support nested comments

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#5096]
In both Scala and Swift modes:

```scala
/*
  /* this is a nested comment */
  this is commented in Github, but not CodeMirror
*/
```

Is there a bit to flip in these modes that's easy to turn on?

**Comment by marijnh** [comment]
> Is there a bit to flip in these modes that's easy to turn on?

No, you'd have to adjust their block-comment tokenizers to track comment depth.

**Comment by adrianheine** [comment]
I just verified that Scala and Swift indeed support nested block comments, curious. Are there any other languages (in CodeMirror) that do that?

**Comment by vincentwoo** [comment]
Yup, at least one: https://github.com/codemirror/CodeMirror/issues/3878

**Comment by adrianheine** [comment]
a7e29eee89aed63727e46d1e422cfa95b1200859 and ff21fec1 :)

**Comment by vincentwoo** [comment]
Thanks so much, Adrian.
