### ISSUE TITLE
Prevent parent scrolling

### ISSUE THREAD

**Issue by parraman** [codemirror/CodeMirror#5097]
Dear all,

Is there a way to prevent the scrolling of the whole page (i.e. parent scrolling) when the last line of the code editor is reached? I am using the default editor preferences, but I have seen that behavior with all the scrollbar modes: when I reach the end of the text and keep scrolling down, the whole page starts to scroll down. I do not wish to disable body scrolling, not even on mouse-over, because I do not want the body scrollbars to appear and disappear out of the blue.

Thank you very much in advance!

Best regards,

Pablo.

**Comment by marijnh** [comment]
What kind of scrolling are you talking about? If this is about wheel scrolling, that's just how browsers act—if the pointer is over a scrollable container that's scrolled to the very end, its next scrollable parent is scrolled.

**Comment by parraman** [comment]
Yes, I was talking about wheel scrolling. I was wondering if there was some
sort of option or setup that prevented the event from being propagated if
the editor was scrolled to the end.

**Comment by marijnh** [comment]
You can add your own wheel event handler to do that. CodeMirror itself doesn't do it.
