### ISSUE TITLE
In search.html demo, setting the openDialog of closeOnBlur is false, Esc will has some error

### ISSUE THREAD

**Issue by soulxy** [codemirror/CodeMirror#5098]
I want that persistent search(Alt-F)  is not closed when input loses focus, then I set `closeOnBlur` false.
  Unfortunately, when search input lose focus, new `CodeMirror-dialog` always  appends to cm by using Alt-F again, then shortcut Esc doesnot work.

**Comment by marijnh** [comment]
That's not a feature that our search dialog supports—you'll have to write your own if you need it.
