### ISSUE TITLE
<%-- --%> JSP and ASP comments are not getting recognized as comments

### ISSUE THREAD

**Issue by nethip** [codemirror/CodeMirror#5102]
**Problem:**

Text under `<%-- --%>` are not getting recognized as comments for JSP and ASP files. This is because of the fact that `blockComments` are mapped to `<!-- --!>`. But unfortunately we can't define multiple `blockComments` type, while defining a language mode. 

**Expected**

Comments under `<%-- --%>` as well as under `<!-- -->` should be recognized as comments. 

We are adding a new language mode as the following.

```
        "name": "HTML",
        "mode": ["htmlmixed", "text/x-brackets-html"],
        "fileExtensions": ["html", "htm", "shtm", "shtml", "xhtml", "cfm", "cfml", "cfc", "dhtml", "xht", "tpl", "twig", "kit", "aspx", "ascx", "asp", "master", "cshtml", "vbhtml"],
        "blockComment": ["<!--", "-->"]
    
```
And we are defining the MIME type `text/x-brackets-html` to be

```
CodeMirror.defineMIME("text/x-brackets-html", {
        "name": "htmlmixed",
        "scriptTypes": [
            {
                "matches": /\/x-handlebars|\/x-mustache|\/ng-template$|^text\/html$/i,
                "mode": "htmlmixed"
            },
            {
                "matches": /^text\/(babel|jsx)$/i,
                "mode": "jsx"
            }
        ]
    });
```
Is there any easy way to make `cm` recognize multiple block comments?

**Comment by marijnh** [comment]
I assume you're talking about uncommenting such comments? The comment plugin currently doesn't support this. One option would be to add an extra field, say `additionalBlockComments`, containing and array of `{open, close}` objects, and have the comment plugin scan for those as well when uncommenting. I don't, off the top of my head, know of any language with multiple line comment syntaxes, but I guess that might come up in the future as well.

**Comment by nethip** [comment]
@marijnh It is about recognizing multiple types of block comments. In JSP, a comment could be `<!-- -->` or `<%-- --%>`. Please refer to the example below. There are two types of comments used.

```
<%@ taglib uri="/WEB-INF/tld/org.tld" prefix="TheOrg" %>
<%@ taglib uri="/WEB-INF/tld/portal.tld" prefix="wps" %>
<%@ taglib uri="/WEB-INF/tld/portal-content-ext.tld"  prefix="content" %>
<%@ taglib uri="/WEB-INF/tld/engine.tld" prefix="wp" %>


<div id="grid">
			<div class="grid grid_24">
				<div id="productNav">
					<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas maiores, in aliquid provident ab cupiditate laudantium. Voluptas, numquam voluptates error minus dolorem hic nemo? Reprehenderit veniam ratione magnam beatae id.</h2>
                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed quibusdam accusamus sunt alias facilis earum voluptate enim, quia sint facere deserunt hic, culpa nam odio. Accusantium et repudiandae amet dolor.</p>
                    
                    <!-- The below <p></p> should be greyed out similar to this comment --> 
<%--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, odit, nulla. Et similique fugit vero, enim minima laborum accusamus, obcaecati atque magni illum reiciendis optio, consequatur nihil fuga sed numquam.</p>--%>
					
				</div>
			</div>
</div>
```

**Comment by marijnh** [comment]
Ah, I see what you mean now. Try with attached patch.

**Comment by nethip** [comment]
Thanks @marijnh I will validate the fix.

**Comment by nethip** [comment]
Awesome! I just validated the fix it is working. Thanks for the quick turnaround. Can you tell us when is the next release of CodeMirror planned, so that we can update our dependencies to be pointing to the new release?

**Comment by adrianheine** [comment]
@nethip Marijn tries to publish one release per month towards the end of the month. The last one was 13 days ago, so I would expect him to publish one in 2–3 weeks.

**Comment by nethip** [comment]
Thanks @adrianheine for the information. We will plan our integration accordingly.
