### ISSUE TITLE
`cmd+shift+up` and `cmd+shift+down` broken on OS X

### ISSUE THREAD

**Issue by tbertelsen** [codemirror/CodeMirror#5109]
Hi There.

Firsts of all, thanks for making a great editor :).

I've noticed a problem with the Sublime Keymap. The functionality of `cmd+shift+up` and `cmd+shift+down` recently broke on OS X.

Current behavior in CodeMirror.

 - `cmd+shift+up` Add cursor above
 - `ctrl+shift+up` Add cursor above
 - `cmd+shift+down` Add cursor below
 - `ctrl+shift+down` Add cursor below

Behavior in Sumblime text and desired behavior in CodeMirror.

 - `cmd+shift+up` Select text from start of file to cursor
 - `ctrl+shift+up` Add cursor above
 - `cmd+shift+down` Select text from cursor to end of file
 - `ctrl+shift+down` Add cursor below

[Sublime text documentation](https://www.sublimetext.com/docs/2/multiple_selection_with_the_keyboard.html)

# Testing

 1. Go to http://codemirror.net/demo/sublime.html
 2. Put the cursor somewhere.
 3. Press `cmd+shift+up` or `cmd+shift+down`
 4. Press `ctrl+shift+up` or `ctrl+shift+down`

Notice how the commands has the same effect. If "Mission Control" conflicts with the hotkeys, see [this stackoverflow question](https://apple.stackexchange.com/questions/24343/how-do-i-disable-the-controlshiftdown-arrow-hotkey)

Tested on OS X 10.12.6 using Chrome v.62 and Safari v.11.0.1

# Cause

I believe the problem was introduce by [this change](https://github.com/codemirror/CodeMirror/commit/3073bdd97a4e55c3fa8c69ecbabdc18c4dd0b3a7). Interesting that change also introduces the function `addCursorToSelection` which seems to be solve the same problem as `cmds.selectLinesUpward` and `selectLinesDownward`.

I propose we revert that change, since

 - The `shift-cmd` command for mac is inconsistent with the Sublime Text behavior on mac, and it prevents the user from selecting to the start/end of page.
 - The `alt-ctrl` command for windows is already specified [on line 536](https://github.com/codemirror/CodeMirror/blob/3073bdd97a4e55c3fa8c69ecbabdc18c4dd0b3a7/keymap/sublime.js#L536)

**Comment by adrianheine** [comment]
@dwelle since you were part of the discussion in #4850, could you have a look at this as well?

**Comment by mtaran-google** [comment]
Thanks for writing up the great repro case + explanation, Tobias. It looks like the main issue in #4850 was that the existing selectLinesUpward/Downward has a slightly different behavior, in that the earlier implementation goes by *logical* lines whereas the new one (and Sublime's) goes by *visual* lines. Since the latter behavior matches Sublime's, I would say it should be the only one retained (at the proper shortcut).

**Comment by dwelle** [comment]
@adrianheine unfortunately I'm on Windows and don't have access to a mac machine, so can't add much to this discussion, If I understood it correctly.

WTBS (/c @mtaran-google) is OP talking about the logical/visual lines at all? I understood that this issue is only related to key mapping.

**Comment by tbertelsen** [comment]
@dwelle: You are correct. This is not about visual vs. logical lines, but about the keymap.

To recap. Please confirm, that this is what we want to do.

# Mac

We currently have this:

```
    "Ctrl-Shift-Up": "selectLinesUpward",
    "Ctrl-Shift-Down": "selectLinesDownward",
    "Shift-Cmd-Up": "addCursorToPrevLine",
    "Shift-Cmd-Down": "addCursorToNextLine",
```

  - First two use logical lines
  - Last two use visual lines

We want this (which matches sublime text)

```
    "Ctrl-Shift-Up": "addCursorToPrevLine",
    "Ctrl-Shift-Down": "addCursorToNextLine",
```

# Windows

We currently have this

```
    "Alt-CtrlUp": "addCursorToPrevLine", 
    "Alt-CtrlDown": "addCursorToNextLine",
    "Ctrl-Alt-Up": "selectLinesUpward",
    "Ctrl-Alt-Down": "selectLinesDownward",
```

 - I assume the first two are broken, since it is missing `-` after `Ctrl`.

We want 

```
    "Ctrl-Alt-Up": "addCursorToPrevLine",
    "Ctrl-Alt-Down": "addCursorToNextLine",
```

# Cross-platform

We want to 

 - Delete `selectLinesUpward` `selectLinesdownward`

**Comment by mtaran-google** [comment]
I similarly don't have access to a windows machine but http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_win.html agrees with your keybindings.

Though on linux, the sublime bindings for these actions are alt+shift+up/down. Since the "PC" keybindings are also used for Linux (and those bindings are otherwise unused in the CM sublime PC keymap), would you be opposed to including them as well?

**Comment by tbertelsen** [comment]
I created https://github.com/codemirror/CodeMirror/pull/5117
I just edited the file in the browser, since I don't know how you do testing/QA. Someone who knows should probably verify that it works and don't break things.

**Comment by nickasd** [comment]
This should be fine. Just wondering if your change will restore the "Select text from start of file to cursor" behaviour you described at the beginning, since the `cmd+shift+up` shortcut was removed?

**Comment by mtaran-google** [comment]
I think it should. Haven't tested. If it doesn't, will follow up.

**Comment by tbertelsen** [comment]
Thanks @mtaran-google for helping. I've been quite busy the last couple of days.
I believe the `cmd+shift+up` will be caught be the fall through. It is a standard OS X keybinding.

**Comment by adrianheine** [comment]
Thanks for your work, everyone :)

**Comment by tbertelsen** [comment]
Yeah, Thank you everyone for your help :)
