### ISSUE TITLE
[vim mode] increment/decrement ignores base

### ISSUE THREAD

**Issue by wsweyerman** [codemirror/CodeMirror#5110]
In vim, using <C-a> to increment or <C-x> to decrement it understands the base (0bnn for binary, 0nn for octal, 0xnn for hexadecimal). The vim mode increment and decrement treat everything as decimal and drop leading zeros:

examples:
0b001 -> 0b2
07 -> 8
0x00f -> 0x1f if cursor is on either 0, no effect otherwise

all of these examples work as expected in vim:
0b001 -> 0b010
07 -> 010
0x00f -> 0x010

**Comment by adrianheine** [comment]
Please have a look at current master.
