### ISSUE TITLE
not possible to round-trip contents with unknown line terminators

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5112]
1. codemirror.net
2. `editor.setValue('foo\r\nbar\r\n'); JSON.stringify(editor.getValue())`

expected:
`"foo\r\nbar\r\n"`

actual:
`"foo\nbar\n"`

An editor should not corrupt contents written to and read from it, or should at least provide some combination of settings to avoid such corruption.

**Comment by marijnh** [comment]
The setting you're looking for is [`lineSeparator`](http://codemirror.net//doc/manual.html#option_lineSeparator). When that's set, it will no longer normalize anything that looks like a line separator to `\n`. That also means that the `\r` character will show up in the actual document.

**Comment by mtaran-google** [comment]
Passing that option does appear to work if you use a full CodeMirror. But we use a CodeMirror.Doc and give that a value (and then potentially attach linked docs to multiple CodeMirror views of the same file). There is no documented way to set the line separator on a Doc, though it appears that just doing `doc.lineSep = '\n'` after construction does the right thing.

Can you please describe this workaround in the manual? Or provide a real API for this use case?

**Comment by mtaran-google** [comment]
Actually, no. What I would need to do to work around this right now is to create a doc with '' content, then set the line sep, then set the actual content I wanted in there, and then clear the history so it's not randomly polluted. This really needs an actual API.

**Comment by adrianheine** [comment]
`lineSep` is a constructor argument for `Doc`. Would using that work?

**Comment by marijnh** [comment]
> This really needs an actual API.

I assume setting the document to be empty first and then updating it was intended to work around the fact that you couldn't set the line separator right away? It is, as @adrianheine pointed out, an argument to the constructor. Attached patch documents it. Does that help?

**Comment by mtaran-google** [comment]
Thanks, that does work!

Though BTW now the next sentence in the docs isn't correct: "The last two arguments are optional and can be used to set a mode for the document and make it start at a line number other than 0, respectively.", but there are three optional params etc.

**Comment by adrianheine** [comment]
I think we are done here :)
