### ISSUE TITLE
Problem highlighting OCaml code

### ISSUE THREAD

**Issue by cprieto** [codemirror/CodeMirror#5113]
We found some issues when highlighting OCaml code, especially with:

 * Some number literals (hex, binary, exponential floats)
 * Bracket string literals
 * Some reserved words (sig, module)
 
You can see a working example with current CodeMirror version at http://jsbin.com/yutewuwafa/edit?html,js,output

**Comment by marijnh** [comment]
Want to take a look at the ocaml mode's source and see if you can fix these?

**Comment by cprieto** [comment]
Sure, I am already on it.

**Comment by marijnh** [comment]
Fixed via #5116
