### ISSUE TITLE
how to create a mode for RPGILE completely free

### ISSUE THREAD

**Issue by FedeHerrera10** [codemirror/CodeMirror#5114]

**Comment by FedeHerrera10** [comment]
// CodeMirror, copyright (c) by Marijn Haverbeke and others
// Distributed under an MIT license: http://codemirror.net/LICENSE

/**
 * Author: Federico Herrera
 * 
 */
(function(mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
    mod(require("../../lib/codemirror"));
  else if (typeof define == "function" && define.amd) // AMD
    define(["../../lib/codemirror"], mod);
  else // Plain browser env
    mod(CodeMirror);
})(function(CodeMirror) {
"use strict";

CodeMirror.defineMode("rpg", function () {
  var BUILTIN = "builtin", COMMENT = "comment", STRING = "string",
      ATOM = "atom", NUMBER = "number", KEYWORD = "keyword", MODTAG = "header",
      COBOLLINENUM = "def", PERIOD = "link";
  function makeKeywords(str) {
    var obj = {}, words = str.split(" ");
    for (var i = 0; i < words.length; ++i) obj[words[i]] = true;
    return obj;
  }
  var atoms = makeKeywords("TRUE FALSE ZERO ");
  var keywords = makeKeywords(
      "\/ COPY \/ FREE \/ END-FREE " +
	  "\% ABS \% ADDR \% ALLOC \% BITAND \% BITNOT \% BITOR \% BITXOR \% CHAR \% CHECK \% CHECKR \% DATE \% DAYS \% DEC " +
	  "\% DECH \% DECPOS " +
	  "\% DIFF \% DIV \% EDITC \% EDITFLT \% EDITW \% ELEM \% EOF \% EQUAL \% ERROR \% FIELDS \%FLOAT  " +
	  "\% FOUND \% GRAPH \% HANDLER \% HOURS \% INT \% INTH \% KDS \% LEN \% LOOKUP \% MINUTES \% MONTHS "+
	  "\% MSECONDS \% NULLIND \% OCCUR \% OPEN \% PADDR \% PARMS \% REALLOC \% REM \% REPLACE \% SCAN " +
	  "\% SECONDS \% SHTDN \% SIZE \% SQRT \% STATUS \% STR \% SUBARR \% SUBDT \% SUBST \% THIS \% TIME " +
	  "\% TIMESTAMP \% TLOOKUP \% TRIM \% TRIML \% TRIMR \% UCS2 \% UNS \% UNSH \% XFOOT \% XLATE \% XML \% YEARS " +
	  "ACQ ADD ADDDUR ALLOC AND BEGSR BITOFF BITON CALL CALLB CALLP CAT CHAIN CHECK CHECKR CLEAR CLOSE COMMIT " +
	  "COMP DEALLOC DEFINE DELETE DIV DO DOU DOW DSPLY DUMP ELSE ELSEIF ENDyy ENDSR EVAL EVALR EVAL-CORR EXCEPT" +
	  "EXFMT EXSR EXTRCT FEOD FOR FORCE GOTO IF IN ITER KFLD KLIST LEAVE LEAVESR LOOKUP MAIN MHHZO MHLZO MLHZO MLLZO " +
	  "MOVE MOVEA MOVEL MULT MVR NEXT OCCUR ON-ERROR OPEN OR OPTION OTHER OUT PARM PLIST POST READ READC READE READP READPE "+
	  "REALLOC REL RESET RETURN ROLBK SCAN SELECT SETGT SETLL SETOFF SETON SHTDN SORTA SQRT SUB SUBDUR SUBST TAG TEST "+
	  "TESTB TESTN TESTZ TIME UNLOCK UPDATE WHEN WRITE XFOOT XLATE XML-INTO XML-SAX Z-ADD Z-SUB CHAR VARCHAR BINDEC FLOAT "+
	  "INT PACKED UNS ZONED GRAPH UCS2 DATE TIME TIMESTAMP OBJECT POINTER IND DCL-S DCL-C DCL-DS DCL-F DCL-PI DCL-PR CTL-OPT END-DS "+
	  "DCL-PROC END-PROC EXEC SQL ENDIF ENDDO NOT BNDDIR USAGE"
	   );
 
  var builtins = makeKeywords("- * ** / + < <= = > >= ");
  var tests = {
    digit: /\d/,
    digit_or_colon: /[\d:]/,
    hex: /[0-9a-f]/i,
    sign: /[+-]/,
    exponent: /e/i,
    keyword_char: /[^\s\(\[\;\)\]]/,
    symbol: /[\w*+\-]/
  };
  function isNumber(ch, stream){
    // hex
    if ( ch === '0' && stream.eat(/x/i) ) {
      stream.eatWhile(tests.hex);
      return true;
    }
    // leading sign
    if ( ( ch == '+' || ch == '-' ) && ( tests.digit.test(stream.peek()) ) ) {
      stream.eat(tests.sign);
      ch = stream.next();
    }
    if ( tests.digit.test(ch) ) {
      stream.eat(ch);
      stream.eatWhile(tests.digit);
      if ( '.' == stream.peek()) {
        stream.eat('.');
        stream.eatWhile(tests.digit);
      }
      if ( stream.eat(tests.exponent) ) {
        stream.eat(tests.sign);
        stream.eatWhile(tests.digit);
      }
      return true;
    }
    return false;
  }
  return {
    startState: function () {
      return {
        indentStack: null,
        indentation: 0,
        mode: false
      };
    },
    token: function (stream, state) {
      if (state.indentStack == null && stream.sol()) {
        // update indentation, but only if indentStack is empty
        state.indentation = 6 ; //stream.indentation();
      }
      // skip spaces
      if (stream.eatSpace()) {
        return null;
      }
      var returnType = null;
      switch(state.mode){
      case "string": // multi-line string parsing mode
        var next = false;
        while ((next = stream.next()) != null) {
          if (next == "\"" || next == "\'") {
            state.mode = false;
            break;
          }
        }
        returnType = STRING; // continue on in string mode
        break;
      default: // default parsing mode
        var ch = stream.next();
        var col = stream.column();
        if (ch == "/") {			// comment
		  if(stream.eat("/"))
		  {
		   stream.skipToEnd(); // rest of the line is a comment
           returnType = COMMENT; 
		  }
		  else returnType=KEYWORD;
        } else if (ch == "\"" || ch == "\'") {
          state.mode = "string";
          returnType = STRING;
        } else if (ch == "'" && !( tests.digit_or_colon.test(stream.peek()) )) {
          returnType = ATOM;
        } else if (ch == ".") {
          returnType = PERIOD;
        } else if (isNumber(ch,stream)){
          returnType = NUMBER;
        } else {
          if (stream.current().match(tests.symbol)) {
            while (col < 76) {
              if (stream.eat(tests.symbol) === undefined) {
                break;
              } else {
                col++;
              }
            }
          }
          if (keywords && keywords.propertyIsEnumerable(stream.current().toUpperCase())) {
            returnType = KEYWORD;
          } else if (builtins && builtins.propertyIsEnumerable(stream.current().toUpperCase())) {
            returnType = BUILTIN;
          } else if (atoms && atoms.propertyIsEnumerable(stream.current().toUpperCase())) {
            returnType = ATOM;
          } else returnType = null;
        }
      }
      return returnType;
    },
    indent: function (state) {
      if (state.indentStack == null) return state.indentation;
      return state.indentStack.indent;
    }
  };
});

CodeMirror.defineMIME("text/x-rpg", "rpg");

});

**Comment by FedeHerrera10** [comment]
**this is the js code for the rpg mode**

**Comment by adrianheine** [comment]
Hi. We're no longer accepting new modes into the main distribution. The recommended way to distribute new modes is to maintain them in their own repository and publish them to NPM as separate packages—see for example the [Elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir).
