### ISSUE TITLE
[ts] highlighting of `` strings leaks

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5118]
```ts
function foo(a) {
  bar({`baz ${a[0]}...`});
}
```
https://codemirror.net/mode/javascript/typescript.html

**Comment by adrianheine** [comment]
The JavaScript mode has the same problem, I'll have a look.

**Comment by adrianheine** [comment]
I couldn't find any syntactically valid example for this issue, neither TypeScript nor JavaScript.

**Comment by marijnh** [comment]
Indeed, the example isn't syntactically valid, and if you fix it (add a property name before the string) the problem goes away.

**Comment by mtaran-google** [comment]
Indeed, I can't get it to repro with the final code either. It looks like the syntax highlighting was only broken when my code was also in an intermediate/broken state. Sorry for the noise.
