### ISSUE TITLE
Performance issue in Autoresize demo

### ISSUE THREAD

**Issue by IanWang** [codemirror/CodeMirror#5120]
## Steps to reproduce
- go to [this demo page](https://codemirror.net/demo/resize.html)
- copy a random long text, you can just use [this](https://raw.githubusercontent.com/codemirror/CodeMirror/master/keymap/sublime.js)
- paste it to the editor on the demo page
- hold `delete` or try to type anything, you should be able to feel the delay

**Comment by marijnh** [comment]
This is expected behavior — if you turn off the lazy rendering that uses the editor's scrolling viewport, performance for large documents will degrade.
