### ISSUE TITLE
how to specify where cursor goes during a replaceRange?

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5121]
We've run into this issue:

1. Open codemirror.net
2. Place cursor on the last line, las column in the document
3. Try to automatically insert a newline at the end of the doc, with `editor.replaceRange('\n', {line: 7}, {line: 7})`

Expected:
The cursor stays where it was, but the newline gets inserted after it.

Actual:
The newline gets inserted and the cursor goes down with it.

I don't see any way to effectively configure this behavior. Is there something I'm missing?

**Comment by marijnh** [comment]
> I don't see any way to effectively configure this behavior. Is there something I'm missing?

Nope, `replaceRange` (and more generally any kind of change) will move the selection forward when it's in or on the boundaries of the change. You could work around this by resetting the selection after the change (if it changed at all).
