### ISSUE TITLE
Addon: Selected text does not respect line padding

### ISSUE THREAD

**Issue by weary-adventurer** [codemirror/CodeMirror#5122]
Any way to apply the selection style to a part of the line, but not to the text itself?

Expected result:
![expected](https://user-images.githubusercontent.com/30081929/33789728-d367f12c-dc8b-11e7-93c5-f16d3f8a03ba.PNG)

Current result:
![got](https://user-images.githubusercontent.com/30081929/33789715-c00a3248-dc8b-11e7-8272-b7ff5fe4c9c0.PNG)

**Comment by weary-adventurer** [comment]
Native selection works, but it selects the whole line:
![image](https://user-images.githubusercontent.com/30081929/33790054-0f87c84c-dc8e-11e7-8c10-f3c3ff54b53b.png)

**Comment by marijnh** [comment]
You can use `markText` to style pieces of text. That's all this library supports.
