### ISSUE TITLE
Syntax highlighting within ES6 template strings

### ISSUE THREAD

**Issue by nickvorie** [codemirror/CodeMirror#5124]
### Description

Is it possible to apply syntax highlighting (in my case HTML) to ES6 template strings? Take for example, an angular 1.x component file:

```
(function () {
    "use strict";
    
    angular.module("app").component("example", {
        template: `
            <div layout="row" layout-align="end center">
                <md-button class="md-raised md-default">Cancel</md-button>
                <md-button class="md-raised md-primary">Submit</md-button>
            </div>
        `,
        
        controller: function () {
            var ctrl = this;
        }
    });
})();
```

Relevant issue on the Atom GitHub: https://github.com/TypeStrong/atom-typescript/issues/818

**Comment by adrianheine** [comment]
That's highly specific to your use-case, but should be possible with nested modes. You could have a look at the JSX mode for inspiration.
