### ISSUE TITLE
JavaScript: input invalid syntax code, chrome crash

### ISSUE THREAD

**Issue by fuyb** [codemirror/CodeMirror#5126]
Chrome:  Version 61.0.3163.100 (Official Build) (64-bit)
Javascript code: for() { 
codeMirror Version: 5.26.0

**Comment by adrianheine** [comment]
Well, that would be a Chrome bug. I don't have that version at hand, so I cannot try to reproduce it, but I doubt that Chrome would contain such a blatant bug in a released version. In any case, there's nothing we can do about it.

**Comment by marijnh** [comment]
It might be that 'chrome crash' is referring to an infinite loop in the JS code. But I can't reproduce this in Chrome 62, so I'm going to leave it closed until further information comes in.
