### ISSUE TITLE
When smartindent and autoCloseTags are enabled, the indentation gets incorrect for some cases.

### ISSUE THREAD

**Issue by sobisht** [codemirror/CodeMirror#5130]
1. Go to http://codemirror.net/demo/closetag.html
2. Insert the code below
3. Place the cursor after <div
4. Add the missing >

```
<html>
  <body>
    	<div
  </body>
</html>
```
Result:
The </div> closing tag gets outdented.

Expected:
The </div> closing should have same indentation as <div> opening tag.

The reason for this behavior is because in indentLine (xml.js), it considers indentation of parent (<body>) for indenting </div> closing tag rather than indentation corresponding opening tag <div>

**Comment by marijnh** [comment]
The indentation of the close tag is correct, by the mode's indentation rules. The issue is that the opening tag isn't indented properly. I don't think that's an issue with the addon.

**Comment by sobisht** [comment]
I have added gifs of behaviour of VS Code, Sublime Text and CodeMirror.

VS Code:

![vsindentsample](https://user-images.githubusercontent.com/29909810/34142051-16163930-e4ab-11e7-9b1d-4c24c8edfb82.gif)


Sublime Text:

![sublimeindentsample](https://user-images.githubusercontent.com/29909810/34142091-4674969e-e4ab-11e7-89e4-5757e6e18b0b.gif)


CodeMirror:

![codemirrorindentsample](https://user-images.githubusercontent.com/29909810/34142101-50247448-e4ab-11e7-88a1-e67971532847.gif)


As can be seen, while auto indenting, VS Code and Sublime Text also uses the previous indentation for indentation in new line.
While in case of Codemirror, it considers the indenation of parent tag for indentation in new line.
