### ISSUE TITLE
Annotations are not highlighted in groovy

### ISSUE THREAD

**Issue by AlexCzar** [codemirror/CodeMirror#5132]

**Comment by adrianheine** [comment]
Hi, I don't know any Groovy. Could you give a small sample and explain what you'd expect?

**Comment by AlexCzar** [comment]
```groovy
@Component
public class SomeComponent {
    @RequestMapping(method = GET)
    def getRequest(@RequestParam("getParam") String getParam, @RequestParam(name="otherParam", defaultValue="10" int someInteger)) {
    }
}
```

`@Component`, `@RequestMapping`, `@RequestParam` here are examples of annotation is an annotation (meta-programming feature). CodeMirror does not highlight it in any way.
In the example `@Component` does not have parameters, `@RequestMapping` has one named parameter (`method`), 1st request param has one unnamed param (default parm name is `value`) `@RequestMapping`, second request param has two named parameters.
Parameters' values can be any language variables, types and literals.

**Comment by marijnh** [comment]
> CodeMirror does not highlight it in any way.

If I go to http://codemirror.net/mode/groovy/ and paste that example code, all the annotation names are highlighted as `meta` tokens. Am I missing something?

**Comment by AlexCzar** [comment]
@marijnh hm... you're right, seems like it was some misconfiguration on my side. feel free to close this issue. I can't debug it at the moment anyway, we've had to abandon codemirror anyway due to some other out-of-scope considerations.

**Comment by adrianheine** [comment]
Ok, sorry to hear that. Good luck with your project, though!

**Comment by AlexCzar** [comment]
@adrianheine it is not codemirror's fault, or else I would've filed an issue :) So don't be :)
