### ISSUE TITLE
Cannot read property 'first' of undefined

### ISSUE THREAD

**Issue by dcolumbus** [codemirror/CodeMirror#5134]
The CodeMirror library is causing issues within all browsers while implemented with WordPress' Customizer:

`codemirror.js?ver=1.5:185 Uncaught TypeError: Cannot read property 'first' of undefined`

Is there a solution for this? I've spent far too much time researching this mystery, as it plagues several of my websites.

**Comment by marijnh** [comment]
This is not enough information for us to do anything with. Can you reproduce the issue outside of WordPress? Which calls cause it?

**Comment by ronyland** [comment]
I have the same problem.
Uncaught TypeError: Cannot read property 'first' of undefined
    at new Display (codemirror.js:353)
    at new CodeMirror$1 (codemirror.js:7783)
    at CodeMirror$1 (codemirror.js:7771)
    at Function.fromTextArea (codemirror.js:9576)
    at untitled.html:27

**Comment by ronyland** [comment]
I know why.because of your tag is not "textarea"

**Comment by adrianheine** [comment]
I'm closing this until there's more information.
