### ISSUE TITLE
From 5.21.0 to 5.32.0, CodeMirror doesn't work

### ISSUE THREAD

**Issue by GitbyWe** [codemirror/CodeMirror#5136]
Hello,
Now, I'm using the ` 5.21.0` of CodeMirror bu when I try to pass (update) to `5.32.0`, the editor doesn't work.
I need help please.

Thanks in advance.

**Comment by marijnh** [comment]
Sorry, but 'doesn't work', without further information, is not a bug report. The editor is working for thousands of other users, so the problem is not obvious.

**Comment by GitbyWe** [comment]
But I don't know why. In `5.21.0`, I use JavaScript, HTML and CSS mode and a dozen of latest version of CodeMirror widgets. All work normaly but if I try to swipe to the latest version of `codemirror.js` like that everything will be up to date, It's like nothing is downloaded, so nothing work.
But there is:
````
CodeMirror.fromTextArea(document.getElementById("myTextareaCode"), editorParams)
````
in my code.
