### ISSUE TITLE
dom range object in codemirror crash

### ISSUE THREAD

**Issue by johnsoncheg** [codemirror/CodeMirror#5139]
Hi, when I try to select a paragraph in codemirror and I want to get the range object, but it seems that the range object is perform weird, I can not get the range coordinate relative to the window, always (0, 0)。the range invoke `toString` method print nothing。I think it's unreasonable。
I guess that codemirror has do something to the window range object。
![image](https://user-images.githubusercontent.com/12552574/34251337-bc8f80ac-e67a-11e7-94a4-d8701ce15c23.png)

![image](https://user-images.githubusercontent.com/12552574/34251370-d57052ea-e67a-11e7-8292-9bd9dfad451a.png)

**Comment by marijnh** [comment]
CodeMirror's visible selection isn't the DOM selection (unless you turn on contentEditable-mode), so that's where the confusion comes from.

**Comment by johnsoncheg** [comment]
I pass the `inputStyle` to the cm constructor, it's still not work 
￼
￼￼
![image](https://user-images.githubusercontent.com/12552574/34252745-d2bb4cda-e67f-11e7-8b18-ca4bca6c8ffb.png)

**Comment by johnsoncheg** [comment]
it's work, thks
