### ISSUE TITLE
How to duplicate a line with CodeMirror? Shortcut?

### ISSUE THREAD

**Issue by q2apro** [codemirror/CodeMirror#5141]
Using codemirror for long, I am still missing the shortcut to duplicate a line. CTRL+D would do it, but it does not work. 

What's the reason that there is none?

PS: Please rename the "Commands" section to "Shortcuts" at https://codemirror.net/doc/manual.html#commands - It took me ages to find them.

**Comment by marijnh** [comment]
The default keymap doesn't come with a lot of extra, non-standard functionality. You can find a command for duplicating a line in the Sublime keymap, named `duplicateLine` and bound to `Shift-Ctrl/Cmd-D` by that keymap.

**Comment by q2apro** [comment]
> non-standard functionality

Meanwhile this is a standard functionality in all editors I know, only codemirror is the exception.

Using the proposed CTRL SHIFT D marks all the li blocks when inside the ul element. Such a shortcut is standard then? And duplicating is not?

**Comment by Yefee** [comment]
> The default keymap doesn't come with a lot of extra, non-standard functionality. You can find a command for duplicating a line in the Sublime keymap, named `duplicateLine` and bound to `Shift-Ctrl/Cmd-D` by that keymap.

May I know where I could find the `duplicateLine` . The keymap json doesn't have this option. Thank you!
