### ISSUE TITLE
From 5.21.0 to 5.33.0, highlight doesn't work

### ISSUE THREAD

**Issue by GitbyWe** [codemirror/CodeMirror#5144]
Hi, I recently opened a [issue](https://github.com/codemirror/CodeMirror/issues/5136) to say that my editor doesn't work when I update it but in fact, It's just highlight text which doesn't work when I try to udate to the latest version of `codemirror.js`. 
Note that all widgets are already up to date.
I tried `CodeMirror.colorize()` but no change.

Do I need to add more code to colorize the editor or keep the older version?

**Comment by marijnh** [comment]
If you mean highlighting of code within the editor, you don't need `colorize` for that. You just need to load the proper modes. Check `CodeMirror.modes` to see if your modes are there.

**Comment by GitbyWe** [comment]
For the editor, I have : ![this](https://4.bp.blogspot.com/-dQk4jHdweZY/WkE3o6gKF1I/AAAAAAAAMEQ/7vfOHdNtOtUut46D_ZsGspbwCMkyWeJegCLcBGAs/s1600/ep.png)

And when I type `CodeMirror.modes` in the console, it return ![this](https://4.bp.blogspot.com/-794rP6GDcXk/WkE5rcCJJYI/AAAAAAAAMEc/HNCRupnh5IAlI8veLScDYSa_7uQ93ECBgCLcBGAs/s1600/ec.png)

All needed dependencies (HTML, XML, JS, CSS) are loaded.
And `editor.getMode().name` returns `"htmlmixed"`

**Comment by marijnh** [comment]
Since I'm seeing neither the `xml` nor the `css` mode in that screenshot, it seems like those aren't actually loaded. Look into that.

**Comment by GitbyWe** [comment]
I have `{null: ƒ, htmlmixed: ƒ, javascript: ƒ, xml: ƒ, css: ƒ, markdown: ƒ}` for the latest version.
It work now and markdown  work too.
You're the best.
Much thanks.
