### ISSUE TITLE
CodeMiror in table cell grows when adding new lines

### ISSUE THREAD

**Issue by thipages** [codemirror/CodeMirror#5145]
Hi,
find below a code pen with the issue I have
It seems basic but I  am stuck
Thank you

[CODE PEN LINK](https://codepen.io/thipages/pen/NXbVpq)

**Comment by adrianheine** [comment]
Adding `overflow-y: auto` to `.CodeMirror` works as expected for me.

Note that we use GitHub issues for tracking bugs and enhancements, not discussing and getting help. The [forum](https://discuss.codemirror.net/) on the other hand is open for questions like this.

**Comment by thipages** [comment]
Thank you. I will post in the forum next time for such questions.
