### ISSUE TITLE
python tab not smart

### ISSUE THREAD

**Issue by AinolaLong** [codemirror/CodeMirror#5146]
I set `indentWithTabs` is true, and new line indentation is tab, when false indentation is spaces
Can you resolve this?
When I use the tab indent, indentation of the new line also want to become a tab.
When I use spaces indent,  indentation of the new line also want to become spaces.

like this: 
![image](https://user-images.githubusercontent.com/21746104/34346322-5f718ad6-ea31-11e7-880d-334ea7155518.png)

**Comment by adrianheine** [comment]
Hi, just to clarify: You want the indentation of a new line to follow `indentWithTabs` instead of copying the indentation style of the previous line? So, if `indentWithTabs` is true, a new line should be indented with tabs, not spaces?

**Comment by AinolaLong** [comment]
first of all,thanks! 
I want the indentation of a new line to copy the indentation style of the previous line.

**Comment by marijnh** [comment]
That isn't supported—indentation is measured in units, not specific strings. `indentWithTabs` determined whether the first _n_×`tabSize` units are converted to tabs or not.

You could write your own commands to implement the behavior you are looking for, but it is unlikely to be supported by the core editor.
