### ISSUE TITLE
Documentation of `show-hint`: customKeys is not correct

### ISSUE THREAD

**Issue by asashour** [codemirror/CodeMirror#5157]
The below statement of [show-hint](http://codemirror.net/doc/manual.html#addon_show-hint) `customKeys` is not correct:

> The handlers will be called with an extra argument, a handle to the completion menu, which has moveFocus(n), setFocus(n), pick(), and close() methods (see the source for details), that can be used to change the focused element, pick the current element or close the menu. 

Instead, the handlers are called with `CodeMirror` object, and to get the selected element, one has to do something like:

    ".": function(cm) {
        var completion = cm.state.completionActive;
        if (completion) {
            var data = completion.data.list[completion.widget.selectedHint];

**Comment by marijnh** [comment]
The handle is the _second_ argument to the function, hence the formulation "_extra_ argument". The first is, as with regular key bindings, the editor object.

**Comment by asashour** [comment]
May be I wasn't clear enough.

The _second_ argument is always `undefined`, please check this [JSFiddle](https://jsfiddle.net/065f0awb/).

**Comment by marijnh** [comment]
So I tested this, and I'm getting the proper object passed as second argument to my custom key handler.
