### ISSUE TITLE
misspelling: is it significant anywhere?

### ISSUE THREAD

**Issue by Ndolam** [codemirror/CodeMirror#5159]
Line 37 of mode/dtd/dtd.js has
    else if (ch == "|") return ret("keyword", "seperator");
Is there going to be some other place in the future that expects "separator" to be spelled correctly?
Or, is this misspelling already written in stone?

**Comment by marijnh** [comment]
That string seems to be completely unused. Feel free to submit a pull request that fixes the spelling if it bothers you.

**Comment by Ndolam** [comment]
Thanks for the quick response.
It doesn't bother me enough to go through the effort of creating a pull request.

Cheers.
