### ISSUE TITLE
getTokenAt() includes braces

### ISSUE THREAD

**Issue by neon-dev** [codemirror/CodeMirror#5169]
I've encountered an inconsistent behavior while implementing custom hints in sql mode using `CodeMirror.hint.fromList`. These custom hints are available inside double curly braces (will be parsed/substituted before the actual SQL statement execution).
The problem is, `fromList` uses `getTokenAt` internally which returns strange tokens in this mode.
This issue is restricted to modes where curly braces and regular words have no special token type.

Example:
The cursor position is anywhere inside, or at the end of `test`, which is enclosed in double curly braces (`{{test}}`).
Now I call `CodeMirror.hint.fromList(cm, {words: ['testWord']})`, but testWord will not be found as a possible result.
This is because `cm.getTokenAt` returns a token containing `{test` instead of `test`. Currently I need to modify the input words, as well as the returned list to make it work and display properly, which is an ugly workaround.

I'd expect `cm.getTokenAt(cursor)` to return either `test` or `{{test}}`. The first one feels more intuitive and surely is more useful in my case, but I get that curly braces could also be interpreted as plain text in some languages. In fact, in sql mode curly braces have no special meaning at all.

**Comment by marijnh** [comment]
The mode determines how the code is split into tokens. `getTokenAt` just queries those. There is no guarantee that token boundaries happen to fall at the point where it is convenient for your completion code. Unless you can change the mode, of course, in which case you can make sure it produces different token types for the braces and their content.

**Comment by neon-dev** [comment]
I know there's no guarantee for that, that's not what I was after. Just thought that this could be wrong, since these braces have the same token type and aren't special syntax chars.

Regarding my problem, I think I'll keep the workaround I have. Changing the mode on the fly seems to be the worse solution if it introduces more overhead than iterating and replacing a few array values.
If `hint.fromList` would consider word boundaries instead of tokens, that'd be prettier. It takes "words" as an argument, so word boundaries seem reasonable, but I don't know how you intended that function to work.

**Comment by marijnh** [comment]
> It takes "words" as an argument

It is indeed called "words", but it can hold any strings, which can occasionally be useful. I think fixing this in the mode is the way to go here.

**Comment by neon-dev** [comment]
I guess enabling [overlay.js](https://codemirror.net/demo/mustache.html) in my sql editor like in that example should be an adequate solution. Plus we get nice highlighting.
If I understand it correctly, it will override tokenizing and thus the the token type, if returned.
So if I want to properly detect and set different token types for braces and variables, I must call `match()` with a lookahead/-behind regex for opening/closing braces? And `eat()` controls what chars will get the token type we return.

I also found `cm.addOverlay()` which seems very similar, but it seems like it's only for styles and doesn't influence token types so I didn't look into it.

**Comment by neon-dev** [comment]
I was mistaken, the overlay is really only display logic, it doesn't affect tokenizing (makes sense).

Instead I used `multplex.js` and defined Mustache as a simple mode via `simple.js`, which works just fine.
This is, until you want hints to work, but I found a (hopefully temporary) workaround (see #5249)
