### ISSUE TITLE
Ctrl + F2 cannot toggle/delete bookmark

### ISSUE THREAD

**Issue by wernight** [codemirror/CodeMirror#5171]
Steps:

1. Place cursor somewhere
2. Press Cltr + F2
3. Move cursor
4. Press F2 -> Cursor should return to position (1)
5. Press Ctrl + F2
6. Move cursor
7. Press F2

Expected: Does nothing, as the bookmarked location (1) should have been removed by the second Ctrl + F2. This is Sublime's behavior.

Actual: Creates yet another bookmark at that location meaning that F2 will go to the same location twice now (one more time for each Ctrl + F2).

Regression: I recall this used to work.

**Comment by marijnh** [comment]
Yes, it was broken in 5.12 due to a change in the core. Attached patch should help.
