### ISSUE TITLE
Anyway to just get the syntax highlighter?

### ISSUE THREAD

**Issue by domharrington** [codemirror/CodeMirror#5175]
Hello there,

We're using this module just for syntax highlighting on the front end, not for any of the IDE or editing capabilities. Is there some way to require just the syntax highlighter and the languages I require, as opposed to `require('codemirror')` then `require('codemirror/addon/runmode/runmode')`. Codemirror is adding around 300kb to our built JS. 

I've investigated using runmode-standalone, runmode.node and neither of them work. I'm bundling up our JS using webpack - so it looks like a node environment (with `module` and `exports`) but then also has browser globals like `window`.

Any help would be greatly appreciated.

Dom

**Comment by marijnh** [comment]
> runmode-standalone, runmode.node and neither of them work.

They do, but not with bundlers unless you add some configuration—the modes all depend on lib/codemirror.js, and you have to somehow convince your bundler to load the runmode-standalone shim instead of the regular core library for that dependency.

But yeah, runmode is what you need, if all else fails you can also load the regular core lib and use runmode/runmode.js with that.

**Comment by domharrington** [comment]
Do you have any tips as to how I might achieve that? The main problem I have with including the regular core lib is bundle size, it adds around 300kb and I suspect adding just runmode-standalone would reduce that significantly.

I've had some success writing my own build script which recompiles the bundles that i need to be simple `module.exports =` modules:

```js
const fs = require('fs');
const path = require('path');
const CodeMirror = require('codemirror/addon/runmode/runmode.node');

const modes = require('../codemirror-modes/modes.json');

modes.forEach((mode) => {
  require(`codemirror/mode/${mode}/${mode}`);

  fs.writeFileSync(path.join(__dirname, '../codemirror-modes/', `${mode}.js`), `
    // Auto-generated from build-codemirror-modes.js
    module.exports = ${CodeMirror.modes[mode].toString()}
  `);
});
```

Then using it like this:

```js
require('codemirror/addon/runmode/runmode-standalone');

const CodeMirror = global.CodeMirror;
const modes = require('./codemirror-modes/modes.json');
require('codemirror/mode/meta.js');

modes.forEach(mode => {
  CodeMirror.defineMode(mode, require('./codemirror-modes/' + mode))
});
```

But this fails because it only fetches the function inside of the `defineMode` call: https://github.com/codemirror/CodeMirror/blob/e9e5f23b81ec86f84680d8b13ff422408e1a9428/mode/javascript/javascript.js#L14

This misses out all of the `defineMIME` stuff below that, which is required for `runMode`: https://github.com/codemirror/CodeMirror/blob/e9e5f23b81ec86f84680d8b13ff422408e1a9428/mode/javascript/javascript.js#L846-L855 So it fails.

Have you ever considered having the modes in the repo as common js exports, then bundling them up as UMD modules during the build process?

**Comment by renatodeleao** [comment]
@domharrington having the same issue at a regular web app, i know it was quite some time ago, but did you manage to to workaround it for webpack? 

Tried a mix of `imports-loader`, `scripts-loader` and `webpackIgnorePlugin` (similar to what's commonly suggested to ignore `moment.js` locales) but without success; more context [on SO](https://stackoverflow.com/questions/57201469/how-to-use-codemirror-runmode-standalone-version-in-a-webpack-setup) .

✌️

**Comment by rafegoldberg** [comment]
Yeah, now I'm having this issue while attempting to rehydrate an SSR-rendered component! @marijnh any updates on this?

**Comment by BrianHung** [comment]
@rafegoldberg @renatodeleao 

Have you guys tried configuring webpack to use
```
    externals: {
      "../lib/codemirror": 'CodeMirror'
    }
```

It seems to be working for me. My intuition was that a lot of CodeMirror imports contain
```
(function(mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
    mod(require("../lib/codemirror"));
  else if (typeof define == "function" && define.amd) // AMD
    define(["../lib/codemirror"], mod);
  else // Plain browser env
    mod(CodeMirror);
})
```
Instead of trying to prevent Webpack from bundling the CodeMirror library and using `Plain browser env`, we just replace the call to `require("../lib/codemirror")` with the `CodeMirror` which is globally available from the `runmode-standalone.js` file.
