### ISSUE TITLE
Editor content is not right corresponding the event 'change'

### ISSUE THREAD

**Issue by gaokunbuaa** [codemirror/CodeMirror#5176]
Thanks for your great work firstly.

My options setting as below:
  "    
      lineNumbers: true,
      mode: "javascript",           
      matchBrackets: true,
      theme: "monokai",
      showCursorWhenSelecting: true,
      lineWrapping: true,
      keyMap: "pcDefault",
      indentWithTabs: true,
      indentUnit: 4
"
Steps to reproduce:

1. input one left brace and press enter (one new line is started with '\t');
2.press 'Backspace' to remove the '\t' and input two spaces, at this time, the editor content is '0x7b,0xa,0x20,0x20';

![image](https://user-images.githubusercontent.com/18030715/34752571-114cef4e-f5ee-11e7-830c-7355da0e4810.png)

3. Then input one close brace;

At this time, I got one change to insert the close brace :

 {"from":{"line":1,"ch":2,"sticky":null},"to":{"line":1,"ch":2,"sticky":null},"text":["}"],"removed":[""],"origin":"+input"} 

but the content now is '0x7b,0xa,0x7d', the two spaces input are gone.

and try the function codeMirror.indexFromPos(change.from), I get 3, but I think it should be 4 now, because the original string is '0x7b,0xa,0x20,0x20' before append the '}'.

although I got another event 'change' to remove the two spaces soon:

{"from":{"line":1,"ch":0,"sticky":null},"to":{"line":1,"ch":2,"sticky":null},"text":[""],"removed":["  "],"origin":"+input"}

And at this time the editor content is still: '0x7b,0xa,0x7d',

Is there something wrong?

thanks

**Comment by gaokunbuaa** [comment]
Seems these two change events sequence should be reversed?

**Comment by gaokunbuaa** [comment]
Seems that the two change events sequence should be reversed?

**Comment by marijnh** [comment]
No, this is how the library works—change events are not synchronous, and the editor content may have been affected by further changes. You may want to use the `"changes"` event instead, which gives you an array of changes up to the current state.
