### ISSUE TITLE
[addon edit/closebrackets] Python docstrings do not always close properly

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#5177]
It seems the handling of triples doesn't always work right. With the following text:

`"""Here is the beginning of a docstring`

If one then types ", no completion is performed. But after the 3rd ", another 3 quotes are added (""").

Normally, after typing the first """ the quotes are autocompleted, but if the text already does not have that (e.g. through pasting) then it will not detect that the docstring should be closed.

**Comment by marijnh** [comment]
Attached patch avoids the adding of the extra quotes in this situation. It still doesn't automatically close a triple-quoted string, as the addon doesn't do the kind of non-local analysis that would make it easy to know that the string was double quoted, but it at least doesn't get in the way. Does that work for you?

**Comment by takamori** [comment]
Yep, that behaves better. Thanks!
