### ISSUE TITLE
[Typescript] highlight 'as' as a keyword?

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#5181]
In the following snipped as is highlighted as variable. Shouldn't be highlighted as a keyword?
```typescript
  let type: CodeInspectionResultType;
  switch (result.severity) {
    case ESLINT_SEVERITY_ERROR:
      type = BRACKETS_TYPE_ERROR as CodeInspectionResultType;
      break;
  }
```

**Comment by marijnh** [comment]
That's because `type` is a contextual keyword in TypeScript, and since it's appearing at the start of a statement here the mode considers it a type definition. If you know the proper way to disambiguate this, let me know.

**Comment by marijnh** [comment]
Ah, never mind, there was already a similar check (to see if the keyword was followed by an identifier) for `enum` and `module`, so I've applied to to `type` as well and that seems to improve this case.

**Comment by ficristo** [comment]
Thank you.
