### ISSUE TITLE
Using mode/simple addon, dedent does not work as expected

### ISSUE THREAD

**Issue by sslotsky** [codemirror/CodeMirror#5183]
Using version 5.33.0 from npm.

I've copied the code for the [mode/simple](http://codemirror.net/demo/simplemode.html) addon in attempt to define a very small, simple mode.

```javascript
CodeMirror.defineSimpleMode("slangwidge", {
  start: [
    { regex: /"(?:[^\\]|\\.)*?(?:"|$)/, token: "string" },
    { regex: /do/, indent: true, token: "keyword" },
    { regex: /end/, token: "keyword", dedent: true },
    {
      regex: /(walk|move|shoot|listen|send)\b/,
      token: "keyword"
    },
    { regex: /up|down|left|right/, token: "atom" }
  ]
});
```

The indentation _almost_ works correctly, but the `dedent` occurs on the line after the `end` keyword, instead of dedenting the line where it appears.

```
listen "mock" do
  shoot right
  end

walk right
```

After typing `end` and hitting `Enter`, the dedent occurs. But based on what I read, it should by default dedent the line where `end` appears. I tried adding `dedentIfLineStart: true` as well but this made no difference. Is there a different property I need for this rule? I tried several and noticed no change.

**Comment by sslotsky** [comment]
Spent more time with the docs and it looks like `electricInput` is required for this to work? Are there plans to support that for the simple mode? I currently have something working directly against the lower level mode API and using `electricInput` so I will close this, but I think simple mode shows a lot of promise and it would be really great to have this supported. 

Thanks so much for this amazing code editor!

**Comment by marijnh** [comment]
> Are there plans to support that for the simple mode?

Adding the `electricInput` property to your mode's `meta` object should work.

As for the future of simple-mode, I think I made some design mistakes in this approach, which make it easy to run into a wall where the abstraction just doesn't work anymore. I'm still mulling over what a better user-friendly mode definition system would look like, and will probably take some time later this year to try and work on that.
