### ISSUE TITLE
show-hint.js using a let variable, but has 'use strict' - breaks in phantomjs, and probably safari

### ISSUE THREAD

**Issue by lhfiedler** [codemirror/CodeMirror#5198]
You need to change let firstChar to var firstChar, otherwise you'll get an error:
SyntaxError: Use of reserved word 'let' in strict mode
   
 cursorActivity: function() {
      let firstChar = this.cm.getTokenAt(this.cm.getCursor()).string.charAt(0);
      if (firstChar === '\'' || firstChar === '"') {
        this.close();
        return;
      }

**Comment by marijnh** [comment]
This code doesn't appear in the current version of `show-hint.js`, so you're looking at either an old or a modified version.
