### ISSUE TITLE
Cursor incorectly displayed after applying scale transform

### ISSUE THREAD

**Issue by bartosz-m** [codemirror/CodeMirror#5199]
When scale is applied to codemirror its cursor's position and size are incorrectly displayed, see picture below. I checked either css transform and svg foreignObject, both exhibits same issue.

screen capture of official codemirror [page](https://codemirror.net/) with css `transform: scale(2)`

![obraz](https://user-images.githubusercontent.com/11303115/35184165-3e08e9aa-fdf2-11e7-94e5-b55c76f858f6.png)

**Comment by marijnh** [comment]
This is a known issue. See #2443—it's titled somewhat differently but describes the same problem. It's not likely this will be fixed in the short term.
