### ISSUE TITLE
Manual doesn't explain how to build code mirror

### ISSUE THREAD

**Issue by zadam** [codemirror/CodeMirror#5200]
Manual refers to the "distribution" - since I didn't find anything else I went to latest release and downloaded "source code".

Then I'm following the manual and the basic usage refers to the "lib/codemirror.js", but that file doesn't exist. I can see only CSS file there. 

Then I noticed package.json and found out I need to npm install and then build. After doing that I get lib/codemirror.js file. But for people without node experience this isn't really obvious ...

**Comment by marijnh** [comment]
The built code can be downloaded from the website or from NPM.

**Comment by zadam** [comment]
So finally I found the download link. But still I think it would be nice to include it also in the manual and / or mention the npm as well. I think I can't be the only one who had trouble figuring out how to download "built" code mirror.
