### ISSUE TITLE
Unhandled keyboard events / shortcuts are not propagated

### ISSUE THREAD

**Issue by zadam** [codemirror/CodeMirror#5201]
I have an application which has "global" keyboard shortcuts - they are bound to body document.

These shortcuts are expected to work from anywhere in the app - including inside the codemirror editor. But it looks that if they are not handled in CodeMirror, they are not propagated and stopped instead - i.e. pressing the keyboard shortcut inside codemirror will do nothing, but whenever I put focus outside code mirror, the shortcut works as intended.

Interestingly standard shortcuts like CTRL-H work (but overriding them doesn't work inside codemirror while it works outside codemirror).

I can define extra shortcuts like this:

```
editor.setOption("extraKeys", {
  Tab: function(cm) {
    var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
    cm.replaceSelection(spaces);
  }
});
```

And this works, but frankly I don't want to re-define all of my shortcuts specifically for code mirror. It seems strange that code mirror doesn't propagate them to outer elements like other editors do ...

**Comment by marijnh** [comment]
It's likely that this only happens for keys that CodeMirror has its own binding for. Can you give some examples of keys where the problem occurs?

**Comment by zadam** [comment]
This seems to happen with all my keyboard shortcuts - examples are ALT-A, ALT-Q, CTRL+. (dot)

There's an interesting effect with browser "standard" keyboard shortcuts - e.g. CTRL-J in FF normally jumps into google search input, but in my app I have this overriden to do something different (bind to the CTRL+J and ev.preventDefault()). But when I have focus inside CodeMirror, CTRL-J will jump into google search input as if the keyboard binding wasn't overriden by the app - so obviously it's not CodeMirror's own binding, but it somehow executes the default browser behavior.

**Comment by marijnh** [comment]
I can't reproduce this issue — key events for these keys arrive at the window level just fine. Are you maybe wrapping your editor in an iframe?

**Comment by zadam** [comment]
So finally I found the issue - problem was with used plugin - jquery.hotkeys.js which ignored keyboard events from textarea (even though filtering of form input events was disabled). Thanks for help.
