### ISSUE TITLE
All demos broken due to missing precompiled lib/codemirror.js

### ISSUE THREAD

**Issue by Connum** [codemirror/CodeMirror#5205]
Just wanted to let you know that all the demos fail to execute because a precompiled codemirror.js in the /lib folder is missing.

\\edit: then, on the other hand, I think that might be intentional? Just was expecting to be able to extract the files and have a quick go on the demos without having to compile myself first...

**Comment by marijnh** [comment]
If you clone the git repository, you have to first build the library (`npm install`).
