### ISSUE TITLE
setCursor breaks with string arguments

### ISSUE THREAD

**Issue by W1zzardTPU** [codemirror/CodeMirror#5206]
http://jsfiddle.net/chu87hhk/embedded/result/

After loading, the cursor should be set to line 3, char 2

Press enter now and the text after the cursor will vanish, other weirdnesses when typing characters.

Seems the issue is related to passing a string into the function, which I assumed would convert its input to numeric or throw an error message

**Comment by marijnh** [comment]
The `line` property in position objects is specified to be a number, so I consider this problem to be in the calling code, not the library. CodeMirror doesn't do type checks or conversions on all values it gets. This is intentional (too much noise and overhead).
