### ISSUE TITLE
ng-model data binding not working with CodeMirror

### ISSUE THREAD

**Issue by Nagendra080389** [codemirror/CodeMirror#5208]
Has anyone faced this kind to issue, I am sharing a link from stackoverflow below. I have tried many things here but all in vain.

[Question Link](https://stackoverflow.com/questions/48437078/ng-model-data-binding-not-working-with-codemirror)

**Comment by marijnh** [comment]
I don't expect a framework like Angular to automatically 'know' how to set and get CodeMirror's value. In any case, this isn't a bug in CodeMirror, so the issue tracker isn't the place for it.
