### ISSUE TITLE
"codemirror.js" is missing from "lib/" folder

### ISSUE THREAD

**Issue by SeanJM** [codemirror/CodeMirror#5215]
Hello, I've been trying to set up code mirror and I noticed "codemirror.js" is missing from "lib/" folder

**Comment by AnshulMalik** [comment]
Hey @SeanJM, you can download it from [http://codemirror.net/codemirror.zip](http://codemirror.net/codemirror.zip)

**Comment by adrianheine** [comment]
Sure, if you clone the git repository you have to run `npm i` and `npm run build`.
