### ISSUE TITLE
Code Mirror Python Liniting?

### ISSUE THREAD

**Issue by oscartbeaumont** [codemirror/CodeMirror#5222]
Is there support for linting Python code in CodeMirror. I could not find it in the linting folder. If not are there any ways of doing it?
Thanks,
Oscar

**Comment by marijnh** [comment]
No, this isn't provided. You might be able to create it yourself, by wiring the lint addon up to some existing Python linter.

In the future, please use the [forum](https://discuss.codemirror.net/), not the bug tracker, for questions like this.
