### ISSUE TITLE
SQL Mode Syntax Highlighting Bug

### ISSUE THREAD

**Issue by brioconnor** [codemirror/CodeMirror#5229]
I'm seeing unusual syntax highlighting behaviour in sql mode after using an escape sequence with `like`. Everything I type after `escape '\'` is highlighted in red.

```
select
*
from table_name
where field_1 like 'AB-CD\_%' escape '\'
and field_2 is not null
;
```

I've confirmed this on the code mirror website http://codemirror.net/mode/sql/ on macos 10.12.6 using Chrome version 64.0.3282.119 (Official Build) (64-bit).

<img width="957" alt="sql_syntax_highlighting" src="https://user-images.githubusercontent.com/11869885/35717106-14225aba-0818-11e8-8791-f0c65739150a.png">

**Comment by marijnh** [comment]
This appears to be intentional—you escaped the closing quote, so it doesn't close the string, which continues on the next line.

**Comment by brioconnor** [comment]
Thanks for getting back to me marijnh. So it’s just not possible to use a backslash as an escape character in SQL?

**Comment by marijnh** [comment]
I don't know—I haven't written SQL in years. It seems that standard SQL doesn't support backslash escapes in strings, but most implementations do, which I guess is why the mode supports them. I can't teach you SQL, but if you are using a SQL implementation that doesn't do backslash escapes in strings, let me know, and I can make it so that the mode only does them for some dialects.

**Comment by brioconnor** [comment]
marijnh, the sql still runs. It’s only a problem with the syntax highlighting. ANSI SQL doesn’t have an escape character by default.

**Comment by marijnh** [comment]
Yes, that's what I mentioned. Which dialect are you using?

**Comment by aharpervc** [comment]
This is definitely a flaw for `text/x-mssql`, which does not use `\` for escaping

**Comment by marijnh** [comment]
Thanks. Attached patch disables backslash escapes in strings for mssql
