### ISSUE TITLE
How to create a custom mode properly?

### ISSUE THREAD

**Issue by nickkolok** [codemirror/CodeMirror#5235]
I'm using `CodeMirror` in my project *(lots of thanks to you, `CodeMirror` devlopers, it's great)*.

However, I have to patch original `stex` mode to get spaces marked as spaces, to get cyrillic text as one node per word etc. Some of these patches could be useful for others and are being backported to original `CodeMirror` `stex` mode (e.g. #5226 #5233 #5234), but other patches are `tex-lint`-specific (for example, it's unusual to have spaces highlighed by certain color, isn't it?).

Summing up, I have to maintain my own `CodeMirror` mode. Moreover, I want other people to be able to use my mode. But the problem is that I don't know how to maintain a mode properly.

Yes, I've seen `codemirror-mode-elixir` and tried to do like there... No success :-(
Now I have to use a `postinstall` [script](https://github.com/nickkolok/tex-lint/blob/master/package.json#L8) in my project, which copies (symlinking doesn't work!) my mode file into `node_modules/codemirror/mode/stex`. This ugly hack works, but it's surely not a proper way to maintain a `CodeMirror` mode.

If I'm `require`ing my mode from elsewhere, it fails to run.

I know that you are not accepting new modes in the main `CodeMirror` repo, but could you please help me with creating an external one?

**Comment by marijnh** [comment]
This is the issue tracker, so really not the place for asking help. You can post something on the forum, if you want, but without a proper description of what went wrong when you tried to follow the example of the Elixir mode, I'm not sure how anyone can help you.
