### ISSUE TITLE
Emacs mode with 'search' and 'next line' inappropriately launches new browser window

### ISSUE THREAD

**Issue by I82Much** [codemirror/CodeMirror#5237]
Repro:
visit http://codemirror.net/demo/emacs.html in chrome
hit alt-e -> More tools -> add to desktop; save 
Launch the app from desktop that you just saved
Click into the editor pane
Hit ctrl-s to open search menu
Hit ctrl-n to go to new line

OBSERVED
New browser tab is opened

EXPECTED
cursor position is moved

Chrome version: 63.0.3239.132, Linux OS

This happens frequently to me as I use ctrl-s to search, then try to use next line to move through the file and edit based on the results of the search. 

The only workaround I know of is to hit ctrl+g to close search menu, then hit escape to close the browser search bar, then hit ctrl-n to go to new line.

**Comment by marijnh** [comment]
That doesn't just happen when you save the app, it happens in every situation—Chrome doesn't allow JavaScript to capture ctrl-n, so this isn't something CodeMirror can do.
