### ISSUE TITLE
[search] Search for ^\s does not work.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#5238]
1. Go to http://codemirror.net/demo/search.html
2. Alt-F and search for /^\s+</
3. Press enter repeatedly.

Expected: Cursor to move across results (altho- they are highlighted properly).
Actual: Cursor does not move.

Searching for /\s+</ works.
Searching for /^\s/ also does not work, and appears to be the minimal repro case.

**Comment by marijnh** [comment]
What do you expect `^` to match? CodeMirror's regexp search is not line-wise (it can match multi-line patterns), so `^` isn't really meaningful, and doesn't stand for 'start of line'.

**Comment by takamori** [comment]
I'd like to note the following:
- the `^` works for other patterns. For instance, `/^</` and `/^ /` and `/^ +</` works, as does `/^[ \t]+</`.
- the highlighted result looks just fine, from what I can tell. 

Why is it any different for the search cursor?

**Comment by takamori** [comment]
Btw that pattern that line-wrapped should have been `/^[ \t]+</` (a space and tab)

**Comment by marijnh** [comment]
> Why is it any different for the search cursor?

Because the search cursor must be able to match multi-line patterns (which is why the problem occurs for regexps that contain `\s` or another element that matches newlines, but not for simpler regexps).

**Comment by mtaran-google** [comment]
`^` and `$` should continue to match start-of-line and end-of-line, even with the multi-line regex search feature. This is how multi-line regexes are handled in Sublime, VSCode, Atom and IntelliJ. For example, given the file

```
  foo
  bar
  baz
  quux
```

the regex `^\s+.*\n\s+` matches two regions, one starting one the line with foo and one starting on the line with baz, in each of those editors. In https://codemirror.net/demo/search.html it only matches the first region.

Presence of `\s` etc. shouldn't alter the behavior of other regex special characters.

**Comment by marijnh** [comment]
JavaScript provides no way to match regular expressions like that, and emulating it by feeding `exec` every possible subsequence of lines is exponentially slow, so you definitely also don't want that.

**Comment by mtaran-google** [comment]
Considering VSCode is implemented in JS (Atom's implementation boils down to a native module), and does provide this functionality, I suspect that some reasonable implementation exists. 

Can you take a look at how they do it and maybe use some of their approach?
https://github.com/Microsoft/vscode/blob/73d60bd4c8308f018c4bd761d38702a8f0e91c3a/src/vs/editor/common/model/textModelSearch.ts#L132

**Comment by marijnh** [comment]
Turns out there's a regexp flag for that (`m`). Implemented in attached patch.
