### ISSUE TITLE
Syntax highlighting with static properties in JavaScript/JSX

### ISSUE THREAD

**Issue by eveningkid** [codemirror/CodeMirror#5243]
First of all, thanks a lot for all the time you spent working on this wonderful project. 

Now here is the problem I encountered: as soon as I add a few static properties to the class body, the syntax isn't highlighted correctly. I tried using the following code and both javascript/jsx modes:
```javascript
import React, { Component } from 'react';

class App extends Component {
  static propTypes = {
    title: PropTypes.string
  };

  static a = {};

  static hello() {
    return "Hello";
  }
}
```
[You can see how the editor highlighted this code in codemirror here.](https://image.prntscr.com/image/RtqOXFowTeiExbcEXgKMMA.png)

That pretty sums up the issue here, hope the mistake can easily be fixed.
Thanks again.

**Comment by marijnh** [comment]
[Class properties](https://github.com/tc39/proposal-class-fields) aren't part of the language yet, and aren't supported in the JavaScript mode. A pull request that implements the current proposal would be welcome, but I'm not going to implement them before they reach stage 4.
