### ISSUE TITLE
firefox : error message hostEl.createShadowRoot is not a function

### ISSUE THREAD

**Issue by skMun** [codemirror/CodeMirror#5247]
Hi. I am not good at English and I ask for your understanding.
hm... 

works fine in chrome.
but firefox is print an error message.
my firefox version : 58.0.1 (64bit)

If you can not use createShadowRoot, tell me how.

Thank you. Have a nice day. :)

full error message 
======================
columnNumber: 28
fileName: "http://localhost:4201/vendor.bundle.js"
lineNumber: 233663
message: "hostEl.createShadowRoot is not a function"
stack: "ShadowDomRenderer@http://localhost:4201/vendor.bundle.js:233663:28\n../../../platform-browser/@angular/platform-browser.es5.js/DomRendererFactory2.prototype.createRenderer@http://localhost:4201/vendor.bundle.js:233376:24\n../../../platform-browser/@angular/platform-browser/animations.es5.js/AnimationRendererFactory.prototype.createRenderer@http://localhost:4201/vendor.bundle.js:235379:41\ncreateComponentView@http://localhost:4201/vendor.bundle.js:219304:24\ncreateViewNodes@http://localhost:4201/vendor.bundle.js:219362:37\ncreateEmbeddedView@http://localhost:4201/vendor.bundle.js:219275:5\n../../../core/@angular/core.es5.js/</TemplateRef_.prototype.createEmbeddedView@http://localhost:4201/vendor.bundle.js:217469:29\n../../../core/@angular/core.es5.js/</ViewContainerRef_.prototype.createEmbeddedView@http://localhost:4201/vendor.bundle.js:217246:40\n../../../common/@angular/common.es5.js/NgIf.prototype._updateView@http://localhost:4201/vendor.bundle.js:174830:25\nset@http://localhost:4201/vendor.bundle.js:174789:13\nupdateProp@http://localhost:4201/vendor.bundle.js:218297:5\ncheckAndUpdateDirectiveInline@http://localhost:4201/vendor.bundle.js:218006:19\ncheckAndUpdateNodeInline@http://localhost:4201/vendor.bundle.js:219546:20\ncheckAndUpdateNode@http://localhost:4201/vendor.bundle.js:219489:16\nprodCheckAndUpdateNode@http://localhost:4201/vendor.bundle.js:220179:5\nView_EditorPreview_0/<@ng:///MenualModule/EditorPreview.ngfactory.js:162:9\nupdateDirectives@http://localhost:4201/vendor.bundle.js:219923:63\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219456:5\ncallViewAction@http://localhost:4201/vendor.bundle.js:219804:21\nexecComponentViewsAction@http://localhost:4201/vendor.bundle.js:219736:13\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219462:5\ncallViewAction@http://localhost:4201/vendor.bundle.js:219804:21\nexecComponentViewsAction@http://localhost:4201/vendor.bundle.js:219736:13\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219462:5\ncallViewAction@http://localhost:4201/vendor.bundle.js:219804:21\nexecEmbeddedViewsAction@http://localhost:4201/vendor.bundle.js:219762:17\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219457:5\ncallViewAction@http://localhost:4201/vendor.bundle.js:219804:21\nexecComponentViewsAction@http://localhost:4201/vendor.bundle.js:219736:13\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219462:5\ncallViewAction@http://localhost:4201/vendor.bundle.js:219804:21\nexecEmbeddedViewsAction@http://localhost:4201/vendor.bundle.js:219762:17\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219457:5\ncallViewAction@http://localhost:4201/vendor.bundle.js:219804:21\nexecComponentViewsAction@http://localhost:4201/vendor.bundle.js:219736:13\ncheckAndUpdateView@http://localhost:4201/vendor.bundle.js:219462:5\n../../../core/@angular/core.es5.js/</ViewRef_.prototype.detectChanges@http://localhost:4201/vendor.bundle.js:217379:9\n../../../core/@angular/core.es5.js/</ApplicationRef_.prototype.tick/<@http://localhost:4201/vendor.bundle.js:212017:58\n../../../core/@angular/core.es5.js/</ApplicationRef_.prototype.tick@http://localhost:4201/vendor.bundle.js:212017:13\nnext/<@http://localhost:4201/vendor.bundle.js:211889:100\n../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:4201/polyfills.bundle.js:20462:17\nonInvoke@http://localhost:4201/vendor.bundle.js:211095:24\n../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:4201/polyfills.bundle.js:20461:17\n../../../../zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:4201/polyfills.bundle.js:20212:24\n../../../core/@angular/core.es5.js/</NgZone.prototype.run@http://localhost:4201/vendor.bundle.js:211026:54\nnext@http://localhost:4201/vendor.bundle.js:211889:70\n../../../core/@angular/core.es5.js/</EventEmitter.prototype.subscribe/schedulerFn<@http://localhost:4201/vendor.bundle.js:210840:36\n../../../../rxjs/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub@http://localhost:4201/vendor.bundle.js:147479:13\n../../../../rxjs/Subscriber.js/SafeSubscriber.prototype.next@http://localhost:4201/vendor.bundle.js:147426:17\n../../../../rxjs/Subscriber.js/Subscriber.prototype._next@http://localhost:4201/vendor.bundle.js:147366:9\n../../../../rxjs/Subscriber.js/Subscriber.prototype.next@http://localhost:4201/vendor.bundle.js:147330:13\n../../../../rxjs/Subject.js/Subject.prototype.next@http://localhost:4201/vendor.bundle.js:147074:17\n../../../core/@angular/core.es5.js/</EventEmitter.prototype.emit@http://localhost:4201/vendor.bundle.js:210826:54\ncheckStable@http://localhost:4201/vendor.bundle.js:211060:13\nonHasTask@http://localhost:4201/vendor.bundle.js:211108:21\n../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.hasTask@http://localhost:4201/polyfills.bundle.js:20515:21\n../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype._updateTaskCount@http://localhost:4201/polyfills.bundle.js:20535:17\n../../../../zone.js/dist/zone.js/</</Zone.prototype._updateTaskCount@http://localhost:4201/polyfills.bundle.js:20359:17\n../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:4201/polyfills.bundle.js:20279:25\ndrainMicroTaskQueue@http://localhost:4201/polyfills.bundle.js:20666:25\n../../../../zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:4201/polyfills.bundle.js:20573:21\ninvokeTask@http://localhost:4201/polyfills.bundle.js:21441:9\nglobalZoneAwareCallback@http://localhost:4201/polyfills.bundle.js:21459:17\n"

**Comment by marijnh** [comment]
Hi. CodeMirror doesn't use the shadow DOM, and the library never calls `createShadowRoot`, so this error must be coming from somewhere else.

**Comment by skMun** [comment]
#marijnh oh. I'm sorry. I was mistaken.
Thank you. Have a nice day. :)

**Comment by shabbir1995** [comment]
Did You find a solution for this error?

**Comment by shabbir1995** [comment]
I am stuck really bad with this error! any help appreciated.
Thanks
