### ISSUE TITLE
Add clikable link to each line (via id attribute)

### ISSUE THREAD

**Issue by pevik** [codemirror/CodeMirror#5252]
Hi, it would be nice to have id attribute to be able to jump to each line via id attribute for each line + have each number clickable with this URL.

Something like github, cgit, gitweb have:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/samples/bpf/bpf_load.c?id=refs/tags/v4.11#n535
https://github.com/codemirror/CodeMirror/blob/master/.travis.yml#L2

I suppose there would need to be unique instance number as there can be more CodeMirror instances:
`id="CodeMirror-linenumber-instance_id-NUM"`

**Comment by marijnh** [comment]
This is out of scope for the core library, and would be problematic to implement anyway, as CodeMirror renders only visible lines, so not all IDs would be available at any given time.
