### ISSUE TITLE
javascript-lint error severity error introduced in 5.34.0

### ISSUE THREAD

**Issue by mkapiczy** [codemirror/CodeMirror#5260]
The change introduced in release 5.34.0 causes an error in my application, because it relies on the fact that an error struct provided by JSHINT.data.errors() will contain a code property. In my case it doesn't an then I get an error:

![image](https://user-images.githubusercontent.com/16140337/36142695-2175c6c2-10a9-11e8-884b-9025a07e3777.png)
![image](https://user-images.githubusercontent.com/16140337/36142711-2c3658d8-10a9-11e8-9430-df7db57b55cc.png)

When I execute JSHINT.data().errors command in the console I get errors struct in this form:

![image](https://user-images.githubusercontent.com/16140337/36142732-3fe59a4c-10a9-11e8-82cf-71ee56af5450.png)

I guess when we rely on the structure got from external module, we shall have more defensive approach?

**Comment by marijnh** [comment]
Which version of JSHint are you using?

**Comment by mkapiczy** [comment]
Yes. I've been using old jshint version. I have a problem with updating it, as it causes new errors, so I will get back to you when I manage to do that.

**Comment by mkapiczy** [comment]
I still didn't manage to upgrade my JSHINT version, but I will still work on that and this is codemirror unreletaed issue.

Anyway, wouldn't it be better to provide a backward functionality if there was one previously? E.g. check for a code property if not there make severity 'error' by default?
