### ISSUE TITLE
Uncaught TypeError: n.listSelections is not a function

### ISSUE THREAD

**Issue by bspsz** [codemirror/CodeMirror#5264]
Hi.
I'm using CodeMirror plugin in CKEditor 4.8.0, and after switching editor to code edit mode I've got an error: 

> Uncaught TypeError: n.listSelections is not a function

and I can't switch back to wysiwyg mode. In config.js I have just: 
`config.extraPlugins = 'codemirror';`

Does anyone had that problem too?

**Comment by adrianheine** [comment]
While `listSelections` is a method name used in CodeMirror, I have no idea what your problem might be. Unless you can reproduce the issue with a standalone CodeMirror instance, this is the wrong place to report it.

Please open an issue at the [CKEditor 4 issue tracker](https://github.com/ckeditor/ckeditor-dev/issues). Also, there's CKEditor 5, did you try that one?

**Comment by adrianheine** [comment]
Ok, then your best bet is to open an issue in the CKEditor 4 issue tracker and try to work out what the problem is and where it comes from.
