### ISSUE TITLE
how to highlight full line? (I try use markText)

### ISSUE THREAD

**Issue by gosp** [codemirror/CodeMirror#5270]
I don't know whether CM has similar api as ACE: `this.aceEditor.getSession().addMarker(range,"errorHighlight", "line", false);`,     
I try to use
`this.cmEditor.markText({line:0, ch: 0}, {line: 1, ch: 9}, {className: "errorHighlight"});`

But I get the result:       
![markText](https://sfault-image.b0.upaiyun.com/185/069/185069421-5a893d26ce3fe)

In fact, because there is multiple lines to be highlighted, I want to highlight the first `full line`. I don't know how CM do it?

**Comment by marijnh** [comment]
The positions you pass to `markText` lie in different lines, so the fact that it highlights multiple lines is expected. You can pass the correct positions, or use `addLineClass` instead.
