### ISSUE TITLE
New Line not Work On All Statement in sql Like : SELECT * FROM Main \nWHERE a > 10

### ISSUE THREAD

**Issue by AMAISGOD** [codemirror/CodeMirror#5276]
Hi
Thank For you Project
its so perefect but have some bug in new line when use where , ...
i fix it by this new Function
`codeMirror.getText = () => {
                  return codeMirror.getValue().replace(new RegExp(/\n\S/, "g"), (val) => {
                      return(" " + val);
                  });
                };`
and Use getText();
Thank you
GoodLuck

**Comment by marijnh** [comment]
Could you be a bit more specific about what the problem is?

**Comment by AMAISGOD** [comment]
When I use `codeMirror.getValue()`  for This Text
`SELECT a FROM Main\nWHERE  a > 1`
Query dont work and sql Library (mssql npm) Send Error :
Incorrect Syntax Near 'WHERE'

**Comment by marijnh** [comment]
That's too bad, but it's definitely not a CodeMirror issue -- the editor treats its content as just text, what happens with it after it is edited is outside of the library's scope.
