### ISSUE TITLE
JavaScript lint in htmlmixed mode doesn't work

### ISSUE THREAD

**Issue by zadam** [codemirror/CodeMirror#5278]
I have codemirror instance with "htmlmixed" mode which contains HTML page with included <script> tag, something like this:

```
<p>Hello world!</p> 

<script type="text/javascript">
alert("Hello!");
</script>
```

Syntax highlighting works correctly here - both HTML & JS is highlighted correctly. But lint is not working - e.g. JS syntax errors are not marked. I was experimenting with javascript-lint.js and found out it's simply because its validator() function is not called at all. If I add registration to "html" mode, then validator is called, but fails to parse the code at first HTML code (and doesn't continue). Lint works correctly in "javascript" mode.

Unfortunately it's not really clear to me if lint is even supposed to work in htmlmixed mode...

**Comment by marijnh** [comment]
That's true, this is not a feature that currently exists. It'd require somehow extracting the scripts and passing them to JSHint, and then making sure positions are adjusted to point at the right places in the original file. I consider it out of scope for the current code.
