### ISSUE TITLE
addon/mode/simple: detect empty lines

### ISSUE THREAD

**Issue by boljen** [codemirror/CodeMirror#5280]
First of all thank you for your amazing work on this library.

I'm implementing a language that has significant empty lines. Is there a way to detect those in the simple mode add-on?

Thanks in any case!

**Comment by marijnh** [comment]
I'm afraid not. The simple mode add-on is probably a bit of a dead end, at this point I recommend using the 'plain' mode API if you're building a new mode.

**Comment by boljen** [comment]
Aight, thanks!
