### ISSUE TITLE
Range definition in DefinitelyTyped seems wrong.

### ISSUE THREAD

**Issue by shunjikonishi** [codemirror/CodeMirror#5282]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c7450fa3201c7c8e6e519cc8146fb3f135963b2f/types/codemirror/index.d.ts#L720-L721

I believe it should be

```
        from: CodeMirror.Position;
        to: CodeMirror.Position;
```

**Comment by marijnh** [comment]
That definition isn't maintained by the maintainers of the library, so this bug tracker isn't the right place to report issues with it.
