### ISSUE TITLE
Materialize interferes with search and ex prompts of the vim keymap

### ISSUE THREAD

**Issue by digwuren** [codemirror/CodeMirror#5284]
I'm porting a web app that uses CodeMirror to Materialize.

It turns out that Materialize's extensive CSS rules for everything that looks like a form input field make the vim keymap's search and ex-style command entry boxes look wrong as in bulky: the rules force the helpful _desc_ inscriptions such as "`(Javascript regexp)`" to be placed not right of the input field but beneath it, beyond a thick line meant to symbolise an entry field.

Materialize's CSS rules have an exemption for elements tagged with the `browser-default` class.  Accordingly, this patch provides something of a workaround.

[CodeMirror-vim-prompt-Materialize-exemption.diff.txt](https://github.com/codemirror/CodeMirror/files/1759342/CodeMirror-vim-prompt-Materialize-exemption.diff.txt)

I suppose a proper solution would allow the class(es) added to be customisable.  It is currently not clear to me how best to do it.

**Comment by marijnh** [comment]
Does `browser-default` work on child nodes? If so, you could maybe just set it on some node surrounding the whole editor.

In any case, I am not interested in adding workarounds for problems caused by 3rd party code to this library, so you'll have to apply that patch locally.
