### ISSUE TITLE
java mode

### ISSUE THREAD

**Issue by dhib-dy** [codemirror/CodeMirror#5285]
java mode not exist

**Comment by marijnh** [comment]
See http://codemirror.net/mode/clike/

**Comment by dhib-dy** [comment]
thanx , i have been see that link, but in the repo https://github.com/codemirror/CodeMirror/tree/master/mode the java mode is absent

**Comment by marijnh** [comment]
No, it's not, you're just looking in the wrong place. The clike mode defines a `"text/x-java"` MIME type.

**Comment by dhib-dy** [comment]
thanx you it's working

**Comment by x5engine** [comment]
please a note in the docs or something thank you :)
