### ISSUE TITLE
Velocity variables with dash are not well highlighted

### ISSUE THREAD

**Issue by cmglez10** [codemirror/CodeMirror#5287]
In velocity language, when a variable contains a dash (eg. ${MASK-LAN}), only the left part is highlighted as a variable.

**Comment by adrianheine** [comment]
That should be the regular expression in [line 85](https://github.com/codemirror/CodeMirror/blob/master/mode/velocity/velocity.js#L85). Would you like to try to fix this?

**Comment by cmglez10** [comment]
Sorry, Regexp and me are not best friends... :(

**Comment by adrianheine** [comment]
Ok, it's actually pretty easy. Currently, variable names after dollar signs are matched with `/[\w\d\$_\.{}]/`, which means: any letter, number, the dollar sign, an underscore, a dot or square brackets are acceptable. You want to add a dash, so the correct regular expression would be `/[\w\d\$_\.{}-]/`. Do you want to try submitting a pull request for that change?

**Comment by cmglez10** [comment]
Done! Sorry about the delay.
Thanks!

**Comment by marijnh** [comment]
Solved via #5292
