### ISSUE TITLE
(some) whitespace characters as well as curser shown as  Â  in production build (only)

### ISSUE THREAD

**Issue by SebastianKrieger** [codemirror/CodeMirror#5288]
**what should happen:** normal whitespace shown
**what happened:**  Â  character shown instead of whitespace

![a instead of whitespace](https://user-images.githubusercontent.com/27827339/36811518-602f1252-1cce-11e8-86c8-08587ddea29c.png)

**what i tried:** 
- adding `<meta charset="UTF-8">` to html
- using ascii_only option in uglify-js
<img width="423" alt="asci only" src="https://user-images.githubusercontent.com/27827339/36811666-dfe56276-1cce-11e8-894a-fbc6176c1b61.png">

my babel rc looks like this:
<img width="616" alt="babelrc" src="https://user-images.githubusercontent.com/27827339/36812003-069f423c-1cd0-11e8-81ac-3354091eae72.png">

**Comment by adrianheine** [comment]
I doubt that's something we can help with, or at least it doesn't seem to be CodeMirror's fault.

**Comment by SebastianKrieger** [comment]
yes, maybe you are right, at least with the second statement. Not many others seem to experience this behaviour like me..
![space code](https://user-images.githubusercontent.com/27827339/36816846-6dcc13ae-1cdf-11e8-9673-d4294734af05.png)

Maybe as help for people who may run into this and read this page, is there a work-around like configuring the visual whitespace element to be sth. else ? Or so... if not its ok...

**Comment by marijnh** [comment]
There's no way to reconfigure the whitespace character, and you'll run into other problems when the encoding of the library is mangled, so I'd look through my build process carefully to see where the problem is being introduced, and fix it.

**Comment by SebastianKrieger** [comment]
wow finally! Found the source! After hours of checking everything else the reason was a **missing utf-8 content type in s3 metadata** which just showed up in production version. Thank you for the replies!
