### ISSUE TITLE
Uncontrollabe codemirror cursor and freezes

### ISSUE THREAD

**Issue by pvzzombs** [codemirror/CodeMirror#5291]
The problem makes my html file buggy.
I am using the updated version of codemirror.
The bug is when my js code tries to get the value, edit something and set the value to the codemirror textarea, the textarea freezes.
And when I try to type something, the new typed characters are reversed, in the direction on the left
`
<html>
<head>
<script src="lib/codemirror.js"></script>
<link rel="stylesheet" href="lib/codemirror.css" />
<link rel="stylesheet" href="theme/monokai.css" />
<link rel="stylesheet" href="addon/lint/lint.css" />
<link rel="stylesheet" href="cm.css" />
<link rel="stylesheet" href="addon/hint/show-hint.css" />
<script src="mode/javascript/javascript.js"></script>
<script src="addon/lint/html-lint.js"></script>
<script src="addon/lint/javascript-lint.js"></script>
<script src="addon/hint/javascript-hint.js"></script>
<script src="addon/hint/show-hint.js"></script>
<script src="htmlhint.js"></script>
<script src="jshint.js"></script>
<script src="addon/lint/lint.js"></script>
<script src="mode/css/css.js"></script>
<script src="mode/xml/xml.js"></script>
<script src="mode/htmlmixed/htmlmixed.js"></script>
<script src="m.js"></script>
</head>
<body>
<div>
<textarea name="textBox" id="textBox">
</textarea>
</div>
<script type="text/javascript">
var timeout;
var edit = CodeMirror.fromTextArea(document.getElementById("textBox"),
{
lineNumbers: true,
mode: "javascript",
theme: "monokai",
gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter", "CodeMirror-lint-markers"],
lint: true
});
edit.on("change",function(cm){
	var a = m.getKey(edit.getValue()),b = a[0],c = a[1],arr;
	if(b == "{"){
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){arr = m.New.split("");
		arr[c] = "{}";
		cm.setValue(arr.join(""));
		m.New = arr.join("");},200);
		return ;
		
	}else if(b == "("){
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){arr = m.New.split("");
		arr[c] = "()";
		cm.setValue(arr.join(""));
		m.New = arr.join("");},200);
		return ;
		
	}else if(b == "["){
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){arr = m.New.split("");
		arr[c] = "[]";
		cm.setValue(arr.join(""));
		m.New = arr.join("");},200);
		return ;
	}else{
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){cm.setValue(m.New);},200);
		return ;
	}
});
</script>
<br />
</body>
</html>
`
Javascript code

`var m = {};
m.Old = "";
m.New = "";
m.Store = ["backspace", "enter", "error"];
m.getKey = function(x) {
    var y = m.New;
    m.New = x;
    m.Old = y;
    if (m.New.length < m.Old.length) {
        return [m.Store[0]];
    } else if (m.New.length > m.Old.length) {
        var i, a = m.Old + " ",
            b = a.split(""),
            c = m.New.split("");
        for (i = 0; i < c.length; i++) {
            if (c[i] != b[i]) {
                return [c[i], i];
            }
        }
        if (c[i].test(/[\n\r]/g)){
        	return [m.Store[1], i];
        }
        return ["space", i - 1];
    } else {
        return [m.Store[2], -1];
    }
}
m.appear = function(d, el, ty) {
    document.getElementById(el)[ty] = m.getKey(d);
}

`

**Comment by marijnh** [comment]
We'll take a look if you can reduce this to the minimal code needed to reproduce it. As it is, this is too much irrelevant code.

**Comment by pvzzombs** [comment]
HTML:
`
<html>
<head>
<script src="lib/codemirror.js"></script>
<link rel="stylesheet" href="lib/codemirror.css">
<link rel="stylesheet" href="cm.css" />
<script src="mode/javascript/javascript.js"></script>
<script src="m.js"></script>
</head>
<body>
<div>
<textarea name="textBox" id="textBox">
</textarea>
</div>
<script type="text/javascript">
var timeout;
var edit = CodeMirror.fromTextArea(document.getElementById("textBox"),
{
lineNumbers: true,
mode: "javascript"
});
edit.on("change",function(cm){
	var a = m.getKey(edit.getValue()),b = a[0],c = a[1],arr;
	if(b == "{"){
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){arr = m.New.split("");
		arr[c] = "{}";
		cm.setValue(arr.join(""));
		m.New = arr.join("");},200);
		return ;
		
	}else if(b == "("){
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){arr = m.New.split("");
		arr[c] = "()";
		cm.setValue(arr.join(""));
		m.New = arr.join("");},200);
		return ;
		
	}else if(b == "["){
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){arr = m.New.split("");
		arr[c] = "[]";
		cm.setValue(arr.join(""));
		m.New = arr.join("");},200);
		return ;
	}else{
		if(timeout){clearTimeout(timeout)}
		timeout = setTimeout(function(){cm.setValue(m.New);},200);
		return ;
	}
});
</script>
<br />
</body>
</html>
`

Javascript
`
var m = {};
m.Old = "";
m.New = "";
m.Store = ["backspace", "enter", "error"];
m.getKey = function(x) {
    var y = m.New;
    m.New = x;
    m.Old = y;
    if (m.New.length < m.Old.length) {
        return [m.Store[0]];
    } else if (m.New.length > m.Old.length) {
        var i, a = m.Old + " ",
            b = a.split(""),
            c = m.New.split("");
        for (i = 0; i < c.length; i++) {
            if (c[i] != b[i]) {
                return [c[i], i];
            }
        }
        if (c[i].test(/[\n\r]/g)){
        	return [m.Store[1], i];
        }
        return ["space", i - 1];
    } else {
        return [m.Store[2], -1];
    }
}
m.appear = function(d, el, ty) {
    document.getElementById(el)[ty] = m.getKey(d);
}
`

**Comment by pvzzombs** [comment]
Heres the link for better testing:
HTML: https://cdn.rawgit.com/pvzzombs/hello-world/0f539409/Sample.html

JS: https://cdn.rawgit.com/pvzzombs/hello-world/0f539409/m.js

**Comment by pvzzombs** [comment]
EDIT:
HTML : https://github.com/pvzzombs/hello-world/blob/master/Sample.html

**Comment by marijnh** [comment]
> And when I try to type something, the new typed characters are reversed, in the direction on the left

This is because you're using `setValue` to give the editor a new value, which will reset the cursor position. Use methods like `replaceRange` to make targeted changes, if that's what you want.

I can't reproduce the freezing, but I expect that's also caused by your code.

**Comment by pvzzombs** [comment]
The direction of text is fixed, but when I try to type the cursor, it freezes. Then the browser crashes.

```
<html>
<head>
<script src="lib/codemirror.js"></script>
<link rel="stylesheet" href="lib/codemirror.css">
<link rel="stylesheet" href="cm.css" />
<script src="mode/javascript/javascript.js"></script>
<script src="m.js"></script>
</head>
<body>
<div>
<textarea name="textBox" id="textBox">
</textarea>
</div>
<script type="text/javascript">
var timeout;
var edit = CodeMirror.fromTextArea(document.getElementById("textBox"),
{
lineNumbers: true,
mode: "javascript"
});
edit.on("change",function(cm){
	var a = m.getKey(edit.getValue()),b = a[0],c = a[1],arr;
	if(b == "{"){
		arr = m.New.split("");
		arr[c] = "{}";
		cm.replaceRange(arr.join(""),{line : 1,ch : 1},{line : arr.join("").split("\n").length , ch : arr.join("").length});
		m.New = arr.join("");
		
	}else if(b == "("){
		arr = m.New.split("");
		arr[c] = "()";
		cm.replaceRange(arr.join(""),{line : 1,ch : 1},{line : arr.join("").split("\n").length , ch : arr.join("").length});
		m.New = arr.join("");
		
	}else if(b == "["){
		arr = m.New.split("");
		arr[c] = "[]";
		cm.replaceRange(arr.join(""),{line : 1,ch : 1},{line : arr.join("").split("\n").length , ch : arr.join("").length});
		m.New = arr.join("");
	}else{
		cm.replaceRange(m.New,{line : 1,ch : 1},{line : m.New.split("\n").length , ch : m.New.length})
	}
});
</script>
<br />
</body>
</html>
```

**Comment by pvzzombs** [comment]
@marijnh Is there any problem in my code?
