### ISSUE TITLE
Feature request - No scrolling when editor doesn't have focus

### ISSUE THREAD

**Issue by polterguy** [codemirror/CodeMirror#5293]
Howdy, I'm consuming tons of CodeMirror instances in [this project](https://github.com/polterguy/phosphorusfive), and I've even implemented my own mode for Hyperlambda, which is a programming language I've created myself. However, this creates a problem for me, since having several instances of CodeMirror around makes it difficult to scroll the actual page. Hence, I was wondering if it's possible to avoid having the editor instance itself scroll, unless it's got focus ...?

**Comment by polterguy** [comment]
BTW, thx for a spectacular piece of work! It's an amazingly nice tool :)

**Comment by marijnh** [comment]
Not really—the scrolling is largely handled by the browser, which will scroll the innermost scrollable element under the cursor. You might be able to build your own solution by setting `pointer-events: none` on unfocused editors, but then you need some other hack to remove it again on mousedown.

**Comment by polterguy** [comment]
Thx mate, I might look into it ... :)
