### ISSUE TITLE
Three way compare with 2 pane view

### ISSUE THREAD

**Issue by legatoloco** [codemirror/CodeMirror#5295]
Is it possible to use the code mirror merge view with 2 originals and one editable, but showing in the 2 way compare format?
This would be similar to cvs/svn compare where diffs with one original are colored differently from diffs with the second original.
In cvs/svn, it used to be colored differently for outgoing, incoming and conflicting.

If not, is it possible to pass in the set of diffs (and special css classes) to the 2 way view compare mode?

**Comment by marijnh** [comment]
Nope, neither of these are features that the merge addon has (and they are unlikely to be added).
