### ISSUE TITLE
slow find/replace with some multiline regex queries

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5298]
put the following into https://codemirror.net/demo/search.html
~~~~
#

x: {
  y_z: "a-b-reviews"

  check_tests: {
    project: "youtube.b.x"
  }
  check_default_stuff: {}
  check_do_not_submit: {}
  check_some_conflict: {}
}
~~~~
ctrl+f, and then paste in `/check_tests([^]*\n?)*}/`

expected: the result should come up quickly

actual: chrome freezes for many seconds (with variants of this input, it freezes long enough for chrome to tell you to kill the tab)

Doing the following in the dev console works quite quickly:
```js
const s = `#

x: {
  y_z: "a-b-reviews"

  check_tests: {
    project: "youtube.b.x"
  }
  check_default_stuff: {}
  check_do_not_submit: {}
  check_some_conflict: {}
}
`;
const re = /check_tests([^]*\n?)*}/gmi;
re.exec(s);

**Comment by marijnh** [comment]
I warned you about performance when we discussed the multi-line regexp feature. In this case, the regexp itself is exponential (and, as far as I can see, needlessly so), which you can see if you run it against a substring of your example instead:

```javascript
/check_tests([^]*\n?)*}/gmi.exec(`#

x: {
  y_z: "a-b-reviews"

  check_tests: {
    project: "youtube.b.x"`)
```

Regexps are a performance liability in their very nature, and that's not something CodeMirror can solve.
