### ISSUE TITLE
Parentheses in vim mode inserts parentheses instead of moving a sentence

### ISSUE THREAD

**Issue by jolars** [codemirror/CodeMirror#5299]
### How to reproduce
Select any part of a text in normal mode and press `(` or `)`.

### Expected
Cursor should move a sentence ahead or back.

### Actual result
A parentheses is inserted at the cursor.

**Comment by ebogard** [comment]
Hi I'm a new contributor, do you think I could take this as a first issue?

It looks like there are no motions defined for '(' and ')' in /keymap/vim.js

**Comment by ebogard** [comment]
Great! I submitted a pull request. Any feedback is greatly appreciated since I'm new to contributing.

**Comment by marijnh** [comment]
Fixed via #5357
