### ISSUE TITLE
Tab whitespace is not normalised on paste, breaking Python code

### ISSUE THREAD

**Issue by wesinator** [codemirror/CodeMirror#5305]
Chrome browser on Linux

With CodeMirror in Jupyter notebook, pasting text with tab (`\t`) characters does not normalize the tab chars to the default use of spaces for indentation, causing mixed indentation that breaks Python code.

#### To reproduce:
- In a text editor, type python function with indented code using tab characters (not spaces).
- Paste the code into codemirror
- Write new indented code in codemirror using tab, notice the indent is represented with spaces

#### Actual results:
Pasted code keeps tab characters, while the new code uses spaces for indent. This creates a mixture of tab whitespace that breaks otherwise functional Python code since [python does not allow mixed indentation](https://docs.python.org/3/reference/lexical_analysis.html#indentation).
![codemirror_pasted_tabs_error](https://user-images.githubusercontent.com/5124946/37249586-83cc8ec8-24b8-11e8-97c2-c4c715338c8a.png)

Code that reproduces this issue:
```py
def main():
	x = 'hi' # tab indent
    y = 0 # spacing indent
```
Also tested on https://codemirror.net/mode/python/index.html, tab chars are not normalised.

#### Expected:
On paste, codemirror converts any tab characters to the indentation whitespace that is the default when typing in codemirror (e.g. tab chars -> 4 spaces, if spaces are default for tab)

**Comment by marijnh** [comment]
> On paste, codemirror converts any tab characters to the indentation whitespace that is the default when typing in codemirror 

This is not a feature that CodeMirror has (nor is it something that I think it should be doing by default). You may be able to implement it as an addon.

**Comment by josephrocca** [comment]
@wesinator Hey Wes, in case it's helpful to you, here's how I ended up fixing this with my application:

```
editor.on("beforeChange", (cm, change) => {
  if(change.origin === "paste") change.update(null, null, change.text.map(line => line.replace(/\t/g, "  ")));
});
```
