### ISSUE TITLE
Add a way to highlight a string without needing to use dom

### ISSUE THREAD

**Issue by paladox** [codemirror/CodeMirror#5307]
Hi, would it be possible to support highlighting strings without needing to use the dom, ie like prism.js and highlight.js please?

highlightjs.highlight and prism.highlight

**Comment by marijnh** [comment]
Yes, it is possible, see the [runmode addon](http://cm/doc/manual.html#addon_runmode).

**Comment by paladox** [comment]
@marijnh hi, does codemirror also support a way to look ahead ie if you highlight per line it needs a way to know if your using HTML but also using javascript 

Ie doing

```
<div></div>

<script>
  function(e) {}
</script>
```

When highlighting per line will it also highlight within <script>?

(This is what highlight.js does)

**Comment by marijnh** [comment]
The [htmlmixed](http://codemirror.net/mode/htmlmixed/) mode highlights HTML with JavaScript and CSS embedded in it.

**Comment by paladox** [comment]
@marijnh is there a way to use codemirror.runmode so that it's return is a string, so something like

var results;
results = CodeMirror.runMode(document.getElementById('var = test', "application/javascript");
this.push('_baseRanges', results); (results returning a string)

**Comment by paladox** [comment]
if callback is empty (which is used to highlight the code by id or class name) then it throws an error.

**Comment by paladox** [comment]
soemthing like https://github.com/curvedmark/codemirror-highlight/blob/master/lib/highlight.js#L30 but that's too old to use (on npm under codemirror-highlight).

And could we support highlight.js .top to please?

so ie it's used like this in highlight.js

        result = window._hljs.highlight(this._baseLanguage, baseLine, true,
            state.baseContext);
        this.push('_baseRanges', result.value);
        state.baseContext = result.top;

notice result.top and state.baseContext . state.baseContext  pushes up what it reads from result.top, then highlight.js read from state.baseContext and returns it again as result.top.

This is so it can read each string ie if you have something like

```
<element></element>

<script>
function(e) {
  return e;
}
</script>
```

it will parse <script> but after it will then parse ```function(e) {``` but because it cannot tell if it was in <script> it will then not highlight.
