### ISSUE TITLE
cm.display.maxLine is not updated when doc is changed by markText

### ISSUE THREAD

**Issue by gera2ld** [codemirror/CodeMirror#5308]
`cm.display.maxLine` is not updated when doc is changed by `markText` with `replacedWith`. As a result, the new max line can not be shown completely.

```html
<div id="code"></div>
```

```js
const cm = CodeMirror(document.querySelector('#code'), {
  mode: 'javascript',
});
cm.setValue('abcdefghijklmnopqrstuvwxyz\nb\nc');
// maxLine should be line 0
const span = document.createElement('span');
span.textContent = '1234567890'.repeat(10);
const marker = cm.markText({ line: 1, ch: 0 }, { line: 1, ch: 1 }, {
  replacedWith: span,
});
marker.changed();
// maxLine should be line 1 now, but not updated
```

I think it is related to these lines in `lib/codemirror.js`:
```js
// function markText(...) {
    if (cm && marker.collapsed && !cm.options.lineWrapping && visualLine(line) == cm.display.maxLine)
      { updateMaxLine = true; }
```
Does this mean that the max length will be measured again only if we are marking the `maxLine`? What if `markText` changes the line length?

**Update:**
Tried `marker.changed()` but makes no difference. Do I miss something? Thanks in advance.

**Comment by marijnh** [comment]
The max line is determined based entirely on line character length, not on visual appearance. This is problematic, but computing the visual length of every line would be too expensive, and it's unlikely to be fixed on the short term.

**Comment by gera2ld** [comment]
Thanks for the explanation.
It's totally acceptable to determine line length based on characters, but I thought it should be mentioned somewhere in the document.
