### ISSUE TITLE
Unload Merge

### ISSUE THREAD

**Issue by tcederquist** [codemirror/CodeMirror#5310]
v5.31.0

I have an editor which can switch between a basic codemirror and merge view. When I switch from normal to merge and back to normal it appears to leave the merge view hooks in place. If my single page app stays open long enough it take increasingly long periods of time to load the codemirror editor with new code as the hidden merge view is trying to diff. I reset the generation in the codemirror instance when I load new code but merge is left alone. 

My request - is there a way to add support to unload MergeView and its hook/timers?

Background:
Merge appears to have hooks like timeouts, events and others. Chrome performance dev tools show merge registered timeout events that run for 1 second per each time I open merge diff with different code as I can see more and more merge.js timers showing up in the performance monitor when I run it (each instance locking the ui for 1s). Refreshing the screen fixes it until I start to use the merge features. Here is my code block for how I start the merge view each time a diff is requested by the user:

	var target = document.getElementById("view");
	target.innerHTML = "";   // Tried with and without this line
	var dv = CodeMirror.MergeView(target, {
			value: $scope.codeEditor.linkedDoc({sharedHist:true}),
			origLeft: null,
			orig: $scope.editorMdl.gitCompare.codeStore.code,
			lineNumbers: true,
			highlightDifferences: true,
			connect: "align",
			collapseIdentical: true,
			mode: codingcenterService.getLangsMeta($scope.editorMdl.intrchg.lang).language,
			theme: "neat"
	});

Here is the HTML hosting the segment of the spa display:
`       <div ng-hide="visi.codeHide" class="erm-full">`
`              <textarea ui-codemirror="codeOption" ng-model="editorMdl.intrchg.fullCode"></textarea>`
`        </div>`
`        <div id=view style="height: 100%;" ng-show="visi.codeHide"></div>`

Call stack of the issue:
Timer in merge.js line 119 (this calls ~x times depending on on how many times I start diff)
Calls merge.js:87 and etc...

Possible fixes in merge.js:

- An "unregister" events function for the materials inside function registerUpdate(dv) on line 83
- A way to call the clearTimeout(debounceChange); as found on line 117

**Comment by marijnh** [comment]
How are you switching to a plain editor? In principle, removing the editor from the DOM should cause it to be garbage collected. I'm not sure how the `setTimeout` that's set when editor events occur can continue happening when the editor isn't active anymore.

**Comment by tcederquist** [comment]
I'm switching the ng-show/ng-hide back on and refreshing the contents since it was a linked doc that may have changed. However, when I switch back into diff mode, it calls the same MergeView constructor shown in my code again which after tracing the code creates a 'new MergeView' on the first line in the constructor. As such it appears, none of the events are recycled, new ones are created. I've tried to recycle the old MergeView assigned to 'dv' by apply a new option set but it does not redraw correctly (might just need to use a similar repaint if I can get a reference to the codemirror instances) but not able to make that work yet.

The removal of the elements in the dom with the innerHTML call may remove the dom objects but not the event hooks so the code stays in memory and continues to get called. Such are the woes of the spa I think.

**Comment by marijnh** [comment]
> I'm switching the ng-show/ng-hide back on

What does that mean in DOM terms?

> The removal of the elements in the dom with the innerHTML call may remove the dom objects but not the event hooks

Event handlers are garbage collected when the DOM nodes they are registered on are collected.

**Comment by tcederquist** [comment]
ng-show/hide is angular translation of hidden css. 

To try out your thoughts on gc I added logic to set the innerhtml to empty when it switches back to normal view instead of just hiding. I also confirmed the dom elements are deleted (chrome inspect on the dom node for split window). Unfortunately, the hooks stay in place even after the dom segment is destroyed. Here is the best reference I can find at the moment for the issue, I suspect 2 or 4 might be involved after a quick review of the merge.js logic (or I've done something very wrong in my own code which I keep reviewing). https://auth0.com/blog/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/

The web reference isn't meant negatively, I just didn't trust my interpretation of issues I've had with my own code, I find I'm constantly struggling with leaks, spa probably still not being too common. The issue may still be in my logic so I'm still digging looking for any references I may have to anything inside the merge view. However, I pretty much just turn it on and link the codeviewer doc and nothing else (this is my next theory and looking for ways to destroy the codeview doc as I keep it and just reset the generation, maybe I need to delete the doc and start over for each load of new code). I can use the ide I've built for hours without issue, as soon as I invoke the merge view it starts adding merge.js hooks for nearly each occurrence. I think its trying to diff unrelated docs which is why I found it as it takes a while to determine two large documents have nothing in common * x instances.

I'll try to break away later today, another large deliverable to knock out, and then I'll try to put together an online sample to try to isolate this further as I really don't want to waste your time if this is my issue. I love the features and support! Best editor out there imho. Once I get an actual customer, I'll be sharing some dosh.

**Comment by marijnh** [comment]
> Unfortunately, the hooks stay in place even after the dom segment is destroyed.

How are you determining that it is in place? Is it actually firing after the editor was removed from the DOM?

**Comment by tcederquist** [comment]
Yes, running the chrome's application rendering profiler I can see the long delay in releasing the main codemirror editor to use when loading new code into the main codemirror doc are due to the merge.js events listed at the opening comment ('call stack of the issue' comment). It can have as many as 6 or 7 separate identical hooks fire in series if I've opened diff a number of times (each typically slows it down a little more). At this point the page is too sluggish and I just refresh the page and start again. These don't show up again until I start using the diff view.

https://developers.google.com/web/tools/chrome-devtools/rendering-tools/

**Comment by tcederquist** [comment]
![image](https://user-images.githubusercontent.com/1350745/37473264-63049cb4-2844-11e8-9bdc-ae97cb701682.png)

A quick snapshot of a single instance I tested after the dom was deleted.

**Comment by tcederquist** [comment]
![image](https://user-images.githubusercontent.com/1350745/37473480-b02156d6-2844-11e8-892f-126e6fc04273.png)

A quick one after opening a few code items with diff and then closing them. This is the record of loading a new document (without diff active) into the main codemirror editor.

**Comment by marijnh** [comment]
> Yes, running the chrome's application rendering profiler I can see the long delay in releasing the main codemirror editor to use when loading new code into the main codemirror doc are due to the merge.js events listed at the opening comment

Since those events respond to events in the editor, this suggests that your code is somehow still doing something with this editor—the user can't cause events, on an editor that's no longer in the DOM.

**Comment by tcederquist** [comment]
Agreed, that's why I'm guessing now perhaps it might be the shared doc? I can't think of anything else at this point.

      value: $scope.codeEditor.linkedDoc({sharedHist:true}),

Since I keep this linked doc inside the main codemirror editor and just clean it up when I load a new document, perhaps merge won't let go as this doc object survives all the updates (cleaned out and reset generations to clean up undo history). An unload method or at least a way to break the link to the doc in merge might solve this kind of issue? Is there a better way to load a new document into a codemirror instance? (I use one main and one diff two panel set, neither are shown at the same time, the doc is actually part of the main instance, mapped into the diff panel set when needed)

**Comment by marijnh** [comment]
> Agreed, that's why I'm guessing now perhaps it might be the shared doc?

Yes, that'd be it. You'll have to unlink the document in the editor that you're dropping.

**Comment by tcederquist** [comment]
In case someone stumbles on this from google, here is a code extract of the solution @marijnh pointed me at:

	var ed = $scope.diffDv.editor();    // Stored from the call $scope.diffDv = CodeMirror.MergeView(target, {...
	var doc = ed.getDoc();
	doc.iterLinkedDocs((ldoc, shared)=>{ // Iterate over all the linked docs to remove and cleanup the event hooks
		console.log("unlinking doc:", ldoc);
		doc.unlinkDoc(ldoc);
	});
