### ISSUE TITLE
[emacs] About removing Ctrl-V shortcut

### ISSUE THREAD

**Issue by arnaud-fontaine** [codemirror/CodeMirror#5321]
Considering how Ctrl-V is widely used in browser as paste and that it is really inconvenient when trying to paste from another browser tab/window, would you mind removing this shortcut (and probably Alt-V as well for consistency) and only keep PageUp/PageDown?

**Comment by marijnh** [comment]
You can do this locally (`delete CodeMirror.keyMap.emacs["Ctrl-V"]`), but I want to keep it in the library itself.
