### ISSUE TITLE
Add showInCenter support for emacs keymap

### ISSUE THREAD

**Issue by hanfeisun** [codemirror/CodeMirror#5322]
Currently there is only showInCenter (Center the active line) shortcut for sublime keymap: https://github.com/codemirror/CodeMirror/blob/97b03ae0def7e71ee719307e19bd83bf01f2ae37/keymap/sublime.js#L518

But there is no such shortcut for emacs keymap. By default, Emacs uses `Ctrl+l` to center current line. Would it be possible to add this keybinding for emacs keymap?

**Comment by marijnh** [comment]
Emacs' `recenter-top-bottom` command (which is what C-l is bound to) does a bunch more than just centering a line though—it'll cycle between centering, moving to the top, and moving to the bottom of the screen. If you want to implement that and submit a pull request, I'd gladly accept it, but I'm probably not going to work on that myself.
