### ISSUE TITLE
[md] codemirror starts highlighting from an underscore where markdown renderers don't

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5323]
```md
[`foo`](bar){blah="_bark"}
```

in http://spec.commonmark.org/dingus/, the `_` comes through as a literal, while in the CodeMirror mode it starts an italic span

**Comment by marijnh** [comment]
It _will_ make `bark"}\nfoo` italic in the example below, though. And since our mode doesn't look ahead across lines, the current behavior is intentional, and the best it can do.

```
[`foo`](bar){blah="_bark"}
foo_
```

**Comment by mtaran** [comment]
Makes sense, thanks.
