### ISSUE TITLE
[New Feature] Wrap with backticks for applicable SQL modes

### ISSUE THREAD

**Issue by lukewatts** [codemirror/CodeMirror#5325]
First, can I just say CodeMirror is great! Nice work!

In PHPStorm when writing SQL for MySQL, MariaDB etc, then you can wrap with backticks the same way you would with single/double quotes or parenthesis elsewhere.

For example selecting _id_ or _table_ in the below statements and hitting ` would wrap them with backticks, not replace the words

```
SELECT id FROM table WHERE id = 1;
```

Select id and hit ` you get:

```
SELECT `id` FROM table WHERE id = 1;
```

You should also be able to select using multiselect and do all relevant words at once.

**Comment by marijnh** [comment]
The closebrackets addon can do that, if you configure it correctly. Attached patch adds the required mode property.

**Comment by lukewatts** [comment]
Thanks!
