### ISSUE TITLE
Cannot input anymore after press down a key and hold for a while

### ISSUE THREAD

**Issue by zwz** [codemirror/CodeMirror#5327]
I test it both on safari and chrome in the editor at codemirror.net.
After press down a key and hold for a while, nothing is inputed.
And you can not interact with the editor anymore with letter or digit key.

**Comment by marijnh** [comment]
How long is "a while"? I am not able to reproduce this so far on Chrome Linux.

**Comment by zwz** [comment]
This is weird. 
I just re-checked. I find that every input/textarea of any web page has this problem.
So there must be something wrong with my system, not codemirror.
