### ISSUE TITLE
somethingSelected() returns true if only whitespace is selected

### ISSUE THREAD

**Issue by ivanbacher** [codemirror/CodeMirror#5329]
Not sure if this is an issue but when `doc.somethingSelected()` returns true even if  only white space is selected.

![screen_shot_2018-03-26_at_14_43_14](https://user-images.githubusercontent.com/5493114/37910238-ef6cf886-3104-11e8-9ebf-a14d62e9b398.png)

**Comment by schanzer** [comment]
My reading of the API is this: if nothing is selected, then hitting the delete key should not modify the document in any way. Removing white space modifies the document, therefore something has to be considered selected.

**Comment by marijnh** [comment]
Yes, this method is behaving as it is intended.
