### ISSUE TITLE
Some of the vim commands(like ci(, ci[, etc.. ) don't work in Markdown mode.

### ISSUE THREAD

**Issue by hidaiy** [codemirror/CodeMirror#5334]
When I use CodeMirror with Vim mode and Markdown mode, it seems like some of the vim commands don't work.( like `ci[` or `da{`)
If bracket(like `[` or `(` etc..) have style of html, It seems like Vim mode can't scan bracket.

I checked vim.js and matchbracket.js to check sccaning bracket logic.

https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js#L3555
I found brackets are scanned using `scanForBracket` with a null as a second argument.( The sesond argument is style of html)
I thought this `null` means to scan a bracket without a style of html.

```
start = cm.scanForBracket(Pos(cur.line, cur.ch + offset), -1, null, {'bracketRegex': bracketRegexp});
end = cm.scanForBracket(Pos(cur.line, cur.ch + offset), 1, null, {'bracketRegex': bracketRegexp});
```

https://github.com/codemirror/CodeMirror/blob/master/addon/edit/matchbrackets.js#L65
On the other hand, in matchbrackets.js, `scanForBracket` look for bracket from string, and if the bracket has style passed as a argument, or if style is `undefined`, It seems that the bracket is considered to be found.

[As we can see from the demo](https://codemirror.net/mode/markdown/
), In Markdown mode on CodeMirror, bracket has a style.

```
 ![alt text](/path/to/img.jpg "Title")
 ↓
<span class="cm-comment">![alt text](/path/to/img.jpg "Title")</span>
```

vim.js call the `scanForBracket` with null as a style, so when we use Markdown mode, we can't find bracket using the vim commands like `ci[` or `ci(`.

I thought it would be that when we use the `scanForBracket` and we don't care html styles, It might be better we should pass `undefined` instead of `null`.

Using the `scanForBracket` with `undefined` as a second argument works in the vim mode with the markdown mode.

CodeMirror is realy great.
I use Markdown editor based on  CodeMirror.

I would appreciate it if you could consider this issue.

**Comment by marijnh** [comment]
Solved via #5328
