### ISSUE TITLE
How to get the CodeMirror Html after merging

### ISSUE THREAD

**Issue by GregorioCunha007** [codemirror/CodeMirror#5336]
My problem is that I'm trying to implement this over an infrastructure than only reads the HTML once. So it does not get updated when CodeMirror does its magic. So what I'm trying to do is to alter the reference in Html again. 

`
let target = document.getElementById("target"); 
var view = new CodeMirror.MergeView(target,{
        value: orig1,
        orig: orig2,
        lineNumbers: true,
        mode: "text/html",
        highlightDifferences: true,
        connect: null
      });`

What I have to do is something of the sort

` document.getElementById("target").innerHtml = target.innerHtml;` .. Well but this doesn't work, since target is a TextArea node, it will just show some text that has a bunch of CodeMirror divs.. 

I really need to make CodeMirror work over this infrascturure. Any ideas ?

![help](https://user-images.githubusercontent.com/14839994/38085329-f7ee0c8a-3347-11e8-8e15-95fb8e884a46.PNG)

**Comment by marijnh** [comment]
You can get the edited content out of a merge view with `view.editor().getValue()`. Beyond that, I'm not sure I can help much with this.
