### ISSUE TITLE
Feature request: dynamic rulers when max line length changes

### ISSUE THREAD

**Issue by blerner** [codemirror/CodeMirror#5339]
We are using CodeMirror for a code editor, and would like to display a warning ruler when any line in the document exceeds our desired maximum line length.  We've configured the rulers addon to create our ruler, and given it an extra CSS class of `.hidden` by default.  We can iterate over all the lines of the document on every `'change'` event and get their line lengths, but this seems to be quite inefficient, especially since CodeMirror already has the function `findMaxLine` and the fields `display.maxLine`, `display.maxLineLength` and `display.maxLineChanged`.  (Those fields aren't part of the documented public API, granted, but right now I'm trying to see what existing functionality we could re-purpose.)  But unfortunately, even with those fields' existence, their values are never updated because our CM instance is configured with `lineWrapping: true`, which short-circuits that entire process.  Additionally, while the rulers addon allows us to mutate the provided rulers array and then call `cm.refresh()` to trigger re-creating the rulers, calling `refresh()` from within an `update` event leads to an obvious hang.

I've currently come up with a hackaround, that uses a `'change'` event handler to force `cm.curOp.updateMaxLines = true`, to call `findMaxLine`, then using an `'update'` event handler to tweak the rulers if any of them have a column less than the current maxLineLength.  Finally, a `CodeMirror.signal(instance, "refresh", instance)` call forces a refresh event without triggering a full `refresh()`, which is just enough to trigger the rulers to redraw.

But this is very inefficient on large documents, since `findMaxLine` rescans the entire document, and a cleaner solution would be nice.  I'd be happy with any of:
- enhancing the rulers addon with a boolean `dynamic` flag, such that CodeMirror does all this dynamic enabling of rulers stuff for me, using private APIs that I shouldn't touch;
- an option to request line-length measuring anyway, even when `lineWrapping` is true
- an event to listen for when maximum line lengths change
- a `refresh` method on the rulers addon, to allow me to change the rulers after the CM instance has been initialized.

**Comment by marijnh** [comment]
> We can iterate over all the lines of the document on every 'change' event and get their line lengths, but this seems to be quite inefficient

Since change events give you information about which lines changed, you could largely make this incremental.

> a refresh method on the rulers addon, to allow me to change the rulers after the CM instance has been initialized.

Calling `setOption("rulers", ...)` already allows you to update the ruler setup dynamically.

I don't want to add new core features for this, since it seems possible to work around it in 3rd party code.
