### ISSUE TITLE
Why is CodeMirror cm-error marking

### ISSUE THREAD

**Issue by GregorioCunha007** [codemirror/CodeMirror#5340]
![mergeproblem](https://user-images.githubusercontent.com/14839994/38192342-5a842284-3664-11e8-8f37-f3d55c5cb61c.PNG)

It's working quite nicely. But why does it mark as an error that character ? And then all lines below it aswell ? How can I fix this ? It must remain white, or yellow if there are differences in the line.. thanks

**Comment by GregorioCunha007** [comment]
@marijnh Please provide your insight thanks !!!!

**Comment by marijnh** [comment]
The language mode does that. As such, it'd be useful to know what language you are using, and check for syntax errors in the code that you load into the editor.

**Comment by GregorioCunha007** [comment]
It's not any specific language. They're just keys and values

**Comment by GregorioCunha007** [comment]
The mode i selected was => "text/html"

**Comment by GregorioCunha007** [comment]
Using text/plain did the trick. What mode do you recommend for bash script ".sh" files ? Thanks for your fast response man

**Comment by marijnh** [comment]
A short glance at the mode list would have told you that there's a [shell mode](http://cm/mode/shell/index.html).

**Comment by GregorioCunha007** [comment]
@marijnh Tried using both of these possibilities inside http://codemirror.net/mode/shell/index.html, but it keeps showing it in plain text

**Comment by GregorioCunha007** [comment]
My files start with "#!/bin/sh" this annotation. Is it still considered a shell file right ?

**Comment by GregorioCunha007** [comment]
@marijnh  This is just a snippet of a file .. Anything wrong with it ? Since CodeMirror seems not able to recognize it as a .sh ?

`if [ -x /bin/test ]; then
    TEST_BIN=/bin/test
elif [ -x /usr/bin/test ]; then
    TEST_BIN=/usr/bin/test
else
    TEST_BIN=test
fi

DIRNAME=`dirname $0``
