### ISSUE TITLE
Mode: text/x-sh | application/x-sh not working

### ISSUE THREAD

**Issue by GregorioCunha007** [codemirror/CodeMirror#5344]
My .sh file looks like this..

    `#!/bin/sh"
     if [ -x /bin/test ]; then 
     TEST_BIN=/bin/test
      elif [ -x /usr/bin/test ]; then
      TEST_BIN=/usr/bin/test
      else 
      TEST_BIN=test
      fi
      DIRNAME=`dirname $0`

But it keeps being printed like a plain/text file. Something wrong with it ?

**Comment by marijnh** [comment]
It's a highlighter, not a syntax checker. Some modes may mark some mistakes as errors, most won't.
