### ISSUE TITLE
Fix of codemirror.js place (sample doesn't works)

### ISSUE THREAD

**Issue by mbaev** [codemirror/CodeMirror#5346]
From documentation "[Basic usage](http://codemirror.net/doc/manual.html#usage)"
```html
<script src="lib/codemirror.js"></script>
<link rel="stylesheet" href="lib/codemirror.css">
<script src="mode/javascript/javascript.js"></script>
```
But `codemirror.js` doesn't exists in folder "[lib](https://github.com/codemirror/CodeMirror/tree/master/lib)".

I think, that it moved somewhere and for now no one of examples works.

**Comment by marijnh** [comment]
Maybe try reading the [installation instructions](https://github.com/codemirror/codemirror#installation) first

**Comment by mbaev** [comment]
@marijnh maybe need to add this in manual?
http://codemirror.net/doc/manual.html
or, by your think, for first try we need to find and read all related documentation?
