### ISSUE TITLE
Copy & Paste of crylic letters overlap on Windows

### ISSUE THREAD

**Issue by ConiKost** [codemirror/CodeMirror#5351]
When I do paste under Windows a longer list of crylic letters, they seems to overlap on Windows. Interestingly, I can't reproduce this on Linux. Any ideas, if this can be fixed somehow?

Steps to reproduce
1) copy & paste this code into Codemirror. After pasting, you will notice, that one line is shorter, as several letters are overlapping.
```
  var utfMap = "´ÓÓóÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſƀƁƂƃƆƇƈƉƊƋƌƎƐƑƒƓƗƘƙƚƜƝƞƟƠơƤƥƫƬƭƮƯưƲƳƴƵƶǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǝǞǟǠǡǢǣǤǥǦǧǨǩǪǫǬǭǰǴǵǸǹǺǻǼǽǾǿȀȁȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȞȟȠȡȤȥȦȧȨȩȪȫȬȭȮȯȰȱȲȳȴȵȶȻȼȽȾȿɀβẞ`";
  var latMap = "'OOoyAaAaAaCcCcCcCcDdDdEeEeEeEeEeGgGgGgGghhHhIiIiIiIiiiYyJjKkqLlLlLlLlLlNnNnNnnNnOoOoÖöÖöRrRrRrSsssSsSsTtTtTtUuUuUuUuÜüUuWwYyYZzZzZzsbBBbOCcDDDdEEFfGIKklMNNOOoPptTtTUuVYyZzAaIiOoUuÜüÜüÜüÜüeÄäAaÄäGgGgKkOoOojGgNnAaÄäOoÄäAaEeEeIiIiÖöOoRrRrÜüUuSsTtHhNdZzAaEeÖöOoOoOoYylntCcLTszbß'";
  var badletters = 'ƁƂƃƆƇƈƉ';
```

**Comment by marijnh** [comment]
The layout of the actual letters is done by the browser, and not something CodeMirror has any control over. I suspect this may be a font or a browser problem.

**Comment by ischas** [comment]
Since the code posted by @ConiKost is shown correctly here at GitHub, I changed the font-family in our CodeMirror instance from "monospace" to "Consolas", which is the font used by my machine (Win 10, Firefox DE 60) to display code at GitHub. With this done, the kyrillic letters are displayed correctly.

So the `codemirror.css` seems to be problematic for kyrillic letters on Windows.

**Comment by marijnh** [comment]
`codemirror.css` sets the `font-family` to `monospace`, which gives you your system's default `monospace` font. I don't think you can blame this library if that font happens to have issues.

**Comment by ischas** [comment]
You're right, it seems to be a problem with the monospace font of Firefox, since the problem is not reproducable with Edge and Chrome.
