### ISSUE TITLE
Checkmarx reports potential XSS issues

### ISSUE THREAD

**Issue by bradgentry** [codemirror/CodeMirror#5352]
We use Checkmarx Static Code Analysis to identify code vulnerabilities.  In codemirror.js 5.32.0, Checkmarx reports 2 potential XSS issues:

1. line 1988:
`var spans = line.markedSpans, allText = line.text, at = 0`
Checkmarx reports that line.text is eventually displayed to the user in lines 1974 and 1979

2. line 2177
`lineView.node.appendChild(lineView.text)`
Checkmarx reports that lineView.text is eventually displayed to the user in line 2191

Can you either fix these vulnerabilities or assure us that they cannot be used to enable a cross site scripting attack?

**Comment by marijnh** [comment]
The text in the editor is indeed displayed to the user—that's what an editor does. That does not, however, constitute an XSS vector.

**Comment by bradgentry** [comment]
I edited my original issue to elaborate that Checkmarx indicates the values "flow through the code without being properly sanitized or validated"
