### ISSUE TITLE
Linter demo page partially broken because of bad link to CSSLint

### ISSUE THREAD

**Issue by teleclimber** [codemirror/CodeMirror#5356]
On this page: https://codemirror.net/demo/lint.html

The CSS linter demo is broken. Here is a screenshot of my console:

<img width="780" alt="screen shot 2018-04-11 at 1 59 34 pm" src="https://user-images.githubusercontent.com/5631748/38637475-d70ccaf8-3d90-11e8-8193-516c47be4622.png">

Chrome 65 on Mac.

**Comment by jdbruxelles** [comment]
@marijnh It's just the `//csslint.net/js/csslint.js` which isn't served over the HTTPS. The correct link is [http://csslint.net/js/csslint.js](http://csslint.net/js/csslint.js) And the [https://codemirror.net/addon/lint/css-lint.js](https://codemirror.net/addon/lint/css-lint.js) file hosted on codemirror.net works as good.

**Comment by marijnh** [comment]
Using an unsecure link would make browsers complain. Attached patch uses unpkg.com to get an https: version of csslint.js
