### ISSUE TITLE
color syntax and image bug in JavaScript

### ISSUE THREAD

**Issue by konojunya** [codemirror/CodeMirror#5359]
**bug in color sytax**

Sometimes JavaScript syntax does not apply. As I encountered myself, the syntax of the code after `await` with` async / await` is broken

![](https://pbs.twimg.com/media/DaRq5tLV4AEHKcJ.png)

**bug in image**

There are other bugs in which `if` images overlap.

![](https://pbs.twimg.com/media/DaR3v2OUQAA3yYy.png)

As a supplement, since it was generated from the extended function of vscode, it is a bug of vscode side.

reference: https://github.com/dawnlabs/carbon/issues/328#issuecomment-381185675

Finally.
I am Japanese and English is not fluent, so please let me know if you do not understand the meaning.

Thanks.

**Comment by marijnh** [comment]
Attached patch should fix at least part of this. If you still have trouble, include the actual code as text, not just an image, since I'm not going to copy text from an image to test this.
