### ISSUE TITLE
Space not registered in the html textarea on iPad

### ISSUE THREAD

**Issue by marvindanig** [codemirror/CodeMirror#5367]
I have a codemirror instance that works fine on the desktop browser and nearly as good on the iPad Safari. The only quirk remaining is that the `spaces` aren't getting registered on iOS. Nothing happens when the spacebar is pressed on the keyboard, though occasionally it scrolls up a little bit. 

I'm using the `htmlmixed` mode. Any clues to where I should be looking?

**Comment by beneboy** [comment]
I am also having this issue, works fine on Desktop with Safari but not iPad.

It appears that Space will scroll the window, so it is as if the space input it not being captured by CodeMirror.

Also the cursor does not appear.

The CodeMirror instance is being displayed inside a BootStrap modal on an Angular 1 SPA.

**Comment by marvindanig** [comment]
> It appears that Space will scroll the window, so it is as if the space input it not being captured by CodeMirror.

True that. It is my guess but with `{passive: false}` passed as options inside `addEventListener` on the iPad, it might just work.

**Comment by adrianheine** [comment]
This is one of many issues which are difficult to debug and solve with the fundamental approach currently taken by CodeMirror.

We are working on a rewrite (CodeMirror 6) that will overhaul input handling and should address this issue, and we are currently raising money for this work: See [the announcement](https://codemirror.net/6/) for more information about the rewrite and a demo.

Note that CodeMirror 6 is by no means stable or usable in production, yet. It is highly unlikely that we pick up this issue for CodeMirror 5, though.

**Comment by kimyLee** [comment]
I also meet this problem, it seems caused by the "contenteditable", try to add the following css style
textarea,
[contenteditable] {
    -webkit-user-select: text;
    user-select: text;
}

**Comment by marvindanig** [comment]
This is it! @kimyLee you found the mojo for this one, great job! :+
