### ISSUE TITLE
simple mode: Uncaught (in promise) TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by mickael-kerjean** [codemirror/CodeMirror#5374]
I made up a mode that produce the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
    at Object.token (simple.js?a7f8*:100)
    at readToken (codemirror.js:1636)
    at runMode (codemirror.js:1693)
    at highlightLine (codemirror.js:1539)
    at getLineStyles (codemirror.js:1583)
    at buildLineContent (codemirror.js:1829)
    at getLineContent (codemirror.js:2207)
    at buildLineElement (codemirror.js:2288)
    at patchDisplay (codemirror.js:4307)
    at updateDisplayIfNeeded (codemirror.js:4215)
```

The error is thrown from: 
```javascript
function tokenFunction(states, config) {
    return function(stream, state) {
      if (state.pending) {
        var pend = state.pending.shift();
        if (state.pending.length == 0) state.pending = null;
        stream.pos += pend.text.length;
        return pend.token;
      }
```
`state.pending` at that time is `[]` which makes `pend` to be `undefined` throwing an error while trying to `pend.text.length`

Tracking down where does this come from:
```javascript
 if (matches.length > 2 && rule.token && typeof rule.token != "string") {
            state.pending = [];
            for (var j = 2; j < matches.length; j++)
              if (matches[j])
                  state.pending.push({text: matches[j], token: rule.token[j - 1]});
```
matches[j] in my case is `""` and nothing is push in `state.pending`.

**Comment by mickael-kerjean** [comment]
I've update the code to be:
```
if (matches.length > 2 && rule.token && typeof rule.token != "string") {
            for (var j = 2; j < matches.length; j++)
              if (matches[j]){
                  if(state.pending === null) state.pending = [];
                  state.pending.push({text: matches[j], token: rule.token[j - 1]});
              }
```
and the problem is gone but I'm not 100% sure if it's a bug in the simplemode thinghy or an issue on my mode

**Comment by marijnh** [comment]
That won't make things better—you have to make sure your regexp's captured groups always match something (and that together they cover the whole token)

**Comment by mickael-kerjean** [comment]
> you have to make sure your regexp's captured groups always match something

That's the thing, I am trying to match multiple token in one line and the error is thrown while typing something in codemirror.

That's the extract from the mode:
```
start: [
{regex: /^(\*{1,}\s)(TODO|DOING|WAITING|NEXT){0,1}(CANCELLED|CANCEL|DEFERRED|DONE|REJECTED|STOP|STOPPED){0,1}(.*)$/, token: ["header org-level-star","header org-todo","header org-done","header"]},
...
...
]
```

The error is thrown while typing, I'm not sure how to manage this "properly" without the hack above and without copying and pasting part of the regex to manage all the different scenarios.

**Comment by marijnh** [comment]
The `{0,1}` will allow the groups to not match at all (producing undefined). You could solve this by putting a trailing `|` inside of the parentheses, as in `(TODO|DOING|WAITING|NEXT|)`, and dropping the curly braces.

**Comment by mickael-kerjean** [comment]
You rock :)
Many thanks for your support and for all the work you've put together to create such an awesome project
