### ISSUE TITLE
Show-hint addon fails to select hint if there is no initially-selected hint

### ISSUE THREAD

**Issue by stan-z** [codemirror/CodeMirror#5380]
If autocompletion hints displayed without initially-selected hint by passing `selectedHint === -1`, it will fail with an exception on trying to select a hint: 
> TypeError: Cannot read property 'className' of undefined
  at Widget.changeActive (show-hint.js:342)

**Comment by marijnh** [comment]
I guess it's assuming there's always a selected option. Want to submit a patch?

**Comment by marijnh** [comment]
Thanks!
