### ISSUE TITLE
Sublime shortcuts on linux - Ctrl-Alt-Down should be changed to Alt-Shift-Down.

### ISSUE THREAD

**Issue by cirvladimir** [codemirror/CodeMirror#5382]
Sublime has a pc shortcut Ctrl-Alt-Down which corresponds to addCursorToNextLine. On linux Ctrl-Alt is reserved so this is changed to Alt-Shift-Down in sublime.

Could we detect that the os is linux and change the shortcut accordingly?

**Comment by jdbruxelles** [comment]
Well seen! Ctrl-Alt-Down (Up/Left/Right) is reserved on Windows too (for screen rotation).

**Comment by marijnh** [comment]
I suppose we could (I assume `navigator.platform` is pretty reliable). Want to submit a patch?
