### ISSUE TITLE
Support ANSI color ???

### ISSUE THREAD

**Issue by ckeyer** [codemirror/CodeMirror#5384]
like this https://github.com/drudru/ansi_up

**Comment by marijnh** [comment]
You could write an addon that does this with an overlay or `markRange`, but the core library isn't going to include support for it.

**Comment by mattmundell** [comment]
If anyone is looking for a V6 extension: [@cookshack/codemirror-ansi](https://www.npmjs.com/package/@cookshack/codemirror-ansi)
