### ISSUE TITLE
show find/replace by button outside codemirror

### ISSUE THREAD

**Issue by thanaratjaruenying** [codemirror/CodeMirror#5390]
Which events/API can i use to show find/replace on codemirror?
I've read the document but couldn't solve the problem.

**Comment by marijnh** [comment]
You can run `editor.execCommand("find")` (or `"findNext"` or `"replace"`) from your button's click handler, where `editor` is the CodeMirror instance.

**Comment by GregorioCunha007** [comment]
@marijnh Hey ! I have a question, I have an instance

`var view = CodeMirror.MergeView(....);
let codeMirrorInstance = view;`

I'm trying to naviggate trough the differences using this code you mentioned above

`codeMirrorInstance.editor().execCommand("findNext")`

But it's return undefined, do you have any idea of what is going wrong ?

Thanks in advance!
