### ISSUE TITLE
FF bug: CodeMirror-vscrollbar and hscrollbar should not be in tab order

### ISSUE THREAD

**Issue by schanzer** [codemirror/CodeMirror#5391]
In Firefox v59/OSX, with VoiceOver enabled, tabbing onto a CM instance focuses the _vscrollbar_ rather than the editor content. This is specific to FF, and does not show up on Chrome or Safari.

Setting `tabIndex=-1` for the scrollbars fixes the issue.

**Comment by marijnh** [comment]
Odd. I see the same without screenreader in FF Linux (but not Chrome). Attached patch adds the attributes.
