### ISSUE TITLE
[fold] single-line fold gets expanded when cursor selection is dragged over it

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5392]
1. https://codemirror.net/demo/folding.html
2. type `const foo = {a:1,b:2};` into the JS editor
3. use a mouse click+drag to create a selection from the start of the line to the end

expected:
the selection includes the collapsed-region marker without affecting it

actual:
as the mouse-dragging-the-selection passes over the collapsed-region marker, the collapsed region expands again

**Comment by marijnh** [comment]
Attached patch should help with this.
