### ISSUE TITLE
'updateHeightsInViewport' function is a likely performance bottleneck.

### ISSUE THREAD

**Issue by AlexanderPrendota** [codemirror/CodeMirror#5398]
Hello! I have some idea that 'updateHeightsInViewport' function is a likely performance bottleneck.
Example: [Blog post](https://blog.jetbrains.com/kotlin/2018/04/embedding-kotlin-playground/). look at canvas example and click on plus-button (+). The example will load about 10 seconds.
Look at performance in Chrome.
<img width="679" alt="screen shot 2018-05-07 at 4 26 25 pm" src="https://user-images.githubusercontent.com/10503748/39704264-6d0293c6-5213-11e8-9744-20fe7e7b7e96.png">

**Comment by marijnh** [comment]
It's hard for us to see what the (+) button is doing. The profile seems to show lots and lots of relayouts. Since nothing is happening on the screen, and CodeMirror is set up to only require a few redraws per update, that probably means the client code is doing something wrong. If you can reduce this to a simple stand-alone script, and wrapping whatever you doing in a call to `operation` doesn't fix this, I can take a look.

**Comment by AlexanderPrendota** [comment]
@marijnh Hmm, If I use incognito window It renders about 3 seconds. Looks strange. (+) - button just cut the code before and after special markers.
Look at:
```js
this.codemirror.setOption("lineNumbers", true);
this.codemirror.setValue(this.prefix + sample + this.suffix);
this.codemirror.markText(
        {line: 0, ch: 0},
        {line: countLines(this.prefix), ch: 0},
        {
          readOnly: true,
          inclusiveLeft: true,
          inclusiveRight: false
        }
);
this.codemirror.markText(
        {line: this.codemirror.lineCount() - countLines(this.suffix) - 1, ch: null},
        {line: this.codemirror.lineCount() - 1, ch: null},
        {
          readOnly: true,
          inclusiveLeft: false,
          inclusiveRight: true
        }
);

for (let i = 0; i < countLines(this.prefix); i++) {
        this.codemirror.addLineClass(i, "background", 'unmodifiable-line')
}

for (let i = this.codemirror.lineCount() - countLines(this.suffix); i < this.codemirror.lineCount(); i++) {
        this.codemirror.addLineClass(i, "background", 'unmodifiable-line')
}
```

`prefix` and `suffix` — just a text.

And the main problem in 2 last loop. Probably it's a no good way co set the line color in loop.

Could you give some advice? 
I guess you are right. It's client side issue.

**Comment by marijnh** [comment]
Just wrap the whole thing in `this.codemirror.operation(() => { /* your code */ })` to make sure only one redraw happens, after you've made all your changes.

**Comment by AlexanderPrendota** [comment]
@marijnh Perfect! Thank you so much 👍
