### ISSUE TITLE
C# highlighter does not highlight interpolated strings

### ISSUE THREAD

**Issue by Voileexperiments** [codemirror/CodeMirror#5399]
Tested [here](https://codemirror.net/1/contrib/csharp/):

![image](https://user-images.githubusercontent.com/14909989/39851254-6f70dce4-5448-11e8-8dda-c0a8a7d3893d.png)

**Comment by marijnh** [comment]
That's true. If you want to fix this with a pull request, I'll take a look. But it isn't something we're going to work on.
