### ISSUE TITLE
Linter demo bug

### ISSUE THREAD

**Issue by abumalick** [codemirror/CodeMirror#5400]
Hello,

I noticed that the linter demo don't work for me:
https://codemirror.net/demo/lint.html

when I click somewhere on the editor, words get removed from the editor and it does not focus.

I use chrome Version 66.0.3359.139 (Official Build) (64-bit)

I have same bug in firefox

**Comment by marijnh** [comment]
That was broken in 9ed217d5b, attached patch should fix it.
