### ISSUE TITLE
Makefile support

### ISSUE THREAD

**Issue by gsemet** [codemirror/CodeMirror#5408]
Hi

It seems to have been a few attempt to integrate makefile support (Gnu Make) for CodeMirror. Is there any way to have nice code highlight on makefile rendered with codemirror?

Thanks

**Comment by marijnh** [comment]
Nope, this doesn't currently exist.

**Comment by varkor** [comment]
This would be useful to have. Could this issue be left open so that people know that this issue is unresolved? Thanks!
