### ISSUE TITLE
text/x-python linter registration

### ISSUE THREAD

**Issue by abumalick** [codemirror/CodeMirror#5409]
I experienced a strange bug when trying to register a linter for `text/x-python` (with the same mode for my document) the validation function was not triggered
```
CodeMirror.registerHelper('lint', 'text/x-python', validator);
```

And when registering it with `python` it worked.
```
CodeMirror.registerHelper('lint', 'python', validator);
```

For `text/x-java` it worked too. 

I didn't find out what was causing that.

**Comment by marijnh** [comment]
Registering helpers under MIME types is not generally supported. The clike mode sets `helperType` to the mime as a way to allow this, but it won't work for other modes.
