### ISSUE TITLE
Feature request: Coq support

### ISSUE THREAD

**Issue by ksqsf** [codemirror/CodeMirror#5410]
It'd be nice to have Coq support in CodeMirror, as it will benefit downstream projects like BoostNote [1].

[1] https://github.com/BoostIO/Boostnote/issues/1906

**Comment by marijnh** [comment]
We're not adding more modes to the main distribution—the way to go would be to implement it yourself and distribute it separately. See the [Elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir) for an example.
