### ISSUE TITLE
Can we include params in autocompletion mode?

### ISSUE THREAD

**Issue by Nagendra080389** [codemirror/CodeMirror#5413]
Autocompletion works fine but is there a way to include params in autocompletion like this - 

https://i.imgur.com/wAZhqMl.png

https://i.imgur.com/SIviORh.png

Also, is there a way to detect localvariables original type and show methods according to that.

Like : List<String> strings = new List<String>;
         'strings.' show show methods of List class..

**Comment by marijnh** [comment]
Yes you can do this, but you'd have to implement it yourself, as I'm not aware of any existing implementations, except for the [Tern integration](http://codemirror.net/demo/tern.html) which does some type inference for JavaScript.
