### ISSUE TITLE
Autocomplete does not work for "dot" correctly.

### ISSUE THREAD

**Issue by Nagendra080389** [codemirror/CodeMirror#5414]
`	setTimeout(function(test) {
						/*CodeMirror.commands.autocomplete = function(cm) {
							cm.showHint({
								hint: CodeMirror.hint.auto
							});
						};*/
						var ExcludedIntelliSenseTriggerKeys = {
							"8": "backspace",
							"9": "tab",
							"13": "enter",
							"16": "shift",
							"17": "ctrl",
							"18": "alt",
							"19": "pause",
							"20": "capslock",
							"27": "escape",
							"33": "pageup",
							"34": "pagedown",
							"35": "end",
							"36": "home",
							"37": "left",
							"38": "up",
							"39": "right",
							"40": "down",
							"45": "insert",
							"46": "delete",
							"91": "left window key",
							"92": "right window key",
							"93": "select",
							"107": "add",
							"109": "subtract",
							"110": "decimal point",
							"111": "divide",
							"112": "f1",
							"113": "f2",
							"114": "f3",
							"115": "f4",
							"116": "f5",
							"117": "f6",
							"118": "f7",
							"119": "f8",
							"120": "f9",
							"121": "f10",
							"122": "f11",
							"123": "f12",
							"144": "numlock",
							"145": "scrolllock",
							"186": "semicolon",
							"187": "equalsign",
							"188": "comma",
							"189": "dash",
							"190": "period",
							"191": "slash",
							"192": "graveaccent",
							"220": "backslash",
							"222": "quote"
						}

						function completeAfter(cm, pred) {
							var cur = cm.getCursor();
							if (!pred || pred()) setTimeout(function() {
								cm.showHint({
									hint: CodeMirror.hint.auto,
									completeSingle: false
								});
							}, 100);
							return CodeMirror.Pass;
						}

						function completeAfterDot(cm) {
							return completeAfter(cm, function() {
								var cur = cm.getCursor();
								return cm.getRange(CodeMirror.Pos(cur.line, cur.ch - 1), cur) == "<";
							});
						}
						var editor = CodeMirror.fromTextArea(document.getElementById('apexBody'), {
							lineNumbers: true,
							matchBrackets: true,
							styleActiveLine: true,
							extraKeys: {
								".": completeAfterDot
							},
							gutters: ["CodeMirror-lint-markers"],
							lint: true,
							mode: "text/x-apex"
						});
						editor.on("inputRead", function(cm) {
							if (timeout) clearTimeout(timeout);
							timeout = setTimeout(function() {
								editor.showHint({
									hint: CodeMirror.hint.auto,
									completeSingle: false
								});
							}, 150);
						});
						editor.on("keyup", function(cm, event) {
							var keyCode = event.keyCode || event.which;
							if (!ExcludedIntelliSenseTriggerKeys[(event.keyCode || event.which).toString()]) {
								if (timeout) clearTimeout(timeout);
								timeout = setTimeout(function() {
									editor.showHint({
										hint: CodeMirror.hint.auto,
										completeSingle: false
									});
								}, 150);
							}
						});
						globalEditor1 = $('.CodeMirror')[0].CodeMirror;
					}), 2000`

When I start typing Sys... the suggestion pops up : https://i.imgur.com/At4UPaH.png
Then when I click "." the methods pops up : https://i.imgur.com/9yADx8i.png
But when I start typing abort... which is the first method suggestion,  the other list pops up and replaces all the method list : https://i.imgur.com/1oWPBCU.png

How can I avoid getting other suggestions when i start typing words after ".'.

**Comment by marijnh** [comment]
Which language is this and which completion source are you using?

**Comment by marijnh** [comment]
So then it looks like the problem is coming from your code, and you'll have to debug it yourself.

**Comment by Nagendra080389** [comment]
Yep, understood the issue, thanks.
