### ISSUE TITLE
Missing Codemirror.js file

### ISSUE THREAD

**Issue by Pahkis** [codemirror/CodeMirror#5421]
Hi,

I downloaded the codemirror-master.zip file, extracted to my drupal site where it could not be found my drupal. On further investigation from the documentation, I found that the codemirror.js file was missing from the lib directory.

Under status report I get:
Patterns editor can be better visualized with CodeMirror. To enable CodeMirror support, download the library and copy it into the libraries folder (e.g. sites/all/libraries/codemirror/). Error: The version of the codemirror library could not be detected.

Under libraries report I get:
[codemirror ](http://www.mindsets.eu/pedles/lol_opigno-d7/admin/reports/libraries/codemirror)| Not detected |   | Patterns module | Homepage \| [Download](https://github.com/marijnh/CodeMirror/)

I did find another .zip version earlier but, that was not recognised either, perhaps because of being the wrong version: codemirror-5.36.0.zip.

Can someone please correct this or tell me where to find a correctly compiled version that drupal can recognise.

Many thanks,

Pahkis

**Comment by marijnh** [comment]
Don't download the zip from github—that just contains the code in the source repository. Get the library from npm or from the website, as described in the readme file.

**Comment by Pahkis** [comment]
Hi marijnh,

Thanks for the pointer :)

Installation Readme file sais:

Either get the [zip file](https://codemirror.net/codemirror.zip) with
the latest version, or make sure you have [Node](https://nodejs.org/)
installed and run:    npm install codemirror

The zip file is what I had before and is not detected even though the codemirror.js file is in the lib directory. That is why I went looking for it on git and found the codemirror-master.

According to drupal/project/node.js integration, It can be downloaded from [GitHub ](https://github.com/beejeebus/drupal-nodejs )or [NPM](https://www.npmjs.com/package/drupal-node.js)

Setup/installation requires to run `npm install` in the app's directory to install the
dependencies. In both cases, be sure the install the app outside of Drupal's root directory. 

Never used npm before - leaves me confused!

Do I just run the command from the cli or browser whilst in the node.js root directory? Or, do I need to install npm first as would have to do with Drush?
When they say outside of the drupal root directory, do they mean in some folder above it, in a sub-directory such as sites/all/libraries, or somehow add it to the php settings/hosting environment (for which no doubt I need help of hosting service provider)?

Kr,
Chris
