### ISSUE TITLE
chrome warning about deprecation of unescaped # in data URL body

### ISSUE THREAD

**Issue by guidorice** [codemirror/CodeMirror#5427]
Today I started seeing this warning from chrome 66 on OS X. I am having trouble reproducing it reliably. I am using the latest codemirror from cdnjs.cloudflare.com, tried some prior versions as well. This page is using as well mode/javascript,  addon/lint and addon/lint/json-lint.

Sorry all I have is screenshot at the moment:

![screen shot 2018-05-24 at 11 35 22 am](https://user-images.githubusercontent.com/766758/40502338-e147e218-5f47-11e8-841f-178632932903.png)

**Comment by guidorice** [comment]
A puzzler because the warning does not make sense in the context of the line of source shown.

**Comment by marijnh** [comment]
Yeah, CodeMirror does not in any way interact with URLs, so I don't think this problem has anything to do with the library.

**Comment by dsandstrom** [comment]
For what it's worth, Chrome is calling out this line for me: https://github.com/codemirror/CodeMirror/blob/2c741bd6742678f67e812307b2f78db4f4566d9d/src/display/update_display.js#L259 .

Error message: 
> Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
