### ISSUE TITLE
Slightly invalid JavaScript causes deep indenting

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#5431]
I often get complaints from users that indenting behaves very strangely by pushing their indent level far to the right. I think this happens in a few language modes, but I've isolated a case in JavaScript. If you go to https://codemirror.net/mode/javascript/ and paste in this code:

```js
class Test {
  emit(name, ...inputs) {
    this.subscriptions[name].forEach(callback => callback(...inputs);
  }
}
```

and then press return after the final brace, you'll find your cursor jumps to align with the `callback` variable. If you correct the code by adding a second closing parenthesis to line 3, this no longer happens.

I think it would be great if this didn't happen even in the invalid case. Is there a way to improve the robustness of the parser? I find that beginners very often commit errors of this nature and it would be nice to help them avoid wrestling with the autoindenter while they try to fix their code.

**Comment by marijnh** [comment]
Attached patch makes the problem slightly less annoying (it only deeply indents the first brace, then returns to normal). I think having indentation quirks for invalid code (there's not really such a thing as 'slightly invalid code') is expected and a useful hint that something is wrong, so I don't want to add more complexity to work around this.
