### ISSUE TITLE
Can't search whitespace followed by word using getSearchCursor()

### ISSUE THREAD

**Issue by diparthshah** [codemirror/CodeMirror#5433]
`searchq = new RegExp("^\\s*myword ")`
`editor.getSearchCursor(searchq)`

The following code snippet should work to search whitespace at start of line followed by "myword" string.
But it returns following error on console: https://hastebin.com/exoninaheg.pas

**Comment by marijnh** [comment]
If I run this at http://codemirror.net/demo/search.html it seems to work fine. Are you using the current CodeMirror version? If so, can you figure out what's different about your setup?

**Comment by diparthshah** [comment]
Search works fine when using search dialog functionality. But it doesn't works when i use above RegExp and pass it to `getSearchCursor()` . Other RegExp except above one works fine too.

**Comment by marijnh** [comment]
I meant I ran the code on the console, and it worked fine

**Comment by diparthshah** [comment]
Sir,
my string is : `       to myword`
string before to can vary.
Regular expression:  `searchq = new RegExp("^\\s*to myword")`
call:  `cursor = getSearchCursor(searchq)`

Any clue where i am going wrong ?

**Comment by marijnh** [comment]
Yes, you showed me the code before. I ran that exact code, it did not crash, so I'm asking you to figure out what you're doing differently in your setup

**Comment by diparthshah** [comment]
```coffeescript
    searchQuery = new RegExp("^\\s*to setup")
    cursor = @_editor.getSearchCursor(searchQuery)
    if !cursor.findNext()
      cursor = @_editor.getSearchCursor(searchQuery)
    @_editor.setSelection(cursor.from(), cursor.to())
```

**Comment by diparthshah** [comment]
@marijnh any issue with above code ?

**Comment by marijnh** [comment]
It'll call `from()` on a cursor that hasn't searched yet if the first search fails, which isn't supported (not sure why you'd create an identical cursor when the first doesn't work)
