### ISSUE TITLE
Page is not mobile friendly in google

### ISSUE THREAD

**Issue by merbin2012** [codemirror/CodeMirror#5434]
When I make the editor using codemirror, the google show it is not mobile friendly website. Is any possible to solve this problem? This problem will solve, if I increase the line spacing but I don't like to do it.
![screenshot-search google com-2018 05 31-11-11-12](https://user-images.githubusercontent.com/3687184/40763758-ac558066-64c3-11e8-9c86-b5f7df197f8a.png)

**Comment by marijnh** [comment]
I don't think there's anything CodeMirror can do about this.

**Comment by merbin2012** [comment]
It should solve by using the following code.

.CodeMirror {
    line-height: 19px !important;
}
