### ISSUE TITLE
Gutter overlaps text in ver 5.38.0

### ISSUE THREAD

**Issue by ifyapishore** [codemirror/CodeMirror#5439]
![image](https://user-images.githubusercontent.com/17021281/40837726-92f2478c-65c5-11e8-8c4c-73076458f022.png)

![image](https://user-images.githubusercontent.com/17021281/40838475-8939a0ac-65c8-11e8-8929-3bec5e4073ca.png)

style="left: 26px...." is incorrect

Configuration:

this.cm = CodeMirror.fromTextArea(textArea, {
            scrollbarStyle: 'null',
            lineNumbers: true,
            gutters: ['CodeMirror-linenumbers', 'as-codemirror-errors'],
            mode: 'htmlmixed'
        });

**Comment by adrianheine** [comment]
Closing this until there's further information on how to reproduce the issue.
