### ISSUE TITLE
MergeView initialisation error when orig == null and connect == 'align'

### ISSUE THREAD

**Issue by EmmanuelP** [codemirror/CodeMirror#5443]
Hi,

I've got an error in MergeView initialisation if in options no original content is set and connect is set to 'align'.

Here is my options content:
```
var editorOptions = {
			value: editableData.editable.data,
			origLeft: originalData,
			lineNumbers: true,
			lineWrapping: true,
			foldGutter: true,
			gutters: ['CodeMirror-linenumbers', 'breakpoints', 'CodeMirror-foldgutter'],
			matchBrackets: true,
			mode: editableData.editable.mime,
			autofocus: true,
			collapseIdentical: mergeViewActive,
			connect: 'align',
			cursorScrollMargin: 2,
			extraKeys: {
				"Ctrl-S": that.showLogDialog,
				"Ctrl-O" : 'toggleComment'
			},
			theme: "neat"
		};
```
where in some case originalData == null.

The error is: `TypeError: dv is null` here `merge.js:426:9 alignChunks`

I think CodeMirror should take care to check if no original data is set instead of throwing an error.

CodeMirror version is 5.38.0.

Cheers.

**Comment by marijnh** [comment]
Sorry, no, `origLeft` expects a string, and if you pass null instead, the problem is on your side. (Type-checking all input is too slow and bloats up the code.)

**Comment by EmmanuelP** [comment]
Understood. Thanks.
