### ISSUE TITLE
Scrollbars do not re-clip after resize followed by an operation

### ISSUE THREAD

**Issue by psybuzz** [codemirror/CodeMirror#5445]
Repro steps:
- Go to http://jsfiddle.net/tZVsS/556/
- Zoom multiple times (maybe 5 or 6 times)

Actual: the text inside CodeMirror gets clipped from the bottom
Expected: the text should not be clipped
Video of repro: https://imgur.com/a/pMFhnIm
Browser: Chrome 66.0.3359.181 and 69.0.3450.0
OS: Linux, Mac, possibly windows too

Hello there!

In CodeMirror, there seems to be some "scrollbar clipping" logic that helps ensure that CodeMirror's scrollbar is hidden.  Its "resize" handler seems to throttle itself every 100ms, and sets `d.scrollbarsClipped = false` to indicate that clipping needs to be updated soon.

In my website, I'd like to start CodeMirror operations within my own window "resize" handler, which seem to interfere with scrollbar clipping.  I'm not very familiar with CodeMirror internals, but perhaps this could be fixed just by setting:
`d.scrollbarsClipped = false`
inside refresh()?  Refresh already clears caches and forces an update, but it doesn't force scrollbar clipping.

Thanks for taking a look!

**Comment by marijnh** [comment]
`onResize` was using the last editor size in a way that wasn't reliable. I've made it always recalculate things in attached patch.

**Comment by psybuzz** [comment]
That makes sense.  Thank you for the quick fix!
