### ISSUE TITLE
:g/^foo/s/$/bar/ gives "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#5450]
1. Go to https://codemirror.net/demo/vim.html
2. Type in the following two lines as its contents:

word: "a
word: "b

3. Execute the vi command :g/^word/s/$/"/

Result: A JS error occurs "RangeError: Maximum call stack size exceeded"

**Comment by marijnh** [comment]
Should be solved via #6593
