### ISSUE TITLE
Hint Addon: Unable to display relevant matches

### ISSUE THREAD

**Issue by diparthshah** [codemirror/CodeMirror#5453]
I have defined new registerHelper for my language to integrate hint addon in my code. I have already included `show-hint.js` and `show-hint.css` and registerHelper code. I am accurately getting a completion dialog on keypress and array of strings binded with them but the problem is upon writing in the editor it does not match relevant string from the completion dialog. My complete project is in coffeescript so attaching registerHelper code snippet and a screenshot. 
Code:
```CoffeeScript
CodeMirror.registerHelper('hint', 'netlogo', (editor, options) ->
  cur = editor.getCursor()
  curLine = editor.getLine(cur.line)
  end = cur.ch
  start = end
  return {list: window.keywords.all, from: CodeMirror.Pos(cur.line, start), to: CodeMirror.Pos(cur.line, end)} )
```
`window.keywords.all` is array of strings which is to be displayed in completion dialog. 

Screenshot: 

![cm](https://user-images.githubusercontent.com/13984495/41194985-8904cde8-6c42-11e8-9229-96fdde68a3b7.png)

Any suggestions/advice is highly appreciated. 
Thank You.

**Comment by marijnh** [comment]
Your completion function is responsible for only returning relevant results. Look into `hintWords` instead, which is a way for you to just register a list of words and having the hint addon automatically show them (see the way the python mode uses it, for an example).
