### ISSUE TITLE
Persistent search

### ISSUE THREAD

**Issue by rinu** [codemirror/CodeMirror#5456]
I tried adding the search addon to my editor. The normal search works fine but persistent search (Alt+F) does not. It works in the [demo](https://codemirror.net/demo/search.html) but not on my site.
Even if it did work, I would like the default (Ctrl+F) to be persistent search instead. Is it possible to configure this?

I'm using codemirror 5.38.0 with Vue. Chrome 67 on Ubuntu 18.04.

**Comment by marijnh** [comment]
> It works in the demo but not on my site.

You'll have to figure out the relevant difference, then.

> I would like the default (Ctrl+F) to be persistent search instead. Is it possible to configure this?

Yes, bind that key combination to the `"findPersistent"` command, using `extraKeys` with a value like `{"Ctrl-F": "findPersistent"}`.

**Comment by rinu** [comment]
I found the `extraKeys` option hidden in the demo. Works perfectly now, thanks.
