### ISSUE TITLE
CodeMirror: Indentation not working on String

### ISSUE THREAD

**Issue by Nagendra080389** [codemirror/CodeMirror#5458]
I would like to apply indentation while writing my code in text area, for this I have this `renderLine` event like this.

                        `setTimeout(function(test) {
                var editor = CodeMirror.fromTextArea(document.getElementById('javaBody'), {
                    lineNumbers: true,
                    matchBrackets: true,
                    styleActiveLine: true,
                    extraKeys: {
                        ".": function(editor) {
                            setTimeout(function() {
                                editor.execCommand("autocomplete");
                            }, 100);
                            throw CodeMirror.Pass; // tell CodeMirror we didn't handle the key
                        }
                    },
                    gutters: ["CodeMirror-lint-markers"],
                    lint: true,
                    mode: "text/x-java"
                });
                editor.markClean();
                editor.on("keyup", function(cm, event) {
                    var keyCode = event.keyCode || event.which;
                    if (!ExcludedIntelliSenseTriggerKeys[(event.keyCode || event.which).toString()]) {
                        if (timeout) clearTimeout(timeout);
                        timeout = setTimeout(function() {
                            editor.showHint({
                                hint: CodeMirror.hint.auto,
                                completeSingle: false
                            });
                        }, 150);
                    }
                });
                var charWidth = editor.defaultCharWidth(),
                    basePadding = 4;
                editor.on("renderLine", function(cm, line, elt) {
                    var off = CodeMirror.countColumn(line.text, null, cm.getOption("tabSize")) * charWidth;
                    elt.style.textIndent = "-" + off + "px";
                    elt.style.paddingLeft = (basePadding + off) + "px";
                });
                editor.refresh();
                globalEditor1 = $('.CodeMirror')[0].CodeMirror;
                if (localStorage && localStorage.getItem('javaEditorTheme')) {
                    globalEditor1.setOption("theme", localStorage.getItem('javaEditorTheme'));
                }
                //globalEditor1.(localStorage.getItem('javaEditorTheme'));
            }), 2000`

I have even applied autoindentation while saving like below:

`editor.indentSelection("smart");` 

But still it does not correct String parameters:

For example : 

   `  public static String getAnimalNameById(Integer x){
    Http h = new Http();
    HttpRequest req = new HttpRequest();
	req.setEndpoint("https://th-apex-http-callout.herokuapp.com/animals/ad as dnaskd nlas fnasklnflaksn falsk fna;ksnflajsbfnaksn flasn fkasnf ansfkansfans f.ans .fnas. fnas fnas fnasnf asnf asnfa jsbfaks bfkasb fkasbf kasbfk absfba sf" + x);

    req.setMethod("GET");
  }`

In the above code it will indent the code but wont try to split `setEndPoint` the string in two lines with `'+'` sign.
Is there a way to implement this?

**Comment by marijnh** [comment]
> Is there a way to implement this?

Not inside CodeMirror, but you might be able to find a code formatting tool that you can run on a string, and then put the formatted string back into the editor.

**Comment by Nagendra080389** [comment]
@marijnh 
But how to detect inside codemirror that the sentence is a String? So that I can pull that out and pass it through my code while running indentation from CodeMirror?

**Comment by marijnh** [comment]
You could maybe use [`getTokenAt`](http://codemirror.net/doc/manual.html#getTokenAt).
