### ISSUE TITLE
[Question] coordinates of change AFTER it was processed

### ISSUE THREAD

**Issue by ehhc** [codemirror/CodeMirror#5460]
Hi,
i would like to react on a change in the editor. Unfortunately the "change" event only contains the positions in the pre-change coordinate system. Is there a way to get the *post-change* coordinates as well? 

Thanks for your great editor btw :)

**Comment by marijnh** [comment]
Not easily, but in the `"changes"` events (which always gives you the full set of changes) you can compute them by 'mapping' positions forward to any changes that come after it (see also the [`changeEnd`](http://codemirror.net/doc/manual.html#changeEnd) utility).

(We're working on a redesign which will make this kind of thing _much_ easier, but for now, it's rather bad.)
