### ISSUE TITLE
Style textarea before highlighting to avoid page "shaking".

### ISSUE THREAD

**Issue by BoPeng** [codemirror/CodeMirror#5462]
I have long HTML documents exported from Jupyter notebooks (e.g. [this page](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Syntax.html)) that consists of a bunch of `textarea`s and are styled by codemirror one by one after the page is loaded. The HTML pages are structured as follows:

```
<textarea class="sos-source">
source code
</textarea>
...
      <script>
		   function highlight_cells(cells, i, interval) {
			  setTimeout(function() {
				var editor = CodeMirror.fromTextArea(cells[i], {
		           ...
		         });
		      if (i < cells.length)
			    highlight_cells(cells, i + 1, interval);
			}, interval);
		  }

	      highlight_cells(document.getElementsByClassName("sos-source"), 0, 10);
      </script>
```

The page looks more or less ok if I start from the beginning of the page because the highlighting is done in the background. However, if I [jump to the middle of the page](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Syntax.html#Makefile-style-workflow--174)), the textares will first be displayed as non-styled textarea, the page will shake for a few seconds (because the textareas before the anchor point are being rendered) before the current location is rendered.

Suppose that I cannot speed up codemirror highlighting because there are too many textareas, is there a way to style the textareas so that they appear with identical font and size as highlighted textarea so that codemirror will appear to just "color" the text?

**Comment by marijnh** [comment]
>  is there a way to style the textareas so that they appear with identical font and size as highlighted textarea so that codemirror will appear to just "color" the text?

Sure, just make sure the CSS font, font-size, line-height, and margins for the textareas match the style of the editor.

**Comment by BoPeng** [comment]
I have tried, but it is very difficult to determine the height of the textarea. I used

```
 $('textarea').each(function() {
	 $(this).height($(this).prop('scrollHeight'));
	 });
```
but `scrollHeight` does not equal to the height of codemirror rendered areas in some cases.

**Comment by BoPeng** [comment]
For example,

![image](https://user-images.githubusercontent.com/9889312/41569234-c4ac304a-732f-11e8-82ba-c155dd573ccc.png)

I can duplicate the height of textarea, in the above example, to be `143.768` which is identical to `Codemirror-lines` as shown in the figure. However, a `Codemirror-sizer` `div` for whatever reason decides the `min-height` should be `144`. Without duplicating the sizer behavior, my textarea will be slightly smaller than codemirror. It is a small difference but in a long document like what I have, the accumulative effect is quite visible at the end.
