### ISSUE TITLE
[vim] after text insertion, the . cmd is doubling the inserted characters.

### ISSUE THREAD

**Issue by swframe** [codemirror/CodeMirror#5464]
I'm using version 5.38.1 and I noticed that the '.' command doubles the last text insertion to cause 
double characters. For example, if I insert text "abc" and then move to a new location and press '.',
vim inserts "aabbcc". I do this all the time so I noticed the regression today.

**Comment by defcc** [comment]
You could check the latest version here https://codemirror.net/demo/vim.html. I test your case with Chrome/Mac, it works as expected.

**Comment by swframe** [comment]
You are correct; it is working correctly at the demo site. Thanks for test it. I can close the issue.
