### ISSUE TITLE
change event origin is undefined when text is selected and push single quote to wrap it

### ISSUE THREAD

**Issue by m44-io** [codemirror/CodeMirror#5465]
So this was found by creating a live save per keystroke on the editor and then it not saving after I wrapped a string in single quotes by selecting it and using the single quote ky as a shortcut to wrap it...

I know its a bug in code mirror because origins should never be undefined right? Shouldn't this be +input?

**Comment by marijnh** [comment]
No, undefined origins are definitely okay—if you call `replaceRange` without providing an origin, as the bracket matching addon does, that's what you get. Origins are an optional piece of metadata, and you can't count on them being there for every change.
