### ISSUE TITLE
customElement support?

### ISSUE THREAD

**Issue by kkimdev** [codemirror/CodeMirror#5468]
It will be really nice if we can use customElement syntax, e.g.,

```html
<code-mirror mode="javascript" theme="dracula">
function thisIsSomeJavaScript() {
  console.log('hello!')
}
</code-mirror>
```

There is a separate package for this, https://github.com/hughsk/element-codemirror , though since customElement is standard and also a nicer API, I think it makes sense to incorporate to the main repository.  Also the implementation is small and pretty straightforward as far as I can see.

**Comment by marijnh** [comment]
No, this is out of scope for the core library. Even if all major browsers supported custom elements (they don't), it's not clear at all yet that they are the right way to go in, so this library is going to remain agnostic to them.
