### ISSUE TITLE
SQL parameter hints?

### ISSUE THREAD

**Issue by MichaelBelgium** [codemirror/CodeMirror#5469]
This worked before but after some updates it does not anymore. I guess it's been deleted? 
What to use instead? Can't find anything useful in the docs.

```
hintOptions: {
    parameters: [":foo", ":bar"],
    tables: {
        "sometable":  [ "column1", "column2", "column3", "column4" ]
    }
}
```

**Comment by marijnh** [comment]
I'm not sure what `parameters` is supposed to do, but, assuming you're using the sql hinter, `tables` should still work.

**Comment by MichaelBelgium** [comment]
The `parameters` worked as hints next to the `tables`, if I did ctrl+space it showed the tables and the parameters. But the `parameters` part doesn't work anymore. Either I missed something or this worked before but wasn't intend to do.

**Comment by marijnh** [comment]
I don't remember ever having that feature, but then, I don't keep all that close track of sql-hint.js. You can try digging through the git history to see if it ever existed, and if you find it, try to port it forward.

**Comment by MichaelBelgium** [comment]
Well, is there any other alternative to add custom hints to sql-hint otherwise?
