### ISSUE TITLE
Bug in indentation

### ISSUE THREAD

**Issue by jdbruxelles** [codemirror/CodeMirror#5471]
I recently added the feature to display the invisible characters (spaces) in my application, but when I create a new line, the indentation is not respected. It's done x5 or more.

In fact, there is an issue only when I make a new line in a `script` or `style` tag. The bug occurs even if `showInvisibles` is disabled.
But not in HTML structure. I let the picture tell you more.

- I use the latest version of CodeMirror, 5.39.0

Here's a screenshot of what it looks like:
![localhost_8080___dev index html_modal setting](https://user-images.githubusercontent.com/18559798/41808713-e968acaa-76e1-11e8-937b-5b557bbe31b2.png)

**Comment by jdbruxelles** [comment]
I think the issue is somewhere in the update.

**Comment by marijnh** [comment]
> I recently added the feature to display the invisible characters (spaces) in my application,

Seems like it would be useful to know _how_ you implemented this.

**Comment by jdbruxelles** [comment]
I have loaded the [show visible code](https://github.com/coderaiser/cm-show-invisibles/blob/master/lib/show-invisibles.js) after codemirror.js. Then I set the option show invisibles by `editor.setOption("showInvisibles", true)` and keep `maxInvisibles: 16` as default.

**Comment by jdbruxelles** [comment]
Can you see that? I restored `codemirror.js` to version `5.36.0` while keeping the other files on `5.39.0` and oddly, it seems that the problem has disappeared.

**Comment by jdbruxelles** [comment]
There was a cache issue. Sorry and thanks ;-)

**Comment by jdbruxelles** [comment]
Hi,
I don't know why but the issue persists :-/

**Comment by jdbruxelles** [comment]
The issue is solved. I was just getting the `tabSize` and `indentUnit` as a string from cookies. It looks like they must be numbers, so I use `Number()`.
