### ISSUE TITLE
Use codemirror and cssLint: how ignore some CSSLint Warnings?

### ISSUE THREAD

**Issue by Sophia-nguyen** [codemirror/CodeMirror#5473]
Hi all,

I used Codemirror with CSS mode as demo https://github.com/codemirror/CodeMirror/blob/master/demo/lint.html.
But many warnings about "qualified heading, adjoining class ... " are shown.
How can I ignore all warnings?
This is a link for issue details: https://stackoverflow.com/questions/50966678/codemirror-and-csslint-how-ignore-some-rules
Thanks,

**Comment by marijnh** [comment]
You can add an `options` field to the value you give to the `lint` CodeMirror option, which will be passed through to `CSSLint.verify`, and can probably be used to configure stuff like this.

**Comment by Sophia-nguyen** [comment]
Thanks @marijnh, and could you please help me for example:
This is my code 

```
this.cssEditor = CodeMirror.fromTextArea(this.element.find("#cssEditor")[0], {
     lineNumbers: true,
     mode: "css",
     gutters: ["CodeMirror-lint-markers"],
     lint: true
});
```
How can I add options?

**Comment by Sophia-nguyen** [comment]
Thanks @marijnh, I'm using an old version, I will update and try that.
