### ISSUE TITLE
Possible to expose doc.makeChange as API to apply change object

### ISSUE THREAD

**Issue by futurist** [codemirror/CodeMirror#5474]
I have the demand to make changes of doc programmatically, like simulate user inputs, and noticed there's a `function makeChange(doc, change, ignoreReadOnly) {}` method in file `src/model/changes.js` which seems to do the job but not exposed to API, so the question is:

1. Is it possible for applying a changeObj to a doc using `makeChange` function, or has another better way?

2. Is it possible to expose such an API?

Thanks!

**Comment by marijnh** [comment]
Why don't you just go through `replaceRange`?

**Comment by futurist** [comment]
Ah, noticed `replaceRange` is a good wrapper for `makeChange `, thank you very much!
