### ISSUE TITLE
[merge] Can't `setGutterMarker` on right hand gutter

### ISSUE THREAD

**Issue by vsaranea** [codemirror/CodeMirror#5481]
I am trying to add a button to each line in a diff view.
The diff view is not editable, but the button will do something with that specific line.
Currently, I am doing: 

```typescript

// MergeView called with { gutters: ["CodeMirror-linenumbers", "new-comment"] }

function AddCommentButton(doc: CodeMirror.Doc) {
    doc.eachLine((line: CodeMirror.LineHandle) => {
        let newAnnotationButton = document.createElement("div");
        newAnnotationButton.classList.add("new-comment", "octicon", "octicon-comment");
        (doc as any).setGutterMarker(line.lineNo(), "new-comment", newAnnotationButton);
    });
}
```

This works, more or less, but I cannot get the right hand gutter to also have these gutter markers.
I have tried using `iterLinkedDocs`, it does not iterate through any.

Also, just in case you care, the typescript definition files for codemirror are very sadly out of date.

**Comment by marijnh** [comment]
Gutter markers are not shared between linked documents, so you'll have to manually arrange for them to be added to the other documents (at the right lines) to do something like that.

**Comment by vsaranea** [comment]
How do I get access to the second document?

**Comment by vsaranea** [comment]
Thanks.

Is there any way to have a simple diff view, without having to pass in a `value` or `orig` (i.e. how to I just pass in an `old` and `new`?). It is non-editable (`allowEditingOriginals: false`), and I just want to deal with it in the simplest way possible.

Currently I am using `origLeft` and `value` together, but then I can't access `.right.chunks`?
Or is there a way to get a `.value.chunks` equivalent?

**Comment by vsaranea** [comment]
I got it working:

```
function AnnotateDiffBar(diffView: CodeMirror.MergeView.MergeViewEditor) {
    var chunks = diffView.leftChunks();

    var leftAnnotations = (diffView.leftOriginal() as any).annotateScrollbar('marker');
    var rightAnnotations = (diffView.editor() as any).annotateScrollbar('marker');

    var ranges = [];
    for (var i = 0; i < chunks.length; i++) {
        var rangeEnd = chunks[i].editTo - 1;
        if (chunks[i].editTo < diffView.editor().getDoc().lineCount() && i < 4) {
            rangeEnd = rangeEnd + 1;
        }
        ranges.push({ from: { line: chunks[i].editFrom }, to: { line: rangeEnd } });
    }

    leftAnnotations.update(ranges);
    rightAnnotations.update(ranges);
}
```


Thanks for the assistance!
