### ISSUE TITLE
Configure with mode & value:Doc

### ISSUE THREAD

**Issue by correnson** [codemirror/CodeMirror#5483]
Hi fantastic maintainers of CodeMirror !

I found a minor issue when configuring a CodeMirror instance with both a document and mode in constructor options. It seems that mode option is not taken into account, unlike other options:

```javascript
const elt = /* some div element */
const doc = new CodeMirror.Doc('//Hello World !\nconst a = 1;');

// case 1 : does not work
const cm = new CodeMirror( elt , { value: doc, mode: 'javascript', readOnly : true } );

// case 2 : does work
const cm = new CodeMirror( elt , { value: doc, readOnly : true } );
cm.setOption('mode' , 'javascript' );
```

To reproduce (Safari and Chrome) :  [cmbug.zip](https://github.com/codemirror/CodeMirror/files/2162371/cmbug.zip)

**Comment by marijnh** [comment]
Not sure how that wasn't caught in the several years since first-class `Doc`s were introduced... but attached patch fixes it!

**Comment by correnson** [comment]
Great!
