### ISSUE TITLE
Bug: there's sth wrong with position

### ISSUE THREAD

**Issue by MatzYang** [codemirror/CodeMirror#5485]
Content:   
```json
{
  "id": "100",
  "state": {
    "code": 5000038,
    "msg": "服务器异常！",
    "tips": ""
  }
}
```

Options:  
```
lineNumbers: true,
mode: 'application/json',
gutters: ['CodeMirror-lint-markers', 'CodeMirror-linenumbers', 'CodeMirror-foldgutter'],
theme: 'eclipse',
foldGutter: true,
readOnly: this.readOnly,
lint: true,
autoRefresh: true
```

![image](https://user-images.githubusercontent.com/1445225/42275664-9bc736b6-7fc3-11e8-897b-7a0ce8ec5902.png)

How to fix this issue

**Comment by marijnh** [comment]
You're going to have to set up a self-contained example (for example on jsbin.com or glitch.com) if you want us to debug this.

**Comment by MatzYang** [comment]
I were solve this issue by call refresh method after setValue method.
