### ISSUE TITLE
Rendering issue at first (slow) load

### ISSUE THREAD

**Issue by bgadrian** [codemirror/CodeMirror#5488]
Hello, I have a weird rendering issue, and I guess (but I'm not sure) that it has something to do with CodeMirror. 

At the first load of the page, when syntax is on and the page is loading slow, not all the div-lines elements are rendered (for the entire source code). At any re-rendering the issue is fixed. 

The [original issue is here](https://github.com/golang/tour/issues/544)
Video: ![video](https://user-images.githubusercontent.com/830001/42249973-e751c4b2-7f36-11e8-839b-b5e0ebbe7aae.gif)

I haven't worked with this library before, I managed to do some debug but I got stuck.

Somehow, in `updateDisplayIfNeeded` at the first render of the page, the `update.to` and `update.visible.to` is 1 instead of 29 (the number of lines). 

The issue only happens on Chrome when the page is loading slow. The website is using Angular, if that matters.

Can I get any help? I don't know where to look further. 

Updating the codeMirror to the latest version didn't helped.
Thanks.

**Comment by marijnh** [comment]
CodeMirror tries to render only the visible part of the document. When it's initialized before the layout has reached its final state (because CSS hasn't been loaded or its container is hidden or not in the DOM yet), it might render the wrong lines. You can arrange to call the `refresh()` method when the page has finished loading, or delay initializing CodeMirror until the layout is stable, to work around this.

**Comment by bgadrian** [comment]
Thank you! Can you pinpoint to the code that gets the element height? Maybe it helps me to find the problem.

The first refresh is done after the Document.load so the CSS should be stable at that time.

**Comment by marijnh** [comment]
The `visibleLines` function in src/display/update_lines.js computes the area that is to be drawn.

**Comment by bgadrian** [comment]
I can confirm that it is a layout issue, the `clientHeight` in `visibleLines` was the source of the bug, so it was not the fault of CodeMirror. 

Thanks for the assistance!
