### ISSUE TITLE
Width is calculated to be far too big if the file contains a large line.

### ISSUE THREAD

**Issue by vsaranea** [codemirror/CodeMirror#5491]
This occurs for me for both merge view and regular codemirror views.

Working with a diff with regularly sized lines of code:
![workingsmalldiff](https://user-images.githubusercontent.com/39252615/42431096-a9646af2-8386-11e8-8138-558b9ead2667.PNG)

However, when you change to viewing a file which has longer lines of code in it, the codemirror div expands to try and fit the largest line of code in the file:
![brokenlargediff](https://user-images.githubusercontent.com/39252615/42431092-a8d3873a-8386-11e8-9cfe-1dbc89f13978.PNG)

You can stretch it across two monitors to view the scroll bar again:
![workinglargediff](https://user-images.githubusercontent.com/39252615/42431094-a9065020-8386-11e8-9259-3da65241918f.PNG)

And then scroll down to find the lines causing the issue (even though if they're large enough it still can't fit them in view):
![workinglargediffshowinglargelines](https://user-images.githubusercontent.com/39252615/42431095-a937297a-8386-11e8-9b01-b2281fc24c72.PNG)

To show you the DOM layout, I've screen captured a few different elements across two screens:

Firstly, the "root" element for this structure, which has the correct (bounding) width.
![image](https://user-images.githubusercontent.com/39252615/42431678-546a6228-838a-11e8-83f8-d380ff3bcacd.png)

When I replace the CM div with just a 100%width/height coloured div, it works exactly as intended.
The distortion of size only occurs once CM has loaded and parsed the file.

Secondly, the wrapper element for the codemirror div and a few other pieces, which have no width property set.

![wrapper-width](https://user-images.githubusercontent.com/39252615/42431370-774eb0e8-8388-11e8-8cd4-c29acd2fa373.PNG)

Thirdly the div which I give to codemirror to do the editing, which you can see has the width that the wrapper element has (i.e. showing that codemirror is setting the width for the parent)
![div-given-to-codemirror-width](https://user-images.githubusercontent.com/39252615/42431455-d8499020-8388-11e8-96aa-7f8d88deb039.PNG)

Finally one of the divs that codemirror itself creates:
![codemirror-internal-width](https://user-images.githubusercontent.com/39252615/42431461-e162e81e-8388-11e8-9da4-7f24461404b9.PNG)

(and just to show that it happens with non-merge view as well):
![singleeditor-width](https://user-images.githubusercontent.com/39252615/42431500-31928560-8389-11e8-95d4-e721c602021f.PNG)

I could be setting up my css wrong for this width malarkey, so I'm happy to try out any suggestions.
(Also, you can see that I can't get vertical resizing of the merge view working correctly. I'd appreciate any help in this area as well).

In fact, I can't get vertical resizing for views to properly respect the parent divs maxHeight either, which might be related:
```
        // Where codeOptions has viewportMargin: Infinity
        var codeView = CodeMirror(codeDiv, codeOptions);

        codeDiv.style.maxHeight = "100vh";
        codeView.setSize(null, "auto");
```
![image](https://user-images.githubusercontent.com/39252615/42431575-d0640fa6-8389-11e8-9a42-24f35e377040.png)

**Comment by marijnh** [comment]
Is the editor, by any chance, directly in a flexbox container? If so, adding another intermediate `<div>` around it might help with this.

**Comment by vsaranea** [comment]
Unfortunately no, there's no flex directly involved. 

Based on your suggestions, I've tried adding a div wrapper, as well as setting that div (and even the <td> parent) to display:block/table-layout:fixed. Still no luck :(

**Comment by vsaranea** [comment]
Could this be because it's in a table?

**Comment by vsaranea** [comment]
Got it working by setting the parent's parent's div container's width directly (and not relying on flex-xxx, especially flex-basis)
