### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by reachnithya18** [codemirror/CodeMirror#5492]
Hi,

I am having angular 5 application when i build an app everything is fine.fter build i am unable to view the file

node dist/server.js
node_modules/codemirror/lib/codemirror.js:18
var userAgent = navigator.userAgent;
                ^

ReferenceError: navigator is not defined
  node_modules/codemirror/lib/codemirror.js:18:17
    at userAgent (node_modules/codemirror/lib/codemirror.js:11:82)
    at Object.<anonymous> (node_modules/codemirror/lib/codemirror.js:14:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

Please help me to solve the problem.

**Comment by defcc** [comment]
The same issue as https://github.com/codemirror/CodeMirror/issues/5470

**Comment by marijnh** [comment]
Right, and also the same answer—CodeMirror doesn't do anything useful outside of the browser, and is currently not set up to be loadable in such an environment.

**Comment by atteeela** [comment]
@marijnh We are trying to pre-render with Server Side Rendering and then shown to the user ahead of time.

Do you have any suggestions on the best way we can overcome this problem?  Perhaps we can detect `navigator` or just node load Code Mirror when we are rendering via SSR.

Thanks,

**Comment by anasbehhari** [comment]
For nextJS that might work
**For calling the Editor**
`import dynamic from "next/dynamic";
const CodeWithCodemirror = dynamic(import("./components/Editor"), {
  ssr: false,
});`

**The code for Editor component**

![image](https://user-images.githubusercontent.com/66890714/107556151-58b07780-6bd8-11eb-9938-4544eff7e489.png)
_Text :_
import React, { Component } from "react";
import { UnControlled as CodeMirror } from "react-codemirror2";
import "codemirror/mode/xml/xml";
import "codemirror/lib/codemirror.css";
import "codemirror/theme/oceanic-next.css";
const editor = (props) => {
  const {value,readOnly,className} = props
  return (
    <CodeMirror
      {...props}
      className={className ? className : ""}
      value={value}
      options={{
        theme: "oceanic-next",
        mode: "xml",
        autocorrect: true,
        readOnly: readOnly ? readOnly : false,
      }}
    />
  );
};

export default editor;
