### ISSUE TITLE
workTime and workDelay configuration options have no effect.

### ISSUE THREAD

**Issue by alistaircolling** [codemirror/CodeMirror#5493]
**Steps to reproduce**

1. Create an instance of CodeMirror with `workDelay` set to 3000 ms:

```
    this.editor = CodeMirror.fromTextArea(this.ref, {
      lineNumbers: false,
      worktime: null,
      mode: 'quoql',
      theme: 'quoql',
      singleLine: true,
      grammarHelper: true,
      cursorHighlight: 'property',
      workDelay: 3000, 
    });
```

2. Type some text into the input field

**Expected Behaviour**
Highlighting does not happen for 3 seconds

**Actual Behaviour**
Highlighting happens almost immediately, there is no change from removing this value altogether.

**Comment by marijnh** [comment]
Re-highlighting of the edited line is intentionally synchronous, to avoid color flickering. The work settings only affect background highlighting. For example, when scrolling to the bottom of a big document and then programatically adding a block comment start marker to the start of the document, you should be able to see the effect of these options.
