### ISSUE TITLE
extraKeys without the editor being focused

### ISSUE THREAD

**Issue by jdbruxelles** [codemirror/CodeMirror#5495]
Hi,
I want to trigger some keyboard shortcuts but if the editor (textearea) is not focused, nothing will happen.
I have tried `window.addEventListenner("keydown", function (e) { ... });` but I still have to focus the cursor on the editor for it to trigger.

Is there any way to avoid that?

**Comment by marijnh** [comment]
You'd have to write your own key event handlers and attach them to the window. Shortcuts registered in the editor will only be handled when the event occurs when the editor is focused (and this is by design).

**Comment by jdbruxelles** [comment]
My extra shortcuts are not in CodeMirror extraKeys, they are in window key event.  
Yet that's what I did. But it's as if CodeMirror forces window shortcuts events to go through it. Then I have to focus on the textarea.

**Comment by marijnh** [comment]
CodeMirror doesn't register any window-wide keyboard event handlers. Possibly you're confusing focusing the window with focusing the editor. If you put another input field in the page and focus that, do the keyboard handlers fire?

**Comment by jdbruxelles** [comment]
Yes, they trigger when I focus another textarea.

**Comment by jdbruxelles** [comment]
It's Ok. I've attached the `keydown` event to the `document` and shortcuts work inside and outside of textarea. Thank you.
