### ISSUE TITLE
Language modes didn't support "Batch"

### ISSUE THREAD

**Issue by Ly-lns** [codemirror/CodeMirror#5497]
Language modes didn't support "Batch".

**Comment by marijnh** [comment]
This sounds like a feature request for a new mode (though it's a bit too cryptic to be sure). We're not adding new modes to the distribution, so if you want a new mode, you'll have to build it yourself.

**Comment by FranzDeschler** [comment]
I know it´s a little late, but maybe others also look for a "Batch" mode.
I created such a mode by myself. You can find it here:
https://codestore.cloud/public-snippets/6799646300799306030
Hope this helps.

**Comment by tifish** [comment]
Batch files are still widely used under Windows. I found Typora does not support batch file syntax, which they said should be added to CodeMirror. Can @FranzDeschler 's code be added as batch mode?

**Comment by marijnh** [comment]
As I said above, no, we are not adding more mode files, and you'd have to implement and distribute this separately.
