### ISSUE TITLE
CodeMirror with Blockly creates multiple CM divs

### ISSUE THREAD

**Issue by immigrantsheep** [codemirror/CodeMirror#5502]
I'm using blockly inside a webapp and I have a textarea that displays the generated python code from blockly. Whenever I updated the blocks, it automatically refreshes the python code. That part works fine. But when I add CodeMirror into the mix, each time the code gets updated, I end up with a new <div= "CodeMirror">. And sometimes it's even more than one new div for every new added block in blockly. 

Another issue is that when I reload the page, the CodeMirror textarea retains the previous state. 

The code I'm calling is:
```
editor = CodeMirror.fromTextArea(document.getElementById("code"), {
          mode: {name: "python",
                version: 3},
          lineNumbers: true,
          indentUnit: 4
      });
```
I tried to call it when blockly changes it's code or on click events but I still end up with the same result.

**Comment by marijnh** [comment]
I don't know what's happening here, but it seems like the problem is one of the way you're integrating with blockly, not something CodeMirror can help.
