### ISSUE TITLE
ABAP Sytax Highlighting

### ISSUE THREAD

**Issue by Tiberriver256** [codemirror/CodeMirror#5503]
Would love to see this

**Comment by marijnh** [comment]
We're not taking requests for modes, or even adding new modes to the main distribution in general. You'll have to implement (and distribute) this yourself.

**Comment by williamstein** [comment]
> We're not taking requests for modes, or even adding new modes to the main distribution in general. You'll have to implement (and distribute) this yourself.

Would you consider having a page that links to "community supported modes"?    Basically, an analogue of https://github.com/primus/primus#community-plugins for codemirror.    For example, I've written modes (for use in https://cocalc.com), and will be writing more...

**Comment by marijnh** [comment]
There's an (incomplete) list [here](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons#external-modes). Extending that and adding a link to it from mode/index.html would be welcome.
