### ISSUE TITLE
Allow markers to have custom payload

### ISSUE THREAD

**Issue by viridium** [codemirror/CodeMirror#5504]
To make a marker work, we'd like support for payload as a first-class concept. For instance:

```
let options = { payload: { ... } };
markText(..., options);

let marker = ...;
let payload = marker.getPayload();

```

**Comment by marijnh** [comment]
You can already do this—properties added on the options are present on the marker object. (Yes, this is a shaky hack, and in the next redesign of the API I'd work differently, but for now, it should suit your use case.)
