### ISSUE TITLE
Color matching brackets for Clojure

### ISSUE THREAD

**Issue by viebel** [codemirror/CodeMirror#5506]
Is it possible in Clojure mode, to color each matching brackets in a different color in a similar way as the [rainbow brackets extension for IntelliJ](https://plugins.jetbrains.com/plugin/10080-rainbow-brackets)?

**Comment by marijnh** [comment]
You could write an addon that does that, but the existing Clojure mode doesn't (and I consider it outside of the scope of modes to do this).
