### ISSUE TITLE
Codemirror site/manual is not easy to be read from a colour-blind user

### ISSUE THREAD

**Issue by keul** [codemirror/CodeMirror#5508]
I'm a colour-blind person, with a light impediment but still It's not easy for me to find links inside the Codemirror documentation.

Example:

![invisible-link](https://user-images.githubusercontent.com/284924/43075955-c229f7e4-8e82-11e8-99d2-89b22311ff62.png)

Just an old-school underline could be enough.

**Comment by marijnh** [comment]
Thanks for letting us know. Attached patch restores the underlines.
