### ISSUE TITLE
[Markdown] Bold followed by a hyphen on the next line becomes a header

### ISSUE THREAD

**Issue by michaelgmcd** [codemirror/CodeMirror#5510]
![bullet-bug](https://user-images.githubusercontent.com/8161781/43153522-8053102c-8f3f-11e8-913d-a4dd5a0993ee.gif)

**Comment by defcc** [comment]
IMHO this should be an expected behavior, as Codemirror markdown mode is live preview.

**Comment by javisperez** [comment]
Have the same problem. Also happens with star characters (*). Did you find any fix @michaelgmcd ?

**Comment by michaelgmcd** [comment]
I accepted this as the expected behavior. I haven't thought much about workarounds.

**Comment by adrianheine** [comment]
I think this behavior matches the spec, see [example](https://spec.commonmark.org/dingus/?text=**bold**%0A-%20).
