### ISSUE TITLE
closebrackets addon: configure the end of statement characters

### ISSUE THREAD

**Issue by tophf** [codemirror/CodeMirror#5512]
As you can observe in the [demo](https://codemirror.net/demo/closebrackets.html) by typing `(` right before `;` on any line, it won't add the closing `)`, which is quite inconvenient in cases where you switch from a function reference to a function invocation, for example. That is, from `foo = bar;` to `foo = bar(whatever);`

Currently the only way to circumvent this is to add `;;` to the `pairs` option i.e. pass `()[]{}''"";;` - quite a hack I'd say, especially if you want to allow all punctuation characters for some language.

What are you thoughts on solving this? Let us use the above hack? A separate endOfStatement string option? A custom callback function? Checking whether we're typing at the end of a *token*? I don't mind trying to submit a PR if needed.

**Comment by marijnh** [comment]
I wasn't able to find out why it behaved like that, but I agree that isn't very good behavior. Attached patch removes it.

**Comment by the-j0k3r** [comment]
Thanks to both of you ;)

**Comment by tophf** [comment]
> I wasn't able to find out why it behaved like that

It made sense in case one wanted to add an opening bracket inside existing text, then a closing one at another place. Without this check a pair of brackets is always added now, which is why I suggested to allow users to configure the behavior. OTOH CodeMirror can surround a selection with brackets when the user types an opening bracket - this is probably a well-known method, although maybe not that obvious if one doesn't know about it.

**Comment by tophf** [comment]
@marijnh, the new behavior is counter-productive and even annoying in JavaScript mode, which I'm positive of after having tried coding for more than a few minutes (in Chrome devtools). When editing an existing script I've notice I delete the closing bracket ~99% of time I type an opening one. I think it should be either configurable - as I suggested initially - or enabled on a per-mode basis.

**Comment by marijnh** [comment]
#5812 brings back a behavior similar to this in a more robust and configurable way

**Comment by the-j0k3r** [comment]
CC @Mottie
