### ISSUE TITLE
Kotlin syntax highlighting doesn't work for function names using back ticks

### ISSUE THREAD

**Issue by woshilapin** [codemirror/CodeMirror#5513]
Functions in Kotlin could be written either as `fun someFunctionName()` or ``fun `some function name`()``. In the second case, the syntax highlighting is failing, see below in the name of the `start and return` function.

![kotlin-back-ticks](https://user-images.githubusercontent.com/2520723/43267641-7fc20a18-90bc-11e8-913c-0569f2d764ce.png)

**Comment by marijnh** [comment]
I'm not actively maintaining the Kotlin mode, but if you want to submit a pull request to implement this, that would be welcome.
