### ISSUE TITLE
Add a way to disable text normalization

### ISSUE THREAD

**Issue by weary-adventurer** [codemirror/CodeMirror#5520]
Currently, CodeMirror appears to manually normalize text input in a similar fashion to <textarea> elements: all carriage return (CR) characters get replaced with line feed (LF: \n).

This feature makes it impossible to paste binary data and preserve its value.
For example, `setValue(String.fromCharCode(13))` will insert a line feed (that indents text as a new line).
Using `getValue().charCodeAt(0)` returns `10` instead.

**Comment by weary-adventurer** [comment]
Clarification: `[contenteditable]` elements allow any characters inside, while `<textarea>` will replace and discard any carriage return symbols.

**Comment by marijnh** [comment]
Not sure if you found it, but the [`lineSeparator` option](https://codemirror.net/doc/manual.html#option_lineSeparator) can be used to customize how the editor treats line breaks.
