### ISSUE TITLE
Find string in Codemirror without Dialog

### ISSUE THREAD

**Issue by Xatenev** [codemirror/CodeMirror#5521]
Hi.

How do I trigger the search in CodeMirror to select(and unselect) a specific string without using the dialog?

I am looking for something like: `CodeMirror.execCommand('find', 'test')` and it will mark all occurences of test just like it would when I use the dialog box.

I found a duplicate of this: https://github.com/codemirror/CodeMirror/issues/3392 but it has been closed with a hint to https://codemirror.net/doc/manual.html#addon_searchcursor and I really can't see _at all_ how I would implement this via `getSearchCursor()`. Can someone provide an example for this or has some additional explanations?

Thanks!

**Comment by Xatenev** [comment]
Quote from https://codemirror.net/1/manual.html

> getSearchCursor(pattern, startPos, caseFold) → cursor
> Returns an object that provides an interface for searching. Call its findNext() and findPrevious() methods to search for an occurrence. This returns true if something is found, or false if the end or start of the document was reached. When an occurrence has been found, you can call select() to select it, or replace(string) to replace it with a given string (you can use \1 placeholders in this string if you matched a regular expression). 

I don't seem to have a function called `select`, only `replace`.

**Comment by marijnh** [comment]
`selectMatches` selects matches _within_ the current selection. To select a given match, you can call `codemirrorInstance.setSelection(cursor.from(), cursor.to())`.

**Comment by Xatenev** [comment]
@marijnh Thanks for the response. I then get:

> vue.esm.js?efeb:1741 TypeError: Cannot read property 'line' of undefined
>     at clipPos (codemirror.js?f14e:508)
>     at Doc.eval (codemirror.js?f14e:6131)
>     at Doc.eval [as setSelection] (codemirror.js?f14e:3903)
>     at CodeMirror$1.eval [as setSelection] (codemirror.js?f14e:9654)
>     at VueComponent.search (Detail.vue?5e21:64)

My code is

```
search(val) {    
    //val being something like "test"
    let cursor = this.cm.getSearchCursor(val);
    this.cm.setSelection(cursor.from(), cursor.to());
}
```

**Comment by marijnh** [comment]
You didn't move the cursor to a match yet, so `from` and `to` aren't returning anything.

**Comment by Xatenev** [comment]
Thanks your right. It works now. I think a doc entry for this might be helpful.
