### ISSUE TITLE
Strange `string.split is not a function error`

### ISSUE THREAD

**Issue by syropian** [codemirror/CodeMirror#5526]
I'm using a Markdown editor that uses CodeMirror behind the hood to manage the document. For some reason, initializing the editor causes CodeMirror's `splitLinesAuto()` helper to fail with a `TypeError: string.split` is not a function.

Fair enough, I thought maybe an invalid value was getting passed so I set a breakpoint on that line in CM, and oddly, it's just a regular old string getting passed in, so I am unsure how it can be failing? 

![](https://d.pr/i/SEhRKF+)

Any ideas?

**Comment by syropian** [comment]
My apologies, I had to step through a little further and found a rogue object getting passed to this function!

**Comment by yanglr** [comment]
I met the same issue when I tried to update the content of CodeMirror by using `editor.getDoc().setValue("the string what I need");`, finally I removed all previous elements with the class `cm-s-default` then initialize the code mirror editor again. The issue is resovled.
