### ISSUE TITLE
markdown mode link highlight

### ISSUE THREAD

**Issue by kyuwoo-choi** [codemirror/CodeMirror#5527]
markdown mode highlights text below
```md
[text having square bracket
```
![image](https://user-images.githubusercontent.com/1215767/44008383-15f365ac-9ede-11e8-9140-d69dc69e126c.png)

But It is actually not a link yet.

![image](https://user-images.githubusercontent.com/1215767/44008403-33c4c152-9ede-11e8-9529-b3ea1aaabe56.png)

The text should not be highlighted.

**Comment by marijnh** [comment]
The mode can't look ahead and determine whether the bracket corresponds to a well-formed link, so it has to work this way—assuming something that may start a link actually does so. Full Markdown parsers work very differently from typical programming language parsers, but in a highligher, we do have to work in a single pass.

**Comment by cybaek** [comment]
If a user invokes '[' on the middle of document, "the rest of document" will have a blue line. It's awkward for users. 

![image](https://user-images.githubusercontent.com/317581/44065841-fd5a9bbc-9fa7-11e8-999f-913968522ae9.png)
