### ISSUE TITLE
"Added non-passive event listener" ... warning in Chrome

### ISSUE THREAD

**Issue by samu** [codemirror/CodeMirror#5534]
In chrome, the following warnings are raised in the console:

```
 Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
 Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
 Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
```

**Comment by marijnh** [comment]
Those handlers are intentionally non-passive, so this is the intended behavior. Chrome making a fuss about it in the console isn't something we can control.

**Comment by luisArandas** [comment]
This is erasing my text. When I get these exact warnings the value of the codemirror object is erased. It just goes away. Any workaround?

**Comment by marijnh** [comment]
That really has nothing to do with erased text. It's a warning from the browser about the kind of event handler that's being registered.

**Comment by luisArandas** [comment]
Found the problem!
Thanks

**Comment by curtislin7** [comment]
@luisArandas Just running into this now...care to expand on how you removed the warnings?

**Comment by luisArandas** [comment]
@curtislin7 It had to do with the code evaluation I was doing, nothing related to the original cm library. Everything seems to be ok now.

**Comment by MrCoder** [comment]
@curtislin7 have you found a solution? I run into this issue for a while.

**Comment by curtislin7** [comment]
@MrCoder really sorry man, looked at this for a bit and I have absolutely no idea what I did to resolve this.
