### ISSUE TITLE
can't disable enter event

### ISSUE THREAD

**Issue by Pengxy0917** [codemirror/CodeMirror#5537]
it's of no use to disable enter event

**Comment by marijnh** [comment]
This is not a useful bug report, though. What effect are you looking for? How did you do it? What went wrong?

**Comment by Pengxy0917** [comment]
I  wanted to use codemirror in a vue application, while I wanted to to listen to keyboard event to disable carriage return when the content of this line doesn't exist. But it didn't work to disable carriage return. I can't see any reason. 
Thank you.

**Comment by marijnh** [comment]
Try going through the keymap mechanism (for example with the [`extraKeys` option](https://codemirror.net/doc/manual.html#option_extraKeys)) instead. See [the docs](https://codemirror.net/doc/manual.html#keymaps).
