### ISSUE TITLE
Add Support for GDScript Syntax Highlighting

### ISSUE THREAD

**Issue by infosisio** [codemirror/CodeMirror#5545]
GDScript is the official scripting language of the promising Godot game engine.

It is rising in popularity and becoming a force on its own for game development.

Supporting it for syntax highlighting makes total sense imo.

**Comment by marijnh** [comment]
We're not adding more language modes to the main distribution. The way to work with a new language is to write the mode as a separate module, and possibly publish that to NPM so that others can benefit from it.

**Comment by AsixJin** [comment]
How would I go about making a language mode into a module so someone like the people at Boostsnotes could implement it into their projects?

**Comment by adrianheine** [comment]
We usually reference the [elexir mode](https://github.com/ianwalter/codemirror-mode-elixir) as an example.
