### ISSUE TITLE
Supporting ReasonML mode

### ISSUE THREAD

**Issue by thangngoc89** [codemirror/CodeMirror#5546]
Hello CodeMirror devs, thank you for making this lovely editor, I've been working on ReasonML mode lately and this is what I've got so far (based on dart, c, ocaml example)

https://github.com/Sketch-sh/sketch-sh/blob/2ad9e87e703d72229bcfd9460eb1b75677303eb8/client/src_editor/reason-mode.js

I'm having troubles with variable name highlighting:

- Variable can contain `'` 
- `'` could be used to indicate type variable
- `'a'` , `'b'` is a char (8 bit)

![image](https://user-images.githubusercontent.com/3049054/44629335-eac85500-a977-11e8-88b8-77349e16df25.png)

I can't figure out how to make it work with 3 conditions above.

**Comment by marijnh** [comment]
Doing this properly would require doing an accurate enough parse to know what kind of syntactic element is expected at a given position, as the [TypeScript mode](https://codemirror.net/mode/javascript/typescript.html). But that requires a lot of additional complexity. Instead, you could use a heuristic, like seeing if the text ahead is a valid character expression, and if not, just treat the quote as part of an identifier name.

**Comment by thangngoc89** [comment]
> like seeing if the text ahead is a valid character expression, and if not, just treat the quote as part of an identifier name.

 This sounds good to me. Could you show me an example or something? Because I don't quite get this part

**Comment by marijnh** [comment]
Something like `stream.match(/^\'.\'/)` (might need to include a case for backslash escapes or whatever ReasonML does there))

**Comment by thangngoc89** [comment]
@marijnh so only match char , anything else is a identifier. thank you very much. 

Sidenote: Do you accept an PR to this repo once I have figure this out?

**Comment by thangngoc89** [comment]
Thank you for the information
