### ISSUE TITLE
Having problem with formatting ECMAScript 6

### ISSUE THREAD

**Issue by clms2** [codemirror/CodeMirror#5561]
Hi, I followed the [format demo](https://codemirror.net/2/demo/formatting.html), it didn`t work pretty good with es6 grammar, eg:
```js
function dealWithPromise() {
  return new Promise((resolve, reject) => {
    getListCount().then(res => {
      totalNum = res;
      console.log('Get count', res);
      if (pageSize * (curPage - 1) > totalNum) {
        curPage = 1;
      }

      return getListData()
    }).then(resolve).catch(reject);
  });
}
```
when I clicked autoformat button, it showed like this:
```js
function dealWithPromise() {
  return new Promise((resolve, reject) => {
                     getListCount().then(res => {
                                         totalNum = res;
                                         console.log('Get count', res);
  if (pageSize * (curPage - 1) > totalNum) {
    curPage = 1;
  }
  return getListData()
}
  ).then(resolve).catch(reject);
  }
  );
  }
```

**Comment by marijnh** [comment]
> Hi, I followed the format demo, it didn`t work pretty good with es6 grammar, eg:

That's because that feature hasn't been part of CodeMirror since 2012 (note the `/2/` in the URL). We're no longer providing it, because it was too much work to maintain. Use a separate code formatter if you need this.

**Comment by ran720** [comment]
Hi, @marijnh  , How to use a separate code formatter with codemirror?
