### ISSUE TITLE
Scheme mode quoted items get colorized improperly

### ISSUE THREAD

**Issue by dsblank** [codemirror/CodeMirror#5574]
Scheme mode incorrectly shows keywords in quoted list as highlighted. Notice that the `and` is purple in the demo below:

![screenshot from 2018-09-09 15-56-10](https://user-images.githubusercontent.com/168568/45268352-ed7f7b80-b448-11e8-85e2-50be4e0b1dc0.png)

**Comment by marijnh** [comment]
You could try submitting a pull request to fix this (which I suppose would involve tracking quote depth in the mode state). I don't consider this a big enough problem to work on it myself, so I'm going to close the issue.

**Comment by dsblank** [comment]
Ok, I fixed this (and a couple of other issues) in https://github.com/codemirror/CodeMirror/pull/5585

Before:

![screenshot from 2018-09-20 11-30-21](https://user-images.githubusercontent.com/168568/45829603-5082d500-bcc9-11e8-8905-25db6ee4963b.png)

After:

![screenshot from 2018-09-20 11-29-46](https://user-images.githubusercontent.com/168568/45829619-5d072d80-bcc9-11e8-9f7b-a8ab00addb71.png)
