### ISSUE TITLE
gutterContextMenu event not fired in Firefox

### ISSUE THREAD

**Issue by rakeshrohan** [codemirror/CodeMirror#5584]
Hi,

GutterContextMenu event is not fired in firefox. But it does in chrome and opera.
Only the click event is being fired on right click on gutter.

Here is the code i am using

```
 editor.on('gutterContextMenu', function(cm, line, gutter, event) {
          onGutterContextMenu(id, cm, line, gutter, event);
 });
```

Here are the versions i am using.
Firefox 61.0.2
MacOS High Sierra 10.13.4

Please let me know if you need more details.

**Comment by marijnh** [comment]
Attached patch should help!

**Comment by rakeshrohan** [comment]
@marijnh  Thanks mate. It worked. But the firefox context menu is opening up even though event.preventDefault() and event.stopPropagation() is called.
Tried to debug your code. But i couldn't find anything related to it.

**Comment by marijnh** [comment]
Oh, right, the thing that's passed there is actually the mousedown event, and it appears `preventDefault` doesn't actually prevent the context menu from showing up. Attached patch should fix that.

**Comment by rakeshrohan** [comment]
@marijnh . Great. Will you create a release for this patch?

**Comment by adrianheine** [comment]
Marijn usually does one release per month, so there should be a release pretty soon.
