### ISSUE TITLE
Programmatic call of copy/cut/paste

### ISSUE THREAD

**Issue by centurianii** [codemirror/CodeMirror#5594]
Suppose user selects some code and then press a button outside of CodeMirror to enable cut/copy/paste.
How can I do it?

**Comment by marijnh** [comment]
You can't, generally—browser's don't allow you to read the clipboard unless the user initiated the paste event.

**Comment by centurianii** [comment]
...but I can see on lines 9229-9230
`  on(te, "cut", prepareCopyCut)
  on(te, "copy", prepareCopyCut)`
these are inside `TextareaInput.prototype.init = function (display)`.

At 9630 there is a `CodeMirror.inputStyles = {"textarea": TextareaInput, "contenteditable": ContentEditableInput}`.

Just expose `prepareCopyCut`...?

**Comment by centurianii** [comment]
...or create a `Ctrl-X` or `Ctrl-C` event...?

**Comment by marijnh** [comment]
Doesn't work. Preparing for copy/cut when no actual copy or cut will be performed by the browser is useless, and simulating a keyboard event doesn't trigger this functionality.

**Comment by centurianii** [comment]
Ok, the idea is to replace keystrokes with a button so useful in a touch screen device...

**Comment by centurianii** [comment]
If I use `Document.execCommand('copy')` and make a range from the editor's selection?

**Comment by centurianii** [comment]
like this https://developers.google.com/web/updates/2015/04/cut-and-copy-commands

**Comment by centurianii** [comment]
Ok, it's possible - at least **inside the editor**! Just create a global buffer and when user **selects** sth & clicks 

1. **cut** write sth like:
`text = self.instance.editor.getSelection(); buffer.set(text); editor.replaceSelection('');`

2. **copy** write sth like:
`text = self.instance.editor.getSelection(); buffer.set(text);`

3. **paste** write sth like:
`text = buffer.get(); editor.replaceSelection(text);`

I decided to create a multi-level buffer so user can do things like: 
1. copy to buffer 1, 

2. cut to buffer 2,

3. paste from buffer 1.

What about transferring our buffer to clipboard? I'll see that too...

**Comment by centurianii** [comment]
A buffer [implementation](https://gist.github.com/centurianii/570573fa79cc493d7a8e59701fba3b25)

**Comment by centurianii** [comment]
It's possible to connect our private buffer with the system's clipboard when user clicks
1. **cut** add sth (continuing from my previous reply): on construction add a textarea `$('<div class="buffer"><textarea></textarea></div>').appendTo('#' + editorId + ' > .panel-footer')` and on event handler `$('#' + editorId + ' > .panel-footer > .buffer > textarea').val(text).get(0).select(); document.execCommand("copy");`
I use jquery here. `editorId` comes from your program/class/object. I also used a bootstrap 3 panel with panel footer and there I hide my buffer.

Styles for class `.buffer`:
`/* Panel footer */
#editorId > .panel-footer > .buffer {
   overflow: hidden;
   outline: none;
   height: 0;
   border: 0;
   margin: 0;
   padding: 0;
}`

2. **copy:** like cut on event handler `$('#' + editorId + ' > .panel-footer > .buffer > textarea').val(text).get(0).select(); document.execCommand("copy");`

3. **paste**: comes at no cost!

Now you can add events that simulate the missing and infamous key bindings from the source: `Ctrl-X`, `Ctrl-C` and `Ctrl-V`.
 How difficult was that?

**Comment by gloony** [comment]
For paste, your need something this for make it work with multiple selection:

```
if(text.indexOf("\n")!=-1){
	var a = text.split("\n");
	editor.replaceSelections(a);
}else editor.replaceSelection(text);
```

**Comment by centurianii** [comment]
My solution populates visual copy/cut from the interface to clipboard.

In order to populate copy/cut from the keyboard to the buffer which is used by the visual copy/cut we need a [patch](https://gist.github.com/centurianii/de0618291311253473214e25b1f282da) at the CodeMirror code.

An example that supports the above:

1. user selects sth,

2. presses Ctrl+C,

3. go to another place in the editor,

4. clicks button Paste,

5. Error as the buffer hasn't been populated from the keyboard copy! (see the hidden textarea).

On the other hand, if we replace step 2 with a click at button Copy and use as step 4 Ctrl+V everything is OK!

With the patches now we can update the textarea and we have 2-way communication, a synchronized copy/cut wherever it comes from!
