### ISSUE TITLE
[sublime] possible to have an option to allow selections to touch like in sublime text?

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5602]
CodeMirror implements multi-selections in a way that does not allow adjacent selections (they are merged into a larger selection), while Sublime Text supports adjacent selections fine. This results in issues like the following:

1. https://codemirror.net/demo/sublime.html
2. Paste in
```
foo
foofoo
foo
```
3. Select the first "foo" and press ctrl+d several times

Expected:
all the instances of "foo" (including two in the second line) are selected

Actual: 
only the first three instances are selected, because at the end, "foofoo" was the selection and ctrl+d couldn't find another match for it.

I realize that this would be a significant change in terms of user interaction, so I'm wondering if it would be possible to have it as an option?

**Comment by marijnh** [comment]
We're doing it that way in CodeMirror 6. I guess adding an option to turn that on in the current code would also be harmless. Done in fc60137b
