### ISSUE TITLE
[core] alt+click (e.g. when trying to do an alt-drag for rectangular selection) opens context menu in chrome os

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5603]
This is because chrome translates an alt-click into a right-click (and this can't really be changed with user preferences). :/

Would it be possible to change the default mouse behavior in CM on CrOS to treat a right-click-drag as also producing an rectangular selection, in a way that does not prevent right-clicking in place from opening the context menu?

**Comment by marijnh** [comment]
Is this a problem outside of your in-house product? If you control the configuration, you should be able to use [`configureMouse`](https://codemirror.net/doc/manual.html#option_configureMouse) to do this. Since rectangle-selection is a somewhat obscure feature, I'm not sure how much of an issue this is in the wild.

**Comment by marijnh** [comment]
Those are good point, but I'm worried that overriding right click behavior will mess with context menu functionality—I don't have a ChromeOS device around, but I'd assume that a right click brings up a context menu, and I'm not sure how that'd interact with right-click-drag actions.

**Comment by mtaran-google** [comment]
Will try it out tomorrow and let you know how it goes.

**Comment by mtaran-google** [comment]
Heh, I was looking through the code trying to figure out how to deal with this and noticed that there's already a hack in there to create rectangular selections on CrOS with meta+shift+drag (I think this was at my request a long time ago).

Could you note this in the manual somehwere? I'll similarly have to add it to our internal docs, since it's extremely obscure right now...

**Comment by marijnh** [comment]
Good point, I've added this to the manual in attached patch
