### ISSUE TITLE
How can i fix the gutter padding?

### ISSUE THREAD

**Issue by demirdoven** [codemirror/CodeMirror#5605]
I use Codemirror editor on a WordPress project and i see this after test the editor. As you can see, the lines are under the gutter. Any idea?

For example I try to add this:

```
#vertical_tab_nav{
	display: block;
	width: 100%;
	background-color: #f9f9f9;
}
```
But here is the result:

![fgdgdfg](https://user-images.githubusercontent.com/24434119/46444571-3c37e100-c77b-11e8-9495-fc0020d79e4b.png)

**Comment by marijnh** [comment]
Is it possible that the editor was initialized in a hidden state, and then shown? It needs to have a proper layout to initialize itself, so if the editor starts out hidden, you should call the `refresh` method when you unhide it.

**Comment by demirdoven** [comment]
> Is it possible that the editor was initialized in a hidden state, and then shown? It needs to have a proper layout to initialize itself, so if the editor starts out hidden, you should call the `refresh` method when you unhide it.

Hi, i use Codemirror in WordPress. My codes ara like this:

`'use strict';
 (function($){
    $(function(){
        if( $('#code_editor_page_head').length ) {
            var editorSettings = wp.codeEditor.defaultSettings ? _.clone( wp.codeEditor.defaultSettings ) : {};
            editorSettings.codemirror = _.extend(
                {},
                editorSettings.codemirror,
                {
                    indentUnit: 2,
                    tabSize: 2
                }
            );
            var editor = wp.codeEditor.initialize( $('#code_editor_page_head'), editorSettings );
        }

        if( $('#code_editor_page_js').length ) {
            var editorSettings = wp.codeEditor.defaultSettings ? _.clone( wp.codeEditor.defaultSettings ) : {};
            editorSettings.codemirror = _.extend(
                {},
                editorSettings.codemirror,
                {
                    indentUnit: 2,
                    tabSize: 2,
                    mode: 'javascript',
                }
            );
            var editor = wp.codeEditor.initialize( $('#code_editor_page_js'), editorSettings );
        }

        if( $('#code_editor_page_css').length ) {
            var editorSettings = wp.codeEditor.defaultSettings ? _.clone( wp.codeEditor.defaultSettings ) : {};
            editorSettings.codemirror = _.extend(
                {},
                editorSettings.codemirror,
                {
                    indentUnit: 2,
                    tabSize: 2,
                    mode: 'css',
                }
            );
            var editor = wp.codeEditor.initialize( $('#code_editor_page_css'), editorSettings );
        }
    });
 })(jQuery);`

**Comment by marijnh** [comment]
I'd assume that the `editor` variable will hold a CodeMirror instance, which is what you'd call the method on (though maybe wordpress wraps it, I wouldn't know). Alternatively, you could enable the autorefresh addon or delay initialization until the container is visible, so that it initializes visibly.

**Comment by demirdoven** [comment]
Thanks. 

I've added this option and it's done :)

`autoRefresh: true`
