### ISSUE TITLE
show the user defined variable/func hint in python mode 

### ISSUE THREAD

**Issue by kimyLee** [codemirror/CodeMirror#5612]
I just found the js mode can show the hint from context that defined by user, like this
![4c36e858-3d38-cffe-4da0-b4db02606df8](https://user-images.githubusercontent.com/11704790/46653116-b7fcb800-cbd7-11e8-9a95-ea1ddf1b96ef.png)
my problem is how can I make this in python mode ?
just want like: 
![cf6268dd-1d53-f98c-bd7c-163b48029cfd](https://user-images.githubusercontent.com/11704790/46653177-de225800-cbd7-11e8-9a81-b4fefe65dd3d.png)
I have read the code and I think javascript.js make this, is that any way I can achieve this feature?

**Comment by marijnh** [comment]
> any way I can achieve this feature?

Yes, but it's not easy — you'll have to analyze the code somehow to figure out what names are in scope.

Since this is more of a question than an issue, I'm closing it. Please use the [forum](https://discuss.codemirror.net/) for questions in the future.

**Comment by kimyLee** [comment]
all right, thanks, I will do some more search and coding to try to solve this, thanks for your quick reply and help

**Comment by TonyZhang1993** [comment]
Hi @kimyLee , any solution or suggestion for the question? I need to achieve the feature in python mode too. 
Thanks in advance :)
