### ISSUE TITLE
Syntax highlighting for Stan

### ISSUE THREAD

**Issue by rongmu** [codemirror/CodeMirror#5623]
Please add syntax highlighting for [Stan](http://mc-stan.org/), a state-of-the-art Bayesian modelling language.
The RStudio IDE supports Stan syntax out-of-the-box, there is also a Vim plugin [stan.vim](https://github.com/maverickg).
It would be great if CodeMirror could support Stan code.
Thank you!

**Comment by marijnh** [comment]
We aren't going to add any more language modes to the main distribution. Fortunately, it is possible to write language modes as separate modules, so you're not dependent on us.

**Comment by kylebarron** [comment]
> it is possible to write language modes as separate modules

What's the proper way to distribute language modes as separate modules? As an npm package?

**Comment by marijnh** [comment]
> What's the proper way to distribute language modes as separate modules? As an npm package?

Yes. You can take the [elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir) as an example.

> Does this mean that you won't accept a PR to add another mode, or that you won't expend any work to create one yourself?

Both.
