### ISSUE TITLE
Ubuntu Theme?

### ISSUE THREAD

**Issue by curran** [codemirror/CodeMirror#5635]
I developed a new theme for CodeMirror based on how Vim appears in Ubuntu.

It is currently located in another Open Source project here https://github.com/datavis-tech/vizhub-ui/blob/master/src/css/codemirror-ubuntu-theme.scss

It looks something like this ([see it in action](https://vizhub.com/curran/012b5b20ce894b0fa7dc98ef3a0b43a5)):

[![image](https://user-images.githubusercontent.com/68416/47272199-ac2dd000-d59f-11e8-9d2c-1b4d620295a9.png)](https://vizhub.com/curran/012b5b20ce894b0fa7dc98ef3a0b43a5)

It has been iterated to work well for HTML, CSS and JavaScript, and is currently used in [VizHub](https://vizhub.com/curran/012b5b20ce894b0fa7dc98ef3a0b43a5).

Would this Ubuntu theme be a welcome addition to CodeMirror's themes?

I'd be happy to send a PR adding this theme to CodeMirror's collection if there is interest/support for this idea.

**Comment by marijnh** [comment]
Hi. We've decided to stop expanding the scope of the main distribution, so we're not accepting new additions there. But it would be wonderful if you could put this on npm under a name like codemirror-theme-ubuntu, so that others can easily use it.

**Comment by curran** [comment]
Great idea. Done!

https://github.com/datavis-tech/codemirror-theme-ubuntu

https://www.npmjs.com/package/codemirror-theme-ubuntu
