### ISSUE TITLE
passing selectionsMayTouch: true results in extra selection ranges when using sublime ctrl-shift-down

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#5636]
I see the selectionsMayTouch option was added to address https://github.com/codemirror/CodeMirror/issues/5602
Unfortunately, there's a bug that occurs w/ sublime keymappings when this is used. Repro's with the following minimal editor configuration:

var editor = CodeMirror.fromTextArea(document.getElementById('testEditor'), {
  mode: 'javascript',
  keyMap: "sublime",
  selectionsMayTouch: true,
});

1. Use Ctrl-shift-down 3 or more times to create a column of 3+ cursors in an editor with some existing content. (This does not occur if using Cmd-click to create extra cursors).
2. Type 'a'

Observe that extra a's appear in the rows in the middle.
With 2 cursors, no extra a's appear.
With 3 cursors, 1 extra a appears.
With 4 cursors, 2 extra a's appear.
With 5 cursors, 3 extra a's appear in the 2nd and 4th row, and 5 extra a's appear in the 3rd row.

A debug session revealed there were some duplicate selection ranges that appear to normally be dropped by normalizeSelection(), but not when this option is enabled.

**Comment by marijnh** [comment]
Oh, right, I guess when I implemented `selectionsMayTouch` I missed some considerations. I guess a cursor selection should _not_ be allowed to touch another selection (sublime text itself seems to behave the same).  Attached patch takes care of that.

**Comment by takamori** [comment]
thanks!
