### ISSUE TITLE
Text cursor is offset from the line selected

### ISSUE THREAD

**Issue by ischolten** [codemirror/CodeMirror#5641]
We are using a CodeMirror version 5.40.2 and are using Chrome.

Any time after a hard refresh, the cursor seems to be offset or has a different line height than what the text editor shows. 

Below shows what is expected and what happens most of the time.
![cursor_afterrefresh](https://user-images.githubusercontent.com/5751863/47452450-2d8f8900-d77f-11e8-92e7-f59b50663314.gif)

This shows what happens after a hard refresh.
![cursor_afterhardrefresh](https://user-images.githubusercontent.com/5751863/47452527-5748b000-d77f-11e8-9015-13e7f09451c7.gif)

<img width="217" alt="47039223-4d4bff00-d138-11e8-9fbb-2d6d2a5587f6" src="https://user-images.githubusercontent.com/5751863/47451272-2e72eb80-d77c-11e8-8829-df7dbf374c03.png">

After typing, the issue seems to resolve itself.

**Comment by marijnh** [comment]
Looks like some CSS or font loaded after the editor initialized, causing its size to change. If you can arrange for the editor to be initialized after the entire page finishes loading, or do a call to its `.refresh()` method when that happens, that should take care of this.

**Comment by ischolten** [comment]
@marijnh I'll try that out. Thanks!

**Comment by adrianheine** [comment]
Closing this for now, please feel free to reopen if Marijn's suggestion doesn't work for you!
