### ISSUE TITLE
Appearance broken out of the box

### ISSUE THREAD

**Issue by PerryRylance** [codemirror/CodeMirror#5644]
Steps:
- Download codemirror
- Set up test page with no other components
- Add JS & CSS modes
- Initialize with fromTextArea

Expected behaviour:
- CodeMirror set up with my example code ready to go

Observed behaviour:
- Code is initially invisible, mouse interaction causes it to become visible
- Code overlaps line numbers

![2018-10-25 11_27_30-map block - settings map block archived wordpress](https://user-images.githubusercontent.com/14136738/47515658-17e69600-d849-11e8-85ce-b7908e3b931d.png)

**Comment by marijnh** [comment]
I assume you initialized the editor in a hidden or unstyled state. In that case, you have to call `.refresh()` on it when it becomes visible and/or styled.

**Comment by PerryRylance** [comment]
Thanks
