### ISSUE TITLE
setSize  when height less than 300 is not work

### ISSUE THREAD

**Issue by ywww** [codemirror/CodeMirror#5650]
onEditor = () => {
        this.CodeMirrorEditor = CodeMirror.fromTextArea(this.editor, {
            mode: {name: "text/x-sql"},
            extraKeys: {"Ctrl": "autocomplete"},
            lineNumbers: true,
            matchBrackets: true,
            tabSize: 4,
            indentUnit: 4,
            smartIndent: true,
            viewportMargin: 50,
        });
        // this.CodeMirrorEditor.setSize("auto",300);   // height is not work
        this.CodeMirrorEditor.setSize("auto",1000);  // height is work
        this.CodeMirrorEditor.on('change', this.onChange);
        this.CodeMirrorEditor.addKeyMap({
            Tab: this.onTab2Space
        });
    };

    render() {
        const {value} = this.state;
        // console.log(value);
        // this.CodeMirrorEditor.setValue("hello")
        return (
            <textarea ref={node => this.editor = node}
                      style={{border: '1px solid #d9d9d9'}}
                      rows={4}
                      cols={10}
                      defaultValue={value}
            />
        );
    }

**Comment by marijnh** [comment]
This works in the demos. Do you maybe a style sheet active that is setting a `min-height: 300px` on the editor?

**Comment by ywww** [comment]
yes , thankyou
