### ISSUE TITLE
Get yaml lint errors externally

### ISSUE THREAD

**Issue by ChinmayeePDas** [codemirror/CodeMirror#5652]
I am using codemirror in yaml mode.
I have enabled linting and below is my config

 lineNumbers: true,
mode: 'text/x-yaml',
 gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter", "CodeMirror-lint-markers"],
 foldGutter: {
        rangeFinder: new CodeMirror.fold.combine(CodeMirror.fold.indent, CodeMirror.fold.comment)
 },
 "lint": {
     "getAnnotations": self.yaml_validator()
  }

I want validation to happen on every change in the editor. 
When i click on a button, i want to ensure that the functionality gets executed only when there are no errors in the yaml.

I found that 'getAnnotations' is helpful for this.
Added it in my config above. 
I see that on page load, yaml_validator() method is getting called, but when i add some new content to the editor, it does not get invoked.

Please let me know how what am i doing wrong here?

**Comment by marijnh** [comment]
You have parentheses after `self.yaml_validator`, which will cause it to be called one, one load. You want to pass the function value, so remove those parentheses.
