### ISSUE TITLE
Update the gutter with validation errors

### ISSUE THREAD

**Issue by ChinmayeePDas** [codemirror/CodeMirror#5657]
I want to get hold of YAML lint errors and perform some action based on it.

Hence i have below code.

var codeMirrorOptions = {
        lineNumbers: true,
        mode: 'text/x-yaml', // we are using the yaml editor
        gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter", "CodeMirror-lint-markers"],
        foldGutter: {
          rangeFinder: new CodeMirror.fold.combine(CodeMirror.fold.indent, CodeMirror.fold.comment)
        },
        "lint": {
          "getAnnotations": checkYAMLForErrors
        }
      };

function checkYAMLForErrors(cm, updateLinting, options) {
   var errors = CodeMirror.lint.yaml(cm);
};

The linting happens now, but the error is not shown in the gutter.
How to achieve this?

**Comment by marijnh** [comment]
You need to add the `CodeMirror-lint-markers` gutter, as seen in [the demo](https://github.com/codemirror/CodeMirror/blob/master/demo/lint.html#L152).

**Comment by ChinmayeePDas** [comment]
I have added it as seen above.

if i just have  'lint: true', i see the gutter getting updated, but with the above code it is not being shown
