### ISSUE TITLE
Unable to update the gutter with lint errors

### ISSUE THREAD

**Issue by ChinmayeePDas** [codemirror/CodeMirror#5658]
I am getting updateLinting - function not found.

 var codeMirrorOptions = {
        lineNumbers: true,
        mode: 'text/x-yaml', // we are using the yaml editor
        gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter", "CodeMirror-lint-markers"],
        foldGutter: {
          rangeFinder: new CodeMirror.fold.combine(CodeMirror.fold.indent, CodeMirror.fold.comment)
        },
        "lint": {
          "getAnnotations": checkYAMLForErrors
        }
  };

function checkYAMLForErrors(cm, updateLinting, options) {
        var errors = CodeMirror.lint.yaml(cm);
        updateLinting(cm, errors);
};

**Comment by marijnh** [comment]
The bug tracker isn't intended for support questions like this. You can add replies to your forum thread if you want (preferably without starting a new thread for every question), maybe someone is willing to help you there, but please stop opening issues.
