### ISSUE TITLE
Powershell mode - wrong syntax highlighting/syntax error when $ is used ""

### ISSUE THREAD

**Issue by waldemarsvk** [codemirror/CodeMirror#5666]
In powershell mode if i use $ in "" (e.g.: "text$" - this highlight $ red as it is syntax error 
or "text1$text2" - here is $text2 highlighted as a variable).

![image](https://user-images.githubusercontent.com/11034591/48493394-01ba6d00-e82c-11e8-82d7-863cf326e17a.png)

Tested version 5.41.0 in Chrome, Firefox and IE.

**Comment by marijnh** [comment]
This appears to be just a matter of its error-checking being relatively simple and limited. Feel free to send a pull request if you want to fix this, but I'm going to close this issue, since it's more a matter of scope (modes are primary highlighters, not error checkers) than a bug.
