### ISSUE TITLE
[WIKI] Plugin simplemde-markdown-editor not maintened / empty

### ISSUE THREAD

**Issue by hjortzen** [codemirror/CodeMirror#5667]
By following the link provided in the wiki from https://github.com/codemirror/codemirror/wiki/codemirror-addons to Simple MDE (https://github.com/nextstepwebs/simplemde-markdown-editor/blob/master/index.html) you quickly see that either:
1) Project was never commited
or 
2) Was hacked.

Please remove the repository from list.

**Comment by marijnh** [comment]
I've removed the link.
