### ISSUE TITLE
Wrong highlighting and indentation for Python f-strings with nested strings

### ISSUE THREAD

**Issue by aldanor** [codemirror/CodeMirror#5668]
Example:

```python
a = g(f'{b["c"]}') # oops
```

The comment will be highlighted wrong (as if it was still a part of the string), and if you hit enter the subsequent indentation will be wrong:

![image](https://user-images.githubusercontent.com/2418513/48588429-00259d80-e92f-11e8-9eed-ea3e2ae74084.png)

**Comment by marijnh** [comment]
Attached patch should help with this

**Comment by aldanor** [comment]
Thanks! That was very fast :)
