### ISSUE TITLE
Doubt about auto close and "active mode"

### ISSUE THREAD

**Issue by jotakar** [codemirror/CodeMirror#5670]
In manual I read

> By default, if the active mode has a closeBrackets property, that overrides the configuration given in the option. But you can add an override property ...

I wonder what is the active mode? where to put closeBracket property?
If I set
autoCloseBrackets: "()[]{}<>"
the editor uses the default closebracket string: ()[]{}''""
The same if I set
autoCloseBrackets: true
closeBrackets: "()[]{}<>"
or
autoCloseBrackets: {pairs:"()[]{}<>"}

The only way to get what I want (a <> close pair) is setting:
autoCloseBrackets: {pairs:"()[]{}<>", override:true}

Thanks

**Comment by marijnh** [comment]
> I wonder what is the active mode?

The language mode that's active at the cursor position. This'll usually be the mode selected through the `mode` option, but if that's a nesting node (for example the HTML mode will use the JavaScript mode to process the content of `<script>` tags), it may be one of its inner modes.

See for example the property being set on [the JavaScript mode](https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js#L872).

**Comment by jotakar** [comment]
Thanks for your answer, so I read again about mode option, and I understand that if I do
```
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
	  	mode: {name:'javascript', closeBrackets: "()[]{}<>''\"\"``"},
	    autoCloseBrackets: true
		  });
```
closeBrackets should be set to ()[]{}<>''\"\"``, but It doesn't happen so. It keeps their default value. Why?

**Comment by jotakar** [comment]
Why closed?

**Comment by marijnh** [comment]
You misunderstood. You're adding fields to the mode options, whereas the fields should be on the mode object, which is created by the mode's implementation, not the editor configuration. If you can't change the mode, you'll have to use the `closeBrackets` option to configure this.

> Why closed?

Because this is a bug tracker, not a [support forum](http://discuss.codemirror.net/).

**Comment by jotakar** [comment]
Now I understand my error.
Sorry, and thanks for your answers.
Bye
