### ISSUE TITLE
Check if codeMirror is readOnly

### ISSUE THREAD

**Issue by ChinmayeePDas** [codemirror/CodeMirror#5671]
I have rendered a readOnly codeMirror. 
Now in my javascript code i want to check if the codeMirror is indeed readOnly.

When i inspect the DOM, i dont see readOnly flag anywhere.

Can you let me know how the DOM becomes readOnly if there is no such flag/attribute.

How can check in my code?

**Comment by gloony** [comment]
editor.getOption('readOnly')

**Comment by ChinmayeePDas** [comment]
yes that is correct, but i want to use some property on the DOM to check this.

**Comment by marijnh** [comment]
> Can you let me know how the DOM becomes readOnly if there is no such flag/attribute.

The DOM was read-only from the start—all editing behavior in CodeMirror 5 is 'fake', implemented in JavaScript.
