### ISSUE TITLE
Support attributes in MarkText function

### ISSUE THREAD

**Issue by AlexanderPrendota** [codemirror/CodeMirror#5672]
Hi!
It will be awesome to have ability to set own attribute in option parameter in function `markText`

Currently we have only `title` attribute, but title attribute will be displayed as a tooltip when you mouse over.

```js
this.codemirror.markText(start, end, { "title": message }));
```
For example, may be add [`area-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) attribute or something else.

Thanks.

**Comment by marijnh** [comment]
This is being designed in from the start in [CodeMirror 6](https://codemirror.net/6/), but I probably won't be adding it to the current version. A clean pull request that does so would be considered, though.

**Comment by AlexanderPrendota** [comment]
Okay. I'll try to add `area-label ` attribute
