### ISSUE TITLE
Canceling changeObj in beforeChange handler with selection causes indefinitely repeated change events

### ISSUE THREAD

**Issue by bjornhansen** [codemirror/CodeMirror#5677]
### Steps to reproduce
1.  Open [https://codepen.io/bjornhansen/pen/bQrbxx](https://codepen.io/bjornhansen/pen/bQrbxx) - there is a simplified CodeMirror test site here. Note that there is a handler for the "beforeChange" event in the JS tab that cancels any changes.
2. Open developer tools in the browser so you can see the console.
3. Select some text in the CodeMirror editor.
4. Press the "V" key. Also works when entering any letter, symbol, number, or a space.

  **Expected behavior**: the change is cancelled and `"Change object cancelled in beforeChange handler."` is printed to the console -- _one time_.
  **Resulting behavior**: same as above, but _repeats indefinitely_ every 100ms until another user input occurs.

### Other notes
I get the expected behavior if in step 4 the Enter, Delete, or Backspace keys are pressed.

### Details
**CodeMirror versions**: 5.41.0 and 5.38.0

**System**: Windows 10 with Firefox 61.0.2 (64-bit) and Chrome 70.0.3538.102 (64-bit).

**Thank you for building and maintaining CodeMirror!**

**Comment by marijnh** [comment]
This was due to the change sticking around in the hidden textarea when it was canceled in the actual editor. Attached patch should fix it.
