### ISSUE TITLE
Textmate grammars in CodeMirror

### ISSUE THREAD

**Issue by NeekSandhu** [codemirror/CodeMirror#5679]
(Pure) Textmate grammars are now working in CodeMirror. Please see [codemirror-textmate](https://github.com/NeekSandhu/codemirror-textmate) for more details.

@marijnh Would you be interested in endorsing* it? (tweet?, blog?)

*(more users === more diverse feedback => frequent updates => more reliability)

**Comment by marijnh** [comment]
Write a tweet, and I'll gladly retweet it from the codemirror account

**Comment by NeekSandhu** [comment]
Awesome! Thanks, Marijn

https://twitter.com/neek_sandhu/status/1067104901665177601

Also I just discovered about CodeMirror 6 in the works. Don't you agree it'd be nice to keep this package in mind while making it's API and architecture?

If you agree, I'm happy to list all the things I think would be necessary/nice-to-have in CM6 for optimal operation.

**Comment by marijnh** [comment]
Thanks, I've retweeted that.

I think for most sites running webassembly as part of the highlighter is still going to be overkill, but supporting this style of highlighter as alternative is definitely a good thing. In CodeMirror 6, the mode 'driver' will be outside of the core, so it'll be a lot easier to have different styles of modes. (We're already planning both a backwards-compat shim that can run slightly modified CodeMirror 5 modes, and a new system, which is still being designed, that is going to run a more grammar-like style of highlighter.)

**Comment by NeekSandhu** [comment]
Good. In the context of what I'm envisioning and what #5648 brings up. I think it'd be super awesome if CodeMirror (6+) __also__ moves towards Textmate theme format (being followed by Sublime, Atom, VSCode (monaco), Ace editor etc.) where tokenizers are welcome to return "scopes" besides `cm-property`, `cm-string` etc.

A lot more information is conveyed with `support.variable.property` and `variable.other.property` than just `cm-property`.

Should we proceed that direction, I'm happy to say that mechanism for that is already been made and is what drives `codemirror-textmate`. Taking in a TM scope and generating a CSS class that will be applied to the token. And on top of that, it is backwards compatible with "traditional" codemirror tokens. Pretty neat IMO.

**Comment by atomiks** [comment]
Oh damn thank you for this, sad I didn't see this earlier! It's exactly what I needed. Accurate & colorful syntax highlighting is something I was desperately wanting for a project. I've been extending Prism for regular code blcoks on my docs for a while to imitate my VS Code theme and can't live without all the granular scopes.
