### ISSUE TITLE
sourcing external files: rawgithub.com is shutting down

### ISSUE THREAD

**Issue by LaKing** [codemirror/CodeMirror#5681]
I had an attempt to pull a slightly enhanced linter demo, that has a html demo as well.
However, linters are sourced externally for the demo, and I noticed that rawgithub is shutting down.
The question is now where to source the two files from, they do not have CDN's. 

[jsonlint.js](https://github.com/zaach/jsonlint/blob/master/lib/jsonlint.js)
[htmlhint.js](https://github.com/htmlhint/HTMLHint/blob/develop/lib/htmlhint.js)

**Comment by marijnh** [comment]
Maybe unpkg.com , since both those are published as npm packages

**Comment by LaKing** [comment]
Fixing in #5683
