### ISSUE TITLE
show-hint addon should return a `close` function

### ISSUE THREAD

**Issue by wylieconlon** [codemirror/CodeMirror#5682]
I am trying to write integration tests for a component using the `show-hint` addon, and part of my test setup is to create and remove `CodeMirror` documents. I found that the `dialog` addon has this feature: `It returns a function closeFunction which, if called, will close the dialog immediately.`, and I am requesting that the `show-hint` addon should return the same kind of close function.

I haven't looked at other addons beyond `show-hint`, but is this possibly something that would affect the other addons?

**Comment by marijnh** [comment]
Since there's only ever a single hint dialog open, this can be a method. Does attached patch work for you?

**Comment by wylieconlon** [comment]
Yes, I think that solves the testing case nicely.
