### ISSUE TITLE
[Hint addon] Custom hints[2]

### ISSUE THREAD

**Issue by CreatorVilius** [codemirror/CodeMirror#5689]
> **CreatorVilius**
> Is there anyway to make custom hints? I want to create custom hints. What I mean by custom hints, is add our own hints.

> **marijnh**
> Yes, there is—start with [the docs](https://codemirror.net/doc/manual.html#addon_show-hint) for the show-hint plugin, or look at css-hint.js for a relatively simple example.

I know there is manual for show hint addon, but I need clean example. Taking look at JavaScript's hints, makes me confused. I know what does what, but there are bunch of random functions put together which makes me slightly confused.

**Comment by marijnh** [comment]
Please stop opening new issues for questions. Start a thread on the [forum](https://discuss.codemirror.net/) if you want, but this is a bug tracker.

Anyway, I pointed you at the css-hint file for an example, which is simpler. But yeah, reading code is going to require figuring out why the 'random functions' are there, that's an effort you'll have to make.
