### ISSUE TITLE
Python nested f-string shows incorrectly syntax error.

### ISSUE THREAD

**Issue by Nevsor** [codemirror/CodeMirror#5691]
### Bug
Syntax highlighting indicates a syntax error despite the code being valid, if I use quotes or nested curly braces inside the curly braces of f-strings.

### Example

A few test cases:

```python
print(f"π is approximately {3.1415926536:.3f}!") # OK
print(f"π is approximately {3.1415926536:.{2+1}f}!") # Is valid, but highlights as error
print(f"π is approximately {len('abc'):d}!") # Is valid, but continues to highlight in wrong mode
```
![Rendering of example code](https://user-images.githubusercontent.com/15523614/49408023-f25b7f00-f75a-11e8-8573-1e26552af2f7.png)

The third line works correctly in https://codemirror.net/mode/python/index.html but not in JupyterLab 0.35.3.
The second line is wrong in both.

Does that mean, that the problem with nested quotes is fixed in CodeMirror and I only have to wait for JupyterLab to upgrade?

I tested the examples with Firefox 63.

### Analysis

I tried to locate the bug and it seems to be caused by [tokenFString](https://github.com/codemirror/CodeMirror/blob/9376ad89daee45102e1a0a46a96d70d9ea8e9fd5/mode/python/python.js#L190):

```javascript
function tokenFString(stream, state) {
        // inside f-str Expression
        if (stream.match(delimiter)) {
          // expression ends pre-maturally, but very common in editing
          // Could show error to remind users to close brace here
          state.tokenize = tokenString
          return OUTCLASS;
        } else if (stream.match('{')) {
          // starting brace, if not eaten below
          return "punctuation";
        } else if (stream.match('}')) {
          // return to regular inside string state
          state.tokenize = tokenString
          return "punctuation";
        } else {
          // use tokenBaseInner to parse the expression
          return tokenBaseInner(stream, state);
        }
      }
```

The code seems to assume, that there are no nested curly braces and sets the state back to `tokenString`, as soon as the first `}` character is read. Also `tokenBaseInner` does not seem to support returning to an outer state like `tokenString` does with `formatStringFactory`.

I am not completely sure how to implement the correct behavior for nested quotes or curly braces, but I might try to fix this bug later this week, if noone else, who is more familiar with the codebase and JavaScript than me, starts to work on this issue.

**Comment by marijnh** [comment]
Attached patch fixes this. The original code was rather confused. CodeMirror releases happen monthly, around the 20th. I'm not sure how closely Jupyter follows them.

**Comment by Nevsor** [comment]
Wow that was fast! Thank you.
