### ISSUE TITLE
Can see 2 cursors in IE11 when opening context menu

### ISSUE THREAD

**Issue by petrovalex** [codemirror/CodeMirror#5693]
Steps: 
1. Open for example https://codemirror.net/demo/theme.html
2. Right click in editor to open context menu so that Paste option is available

Actual result: 
Multiple cursors are visible

Expected result:
Native cursor should not be visible

**Comment by marijnh** [comment]
This is a side effect of the hack we need to make the context menu work (the hidden textarea has to be visible and under the cursor when you click, on on IE11 setting opacity doesn't hide the cursor), and not likely to get fixed in version 5. Version 6 will not need this hack anymore.

**Comment by petrovalex** [comment]
Understand this, unfortunately there is some miscalculation happening sometimes and textarea is positioned not under cursor but aside and then not getting moved away, so can end up in situation when there are 2 cursors even if context menu is not opened.
What are you going to use in version 6? Is it possible to implement as plugin for version 5?
If I am to accept the fact that context menu wont work properly, any ideas how can prevent textarea from showing up in IE 11?

**Comment by marijnh** [comment]
Patches adb4ad3f7fc4 and a21ea6f496f0 should resolve this.
