### ISSUE TITLE
Julia indentation broken after "else" and "elseif"

### ISSUE THREAD

**Issue by LaurentLessard** [codemirror/CodeMirror#5702]
Indentation gets offset every time an "else" or "elseif" command is used in the Julia language. And it stays offset for the rest of the file. Here is the indentation I get in CodeMirror:
```julia
if x == 1
    println("one")
elseif x == 2
        println("two")
    else
            println("few")
        end
        println("all messed up now")
```
I would expect it to look like this:
```julia
if x == 1
    println("one")
elseif x == 2
    println("two")
else
    println("few")
end
println("all messed up now")
```

**Comment by marijnh** [comment]
@pabloferz Do you have time to take a look at this?
