### ISSUE TITLE
markText() splits emoji

### ISSUE THREAD

**Issue by vedadkajtaz** [codemirror/CodeMirror#5707]
Hello, 

Given the following sample code (using version 5.42.0 from a CDN):
```
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.42.0/codemirror.css">
	<style>
		.CodeMirror {border: 1px solid black; font-size:13px}
    </style>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.42.0/codemirror.js"></script>
</head>
<body>

<textarea id="code" name="code">🐎2345</textarea>

<script>

var cm = CodeMirror.fromTextArea(
	document.getElementById("code")
);

function	markText()
{
	var	doc = cm.getDoc();

	doc.markText(
		doc.posFromIndex(0),
		doc.posFromIndex(1),
		{ 'css' : 'background-color: red' }
	);
}


</script>

<button onclick="markText()">Mark first character</button>

</body>
</html>
```
Pressing the button invokes the `markText()` function, to mark the first character (from index 0 to 1). However, in the above example, CodeMirror splits the emoji which is placed as the first character into two invalid unicode characters. Poor horse.

Note that this is *not* related to  https://github.com/codemirror/CodeMirror/issues/4488 .
The above emoji character is U+1F40E (utf8 F0 9F 90 8E).

Kind regards,

**Comment by vedadkajtaz** [comment]
I was expecting this to behave identically on all platforms, but it appears Firefox PC and IE11 PC behave correctly. The above issue is reproducible on Chrome PC and Mac.

**Comment by vedadkajtaz** [comment]
The outcome is even worse on Safari - the whole content gets (visually) wiped out, making the editor unusable.

**Comment by marijnh** [comment]
Our current approach is that the caller of `markText` is responsible for making sure that the given start and end point fall on code point boundaries. This usually happens naturally, since you'll be using meaningful endpoints that you got from somewhere like selection positions or word boundaries, but if you blindly add 1 to a position that does cause problems.

**Comment by vedadkajtaz** [comment]
@marijnh Thanks for the quick reply.

I expected the emoji character to have the length of 1 in javascript (both the content and markup indexes are generated by a server search in my case), but that's not true.

This link explains it well, and how to workaround the issue:
https://mathiasbynens.be/notes/javascript-unicode#counting-symbols

**Comment by marijnh** [comment]
Yeah, UTF-16 is a really terrible thing, but unfortunately something we have to work with in JS.

**Comment by vedadkajtaz** [comment]
I was also mistaken by the fact the editor status displayed the correct length (counting the emoji as one character) - but that's because I used a strlen() implementation coined long ago, that did take the surrogate pairs into account.
