### ISSUE TITLE
Add mode "fish" to wishlist

### ISSUE THREAD

**Issue by hrvoj3e** [codemirror/CodeMirror#5726]
Please add mode "fish" for Fish shell
https://fishshell.com/
https://github.com/fish-shell/fish-shell

This is very similar to bash, zsh, ... small differences only.

**Comment by marijnh** [comment]
We're not adding modes to the main distribution at all anymore, and don't take requests for new modes. The best way to get a new mode is to implement it yourself and distribute it as a separate package on npm (see for example the [elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir))
