### ISSUE TITLE
window.jsyaml not defined, CodeMirror YAML linting cannot run.

### ISSUE THREAD

**Issue by Cloudzp** [codemirror/CodeMirror#5738]
## this is my code
```
import CodeMirror from 'codemirror'
    import 'codemirror/addon/lint/lint.css'
    import 'codemirror/lib/codemirror.css'
    import 'codemirror/mode/javascript/javascript'
    //import 'codemirror/mode/js'
    import 'codemirror/mode/yaml/yaml'
    import 'codemirror/mode/css/css.js'
    import 'codemirror/addon/lint/lint'
    import 'codemirror/addon/lint/yaml-lint'
    import {dump as toYaml, load as fromYaml} from 'js-yaml';
```
## this is my got error
![image](https://user-images.githubusercontent.com/25190767/50763233-2f5ee800-12aa-11e9-8092-93c47bf19069.png)

**Comment by marijnh** [comment]
The yaml linter file doesn't appear to properly declare js-yaml as a dependency, and instead gets it from `window.jsyaml`. As such, to use it, you'll have to make sure that property is present and holds the library (something with a `loadAll` property).

(yaml-hint.js was contributed and is pretty much unmaintained at this point)
