### ISSUE TITLE
Use Sublime syntaxes

### ISSUE THREAD

**Issue by jrappen** [codemirror/CodeMirror#5741]
Compare:

* https://github.com/Thom1729/SublimeSyntaxParser
* https://github.com/sublimehq/Packages

Why:

* improve highlighting for a few, loose a few
* win-win by outsourcing maintenance of syntax files to Sublime when/if editors are directed there for suggesting improvements

---

This was a random midnight idea. Feel free to close if it doesn't make sense continuing further.

**Comment by marijnh** [comment]
This isn't going to happen (at least not in the core library) in CodeMirror 5. In version 6, we are taking some inspiration from TextMate syntax bundles (which ST's system is based on), but it's unclear whether we'll directly support them (these use a regexp format different from, and more powerful than, JS's regexps, so they aren't trivial to run in the browser)
