### ISSUE TITLE
Codemirror autocomplete mode, I wanted to give new line when someone hit Enter..  Except autocomplete(Suggested) words

### ISSUE THREAD

**Issue by chandu89** [codemirror/CodeMirror#5743]
`if(event.key =="Enter" && $("li.CodeMirror-hint-active").length == 0){
        cmeditor.setCursor({line: cmeditor.getCursor().line, ch: 0, sticky: null});
      }
`
I am using above code but Its breaking if autosuggested word is popping up in that case anyone can use enter.

**Comment by marijnh** [comment]
I don't know where you're putting that code, but it doesn't look great. The recommended approach would be to bind a new command to Enter (using for example `extraKeys`), have that check for `editor.state.completionActive`, and return `CodeMirror.Pass` when it's false.

**Comment by chandu89** [comment]
Can you please tell me how i can use extrakeys in Codemirror..It would be helpful.

**Comment by marijnh** [comment]
You'll have to figure it out from [the manual](https://codemirror.net/doc/manual.html#option_extraKeys)

**Comment by chandu89** [comment]
I have tried with below code but not working ...
  `editor.setOption("extraKeys", {
      Enter: function(cm) {
        if (cm.state.completionActive){
          return CodeMirror.Pass;
        }
      }
    });`

**Comment by marijnh** [comment]
> and return CodeMirror.Pass when it's false.

So you'll need a `!` in front of the condition there.

**Comment by chandu89** [comment]
`extraKeys: {
            'Enter': function(){
              if (!editor.state.completionActive){ return CodeMirror.Pass; }
            }
        } `

Extra key is not working for me... Actually the block is not executing.
I have tried here its working.

[http://jsfiddle.net/aljordan82/h5f67/](Working Url)
