### ISSUE TITLE
Changing a theme should be considered as breaking change (?)

### ISSUE THREAD

**Issue by GuyShaanan** [codemirror/CodeMirror#5747]
Recently, a theme has been changed (https://github.com/codemirror/CodeMirror/commit/59a2b03bd5cca17166b0323551ed411fc10d7561#diff-6bf4afcdc6f4ee22d1c4185581c232a8) which affected the UX of our app.
Changing css rules like that (in our case the span.cm-def) so drastically should at least be mentioned in the Change List.
Although not a classic "breaking change" it is something that affects the UI of an app in a very bad manner.

**Comment by marijnh** [comment]
In version 6, themes will be their own semantically versioned packages. I didn't look too closely at that patch, assuming it just fixed some contrast issues, but yeah, it looks rather invasive. Will take better care next time.
