### ISSUE TITLE
Failing to detect the end of template string in a slightly modified version of Javascript's mode

### ISSUE THREAD

**Issue by LakshSingla** [codemirror/CodeMirror#5749]
Processing foundation uses CodeMirror in its web editor which is still in it's early stages. In order to style the added predefined functions of p5.js differently, it slightly modifies the [`mode/javascript/javascript.js`](https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js) to [`client/utils/p5-javascript.js`](https://github.com/processing/p5.js-web-editor/blob/master/client/utils/p5-javascript.js). An issue is arising in case of template string highlighting, where it is failing to recognize the end of the template string in case p5's functions are called. More info about this bug can be found on this issues page itself processing/p5.js-web-editor#773, where the explicit case in which it is arriving is enumerated. It would be helpful if someone provided an insight on why this bug is present.

PS. The p5-web-editor's code is not updated with the latest CodeMirror's version, which will be done along with rectifying this issue. The bug is not due to using an older version of the CM's code. (As I have tried it locally after updating the code)

**Comment by marijnh** [comment]
Could you try to reduce the breaking test case to the minimal code needed to trigger it?

**Comment by LakshSingla** [comment]
It fails to detect the end of template string when string interpolation is used and a `p5-function(e.g random(..), round(..)` is called upon to evaluate a result.
Minimalist case would be : 
``let x; ``
``x = `${round(2.1)}` //Would fail to evaluate the end of string correctly and parse this comment``

 - Minimal case where it doesn't work
![screenshot from 2019-01-17 19-36-55](https://user-images.githubusercontent.com/30999375/51323844-4e6e2e80-1a8f-11e9-917a-0dac2c9ad005.png)
 - Extensive list of cases where it works and where it doesn't 
![screenshot from 2019-01-15 22-13-29](https://user-images.githubusercontent.com/30999375/51323663-cc7e0580-1a8e-11e9-85f4-c1ee835ff4ca.png)

**Comment by marijnh** [comment]
If I paste this into https://codemirror.net/mode/javascript/ it seems to highlight fine

**Comment by LakshSingla** [comment]
Try using it here https://editor.p5js.org/ . The code is slightly modified in order to support special highlighting for the p5's functions and variables (which is the main cause of trouble). The modified version can be found [here](https://github.com/processing/p5.js-web-editor/blob/master/client/utils/p5-javascript.js#L50-L119). Changes made are from [Line#50](https://github.com/processing/p5.js-web-editor/blob/7bd016bac35b50d5ecb8b2fd97335d5e3b52bf6f/client/utils/p5-javascript.js#L50-L119)

**Comment by marijnh** [comment]
> The code is slightly modified in order to support special highlighting for the p5's functions and variables (which is the main cause of trouble)

I am not going to support you modified version of the code, sorry.
