### ISSUE TITLE
Where to get minified version?

### ISSUE THREAD

**Issue by JPustkuchen** [codemirror/CodeMirror#5752]
Some CDNs provide minified versions of all library .js files but currently I can't find a dist version of the library. npm install codemirror also doesn't provide min files... can someone help or would it be possible to create a dynamic ressource for a release containing dist/ folder?

**Comment by marijnh** [comment]
We don't provide a pre-minified version, but you can install terser or uglify-js and run it over the code, and you should be good to go.
