### ISSUE TITLE
Feature request: Support &/$0 in vim substitute replacements

### ISSUE THREAD

**Issue by nikklassen** [codemirror/CodeMirror#5753]
I'd like a way to refer to the entire search pattern in a Vim replacement. Currently I have to wrap the whole pattern in brackets and use $1 in my replacement.

Desired behaviour
:%s/foo/namespace.&/ = foo -> namespace.foo
or
:%s/foo/namespace.$0/ = foo -> namespace.foo

**Comment by marijnh** [comment]
(The vim bindings are not being actively maintained, so feature requests are unlikely to get acted on.)

**Comment by MarcelGerber** [comment]
@nikklassen Note that you can use `$&` (`:%s/foo/namespace.$&/`) to get the whole text. This may not be expected Vim behavior, but still, you can easily use it as a workaround.

**Comment by nikklassen** [comment]
That's exactly what I wanted. It should've occurred to me to try that given how other substitutions work. I really just wanted to use this feature, the exact syntax isn't important to me, and given that Vim bindings aren't being maintained this could probably be closed.

**Comment by ilyakharlamov** [comment]
fix in #5929 5929
