### ISSUE TITLE
Selection using mouse does not work in IE11 after call 'refresh' in listener of 'focus' event.

### ISSUE THREAD

**Issue by sohee-lee7** [codemirror/CodeMirror#5759]
I am using the CodeMirror and call to `refresh` function in the `focus` event handler.

```js
this.cm = CodeMirror.fromTextArea(cmTextarea, options);

this.cm.on('focus', () => {
   this.cm.refresh();
});
```
In this case selection using mouse does not work in **IE11**. I found the point of problem.

After call the `refresh` function, the `buttons` of `mousemove` event object is **0**.
So, the move operation is done.

https://github.com/codemirror/CodeMirror/blob/fc60137bcc5737b7fa7146fdebf311a93a2f231a/src/edit/mouse_events.js#L316

Is there a correlation between `refresh` function and mouse move behavior?
When debugging in more detail, the behavior in the `regChange` function seems to affect IE11 mouse events.

I would like to hear the opinion and would appreciate it if fix this.

**Comment by marijnh** [comment]
That's odd, that `buttons` would be set to zero. But in general, `refresh` is an expensive, somewhat invasive operation, and calling on every focus event is not a good idea, so the easiest way forward would probably be to find a way to do what you're trying to do that doesn't involve calling `refesh` on focus.

**Comment by sohee-lee7** [comment]
@marijnh Thank you for quick response. I will accept your opinion that it is not good to call refresh on focus events. Thank you :)
