### ISSUE TITLE
API provides no way to insert text around inclusiveLeft/inclusiveRight markers

### ISSUE THREAD

**Issue by thomasjm** [codemirror/CodeMirror#5763]
This sandbox should show most clearly what I'm trying to do: https://codepen.io/anon/pen/bzWpGR

This is partly a question and partly a feature request, if it's not possible. I'm wondering if there's some way to programmatically insert text to the left of an `inclusiveLeft` marker (or right of an `inclusiveRight`) marker without the text being eaten by the marker, and preferably without clearing the marker.

(The motivation for this is to make a collaborative text editor. Suppose user 1 has a collapsed widget on a certain line, and user 2 in another browser inserts a newline on the previous line. When we apply this change to user 1's document we want to do so without the newline being eaten by the marker, but there doesn't appear to be an easy way to do this.)

**Comment by thomasjm** [comment]
Possible solution: reach into the marker and temporarily change its `inclusiveLeft`/`inclusiveRight` setting. How bad an idea is this? https://codepen.io/anon/pen/VgbgKY

**Comment by marijnh** [comment]
Markers can't be changed during their lifetime—that hack might work, but it's not something the library expects, so it's likely to break in subtle ways. The only way to do this would be to remove the mark, make the changes, and recreate it in the proper new position.

More generally, if you don't want inclusive behavior, maybe the mark shouldn't have those options enabled?

**Comment by thomasjm** [comment]
You're right that I don't want inclusive behavior. What I want is for the line to be collapsed, so it's impossible to put the cursor on the line with the marker. But as the manual says, "In atomic ranges, `inclusiveLeft` and `inclusiveRight` have a different meaning—they will prevent the cursor from being placed respectively directly before and directly after the range." So I'm forced to use the inclusive options to get the effect I want. Perhaps the real source of the trouble is how the meaning of `inclusiveLeft`/`inclusiveRight` is overloaded this way.

Maybe it would be good to separate the "no cursoring before or after" meaning into a separate option called `preventCursorLeft`/`preventCursorRight` (which has no effect on non-atomic ranges)?

**Comment by thomasjm** [comment]
This was closed by #5773
