### ISSUE TITLE
Is there a way to batch operations without updating display?

### ISSUE THREAD

**Issue by robinp** [codemirror/CodeMirror#5766]
I would like to perform mass `markText` on a document, and currently it takes a long time. Is it possible to perform these changes more efficiently?

Thank you!

**Comment by marijnh** [comment]
Yes, [there is](https://codemirror.net/doc/manual.html#operation)!

**Comment by robinp** [comment]
Wow, thanks! This resulted in ~30x speedup. Idea: could add `batch` keyword in that section of the manual so it is easier to find.
