### ISSUE TITLE
Accesskeys ignored while editor focused

### ISSUE THREAD

**Issue by rosano** [codemirror/CodeMirror#5767]
Probably related to #5253. This is about [accesskeys](https://www.w3schools.com/tags/att_global_accesskey.asp) effectively being ignored while the editor is focused. You can see on [my fork of CodeMirror homepage](https://rosano.github.io/CodeMirror/) with accesskey `x` on the `select` element for other demos - when the editor is not focused, it can be used to highlight the selector, when the editor is focused, it is ignored.

I'm trying some hacky workarounds where I focus on some element outside of the editor if there is `Alt-$SomeSingleLetter` on `keydown`, but it means I have to invoke the accesskey a second time to actually get to my destination. The commented code is stuff I've tried that doesn't seem to solve the problem.

```javascript
editor.on('keydown', function (instance, event) {
  if (!event.altKey) {
    return;
  }

  if (event.key.length > 1) {
    return;
  }

  if (event.key.match(/\W/)) {
    return;
  }

  // event.codemirrorIgnore = true;

  // event.preventDefault();

  document.getElementById('SomeElement').focus();
  // document.body.dispatchEvent(new KeyboardEvent('keydown', event))
});
```

I'm hoping I haven't missed something obvious in the manual!

**Comment by marijnh** [comment]
Which browser and platform are you using? On Firefox Linux, access keys work with alt+shift, and pressing alt-shift-x while the editor is focused in your demo does focus the select field. If there's some other command bound to a key combination that's also used as access key, then yes, the editor will `preventDefault` that event when handling the key combination.

**Comment by rosano** [comment]
Okay, I'm on macOS and it looks like only Safari is doing this - works fine on Firefox, Chrome, and two other Chromium browsers I tested. It looks like there might be some OS-level commands (see below) bound to `Ctrl-Alt-…` only in Safari.

I have another project that uses CodeMirror and the access key `1` works fine, so if you ever have a hunch on why this certain keys do this please let me know.

* * *

Slight tangent that might be related, but when I try `Ctrl-Alt-N`, these bright red dots get inserted in the editor:
<img width="602" alt="screen shot 2019-02-05 at 09 17 07" src="https://user-images.githubusercontent.com/1680612/52279275-33246f80-2927-11e9-83f8-d2f3ba91689f.png">

When I copy and paste them into a plaintext editor, they appear as some kind of special invisible byte character `` or `<0x0e>`. The shortcut creates the same character in the native RTF editor TextEdit, and this other web-based code editor (only in Safari) https://ace.c9.io .

**Comment by marijnh** [comment]
macOS does some really strange character insertion on some key combinations. See also https://github.com/codemirror/CodeMirror/issues/2689
