### ISSUE TITLE
On resize, screen is partially blank until the first click.

### ISSUE THREAD

**Issue by cdsmith** [codemirror/CodeMirror#5770]
When I resize the CodeMirror editor at http://code.world, the bottom part of the screen remains blank.  The document is still there, and finishes drawing the first time I click on the editor or make any other change (even another resize).

![ezgif-4-d54d0c3dd15a 1](https://user-images.githubusercontent.com/544744/52290329-d2ecf800-293d-11e9-8441-25a63d788b53.gif)

**Comment by cdsmith** [comment]
(This is https://github.com/google/codeworld/issues/819 on my side.)

**Comment by cdsmith** [comment]
The changelog for 5.39.0 suggests this may be fixed.  I'll update the editor on a test server and see if that fixes it.

**Comment by marijnh** [comment]
You have to make a call to `.setSize()` (without arguments) on the editor instance to make it query its new size and update itself. Unfortunately, the DOM does not allow a script to notice when a given element is resized or restyled (short of expensive polling), so CodeMirror relies on you telling it when to update itself in that case.
