### ISSUE TITLE
mode playground: cm-variable and cm-property on default theme

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#5772]
I'm using https://codemirror.net/mode/javascript/typescript.html to test some TS snippet.
It would be nice if cm-variable and cm-property were also highlighted with some different color.
ATM is a little hard to tell if everything is highlighted correctly without using the browser dom inspector.

Another option could be to always have the ability to change the theme in the playground.

**Comment by marijnh** [comment]
The default theme intentionally doesn't color those. You can use the inspector to figure out the class of a given token.
