### ISSUE TITLE
[Typescript] bug -- backticks sometimes results in the rest of the file being highlighted as a string

### ISSUE THREAD

**Issue by williamstein** [codemirror/CodeMirror#5774]
Here is a minimal .ts example to reproduce the problem:
```
class Foo {
  f(obj) {
    for (let key in obj) {
    }
  }

  g(a: string): void {
    if (!this.h(a)) {
      throw Error(`${a}`);
    }
  }

  // This should not be red!
  h(a: string): boolean {
    //...
  }
}
```

Paste that into [the official demo](https://codemirror.net/mode/javascript/typescript.html) and you'll see: 

![image](https://user-images.githubusercontent.com/1276278/52360353-a8a84280-29f0-11e9-94c4-228a712159e3.png)

**Comment by haraldschilly** [comment]
I refined the one above to be a bit shorter. It seems to trip over nested `{ { .. } }`:

```
if (true) {
  for (let i in [1, 2, 3]) {
    console.log(`${i}`);
  }
}
console.log("this is all orange");
console.log("this is all orange");
console.log("this is all orange");
```

![screenshot from 2019-02-06 18-40-09](https://user-images.githubusercontent.com/207405/52361472-a7056b80-2a3e-11e9-8b7d-eec92d4a35b6.png)

**Comment by OmgImAlexis** [comment]
Seems this is still an issue https://github.com/alexcanessa/typescript-coverage-report/issues/61#issue-873674065

**Comment by marijnh** [comment]
That's a different issue -- the mode didn't support the newly introduced template string types yet. Attached patch should address that.
