### ISSUE TITLE
Pasting into the Code Mirror doesn't refresh the cell

### ISSUE THREAD

**Issue by applecool** [codemirror/CodeMirror#5778]
Hi,

Whenever I copy some lengthy code from a file and paste into the code mirror cell, it shows only the last part and until I click on the cell, it doesn't show the entire code which was pasted. I am already using the `display/autorefresh` addon and setting the `autoRefresh: true` as the config option at the time of initialization of the code mirror. And I tried calling `codemirror.refresh()` after creating the cell. It doesn't work. I think whenever the paste event is triggered, I need to call the `refresh()` but I am not sure what's the correct way to do this. Could anyone point me in a right direction? 

Thank you.

**Comment by applecool** [comment]
@marijnh

**Comment by adrianheine** [comment]
Does the same happen for you in any of the demos on the website? Otherwise, please post an example setup hat has this issue.

**Comment by applecool** [comment]
I actually fixed the issue by handling the `paste` event at document level and calling `cm.refresh()` on it. Thanks.
