### ISSUE TITLE
Value change won't refresh the view while the editor is not visible

### ISSUE THREAD

**Issue by jarrodek** [codemirror/CodeMirror#5779]
Hi,
Great project. I am using it for Advanced REST Client and API Console projects.
The use case is that the user can navigate through API documentation (API Console) and then try the API. CM is used for both headers and payload editors. The thing is, the request editor is hidden in mobile view while you are navigating the documentation but the values are still set on the editor at the same time. When the user switch to the request editor he sees previously selected body. When you get value from the editor it contains new value, however the view still shows old value. When calling refresh it would reset the view but I believe it shouldn't be required (to call the function).
I am having trouble with recognising whether the panel is rendered or not as the body editor is a web component (inside few other web components in the tree). Therefore I would need to define a function on each component in the tree to finally call the refresh function. This might now always be possible, however. When using 3rd party components I wouldn't have direct access to change the API.

As a side note, I saw your article about CM6. I'd be happy to contribute in capacity to bring CM6 to the web components ecosystem. I am doing it anyway for my projects but I could provide official support.

**Comment by marijnh** [comment]
> When calling refresh it would reset the view but I believe it shouldn't be required (to call the function).

It is, though. The editor can't notice when it becomes visible, and it needs its size to draw itself properly.
