### ISSUE TITLE
How to hide XML tag attributes or lock XML tag attributes

### ISSUE THREAD

**Issue by dataangel** [codemirror/CodeMirror#5784]
Like what：<xml data1="abc" data2="aaa"></xml> 
1:data1 hide  attributes
2:data1 lock attributes  Cannot be modified

**Comment by marijnh** [comment]
Questions such as this one are better put on the [forum](https://discuss.codemirror.net/), not the bug tracker.

[The `markText` method](https://codemirror.net/doc/manual.html#markText), especially its `readOnly` option, might be of interest.
