### ISSUE TITLE
Shift-Ctrl-F won't trigger replace dialog

### ISSUE THREAD

**Issue by reactma** [codemirror/CodeMirror#5785]
Hi, I was trying out the Search/Replace addon and found out Shift-Ctrl-F won't trigger replace dialog. The others work as expected.

It wouldn't work with my code and I also directly tested it on your demo here [Search demo](https://codemirror.net/demo/search.html), which would't work either.

I use Fedora 29 and tested it on both Firefox and Chromium.

**Comment by marijnh** [comment]
Works for me in both Firefox and Chrome (also on Linux). Could it be that your system is capturing that key combo before it gets to the browser?

**Comment by reactma** [comment]
Yes you are right. I have an IME that uses Ctrl-Shift-F to do certain thing. After I disable the combo the demo worked.
Thanks for the quick response.
