### ISSUE TITLE
Cursor vanishes at 90% zoom on Chrome/Mac

### ISSUE THREAD

**Issue by dpage** [codemirror/CodeMirror#5788]
With zoom set to 90% on Chrome on macOS, the cursor vanished in some positions, for example: 

select (
) a

Position the cursor prior to a and it disappears. e.g., ") |a"

Original issue logged on the pgAdmin project: https://redmine.postgresql.org/issues/3988

**Comment by marijnh** [comment]
This is the same issue as #5056
