### ISSUE TITLE
Question: Why textAfter argument in indent method for custom mode is always empty?

### ISSUE THREAD

**Issue by shubhsharma10** [codemirror/CodeMirror#5789]
Hi,
I am writing a custom mode, where I am trying to implement smart indentation using content in previous line and current line. However in indent method textAfter argument is always empty. Reason for that is I think that indent method gets called only when new line is entered. So what's the use of textAfter argument? Is there any way to trigger indent method while we are in a line?

**Comment by marijnh** [comment]
> So what's the use of textAfter argument?

It will, as you guessed, give access to the text after the line break when you press enter inside a line, which is useful when you want to align closing brackets with the indentation of the line that started them or something like that.

Shift-tab reindents the selected lines. Modes can declare an `electricInput` regexp that, when typed text matches it, will cause the current line to be reindented.
