### ISSUE TITLE
[Swift] empty string highlighting problem

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#5793]
if you go to https://codemirror.net/mode/swift/index.html and put in this:

```swift
print("")
print("")asdfadsfkjdsf//dsfsdfsdf
```

You'll find that the close parens and all the characters afterwards are highlighted like strings, which seems wrong:

![image](https://user-images.githubusercontent.com/613320/53458525-5785e000-39eb-11e9-8a97-034405c37a19.png)

**Comment by marijnh** [comment]
I'm not actively maintaining the Swift mode, so the quickest way to get this fixed would be a pull request.

**Comment by vincentwoo** [comment]
No prob. We'll try to make some time to figure this one out.
