### ISSUE TITLE
Looks like D and clike modes in the npm package are broken

### ISSUE THREAD

**Issue by CodeMyst** [codemirror/CodeMirror#5795]
Both D and clike output the same result to me, might be just in the npm package?

![image](https://user-images.githubusercontent.com/7966628/53685261-9cc24e80-3d18-11e9-8444-dae35f4609ed.png)

**Comment by marijnh** [comment]
They look fine on the website ([d](https://codemirror.net/mode/d/), [clike](https://codemirror.net/mode/clike/)). That screenshot is also showing highlighting. Are you sure the problem isn't in your setup?

**Comment by CodeMyst** [comment]
Yeah, most likely. I tried using the modes from the source directly and those have the same result. I am making a Vue.js app and creating the editor like so:
```ts
import Vue, { VNode } from 'vue';
import * as cm from 'codemirror';
import 'codemirror/mode/pug/pug';
export default Vue.extend
({
    mounted () : void
    {
        this.$nextTick (function ()
        {
            const textArea: HTMLTextAreaElement = this.$el.getElementsByClassName ('editor') [0] as HTMLTextAreaElement;
            const editor: cm.Editor = cm.fromTextArea (textArea, { mode: 'pug', theme: 'base16-dark', indentUnit: 4, lineNumbers: true });
        });
    }
});
```

**Comment by CodeMyst** [comment]
I tried making an empty project with CodeMirror, got the same results: https://jsfiddle.net/mpzo0s5q/

**Comment by marijnh** [comment]
Set the mode to `text/x-d`, not just `d`, which is (for some reason) a generic unconfigured version of the mode that doesn't know about keywords and such.

**Comment by CodeMyst** [comment]
Ah! Thank you! 😄
