### ISSUE TITLE
search in one line only instead of whole doc

### ISSUE THREAD

**Issue by mafar** [codemirror/CodeMirror#5796]
I have a usecase where I want to search a given query for a specifc line instead of whole document as user lready knows line number 

**getSearchCursor** _function_ from **search/searchcursor.js**  accepts start object, but how can i limit it to just that line

```js
  cm_instance.getSearchCursor(query, {
    line: 5,
    ch: 0
  }, {
    caseFold: queryCaseInsensitive(query),
    multiline: true
  });
```

**Comment by marijnh** [comment]
Use `getLine` to get the line's content and run you regexp directly on the result? The point of search cursors is that they abstract the multi-line seaching logic. If you don't need that, you probably don't need an abstraction at all.

**Comment by mafar** [comment]
Great idea thanx
