### ISSUE TITLE
[Julia] Extraneous '}' causes highlighting to "crash"

### ISSUE THREAD

**Issue by mlubin** [codemirror/CodeMirror#5797]
When I paste the code below into https://codemirror.net/mode/julia/index.html and then press enter three times, all the text disappears.
```jl
struct S
    field::Float64}
end
```
The `}` is incorrect syntax. However, the fact that the text disappears makes it hard to correct the syntax error :)

Browser: Chrome 72.0.3626.119 on Linux 64 bit.

Screenshots:

![image](https://user-images.githubusercontent.com/1733683/53820519-edfd5880-3f39-11e9-8049-e78e22e512f5.png)

This is after pasting the code, before pressing enter.

![image](https://user-images.githubusercontent.com/1733683/53820568-053c4600-3f3a-11e9-90a8-8fdea307d421.png)

This is after pressing enter once. Note that the `end` appears on its own.

![image](https://user-images.githubusercontent.com/1733683/53820622-23a24180-3f3a-11e9-88ad-f56d96607704.png)

This is after pressing enter two additional times. All the text disappears.

CC @pabloferz (most active author on the Julia syntax highlighting)

**Comment by adrianheine** [comment]
Same happens for me. I also tried disabled the matchbrackets addon, but it still happens.
