### ISSUE TITLE
How can i add   customer  keyword ,atoms etc

### ISSUE THREAD

**Issue by jol5** [codemirror/CodeMirror#5799]
![image](https://user-images.githubusercontent.com/28615922/53856209-fb831300-400b-11e9-875b-8ec8831ffa2f.png)
i want to add some custom keywords, and show it during show hint.

**Comment by marijnh** [comment]
Going by the screenshot, I'm going to assume you're trying to define a custom SQL dialect. If so, yes, that screenshot pretty much shows what you should do—define a MIME type with `name: "sql"` and your language description in the other properties. To access the values used in other SQL dialect, which you might want to use as a base, you can use `CodeMirror.resolveMode("text/x-....")`, which'll give you the configuration object for the MIME you passed.
