### ISSUE TITLE
append parent after CodeMirror is not working

### ISSUE THREAD

**Issue by llpamies** [codemirror/CodeMirror#5800]
The following code works:

```
var cont = document.createElement('div');
document.body.appendChild(cont);
CodeMirror(cont, {});
```

However, this doesn't work:

```
var cont = document.createElement('div');
CodeMirror(cont, {});
document.body.appendChild(cont);
```

It shows the UI all messed up with the elements out of place.

**Comment by marijnh** [comment]
Yes, that's a known limitation—you have to call `.refresh()` on the editor when it's added to the DOM (if it's not initialized there). This is unlikely to change in version 5 (there is, at least in a bunch of the supported browsers, no way for the editor to notice it has been added to the DOM, short of polling, which is unattractive)

**Comment by llpamies** [comment]
Thanks for the explanation.
