### ISSUE TITLE
use fastdom to avoid unnecessary document reflows

### ISSUE THREAD

**Issue by futurist** [codemirror/CodeMirror#5823]
CodeMirror and [codemirror.next](https://github.com/codemirror/codemirror.next) can use [fastdom](https://github.com/wilsonpage/fastdom) to avoid unnecessary document reflows when possible, like below function (`updateGutterSpace`)

![image](https://user-images.githubusercontent.com/159167/54729010-f00f1a80-4bbb-11e9-9b9c-56d81a678cd2.png)

After changing `updateGutterSpace` to use **fastdom**, the performance is far more better:

![image](https://user-images.githubusercontent.com/159167/54729443-74629d00-4bbe-11e9-9055-2105a4010b66.png)

**Comment by marijnh** [comment]
We have our own, similar (but synchronous) solution for this (see operations, specifically the `endOperation` code)
