### ISSUE TITLE
Markdown bold and italics higlighted even when there is a space before the ending *

### ISSUE THREAD

**Issue by GenaBitu** [codemirror/CodeMirror#5828]
### Description
before the closing * of a part of the text, it shouldn't be italics/bold. In the editor, it not only is higlighted as bold, but the bolding doesn't end with the closing * and continues on.

### To Reproduce
`**Hello ** World`

### Expected behavior
\*\*Hello \*\* World

### Actual behaviour
**\*\*Hello \*\* World**

**Comment by marijnh** [comment]
Yes, the markdown mode doesn't look ahead to find a matching end marker for inline styles (for reasons of performance and technical limitations), so this is intentional behavior. This already exists as an issue in #4501
