### ISSUE TITLE
sublime bindings is incorrect 

### ISSUE THREAD

**Issue by Amanda1995pig** [codemirror/CodeMirror#5835]
Hi all,
   My project is in Angular6，when I import 'codemirror/keymap/sublime.js' And set the keyMap option to "sublime". "Ctrl-/" is not working.And, I check the console,it shows "cm.toggleComment is not a function  at cmds.toggleCommentIndented (sublime.js:277)".
  But some of other hot keys is working.
    I want to toggle comment by "Ctrl-/",how to resolve this question?

**Comment by marijnh** [comment]
Looks like you didn't load the `addon/comment/comment.js` addon.

**Comment by Amanda1995pig** [comment]
Thanks for your helping,Adopting your suggestion,I resolved the error in console.And it works on the mode of 
"text/x-mysql",But it doesn't work on the mode of "text/javascript"

**Comment by marijnh** [comment]
That's odd—commenting should be supported in JavaScript as well, and on the [sublime bindings demo](https://codemirror.net/demo/sublime.html), which is in JavaScript mode, it does work
