### ISSUE TITLE
extrakey doesn't work when I change mode dynamically

### ISSUE THREAD

**Issue by Amanda1995pig** [codemirror/CodeMirror#5836]
In my Angular6 project,My codeMirror options are as follows:

```
 this.CodeMirrorEditor = CodeMirror.fromTextArea(dom, {
      lineNumbers: true,
      cursorHeight: 1,
      mode: type === 'sql' ? { name: "text/x-pgsql" } : { name: "text/javascript", json: true },
      theme: 'dracula',
      styleActiveLine: true, // 当前行背景高亮
      scrollbarStyle: 'overlay',
      autofocus: true,
      extraKeys: {
        "F11": (cm) => {
          cm.setOption("fullScreen", !cm.getOption("fullScreen"));
        },
        "Esc": (cm) => {
          if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
        },
        "Ctrl-/": 'toggleComment',
      },
    })
```

I change the mode dynamically,but the extrakey 'Ctrl-/' only worked at the first model

I want  the extrakey 'Ctrl-/' to work at the mode of both

**Comment by marijnh** [comment]
Works fine for me (when I load the sql mode into demo/sublime.html and switch to it, commenting with ctrl-/ still works)

**Comment by Amanda1995pig** [comment]
Thanks for your helping!
I have resolved the issue by replace the { name: "text/javascript", json: true } with { name: "text/javascript" } 
And How can I  achive  Multi-line comment by extraKeys ??

**Comment by marijnh** [comment]
JSON doesn't have comments, so that mode intentionally doesn't have comment metadata.

> And How can I achive Multi-line comment by extraKeys ??

See the [manual](https://codemirror.net/doc/manual.html#addon_comment) for a list of methods added by that addon. You can call those from a key handler function.

**Comment by Amanda1995pig** [comment]
Ok, Thanks for helping me.
