### ISSUE TITLE
Prolog syntax highlight request

### ISSUE THREAD

**Issue by XVilka** [codemirror/CodeMirror#5842]
To support Prolog syntax highlight.
See [Atom syntax highlight](https://github.com/Jakehp/language-prolog) for example.

**Comment by marijnh** [comment]
We aren't adding new modes to the main distribution anymore—so the recommended way to go forward would be to implement it yourself and distribute it is as separate package, say `codemirror-mode-prolog`.

There's this [ancient thread](http://codemirror.977696.n3.nabble.com/A-Prolog-mode-for-CodeMirror-td4028633.html) where someone was working on such a mode, but it seems like it was never merged in.
