### ISSUE TITLE
javascript mode restrict to json mode seems not working

### ISSUE THREAD

**Issue by zedongh** [codemirror/CodeMirror#5852]
What i really want a json mode, not a complete javascript mode, I read the docuement, 

> JavaScript mode supports several configuration options:
> json which will set the mode to expect JSON data rather than a JavaScript program.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet" href="codemirror-5.45.0/lib/codemirror.css">
  <script src="codemirror-5.45.0/lib/codemirror.js"></script>
  <script src="codemirror-5.45.0/mode/javascript/javascript.js"></script>
</head>
<body>
<textarea id="code"></textarea>
<script>
  let editor = CodeMirror.fromTextArea(document.getElementById("code"), {
      mode: "application/json",
      lineNumbers: true,
  });
</script>
</body>
</html>
```

will still mark `function` as keyword.

**Comment by marijnh** [comment]
That doesn't exist. The JavaScript mode in JSON configuration will correctly highlight valid JSON, but it'll treat some forms of invalid JSON as JavaScript code.
