### ISSUE TITLE
token/state/stream behave differently for unrendered text?

### ISSUE THREAD

**Issue by breck7** [codemirror/CodeMirror#5862]
I wrote my own mode. It works great for short documents. But breaks for long documents.

Are there guidelines how to handle the "virtualization" bit of CodeMirror?

If I paste a 141 line block of text into my CM instance, my highlighter breaks, UNLESS I set "viewportMargin" to something like 200, to ensure all lines are processed.

So It seems something different happens with token/stream/state, when you have a big document vs a small one, that I don't see documentation on.

It seems like something akin to "blankLine()" is happening?

**Comment by marijnh** [comment]
From your description of the issue it sounds like you're misunderstanding the interface—there is no guarantee that a mode is always ran sequentially over the entire input. It generally won't be run over content below the viewport, and will be resumed with a previously stored state from a few lines above the change when something changes. I can't quite figure out what's going on, but maybe you're using global state or storing state in the state object in a way that doesn't get copied properly.

**Comment by breck7** [comment]
You're absolutely right! I assumed the highlighting was run over the entire input.

In order to get the correct token style my method only needs the code, linenumber and position. I was using the "state" to store the line number and that's where the bug was coming from.

A much simpler solution is for me to get the line number from the stream.

I now use stream.lineOracle.line to access the line number. I'm not sure if this is a no-no, as I don't see this lineOracle object in the public interface (either in the docs or in the TypeScript). However, it works great for my purposes. Is that okay to use, or is there a reason why it's not exposed?

Thanks for your help!

My now fixed example: http://treenotation.org/sandbox/grammars.html

**Comment by marijnh** [comment]
The info produced by a highligher run might be reused after changes, even when those changes are above it and thus the line numbers don't align anymore. That's why you probably shouldn't rely on having access to line numbers in the mode.

That being said, unless you define a `stateEqual` method, such data will probably be overridden by a new run pretty quickly, and thus might be harmless.

**Comment by breck7** [comment]
Thank you for your help. So far the line number approach seems to be working but may have to revisit once it has more use and maybe more chance of hitting edge cases.
