### ISSUE TITLE
GitHub Flavored Markdown mode should not have strikethrough in the editor

### ISSUE THREAD

**Issue by Jakobud** [codemirror/CodeMirror#5865]
On your page here:

https://codemirror.net/mode/gfm/index.html

You can see that in the editor, when you use `~~text~~` it actually puts strikethrough text IN the editor. This is wrong. It should not do this. It doesn't do it on GitHub with their markdown. This markdown syntax is to generate strikethrough text in the RENDERED markdown output. Not in the actual markdown itself.

The easy solution is to remove this line:

https://github.com/codemirror/CodeMirror/blob/8900d1b7bce09c7101be631d9afa16a74c6e4598/lib/codemirror.css#L117

**Comment by marijnh** [comment]
Is this any different from how it shows emphasized text as emphasized in the editor?

**Comment by Jakobud** [comment]
Actually that is a good point. Upon further inspection Codemirror also incorrects adds emphasis and strong/bold to markdown:

![Screenshot_23](https://user-images.githubusercontent.com/87356/57184577-9ff1cc00-6e7a-11e9-8354-5848e194fc67.png)

Markdown is supposed to be completely un-formatted text. It made to GENERATE formatted text. But the markdown itself should not be formatted:

https://guides.github.com/features/mastering-markdown/

If you need to see more proof of this simply copy paste the examples into a GitHub comment window:

![Screenshot_22](https://user-images.githubusercontent.com/87356/57184590-e1827700-6e7a-11e9-85d3-61882947aa69.png)

Make sense?

**Comment by marijnh** [comment]
No, that doesn't make sense. This is intentional behavior. You can define your own CSS to turn if off if it bothers you, but claiming that it's "incorrect" is nonsense, and its going to stay this way in the default setup, because other people appreciate this behavior.

**Comment by Jakobud** [comment]
Hmmm okay.... Do you realize that when you look at every single implementation of markup out there (for example on GitHub or Stackoverflow) that the markup is **not** styled?

https://stackoverflow.com/editing-help
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
https://support.zendesk.com/hc/en-us/articles/203691016-Formatting-text-with-Markdown
https://daringfireball.net/projects/markdown/syntax
https://www.markdownguide.org/basic-syntax
https://commonmark.org/help/

Just trying to help your library be consistent with what Markdown actually is by definition. Take care,
