### ISSUE TITLE
Lint's async option breaks the editor.

### ISSUE THREAD

**Issue by elpeleq42** [codemirror/CodeMirror#5875]
Whenever I set async:true within lint options, codemirror editor's break throwing this error
"Uncaught ReferenceError: schemaLint is not defined"(No errors are thrown without that option)

I tried googling what this schemaLint was but couldn't find anything. Also there's no info about how to use the async option nor what it does exactly, besides [this issue from 2015](https://github.com/codemirror/CodeMirror/issues/3073)

**Comment by Narias1999** [comment]
Same problem, any solution for this issue?

**Comment by marijnh** [comment]
The identifier `schemaLint` does not exist in this repository, so I expect the problem is elsewhere.
