### ISSUE TITLE
Number before hints

### ISSUE THREAD

**Issue by jbharatrhodes** [codemirror/CodeMirror#5880]
Hi,

I am new to codemirror and please forgive me if this is a silly question. I want to add numbers before the hints. As an example for HTMLmode when < is typed then 1 <a  2 <abbr   3 <address will be displayed and i can type 2 to select <abbr>. Is there any way to do that?

Thank you

**Comment by marijnh** [comment]
You could style the `ul.CodeMirror-hints` elements with `list-style: decimal`, but picking completions by numbers is currently not supported.
