### ISSUE TITLE
Gutter trouble: CodeMirror-linenumber not defaulting to right

### ISSUE THREAD

**Issue by Nerbert1** [codemirror/CodeMirror#5884]
I recently upgraded from 5.30 to 5.46. I'm using the old deprecated addon collapseRange. In 5.30 it wasn't necessary to set a gutter option but now it is in 5.46. 

Code from addon:

	var gutterClass = "CodeMirror-collapserange";

	function enableRangeCollapsing(cm) {
		cm.on("gutterClick", gutterClick);
		cm.setOption("gutters", (cm.options.gutters || []).concat([gutterClass]));
	}

	function disableRangeCollapsing(cm) {
		cm.rangeCollapseStart = null;
		cm.off("gutterClick", gutterClick);
		var gutters = cm.options.gutters;
		for (var i = 0; i < gutters.length && gutters[i] != gutterClass; ++i) {}
		cm.setOption("gutters", gutters.slice(0, i).concat(gutters.slice(i + 1)));
	}
In 5.46, CodeMirror-collapserange is to the right of CodeMirror-linenumbers, in  5.30 the sequence was correct. I don't know if this is a problem associated with using old code or a general problem. Setting a gutters option with the correct sequence solves the problem for me.

**Comment by marijnh** [comment]
Strange, `.getOption('gutters')` seems to still return `[]` when no explicit line number gutter position was specified, and setting it to `["CodeMirror-collapserange"]` does, for me, put the line number gutter to the right of the collapserange gutter.

Can you distill the calls that lead to the unexpected behavior down to the minimum sequence needed to illustrate the issue?

**Comment by Nerbert1** [comment]
The more I tinker with this the more I'm convinced it's a problem with my code. I was using some clumsy code but it worked in 5.30. It's still strange to me it would change in 5.46. I think when I get things tidied up I'll get consistent behavior.

**Comment by marijnh** [comment]
Sounds good. Let me know if you uncover any actual issue.

**Comment by Nerbert1** [comment]
[codemirror-toolbars-1.3.zip](https://github.com/codemirror/CodeMirror/files/3207368/codemirror-toolbars-1.3.zip)
I've tried all kinds of experiments on this and can't resolve it, so I'll let you have a look.

Upload the included file to a directory with various CodeMirror versions available and navigate to codemirror-toolbars-1.3/doc/manual.html. Set the version in the navbar.  In the Demos menu try example/test.html and View Code. 

Test.html is an example of adding ToolBars using a CodeMirror option, View Code (misc/code.html) is an example of adding ToolBars to an existing instance of CodeMirror.

View Code by default shows my main file, lib/toolbars.js. Relevant code on lines 24, 257 and 2508. The reason for disabling and then enabling at line 257 is that ToolBars.addToolBarsToEditor() (line 2433) can be used to add ToolBars to an existing editor or to rebuild them if you are making a change that involves major DOM changes (an example of this is toggling between using icons or phrases in test.html, or see demo/toolbars.html and toggle between Full Search and Mini Search)

As you can see I have the top part of collapseRange commented out. I've tried leaving that in and not enabling at line 257. No matter what I try in version 2.46 I still get collapserange to the right of linenumbers 

(By the way, do you know what the error "(WEB_PAGE context) Couldn't find native for requireNative(addons)" is on the manual page?)

**Comment by Nerbert1** [comment]
As an aside, collapseRange really is a nice product. It would be handy for drag drop; I could never get drag drop to auto-scroll with the native code so I coded in my own auto-scroll in ToolBars (try it). I don't know if this is a CodeMirror issue or a browser issue. But I did have a bit of a problem margining it to the left and getting it to work.

**Comment by marijnh** [comment]
That doesn't sound like a minimal, no frills demonstration of the problem. Sorry, but I don't have time to dive into your code.

**Comment by Nerbert1** [comment]
But I still think it's a general problem you would have with gutters.

**Comment by Nerbert1** [comment]
If you're still listening, I found the problem (or the _difference_ anyway).

I modified enableRangeCollapsing() as follows:

	function enableRangeCollapsing(cm) {
		cm.on("gutterClick", gutterClick);
			console.info(cm.getGutterElement().querySelectorAll("div"))
			console.info('gutters = ' + cm.options.gutters)
		cm.setOption("gutters", (cm.options.gutters || []).concat([gutterClass]));
			console.info('gutters = ' + cm.options.gutters)
	}

in 5.30.0 I get

NodeList [div.CodeMirror-gutter.CodeMirror-linenumbers]
toolbars.js:2522 gutters = CodeMirror-linenumbers
toolbars.js:2524 gutters = CodeMirror-linenumbers,CodeMirror-collapserange

in 5.46.0 I get

NodeList [div.CodeMirror-gutter.CodeMirror-linenumbers]
toolbars.js:2522 gutters = 
toolbars.js:2524 gutters = CodeMirror-collapserange

So, even tough the linenumbers div is there, it doesn't show in cm.options.gutters

**Comment by marijnh** [comment]
Ah, right, the `gutters` option preserves what you put in there now, whereas it used to replace it with an updated value when necessary.

**Comment by Nerbert1** [comment]
5.30.0 has this function on line 4328

      // Make sure the gutters options contains the element
      // "CodeMirror-linenumbers" when the lineNumbers option is true.
      function setGuttersForLineNumbers(options) {
        var found = indexOf(options.gutters, "CodeMirror-linenumbers")
        if (found == -1 && options.lineNumbers) {
          options.gutters = options.gutters.concat(["CodeMirror-linenumbers"])
        } else if (found > -1 && !options.lineNumbers) {
          options.gutters = options.gutters.slice(0)
          options.gutters.splice(found, 1)
        }
      }

but I couldn't find anything like it in 5.46.0

**Comment by Nerbert1** [comment]
> Ah, right, the `gutters` option preserves what you put in there now, whereas it used to replace it with an updated value when necessary.

Didn't see this when I posted. So I just need to put CodeMirror-linenumbers in a gutter option regardless which version I use?
