### ISSUE TITLE
When i use CodeMirror.MergeView in react,i got diff_match_patch is not defined

### ISSUE THREAD

**Issue by mov1er** [codemirror/CodeMirror#5886]
here is code:
import CodeMirror from 'codemirror';
require('codemirror/lib/codemirror.css');
require('codemirror/addon/merge/merge');
require('codemirror/addon/merge/merge.css');
require('codemirror/mode/xml/xml');
require('codemirror/mode/javascript/javascript');

In React components:
let container = document.getElementById('comparison');
let val = this.state.value;
    CodeMirror.MergeView(container, {
      value: val,
      orig: '',
      lineNumbers: true,
      mode: 'xml',
      highlightDifferences: true
    });

then i go diff_match_patch is not defined

![WechatIMG3](https://user-images.githubusercontent.com/16483316/58067148-e3f50880-7bbe-11e9-8165-f1d8285606a6.png)

**Comment by mov1er** [comment]
package.json:{
"codemirror": "^5.46.0",
"react": "^16.6.3",
...
}

**Comment by marijnh** [comment]
Because, last time I checked, diff_match_patch (a 3rd-party library for diffing) wasn't properly packaged (and none of the properly packaged implementations come close to its speed), you have to manually load it.
