### ISSUE TITLE
More of a request then an issue - CISCO IOS

### ISSUE THREAD

**Issue by petterostergren** [codemirror/CodeMirror#5890]
Hey! 

Would be great if it's possible to add syntax highlighting for CISCO IOS. Added two examples from atom and sublime text!

https://atom.io/packages/language-cisco
https://network-tech.readthedocs.io/en/latest/

**Comment by marijnh** [comment]
We're not adding new highlighters to the core library anymore—the recommended way to get support for new languages is to write your mode and distribute it as a separate package (say `codemirror-mode-cisco`).
