### ISSUE TITLE
goGroupLeftCtrl  command is not working

### ISSUE THREAD

**Issue by jbharatrhodes** [codemirror/CodeMirror#5892]
I am trying to execute the command goGroupLeftCtrl in codemirror and it is not working,
Other commands like goLineUp is working.
`editor.execCommand('goGroupLeftCtrl');`
The cursor should move to left of the word. Do I need any special addons? Thank you

**Comment by marijnh** [comment]
The word "goGroupLeftCtrl" doesn't exist in this repository. I'm not sure what you are looking for, but the base library doesn't define it. Check `Object.keys(CodeMirror.commands)` for a list of defined commands.
