### ISSUE TITLE
ContextMenu-Event Target is different between chrome and Firefox/IE 

### ISSUE THREAD

**Issue by kishorethecoder** [codemirror/CodeMirror#5894]
I have used typo spell checker implementation from the below example 
[https://codepen.io/anon/pen/veGzWN?editors=1000](https://codepen.io/anon/pen/veGzWN?editors=1000) which seems to be working fine in all browsers which Codemirror version 5.18.0

When i tried with the latest version  on the contextmenu handler, Event target is showing as below

**Chrome**
![image](https://user-images.githubusercontent.com/3882978/58623380-7e55fa00-82eb-11e9-8015-74de6ebf84a5.png)

**FireFox**
![image](https://user-images.githubusercontent.com/3882978/58623486-b9f0c400-82eb-11e9-9076-3032c18ff8de.png)

Due to the above conflict , i'm not able to proceed further

**Comment by marijnh** [comment]
Try using `posAtCoords` with the coordinate data in the event. I doubt the library can do much about how the browser builds up the event.

**Comment by kishorethecoder** [comment]
Hi @marijnh , thanks for your suggestion . I have forgot to include the link for Non-working version .please find the link [here](https://codepen.io/kishore92/pen/arREyy). I have logged this issue because it was working fine in older version but it seems getting broken with contextmenu is segregated with textarea and Input

**Comment by hriverahdez** [comment]
@kishorethecoder I also ran into this issue with the exact implementation which I'm trying to reuse. Did you find a solution for this problem?

**Comment by dozed** [comment]
When you set `inputStyle` to `contenteditable` Firefox receives the correct event target.
