### ISSUE TITLE
What is outside option? 

### ISSUE THREAD

**Issue by yogeshmuthuraj** [codemirror/CodeMirror#5895]
"Pos {line: 0, ch: 42, sticky: "before", xRel: -86.53125, outside: true}"

When outside becomes true then the editor line becomes uneditable, how to prevent this?

**Comment by marijnh** [comment]
`posAtCoords` adds this when the coordinates queried lie outside of the line's bounding rectangle.

What you mean by the line becoming uneditable isn't clear to me. You're going to have to provide some more details.

**Comment by yogeshmuthuraj** [comment]
Got it. when outside: true the editor line does not focus but looks like that is expected. I fixed it but not encountering outside: true.

**Comment by yogeshmuthuraj** [comment]
Looks like this is something else,
when the Pos {line: 0, ch: 6, sticky: "before", xRel: -33.9375, outside: true} I am not able to focus on the line with the cursor.

**Comment by yogeshmuthuraj** [comment]
Is there any issue if we use 'focus()' and 'setCursor()' at the same time?

**Comment by marijnh** [comment]
No, you can do that.

**Comment by yogeshmuthuraj** [comment]
'Keyup' is working but Want to achieve the focus without 'Keyup'.

**Comment by yogeshmuthuraj** [comment]
Refreshing after Focussing works.
this.editorInstance.focus();
this.editorInstance.refresh();
