### ISSUE TITLE
Scheme mode indent issue

### ISSUE THREAD

**Issue by jcubic** [codemirror/CodeMirror#5897]
Here is the code that show wrong indent after class definition (define-class is macro that have proper S-Expression)

```lisp
(define-class Button (. preact 'Component)
              (constructor (lambda (self x)
                             (print x)))
              (render (lambda (self props state)
                        (with-tags (:button (:onclick (lambda (e)
                                                        (alert "foo"))))))))
;; wrong indent should indent to begning of the line
        (define h (. preact 'h))
        
        (define foo (new Button "hello"))
```

**Comment by marijnh** [comment]
If I go to https://codemirror.net/mode/scheme/, paste that code, and reindent it (ctrl-a shift-tab), I get the correct indentation.

**Comment by jcubic** [comment]
Sorry, I don't understand why I've got this wrong indent in first place. It seems to work fine. I was getting this indent when I've pressed enter after first S-Expression.
