### ISSUE TITLE
[groovy] [comment-fold] Comment folding doesn't work with groovy mode

### ISSUE THREAD

**Issue by lexek** [codemirror/CodeMirror#5906]
Repro with comparison to clike mode:
https://codesandbox.io/s/hopeful-field-y1mip

**Comment by crackhubpc6** [comment]
I am content writer with log time experence of this. My articals consist of  orignal human writen. of these type of **[softwares](https://crackhubpc.com)** of computers. For  more details about these type of software visit my link. **[Click Here](https://crackhubpc.com/x-mirage-crack/)**
