### ISSUE TITLE
[TypeScript] for in highlighted as type

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#5909]
```ts
export function getShell() {
    const config = shell[brackets.platform];
    const params: PlatformConfig = {};
    for (const key in config) {
        if (config.hasOwnProperty(key)) {
            params[key] = prefs.get(config[key]);
        }
    }
    return params;
}
```
`config` inside the for is highlighted as type when it shouldn't.

**Comment by ficristo** [comment]
The first issue mentioned here https://github.com/codemirror/CodeMirror/issues/5737 is not highlighted correctly anymore.
The `keyof JSX.IntrinsicElements` after `in` aren't highlighted as keyword and type.

**Comment by marijnh** [comment]
Ah, thanks for referencing that, that explains the original code.

**Comment by ficristo** [comment]
I copied and pasted the snipped on

**Comment by marijnh** [comment]
What's wrong? I'm seeing `JSX.IntrinsicElement` highlighted as a type.

**Comment by ficristo** [comment]
I mean the `[K in keyof JSX.IntrinsicElements]` part.

**Comment by marijnh** [comment]
Ah, sorry, it seems *I* was looking at an old cached version of the script. Try again with 9353e166

**Comment by ficristo** [comment]
Thank you!
