### ISSUE TITLE
Keymap problem

### ISSUE THREAD

**Issue by Longgererer** [codemirror/CodeMirror#5917]
I import `codemirror/keymap/sublime.js` and set `keymap: 'sublime'`. But when I pressed `CTRL+/`, the browser reported an error: **cm.toggleComment is not a function**
![截图未命名](https://user-images.githubusercontent.com/40834209/59976348-b5bb7c00-95f5-11e9-927b-86c350d48af6.jpg)

**Comment by marijnh** [comment]
Those only work if you also load `codemirror/addon/comment/comment.js`
