### ISSUE TITLE
cm.indentLine() removes all indentation on "Enter" or "Tab" key press

### ISSUE THREAD

**Issue by kiernfeeney** [codemirror/CodeMirror#5918]
Here's my code...

```
editor.on("keyup", function (cm, event){
		if(event.keyCode === 13){
			var prevLine = editor.getLine(editor.getDoc().getCursor().line - 1);
			if(prevLine.substr(prevLine.length - 1) === "{"){
				editor.indentLine(editor.getDoc().getCursor().line, "add");
			}
		}
});
```

and here's my problem...

On enter press the cursor is not tabbed forward and if there was any indentation on the line to begin with. It gets removed.

**Comment by marijnh** [comment]
I'm not sure, at a glance, what the problem is, but it is likely to exist in your code, so unless you can isolate the issue to something CodeMirror does, this bug tracker is not the place for it.
