### ISSUE TITLE
TypeScript type at position

### ISSUE THREAD

**Issue by goodmind** [codemirror/CodeMirror#5923]
Is it possible to implement something like Monaco type hints, but integrate it with lint addon, so warnings get stacked on top of type hint, not creating two different tooltips

I don't know locations of type hints in advance, only using API on mouseover

**Comment by marijnh** [comment]
The existing lint addon doesn't support on-demand linting—it assumes the lint information for the whole document is updated in one go. So you'd have to implement this outside of that addon.
