### ISSUE TITLE
Please include a README file that includes documentation on how to create our own parsers.

### ISSUE THREAD

**Issue by Windows81** [codemirror/CodeMirror#5925]
I'm planning to create a parser for the `.rbxl` and `.rbxml` file formats, which would require code for parsing both Lua and XML.  My problem is twofold:
1. People who are just learning about CodeMirror and would just like to implement syntax highlighting for their own language (like myself) will have a hard time trying to set a testing environment for their product.
2. I couldn't find any mention of what arguments, for example, the `token` method takes in and what it should return.

Thank you.

**Comment by marijnh** [comment]
There's a [section](https://codemirror.net/doc/manual.html#modeapi) on how modes work in the manual, and a large amount of example modes. The next version of the library will probably come with more detailed documentation, but for version 5 there are no plans to add extra docs.
