### ISSUE TITLE
feature request * add onSave option callback when initialized with FromTextArea

### ISSUE THREAD

**Issue by emergence75** [codemirror/CodeMirror#5932]
it would be nice to modify the save event which is attached to the form submit event

in function fromTextArea there is a function which is attached to the form
with 
`on(textarea.form, "submit", save);`

the function which i like to modify is this one

`function save() {textarea.value = cm.getValue();}`

it would be nice if you would change this function to

`function save() { if (typeof options.onSave == 'function') { options.onSave(cm) }; textarea.value = cm.getValue();}`

as workaround i currently detach the current event which gets added and attach a new one which calls cm.save defined in options.finishInit... the workarround works but i have about 30 lines of additional code the get the same feature...

**Comment by marijnh** [comment]
I'd prefer not to further complicate `fromTextArea`. I recommend constructing your editor directly with `new CodeMirror` and hooking up your own submit handlers.
