### ISSUE TITLE
Cannot combine HTMLHint and CSSLint?

### ISSUE THREAD

**Issue by jkupczak** [codemirror/CodeMirror#5939]
I'm trying to run both HTMLHint and CSSLint on a CodeMirror instance that has `mode:  "htmlmixed"`. Is this not supported or is there some extra work I need to do to get it activated? I've switched the mode to `css` and can confirm that the CSS Linting scripts are loaded properly. The Linter demos here (https://codemirror.net/demo/lint.html) don't show this capability but I was hoping it existed.

As an example, the HTMLHint website at https://htmlhint.io/ supports running CSSLint simultaneously. But they are using the Ace Code Editor and not CodeMirror.

My apologies if this isn't the right place to ask this question!

**Comment by marijnh** [comment]
This isn't supported—linters are expected to run on the entire file, so unless you can find some linter that works on HTML + the CSS embedded inside of it, it'll be hard to use the framework from addon/lint/lint.js to do what you want.
