### ISSUE TITLE
CodeLens like in VSCode

### ISSUE THREAD

**Issue by goodmind** [codemirror/CodeMirror#5940]
Is it possible to display text on top of every location that I want?
![image](https://user-images.githubusercontent.com/3275424/61158819-883a6200-a513-11e9-8fbf-4ae0cfc21778.png)

Maybe this is even doable in CSS

**Comment by marijnh** [comment]
Please use the [forum](https://discuss.codemirror.net/) for questions in the future.

You can use [`cursorCoords`](https://codemirror.net/doc/manual.html#cursorCoords) to find the screen coordinates of a given document position, and then absolutely position a DOM node at that position. Or you could use a [line widget](https://codemirror.net/doc/manual.html#addLineWidget).
