### ISSUE TITLE
setLine is not run

### ISSUE THREAD

**Issue by duanbaihong** [codemirror/CodeMirror#5942]
![image](https://user-images.githubusercontent.com/17972226/61206393-028e0080-a725-11e9-8474-476edac39e95.png)
Use setLine prompts when modifying a line ,"cm.setLine" command cannot run, prompt not function
![image](https://user-images.githubusercontent.com/17972226/61206516-539df480-a725-11e9-9cd0-a43c83a0e319.png)

**Comment by marijnh** [comment]
`setLine` does not exist in this library. I think it existed in version 3 and below, but that's a long time ago.
