### ISSUE TITLE
Bug in Text-marking methods or not ?

### ISSUE THREAD

**Issue by JulienLL** [codemirror/CodeMirror#5943]
Hy,
The Text-marking methods work or not ? The marks do not match the coordinate in table tab1.

```
var click1=0;
var tab1=["1","2","1","5","4","9","4","15","7","5","7","8"];
var lo1=tab1.length/4;
function modepasapas1(){
editor1.markText({line: tab1[click1*4] , ch: tab1[click1*4+1]}, {line: tab1[click1*4+2], ch: tab1[click1*4+3]}, {className:"aaaa"});
alert(tab1[click1*4]+","+tab1[click1*4+1]+","+ tab1[click1*4+2]+","+ tab1[click1*4+3]);
click1++;}
```

https://framapic.org/l4h0onuVwz04/5NSXtTTxbiIZ.png

**Comment by marijnh** [comment]
> The Text-marking methods work or not ?

Yeah, they work. But don't pass strings where numbers are expected.

**Comment by JulienLL** [comment]
Thank you for your quick and efficient response.
