### ISSUE TITLE
A problom on win10 and firefox

### ISSUE THREAD

**Issue by mhlx** [codemirror/CodeMirror#5945]
## problem
when I input Chinese with win10's input method  ,some strange behavior happened on top left corner

![screen_1](https://user-images.githubusercontent.com/15812754/61439694-90135f80-a974-11e9-96d1-9600d76afc5e.gif)

## os
Win 10

## firefox version
68.0

**Comment by mhlx** [comment]
I think that's filefox's problem
I have tested a single page as below and I got the same problem
```
<textarea style="width: 50px;">textarea1</textarea>
<textarea cols="0" rows="0">textarea2</textarea>
```

**Comment by marijnh** [comment]
Okay, thanks for reporting back. Going to close this issue then, since it's not CodeMirror-related.
