### ISSUE TITLE
Use of `rgb` with four arguments breaks use of CM in Rails/Sass

### ISSUE THREAD

**Issue by blerner** [codemirror/CodeMirror#5951]
https://github.com/codemirror/CodeMirror/blob/85482b0377911befe59c90fc7d714f30b59c98e7/theme/yonce.css#L27-L28 uses `rgb` with a fourth argument.  This is legal CSS syntax, but not yet legal in Sass.  This recently broke a rails app I was writing, when I updated my npm packages and that updated CM.

https://github.com/sass/sass/issues/2564 tracks adding support for four-argument `rgb` to sass, but it hasn't made its way into libsass and sassc yet...

**Comment by ReasorA** [comment]
Ran into this same issue using dynamic imports with Webpack. It errors when run through Webpack's sass-loader. Currently, we need to either edit this file or delete it with each npm i.

import(\`codemirror/theme/${editorTheme}.css\`)
