### ISSUE TITLE
Is it possible to render html content inside codemirror ?

### ISSUE THREAD

**Issue by Rajkiran0147** [codemirror/CodeMirror#5961]
In Zapier the edit template form has this field that uses codemirror to display the dynamic choice/option/value in custom UI. Zapier has managed to do it in some way that I am not able to understand. Can anyone help ?
![image](https://user-images.githubusercontent.com/16320704/62464790-29cb7100-b7ab-11e9-8a5b-725a1e9b85c7.png)

**Comment by Rajkiran0147** [comment]
I figured out that https://codemirror.net/doc/manual.html#markText is the way to achieve it. But I am trying to do the same using the `replaceWith` Option it doesn't reflect in the editor.

For instance I want the `{{dynamic.first_name}}` to be transformed into
 `<span><span>dynamic</span><span>first_name</span></span>`. For achieving this I did the following:

let node = '<span><span>dynamic</span><span>first_name</span></span>';
codemirror.markText(
      from,
      to,
      { replaceWith: node }
    );

But there is no change. Editor still displays {{dynamic.first_name}}

**Comment by marijnh** [comment]
`node` should be a DOM node, not the HTML string for one.
