### ISSUE TITLE
add support for virtual space

### ISSUE THREAD

**Issue by OlegYch** [codemirror/CodeMirror#5964]
many editors support this (eg visual studio, intellij)
here is a bit of explanation https://blogs.msdn.microsoft.com/zainnab/2010/02/28/understanding-virtual-space/
it is useful when you edit aligned content (and pretty much any code) as cursor does not jump around when you move between lines

**Comment by marijnh** [comment]
This is unlikely to be added to the core library (but it might be possible to write an addon that implements it).
