### ISSUE TITLE
Method setSpellCheck missing?

### ISSUE THREAD

**Issue by alper** [codemirror/CodeMirror#5965]
I'm fiddling around with getting spellcheck to work in CodeMirror.

I find this in the [User Manual](https://codemirror.net/1/manual.html):

> Can be changed with the setSpellCheck(on) method.

But I can't find that function anywhere in the latest code. Has it been removed?

**Comment by marijnh** [comment]
That's the user manual for CodeMirror version 1 (which has been obsolete for 8 years now). Try [this one](https://codemirror.net/doc/manual.html).

**Comment by alper** [comment]
Thanks for the reply! We were frantically googling around and ended on that page without realizing it.
