### ISSUE TITLE
Impossible to move cursor into some regions in some code-folding + wrapping cases

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5966]
1. open https://codemirror.net/demo/folding.html
2. paste the following into the HTML field:
```html
=======================================================ooooo<foobar>
  
  
</foobar>
```
3. click the triangle in the gutter to collapse the tag
4. click anywhere within the `</foobar>`

expected:
cursor/selection get created as normal

actual:
cursor gets placed into the collapsed region

**Comment by marijnh** [comment]
Attached patch should help
