### ISSUE TITLE
GetTokenAt does not return the complete token when it starts with 'a'

### ISSUE THREAD

**Issue by mistermboy** [codemirror/CodeMirror#5968]
For example:

If you are typing 's' and you call getTokenAt()  codemirror returns 's', and if you add another letter to the token like 'c'  ('sc') and call getTokenAt() codemirror return 'sc'. 

Ok, but if you do the same with any other word that starts with 'a', getTokenAt() only returns the last letter of the word. Example:

You are  typing 'a' and call getTokenAt() -> returns 'a'
Then you add another letter like 'b'  ('ab') and call getTokenAt() -> returns 'b' instead of 'ab'

**Comment by marijnh** [comment]
Which mode is this with? And did you disable the `flattenSpans` option?

**Comment by mistermboy** [comment]
Sorry it was my bad. I defined a token 'a' so that the codemirror returns me always that token
