### ISSUE TITLE
Issue in Codemirror with multiple readOnly blocks using markText

### ISSUE THREAD

**Issue by johnblesswin** [codemirror/CodeMirror#5969]
Hi.,

I am John Blesswin., 

I am trying to add multiple markText blocks with readOnly option in the code editor. but, when Enter Key pressed between the two blocks, other codes are adding in markText blocks., that is  inclusiveRight and inclusiveLeft is not working correctly !!

When i **Enter key** pressed in Line A., Line B added in the readOnly blocks.,
Like, When i press **Backspace** in Line D, Line D added in the readOnly blocks.,

Kindly see the images and reply.

<img width="1082" alt="Screenshot 2019-08-11 at 7 33 37 PM" src="https://user-images.githubusercontent.com/22275776/62834812-13238f00-bc6f-11e9-85bf-785923ae2783.png">

<img width="321" alt="Screenshot 2019-08-11 at 7 44 34 PM" src="https://user-images.githubusercontent.com/22275776/62834947-7feb5900-bc70-11e9-8ecb-a2bebfa185d1.png">

**Comment by marijnh** [comment]
Why are you passing negative numbers to `markText`? Also, `readOnly: "nocursor"` is not a thing in this context.

**Comment by johnblesswin** [comment]
Thank you for replying...

I have tried to make the Line 1 as read only and the line number 3 got effected. When i use line -1 then the first line gets readonly...

also I understand "nocursor" is wrong from my end...


Here is what i would like to have in react js


I need 
a part of code (Block A) to be readonly 
a part of code (Block B) to be Editable
a part of code (Block C) to be readonly
a part of code (Block D) to be Editable

---- issue here is-----
when I press 'enter' key in Block B, the code is moved downwards and the last line of Block C becomes editable.... 
Can you help me to write code for the blocks

**Comment by marijnh** [comment]
> I have tried to make the Line 1 as read only and the line number 3 got effected. 

That's not really something the library does, so it suggests some confusion on your part.

I'm sorry, but I don't have time to solve problems in arbitrary code that uses this library. Going to close this, since there's no real indication that it's about a library bug.
