### ISSUE TITLE
Bug: cm.setValue("") over inclusive mark results in broken editor

### ISSUE THREAD

**Issue by thomasjm** [codemirror/CodeMirror#5974]
This one is a slightly weird edge case. Here's how to trigger it:

1. Create a document with some content, and set a mark over the entire document with `inclusiveLeft` and `inclusiveRight` set to `true`.
2. Call `cm.setValue("")`
3. The editor will become empty, but it is now in a broken state where you can't type anything.

Here is a [pen](https://codepen.io/thomasjm/pen/BaBzpKm?editors=0010) demonstrating this. Note that the `setValue` call happens in a timeout after 5 seconds.

**Comment by thomasjm** [comment]
Thanks!

**Comment by thomasjm** [comment]
@marijnh I just tested with `replaceRange` instead of `setValue` and found the issue still exists in that case. Here's an updated pen:

https://codepen.io/thomasjm/pen/QWLEmoY?editors=0010

Should I open a new issue for this one?

**Comment by marijnh** [comment]
Good point. Attached patch moves the fix to a more appropriate place.

**Comment by thomasjm** [comment]
Looks good, thanks again!
