### ISSUE TITLE
VB.Net support

### ISSUE THREAD

**Issue by LuckyTil** [codemirror/CodeMirror#5977]
Please, replace into vb.js
line
    var stringPrefixes = '"';
to
    var stringPrefixes = '"@$';

for support VB.Net features - raw string and interpolated string.
Thanx!

**Comment by marijnh** [comment]
That doesn't look like it'll work—`stringPrefixes` is given to `stream.match`, which will look for the literal sequence `"@$` in the code.

(A working, well-tested pull request for this would be accepted.)
