### ISSUE TITLE
Cannot pass options to TernServer prototype functions.

### ISSUE THREAD

**Issue by cjkindel** [codemirror/CodeMirror#5978]
Using TernServer.complete as an example, it isn't possible to set completeSingle when calling complete(). Complete could take an options object that would be passed to cm.showHint, which already takes options.

https://github.com/codemirror/CodeMirror/blob/f9c0e370ec4ddace08bb799965b3f46f9536a553/addon/tern/tern.js#L106

**Comment by marijnh** [comment]
Doesn't `editor.setOption("hintOptions", {completeSingle: true})` cover this?

**Comment by cjkindel** [comment]
Was not aware of that workaround, this addresses my concern/issue
