### ISSUE TITLE
Feature request: Progress OpenEdge ABL/4GL 

### ISSUE THREAD

**Issue by timhutchens** [codemirror/CodeMirror#5979]
We use Bitbucket to manage our Git repositories and would like to have syntax highlighting for the Progress OpenEdge 4GL/ABL language available. Since Bitbucket uses CodeMirror, I am requesting this language to be added to the CodeMirror repository. Is this something the CodeMirror team is willing to take on, or can you point me in the right direction to add this myself and submit a pull request?

Thank you!
Tim

**Comment by schanzer** [comment]
I don’t think new languages are being accepted into the main repo - all new language modes are going into their own packages instead. If you’re up for writing your own mode, I’d suggested looking at some of the existing modes to get a feel for how this works. Start simple with something like Scheme, then check out the JS mode to see all the bells and whistles.

**Comment by marijnh** [comment]
Indeed—keeping every language in the main distribution isn't sustainable anymore, so new languages should be implemented and maintained as separate npm packages.
