### ISSUE TITLE
Code Mirror pushing to Prism stripping out closing HTML brackets, "</" are missing

### ISSUE THREAD

**Issue by Dcmorris101** [codemirror/CodeMirror#5983]
**Description**
I am using code mirror to push written code into a prism box for easy writing and easy viewing. I am getting the innerHTML value and passing it straight to prism for styling. When I write a block of HTML specifically (all other languages work), the output of the final product strips out the closing bracket and slash and puts it into an HTML comment as a closing span tag.

The image below shows an example. The left is the output while the right is what the dev tools is showing.

![prism issue](https://user-images.githubusercontent.com/37924444/63631438-7b159600-c5dc-11e9-9bf0-351bf79442bf.PNG)

The code input into Code Mirror is the following:
```
<script type="text/plain">
<div class="singleitem" data-repeating-id="repeating-content">
  <div class="testing">
      <section id="test-id">
        <p>Some things work and some don't.</p>
      </section>
  </div>
</div>
</script>

```

**Comment by marijnh** [comment]
This doesn't sound like it is related to CodeMirror.
