### ISSUE TITLE
Editor is bugged if created in a hidden div

### ISSUE THREAD

**Issue by CodeMyst** [codemirror/CodeMirror#5985]
html:

```html
<div id="container">
  <textarea id="editor"></textarea>  
</div>
```

And if you first set the style of the `container` to `display: none;`, create the editor using `fromTextArea` and then set the display back to `block` the editor is a bit bugged. It only "activates" when it gains focus, the line numbers are over the code (until you create 10 lines), if the code is set from javascript it's invisible until it gains focus, and maybe some other stuff.

js:

```js
document.getElementById ("container").style.display = "none";

CodeMirror.fromTextArea (document.getElementById ("editor"),
{
  lineNumbers: true,
  indentUnit: 4,
  mode: "text/plain",
  tabSize: 4,
  lineWrapping: true
});

document.getElementById ("container").style.display = "block";
```

Example: https://jsfiddle.net/rv01p7q4/

**Comment by marijnh** [comment]
You need to call `refesh()` on the editor instance after unhiding it. (Unfortunately, browsers make it really hard to get notified of this, so the library can't really do it on its own in a lightweight way.)

**Comment by CodeMyst** [comment]
Thanks, that fixed it! :D

**Comment by richytong** [comment]
this helped me too! slightly different use case; I was appending a group of elements with a reference to the editor instance to an empty div
