### ISSUE TITLE
Codemirror onChange messes up undo/redo history when emiting an event

### ISSUE THREAD

**Issue by benkonz** [codemirror/CodeMirror#5986]
```typescript
  codeChange = new EventEmitter<string>();

    this.editor.on('change', (editor: CodeMirror.Editor, _change) => {
      this.codeChange.emit(editor.getValue());
    });
```

I'm using CodeMirror with Angular and emiting an event whenever the text inside the editor changes. Something is with the `emit` function is causing the undo/redo buttons to get messed up. Now I have to call the undo/redo functions twice and character-by-character, instead of the normal behavior.

**Comment by marijnh** [comment]
> Something is with the emit function

Since I don't have the `emit` function, it's hard for me to diagnose this. Just calling `getValue` on `change` events doesn't produce the effect you describe. Can you create a _minimal_ script that demonstrates the problem?

**Comment by benkonz** [comment]
Example repo created: https://github.com/benkonz/codemirror-history-example

**Comment by benkonz** [comment]
Nevermind, I figured out what the problem was. When I setup the two way data-binding with the codemirror editor text, the editor text was getting set to the old text every time a change was made to the editor in addition to the new text added, so the undo stack had a duplicate copy of the text after every change. I just removed the two-way data binding with the editor code and it is working a lot better

**Comment by HenonoaH** [comment]
> Example repo created: https://github.com/benkonz/codemirror-history-example

@benkonz I'm also working Codemirror with Angular and facing a similar issue. Could please invite/share this repo with me?

**Comment by benkonz** [comment]
@HenonoaH Sorry! I deleted the repository when I figured out the issue... It's been a while since I encountered this issue, and I don't quite remember specifically what I did to fix it (outside the comment I left). I can take another look at the commit I made to fix the issue this weekend.
