### ISSUE TITLE
Incorrect syntax highlighting when using HTML comments in Javascript section

### ISSUE THREAD

**Issue by TimvdLippe** [codemirror/CodeMirror#5988]
Given the following snippet:

```js
console.log("This is executed (A)"); <!-- This is a line comment.
--> This is also a line comment. Even if I add this: /* 
console.log("This is executed (B)"); 
```

Code Mirror renders the following:

![image](https://user-images.githubusercontent.com/5948271/64031116-b285c480-cb3f-11e9-902b-56b7e149bffc.png)

The expected highlighting would be that past the `<!--` and the whole second line are green, while the third line is styled as the first `console.log`

You can reproduce this issue on https://codemirror.net/demo/theme.html and pasting the above snippet.

This issue was originally reported on https://bugs.chromium.org/p/chromium/issues/detail?id=920367 which also links to the ECMAScript standard: https://www.ecma-international.org/ecma-262/#sec-html-like-comments

> Similar to a MultiLineComment that contains a line terminator code point, a SingleLineHTMLCloseComment is considered to be a LineTerminator for purposes of parsing by the syntactic grammar.

**Comment by marijnh** [comment]
I'm kind of wondering if the person reporting that ran into a real problem or was intentionally trying out corner cases, since it's been really long since I've seen such comments in actual source code, but okay, attached patch adds support.

**Comment by TimvdLippe** [comment]
Thank you for the quick resolution!
