### ISSUE TITLE
dragDrop option doesn't work

### ISSUE THREAD

**Issue by hqzh** [codemirror/CodeMirror#5989]
Drag and drop can't  zoom in and out

**Comment by marijnh** [comment]
I've never zoomed in or out with drag and drop. Please consider actually describing your issue in enough detail for us to know what you mean.

**Comment by hqzh** [comment]
I thought this API has the effect of <textarea/>resize, so does it support resizing?

**Comment by marijnh** [comment]
No, it relates to dragging and dropping text.

**Comment by hqzh** [comment]
@marijnh Does any API support Textarea the future support
