### ISSUE TITLE
垃圾，缺少CodeMirror.js文件。害老子浪费半天时间

### ISSUE THREAD

**Issue by sifanlook** [codemirror/CodeMirror#5990]
垃圾

**Comment by sifanlook** [comment]
你引尼玛呢，这个文件被你吃了？
![image](https://user-images.githubusercontent.com/21136881/64168070-55f71200-ce7d-11e9-851a-0f43981365c4.png)

**Comment by sifanlook** [comment]
![image](https://user-images.githubusercontent.com/21136881/64168305-d1f15a00-ce7d-11e9-8516-ac67c403f7fc.png)

**Comment by marijnh** [comment]
Going by Google translate, this was another user Very Angry that the git repository doesn't include the build artifacts. As such, closing.
