### ISSUE TITLE
Merge addon from a CodeMirror initialized in a <textarea> tag

### ISSUE THREAD

**Issue by Dcmorris101** [codemirror/CodeMirror#5996]
So my custom site initializes CoderMirror instances inside textareas due to some issues with the browser changing contents inside divs when it treated them like any other DOM element. If a CodeMirror instance is created within a <textarea> tag, is it still possible to use the merge addon? Or does a merge require a div? If I leave it as a textarea, the merge.js doesn't load and i get a "CodeMirror.MergeView is not a function" in the console. If I change it to a div, the merge.js script won't load due to how the site is currently built. Is there any way around this?

Example of a snippet of the code below: (values are the same for testing purposes)

```
var tag="textarea";

$(".ModuleEditorSection").html("<"+tag+" id='ModuleEditor_TextArea' style='width:100%;height:100%;'></"+tag+">");

        var value, orig1, orig2, dv, panes = 2, highlight = true, connect = "align", collapse = false;
        function initUI() {
          value = data;
          orig1 = value;
          orig2 = value;
          
          
          if (value == null) return;
          var target = $(".ModuleEditorSection #ModuleEditor_TextArea");
          target.innerHTML = "";
          dv = CodeMirror.MergeView(target, {
            value: value,
            origLeft: panes == 3 ? orig1 : null,
            orig: orig2,
            lineNumbers: true,
            mode: "text/html",
            highlightDifferences: highlight,
            connect: connect,
            collapseIdentical: collapse
          });
        }
        initUI();

        function toggleDifferences() {
          dv.setShowDifferences(highlight = !highlight);
        }

        function mergeViewHeight(mergeView) {
          function editorHeight(editor) {
            if (!editor) return 0;
            return editor.getScrollInfo().height;
          }
          return Math.max(editorHeight(mergeView.leftOriginal()),
                          editorHeight(mergeView.editor()),
                          editorHeight(mergeView.rightOriginal()));
        }
```

**Comment by marijnh** [comment]
This doesn't belong on the bug tracker—it's a question about your code, not an issue with CodeMirror.

I can't really make heads or tails of the question, so I'd suggest you take a step back, reconsider what you're doing, and if you have a more precise question, try asking on [the forum](https://discuss.codemirror.net).
