### ISSUE TITLE
CodeMirror horizontal scrollbar not accounting for bookmark width

### ISSUE THREAD

**Issue by darkwing** [codemirror/CodeMirror#5997]
The Firefox DevTools Debugger now proudly boasts an inline preview feature to show variable values while paused -- a really awesome feature!  We've run into an interesting issue with the CodeMirror horizontal scrollbar when trying to use `setBookmark`:

<img width="1092" alt="CutOffPreview" src="https://user-images.githubusercontent.com/46655/64552975-18233f00-d2fe-11e9-819b-7323f44e636d.png">

Despite the inline preview bookmark block/text [starting within the viewport](https://github.com/codemirror/codemirror.next/issues/39#issue-365445555), the horizontal scrollbar never grows to accommodate the entire preview element.  In doing some investigating of my own, CodeMirror's `updateScrollbars` function is never called after injecting the previews into the line.

Since we're using the CodeMirror `setBookmark` API to inject the bookmark, it seems reasonable to assume that the scrollbar should be aware that the length of the line that the bookmark was injected into has changed an thus kick off a resize/scrollbar check.

**Comment by jasonLaster** [comment]
Here are some links to the implementation

- [InlinePreview](https://searchfox.org/mozilla-central/source/devtools/client/debugger/src/components/Editor/InlinePreview.js)
- [InlinePreviewRow](https://searchfox.org/mozilla-central/source/devtools/client/debugger/src/components/Editor/InlinePreviewRow.js#87-113)
  - includes the element the preview component is inject in
  - includes the left attribute, which determines the component's position

**Comment by darkwing** [comment]
Thank you for adding additional info @jasonLaster!  The above is the current implementation which uses a line widget and a calculated `left` style along with a negative top margin; the reason I'm trying to move to a `setBookmark` implementation is to avoid the costly perf hit of numerous `left` calculations by simply add the bookmark inline, and allowing CodeMirror to do the scrollbar calculation.

You can get an idea of what I'm trying to do here:  https://phabricator.services.mozilla.com/D44532

The original "bug" remains the same, in that I would expect that CodeMirror would see a bookmark and adjust the horizontal scrollbar accordingly.

**Comment by marijnh** [comment]
I'm not seeing this happen when I use `addBookmark` to add a widget at the end of a line that would introduce or extend the horizontal scrollbar—the editor seems to immediately adjust the scrollbar. Looking over the patch in phabricator, I can't figure out what you might be doing differently.

Are you using the current version? If so, can you set up a small script that reproduces the issue?

**Comment by darkwing** [comment]
Thank you for the response @marijnh.  The issue is really interesting to try to nail down. As for a test script, I'll see what I can do; since we're using React, it may be difficult to put together a simple script.

My first thoughts were timing issues.  I see that `endOperation_R2` appears to be the sizer shifting, so I've been trying to trigger that function in a variety of ways, including fake operations, manually setting `cm.display.maxLineChanged`, `cm.refresh()` or simply setting that conditional to `if(true)`but the scroll scroller size remains the same.

Is there a hack way to trigger that scroll size change?  The only real CSS on the resulting bookmark is `display: inline-block` which shouldn't be doing anything weird to effect scrollbars.

**Comment by jasonLaster** [comment]
We're currently on `5.40.0.` which is a couple of versions back

@darkwing it might be worth trying to upgrade [docs](https://searchfox.org/mozilla-central/source/devtools/client/shared/sourceeditor/README#6-23).

**Comment by marijnh** [comment]
5.40.0 isn't that old, I don't remember anything related to this changing, so upgrading might not do a lot.

Is the widget being initialized asynchronously by React? It it doesn't have its final shape/size when it's inserted that might cause this.

**Comment by jasonLaster** [comment]
this seems likely and definitely a good place to investigate

**Comment by darkwing** [comment]
Consider the following reduced demo I've created:  https://jsfiddle.net/4eLjmbwr/6/

In this demo I continually inject a bookmark with text and no explicit width.  A few notes:

1.  While the scrollbar does move, the marker quickly starts being cut off on the right . That partially supports my feeling that the bookmark width isn't accurately portrayed in the scrollbar

2.  Note that the `.CodeMirror-sizer` doesn't appear to ever move, which supports my feeling that the debug line (the blue-outlined element in my original image) never stretches to full width once a bookmark is introduced.

I've studied the Chrome DevTools source code and they also use `addLineWidget` with a negative top margin and calculated `left` CSS value to align the previews properly and force the editor to scroll far enough that the full preview is seen.  They also have the issue triggered by the `.CodeMirror-sizer` not moving, which makes their blue debug line not stretch to full scroll width.

**Comment by marijnh** [comment]
That test is running CodeMirror 5.4 for some reason. It seems to get a lot better with 5.49.

**Comment by darkwing** [comment]
Thank you for checking it out!  Updating to 5.8 shows no improvement, unfortunately; https://jsfiddle.net/px9rsh52/1/

**Comment by marijnh** [comment]
I really have no idea why you upgraded to 5.8 when I mentioned 5.49 in my comment.

**Comment by darkwing** [comment]
My apologies @marijnh, that does appear to work much better.  Closing this issue -- thank you!
