### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by claviska** [codemirror/CodeMirror#60]
While this isn't exactly an issue, I figured this might be the best place to bring your attention to support for iOS devices (and possibly Android, Windows 7, etc.).  Obviously this wasn't possible with CodeMirror 1 and its use of an IFRAME and contentEditable, but with very little modification to codemirror.js I was able to get a functional version on my iPad and iPhone.  That said, I think the future of CodeMirror on mobile devices is very promising, but there are a couple issues I immediately noticed that may prove to be very simple to solve.

First, for devices with soft keyboards the hidden textarea needs to gain focus in order for the keyboard to appear on-screen.  I was able to work around this by making the text area visible and giving it focus.  After it's initial focus, the keyboard responded rather naturally (but not perfectly) to focusing and blurring on CodeMirror itself.  Further testing is needed, but I think it would be possible to make the textarea "visible" and position it absolutely off the screen to accommodate this.

The other problem I noticed is that, when the textarea receives input and is out of the viewport, mobile Safari centers the display on the textarea.  This seems like it would be easy to fix by setting the vertical position of the hidden textarea to the same line the "cursor" is on.

Let me know what you think, Marijn.  And congrats and great work on CodeMirror 2!

**Comment by marijnh** [comment]
This has landed in 5.0.
