### ISSUE TITLE
Writing a unit test for CodeMirror

### ISSUE THREAD

**Issue by oliverwatkins** [codemirror/CodeMirror#6000]
I would like to write an extremely simple test for CodeMirror.

This is what I wrote : 

```
    test(' codemirror ', () => {

        let text = document.createElement("div");

        let settings = {}

        codemirror(text, { ...settings, value: '' });
    });
```

Unfortunately I get this error  : 

> TypeError: document.body.createTextRange is not a function
> 
>     at range (A:\frontend\node_modules\codemirror\lib\codemirror.js:94:25)
>     at hasBadBidiRects (A:\frontend\node_modules\codemirror\lib\codemirror.js:1343:12)
>     at buildLineContent (A:\frontend\node_modules\codemirror\lib\codemirror.js:1838:9)
>     at updateExternalMeasurement (A:\frontend\node_modules\codemirror\lib\codemirror.js:2442:28)

What do I need to do to get this running?

**Comment by marijnh** [comment]
In which context are you running this? It looks like the old-IE fallback for creating ranges is running, but that should only happen when `document.createRange` doesn't exist, which shouldn't be the case on any reasonably current browser.

**Comment by oliverwatkins** [comment]
Of course we want to use it in a non-browser process. We want to unit test our code.

**Comment by marijnh** [comment]
Right. As I mentioned, this library doesn't work outside the browser.
