### ISSUE TITLE
How select in hint  elements through mouse click

### ISSUE THREAD

**Issue by Tonypz** [codemirror/CodeMirror#6001]
Hi!! I can select an item using buttons (arrows), I would like to be able to select with a mouse click
![image](https://user-images.githubusercontent.com/23166800/64693845-e8606c80-d4a0-11e9-9a9c-146efc987d73.png)

and when pressed, the hint closes. thank you !

**Comment by marijnh** [comment]
Try the `completeOnSingleClick` hint option.
