### ISSUE TITLE
Cant get text/html or javascript to show styles

### ISSUE THREAD

**Issue by pkasson** [codemirror/CodeMirror#6007]
I have looked at various examples but can not get those two types to show any formatting:

`              editor = CodeMirror.fromTextArea(document.getElementById("sourceCode"), 
              {
               mode             : codeMode,
               lineNumbers      : true,
               extraKeys        : { "Ctrl-Space": "autocomplete" },
               styleSelectedText: true,
               styleActiveLine  : true,
               foldGutter       : true,
               theme            : defaultTheme,
               gutters          : ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]               
               });`

I replace codeMode like:

`              if(codeType == "Javascript")
              {
               codeMode = "javascript";
              }
              if(codeType == "Text" || codeType == "HTML")
              {
               codeMode = "text/html";
              }
              if(codeType == "Swift")
              {
                codeMode = "swift";
              }
              if(codeType == "SQL")
              {
                codeMode = "sql";
              }
              if(codeType == "Stencil" || codeType == "Template")
              {
                codeMode = "velocity";
              }`

**Comment by marijnh** [comment]
`"HTML"` isn't a defined mode. You'll want to look at the [mode demo pages](https://codemirror.net/mode/htmlmixed/) to see which mime types the modes define. (In this case, I guess you want `"text/html"`)

**Comment by pkasson** [comment]
Yep, that did the trick - thanks !
