### ISSUE TITLE
tab indention works incorrectly

### ISSUE THREAD

**Issue by xdandyx** [codemirror/CodeMirror#6008]
1. if a line is blank,tab indention works normally.
1. if indent after text like `some text xx`,the length of this tab will be `tabSize-xx.length`
1. if there is a selection on text,the tab indention will be insert at the front of this line

please fix the indention problem!

**Comment by marijnh** [comment]
This is entirely intentional. See [the docs](https://codemirror.net/doc/manual.html#command_defaultTab).
