### ISSUE TITLE
[sublime] cmd+d/ctrl+d should stop moving the main selection after it's added all instances

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#6024]
repro:

1. open https://codemirror.net/demo/sublime.html
2. put cursor on any of the instances of `Shift'
3. press cmd+d repeatedly

expected:
all the instances of `Shift` will be selected, and then the viewport will stop moving. this is the behavior of sublime (as well as VSCode & IntelliJ). not sure if it always was, but that is the behavior now.

actual:
all instances of `Shift` do get selected, but then the viewport keeps moving, because very time the command gets executed, the primary cursor moves.

**Comment by marijnh** [comment]
There was code trying to implement this, but it was broken. Attached patch should help.
