### ISSUE TITLE
getLineTokens breaks each individual characters into token in markdown gfm mode

### ISSUE THREAD

**Issue by nmanandhar** [codemirror/CodeMirror#6035]
In markdown gfm mode each individual character is treated as a token, resulting in large number of tokens. The same behaviour does not exist in normal markdown mode
![image](https://user-images.githubusercontent.com/9746042/67200457-8db51b80-f423-11e9-828d-3162cc14484e.png)

**Comment by marijnh** [comment]
That's how that mode is implemented. It's not very efficient, but it works. The code was contributed and I'm not going to rewrite it, so unless you fix it yourself you'll have to work with this.
