### ISSUE TITLE
Stacking contexts make it impossible to control TextMarker z-index relative to content

### ISSUE THREAD

**Issue by thomasjm** [codemirror/CodeMirror#6044]
When making a collaborative text editor, one might want to show the position of other users' cursors. In the past I've used TextMarkers for this, and it's worked fine. Here's an example of a green cursor representing another user:

![image](https://user-images.githubusercontent.com/1634990/67666309-caec4280-f928-11e9-850a-5f2b3b194023.png)

Suppose you want to augment the cursor with a label saying who the user is. The goal is to look something like this:

![image](https://user-images.githubusercontent.com/1634990/67666433-02f38580-f929-11e9-996d-58b652c505cc.png)

But what really happens in CodeMirror today is the following:

![image](https://user-images.githubusercontent.com/1634990/67666482-1c94cd00-f929-11e9-9b92-f33f2c13c2c0.png)

I made a pen where you can see this [here](https://codepen.io/thomasjm/pen/gOOxOGa). The basic problem is that no matter what you do with the z-index of the `TextMarker`, it will never appear above the content, because the `.CodeMirror-line` object forms a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). 

This is unfortunate because this appears to be the only stacking context that appears in the DOM tree generated by CodeMirror. If it didn't exist, then a CodeMirror user could control the Z-positioning of everything (widgets, TextMarkers using absolute positioning tricks, etc) just by styling them. 

The cause of the stacking context is [here](https://github.com/codemirror/CodeMirror/blob/9e917beec874829c28bc1918a9afd0d71a7d7957/lib/codemirror.css#L254) where the `position: relative` style is set. Naively removing it breaks other things (for example, text selection totally covers the text), but it seems like the problems could be patched up.

Would this make sense as a PR? Or is there perhaps some easier way to get this effect? Thanks!

**Comment by marijnh** [comment]
> but it seems like the problems could be patched up.

Since gutter elements are positioned relative to their parent line, I don't think changing this is going to be easy. In any case, it'd create various user-observable changes in behavior that will without a doubt break someone else's code, so I don't think this is a viable direction.

You could try overlaying the cursors on the editor with absolutely positioning. This has the advantage that it won't mess with the editor's layout (such cursors are likely to introduce new line breaking positions, if you have line wrapping turned on), but the disadvantage that it is harder to keep the position in sync with the content during scrolling and changes.

**Comment by thomasjm** [comment]
> You could try overlaying the cursors on the editor with absolutely positioning.

I experimented with this a little bit. I tried using a `TextMarker` for the vertical line and then using [popper.js](https://popper.js.org) to attach the label to the vertical line. But as you said, it's tricky to always keep the position in sync.

What I'd really like is if CodeMirror could expose its cursor-drawing tools. CodeMirror already knows how to draw absolutely positioned cursors and make them behave nicely with scrolling etc. If I could draw a cursor and have control over the DOM node it uses then that would solve the problem nicely. Do you think this would be a reasonable direction?

**Comment by thomasjm** [comment]
A possible interface idea: what if the `setBookmark` function had an optional boolean `absolute` option that caused the bookmark to be drawn with absolute positioning?

**Comment by marijnh** [comment]
That would just push the complexity of keeping positioned elements in place into the core library. I don't think it's an important enough feature to justify that.

**Comment by thomasjm** [comment]
But, doesn't the core library already know how to keep positioned elements in place? I was hoping there would be a way to leverage the same code that already draws cursors.

**Comment by marijnh** [comment]
Sort of, but that layer is only used for selections and would probably be a bad fit for such cursors anyway, since the label text wouldn't be able to stick out of the editor. I'm not too keen on adding new, nontrivial features to this version at this point.

**Comment by thomasjm** [comment]
Okay, thanks for the advice. I had a go with managing absolutely positioned cursors myself and it wasn't actually too bad. Here's what I did:

1) Call `setBookmark` with an invisible, zero-width span at the desired location
2) Make a cursor element (vertical line + label) and attach it to the bookmark node using Popper.js
3) Call the Popper.js `update` method on the CodeMirror "update" and "scroll" events.

I'll close this now.
