### ISSUE TITLE
Height of 100% doesn't work with flex-grow parent on Safari/macOS.

### ISSUE THREAD

**Issue by kssreeram** [codemirror/CodeMirror#6047]
Hello CodeMirror Team.
Thanks for an amazing open-source project! ❤️

Bug details:

This bug was tested with CodeMirror versions 5.48 and 5.49.
The parent of the editor is sized with `flex-grow`.
The editor size is set with `editor.setSize("100%", "100%");`.

The editor doesn't fill the parent on Safari (v13.0.3, macOS 10.14.6).
It works fine on Firefox and Chrome.

Here's a link to a reproduction of the problem:
https://jsfiddle.net/f2xwdkro/

**Comment by marijnh** [comment]
Does Safari do the same when you put a `<div style="width: 100%; height: 100%; border: 1px solid red"></div>` element instead of a CodeMirror instance? If so, this might be a Safari bug, not something that CodeMirror does.

**Comment by kssreeram** [comment]
I tried that, and you're right.
The problem does occur even with just a simple div.
Looks like a bug in Safari.

Thanks.

**Comment by kssreeram** [comment]
Here's some more information about the bug:
https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

Apparently, the bug was present in both Safari and Chrome, and it was fixed in Chrome alone.
https://bugs.chromium.org/p/chromium/issues/detail?id=426898

The suggested workaround is to use flexbox to size the child div. And that works with a simple div. When I try doing that with CodeMirror, the last line or two is outside the scroll region and is being cut off.

Is it possible to size CodeMirror editors with flexbox?

**Comment by marijnh** [comment]
No, the CodeMirror wrapper div expects to be display: block. You'll probably need to add another intermediate wrapper element to work around this.

Going to close this, since I don't know of a credible way to work around the Safari bug on the CodeMirror side.

**Comment by kssreeram** [comment]
Btw, the intermediate wrapper idea worked well. Thanks.

```
#wrapper2 { position: absolute; top: 0; left: 0; bottom: 0; right: 0; }
```
I added wrapper2 as child of the flexbox element and CodeMirror as a child of wrapper2.
