### ISSUE TITLE
[continuecomment] block comment continuation fires within a line comment

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#6048]
repro:
1. open an editor in some mode that c-style line and block comments, with block comment continuation and no line comment continuation
2. type the line `// The order of operations is ()/*+-`
3. press enter at the end of the line

expected:
a new line should be started and that's it

actual:
a new line is started, but the `/*` is recognized as a block comment start sequence and so a `*` is inserted and aligned to be under the existing `*`

**Comment by marijnh** [comment]
Trying this in the [javascript mode demo](https://codemirror.net/mode/javascript/), which has continuecomment enable and uses c-style comments, I'm not seeing this happen.

**Comment by jdbruxelles** [comment]
Hi, I can confirm this issue with javascript mode and continuecomment enabled. But, it also happens even on the html and htmlmixed mode. The editor that I used uses the version 5.45.0 of CodeMirror.

*javascript mode*
![code](https://user-images.githubusercontent.com/18559798/68070328-46a51f80-fd6d-11e9-8225-f1634e18ee43.png)

*html mode & html mixed*
![code](https://user-images.githubusercontent.com/18559798/68070441-8ae4ef80-fd6e-11e9-97d6-4f432d778ba9.png)

**Comment by marijnh** [comment]
> Hi, I can confirm this issue with javascript mode and continuecomment enabled.

Can you? On the mode demo I linked? (I can't.) If it requires a different setup, please let me know which one.

**Comment by jdbruxelles** [comment]
[Editor used](https://code.wetrafa.xyz/) - I tried again. When the `continueComments` option is set to `true`, the issue occurs. Then, when I set it to `false`, the cursor simply goes in the start of a new line.

I noticed that the value of `editor.getOption("continueComments")` in the [Demo](https://codemirror.net/mode/javascript/) is `"Enter"` while in my editor, it's `true`.

And I found this in the Demo editor:
![codemirror net_mode_javascript_](https://user-images.githubusercontent.com/18559798/68149620-7d7e5f80-ff3e-11e9-9413-3c88ad3d02cf.png)

**Comment by marijnh** [comment]
Setting the option to `true` still doesn't cause the problem to appear. If you want this looked at, you'll have to isolate it yourself.

**Comment by jdbruxelles** [comment]
> Setting the option to true still doesn't cause the problem to appear. 

Ok. But what causes this? If you have a look on lines 3 and 4 of [the latest image I sent](#issuecomment-549503847), you'll see the same issue in the block comment (when `continueComments` is enabled).

Unfortunately, I don't know how to fix that because I don't master the Codemirror API. Maybe @mtaran-google can do something about that.

**Comment by mtaran-google** [comment]
@marijnh I performed the original repro steps in a (locally-installed) index.html from the google-modes repo, specifically in the C++ mode. It also repros in the JS mode example there.

**Comment by marijnh** [comment]
I'm not seeing it int the google-modes demos either. Which CodeMirror version are you testing against?

**Comment by mtaran-google** [comment]
Oh great! We'd been using a version from last month (1aadc718a0534a0d77ba96a5b85b1c27bdc64b41) but upgrading to the latest release fixes this! :D
