### ISSUE TITLE
Handlebars raw tags not working

### ISSUE THREAD

**Issue by mbkinnovo** [codemirror/CodeMirror#6052]
There seems to be an issue in raw og triple mustache tags fixed in issue #5957 ... it doesn't work in the demo either. All content after the triple tag is not colour coded:

https://codemirror.net/mode/handlebars/index.html

![image](https://user-images.githubusercontent.com/20941567/68127753-c7534f80-ff16-11e9-9855-6f1aad31b39e.png)

**Comment by marijnh** [comment]
Support for triple braces seems to have been added in a6a9696aa61ffd918726 , without ever working. The mode multiplexer will cut off the inner mode at the first occurrence of its end token (in this case `}}`).

**Comment by mbkinnovo** [comment]
Thank you for at quick resolution. I can confirm the change has fixed the issue 👍
