### ISSUE TITLE
Text is added at wrong caret position in text area

### ISSUE THREAD

**Issue by AhtishamShahid** [codemirror/CodeMirror#6054]
**Initilization Code**
`CodeMirror.fromTextArea($(".edit-box", this.element)[0], {
        mode: "text/html",
        lineNumbers: true,
        lineWrapping: true
});`

On adding text in editor sometimes the text is added in the wrong position as shown in the GIF below 
This issue is tested on version 3.21.0 and 5.48.4
**Steps to reproduce.**
1. Open the editor add text in it.
2. Click on the end of any word and then click on the start of the next word.
3. Type anything, it will be added to wrong position.

**Code Pen** 
https://codepen.io/ahtishamshahid/pen/pooLqeJ

![codeMirrorBug](https://user-images.githubusercontent.com/26253150/68362460-2bf5f080-0149-11ea-9b3f-f46139dd239d.gif)

**Comment by marijnh** [comment]
I'm not able to reproduce this. Does it happen in the demos on the website?

**Comment by awaisdar001** [comment]
> I'm not able to reproduce this. Does it happen in the demos on the website?

Actually I was able to reproduce in a simple HTML template as well. Here is the content of the HTML file ( I can't attach the html so pasting the contents here.)

```
<html>

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous">
</script>

<script src="https://cdn.jsdelivr.net/npm/codemirror@3.21.0/lib/codemirror.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/codemirror@3.21.0/mode/xml/xml.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/codemirror@3.21.0/lib/codemirror.min.css"/>

<body>
<textarea  class="edit-box"  rows="4" cols="50"></textarea>
<textarea  class="edit-box2"  rows="4" cols="50"></textarea>
<script>
    var editor= CodeMirror.fromTextArea($(".edit-box", this.element)[0], {
        mode: "text/html",
        lineNumbers: true,
        lineWrapping: true,
      });
    editor.getDoc().setValue('<p><problem> <multiplechoiceresponse> <label>What do we call the accumulation of excess water in the root zone of the soil?</label> <choicegroup type="MultipleChoice" shuffle="true"> <choice correct="false">Water ponding<choicehint><br /></choicehint></choice></choicegroup></multiplechoiceresponse></problem></p>\n' +
        '<p>Water ponding is tahe accumulation of excess water on the soil surface.</p>\n' +
        '<p>Waterlogging is the acacumulation aof aexcessa watera ian tahe rooat zaone of the soil.</p>\n' +
        '<p>Bedding is a surface drainage method accomplished by ploughing land to form a series of low narrow ridges, separated by parallel furrows. Water from the furrows disaacharges into a perpendicular field drain at the lower end of the field.</p>\n' +
        '<p>Percolation is the gravity-induced downward flow of water through soil, especially in saturated or nearly saturated soil at hydraulic gradients of one or less.</p>\n' +
        '<p><choice correct="true">Waterlogging<choicehint></choicehint></choice></p>\n' +
        '<p>Water ponding is the accumulation of excess water on the soil surface.</p>\n' +
        '<p>Waterlogging is the accumulation of excess water in the root zone of the soil.</p>\n' +
        '<p>Bedding is a surface drainage method accomplished by ploughing land to form a series of low narrow ridges, separated by parallel furrows. Water from the furrows discharges into a perpendicular field drain at the lower end of the field.</p>\n' +
        '<p>Percolation is the gravity-induced downward flow of water through soil, especially in saturated or nearly saturated soil at hydraulic gradients of one or less.</p>\n' +
        '<p><choice correct="false">Percolation<choicehint></choicehint></choice></p>\n' +
        '<p>Water ponding is the accumulation of excess water on the soil surface.</p>\n' +
        '<p>Waterlogging is the accumulation of excess water in the root zone of the soil.</p>\n' +
        '<p>Bedding is a surface drainage method accomplished by ploughing land to form a series of low narrow ridges, separated by parallel furrows. Water from the furrows discharges into a perpendicular field drain at the lower end of the field.</p>\n' +
        '<p>Percolation is the gravity-induced downward flow of water through soil, especially in saturated or nearly saturated soil at hydraulic gradients of one or less.</p>\n' +
        '<p><choice correct="false">Bedding<choicehint>\n' +
        '<p>Water ponding is the accumulation of excess water on the soil surface.</p>\n' +
        '<p>Waterlogging is the accumulation of excess water in the root zone of the soil.</p>\n' +
        '<p>Bedding is a surface drainage method accomplished by ploughing land to form a series of low narrow ridges, separated by parallel furrows. Water from the furrows discharges into a perpendicular field drain at the lower end of the field.</p>\n' +
        '<p>Percolation is the gravity-induced downward flow of water through soil, especially in saturated or nearly saturated soil at hydraulic gradients of one or less.</p>\n' +
        '</choicehint></choice></p>\n' +
        '<p></p>\n' +
        '<p></p>\n' +
        '<p></p>');
</script>
</body>
</html>
```

**Comment by awaisdar001** [comment]
> I'm not able to reproduce this. Does it happen in the demos on the website?

I am able to reproduce by writing a long line without hitting an enter. If you copy paste this line in the editor you will be able to reproduce the bug. Or any long line will do. I tried.
```
Ok this is a new line i am trying to write, but it seems like the line is going to be long enough that the curser will move to the new and we will be able to reproduce the bug. 
```

**Comment by marijnh** [comment]
Still no luck. Please be more precise. Which page did you paste the line into? What positions did you click before typing? Which browser are you using?

**Comment by AhtishamShahid** [comment]
> Still no luck. Please be more precise. Which page did you paste the line into? What positions did you click before typing? Which browser are you using?

1. Use Code Pen Link [https://codepen.io/ahtishamshahid/pen/pooLqeJ](url) to test.
2. You can click anywhere in the text as shown in the image given above (In reported issue).
3. I am using Chrome browser for testing.

**Comment by enavarro** [comment]
I would like to add the problem is easier to replicate on Mac or Windows machine.

**Comment by marijnh** [comment]
That demo is using an ancient version of CodeMirror. If I load the current version, the problem goes away.

**Comment by awaisdar001** [comment]
- macOS Catalina
- Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by awaisdar001** [comment]
> That demo is using an ancient version of CodeMirror. If I load the current version, the problem goes away.

Thanks for the info; Let me try that.

**Comment by gillsignals** [comment]
Several users of the edX content editing platform have been experiencing this issue as well, and their engineers traced the problem back to CodeMirror and referred us to watch this issue. It is definitely affecting a live version of your product.

I sent a note to them to provide you more information, as I am unclear how edX implements CodeMirror, but I can verify that many users worldwide are experiencing this problem and we have an internal discussion board with several reports.
