### ISSUE TITLE
ensureCursorVisible for custom Enter

### ISSUE THREAD

**Issue by doakey3** [codemirror/CodeMirror#6059]
I want to write my own function for the Enter key. Let's say I've done this:

``` javascript
    cm.setOption("extraKeys", {"Enter", myEnterFunc})
```
and in `myEnterFunc` I do:

``` javascript
    myEnterFunc = function(cm) {cm.replaceSelection("\n", "end")}
```
I can't figure out how to make the editor ensure the cursor is visible after the enter key is pressed without using a `setTimout` method which looks kind of ugly. Looking in the source code, I found an `ensureCursorVisible` function. Could this function be made available as a callable function?

**Comment by marijnh** [comment]
Does something like this not work?

```
cm.operation(() => {
  cm.replaceSelection("\n", "end")
  cm.scrollIntoView()
})
```

**Comment by doakey3** [comment]
Calling `scrollIntoView()` immediately after doesn't work. I think the editor has to update and recalculate before this function works. I got it to work by using one of these methods:

```javascript
    editor.replaceSelection("\n" + leading_space, "end");
    setTimeout(function(){
        editor.scrollIntoView();
    }, 0);
```

or

``` javascript
    editor.replaceSelection("\n" + leading_space, "end");
    editor.on("update", function(event) {
        editor.scrollIntoView();
    });
```
The setTimout method is makes the scrollbar flicker a bit, so I went with the latter option, but I'm not sure if there will be unexpected consequences (I'm not sure exactly what triggers the update event).

**Comment by marijnh** [comment]
> Calling scrollIntoView() immediately after doesn't work. I think the editor has to update and recalculate before this function works.

It should work, in theory, and seems to work for me (I tested on the [website](https://codemirror.net) by pasting the below into the devtools console).

```
editor.setOption("extraKeys", {Enter: cm => cm.operation(() => {
  cm.replaceSelection("\n")
  cm.scrollIntoView()
})})
```

**Comment by doakey3** [comment]
My mistake. I had another function calling `cm.refresh()` onkeypress Enter, when I removed this, your method works fine. Thanks for your help.
