### ISSUE TITLE
Feature Request: AutoHotkey syntax support

### ISSUE THREAD

**Issue by Denis-net** [codemirror/CodeMirror#6060]
Hello !

I was redirected here by the [Boostnote team](https://github.com/BoostIO/Boostnote/issues/3351#issuecomment-552224957).

As I proposed there, i would like to have [Ahk](https://www.autohotkey.com/) snippet with color highlights.
But i see you are managing an entire text editor (interesting btw).
In VSCode there are some extensions that support Ahk and you could find them useful.
Or even better [this forum](https://autohotkey.com/board/topic/37643-best-ide-for-ahk/) or [this page](https://www.autohotkey.com/boards/viewforum.php?f=60).

I personally just need this [tmLanguage](https://github.com/stef-levesque/vscode-autohotkey/blob/master/syntaxes/ahk.tmLanguage) integration.

Thank you.

When i'll have time i'll definitely play with this project 😉
Best

**Comment by marijnh** [comment]
We're not adding new syntax to the core package anymore. The way to add new language modes is to write and distribute them yourself, as a separate package.
