### ISSUE TITLE
Rectangular selection failed after upgrade

### ISSUE THREAD

**Issue by fortooon** [codemirror/CodeMirror#6067]
Hi, all.

I try to upgrade CodeMirror from 5.14.2 to 5.49.2 and note that rectangle selection work incorrectly even after use new option : 
`configureMouse : function() { return {unit: "rectangle"};}`
In 5.14.2 version we used special option  `option("alwaysRectangularSelection", false);` that we used in method
`function leftButtonSelect(` in  condition 
`if ((chromeOS ? e.shiftKey && e.metaKey : e.altKey) || cm.options.alwaysRectangularSelection) {`
that help us do such kind of rectangle selection:
![rec_selection_2](https://user-images.githubusercontent.com/9059698/69126447-f7444a80-0af3-11ea-81ac-5304ebda7c3e.png)

I found that in new version it logic can be implemented just by using `configureMouse` option such way `configureMouse : function() { return {unit: "rectangle"};}`.
But in case when we start to select from shorter string and end after longer on another shorter, result selection don't include some part of text in 2d line :
![optimised](https://user-images.githubusercontent.com/9059698/69129484-2bbb0500-0afa-11ea-9198-5c602daf0a82.gif)

to reproduce it, plz see online demo http://jsfiddle.net/8r09tgv6/

After research code, I found that changes with `xRel` in `coordsCharInner` method not supported by `posFromMouse` in condition `if (forRect && coords.xRel == 1 && line.length == coords.ch) {` because now `xRel` can be more than 1.

So fix like `coords.xRel > 0 ` help in this situation.  
Is there any way around it? Or this fix is correct?

**Comment by marijnh** [comment]
Thanks for debugging that. Your proposed fix makes sense—implemented in attached patch.
