### ISSUE TITLE
[julia mode] Julia mode has a indent problem

### ISSUE THREAD

**Issue by p1scescom** [codemirror/CodeMirror#6071]
I use IJulia on JupyterLab v1.0.9 . JupyterLab uses CodeMirror. 
I found a problem of  CodeMirror's julia mode.
When I write this runnable code and push enter, the indent inserted by CodeMirror is broken.

```
a = [begin i end for i in 1:10]
    # a indent is inserted.

[if isodd(i) i else i+1 end for i in 1:10]
    # a indent is inserted.

[begin if isodd(i) i else i+1 end end for i in 1:10]
        # two indent is inserted.

[if isodd(i) if i%3 == 0 i*2 else 1 end else i end for i in 1:10]
        # two indent is inserted.
```

I think its reason is this section. 

https://github.com/codemirror/CodeMirror/blob/ab25dd7582f4954fc05892c3a85f592fad509925/mode/julia/julia.js#L129-L133

It intends to pop '[' state, but my codes have other states.
So I think editor's indent is broken by it.

https://github.com/codemirror/CodeMirror/blob/ab25dd7582f4954fc05892c3a85f592fad509925/mode/julia/julia.js#L132

Please give me an opinion.

**Comment by marijnh** [comment]
@malmaud or @pabloferz, want to take a look at this?

**Comment by p1scescom** [comment]
@axellew thank you for pushing your path ☺
