### ISSUE TITLE
[Highlight] Highlighting row only in view

### ISSUE THREAD

**Issue by vmagalhaes** [codemirror/CodeMirror#6074]
Hi,

I have a problem with the row highlight. I'm trying to use SHIFT + KEYS, to highlight the row and do some tests, but the codemirror are highlighting only the view of the row, I needed to highlight all the row, with whitespace and any characters that are on the row.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14242447/69438076-386e7180-0d23-11ea-8cc1-45b82c806d40.gif)

What can I do?

Regards,
Victor Magalhães.

**Comment by marijnh** [comment]
Does this still occur in the current version? Can you reproduce it in the demos on the website?

**Comment by vmagalhaes** [comment]
> Does this still occur in the current version? Can you reproduce it in the demos on the website?

I'm using the ngx-codemirror 1.3.10 and the codemirror 5.49.2. I think the ngx-codemirror no affect in the problem. Maybe the dialog?

**Comment by marijnh** [comment]
Maybe. Can you reduce this to the minimal wrapping/styling that causes it?

**Comment by udidol** [comment]
I also have an issue with highlighting rows.
I'm using the active-line.js addon, and when I try to highlight characters with SHIFT+ARROW KEYS, it removes the activeLine class from the highlighted lines and doesn't highlight anything.

Anyone come across that?

**Comment by marijnh** [comment]
I think you want a `styleActiveLine: {nonEmpty: true}` option.

**Comment by marijnh** [comment]
Closing this until a reproduction with plain CodeMirror is available.
