### ISSUE TITLE
CodeMirror addon json-lint.js not working

### ISSUE THREAD

**Issue by masa-ekohe** [codemirror/CodeMirror#6077]
index.haml
```haml
%script(src="https://codemirror.net/lib/codemirror.js")
%script(src="https://unpkg.com/jsonlint@1.6.3/web/jsonlint.js")
%script(src="https://codemirror.net/addon/lint/lint.js")
%script(src="https://codemirror.net/addon/lint/json-lint.js")
%link(src="https://codemirror.net/lib/codemirror.css")
%link(src="https://codemirror.net/addon/lint/lint.css")
%script(src="https://codemirror.net/mode/javascript/javascript.js")
%script(src="https://codemirror.net/mode/css/css.js")
%script(src="https://codemirror.net/")
%script(src="https://codemirror.net/")

%testarea#json
```

index.coffee
```coffee
editor = CodeMirror.fromTextArea(document.getElementById('json'),
      lineNumbers: true
      mode: "application/json"
      lint: true
      gutters: ["CodeMirror-lint-markers"]
    )
```

No warnings shown on the page.

<img width="239" alt="Screen Shot 2019-11-29 at 6 56 29 PM" src="https://user-images.githubusercontent.com/58195096/69894821-fec8d800-12d9-11ea-9d49-6caaccdfb9bf.png">

How could I make it work? I implemented this referencing the official doc and demo.

- https://codemirror.net/doc/manual.html#addons
- https://github.com/codemirror/CodeMirror/blob/master/demo/lint.html

**Comment by marijnh** [comment]
I don't know haml, but since the demo works, I'd say you just have to figure out what you're doing different, and it's unlikely that there's an issue in the library causing this.
