### ISSUE TITLE
Very bad performance on Mobile devices

### ISSUE THREAD

**Issue by elmurzaev** [codemirror/CodeMirror#6086]
I'm using CodeMirror in my **[WebEditor](https://play.google.com/store/apps/details?id=com.elmurzaev.webeditor)** project. The problem is that the editor is very laggy when editing text with 200+ lines of code.

**Comment by marijnh** [comment]
Does the same problem occur when you paste a similarly-sized document into the demo on https://codemirror.net?

**Comment by elmurzaev** [comment]
> Does the same problem occur when you paste a similarly-sized document into the demo on https://codemirror.net?

I'll check it later. I'll also provide a bit more details including the source code of the part where I use CodeMirror.

**Comment by elmurzaev** [comment]
@marijnh I could not paste similarly-sized document into your demo on my mobile phone. Please, check the app I'm talking about. I also sent you an email with some details.

**Comment by marijnh** [comment]
> I could not paste similarly-sized document into your demo on my mobile phone

I don't see why not. I am not inclined to go dig through your app when you can't even be bothered to see if the problem reproduces in a plain setup.

**Comment by elmurzaev** [comment]
Your demo looks like deletes the code I pasted. This is the source code of the google site (mobile version).

**Comment by elmurzaev** [comment]
@marijnh you only need to see [this](https://github.com/elmurzaev/WebEditor/blob/master/app/src/main/assets/codemirror/editor.htm) simple, 2 KB HTML file.

**Comment by elmurzaev** [comment]
When I set the height & width to fixed 500px the editor became much more smoother.

**Comment by elmurzaev** [comment]
Looks like the problem is within the size of the editor.

**Comment by elmurzaev** [comment]
Problem solved by setting height & width to 100vh & 100vw. You should probably mention this in your docs. Thanks!
