### ISSUE TITLE
cursor inside marker

### ISSUE THREAD

**Issue by lukas1994** [codemirror/CodeMirror#6087]
I'm using codemirror with custom markers. I'm adding the markers with the following code:
```
doc.markText(from, to, {
      replacedWith: elem,
      atomic: true,
});
```
Sometimes when I focus the codemirror instance the curser ends up inside the marker:
![Screen Recording 2019-12-17 at 11 58 pm](https://user-images.githubusercontent.com/6901762/71041498-8495b180-2129-11ea-95df-7546a7f1a488.gif)

I found some old issues that referenced this problem but they seem to be resolved so I'm creating a new issue. I'm using version `"codemirror": "^5.47.0"`

**Comment by marijnh** [comment]
It'd be useful if you could create an example script that reproduces the issue.

**Comment by lukas1994** [comment]
I tried to repro it in a sandbox but didn't manage. I fixed it in the end by calling setCursor(0,0) after marking the text.
