### ISSUE TITLE
Mobile device inline widget text field losts focus

### ISSUE THREAD

**Issue by shd101wyy** [codemirror/CodeMirror#6090]
Hi there,

Basically I created an inline widget using `markText` function like [this](https://github.com/0xGG/VickyMD/blob/master/src/addon/fold-widget.ts#L176).  

The inline widget has a text field that allows user to type something in it:  

![Screenshot from 2019-12-19 19-11-00](https://user-images.githubusercontent.com/1908863/71169625-5b456480-2294-11ea-8f94-b02e8852848d.png)

You can probably try it online [here](https://crossnote.app/#/demo_editor/86a1953d-d5db-4db2-877a-3aa2dd136e1d?noteKey=9dd60dc3-4521-4b97-a808-77a06906eb25).

It works fine on desktop browser when I type something in the text field. But on mobile device browsers, like iOS Safari, when I type something, the codemirror editor will take the focus. For example, if I type `s` in the text field, that `s` appears on the first line of the editor instead of the text field.

![Screenshot from 2019-12-19 19-16-12](https://user-images.githubusercontent.com/1908863/71169727-98a9f200-2294-11ea-8e30-9059aef94b4a.png)

Any suggestions?

Thanks a lot ;)

**Comment by shd101wyy** [comment]
Found the solution. Adding `inputStyle: "textarea"` helps. Thank you ;)

**Comment by shd101wyy** [comment]
Actually if I set `inputStyle: "textarea"` then the paste would stop working in mobile devices...

**Comment by marijnh** [comment]
A lot of things will stop working on mobile when you force inputStyle to textarea, so don't do that.
