### ISSUE TITLE
Add Jsx hints

### ISSUE THREAD

**Issue by matias4205** [codemirror/CodeMirror#6092]
Hey! I am currently working on a Jsx live transpiler and I tried to add the html-hints addon, but it only works with the edior in html mode because of the token types I think. So I would like to suggest adding a jsx-hints addon where html as well as js suggestions will be shown up. Thanks!

**Comment by marijnh** [comment]
We're not adding things like that to the main distribution anymore, but it should be possible to write it as a separate extension.
