### ISSUE TITLE
Bug: 5.50.0 breaks Line Widgets

### ISSUE THREAD

**Issue by fellmann** [codemirror/CodeMirror#6100]
As in description. Real life example: https://codemirror.net/demo/widget.html
When you change the code, line widgets duplicate, as removal is broken.

Bug introduced in:
https://github.com/codemirror/CodeMirror/commit/ddafba743612718d2ecbff7edd554ff30e57d390

Fix:
https://github.com/codemirror/CodeMirror/pull/6099

@marijnh Please review.

**Comment by marijnh** [comment]
Resolved in #6099
