### ISSUE TITLE
Document.clearHistory() does not clear history of linked documents.

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#6108]
`clearHistory` only clears the history of the document instance on which it's invoked, and doesn't call `linkedDocs()` to ensure that it's cleared for documents that are intended to have shared history. 

The result is that if one has two CodeMirror instances that share contents via a linked doc, if the undo history is reset via `clearHistory()` on one document, then the other will still be able to perform undo actions on the contents of the file, which doesn't seem expected.

https://github.com/codemirror/CodeMirror/blob/a41ea1b7dfffed8400f58f3f366fa298ee44a4b3/src/model/Doc.js#L200

(If this is intended behavior, is there another approach besides manually calling `iterLinkedDocs()` that should be used to reset the undo history?)

**Comment by marijnh** [comment]
I agree that should clear linked docs' history too. Implemented in attached patch.
