### ISSUE TITLE
Start of line/End of line in RTL text is not working.

### ISSUE THREAD

**Issue by aameen951** [codemirror/CodeMirror#6117]
Hello,

I'm using CodeMirror with the following configurations:
```
  let editor = CodeMirror.fromTextArea(input, {
    direction: "rtl",
  });
```

The editor is having a problem finding the start/end of the first line in the following text:

![DVo0r9E3UR](https://user-images.githubusercontent.com/7351160/72660759-0efc5a00-39e3-11ea-9851-9c107e2b2817.gif)

```
سسسسسس 1  سسسس
سسسسسس
سسسسسس
سسسسسس
```

**Comment by axellew** [comment]
What is the expected outcome here (asking since mixed rtl and ltr always confuses me)? Is it that the selection should should go to the same column (far right) on the top line?

**Comment by aameen951** [comment]
Yes, the cursor should be at the start of the line. The same thing happen with the Home/End keys.
The first line in the example contains three visual runs. When you hit the home button it should go to the start of the first run, instead it is going to the end of the first run.

**Comment by aameen951** [comment]
Also, let me mention this since it might has something to do with the problem, Home/End keys are reversed, Home goes to the end of the line (left) and End goes to the start of the line (right).

I tried to fix the problem but I don't understand this comment or what the code underneath it is doing:
https://github.com/codemirror/CodeMirror/blob/ed8dfeb5e2ed25b5dd1f1eccc7b757ca6dbd118d/src/input/movement.js#L24-L35

**Comment by marijnh** [comment]
Oh, I thought we had implemented this ages ago, but indeed, it was missing. Attached patch should improve this.

**Comment by aameen951** [comment]
Thank you for the quick response.
Home/End keys are doing the right thing now.
But that is not the original problem. The problem is the editor is not going to the start of the line nor the end of the line when hitting Home/End button as show in the video above.
You can try hitting Home/End when you are on the following line (rtl enabled in the configurations):
```
سسسس 123 سسسس
```
Basically, when you hit Home the cursor goes to the end of the first visual run instead of the start of the first visual run.

**Comment by marijnh** [comment]
Oh, I got derailed by the first brokenness I saw and didn't read the issue properly. Does attached patch help?

**Comment by aameen951** [comment]
That's perfect!

Thanks 🌹
