### ISSUE TITLE
Language modes

### ISSUE THREAD

**Issue by Tonypz** [codemirror/CodeMirror#6118]
Hi, we use the library in our project. Requires code highlighting for the "notation3" language. Are there any ways to do it?

PS 

I looked at the modes (https://codemirror.net/mode/) , but did not find anything like it.

Thanks!

**Comment by marijnh** [comment]
You'll have to write it as a separate module. If you end up open sourcing it, the recommended way is to create your own npm package for it, since we're not adding any further languages to the main distribution.
