### ISSUE TITLE
Set the value of the 'text / turtle' mode but the backlight completely disappeared

### ISSUE THREAD

**Issue by Tonypz** [codemirror/CodeMirror#6121]
Before rendering the editor passed it a value. Before that, C # worked fine

 this.codemirror = codemirror(this.ui.editor[0], {
            extraKeys,
            lineNumbers: true,
            mode: 'text/turtle',

![image](https://user-images.githubusercontent.com/23166800/72789561-0c993a80-3c45-11ea-950d-89e7e884e912.png)

**Comment by marijnh** [comment]
Since [the demo](https://codemirror.net/mode/turtle/) of that mode still works, I guess you'll have to figure out what your code is doing differently.

**Comment by Tonypz** [comment]
Maybe you know the reason. But any change in language (except C #) is drawn in plain black.
