### ISSUE TITLE
How to insert another value using AutoComplete ?

### ISSUE THREAD

**Issue by Tonypz** [codemirror/CodeMirror#6122]
I have a tooltip with names
![image](https://user-images.githubusercontent.com/23166800/72899329-d1773400-3d36-11ea-901c-0be48e6d5628.png)

I want that for example, when you select the first line of "cmw", another phrase is inserted, for example, "machine"

**Comment by marijnh** [comment]
See the `text` and `displayText` properties in the [docs for show-hint](https://codemirror.net/doc/manual.html#addon_show-hint).
