### ISSUE TITLE
String interpolation + printf format string = confused syntax highlighter and garbled, uneditable cell

### ISSUE THREAD

**Issue by bzinberg** [codemirror/CodeMirror#6128]
Redirected from https://github.com/JuliaLang/IJulia.jl/issues/896:

Steps to reproduce:

```sh
virtualenv -p python3 repro_jupyter_printf
source repro_jupyter_printf/bin/activate
pip install jupyter
cd repro_jupyter_printf
JULIA_PROJECT=. julia -e 'import Pkg; Pkg.add("IJulia")'
JULIA_PROJECT=. jupyter notebook
```

Then in the Jupyter frontend, create a new Julia notebook, and in the first cell (a code cell), type these characters:

```
"$(@sprintf("%04
```

The 4 is not displayed, and the frontend gets confused.  From that point on the cell looks not editable (in Firefox, no cursor), and trying to type new text in the cell results in the text disappearing and sometimes reappearing.  Also, the cell loses all syntax highlighting.  This behavior for the offending cell persists across page reloads.  Editing other cells or creating new cells still works.

I'm guessing the syntax highlighter is getting confused.

**Comment by marijnh** [comment]
The [Julia mode](https://codemirror.net/mode/julia/) doesn't seem to crash on this input, but this does sound like issue #6064, which was fixed two months ago. So see if you can get Jupyter to update that code (specifically mode/julia/julia.js). If that doesn't help, feel free to reopen.
