### ISSUE TITLE
Feature Request: Option to disable setext headers in markdown mode

### ISSUE THREAD

**Issue by micmcg** [codemirror/CodeMirror#6129]
I know that setext headers are part of the [commonmark spec](https://spec.commonmark.org/0.28/#setext-headings), but our users find them unexpected and confusing (particularly when only a single character is used), in part because we style `cm-header-2` to match the font size it will be rendered at
![image](https://user-images.githubusercontent.com/523902/73514642-91a30180-4446-11ea-8391-0225ece49cab.png)

Would it be possible to add an option to disable setext headers to the markdown modeConfig in the same way other markdown features can be enabled/disabled like `strikethrough`

Alternatively, the spec says 
> If a line containing a single `-` can be interpreted as an empty list items, it should be interpreted this way and **not** as a setext heading underline.

which if implemented would largely solve our issue as well. 

Thanks very much 👍

**Comment by marijnh** [comment]
That mode isn't being actively maintained, but if you submit a pull request I'll review it.

**Comment by micmcg** [comment]
Thanks as always @marijnh for being such a responsive maintainer 👍
