### ISSUE TITLE
command + G => find next not working properly

### ISSUE THREAD

**Issue by ashu8912** [codemirror/CodeMirror#6130]
The Command + G combination should open findNext modal which than we can press multiple times to go to next matching lines but this doesn't happen and the modal gets closed on repetitive pressing this is not a desired behaviour editors like vs code doesn't do that 

Similar is the issue with command + Shift + G which opens the find prev modal that also doesn't shows desired behaviour

**Comment by marijnh** [comment]
The interface provided by CodeMirror's search addon works differently from the one you're used to. That's not a bug, just a different design. As such, I can't do much with a report that insists the code "_should_" work a certain way.
