### ISSUE TITLE
autoCloseBrackets option not working

### ISSUE THREAD

**Issue by ashu8912** [codemirror/CodeMirror#6131]
https://codesandbox.io/s/codemirror-vffh5
here is a codesandbox the autoCloseBrackets thing is not working.

**Comment by ashu8912** [comment]
config for editor is in Example.js in codepen.

**Comment by marijnh** [comment]
It's defined by an addon (`import "codemirror/addon/edit/closebrackets"`), not the core library.

**Comment by ashu8912** [comment]
thanks @marijnh
