### ISSUE TITLE
Line numbers disappear when scrolling left using CodeMirror.scrollTo at the left-most edge

### ISSUE THREAD

**Issue by mliao95** [codemirror/CodeMirror#6139]
I am having trouble saving and sending a jsbin of the issue, but here is a GIF with the code and example that I am seeing:
https://imgur.com/a/rLqFCIT

Is this expected or a bug?

**Comment by marijnh** [comment]
Seems `scrollTo` isn't handling negative x coordinates well. Attached patch clips them.
