### ISSUE TITLE
textarea content no longer restored when posting and navigating back (in chrome)

### ISSUE THREAD

**Issue by steveniemitz** [codemirror/CodeMirror#6141]
Previously, using CodeMirror in a textarea of a form, I would be able to have a workflow of something like this:

- Edit code
- Post form (navigating to a new page)
- Navigate back

After navigating back, the text that was in the textarea that was posted would be populated still.

However, at some point in the recent past (in a chrome update I'd assume), this no longer works and instead the textarea is blank.  I assume this is actually a bug/behavior change in chrome, but I'm curious if anyone knows a workaround for this?

**Comment by marijnh** [comment]
No idea—if you're using the `save()` method to put the editor content back into the textarea, I can't think of anything else that might help.

**Comment by steveniemitz** [comment]
I tracked this down to when I was calling `fromTextArea`.  If I do so from the `ready` event, the text no longer gets restored, but if I do it from `load` it works correctly.

Still not sure what the change was in chrome to cause this, but this seemed to work around it.
