### ISSUE TITLE
about modify indentUnit

### ISSUE THREAD

**Issue by RanX12** [codemirror/CodeMirror#6144]
After the editor has been established, I pass
this.cm.setOption ('indentUnit', index) to modify the indentUnit, but after each modification, the indentUnit on the page will be index * 10, but my getOption ('indentUnit') is still the index. Why is this?

**Comment by marijnh** [comment]
What does it mean for "the indentUnit on the page" to be a certain thing? Do you mean the indentation you get at a specific point in your document? If so, could you be more specific about that?

**Comment by RanX12** [comment]
I need to dynamically change the two parameters of tabSize and indentUnit, but after the indentUnit is changed, the displayed indentation will be * 10. If I this.cm.setOption ('indentUnit', 2), then the displayed indentation will Becomes 20

**Comment by RanX12** [comment]
But the value of my cm.getOption ('indentUnit') is still 2

**Comment by marijnh** [comment]
What displayed indentation? `indentUnit` has no effect until you actually indent a line. And that line's actual indentation will depend both on the `indentUnit` setting and the context.

**Comment by RanX12** [comment]
Simply put：
I set tabSize = 4 and indentUnit = 4
But indentUnit is indented by 40 spaces
If indentUnit = 2, indentUnit is indented by 20 spaces

**Comment by marijnh** [comment]
> But indentUnit is indented by 40 spaces

Again, I don't know what you mean by this (and unless you provide an example I'm going to give up asking)

**Comment by RanX12** [comment]
this.cm = CodeMirror.fromTextArea(element[0], {
      mode: 'text/x-ruby',
      theme: 'monokai',
      matchBrackets: true,
      indentUnit: tab_size,
      tabSize: tab_size,
      vimMode: true
    })
If this is my editor, I want to change the indentUnit after the editor has been created, this.cm.setOption ('indentUnit', 2),
After my setOption('indentUnit', 2) succeeded, my actual indentation effect became 20
![image](https://user-images.githubusercontent.com/46048444/74424586-31bc4a00-4e8d-11ea-8dfb-64f377fd4037.png)

**Comment by marijnh** [comment]
Strange. I can't reproduce that in the [ruby mode demo](https://codemirror.net/mode/ruby/)—if I change `indentUnit` there, further indentations seem to do the right thing.

**Comment by RanX12** [comment]
I click the button to change the value of indentUnit. For example, when my editor is initialized, indentUnit is 4, but I want to change indentUnit to 2 during the process of writing code.

**Comment by RanX12** [comment]
![image](https://user-images.githubusercontent.com/46048444/74621486-26606b80-5178-11ea-89fa-dfde1ac4b1fb.png)
![image](https://user-images.githubusercontent.com/46048444/74621504-311b0080-5178-11ea-8f75-89de2e793557.png)

**Comment by RanX12** [comment]
May be described more accurately here：
https://stackoverflow.com/questions/60255695/there-was-a-problem-setting-up-codemirror-indentunit
