### ISSUE TITLE
Build failing when working with strict mode 

### ISSUE THREAD

**Issue by JerinJ** [codemirror/CodeMirror#6149]
When `tsconfig.json` has strict mode on, when doing `ng serve`  dependencies throws error for code-mirror 

![image](https://user-images.githubusercontent.com/2240674/74821111-1f2c8f80-5329-11ea-8cf6-cbdfd2daa794.png)

Even libcheck to false, issue still persists.

![image](https://user-images.githubusercontent.com/2240674/74821244-526f1e80-5329-11ea-9c73-ff5adc5462fb.png)

What can be done here.

**Comment by marijnh** [comment]
This library isn't written in TypeScript and doesn't provide (it's own) TypeScript declaration file, so this isn't something we're going to take responsibility for.
