### ISSUE TITLE
Better search and more results for hint-sql

### ISSUE THREAD

**Issue by matteopuppis** [codemirror/CodeMirror#6152]
I've made some changes to the sql-hint.js file, so that now it appends, at the end of the result array, also words
<img width="997" alt="Schermata 2020-02-20 alle 18 24 59" src="https://user-images.githubusercontent.com/50489911/74961410-52951a00-540e-11ea-880d-5621230c2de7.png">

 that contains (not only "start with") the string.

**Comment by marijnh** [comment]
Okay, but this is just an issue, though it sounds like you were trying to create a pull request.

**Comment by matteopuppis** [comment]
Yes, I want to create a pull request but I'm no expert on git, so I didn't
know how to do that exactly.

Sorry, I will study how to create a pull request.

Il giorno ven 21 feb 2020 alle ore 08:21 Marijn Haverbeke <
notifications@github.com> ha scritto:
