### ISSUE TITLE
Codemirror's Cursor is simply "invisible", and parenthesis' dont create opposings {}

### ISSUE THREAD

**Issue by skylerspark** [codemirror/CodeMirror#6158]
Ill just go ahead and show the two issues Im dealing with:
![Capture](https://user-images.githubusercontent.com/44554976/75471304-0e4ed000-5960-11ea-8eef-9e9ca610b41f.PNG)

The biggest issue, theres no cursor... So I cant see where Im typing.

and I also noticed that the double parenthesis arent being created.. like typing { should for {} with the cursor in between.

However, both of these things dont work.

**Also a bit after making this, I see that selecting things, either by dragging or just shift+arrow keys doesnt work either.**

Source Code: https://codepen.io/SkylerSpark/pen/GRJmoKq

Full Page View: https://codepen.io/SkylerSpark/full/GRJmoKq

**Comment by skylerspark** [comment]
I think I found out that the closing brackets is an addon... so yeah.. ignore that part

**Comment by marijnh** [comment]
If you tried out the demos on the website, you would have noticed that these issues don't exist there. Since the general tone of this issue is entitled and obnoxious, pointing that out is all the time I'm willing to put into this.
