### ISSUE TITLE
Need syntax support for nim Programming language

### ISSUE THREAD

**Issue by RokuKent** [codemirror/CodeMirror#6165]
https://nim-lang.org

**Comment by marijnh** [comment]
You'll have to write a mode for it, then. Since we aren't adding more modes to the main distribution, the way to go would be to set it up as a separate project and distribute it as an npm package. Or use the one from https://github.com/zah/nim.lt/blob/master/codemirror/nimrod.js

**Comment by RokuKent** [comment]
The issue is that there are packages like Typora that uses Codemirror and if new languages are not included it's a dead-end for type formatting.

**Comment by RokuKent** [comment]
I will file a separate issue in Typora Github and ask them to switch to another code formatting system for code blocks -- this might also be the case for other Markup tools using Codeformatter just now.

**Comment by RokuKent** [comment]
This policy also impacts new languages that might appear the next year or two and will become popular.
