### ISSUE TITLE
How to convert code to tokens by codemirror?

### ISSUE THREAD

**Issue by BuJiZhi** [codemirror/CodeMirror#6166]
I think there must have a method like tokenizer to get tokens.But I read the source code of codemirror, still can't find this method.Is that method exsit?

**Comment by marijnh** [comment]
This is the issue tracker, not really a place to ask for help. That's what the [forum](https://discuss.codemirror.net/) is for.

It's usually easier to read through the docs than the code. [`getLineTokens`](https://codemirror.net/doc/manual.html#getLineTokens) might be what you want. Or the [runmode addon](https://codemirror.net/doc/manual.html#addon_runmode).

**Comment by BrianHung** [comment]
Not to revive a closed thread, but for people who search Github issues, here's the way I'm using CodeMirror to tokenize and style:
```js
import CodeMirror from 'codemirror/addon/runmode/runmode.node.js';
import "codemirror/mode/meta";

 // Compute token styles with node attrs lang.
const tokens = [];
const getTokens = (text, style) => { tokens.push({text, style: style ? `cm-${style}` : null}) }

const lang = "..." // your language here
const mode = CodeMirror.findModeByMIME(lang) || CodeMirror.findModeByName(lang);

// Need to wait for import to finish before calling runMode
if (mode && !CodeMirror.modes[mode])
  import(`codemirror/mode/${mode.mode}/${mode.mode}.js`);

const text = "..." // your text here
CodeMirror.runMode(text, mode.mime || "text/plain", getTokens);
```

The [`source-highlight`](https://github.com/codemirror/CodeMirror/blob/master/bin/source-highlight) is another good example.
