### ISSUE TITLE
codemirror/doc/logo.png  is not available with npm install react-codemirror

### ISSUE THREAD

**Issue by hiraditya** [codemirror/CodeMirror#6176]
This causes error with webpack. To fix this i downloaded logo.png and copied to codemirror/doc/.

**Comment by marijnh** [comment]
Why does webpack want to access the logo, though?

**Comment by hiraditya** [comment]
No idea, maybe via some transitive dependency.

**Comment by marijnh** [comment]
Hm, I don't think that's a bug in this package then, though.
