### ISSUE TITLE
How to display default key even if extra key event is triggered for the particular character.

### ISSUE THREAD

**Issue by Karthik15111996** [codemirror/CodeMirror#6178]
Hi Team,
We have triggered extra key event for "Shift-2" and in the function we have displayed the list of values in the show hint. But, in such case "@" character is not showing in my text area. I have tried with replaceRange within the extra key method, If I do so, the show hint dialog is not displaying. And also ensure after selecting a value in the show hint how to remove the "@" character that is displayed. Please ping with the solution for my case

**Comment by Karthik15111996** [comment]
Hi Team,
We have triggered extra key event for "Shift-2" and in the function we have displayed the list of values in the show hint. But, in such case "@" character is not showing in my text area. I have tried with replaceRange within the extra key method, If I do so, the show hint dialog is not displaying. And also ensure after selecting a value in the show hint how to remove the "@" character that is displayed. Please ping with the solution for my case

**Comment by marijnh** [comment]
Return `CodeMirror.Pass` from your key handler.
