### ISSUE TITLE
Json color error

### ISSUE THREAD

**Issue by bugracoskun** [codemirror/CodeMirror#6182]
I am loading my json to CodeMirror but colors show as black. 

How to make colorful my json text.

`var b=document.getElementById("JsonText");
 var geojson3={"type": "FeatureCollection","features": []}
 var myCodeMirror = CodeMirror(b, {
          lineNumbers: true,
          value: geojson3
});`

Anyone can help me ?

**Comment by marijnh** [comment]
Load `mode/javascript/javascript.js` and set your `mode` option to `"application/json"`.

This is the bug tracker, though, and not the place for questions. Please use the [forum](https://discuss.codemirror.net/) next time.
