### ISSUE TITLE
PHP syntax highlighting

### ISSUE THREAD

**Issue by jonathandalgaard** [codemirror/CodeMirror#6183]
It seems like PHP syntax highlighting doesn't work when using the `text/x-php` mode.

How can I get syntax highlighting in my PHP file with the `text/x-php` mode?

I tried the `application/x-httpd-php` mode, but that doesn't work since I have a pure PHP file without a closing `?>` tag.

This is the code I use to initialize CodeMirror:

```
CodeMirror.fromTextArea(el, {
  mode: `text/x-php`,
  readOnly: true,
  autofocus: true
});
```

**Comment by marijnh** [comment]
This seems to work fine in the [demo](https://codemirror.net/mode/php/) (run `editor.setOption("mode", "text/x-php")` in the console), so I think the problem is in your setup.

**Comment by jonathandalgaard** [comment]
Strange, what could possibly be my issue then?

**Comment by jonathandalgaard** [comment]
The problem was that I needed to import the clike file too.
