### ISSUE TITLE
A lot of x'es are added to my editor

### ISSUE THREAD

**Issue by jonathandalgaard** [codemirror/CodeMirror#6184]
When creating a CodeMirror editor I get a span with a lot of x'es before the data that I put into the editor.

Here's a screenshot of how it looks:

<img width="632" alt="Typer" src="https://user-images.githubusercontent.com/13871894/77347467-31d72180-6d38-11ea-871b-a31be80971bd.png">

From what I can see in the code `codemirror.js`, the x'es are coming from the `charWidth` function.
This is the code:
```
  // Compute the default character width.
  function charWidth(display) {
    if (display.cachedCharWidth != null) { return display.cachedCharWidth }
    var anchor = elt("span", "xxxxxxxxxx");
    var pre = elt("pre", [anchor], "CodeMirror-line-like");
    removeChildrenAndAdd(display.measure, pre);
    var rect = anchor.getBoundingClientRect(), width = (rect.right - rect.left) / 10;
    if (width > 2) { display.cachedCharWidth = width; }
    return width || 10
  }
```

Am I doing something wrong since this happens, or?

**Comment by marijnh** [comment]
I expect you're not including the CSS file (lib/codemirror.css), which will hide these.
