### ISSUE TITLE
Emacs M-Backspace does not work as intended

### ISSUE THREAD

**Issue by felberj** [codemirror/CodeMirror#6198]
How to reproduce:

1. Go to https://codemirror.net/demo/emacs.html
2. Place cursor on line 2 at the position of the $ sign: `/* getchar:  simple buffered version$ */`
3. Press M-Backspace

Expected: Deletes word "version"
Actual: It deletes backwards

OS: ChromeOS Version 80.0.3987.158 (64-bit)
Browser: Chrome

**Comment by felberj** [comment]
I am sorry, I had to edit this bug as I meant that M-Backspace does not work (as described in https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf)

**Comment by marijnh** [comment]
> Expected: Deletes word "version"
> Actual: It deletes backwards

I don't see the difference between these—isn't the word version the one that would be deleted when deleting backwards from this position? Or it is only deleting a single character?

In any case, this seems to work on Firefox and Chrome (Linux), so it's likely that the OS is somehow reporting this key press incorrectly on ChromeOS. Which isn't something CodeMirror can help.

**Comment by felberj** [comment]
Thanks, I will look into this.

**Comment by felberj** [comment]
I confirm that this is working as intended on Chrome on Windows. I am closing this bug and report the issue to chromeos.
