### ISSUE TITLE
getTokenTypeAt return null, but the position is property styled.

### ISSUE THREAD

**Issue by vipcxj** [codemirror/CodeMirror#6199]
I write a custom mode, and it work properly.
I want it to support fold function. so I register a helper. but it not work. after debug, I found getTokenTypeAt return null, but at this position, the text is styled by my custom style.
Or I misunderstand something? Does getTokenTypeAt  only return type when the mode I write return standard style such as keyword, string. My custom style not work?.
When debug into the getTokenTypeAt, I found getLineStyles return a array, and my custom style is in it. but finally, getTokenTypeAt return null, not my custom style.

**Comment by marijnh** [comment]
Any styles assigned by modes should appear in the result of `getTokenTypeAt`. If you can reduce the problem to a minimal demo, I could take a look.

**Comment by vipcxj** [comment]
> Any styles assigned by modes should appear in the result of `getTokenTypeAt`. If you can reduce the problem to a minimal demo, I could take a look.

I found I misunderstand the pos parameter of getTokenTypeAt. it means 'before', not 'at', So I change pos.ch to pos.ch + 1, it works.
