### ISSUE TITLE
[vim] Add all functions in the vim API to the documentation

### ISSUE THREAD

**Issue by ianhi** [codemirror/CodeMirror#6206]
The docs on extending vim are great but currently are missing several of the functions in the [`vimApi`](https://codemirror.net/doc/manual.html#vimapi). In particular:
```
buildKeyMap
getRegisterController
resetVimGlobalState_
getVimGlobalState_
maybeInitVimState_
InsertModeKey
unmap
_mapCommand
noremap
mapclear
handleKey
findKey
defineRegister
```
Could more (all?) of this api be included in the documentation? If yes, I'm happy to open a PR starting to document these.

**Comment by marijnh** [comment]
Sure, that would be useful.
