### ISSUE TITLE
Syntax highlighting works only partially with php

### ISSUE THREAD

**Issue by smknstd** [codemirror/CodeMirror#6207]
Php syntax highlighting works but only partially, too much type of elements seem to have the same color. Comparing to the [php demo](https://codemirror.net/mode/php/index.html) you can spot something more complete (and whatever the theme I load). Do you have any clue why is that ?

on my app with config: `mime: 'application/x-httpd-php',`:

![Carbon](https://user-images.githubusercontent.com/2412608/78928604-2fe3c100-7aa1-11ea-85cd-ce7f7c426f9f.png)

on demo:

![Screenshot_2020-04-08 CodeMirror PHP mode](https://user-images.githubusercontent.com/2412608/78928597-2bb7a380-7aa1-11ea-8102-831ad44c4256.png)

**Comment by marijnh** [comment]
Looks like you're using a theme that doesn't distinguish between `cm-variable` and `cm-variable-2`.

**Comment by smknstd** [comment]
thanx

**Comment by smknstd** [comment]
@marijnh I tried with `dracula` theme which has different value for every variables including `cm-variable` and `cm-variable-2`. And still has same result. I think it shouldn't use `cm-variable-2` ([white](https://codemirror.net/theme/dracula.css)) for both `$object` and call to `->method()` :

![Screenshot_2020-04-13 Carbon Snippet(3)](https://user-images.githubusercontent.com/2412608/79110904-c226e600-7d7b-11ea-8908-e40ad1efa033.png)

I have no idea why with reserved keyword `next`, it works differently ...

Here is syntax highlighting with same theme in my IDE (phpstorm):

![Screenshot from 2020-04-13 11-41-03](https://user-images.githubusercontent.com/2412608/79110970-e1257800-7d7b-11ea-8125-67c06e6d0e86.png)

Ok, there is a swap between blue and white, but we can notice that `->method()` has a different color than `$object`.

What do you think ?

**Comment by marijnh** [comment]
So do I understand correctly that now it is working the same way in your setup as in the demo on the website, but you want it to work differently?

**Comment by smknstd** [comment]
No unfortunately not, demo page still works differently. Here is the demo page, it is showing 2 colors (blue and black):

![Screenshot_2020-04-13 CodeMirror PHP mode(1)](https://user-images.githubusercontent.com/2412608/79136572-86a70e80-7db1-11ea-8307-78760c8044a1.png)

In my setup it only show one (white)

![Screenshot_2020-04-13 Carbon Snippet(4)](https://user-images.githubusercontent.com/2412608/79136596-90c90d00-7db1-11ea-8fdf-c758f179db19.png)

Like I said, a different color is used with keywork `next` and it was misleading...

**Comment by smknstd** [comment]
From theme's css:

```
.cm-s-dracula span.cm-variable { color: #50fa7b; }
.cm-s-dracula span.cm-variable-2 { color: white; }
```

But when I inspect, I find:

![Screenshot from 2020-04-13 18-16-25](https://user-images.githubusercontent.com/2412608/79137460-0c778980-7db3-11ea-8186-1f537e44e015.png)

**Comment by smknstd** [comment]
problem is live here : https://carbon.now.sh/1HBRbot05AIFiezO6H2n

**Comment by marijnh** [comment]
The devtools claim that style is coming from inline css. I don't know why that's there, but there's no rule like that in the CodeMirror repository, so this isn't a problem with the library.

**Comment by smknstd** [comment]
I'll try to reproduce on a distinct and dedicated codemirror setup, and let you know. Thanx again for your time.
