### ISSUE TITLE
Cursor position not visible on click

### ISSUE THREAD

**Issue by Karthik15111996** [codemirror/CodeMirror#6209]
Curson position is not getting visible in the editor on click, but if I press any key the curson position gets visible and working fine.

Like this I render the editor

var editor = (<any>window).CodeMirror(textAreaContainer[0], {
                mode: 'text/x-sql',
                indentWithTabs: true,
                smartIndent: true,
                lineNumbers: false,
                matchBrackets: true,
                autofocus: true,
                extraKeys: {
                    'Ctrl-Space': 'autocomplete'
                },
                hintOptions: {},
            });

**Comment by marijnh** [comment]
There's nothing special in that configuration, and the problem does not occur in any of the demos (I assume, you didn't provide any info about browser and platform, so I can't test what you're doing, precisely). You'll have to provide additional details on how to reproduce this.

**Comment by Karthik15111996** [comment]
Issue occurs on Google browser Version 80.0.3987.163

**Comment by marijnh** [comment]
Does it occur for you on https://codemirror.net ? For me, it doesn't (assuming Google browser means Chrome).

**Comment by Karthik15111996** [comment]
Issue occurs when I render code editor without any character inputs (empty editor) are given. But If I render with characters its working fine

**Comment by marijnh** [comment]
Sorry, but that still doesn't help reproduce this, at all. If you can set up a minimal demo that shows the issue, I can take a look. Until then, I'm going to close this.
