### ISSUE TITLE
[autoFormat] Blank line was deleted

### ISSUE THREAD

**Issue by RanX12** [codemirror/CodeMirror#6211]
This is the code before formatting：
![image](https://user-images.githubusercontent.com/46048444/78966324-2191b580-7b32-11ea-9e5a-fe69a1391d18.png)
This is the formatted code：
![image](https://user-images.githubusercontent.com/46048444/78966361-41c17480-7b32-11ea-9d21-f56cfb8b3a33.png)
I don't want to delete blank lines, can this code do it.
thanks!!!

**Comment by marijnh** [comment]
Autoformattting hasn't been part of this library for years, and as such bug reports about it can't be acted on anymore.

**Comment by RanX12** [comment]
Isn't it possible that I am manually triggering formatting?

**Comment by RanX12** [comment]
I manually trigger formatting ('autoFormatRange'), Then the format is successful, but I don't want to delete the blank line, can't be acted on anymore？

**Comment by RanX12** [comment]
My English is not very good, forgive me
