### ISSUE TITLE
How to set language syntax color

### ISSUE THREAD

**Issue by Haliiliya** [codemirror/CodeMirror#6216]
Hello, all I want is how to set the language for syntax color, for example, I want to set it to auto when I write javaScript and PHP code in the same textarea that automatically checking my code and styling syntax of each part of code inside textarea by language.

thanks.

**Comment by marijnh** [comment]
It sounds like you're talking about automatically detecting the language in the editor and setting the mode accordingly. That's not something the library supports (but you could build it yourself).
