### ISSUE TITLE
Let a mark (presentation span) fill its line height

### ISSUE THREAD

**Issue by AlexGustafsson** [codemirror/CodeMirror#6217]
![image](https://user-images.githubusercontent.com/14974112/79135507-af2e0900-7daf-11ea-81e8-36d01757bf32.png)

In the image above, `left` is marked using `markText`. Its background color is set to the gray color shown. Right of that text (and blue cursor), `right`, is selected using the cursor and styled using `.CodeMirror-selected`.

How come the height of the `presentation` span (`left`) is not the same height of the line itself?

I've set the line height using `.CodeMirror {line-height: 25px;}` as seen on other issues. 

I have not found any workaround or way for me to let each block fill the height of its line.

**Comment by marijnh** [comment]
> How come the height of the presentation span (left) is not the same height of the line itself?

That's how HTML and CSS work—the height of inline content depends on font and line height and probably other factors, and is rarely equal to the height of the entire line/block.

**Comment by marijnh** [comment]
In any case, I don't think the library can do anything about this, but careful tweaking of CSS rules might help.
