### ISSUE TITLE
In Chrome/80, Win 10, Entering the first space is normal, entering the second space is not normal, it will become 2 spaces, enter two spaces, the result is 3 spaces

### ISSUE THREAD

**Issue by RanX12** [codemirror/CodeMirror#6219]
Entering the first space is normal, entering the second space is not normal, it will become 2 spaces, enter two spaces, the result is 3 spaces.
The width of the tab or space becomes the width of 2 spaces.
This will only happen in Chrome, Win 10, I tested on Mac without any problems, Is there any solution?
My configuration is as follows:
![image](https://user-images.githubusercontent.com/46048444/79183584-6d9b6d80-7e44-11ea-800a-f8c5ac9b23cd.png)

**Comment by RanX12** [comment]
This will only happen in Chrome, Win 10

**Comment by RanX12** [comment]
Is there any solution?

**Comment by RanX12** [comment]
This will only happen in Chrome, Win 10, I tested on Mac without any problems, Is there any solution?

**Comment by RanX12** [comment]
The width of the tab or space becomes the width of 2 spaces

**Comment by marijnh** [comment]
Those are default options, and the tab and backspace bindings shouldn't be relevant when this is about the behavior of the space key. Is this happening for you in the demo on https://codemirror.net as well? I can't reproduce it there. So, if it doesn't occur there, the next step would be to reduce your setup to the minimum that still reproduces the issue in order to find out what is causing the different behavior.

**Comment by RanX12** [comment]
When I did the demo at https://codemirror.net/, there were no spaces and tabs wrong
 I click on the tab (tab), it presents 6 spaces, and pressing 4 times the space is also 6 spaces.  And it‘s 2 spaces in width, but only one space is actually counted

**Comment by RanX12** [comment]
I do n’t know where to fix this bug, please give me a hint, thank you.
If you have a win 10 computer and chrome browser, you can visit: https://www.showmebug.com can be reproduced here.

**Comment by marijnh** [comment]
> please give me a hint, thank you.

I did—simplify your setup until you figure out what is causing this. I'm not going to sift through a big production site to debug this, sorry.

**Comment by RanX12** [comment]
Thank you, I know, because the font library I set is not supported on Windows,Causes '&nbsp;' to render incorrectly
