### ISSUE TITLE
Character is prevented when hint is opened

### ISSUE THREAD

**Issue by Karthik15111996** [codemirror/CodeMirror#6220]
Hi Team,

I have rendered the hint option on pressing 'Shift+2'. While doing that I need to visible the '@' character also. And on replacement I need to replace the '@' character too. While sorting the hint the editor has to sort the hint list only base on the characters that I typed ommitting '@' character. Please guide me to achieve this.

**Comment by marijnh** [comment]
You can return `CodeMirror.Pass` from a keybinding function to opt out of preventing the default behavior.
