### ISSUE TITLE
Character to visible even hint is shown

### ISSUE THREAD

**Issue by Karthik15111996** [codemirror/CodeMirror#6221]
Hi Team,
Reference to the incident https://github.com/codemirror/CodeMirror/issues/6220,
As I mentioned in the previous incident, my requirement is both the pressed character and the show hint has to get visible. Currently, I'm using 'Shift+2' to show hint. While showing hint, the editor should also show the 'Shift+2' input (i.e '@' character to get included in the editor). But if I use CodeMirror.Pass command  as you mentioned in your comment in the previous incident, the hint option is not getting visible. please resolve this.

**Comment by marijnh** [comment]
These are not incidents nor issues. They are questions, which are better asked [on the forum](https://discuss.codemirror.net/).

You can probably work around this one by using `setTimeout`.
