### ISSUE TITLE
When i use CodeMirror.MergeView in react, i got diff_match_patch is not defined

### ISSUE THREAD

**Issue by wancun** [codemirror/CodeMirror#6222]
import DiffMatchPatch from 'diff-match-patch';
import CodeMirror from 'codemirror';

require('codemirror/lib/codemirror.css');
require('codemirror/theme/eclipse.css')
require('codemirror/theme/neat.css')
require('codemirror/addon/lint/lint.css')
require('codemirror/addon/merge/merge.css')
require('codemirror/mode/javascript/javascript')
require('codemirror/addon/lint/lint')
require('codemirror/addon/lint/javascript-lint')
require('codemirror/addon/merge/merge')

let container = document.getElementById('mergeArea');
    CodeMirror.MergeView(container, {
      origLeft: '123',
      origRight: '124',
      value: '',
      orig: '',
      lineNumbers: true,
      mode: 'xml',
      highlightDifferences: true
      });

package.json:
    "diff-match-patch": "^1.0.4",
    "codemirror": "^5.52.2",

**Comment by marijnh** [comment]
You need to load diff_match_patch, not diff-match-patch (they are different npm packages).

**Comment by wancun** [comment]
> You need to load diff_match_patch, not diff-match-patch (they are different npm packages).

Thanks!

**Comment by wancun** [comment]
> You need to load diff_match_patch, not diff-match-patch (they are different npm packages).

I have load diff_match_patch, but still got diff_match_patch is not defined.

+    "diff_match_patch": {
+      "version": "0.1.1",
+      "resolved": "https://registry.npmjs.org/diff_match_patch/-/diff_match_patch-0.1.1.tgz",
+      "integrity": "sha1-0/FNW3b7S1qc9EcGJh2ttb2X7bw="
+    },
