### ISSUE TITLE
[vim] The black hole register ( "_ ) is not handled correctly

### ISSUE THREAD

**Issue by ahirschberg-corp-oss** [codemirror/CodeMirror#6223]
In Vim, when writing to the black hole register (`_`), for example with `"_dd`, the default register should not be written to. Likewise, when reading from `_`, the default register should not be read from.

The CodeMirror behavior does not match this.
Tested on https://codemirror.net/demo/vim.html against VIM 8.1:

**VIM (expected)**:
* Issuing `"_dd`, then `p` will paste the whatever was in the default register before the `"_dd` command. 

**CodeMirror (actual)**:
* Issuing `"_dd`, then `p` will paste the deleted text from the `"_dd` command.

The docs on the black hole register can be found with `:help change` and searching "black hole". Web mirror for these docs is [here](https://vimhelp.org/change.txt.html#change.txt).

**Comment by ianhi** [comment]
I think a quick fix would be to add `_` to the list of valid registers:
https://github.com/codemirror/CodeMirror/blob/6fcc49d5321261b525e50f111f3b28a602f01f71/keymap/vim.js#L419

Then not actually treat it as a black hole, but I think this would fix the default register being written to. I think that if you pass a register that is not in the list of valid registers then codemirror vim will fall back on the default register
