### ISSUE TITLE
Subsequent text is not rendered after resized and refresh() with lineWrapping: true

### ISSUE THREAD

**Issue by ktsn** [codemirror/CodeMirror#6228]
## Reproducible Environment

- CodeMirror: v5.52.2
- Browsers
  - Chrome: 80.0.3987.163
  - Firefox: 75.0
  - Safari: 13.1 (15609.1.20.111.8)
- OS
  - macOS 10.15.4

## Reproduction

https://jsfiddle.net/ktsn/aur7wt3L/14/

1. Open the page.
2. Scroll the editor slowly for the bottom.
3. The text after `*************************************` is not rendered even though it is in viewport.
    
    ![image](https://user-images.githubusercontent.com/2194624/79446755-5cec2280-8011-11ea-814f-8605b744bfd7.png)

4. Scroll further and the text will be rendered.

### Expected behavior

The text should be rendered at step 3 where the text is in viewport.

## Details

This issue happens when we:

1. set `lineWrapping: true`,
2. had set text in narrower width and
3. set width wider and call `refresh()` after 2.

Looks like height is calculated for each line on 2 and the value is too large as width is small at the moment, then even though we `refresh()` on 3, the height of lines are not updated.

**Comment by marijnh** [comment]
`refresh` was incorrectly preserving some cached line heights. Attached patch should help.

**Comment by ktsn** [comment]
Thank you for the quick patch!
