### ISSUE TITLE
listening to 'enter' keypress prevents default behavior

### ISSUE THREAD

**Issue by working-name** [codemirror/CodeMirror#6229]
## Description
It seems this was an issue for v3.1 and `return` was implemented, but both the latest (5.52.2) and github versions behave the same way when listening for `enter` key presses: default behavior is suppressed.

The main reason for using this is to do line processing *before* contents are changed as a result of pressing `enter`.

```js
21-02-2013: Version 3.1:

    Incompatible: key handlers may now return, 
rather than throw CodeMirror.Pass to signal they didn't handle the key.
```

Affects: Chrome, Firefox, Safari.

## Expected behavior
When either `CodeMIrror.Pass` or `return` is passed, CodeMirror should carry on doing what it normally does.

## Fiddle
https://jsfiddle.net/fcs5qugv/

## What I tried so far

1. Use `ExtraKeys`
2. Use `.on("keydown"`

#### Failed strategies:
1. `return true/false/CodeMirror.Pass`
2. `return`
3. `$(document).keypress(event)` -- removes ^\s* line, and still doesn't insert a newline
4. `$(document).keypress($.event.fix(event))` same as above, with some extra jQuery errors

## Current workaround

I found this in a StackOverflow post which works but I can't remember which browser was still misbehaving.

```js
CodeMirror.replaceSelection("\n" ,"end")
```

**Comment by marijnh** [comment]
I think you're misreading that release note. You should do `return CodeMirror.Pass`, not just `return`.

**Comment by working-name** [comment]
Well that's not awkward at all 😬. Thank you!
