### ISSUE TITLE
Allow mapping Escape (<Esc>) key in vim normal mode

### ISSUE THREAD

**Issue by MrQubo** [codemirror/CodeMirror#6234]
Trying to map `<Esc>` key with `map()` or `mapCommand()` doesn't do anything. Mapping it in insert or visual mode doesn't really make much sense but it should be possible to map it in normal mode.

Changing [`handleEsc()`](https://github.com/codemirror/CodeMirror/blob/87aaaed6649bad36218faded697dd69ee18c4850/keymap/vim.js#L881-L892) to below code might be enough to fix this.
```js
function handleEsc() {
  if (key == '<Esc>') {
    // Clear input state and get back to normal mode.
    if (vim.visualMode) {
      clearInputState(cm);
      exitVisualMode(cm);
      return true;
    } else if (vim.insertMode) {
      clearInputState(cm);
      exitInsertMode(cm);
      return true;
    }
  }
}
```

**Comment by xeruf** [comment]
Then submit a PR :)

**Comment by MrQubo** [comment]
> Then submit a PR :)

Thanks! I did that.
