### ISSUE TITLE
Imap to insert text on keystroke

### ISSUE THREAD

**Issue by CrashLaker** [codemirror/CodeMirror#6236]
Hi all. 

I'm struggling on trying to insert text on imap. Can anyone help me?

I'm trying to `:imap pp ="```<CR>```"<CR>`

In short I want to output

    ```[]

    ```

as soon as I type `pp` with the caret positioned at []

thanks

**Comment by marijnh** [comment]
This really isn't the place for support requests.

I assume you're talking about the vim bindings, but those aren't really maintained very actively anymore, so I don't even know how you'd get what you're describing and whether that is supported at all.

**Comment by CrashLaker** [comment]
ok sorry
