### ISSUE TITLE
How to resolve not showing lint message sometimes

### ISSUE THREAD

**Issue by liuliangsir** [codemirror/CodeMirror#6240]
As the above title says, I have been running into the issue above for some time. After google search and debugging, I find that the wrapped [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) is the source of evil. you might say that why don't you get rid of the wrapped [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function). It's because that we need to add lint support for experimental syntax([top-level-await](https://github.com/tc39/proposal-top-level-await)) to JavaScript code inside [CodeMirror](https://codemirror.net) . However, [babel-eslint](https://github.com/babel/babel-eslint)  doesn't officially support browser targets. Therefore the wrapped async function is an awkward workaround.

[Here](https://github.com/liuliangsir/codemirror-lint-eslint) is a minimal reproducible example, And the following is some code snippet.

```javascript
import isNil from 'lodash/isNil'
import linterModule from 'eslint/lib/linter/linter'
import defaultEslintConfig from '../assets/json/eslint.json'

const Pos = CodeMirror.Pos
const linter = new linterModule.Linter()

function validator(text, options) {
  const result = []
  if (!text) return result

  const wrappedText = `async () => {\n${text}\n}`
  const config = defaultEslintConfig
  const errors = linter.verify(wrappedText, {
    ...config,
  })
  for (let i = 0; i < errors.length; i++) {
    const error = errors[i]

    result.push({
      message: error.message,
      severity: getSeverity(error),
      from: Pos(error.line - 1 - 1, error.column - 1),
      to: Pos(
        isNil(error.endLine) ? error.line - 1 - 1 : error.endLine - 1 - 1,
        isNil(error.endColumn) ? error.column : error.endColumn - 1,
      ),
    })
  }

  return result
}
```
Here are a bunch of GIFs.

![CodeMirror_-Linter-Demo-Google-Chrome-2020-04-22-14-58-44](https://user-images.githubusercontent.com/8049878/79951256-f05aa300-84aa-11ea-8d54-6a9fff70cd03.gif)

**Comment by marijnh** [comment]
Is this really a CodeMirror issue? Can it be reproduced without involving ESLint?

**Comment by liuliangsir** [comment]
It can't be reproduced without involving ESLint. It's because that I have been using ESLint to lint JavaScript code inside CodeMirror. After debugging, I find that removing the right-most close curly get type text. Here are some code code snippet from CodeMirror source code.
```javascript
  function updateLineForChanges(cm, lineView, lineN, dims) {
    for (var j = 0; j < lineView.changes.length; j++) {
      var type = lineView.changes[j];
      if (type == "text") { updateLineText(cm, lineView); }
      else if (type == "gutter") { updateLineGutter(cm, lineView, lineN, dims); }
      else if (type == "class") { updateLineClasses(cm, lineView); }
      else if (type == "widget") { updateLineWidgets(cm, lineView, dims); }
    }
    lineView.changes = null;
  }

```

**Comment by marijnh** [comment]
Then I guess this was filed in the wrong project. We don't maintain any eslint integration.
