### ISSUE TITLE
If inputStyle is "contenteditable", then the input element created by markText function will lose the focus while typing.

### ISSUE THREAD

**Issue by shd101wyy** [codemirror/CodeMirror#6242]
Please see the jsfiddle here as an example: https://jsfiddle.net/zjp6bh5t/
If inputStyle is "contenteditable" then when you type something in the input element, the cursor will jump out.
But If inputStyle is 'textarea" then it works fine. 
Any suggestions how to fix it?
Thank you!

**Comment by marijnh** [comment]
Good point. Attached patch should help.

**Comment by shd101wyy** [comment]
@marijnh Thank you very much for the help!!! 👍🤓

**Comment by shd101wyy** [comment]
Hi @marijnh , I am sorry to bother you again.
I just tried your patch, the focus won't be lost now. 
However, when I type something in the input element, I can only enter one character at a time. The input element will `blur` first then `focus` again. And I will have to click at the input element before I can continue typing.

For example, in the gif below I was trying to type `abc`. However, I initially typed `a`. Afterwards I typed `b`, it won't won't occur in input element. I will have to click the input element again then type `b` to get it work.

![Peek 2020-04-29 16-12](https://user-images.githubusercontent.com/1908863/80574423-61aece80-8a34-11ea-94a1-e2498915a82f.gif)

Any suggestions? Thank you very much!

**Comment by marijnh** [comment]
Oh, good point. It worked fine on Firefox, but due to the library moving the selection after focusing the input, Chrome seems to stop text input, despite focus still being on the element. Attached patch should help.

**Comment by shd101wyy** [comment]
Awesome. I just tried the new patch and it works perfectly!
Thank you very much for the help!!! :)

**Comment by shd101wyy** [comment]
Hi @marijnh , sorry I encountered another small problem 😂.
After I copied some text and tried to `ctrl-v` to paste in the input element, the pasted content goes outside the input element.

![Peek 2020-04-30 23-07](https://user-images.githubusercontent.com/1908863/80726778-6d36ee00-8b37-11ea-8dd8-194fef76231d.gif)

> The application above is at https://crossnote.app . You could press `/image` in editor to create the input box shown in the gif above.

Thank you very much for all your kind helps!

**Comment by marijnh** [comment]
Ah, clipboard events bubble too. See attached patch.

**Comment by shd101wyy** [comment]
Thank you! Just confirmed that it works well ;)
