### ISSUE TITLE
Minified distribution

### ISSUE THREAD

**Issue by snimavat** [codemirror/CodeMirror#6243]
The released zip, which is also linked from the main codemirror site contains whole source code and every thing, there is no minified distribution. It would be a great help if there is a minified distribution for core and minified js files for each mods.

Documentation says to include lib/codemirror.js -- but the zip does not contain the file in lib directory

**Comment by marijnh** [comment]
No, I consider that out of scope for the distribution. It's easy enough to run your own minifier and/or bundler on the provided sources.
