### ISSUE TITLE
Scroll position jumps when click on multi-line selection in nested inline editor ( body contenteditable = true))

### ISSUE THREAD

**Issue by zTree** [codemirror/CodeMirror#6246]
Step:
1. Inside the inline editor, select from the start of line 1 to the end of line 14
2. click on the any line of selection 

I found that this issue was caused by fixing the code of #3081
'display.wrapper.ownerDocument.body.focus();' will change the scroll position at first.

code in codeMirror :
```
// Work around unexplainable focus problem in IE9 (#2127) and Chrome (#3081)
if (webkit || ie && ie_version == 9)
  { setTimeout(function () {display.wrapper.ownerDocument.body.focus(); display.input.focus();}, 20); }
else
  { display.input.focus(); }
```
now， please remove the ‘webkit’ in the ‘if...' 
```
if (ie && ie_version == 9)
  { setTimeout(function () {display.wrapper.ownerDocument.body.focus(); display.input.focus();}, 20); }
else
  { display.input.focus(); }
```
When I remove the 'webkit', I don't find the issue of #3081 in Chrome.

test case: [https://jsfiddle.net/dyhunter/x6wf9ph3/24/](https://jsfiddle.net/dyhunter/x6wf9ph3/24/)
test code:
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>CodeMirror line widget / wordwrap issue</title>
        <script src="https://codemirror.net/lib/codemirror.js"></script>
        <link rel="stylesheet" href="https://codemirror.net/lib/codemirror.css">
    </head>
    <body contenteditable="true">
    <div id="text-a"  style="line-height:2">
      test-a
    </div>
     
    <div id="code"></div>
    
    <div id="text-b"  style="height:800px;">
      test-b
    </div>  
    
     <script>
var textA = document.querySelector('#text-a');
textA.style.height = (document.documentElement.clientHeight - 80) + 'px';


var content = "";
for (var i = 1; i <= 20; i++) {
  content += "line " + i + "\n";
}

var cmEditor = CodeMirror(document.getElementById("code"), {
  lineNumbers: true,
  value: content
});

     </script>
    </body>
</html>
```

**Comment by marijnh** [comment]
The Chrome bug linked in the old issue still exists, so I don't want to disable this workaround. I think attached patch should address the problem.

**Comment by zTree** [comment]
Hi, @marijnh 

However, you don't want to consider fixing the problem in this case (contenteditable = true)?

**Comment by marijnh** [comment]
Did you try with my patch (e8c0a77)? Because your demo no longer shows the problem with that change.

**Comment by zTree** [comment]
Thanks very much.  I didn't see your commit (e8c0a77).   This patch works well!  I closed my pull request.

**Comment by zTree** [comment]
@marijnh 

Sorry, I find your patch is works well in chrome and  firefox. But, scroll position still jumps in safari.

test page: http://treejs.cn/wiz/code/error.html
When you click, you can see the scroll jumps up to the top and immediately jumps down to the code.

Reference:  https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus
The Safari don't support 'preventScroll' options.

**Comment by marijnh** [comment]
Ahh, I see. What if we just change the test for the workaround from `webkit` to `chrome`?

**Comment by zTree** [comment]
I think it might be safer to keep the current logic and just exclude safari.

**Comment by marijnh** [comment]
See attached patch.

**Comment by zTree** [comment]
Thanks. Now, it works well.
