### ISSUE TITLE
[matchBrackets] addon highlights the bracket even if input is not focused.

### ISSUE THREAD

**Issue by BlueSpider929** [codemirror/CodeMirror#6252]
`matchBrackets` addon now highlights the last function bracket even if input is not focused.
<img width="394" alt="image" src="https://user-images.githubusercontent.com/29029/79735711-5c99a300-8301-11ea-8816-d9ee419d395f.png">

**Comment by BlueSpider929** [comment]
I suggest defining new function called `clearMatchBrackets` inside `matchbrackets.js`.
https://github.com/codemirror/CodeMirror/blob/a67ed9a4ab810b1630e7d698362a3a33c96ca024/addon/edit/matchbrackets.js#L110
```
function doMatchBrackets(cm) {
    cm.operation(function () {
      if (cm.state.matchBrackets.currentlyHighlighted) {
        cm.state.matchBrackets.currentlyHighlighted();
        cm.state.matchBrackets.currentlyHighlighted = null;
      }
      cm.state.matchBrackets.currentlyHighlighted = matchBrackets(cm, false, cm.state.matchBrackets);
    });
  }

/***********************/
/** New Function Here **/
/***********************/
function clearMatchBrackets(cm) {
    cm.operation(function () {
      if (cm.state.matchBrackets.currentlyHighlighted) {
        cm.state.matchBrackets.currentlyHighlighted();
        cm.state.matchBrackets.currentlyHighlighted = null;
      }
    });
  }
```

And then add event handlers for `blur` and `focus` to handle bracket highlighting properly.
https://github.com/codemirror/CodeMirror/blob/a67ed9a4ab810b1630e7d698362a3a33c96ca024/addon/edit/matchbrackets.js#L130
```
...
cm.on("cursorActivity", doMatchBrackets);

/****************************/
/** New Event Handler Here **/
/****************************/
cm.on("blur", clearMatchBrackets);
cm.on("focus", doMatchBrackets);
```

**Comment by marijnh** [comment]
Good idea. Implemented in attached patch.
