### ISSUE TITLE
[JavaScript] optional chaining operator breaks highlight

### ISSUE THREAD

**Issue by tophf** [codemirror/CodeMirror#6255]
I see it's [added](https://github.com/codemirror/google-modes/issues/283) to the next CodeMirror but what about 5.xx?

Currently, using `?.` will break highlighting in seemingly unpredictable ways as seen in the official demo when adding `?.test` after `context` in line 13:

![gif](https://puu.sh/FEMwM/cba5b335ce.gif)

**Comment by marijnh** [comment]
Are you testing with the current master branch? Because I believe I added this last week.

**Comment by tophf** [comment]
No, I tested the official demo (the screenshot) and the latest release.

**Comment by marijnh** [comment]
Try a hard refresh? For me, `obj` on the line below stays blue when I add the property.

**Comment by tophf** [comment]
Retried now with hard refresh in three different browsers as well as tried the master branch locally => still seeing the bug. I'm talking about CodeMirror 5.xx, not the next big thing.

**Comment by marijnh** [comment]
Ah, don't mind me, I had implemented (and was testing) a `.?` operator, instead of a `?.` one. Attached patch should help.
