### ISSUE TITLE
Import all themes and modes with single import

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [codemirror/CodeMirror#6260]
I wanted to import all the themes and modes into my Reactjs project with a single import statement.
I might be missing something but is this possible or importing them individually is the only option?

When I try to import the entire folder with `import "codemirror/theme"` it gives me an error.

**Comment by marijnh** [comment]
That's not something that's supported. (Importing from multiple files at once, or importing css files, doesn't exist in JavaScript, so I guess you're using some kind of bundler that adds support for that, but this project doesn't contain any specific integration for such a thing.)
