### ISSUE TITLE
How to setCursor without focusing?

### ISSUE THREAD

**Issue by jemikanegara** [codemirror/CodeMirror#6261]
Is there any way to set the cursor without focus? I need this feature because I want to prevent user editing the first line (but it must be modified programmatically, I already tried the onBeforeChange and prevent this line from editing and it block programmatically modifying too)

So basically the flow is like this: 
User filling an input field -> template updated with replaceRange -> I want this cursor to be automatically go to end when focused **only when I do this specific operation** (I do have another replacing operations and I don't want user to go to the end of line everytime they click/focusing on template)

**Comment by marijnh** [comment]
I do not understand how the use case described is related to focusing. In any case, this is the bug tracker for the project, and this is not a bug report. Try the [forum](https://discuss.codemirror.net/).
