### ISSUE TITLE
Performance of different scrollbar implementation

### ISSUE THREAD

**Issue by dvkndn** [codemirror/CodeMirror#6262]
Does ["native"](https://github.com/codemirror/CodeMirror/blob/master/src/display/scrollbars.js) have better performance than ["simple"](https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/simplescrollbars.js) or "overlay"?

From reading the code, I understand that:
- No work is done for "null" implementation
- There are significant works needed for "native" implementation

The code for "simple" seems to be even simpler than "native" but I can't tell if it's better in term of performance or not. Can someone give an insight :D

**Comment by marijnh** [comment]
None of them should be any kind of performance hazard. They don't do anything costly.

**Comment by dvkndn** [comment]
Thank you!
