### ISSUE TITLE
Markdown highlights do not handle whitespace

### ISSUE THREAD

**Issue by calculuschild** [codemirror/CodeMirror#6264]
Text in the editor is styled to match the emphasis. However, this doesn't work when a leading or trailing whitespace is included within the emphasis markers:

![image](https://user-images.githubusercontent.com/5878534/81436408-70ce0480-9137-11ea-843d-c9445a5fd14e.png)

**Comment by marijnh** [comment]
This corresponds to how CommonMark is defined. (Try it out [here](https://spec.commonmark.org/dingus/), for example.)

**Comment by marijnh** [comment]
Ah, that thing on commonmark.org appears to be broken, but you can see the same in github's parser:

** Bold?** Nope
