### ISSUE TITLE
🐞: Blinking cursor does not sync with the change font size

### ISSUE THREAD

**Issue by joe733** [codemirror/CodeMirror#6266]
As mentioned in [this issue](https://github.com/PMunch/nim-playground-frontend/issues/16).  When I increase the font size, the cursor remains in the same size unless I start to type (feels awkward at first).
![home](https://user-images.githubusercontent.com/38415384/81492945-da761c00-92b9-11ea-9778-cc74898afb42.png)
That cursor in the circle after in is actually at the last line because when I type the cursor automatically moves to the last line and does the editing. I hope I'm knocking the correct door this time :)

**Comment by marijnh** [comment]
You have to call the `refresh` method after changing editor-relevant CSS (there's no solid way, in the browser, for the library to automatically notice this).
