### ISSUE TITLE
adding colon in the editor changes the color of all words before it

### ISSUE THREAD

**Issue by vighnesh153** [codemirror/CodeMirror#6270]
Adding a colon in the editor changes the colour of all words before it on that line, except the first one, to default colour.

Expected (the following colours should not be lost:
![expected](https://user-images.githubusercontent.com/26544566/81767545-48a72280-94f6-11ea-86c8-a048fe37b13c.PNG)

Actual (as soon as I add a colon, it changes the colours to default):
![actual](https://user-images.githubusercontent.com/26544566/81767619-7c824800-94f6-11ea-9eb9-2fb9d7dbc98f.PNG)

And adding any non-whitespace character after the colon fixes it. But, in the language that I am using, there should not be any non-whitespace character after the colon.

Following is the config I am using:
```
CodeMirror.defineSimpleMode("simplemode", {
    start: [
        {regex: /'(?:[^\\]|\\.)*?(?:'|$)/, token: "string"},
        { regex: new RegExp(`(?:${keywords.join('|')})\\b`), token: 'atom' },
        {regex: /[-+\/*=<>!]+/, token: "operator"},
        {regex: /0x[a-f\d]+|[-+]?(?:\.\d+|\d+\.?\d*)(?:e[-+]?\d+)?/i, token: "number"},
        {regex: /(.*)(:\s*)$/, indent: true},
        {regex: /^\s*((break\s*)|(continue\s*)|(return( .*)?))$/, dedent: true},
    ]
});


const editor = CodeMirror.fromTextArea(
    document.getElementById('code-area'),
    {
        lineNumbers: true,
        theme: 'material-ocean',
        indentUnit: 4,
        autofocus: true
    }
);
editor.setSize("100%", "100%");
```

How do I fix this?

**Comment by marijnh** [comment]
The rule `{regex: /(.*)(:\s*)$/, indent: true}` matches anything followed by a colon. If that's not what you want I guess you'll need to adjust your regexp.

**Comment by vighnesh153** [comment]
It accepts only whitespace characters. But that is for indentation right? How does that change the color of keywords?

**Comment by marijnh** [comment]
The `.*` part matches anything, not just whitespace, so it'll match right at the start of the line and consume the entire line up to the colon.

**Comment by vighnesh153** [comment]
Right. But I am still confused on how it changes the color of the keywords when it is targetted for indentation?

**Comment by vighnesh153** [comment]
Removing that part fixed the issue.
