### ISSUE TITLE
regex vulnerable to regex dos

### ISSUE THREAD

**Issue by ajinabraham** [codemirror/CodeMirror#6273]
This regex https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js#L461
`cx.stream.match(/^([^>]|<.*?>)*>\s*\(/, false)` is vulnerable to catastrophic backtracking and can result in regular expression dos.
see: https://regex101.com/r/nu659M/1

**Comment by marijnh** [comment]
Do you have an example of an input that causes the problem? It looks pretty much linear to me (the choice in the parentheses is unambiguous, and the ? after the `.*` will prevent any overmatching there).

**Comment by ajinabraham** [comment]
You can see that the input with large no of >< is causing a timeout here https://regex101.com/r/nu659M/1

**Comment by marijnh** [comment]
Ahh, the inner `<.*?>` ends up matching (with the outer `*`) in an exponential way. Attached patch fixes that.

**Comment by sahandilshan** [comment]
Is this issue fixed now?
