### ISSUE TITLE
👁Ꙭ👀🦉CodeMirror-Editing-state Vision❔❓

### ISSUE THREAD

**Issue by dnknn** [codemirror/CodeMirror#6276]
💡 This question is not important, just to talk about it, Only consider it if it is easy to implement without affecting the performance of CodeMirror .

### CodeMirror Editing state of vision👁Ꙭ👀🦉 ❔❓
✍Line indicator being edited(Has not been saved)
✍+💾Just edited but saved(🖫<kbd>Ctrl</kbd>+<kbd>S</kbd>).
🔄 F5🗘Refresh page, These line styles will disappear.
![80799330-2b5e8400-8bd9-11ea-9544-3edd358ed635 png (925×460)](https://user-images.githubusercontent.com/10995302/81989137-44524500-966f-11ea-89d3-91125c2487be.png)

⏺⛶🎬 Gif REC Demo:
![80800451-133c3400-8bdc-11ea-9feb-b30b94901ce4 gif (914×503)](https://user-images.githubusercontent.com/10995302/81988923-d73eaf80-966e-11ea-8a47-7d3d6a931c47.gif)
⚠Recommend 2 extensions about GIF playback control.
GIF Player - https://chrome.google.com/webstore/detail/gif-player/alhgepkoeafgfdfonlclgphnedliblpf
GIF Scrubber - https://chrome.google.com/webstore/detail/gif-scrubber/gbdacbnhlfdlllckelpdkgeklfjfgcmp

**Comment by marijnh** [comment]
These are out of scope for the core library (though I think the activeline addon might cover the first one), but it shouldn't be hard to implement them in external code.
