### ISSUE TITLE
👁Ꙭ👀🦉CodeMirror-Bookmark Vision❔❓

### ISSUE THREAD

**Issue by dnknn** [codemirror/CodeMirror#6277]
💡 This question is not important, just to talk about it, Only consider it if it is easy to implement without affecting the performance of CodeMirror .

🖮<kbd>Ctrl</kbd>+<kbd>F2</kbd>  Add/Del bookmark📑;
🖮<kbd>F2</kbd>/<kbd>Shift</kbd>+<kbd>F2</kbd>  Bookmark jump. It can be used to quickly jump the cursor position, it is very useful!
🖮<kbd>Alt</kbd>+<kbd>F2</kbd>  Can be used for multi-point editing, Equal to Ctrl+click/::selection to enter multi-point editing mode.

The bookmark is not visible visually. So see if it is necessary?:
📑For a bookmarked line, add a icon(e.g.🠶) in its [class="CodeMirror-gutters"] area.
There can be multiple bookmarks in a line, this does not affect.
Specific effect plan diagram:
![80796885-f5b69c80-8bd2-11ea-9ebb-26493eb2db56](https://user-images.githubusercontent.com/10995302/81989337-a8750900-966f-11ea-8d85-22e6bfa789e8.png)

⏺Gif Demo:
![80798541-357f8300-8bd7-11ea-9ffa-eb09ea5b34ba](https://user-images.githubusercontent.com/10995302/81989381-b9257f00-966f-11ea-8049-d527f232c373.gif)
⚠Recommend 2 extensions about GIF playback control.
GIF Player - https://chrome.google.com/webstore/detail/gif-player/alhgepkoeafgfdfonlclgphnedliblpf
GIF Scrubber - https://chrome.google.com/webstore/detail/gif-scrubber/gbdacbnhlfdlllckelpdkgeklfjfgcmp

**Comment by marijnh** [comment]
The sublime bindings have some bookmark functionality, though I don't think it matches what you're describing exactly. You could implement this in external code, but I'm not interested in adding more things like that to the core.
