### ISSUE TITLE
[match-highlighter] scrollbar match display doesn't handle leading or trailing special regex chars properly

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#6279]
The regex at
https://github.com/codemirror/CodeMirror/blob/master/addon/search/match-highlighter.js#L93
doesn't handle leading/trailing special characters such as `$` properly; a highlighted variable `$FOO` will result in the regex `\b\$FOO\b`, which doesn't match `$FOO` since there's no word boundary on the left side of the `$` in `$FOO`.

**Comment by marijnh** [comment]
Does conditionally adding the `\b` parts only when the character on that side of the word matches `\w` sound like a good solution?

**Comment by takamori** [comment]
That was my immediate thought, but I figured it would be better for you to
look at it.
