### ISSUE TITLE
Feature request: events on vim mode changes

### ISSUE THREAD

**Issue by peey** [codemirror/CodeMirror#6284]
I wanted to make a simple customization to code mirror -- disabling blinking cursor when in normal mode and enabling it in insert mode. For this, I tried to look through events and vim mode API sections.

I'm aware that my use case can be implemented in other ways -- by hijacking keys which take you between visual, insert and normal modes.

But I think having event hooks for when editor enters one of these could be better and can perhaps have other use cases.

**Comment by benhormann** [comment]
The event you are asking for is called `vim-mode-change`, mentioned on line 21 of keymap/vim.js.
```
cm.on('vim-mode-change', ({ mode, subMode }) => {
  /* make magic happen */
});
```

**Comment by peey** [comment]
@benhormann that's great! Then I think we should just update the user manual and then we could close this issue.
