### ISSUE TITLE
Difference between htmlembedded and htmlmixed

### ISSUE THREAD

**Issue by ultramustang** [codemirror/CodeMirror#6287]
I want to know the difference between the modes `htmlembedded` and `htmlmixed`. They are both HTML modes, but I don’t know which one to use. **Please help!**

**Comment by marijnh** [comment]
This is the bug tracker, it's not the right place for questions. Try the [forum](https://discuss.codemirror.net/) instead.

But in this case, just reading the mode descriptions ([htmlmixed](https://codemirror.net/mode/htmlmixed/), [htmlembedded](https://codemirror.net/mode/htmlembedded/)) would probably have been enough to answer your question.
