### ISSUE TITLE
shell-session language mode (syntax highlight) support please

### ISSUE THREAD

**Issue by sgon00** [codemirror/CodeMirror#6290]
Something like the following screenshot from prismjs:

![Screenshot-6](https://user-images.githubusercontent.com/1555508/82860485-60e25d00-9f4c-11ea-9236-e1dec0970a8b.png)

If the `stdout` can be a different color (more gray) from the arguments at the command line will be great. 

Thanks a lot.

**Comment by marijnh** [comment]
We're not adding new modes to the main distribution except in rare circumstances. If you want this, you'll have to implement it yourself and distribute it separately.

**Comment by sgon00** [comment]
@marijnh thanks a lot for the quick reply. Can I ask why codemirror is not adding new modes except in rare circumstances? Is codemirror not an active project? Thanks.
