### ISSUE TITLE
URLForMode callback along with modeURL

### ISSUE THREAD

**Issue by tolmasky** [codemirror/CodeMirror#6294]
I have my modes compiled with shasums attached that way I can serve them as immutbale resources (so for example /javascript/javascript-sha256-23958394893040blahblah). This makes the current replacement-based `modeURL` system difficult to use for dynamically loading modes. I actually currently get away with passing in a fake string object that has a replace method:

```javascript
CodeMirror.modeURL = { replace: (_, mode) => lookupComplexURLForMode(mode) };
```

While this works **today**, it is certainly not ideal as I have to rely on knowledge that replace() gets called. Having `modeURL` accept a function, or a separate `URLForMode` option for a callback that returns the URL given a mode would make my code more future-proof.

**Comment by marijnh** [comment]
Does the `path` option from attached patch help?

**Comment by marijnh** [comment]
Great!
