### ISSUE TITLE
Support WebWorkers (with importScripts) in loadmode

### ISSUE THREAD

**Issue by tolmasky** [codemirror/CodeMirror#6295]
I currently have a hacked together version of loadmode to support WebWorkers. For a fool-proof solution to properly set the env variable, I am thinking maybe just keying off of `typeof importScript !== "undefined"`.  I actually think it would be nice to just be able to set the loadmode loader to future-proof this (it would have allowed me to just configure loadmode to use `importScripts` vs. modifying it). This could either happen at the callsite (and then have dependency loads "inherit" the load callback), or it could alternatively just be configured once like through `CodeMirror.import`. The signature would be something like `load(URL, cont)`. So for my case it would have been:

```javascript
CodeMirror.requireMode.load = function loadUsingImportScripts(URL, cont)
{
    importScripts(URL);
    cont();
}
```

If we were OK with using promises we of course would not need the `cont` passed to it, but I think the goal is to not need a promise library. Internally, loadmode would just be a consumer of this API by default, something like `CodeMirror.requireMode.load = CodeMirror.requireMode.DefaultLoaders[env]`;

**Comment by marijnh** [comment]
What is the goal of loading modes in a web worker, though? You won't be able to run them in an editor (unless I'm missing something).

**Comment by tolmasky** [comment]
We use CodeMirror modes to syntax highlight various pieces of uneditable source on our page. Everything from snippets in our error viewer:

<img width="1023" alt="hero" src="https://user-images.githubusercontent.com/23753/83062992-54293c00-a014-11ea-8c03-99f6a18a874b.png">

To entire files in our package inspector:

<img width="1392" alt="Screen Shot 2020-05-27 at 12 20 31 PM" src="https://user-images.githubusercontent.com/23753/83063104-7de26300-a014-11ea-852d-b3cec3e0a6a8.png">

The reason we use CodeMirror modes instead of something like highlight.js is so that we can have the same styles both in our editor as well as in static code that we show. As such, we actually use runmode in **3 different environments**:

1. We will attempt to render the code statically on the server (runmode.node.js), but we allot a time budget to this. So if it times out, we send the **unrendered** code to the client, with a script tag that loads up CodeMirror and attempts to render it locally.
2. Locally, it will test for the presence of WebWorkers. If they exist, the text will be sent to a worker that has runmode on it, dynamically loads the right mode, syntax highlights, then send the rendered content back to the main page. This is ideal because it doesn't block the main thread on a file we know to take a long time to render since it timed out on the server.
3. If WebWorkers **aren't** present, then it uses script tag loading of modes and the file is syntax highlighted synchronously.

**Comment by marijnh** [comment]
It seems like it might be easier to ignore `loadmode` and wire something up yourself. In the end, the only relevant thing it does is determine the mode's url, which is pretty trivial (and, given #6294, apparently something you want to do differently anyway), and load a mode's dependencies, which you might also use the UMD header for (by setting up a require or define function in your web worker).

**Comment by tolmasky** [comment]
So, we already have this code working, and as I showed up above, the "non-generic" version requires a 3 line change to support WebWorkers out of the box, including loading up dependencies, which allows us to avoid creating a parallel version of that code. It is really nice that we currently have one script that works in all three environments, as opposed to having three distinct entrypoints that are all trying to do very similar things. It's basically the same argument for having script tag and require handled automatically as opposed to just letting users figure out how to call require themselves in node.

I don't think #6294 should influence this decision since we need it in the existing script tag loading mode as well (#6294 is just solving the problem of string replacement not being sufficiently powerful enough to tell CodeMirror where to look for the files). By attaching the checksum of the mode to the file name itself I can just use forever caching completely safely as opposed to choosing arbitrary caching durations for these files and occasionally running into situations where users have to empty their caches and refresh if they happen to have a stale copy. 

Anyways, in case it wasn't clear, in both cases we already have code forked internally that does this, and we figured it would be useful to contribute. With a little bit of work on our end we could make it useful to everyone to varying degrees (hence me asking whether simply adding the importScripts method or making it so you can pass your own). However, I totally understand if you specifically want to avoid web worker use cases. We are happy to continue using our fork and feel free to close these bugs.

**Comment by marijnh** [comment]
How does the attached patch look to you?
