### ISSUE TITLE
Incomplete definitely typed factory function

### ISSUE THREAD

**Issue by ChrisLincoln** [codemirror/CodeMirror#6298]
The "place" arugment to CodeMirror(place..) is typed as either an HTMLElement or callback function, but does not allow null, even though the code permits it.

I am actually porting a chunk of the ProseMirror "embed CodeMirror" sample using TS, and ran up against it with this [line of code:
](https://github.com/ProseMirror/website/blob/f8a542cd45601820ade7e4e250880a43d02b1e82/example/codemirror/index.js#L26-L30)
```
    this.cm = new CodeMirror(null, {
      value: this.node.textContent,
      lineNumbers: true,
      extraKeys: this.codeMirrorKeymap()
    })
```

I'd gladly PR it, but I don't really  know how/who owns the process.

**Comment by marijnh** [comment]
I don't have anything to do with the definitelytyped types for CodeMirror—you could try submitting a pull request there, or check who wrote them with `git blame` and communicate with them.
