### ISSUE TITLE
Zero-width non-joiner is rendered as a red dot (unrenderable)

### ISSUE THREAD

**Issue by amirography** [codemirror/CodeMirror#6303]
The zwnj character which is used extensively in Persian and Arabic texts, is rendered as a red dot. 

Here is how it should look:
می‌نویسم
Here how it renders:
![IMG_20200602_084124](https://user-images.githubusercontent.com/28535608/83479140-f762d100-a4ac-11ea-8458-70cfb237e8ba.jpg)
You can reproduce it by copy and pasting this: "‌"

**Comment by marijnh** [comment]
This has been fixed last week in 2571b4ad08e007 . It'll be gone in the next release.

**Comment by WhiteNoise-Dev** [comment]
This still happens in 5.59.2

**Comment by marijnh** [comment]
My bad, I didn't see the _non_ part, and assumed this was about zero-width joiners. Attached patch also removes this character from the default set of special characters.

**Comment by WhiteNoise-Dev** [comment]
Thanks!
