### ISSUE TITLE
"-->" character sequence is highlighted as a comment in some languages

### ISSUE THREAD

**Issue by FArekkusu** [codemirror/CodeMirror#6305]
Issue initially reported [here](https://github.com/codewars/codewars.com/issues/2164) in a project which uses CodeMirror.

___

The `-->` character sequence is highlighted as a comment in some languages (at least JavaScript and TypeScript) despite being a post-decrement operator in front of a greater-than operator.

A trivial example reproducible in [JavaScript mode](https://codemirror.net/mode/javascript/):

```
let n = 10;
while (n -->) console.log(n);
```

**Comment by marijnh** [comment]
Ah hold on, you have a missing zero in the example code, which is the actual reason it won't run like that.

**Comment by marijnh** [comment]
Seems that the `-->` comment may only occur at the start of a line. Attached patches implement that.
