### ISSUE TITLE
[closetag addon] emptyTags needs 'same case' tag names, while dontCloseTags & indentTags need lowercased

### ISSUE THREAD

**Issue by goozak** [codemirror/CodeMirror#6323]
When using the `...Tags` option with camelCase tag names, the case requirement is different for `emptyTags`.

`dontCloseTags` and `indentTags` require a lowercased list of tags, but `emptyTags` will only work on same-case tags.

`indentTags: ['thisTag']` will not indent `</thisTag>` and
`<thisTag/>` will NOT be properly closed if `emptyTags: ['thistag']` is used.

Shouldn't it be the same (either lowercase or camelCase) for all options?
A mention about the case requirement could be useful in the 'supported options' section of the `closetag.js` file.

**Comment by marijnh** [comment]
`emptyTags` only has meaning in XML, and XML is case-sensitive, so I think the current behavior is reasonable.
