### ISSUE TITLE
CodeMirror pre-compressed with Brotli:11 on open source CDN

### ISSUE THREAD

**Issue by praisedpk** [codemirror/CodeMirror#6324]
I have added CodeMirror on PageCDN. Current size of [codemirror.min.js](https://pagecdn.io/lib/codemirror/5.55.0/codemirror.min.js) on PageCDN is just **49 KB** that is around 5 KB smaller than normal due to better compression. The files are available on CDN here: https://pagecdn.com/lib/codemirror

Adding this CDN link in docs is helpful for users looking to reduce JS size.

Thanks.

**Comment by marijnh** [comment]
Sorry, no, I don't want to endorse a specific CDN in our docs.
