### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by yongruning** [codemirror/CodeMirror#6326]
This error occurs when you click the edit box console，Upon examination, it was found that：

             cmOption: {
                    autoCloseBrackets: true,
                    tabSize: 4,
                    styleActiveLine: true,
                    lineNumbers: true,
                    line: true,
                    mode: 'text/x-python',
                    theme: 'night',
                    keyMap: "emacs"
                },

This error occurs when configuring keyMap: "Emacs"。

underlying code：
       
          function lookupKey(key, map, handle, context) {
              map = getKeyMap(map);
              var found = map.call ? map.call(key, context) : map[key];
              if (found === false) { return "nothing" }
              if (found === "...") { return "multi" }
              if (found != null && handle(found)) { return "handled" }
              if (map.fallthrough) {
                    if (Object.prototype.toString.call(map.fallthrough) != "[object Array]")
                        { return lookupKey(key, map.fallthrough, handle, context) }
                        for (var i = 0; i < map.fallthrough.length; i++) {
                            var result = lookupKey(key, map.fallthrough[i], handle, context);
                           if (result) { return result }
                       }
              }
          }

"var found = map.call ? map.call(key, context) : map[key]"   map No call attribute,I wonder why,thank you

**Comment by marijnh** [comment]
Could it be that you're not loading `keymap/emacs.js`, yet setting the `keyMap` option to `"emacs"`?

**Comment by yongruning** [comment]
@marijnh I have imported Emacs.js

**Comment by marijnh** [comment]
Reduce your setup to the minimal HTML needed to trigger the error and, if that doesn't make the problem obvious, I'll take a look.

**Comment by yongruning** [comment]
@marijnh sorry,I'm using a vue-codemirror,There seems to be some conflict between the vue-codemirror and the electron,I'm going to close the question
