### ISSUE TITLE
How to integrate Hint for Java, C++,C and NodeJs like our sql, javascript and HTML

### ISSUE THREAD

**Issue by Radhakrishanan** [codemirror/CodeMirror#6327]
I am try to integrate hint for Java , C++, C , NodeJS.  Is there any option to do? Because in codeMirror Hint folder contains not these hints. If possible to integrate hint for the above mentioned language please assist with this one how to do. 
Refer : http://ajaxorg.github.io/ace-builds/kitchen-sink.html
Thanks

**Comment by marijnh** [comment]
Most language modes export a static list of completions, and just loading the autocomplete addon will default to showing those. If you need something beyond that, there's no ready-made solution.
