### ISSUE TITLE
Sql-Hint don't show autocomplete on aliases of tables which are represented in backticks " ` "

### ISSUE THREAD

**Issue by asprazz** [codemirror/CodeMirror#6331]
### Description
As per the issue in Phpmyadmin (https://github.com/phpmyadmin/phpmyadmin/issues/16227)

### Problem
Sql-Hint works very well with tables without backtick " ` "
![85701711-57cce300-b6e6-11ea-9ec2-1d075ccdf397](https://user-images.githubusercontent.com/19568165/85913030-ef4d4580-b84e-11ea-807d-0d1fb173df51.png)

But after using backticks, autocompletion doesn't show up
![85701993-a4182300-b6e6-11ea-8873-c3a2c8f3ca28](https://user-images.githubusercontent.com/19568165/85913056-160b7c00-b84f-11ea-8432-e25a271a199b.png)

### Expectation
![85892729-15eb8c00-b80f-11ea-8ae1-99b7b5f3935d](https://user-images.githubusercontent.com/19568165/85913065-2a4f7900-b84f-11ea-9e52-28385c62b930.png)

Please reference the issue in phpmyadmin (https://github.com/phpmyadmin/phpmyadmin/issues/16227)
and similar to https://github.com/codemirror/CodeMirror/issues/4712
Thank You!

**Comment by KaKi87** [comment]
Hello,

I managed to add SQL tables autocompletion using [this code snippet from StackOverflow](https://stackoverflow.com/questions/20023381/codemirror-how-add-tables-to-sql-hint/24560254#24560254) but how can I add column types like shown on those screenshots ?

*Sorry for being off-topic but I couldn't find any trace of this feature anywhere else.*

Thanks

**Comment by marijnh** [comment]
Commenting on old issues is really not the way to ask for help. Try the [forum](https://discuss.codemirror.net).

**Comment by tianalemesle** [comment]
[Done](https://discuss.codemirror.net/t/display-sql-columns-type-in-autocompletion-dropdown/4155).

**Comment by KaKi87** [comment]
[Done](https://discuss.codemirror.net/t/display-sql-columns-type-in-autocompletion-dropdown/4155).
