### ISSUE TITLE
The require.js example is not working.

### ISSUE THREAD

**Issue by alvarotrigo** [codemirror/CodeMirror#6333]
Way to reproduce it:

Go to /demos/require.html
Open it and click on the button.

**Comment by marijnh** [comment]
Works for me (other than that you got the URL entirely wrong): https://codemirror.net/demo/requirejs.html

Which browser are you using?

**Comment by alvarotrigo** [comment]
It wasn't a url, i was making reference to the example in github:
https://github.com/codemirror/CodeMirror/blob/master/demo/requirejs.html

**Comment by marijnh** [comment]
Which is exactly the file that the link I gave points at.

**Comment by alvarotrigo** [comment]
Yeah I can see that, however I would expect examples to be able to work out of the box when opening them.
It seems however that they are just a replica of the page's code and that won't run unless we replicate the same structure as the page itself.

**Comment by marijnh** [comment]
RequireJS won't work on a `file://` URL, so that may be what you're seeing here.
