### ISSUE TITLE
Tribute.js integration not working

### ISSUE THREAD

**Issue by doshkim** [codemirror/CodeMirror#6340]
**Background:** Tribute was used to implement @mention feature within CodeMirror (https://github.com/zurb/tribute)

- I'm getting the data remotely to fetch the list of suggestions for @mention.
- **What worked:** I've implemented a KeyMap handler to take care of down/up/enter keys to be ignored when the @mention's suggestion list is open, so that I can use the arrow keys & enter to select the right person/content, instead of cursor moving around within the editor.
- **What's not working:** The problem is with left/right arrow keys & backspace. Because element that gets passed when the key is pressed is not textarea, but an editor, it stops calling the servers and the suggestion list no longer updates.

Has anyone successfully implemented Tribute.js to implement @mention feature within CodeMirror?

**Comment by doshkim** [comment]
Because the TextArea gets reset when backspace/left arrow/right arrow is pressed, Tribute.js is using an empty string to look things up, causing no changes to the suggestion/result list.

Need a way to prevent TextArea reset for those keys during Tribute.js menu is open. So far, not sure how to do that without changing CodeMirror code. :'-(

**Comment by marijnh** [comment]
This is out of scope for this bug tracker. 3rd party tools directly interacting with the editor's hidden textarea aren't something we support, so I'm not going to debug this.
