### ISSUE TITLE
`preventDefault` on keydown events has no impact on CodeMirror

### ISSUE THREAD

**Issue by rathboma** [codemirror/CodeMirror#6346]
Firstly -- Love Codemirror. I build [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio), and we use CodeMirror for our SQL editor. It's great.

I am currently building a client side file-menu, and I'm trying to capture up/down/left/right arrow keys for menu interactions.

For a regular textarea, capturing `keydown` events, and calling `e.preventDefault()` works just fine. But in CodeMirror, the cursor still moves.

Here's a JsFiddle (version 5.55) example where I'm capturing `keydown` events, but the cursor still moves in the editor:

https://jsfiddle.net/o78102fr/4/

Reproducing:
- Select the CM editor, press the up arrow. The cursor moves. This is NOT the desired behavior
- Scroll down to the text area, enter some text, then press the up arrow. The cursor does NOT move (this is the desired behavior)
- Check the JSFiddle console - you can see the event is being captured correctly

Hoping someone can recommend a solution!

**Comment by marijnh** [comment]
The cleanest way to do this would be to add a temporary keymap (for example with the [`extraKeys`](https://codemirror.net/doc/manual.html#option_extraKeys) option) or add a handler via CodeMirror's [`on`](https://codemirror.net/doc/manual.html#on) method. If you directly add event handlers with the DOM methods it's likely that those will be executed after CodeMirror has already handled the event.
