### ISSUE TITLE
Is CodeMirror safe to put online and open to public on my VPS ?

### ISSUE THREAD

**Issue by JupyterJones** [codemirror/CodeMirror#6347]
I have a VPS and  want to put CodeMirror online. Then I want to create YouTube lessons on the JavaScript inside the various windows. I want to allow live changes. Users will also be able to download the code they create. It is working fine. My question is reasonably safe for my VPS and website.

**Comment by marijnh** [comment]
CodeMirror itself shouldn't provide any way to compromise your site. What you do with the code edited by users needs more careful consideration, of course.
