### ISSUE TITLE
python hint support?

### ISSUE THREAD

**Issue by chaserstrong** [codemirror/CodeMirror#6348]
I find out that at the version of 3 codemirror is supported for python hint. As i can find python-hint.js in the floder /addon/hint/python-hint.js.
And i'm confused why it would be removed.

**Comment by marijnh** [comment]
There once was a very broken contributed python-hint file, but it never worked very well and I decided not to support it further, so it was dropped in 261d3d3fb035b7350fe (which suggests that you can just use the `hintWords` helper to get the same effect).
