### ISSUE TITLE
Project wiki has been vandalized; should content be restored/merged or moved elsewhere?

### ISSUE THREAD

**Issue by D-side** [codemirror/CodeMirror#6353]
I looked around [the wiki](https://github.com/codemirror/CodeMirror/wiki) and it looks like it was completely demolished back in May. I was particularly curious about the [addons page](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons) that is essentially empty now. [Mode wishlist](https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list) was "restarted" since.

Might be a good idea to revise the means of maintaining that content in a way that does not allow modifying past history, in order to avoid this mishap in the future. I don't know if GitHub has any settings for this now 🤔

I took the liberty to find some of the content on the Wayback Machine:

* [Homepage](https://web.archive.org/web/20171124135415/https://github.com/codemirror/CodeMirror/wiki)
* [CodeMirror addons](https://web.archive.org/web/20200103112134/https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons)
* [Mode wishlist](https://web.archive.org/web/20170724094131/https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list)
* [GSoC 2014 ideas](https://web.archive.org/web/20170724094128/https://github.com/codemirror/CodeMirror/wiki/GSOC-2014-Ideas)
* [Tutorials](https://web.archive.org/web/20170724094134/https://github.com/codemirror/CodeMirror/wiki/Tutorials)

**Comment by D-side** [comment]
Unfortunately so far I'm not finding a setting on GitHub that allows public edits without allowing force-pushing (and with that wiping past history). So-o... I would suggest migrating these pages elsewhere.

Do they change **that** frequently to actively avoid pre-moderation in form of code review? Because if not, keeping that content in an ordinary repo and accepting content through PRs might not be that bad a solution.

**Comment by marijnh** [comment]
Ugh, that's quite a misfeature. Most of the stuff on the wiki was terribly out of date anyway (we don't even add modes anymore, so the mode wishlist wasn't a useful thing anymore), and I've decided that I just don't have time to moderate these. So I've simply closed the wiki. People will have to search for addons on npm instead.

**Comment by D-side** [comment]
Fair enough.
Mind link breakage though, there's at least one "our wiki" link on https://codemirror.net/ — that one in particular is also a good place for the npm search recommendation.

**Comment by marijnh** [comment]
I think patch feed5d5325e97f already took care of those.
