### ISSUE TITLE
Replace decorations 

### ISSUE THREAD

**Issue by zipme** [codemirror/CodeMirror#6354]
In codemirror 6, [you could hide part of the document or replace it with a given DOM node](https://codemirror.net/6/docs/ref/#view.Decoration%5Ereplace)

Is there a way to archive the same in version 5? For example, in markdown mode, as soon as a task list (`- [x] foo`) is entered, you can replace `- [x]` with a checkbox.

**Comment by marijnh** [comment]
Yes, `markText` has a `replaceWith` option that does this.

**Comment by zipme** [comment]
@marijnh Great! Thank you very much!
