### ISSUE TITLE
Importing addons breaks for native ES module imports (vite)

### ISSUE THREAD

**Issue by Yaakov-Belch** [codemirror/CodeMirror#6355]
# Summary: placeholder.js not supporting native ES module import?
Calling `import 'codemirror/addon/display/placeholder.js'` in a vue 3/vite project fails in dev mode with an error message `placeholder.js:10 Uncaught ReferenceError: CodeMirror is not defined`.

It seems that the root cause of this problem is that vite uses native ES module imports --- which seem not to be supported for this particular addon.

Adding a single line `import CodeMirror from 'codemirror'` at the top of the file `codemirror/addon/display/placeholder.js` solves the problem -- of course this is a hack that just demonstrates that the file expects a different import system than used.

Thus, what's needed to resolve this issue is to support native ES module imports for the addons.

# How to reproduce the problem?

    npm init vite-app import-bug-report
    cd import-bug-report
    cat > package.json << "EOF"
    {
      "name": "import-bug-report",
      "version": "0.0.0",
      "scripts": {
        "dev": "vite",
        "build": "vite build"
      },
      "dependencies": {
        "codemirror": "^5.55.0",
        "vue": "^3.0.0-beta.14"
      },
      "devDependencies": {
        "vite": "^0.20.0",
        "@vue/compiler-sfc": "^3.0.0-beta.14"
      }
    }
    EOF

    cat > src/main.js << "EOF"
    import { createApp } from 'vue'
    import App from './App.vue'
    import './index.css'
    
    import CodeMirror from 'codemirror'
    import 'codemirror/addon/display/placeholder.js'
    
    createApp(App).mount('#app')
    EOF

    npm install
    npm run dev

Open in the browser: http://localhost:3000/ and inspect the DevTool console.
    
I use Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Ubuntu Linux.

# Additional references
Info about vite: https://github.com/vitejs/vite -- The section https://github.com/vitejs/vite#browser-support states: "Vite requires native ES module imports during development. The production build also relies on dynamic imports for code-splitting (which can be polyfilled)."

In a possibly similar issue https://github.com/vitejs/vite/issues/385 -- Evan You (the author of vue and of vite) writes: **"I would recommend bugging the author of use-http to switch to ESM syntax and publish an ESM build instead."** I'd like to do this here with this bug report.

**Comment by marijnh** [comment]
> It seems that the root cause of this problem is that vite uses native ES module imports --- which seem not to be supported for this particular addon.

The addons are all UMD modules, and none of them are compatible with ES modules. As such, until version 6 is production-ready and you are able to move to it, you're going to have to accept that you'll have to pre-bundle the parts of CodeMirror you need using some CommonJS-aware bundler.
