### ISSUE TITLE
When I type "e" the cursor goes backward

### ISSUE THREAD

**Issue by SMLVG** [codemirror/CodeMirror#6357]
The source is here:
https://github.com/SMLVG/Delta-Studio
Tested it in Windows 10 Pro 2004, Ubuntu 20.04. UTF8

**Comment by marijnh** [comment]
Assuming this does not happen in the demos on the [website](https://codemirror.net), you'll have to reduce the case in which it does to the minimum code needed if you want us to take a look. We don't debug other people's integration of the library.

**Comment by SMLVG** [comment]
Solved: it was an HTML AUTO-CLOSE-TAGS bug
