### ISSUE TITLE
Question: how do i get a CM's value by its element?

### ISSUE THREAD

**Issue by SMLVG** [codemirror/CodeMirror#6358]
I've tried *element*.CodeMirror.getValue()
The element isn't the textarea, it is the editor.

**Comment by jdbruxelles** [comment]
To ask for help, please use the forum, not the bug tracker.
Here is your configuration:
```javascript
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
  // Your CodeMirror options go here.
});
```
To get the content of your editor, you can call `editor.getValue()` or `editor.getDoc().getValue()`.
Note that `element.CodeMirror.getValue()` or `CodeMirror.getValue()` don't exist.

**Comment by SMLVG** [comment]
Sorry, i'll use the forum the next time, but my question is: can i access a codemirror instance by its textarea?

**Comment by marijnh** [comment]
> can i access a codemirror instance by its textarea?

No. The `CodeMirror` property is added to the `<div>` element created for the editor, but the textarea doesn't have one.
