### ISSUE TITLE
Where is codemirror.js?

### ISSUE THREAD

**Issue by techboyg5** [codemirror/CodeMirror#6366]
I cannot find it in the `lib/` folder but can in the `src/` folder. Is there a typo in the documentation?

**Comment by marijnh** [comment]
Don't install using the git repository. Install from npm or download the zip file from the website, those contain the build artifacts.

**Comment by jdbruxelles** [comment]
And here is more info for the same question on Stackoverflow : http://stackoverflow.com/questions/42444093

**Comment by techboyg5** [comment]
> 
> 
> Don't install using the git repository. Install from npm or download the zip file from the website, those contain the build artifacts.

OK, thank you!
