### ISSUE TITLE
Codemirror show-hint widget sometimes positioned incorrectly

### ISSUE THREAD

**Issue by eforeland** [codemirror/CodeMirror#6369]
When working with about 100 lines or more in the editor, autocomplete widget will get positioned way too far down the screen so that it is not visible. This only happens when typing code on about line 100 or more. I traced some of the variables and I found that when getting the widget position with this line 'var pos = cm.cursorCoords(completion.options.alignWithWord ? data.from : null);', positions has property 'top' that is way off. This line is in the main 'Widget' function. It should be something in the range of 100px -800px but is getting something like '400px' for that property. I have no no idea why this is happening. Also, hitting backspace seems to set the widget back to the correct position but character input will set it wrong.

![show-hint-bug](https://user-images.githubusercontent.com/57921144/89071972-96307000-d32c-11ea-9684-dd923a61c76a.png)

**Comment by marijnh** [comment]
Since this isn't happening in the [demo](https://codemirror.net/demo/complete.html), could you try to simplify your setup until you find out what is causing this?
