### ISSUE TITLE
For`CodeMirror.fromTextArea(editorElem, options)`instance, how to switch theme and programming language?

### ISSUE THREAD

**Issue by WxxShirley** [codemirror/CodeMirror#6374]
Hi, I have created an instance `editor` which is created by  calling `CodeMirror.fromTextArea(textarea_element, options)`

However, I wanted to change the themes and programming languages **dynamic**( adding `dropdowns` for this)

how to implement this function? 🙏🙏🙏

**Comment by marijnh** [comment]
Use the `setOption` method on the editor instance that returns.

Next time, please don't use the bug tracker for questions. We have a [forum](https://discuss.codemirror.net/) for that.
