### ISSUE TITLE
auto move the cursor to the middle of  /* */  without selection comment

### ISSUE THREAD

**Issue by dnknn** [codemirror/CodeMirror#6375]
After inserting a comment when without selection, auto move the cursor to the middle of /**/

seeing to 👇
https://github.com/openstyles/stylus/issues/1012

**Comment by marijnh** [comment]
If I'm guessing correctly that Stylus is calling the `blockComment` method when this functionality is activated with `fullLines: false`, then the attached patch might help.

**Comment by dnknn** [comment]
I don't know how to read the code, but thanks again.
