### ISSUE TITLE
how can select the hint item,and get the item's value in react-codemirror2

### ISSUE THREAD

**Issue by flyaaaaaaaa** [codemirror/CodeMirror#6379]
hi, i'm doing a project with lots of tables,and i want to get one of the table item and use it to search its fields.i've checked the codemirror doc and find the completion property width pick method,but i donnt konw how to use its pick method to get the item value

**Comment by marijnh** [comment]
This is the bug tracker—the [forum](https://discuss.codemirror.net/) is a better place to ask questions. But even there, you'll have to provide a lot more background, since I really don't know what you're trying to do from this description.
