### ISSUE TITLE
[Question] How does the markdown styling mode work?

### ISSUE THREAD

**Issue by ehhc** [codemirror/CodeMirror#6397]
Hi there,
I just found this mode: https://codemirror.net/mode/markdown/index.html which properly styles some elements of markdown text (e.g. make headlines bigger and bold).
I would like to have the same behavior (and more) for asciidoc-text. Unfortunately, I’m not able to figure out how you make it work.. As far as I see there is no guide/explanation/commend in code on how to create an own overlay style..
Can you point me to the right place? Maybe give me a small example on how to create such a formatting-overlay? And maybe point out the limitations of this mode? E.g. I’m wondering whether it’s possible to format tables with it as well..

Thanks in advance :)

**Comment by marijnh** [comment]
The Markdown mode is a regular mode, not an overlay. There's some background on how modes work in [this blog post](https://marijnhaverbeke.nl/blog/codemirror-mode-system.html), but there's no step-by-step guide that'll tell you what to do.

The bug tracker is not the right place for questions, as you could plainly read in the default text that was in the input field when you created this bug. We have a [forum](https://discuss.codemirror.net/) for that.

**Comment by ehhc** [comment]
You're right. I'm sorry. Thanks for the blog post link :)

**Comment by jdbruxelles** [comment]
Hi @marijnh, I noticed that there are many broken links in the blog post.
