### ISSUE TITLE
Do we have any option to allow some custom css properties ?

### ISSUE THREAD

**Issue by bhalke** [codemirror/CodeMirror#6400]
Have some custom css property for example  "padding-me" this css property should not be flagged red,  how can i allow few custom css property to not to flag red.

Do we have any such option or addons in code-mirror?

**Comment by marijnh** [comment]
This doesn't currently exist. You could either use an [overlay](https://codemirror.net/doc/manual.html#addOverlay) that styles these words the way you want, or create a pull request to make the CSS mode easier to configure.

**Comment by bhalke** [comment]
Thank you
