### ISSUE TITLE
Disable MacOS "Add period with double-space"

### ISSUE THREAD

**Issue by humphrey** [codemirror/CodeMirror#6401]
MacOS and iOS has **Add period with double-space** enabled by default for fresh installs to match the functionality of iOS.  While I can see that this behavior *might* be useful when typing when prose on an iOS device, it does not make sense in a code editor where spaces are used to create white-space.  

While it can be [disabled manually](https://www.techjunkie.com/macos-sierra-add-period-double-space/) in the OS settings by the user, I propose CodeMirror either disables it by default or providers an option to disable it.  This must be possible, as none of the other coding software on my computer allows double-space to add a period.

My use case for this is that I am using CodeMirror as a song chord chart editor.  So my users would almost likely not be coders, and would be using multiple taps of the spacebar to layout chords and lyrics.

Many thanks!

**Comment by marijnh** [comment]
> I propose CodeMirror either disables it by default

If you know of a way to do that, let me know.

**Comment by humphrey** [comment]
I now have this working with a regular Textarea element in React - see the following Gist.

https://gist.github.com/humphrey/9d799b50c0dd39431da7a159ea3bb6fe

I now plan to porting this approach to work with **react-codemirror2** so that I can get my project working.

**Comment by humphrey** [comment]
And I got it working using react-codemirror2.  Must simpler!

```tsx
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/material.css';
import React from 'react';
import { UnControlled as CodeMirror } from 'react-codemirror2';
import codemirror from 'codemirror'
import {EditorChangeCancellable} from 'codemirror'

export const App = () => {
  const [state, setState] = React.useState("hello world")
  return (
    <div>
      <CodeMirror
        value={state}
        options={{}}
        onBeforeChange={(editor, data, value) => {
          const data2 = data as EditorChangeCancellable;
          if (data2.update && data.origin === '+input' && data.text.length === 1 && data.text[0] === ". ") {
            console.log(' MacOS and iOS "Add period with double-space" feature');
            data2.update(data.from, data.to, ["  "])
          }
        }}
      />
    </div>
  );
}

```
