### ISSUE TITLE
Valid css property flagging red ?

### ISSUE THREAD

**Issue by bhalke** [codemirror/CodeMirror#6402]
I have valid css property "**margin-inline-start:1px**" but code mirror flagging this prop as red ? what is option available to make this prop not to flag red.

**Comment by marijnh** [comment]
It's recognized as a non-standard property, which it [is](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start#Specifications), so that is by design. I'd be happy to review a pull request that adds an option to turn off property name checking to the CSS mode would be.
