### ISSUE TITLE
markText设置样式

### ISSUE THREAD

**Issue by mjx666** [codemirror/CodeMirror#6405]
给特定范围字符串一个类，如果字符串含有特殊字符串（比如  '/'）,会自动切割

**Comment by marijnh** [comment]
Sorry, but this project is maintained in English and if you can't be bothered to run your text to a translation service before posting, neither can I.

**Comment by mjx666** [comment]
Give a class to a specific range string. If the string contains a special string (such as' / '), it will be automatically cut

**Comment by marijnh** [comment]
Yes, that's how the library works—inline content is split into a flat sequence of elements. You can't nest marks and/or tokens.

**Comment by mjx666** [comment]
Is there any way to solve this problem？
