### ISSUE TITLE
endOfLine in RTL

### ISSUE THREAD

**Issue by aameen951** [codemirror/CodeMirror#6406]
Hello there,

I'm using CodeMirror in RTL mode and I found a weird behavior when pressing the `End` button in the following example:
<p dir="rtl">
السعر هو 1000
<br>
price is 1000
</p>

Currently in RTL mode, when pressing the `End` button the cursor is landing at end of the line in visual order which is between the text and the number in content order. This means if you press `End` and start typing, the text will not go at the end of the line instead it will go before the number in this case.
The expected behavior when pressing `End` is to land at the end of the line in content order (not visual order) regardless of whether text is RTL or LTR. This is also the behavior in Firefox and Chrome.
The same thing should be for `Home`. It should go to the start of the line in content order not visual order.

I think passing false as visual to `endOfLine` function would do it.
https://github.com/codemirror/CodeMirror/blob/f28ed4df39d0c977833504ba0413cdf6f09ef0bd/src/edit/commands.js#L156-L166

**Comment by marijnh** [comment]
CodeMirror's current behavior matches what Firefox does (both in textarea and in contenteditable elements), so it seems like there is at least different opinions on what the right behavior is.

**Comment by aameen951** [comment]
Visually, CodeMirror, Firefox, and Chrome all behave the same, that is when you press `End`, the cursor will be go to the end of the line. However, the location of the cursor in the buffer is different. In Firefox and Chrome the cursor is also at the end of the buffer, but in CodeMirror it is not.

You can verify this by pasting the above Arabic line in both CodeMirror and Firefox RTL textarea then try the following: press `Home`, then hold `Shift` and press `End`. This should select the entire line and it does in Firefox and Chrome but not in CodeMirror.

Anyway, I will close this issue because it is not a big deal and if I find it annoying I can change it manually.
