### ISSUE TITLE
Backspace behaviour on characters created using combining diacritical marks differs to that of a normal browser textarea.

### ISSUE THREAD

**Issue by bmurr** [codemirror/CodeMirror#6408]
For example, this character é is made from the characters e + \u0301.
In a standard textarea, the backspace will delete the accent. In CodeMirror, the whole character is deleted.

Another example, this character in Tamil: க்
Backspace should create the character க but instead the whole character is deleted.
This causes issues when working with software keyboards, like Azhagi. 

The expected behavior is present in Chrome and Firefox, both OSX and on Windows. 

I guess this is probably related to #2115

**Comment by marijnh** [comment]
Good point. Attached patch implements this.
