### ISSUE TITLE
Scrollbar gets outline when focused

### ISSUE THREAD

**Issue by icedjuro** [codemirror/CodeMirror#6412]
This issue can be noted on chromium browsers(Chrome, Edge, etc., but not Firefox). When there is overflow, and the scroll bar appears(vertical or horizontal), holding/clicking on it causes there to be a sudden outline box. An easy way to see this is to go to one of the [demo pages](https://codemirror.net/demo/closebrackets.html) and just click on the scrollbar. If you're focused on an element outside of the editing box, and then press the scrollbar, it remains outlined. If you are focused on an element in the editing box and press on the scrollbar, it appears for a split second. 
```css
.CodeMirror-vscrollbar, .CodeMirror-hscrollbar {
    outline: none;
}
```
Adding the code above in an external stylesheet removed the problem, although there might be a better solution, or there is a deeper issue causing this.

**Comment by marijnh** [comment]
It seems that scrollable elements are focusable, and this can not be disabled. I didn't find a better way to avoid this than to hide the outline with CSS, so I've done that in fd2e3225
