### ISSUE TITLE
`input` event not always triggered

### ISSUE THREAD

**Issue by marcandre** [codemirror/CodeMirror#6416]
Summary: pressing the delete key, or pasting text within a codemirror should trigger an [`input` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) but does not.

Details:
I have a form with a normal input and a textarea. I listen to the `input` event at the level of the `<form>` as I need to update the display on changes to either inputs.

Converting this textarea to a Codemirror *almost* works. Typing in a codemirror still triggers an `input` event, but deleting a character or pasting code won't.

Note that this is the correct usage of the `input` event; one can not use the `change` event for that purpose, as this is triggered only when the user commits that value (e.g. by focussing out). Note that I am not referring to the internal events that codemirror uses (with `on` and `off`); it appears that this API is using an event called "change" instead of the more appropriate name "input", but that is something completely different.

**Comment by marijnh** [comment]
This isn't something that the library promises. You're probably better off using CodeMirror's own [`"changes"` event](https://codemirror.net/doc/manual.html#event_changes).
