### ISSUE TITLE
readOnly mode still allows cut/paste in context menus

### ISSUE THREAD

**Issue by darahak** [codemirror/CodeMirror#6418]
[JSFiddle for repro](https://jsfiddle.net/u7ob1fwL/) (reproducible in Chrome, Firefox and Edge)

When a CodeMirror editor is configured as read-only and the user opens a context menu, they can still see the **cut** and **paste** options.
It can be misleading since clicking on these items will do nothing.

While inspecting the elements inside the CM editor, I noticed a hidden `<textarea>` nested under a classless `<div>` styled with `overflow: hidden` among other things, right under `<div class="CodeMirror cm-s-default">`.
If I add the `readonly` attribute to that `<textarea>`, the issue seems fixed but could this lead to unwanted side effects?

**Comment by marijnh** [comment]
That's a good idea. Implemented in attached patch. Unfortunately, it doesn't help on Firefox, but there's not a lot the library can do about that.
