### ISSUE TITLE
codemirror want to disaplay loader on dragover

### ISSUE THREAD

**Issue by dhavalsoni9989** [codemirror/CodeMirror#6421]
I want to display the loader once user dragover the file on the codemirror editor.

I have added the webhook for that with below code

const options = {
        matchBrackets: true,
        autoCloseBrackets: true,
        mode: "application/json",
        gutters: ["CodeMirror-lint-markers"],
        lineWrapping: true,
        lineNumbers: true,
        dragdrop:true
    };
editor = CodeMirror.fromTextArea(container, options);
editor.on("dragover",function(editor,e){
        $("#file-loading").addClass("is-active");
        console.log("dragover");
        e.preventDefault();
    });
    editor.on("drop",function(editor,e){
        $("#file-loading").removeClass("is-active");
        console.log("drop");
        e.preventDefault();
    });

When I am going to drop the file it will directly open that file into the browser once I added the javascript/Jquery code into the dragover webhook.

Please help me to resolve this issue.

**Comment by marijnh** [comment]
This is not an issue that belongs in the issue tracker. Try the [forum](https://discuss.codemirror.net) for help requests (as the issue template that showed up when you created this clearly asked you to).
