### ISSUE TITLE
RE: Typing text on android does not hide a placeholder

### ISSUE THREAD

**Issue by ivictbor** [codemirror/CodeMirror#6422]
Hi!
AFAIK this page https://codemirror.net/demo/placeholder.html  does use 5.58.0 , when it states that it has this fix (https://github.com/codemirror/CodeMirror/commit/7b63084691b9c56baf02e5f2c2a9d5aebd435dc1), but original issue posted here is still not fixed for me: https://github.com/codemirror/CodeMirror/issues/6420

(Just FYI, thanks a lot for very quick action)

**Comment by marijnh** [comment]
Oh, wow, that patch had a bunch of issues. ca046d7d should help.

**Comment by ivictbor** [comment]
@marijnh great, now it works awesome! Thank you
