### ISSUE TITLE
codemirror 5.58.0 after compilation will produce es6 Functions =>

### ISSUE THREAD

**Issue by kongdemin** [codemirror/CodeMirror#6423]
use uglifyjs will be error

**Comment by kongdemin** [comment]
CodeMirror.on(cm.getInputField(), "compositionupdate", cm.state.placeholderCompose = () => onComposition(cm))

**Comment by marijnh** [comment]
This was fixed already in c74a1cafc01a. I'll tag a new release with the fix.

**Comment by kongdemin** [comment]
ok，thanks
