### ISSUE TITLE
KeyboardEvent - move from keyCode (deprecated) to key

### ISSUE THREAD

**Issue by hirishh** [codemirror/CodeMirror#6424]
Hello!

While unit-testing my application, I was trying to dispatch custom KeyboardEvents with

```javascript
cm.getInputField().dispatchEvent(new KeyboardEvent('keydown', { key: 'b', ctrlKey: true }));
```
I discovered you are using keyCode ( [here](https://github.com/codemirror/CodeMirror/blob/4cfb3a038929d0b5f00d3741551cacd97081fc48/src/input/keymap.js#L136) ) that is now deprecated ( [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) )

This issue is just a reminder to move to [KeyboardEvent.key ](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

**Comment by marijnh** [comment]
CodeMirror 5 is not going to move to `.key`, since that'd cause a whole lot of new incompatibilities and issues. But it may console you that [CodeMirror 6](https://codemirror.net/6/) does use `.key` when available.
