### ISSUE TITLE
The editor under vue3 inserts the last line, cannot enter 

### ISSUE THREAD

**Issue by wike2019** [codemirror/CodeMirror#6435]
the platform is win10

Report an error

codemirror.js:1659 Uncaught TypeError: Cannot read property 'height' of undefined
at lineLength (codemirror.js:1659)
at codemirror.js:5454
at LeafChunk.iterN (codemirror.js:5618)
at Doc.iterN (codemirror.js:5720)
at Doc.iter (codemirror.js:6106)
at makeChangeSingleDocInEditor (codemirror.js:5453)
at makeChangeSingleDoc (codemirror.js:5423)
at makeChangeInner (codemirror.js:5292)
at makeChange (codemirror.js:5283)
at applyTextInput (codemirror.js:8139)

the main code for bug
```
 insertContent(str){
       editor?.value.replaceSelection(str);
       lastInsert.value = str.replace(/\n/g, ""); //保存上一次插入的内容，去掉空格 这个功能用于 列表等操作按回车自增
     },
```
```
insertTitle(level) {// 插入标题
      const titles = {
        1: "#  ",
        2: "##  ",
        3: "###  ",
        4: "####  ",
        5: "#####  ",
        6: "######  "
      };
      const {line} = lastPos;
      const selection = editor?.value.getSelection();
      if (selection) {
        actions.insertContent("\n" + titles[level] + selection + "\n");
        return
      } else {
        const title = titles[level];
        if ( editor?.value.isClean()) {  //判断是否是空文档 特殊处理
          actions.insertContent(title+"\n ");
          setCursor(0,title.length)
          return;
        } else {
          actions.insertContent("\n" + title+"\n ");
          setCursor(line + 1,title.length)
          return;
        }
      }
    },
```
![image](https://user-images.githubusercontent.com/5925704/95499449-de78a800-09d7-11eb-968c-f34643d948b7.png)

```
 let title=[
    {
      "tip":"标题1",
      "name":"h1",
      "action":()=>{
        action.insertTitle(1)}
    },
    {
      "tip":"标题2",
      "name":"h2",
      "action":()=>{action.insertTitle(2)}
    },...
```

```
function renderList(data) {
  return data.map((item)=>{
    // @ts-ignore
    return ( <li  name={item.tip} >
      <WIcon  name={item.name}  class="iconfont" onClick={item.action}></WIcon>
    </li>)
  })
}
```

the step one
click h1
the step two
click h2
the step three
add content at last line 
the bug is can't input things and if click other button the content will insert 

the project git is https://github.com/wike2019/wike-ui

**Comment by marijnh** [comment]
In the other issue, I also asked you to reduce this to a minimal script that shows the problem. I'm not prepared to debug a non-trivial app like the one you linked.

**Comment by wike2019** [comment]
> In the other issue, I also asked you to reduce this to a minimal script that shows the problem. I'm not prepared to debug a non-trivial app like the one you linked.

how can i do for you ,the project is base vue3 , i can't give you a mini things

**Comment by wike2019** [comment]
![image](https://user-images.githubusercontent.com/5925704/95522808-b13ff000-09ff-11eb-8293-5f27b00f094a.png)
this is a simple demo

**Comment by marijnh** [comment]
Debugging this, it looks like you're calling CodeMirror methods on some Vue-related `Proxy`, not the actual editor object. This further wraps stuff returned by its methods in `Proxy` objects, which breaks stuff down the line. I'm not familiar with the magic Vue is performing here, but I think you'll get a lot further if you just avoid wrapping the editor in it.
