### ISSUE TITLE
auto indenting is wrong in JavaScript mode in a multi-line template string?

### ISSUE THREAD

**Issue by greggman** [codemirror/CodeMirror#6442]
version 5.58.1

If you have code like this

```
const s = `
{  //  on the next line type 4 spaces and then a 
`;

// what should happen? the { should be 4 spaces out
// what happens instead, the spaces are removed
```

And follow the directions above, type [space] [space] [space] [space] [{]  the spaces are deleted. That seems unintentional?

In other words I want this

```
const s = `
{
    {
```

but I get this

```
const s = `
{
{
```

repo:

https://jsgist.org/?src=7e596608ea9ebfb166cfd21467accbfc

**Comment by greggman** [comment]
wow! I'm sure you guys are busy and frustrated to get bug reports but seriously? not even comment on why? I'm sorry if this was the wrong place to post what seems like a bug.

It kind of makes it hard to type JavaScript if you use multi-line template literals (which I use all the time since in WebGL you need to type code in them for GLSL)

![lNXIPL6Qby](https://user-images.githubusercontent.com/234804/96232376-ec7b8980-0fd2-11eb-812c-0ae0222c4fe4.gif)

**Comment by marijnh** [comment]
Look closer at how the bug was closed. It was done via a patch that fixes this.

**Comment by greggman** [comment]
Doh! thank you. Sorry I didn't notice the link
