### ISSUE TITLE
Unclear what the relationship between defineMode, defineMIME, modeInfo, and mimeModes is.

### ISSUE THREAD

**Issue by tolmasky** [codemirror/CodeMirror#6445]
There seems to be a variety of overlapping, but independent, places where mode information is stored. For example, calling `defineMode()` and `defineMIME` seems to correctly update the `CodeMirror.mimeModes` object, but not `CodeMirror.modeInfo`, which means that `CodeMirror.findModeByMIME` fails to find modes added solely through `defineMIME`. It's not clear to me what the utility of calling `defineMIME` is at all, as the only source of truth seems to be the contents of the meta.js file.

Anyways, I am in a situation where I am wanting to add modes to new mime types dynamically, and the only thing that seems to actually have the desired effect is to manually mutate the modeInfo object directly. If this is the expected way to do things, then that is totally fine, just seems like `defineMIME` is somewhat of a red herring in its current incarnation.

**Comment by marijnh** [comment]
`modeInfo` is used to look up mode implementations by name or extension. These may not have been loaded yet. As they are loaded, modes use `defineMode` to register the actual mode implementation and `defineMIME` to associate one or more MIME types with it. You _can_ add to `modeInfo` at run-time, for example to add modes that it doesn't yet know about, but the typical use case is to just use it as a static database about the built-in modes.
