### ISSUE TITLE
scrollIntoView not working

### ISSUE THREAD

**Issue by RanX12** [codemirror/CodeMirror#6449]
I use CodeMirror on two pages. When I was doing mobile phone adaptation, after I clicked on the bottom of the editor, the cursor was also at the bottom and the soft keyboard was raised, but it would be retracted automatically after the soft keyboard was raised. As a result, I can’t input at the bottom of the editor. I tried to use ```this.cm.scrollIntoView(this.cm.getCursor())```. After using ```scrollIntoView```, it can sometimes move the cursor When the row is scrolled into the view, it still doesn't work sometimes. Is there any good way to solve this? thanks

[Demonstration video link](https://trello-attachments.s3.amazonaws.com/5d36acd69a82217c744c0126/5f9167248cc9471104410125/e6faf5fa262a3be86a16c0ba0fe7b174/SVID_20201023_174204_1.mp4)

Browser is Chrome. 
The CodeMirror version is:``` "codemirror": "^5.48.2".```

ps: ios system will not have this problem.

**Comment by tonytrangmail** [comment]
Code googleplay

**Comment by tonytrangmail** [comment]
Dh
