### ISSUE TITLE
Inappropriate Link in Old Docs

### ISSUE THREAD

**Issue by rbaker26** [codemirror/CodeMirror#6452]
## Link to Adult Themed Website
The is a link to an adult website on codemirror.net

## Steps to reproduce
1. Go to codemirror.net/1/contrib/csharp/
2. Click on the Written by "Boris Gaber and Christopher Buchino" link
3. Notice that it takes you to an adult website 

It's basically some sketchy pornography site.

**Comment by marijnh** [comment]
Thanks for noticing that. I guess the domain expired and got taken over. I've removed the links in https://github.com/codemirror/CodeMirror-v1/commit/2d7adc98d16cfb05aecf208177d4a4281b43ce30
