### ISSUE TITLE
Selection does not display in contenteditable mode when CodeMirror does not have focus

### ISSUE THREAD

**Issue by catarak** [codemirror/CodeMirror#6455]
Somewhat related to #3552.

I'm using the search addon with CodeMirror, and when I have `contenteditable` enabled, I noticed that a selection is not visible unless the CodeMirror instance has focus. The use case for this with the search addon is the following, where I am trying to replicate other search flows (like in a browser, VSC, etc.):
1. Enter text into my search box:
<img width="582" alt="Screen Shot 2020-10-28 at 6 04 13 PM" src="https://user-images.githubusercontent.com/6063380/97501648-052b5e00-1948-11eb-8a4a-d1bf3d1f71a3.png">
2. Hit <kbd>Enter</kbd> to input the search
3. Hit <kbd>Enter</kbd> to cycle to the next instance (calling `findNext`)

Because hitting <kbd>Enter</kbd> multiple times keeps the focus on the search input, you can't see which instance is selected, even though if I dig into the guts of the CodeMirror instance and inspect the current selection, I can see that it changes. After digging around for a while I figured out that the culprit is the [following line](https://github.com/codemirror/CodeMirror/blob/master/src/input/ContentEditableInput.js#L120):
```js
   // ContentEditableInput.js
   let result = prepareSelection(this.cm, false)
```
whereas TextareaInput calls the same function in the following way:
```js
  // TextareaInput.js
   let result = prepareSelection(cm)
```

I tried changing the ContentEditableInput line to
```js
    let result = prepareSelection(this.cm)
```
and I was able to get it to work.

As someone who is not at all aware of the internals of CodeMirror, I'm wondering if it would make sense to change this line. What would the consequences be?

Thank you!

**Comment by marijnh** [comment]
The second argument to `prepareSelection` determines whether the primary selection is drawn by the editor or left to the native selection. The change you made will cause it to be drawn both ways (which may look weird in some cases, such as cross-line selections, since the way the native selection is drawn doesn't quite match the way CodeMirror itself draws its selection).

**Comment by catarak** [comment]
Got it! Then I think the issue I'm having is that the CodeMirror selection is not being drawn if the input style is set to `"contenteditable"` if CodeMirror does not have focus, but it is when it is set to `"textarea"`. Which seems to me like this is intentional, because the idea is that with `"contenteditable"` input, the selection would be drawn natively (and I assume this is better for accessibility). However, for native selection, the selection is not shown unless the element has `focus`, which makes it difficult to make search work.

**Comment by marijnh** [comment]
Would having your search code mark the current match with some styling using `markText` work for you?

**Comment by catarak** [comment]
> Would having your search code mark the current match with some styling using `markText` work for you?

This works great, thanks for the suggestion! I'm going to close this since there's a workaround.
