### ISSUE TITLE
xml-hint.js violates "use strict" by declaring a function inside an if statement

### ISSUE THREAD

**Issue by OverZealous** [codemirror/CodeMirror#6457]
I tried upgrading to the latest 5.58.x (from 5.45.0 _[Edit: looks like it was introduced in v5.57.0]_) version of CodeMirror, and now my PhantomJS tests won't run due to `"use strict"` throwing an error:

```
SyntaxError: Functions cannot be declared in a nested block in strict mode
  at build/shared/vendor/codemirror/addon/hint/xml-hint.js:104:1 <- build/shared/js/app/codemirror.js:13140
```

[This merge](https://github.com/codemirror/CodeMirror/commit/7d848769f3d2690293a46b996203bf070ba2a702#diff-0e69e3a382a3e7403386aff62e894d61214dbfe844f3d4e1541bcfb94fcd46c8R104) adds the `returnHintsFromAtValues` function inside an `if` statement.

Simply making this a function expression as below should fix the issue. (I have verified this fix on my end.)

```javascript
        var returnHintsFromAtValues = function(atValues) {
          if (atValues)
            for (var i = 0; i < atValues.length; ++i) if (!prefix || matches(atValues[i], prefix, matchInMiddle))
              result.push(quote + atValues[i] + quote);
          return returnHints();
        };
```

If that's OK, I can make a pull request with this change.

**Comment by marijnh** [comment]
Thanks. I've merged #6458
