### ISSUE TITLE
Line widget's insertAt option won't allow a new widget to be inserted as the last widget for a line

### ISSUE THREAD

**Issue by jaril** [codemirror/CodeMirror#6460]
The splicing logic in line 66 won't allow for an `insertAt` option to place a widget as the last widget for a specific line. This is contrary to how it is documented in the [user manual](https://codemirror.net/doc/manual.html).

https://github.com/codemirror/CodeMirror/blob/81fdc6ffbc5d5861e6d9af4517157f246f03980f/src/model/line_widget.js#L65-L66

For example, take a line with three existing widgets (`[oldWidget1, oldWidget2, oldWidget3]`) where we're trying to add `newWidget`:

`addLineWidget(line, node, { insertAt: 0 })` => `[👋newWidget, oldWidget1, oldWidget2, oldWidget3]`
`addLineWidget(line, node, { insertAt: 1 })` => `[oldWidget1, 👋newWidget, oldWidget2, oldWidget3]`
`addLineWidget(line, node, { insertAt: 2 })` => `[oldWidget1, oldWidget2, 👋newWidget, oldWidget3]`
`addLineWidget(line, node, { insertAt: 3 })` => `[oldWidget1, oldWidget2, 👋newWidget, oldWidget3]`
`addLineWidget(line, node, { insertAt: 4 })` => `[oldWidget1, oldWidget2, 👋newWidget, oldWidget3]`

It seems like the only way to add a widget to the end is by passing in `{ insertAt: null }` as an option.

**Comment by marijnh** [comment]
Right, seems the `- 1` shouldn't be there. Attached patch removes it.
