### ISSUE TITLE
How to allow multiple users type simultaneously on the editor ?

### ISSUE THREAD

**Issue by vishal31raj** [codemirror/CodeMirror#6463]
I'm currently working on a project where I'm allowing multiple users to share a codemirror editor. Since, I'm using socket.io for the real time changes, there's one problem I'm facing. The issue is that there's only one cursor to the editor, so only one user can type at a time. But I want that multiple users could type at different lines at the same time with their individual cursors. What changes should I make ? Help me with this.

**Comment by marijnh** [comment]
This is called collaborative editing, and isn't something CodeMirror 5 supports by itself, though there are [external components](https://github.com/yjs/yjs#bindings) that implement this.

**Comment by vishal31raj** [comment]
Can you help with y-codemirror integration ? Because I'm facing a lot of issues in my project. My project is a MEAN application which already uses socket.io. But y-codemirror has its own socket.

**Comment by marijnh** [comment]
> Can you help me with y-codemirror integration ?

No, sorry. I'm providing this library, but no free integration support.
