### ISSUE TITLE
[clike] numberStart in parser config doesn't work with '.'

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#6473]
I'd have expected that when '.' is matched by the numberStart regex in the parser config passed to the clike mode that numbers starting with . would have the . be highlighted as a number. But this doesn't happen by default, because the . gets matched by the punctuation regex instead. This is really not a major issue, but could maybe be commented in the code for the mode. Or the default regexes could be adjusted to not give the misleading expectation that that . in the numberStart regex would have any effect.

**Comment by marijnh** [comment]
At a glance, it looks to me like numbers should definitely be matched before punctuation there (since they are verified against the `number` regexp anyway). Does that sound like a reasonable solution?

**Comment by mtaran-google** [comment]
Yeah, that would be good. It does appear to work, too -- it seems like the change was submitted as part of 0e6548686356d58504638c2bea95d403a9e53cde
