### ISSUE TITLE
Note the dependency on javascript-lint.js

### ISSUE THREAD

**Issue by erosman** [codemirror/CodeMirror#6477]
Similar to `css-lint.js` & `json-lint.js` etc, it would be useful to mention the `javascript-lint.js` dependency.
e.g.
```
// Depends on jshint.js https://github.com/jshint/jshint
```

**Comment by marijnh** [comment]
Makes sense. Want to submit a pull request?

**Comment by erosman** [comment]
> Want to submit a pull request?

Which branch to? master?

**Comment by marijnh** [comment]
Yes

**Comment by erosman** [comment]
done

**Comment by marijnh** [comment]
Thanks!
