### ISSUE TITLE
Placeholder appears beneath the text when I entered 2 backticks

### ISSUE THREAD

**Issue by TristanLrx** [codemirror/CodeMirror#6479]
Hello,

I'm having a problem on Google Chrome with backticks.
I was able to reproduce the problem on your [demo](https://codemirror.net/demo/placeholder.html)

Let's imagine that I grasp a backtick and then I move with my keyboard with the left arrow I get this : 
<img width="162" alt="Screenshot 2020-11-17 at 16 17 24" src="https://user-images.githubusercontent.com/56972424/99408507-99a63200-28f0-11eb-9d0d-bb02961310b2.png">
<img width="190" alt="Screenshot 2020-11-17 at 16 17 30" src="https://user-images.githubusercontent.com/56972424/99408524-9d39b900-28f0-11eb-80fe-563d6bd514b3.png">

Thank you!

**Comment by marijnh** [comment]
I couldn't reproduce the precise issue you're having with my local settings, but I think I found the cause, and attached patch should address that. Let me know if you're still seeing the problem.

**Comment by craftzdog** [comment]
Just wanted to let you know that it also solved an issue on Japanese IME, which looks like:

![09d6eb69d623ef779439b43e7753db12d389ed2b](https://user-images.githubusercontent.com/1332805/100825129-b9198f00-349a-11eb-93ef-c0c6980c7542.gif)

Thanks for fixing it :)

**Comment by ppianist** [comment]
@marijnh 
Can you tell me how you fixed the issue?

> and attached patch should address that.

I can't see it.

**Comment by marijnh** [comment]
Look for the "marijnh closed this in ..." message in this issue.
