### ISSUE TITLE
[core] drag & drop breaks editing in Chrome

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#6480]
This was diagnosed in https://github.com/codemirror/CodeMirror/pull/6427#issuecomment-722289642, but we pulled the latest version of CM in without noticing it and ran into it ourselves. Could you please address the issue or revert the focus change?

**Comment by marijnh** [comment]
Does patch 12512d3e address what you're seeing?

**Comment by mtaran-google** [comment]
I think that's the wrong commit, but 0e6548686356d58504638c2bea95d403a9e53cde does seem to fix things. Thanks!
