### ISSUE TITLE
Clicking inside selected text disables keyboard input (focus state incorrect)

### ISSUE THREAD

**Issue by nonplus** [codemirror/CodeMirror#6481]
Steps to reproduce (using https://codemirror.net/ example showing 5.58.2):

1. Select some text
2. Click within the selected text

**Expected:**
1. Cursor shown at mouse-click position
2. Typing inserts text

**Actual:**
1. Selection disappears and cursor is not shown
2. Typing does not insert text
3. If more text is selected with mouse, the selection is gray (indicating that editor does not have focus)

**Workaround:**
1. Use `inputStyle='contenteditable'`, or
2. Click outside of the text editor
3. Click back into code editor

**Comment by marijnh** [comment]
I think this was another symptom of #6480. Does patch 12512d3e help?

**Comment by nonplus** [comment]
I suspect it's another manifestation of #6480.  It appears to be fixed in 5.58.3.
