### ISSUE TITLE
CodeMirror-5.58.3 demo wrong script src

### ISSUE THREAD

**Issue by erosman** [codemirror/CodeMirror#6486]
All files in demo have
```html
<script src="../lib/codemirror.js"></script>
```

In 5.58.3 it has moved and all should be changed to 
```html
<script src="../src/codemirror.js"></script>
```

**Comment by marijnh** [comment]
> In 5.58.3 it has moved and all should be changed to

Why do you believe that?

**Comment by erosman** [comment]
Sorry... my mistake 

I downloaded source zip by mistake. Please disregard these 2 posts.
