### ISSUE TITLE
CodeMirror-5.58.3 demo syntax error

### ISSUE THREAD

**Issue by erosman** [codemirror/CodeMirror#6487]
After fixing the `codemirror.js` `src` (#6486), I am getting an error in Firefox when opening the demo

```
Uncaught SyntaxError: import declarations may only appear at top level of a module    codemirror.js:1
```

I have no idea why that is.

Could there be an error in `main.js`? :thinking: 

```js
// EDITOR CONSTRUCTOR

import { CodeMirror } from "./CodeMirror.js"
export { CodeMirror } from "./CodeMirror.js"
```

**Comment by marijnh** [comment]
I think this one can be closed, as its premise (#6486) isn't correct.
