### ISSUE TITLE
Suggestion: Word Based CSS

### ISSUE THREAD

**Issue by erosman** [codemirror/CodeMirror#6495]
It is not easy to add keywords to be parsed differntly by CodeMirror. Here is a suggestion using an alternative approach to achieve the same goal.

The code adds the text content as an attribute to the node.
**I am still working out the relevant classes suitable for this purpose and would welcome suggestions.**

Originally I used `data-value` but CodeMirror also uses `data-value` so in order to avoid possible conflict (I am not sure if there would be a conflict or not) I used `data-text`.
Note: `nodeValue` is not supported by IE

**codemirror.js** line 71

```js
  function elt(tag, content, className, style) {
    var e = document.createElement(tag);
    if (className) { e.className = className; }
    if (style) { e.style.cssText = style; }
    if (typeof content == "string") { e.appendChild(document.createTextNode(content)); }
    else if (content) { for (var i = 0; i < content.length; ++i) { e.appendChild(content[i]); } }
    
    var classes = ['cm-keyword', 'cm-atom', 'cm-def', 'cm-variable',
      'cm-property', 'cm-variable-2', 'cm-variable-3, cm-type',
      'cm-meta', 'cm-qualifier', 'cm-builtin', 'cm-bracket', 
      'cm-tag', 'cm-attribute', 'cm-link'];
    className && classes.indexOf(className) > -1 && e.setAttribute('data-text', content[0].textContent);
    return e
  }
```

Example of the result HTML:
```html
<span class="cm-keyword" data-text="var">var</span> <span class="cm-def" data-text="firstRun">firstRun</span> <span class="cm-operator">=</span> <span class="cm-variable" data-text="GM_getValue">GM_getValue</span>(<span class="cm-string">"First_run"</span>, <span class="cm-atom" data-text="true">true</span>);
```

Now with CSS, certain words can be styled based on the word and CM class e.g.

```css
.cm-variable[data-text^="GM_"],
.cm-variable2[data-text^="GM_"],
.cm-variable[data-text="GM"],
.cm-variable[data-text="GM"] + .cm-property {
  color: maroon;
}
```

Example of the result:
![image](https://user-images.githubusercontent.com/6458876/99903684-16635280-2cdb-11eb-9e71-b0b10c4a3a22.png)

**Comment by marijnh** [comment]
No, sorry, this seems too narrow a use case for the amount of noise it'd add to the DOM. The recommended way to do this would be to have a custom mode add additional token classes (i.e. `"keyword var"`) and styling `.cm-var`.
