### ISSUE TITLE
is it possible to support the writing-mode: vertical-lr; ?

### ISSUE THREAD

**Issue by cuu** [codemirror/CodeMirror#6499]
I tried to set a vertical editing mode for cm

by 
```
.CodeMirror-code { 
    writing-mode: vertical-lr;    
}
```
but the CodeMirror cursor will have wired behavior, is there an easy way to the vertical job?

thanks

**Comment by marijnh** [comment]
No, vertical text direction is not supported by the library (and not likely to be supported in the future).
