### ISSUE TITLE
[javascript mode] A template string containing optional chaining breaks syntax highlighting

### ISSUE THREAD

**Issue by bomsy** [codemirror/CodeMirror#6500]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/792924/100493951-e41f7e00-313c-11eb-9fe3-895d3dc2a1d2.png">

There is no syntax highlighting after the closing curly

**Comment by marijnh** [comment]
Is this with the current version? I can't reproduce it on https://codemirror.net/mode/javascript/

**Comment by bomsy** [comment]
ahh ... was on an older version. ..thanks
