### ISSUE TITLE
Codemirror minified issue: no visible cursor in vim keyMap

### ISSUE THREAD

**Issue by BurningTreeC** [codemirror/CodeMirror#6504]
Hi, we have a problem with the current codemirror when we use it minified. The problem doesn't occur if it's not minified. The vim cursor in normal and visual mode is invisible and it appears that it's the width of the cursor that is zero in that case. We know, width is auto but it seems it doesn't get a width applied. Maybe there's a quick fix for this? Best regards, BTC

**Comment by marijnh** [comment]
CodeMirror doesn't use `Function.name` or similar things, so if minification breaks something, that's a bug in the minifier, not something we're going to investigate.
