### ISSUE TITLE
Nested template literals with nullish coalescing break syntax highlighting

### ISSUE THREAD

**Issue by TimvdLippe** [codemirror/CodeMirror#6506]
JavaScript code:

```js
const stringHighlighting = `${"any value" ?? `${"any value"}``;

function someOtherFunction() {
}
```

Is rendered as the following in CodeMirror:

![Screenshot 2020-12-03 at 11 46 09](https://user-images.githubusercontent.com/5948271/101014058-28f04e00-355d-11eb-9d39-40cf2642fd87.png)

Instead, the highlighting should look like the highlighting that is shown in the rendering of this GitHub issue. E.g. correct highlighting of the function keywords at all after the template string.

This was reported as upstream DevTools issue at https://crbug.com/1154241

**Comment by marijnh** [comment]
You're missing a closing `}` between those two backticks on the first line, making this highlighting correct. Could it be that the person reporting the original issue was using an older version of CodeMirror?

**Comment by TimvdLippe** [comment]
You are absolutely correct. The markdown syntax highlighting in this GitHub issue is therefore invalid, which threw me off. I can confirm that upgrading to CodeMirror 5.58.3 in DevTools fixes this issue, so closing this issue as invalid. Thanks for the quick reply!
