### ISSUE TITLE
Indentation issue in Scheme mode

### ISSUE THREAD

**Issue by jcubic** [codemirror/CodeMirror#6507]
I was making modification to Scheme mode to match my Scheme based lips interpreter and found issue with indentation.

`let-syntax`, `letrec-syntax`, `define-syntax` and `syntax-rules` should have 2 space indent. If you're willing to merge I can create a PR. This is how it works in GNU/Emacs (syntax-rules is little bit different in Emacs because it indent 4 spaces if you don't type `()` and press enter just after the keyword, but I think that it's fine to just add all those keywords to 2 indents).

**Comment by marijnh** [comment]
Sure, a PR would be great.

**Comment by marijnh** [comment]
Solved via #6508
