### ISSUE TITLE
Shell mode doesn't support <<<

### ISSUE THREAD

**Issue by laurentlb** [codemirror/CodeMirror#6512]
Repro:
- Open https://codemirror.net/mode/shell/index.html
- Insert a line using <<<, e.g. `sed 's/a/b/g' <<< "aaa"`
- Notice that the rest of the code has broken highlighting

Bash supports here-strings, but the syntax highlighter understands only the here-document syntax

http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Here-Strings
http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Here-Documents

**Comment by marijnh** [comment]
Does attached patch, which simply treats `<<<` as an operator, work for you?

**Comment by laurentlb** [comment]
I've tried https://codemirror.net/mode/shell/index.html and it now works fine.

Thanks for the super quick fix!
