### ISSUE TITLE
shell: << syntax gets thrown off by single quote mark

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#6513]
The following repros the issue at https://codemirror.net/mode/shell/index.html:

```bash
cat <<EOF
  line1
  line2 don't pay attention to apostrophe
EOF
```

**Comment by marijnh** [comment]
Could you tell me what the issue is? Because the highlighting looks reasonable to me and doesn't change when I delete the quote.

**Comment by takamori** [comment]
hmm. argh, sorry, I made a mistake. It looks fine.
