### ISSUE TITLE
Text selection issue

### ISSUE THREAD

**Issue by ozanthedeveloper** [codemirror/CodeMirror#6518]
I have a problem with selections in CodeMirror textarea.

When I press Ctrl+A (basically select all operation) on CodeMirror textarea, it selects text with the spaces. These spaces creating according to longest line in textarea. If you didn't understand what I mean, here is the picture:

What it looks like
![1](https://user-images.githubusercontent.com/47722606/101616740-d01f2a80-3a20-11eb-9f49-87687003b6ab.png)

It shouldn't include these parts
![2](https://user-images.githubusercontent.com/47722606/101616772-d90ffc00-3a20-11eb-98e5-e84542c5d47d.png)

So it has to be a thing similar to this
![3](https://user-images.githubusercontent.com/47722606/101618618-491f8180-3a23-11eb-8c6f-aa30154ee264.png)

I was thinking to change CodeMirror to somethink else but I thinked I must create a issue before it.

**Comment by marijnh** [comment]
That's just how CodeMirror (and many other text editors) draw the selection. There are no spaces, it just indicates that the selection continues on the next line that way. This isn't going to change.

**Comment by ozanthedeveloper** [comment]
Is there no way to change this with manupilating CSS or Javascript? Because a library named Monaco Editor can do what I want bu I still want to use it with CodeMirror.

**Comment by marijnh** [comment]
You could hide the editor's own selection with `.CodeMirror-selected { background: none !important }`, and use the `mark-selection` addon to give the selected text a class that you can style yourself.

**Comment by ozanthedeveloper** [comment]
Works like a charm! Thank you.
