### ISSUE TITLE
Typescript syntax highlighting breaks under a set of conditions

### ISSUE THREAD

**Issue by khvorov45** [codemirror/CodeMirror#6520]
Using the [sandbox](https://codemirror.net/mode/javascript/typescript.html) for examples.

<details>
<summary>Example of wrong highlighting (bottom 3 lines)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102128350-d9394d00-3ea1-11eb-9fd2-07e26e97c3be.png"/>
</details>

Most subsequent code would be highlighted in yellow as if it was all a string.

The set of conditions required for this is (images contain (mostly) correct highlighting when the corresponding condition is removed):

<details>
<summary>3+ fields in an object argument</summary>
<img src="https://user-images.githubusercontent.com/44919476/102128773-75fbea80-3ea2-11eb-9fd8-58dced27af68.png"/>
<img src="https://user-images.githubusercontent.com/44919476/102128808-814f1600-3ea2-11eb-86a8-d30b3fd0f8a8.png"/>
</details>

<details>
<summary>Generic use in the return type (highlight still questionable without it)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102128951-b9eeef80-3ea2-11eb-9417-48aa9f066e5c.png"/>
</details>

<details>
<summary>Template string use (highlight still questionable without it)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102129142-01757b80-3ea3-11eb-837c-aa33ceaf4b26.png"/>
</details>

<details>
<summary>No commas in the types for the object fields (main issue?)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102129007-cffcb000-3ea2-11eb-84e3-a17fbf3a4722.png"/>
</details>

[Code in screenshots](https://github.com/codemirror/CodeMirror/files/5691296/code.zip)

**Comment by marijnh** [comment]
Could you at least provide the _text_ for the reproduction cases, so that I don't have to type it from your screenshots?

**Comment by khvorov45** [comment]
It's in the attached ["Code in screenshots" zip file](https://github.com/codemirror/CodeMirror/files/5691296/code.zip) but sure

<details><summary>Code in screenshots</summary><p>

```ts
async function temp({
  a,
  b,
  c,
}: {
  a: string
  b: string
  c: string
}): Promise<string> {
  console.log(`string ${a}`)
  console.log(`string ${b}`)
  return "one"
}


async function temp({
  a,
  b,
}: {
  a: string
  b: string
}): Promise<string> {
  console.log(`string ${a}`)
  console.log(`string ${b}`)
  return "one"
}


function temp({
  a,
  b,
  c,
}: {
  a: string
  b: string
  c: string
}): string {
  console.log(`string ${a}`)
  console.log(`string ${b}`)
  return "one"
}


async function temp({
  a,
  b,
  c,
}: {
  a: string
  b: string
  c: string
}): Promise<string> {
  console.log("string" + a)
  console.log("string" + b)
  return "one"
}


async function temp({
  a, 
  b, 
  c,
}: {
  a: string, 
  b: string, 
  c: string,
}): Promise<string> {
  console.log(`string ${a}`)
  console.log(`string ${b}`)
  return "one"
}


async function temp(
  a: string,
  b: string,
  c: string,
): Promise<string> {
  console.log(`string ${a}`)
  console.log(`string ${b}`)
  return "one"
}
```

</p></details>

**Comment by marijnh** [comment]
Ah, sorry, didn't see the zip. The issue appears to be support for object types without separators. Can you confirm that attached patch fixes the problems?

**Comment by khvorov45** [comment]
Yes, appears to be fixed now

<details><summary>Running latest master locally</summary>

<img src="https://user-images.githubusercontent.com/44919476/102265695-92b02500-3f6b-11eb-9a2c-c6be06922041.png" />

</details>

<details><summary>Troublesome code</summary>

```ts
async function temp({
  a,
  b,
  c,
}: {
  a: string
  b: string
  c: string
}): Promise<string> {
  console.log(`string ${a}`)
  console.log(`string ${b}`)
  return "one"
}
```

</details>
