### ISSUE TITLE
[vim] split one line into multiple lines

### ISSUE THREAD

**Issue by jphua** [codemirror/CodeMirror#6521]
let's say I want to split one line
```
foo bar baz
```
into multiple:
```
foo
bar
baz
```
when typing `:s/ /\r/g` into codemirror, I get
```
foo
bar baz
```
but I get the following in actual vim
```
foo
bar
baz
```
how do I recreate vim's behavior in codemirror?

**Comment by dbarnett** [comment]
In other words, CodeMirror has a bug in its "g" flag to "Replace all occurrences in the line" so that if the substitution splits the line it forgets to continue processing the rest of the line.
