### ISSUE TITLE
LESS mode doesn't work as expected

### ISSUE THREAD

**Issue by JulianPinzaru** [codemirror/CodeMirror#6523]
I have configured codemirror in my vuejs project, it works well with html, css and javascript, but it's not applying proper parsing for text/x-less mime type. Looks like it applies the defaults for css (not LESS).  Here is a snippet I use:
```    
        import CodeMirror from 'codemirror/lib/codemirror.js';  
	import 'codemirror/lib/codemirror.css';  
	import 'codemirror/theme/twilight.css';  

	// Linting main import  
	import 'codemirror/addon/lint/lint.js';  

	// Linting javascript  
	import 'codemirror/mode/javascript/javascript.js';  
	import 'codemirror/addon/hint/javascript-hint.js';  
	import 'codemirror/addon/lint/javascript-lint.js';  

	// Linting html  
	import 'codemirror/mode/htmlembedded/htmlembedded.js';  
	import 'codemirror/addon/hint/html-hint.js';  
	import 'codemirror/addon/lint/html-lint.js';  

	// Linting css (less as well)  
	import 'codemirror/mode/css/css.js';  
	import 'codemirror/addon/lint/css-lint.js';  
	import 'codemirror/addon/hint/css-hint.js';  

	import { JSHINT } from 'jshint';  
	import { CSSLint } from 'csslint';  

	window.JSHINT = JSHINT;  
	window.CSSLint = CSSLint;  

        codeMirrorOptions: {
		'tabSize': 4,
		'mode': 'text/x-less',
		'theme': 'twilight',
		'lineNumbers': true,
		'line': true,
		'gutters': ['CodeMirror-lint-markers'],
		'lint': {
			options: {}, // Do not delete that one!
			onUpdateLinting: (annotationsNotSorted, annotations, cm) => {
                                // custom errors handler below
				this.handleErrors(annotationsNotSorted, annotations, cm);
			}
		}
	},
```

So basically my expectations is that it shouldn't throw any errors for this perfectly valid LESS snippet:
```
@primarycolor: #FF7F50;
@color:#800080;
h1 {
   color: @primarycolor;
}

h3 {
   color: @color;
}
```

The error `"Unknown @ rule: @primarycolor."`
![image](https://user-images.githubusercontent.com/51966133/102293847-c30caa80-3efc-11eb-9fc9-eef98a1fa576.png)

The settings I pass look fine to me, correct me if I am wrong. I just followed the documentation, not sure if there is anything I missed, but as I said this works well for js, html and css, so I can't see what's the problem here...

**Comment by JulianPinzaru** [comment]
I am using `"csslint": "^1.0.5"` , could it be the reason of that issue ? What version would be the right one to use ?

**Comment by marijnh** [comment]
I don't believe csslint can handle Less. Why are you expecting it to?

**Comment by JulianPinzaru** [comment]
> I don't believe csslint can handle Less. Why are you expecting it to?

I expected it because it has been mentioned in the docs that it's a css sub-mode, did I misunderstood it ?
https://codemirror.net/mode/css/less.html

If it's not, is there any workarounds to make it support it ? I tried to look into registering a codemirror helper to lint LESS, is there any compatible less linter for codemirror (akin csslint and scsslint) ?

**Comment by marijnh** [comment]
> I expected it because it has been mentioned in the docs that it's an css sub-mode, did I misunderstand it ?

Yes, csslint is an external project which, I suppose, only targets regular CSS. I don't have a workaround for that.
