### ISSUE TITLE
[closebrackets] CloseBrackets misbehaves in visual RTL mode

### ISSUE THREAD

**Issue by esm7** [codemirror/CodeMirror#6527]
When the editor direction is set to RTL with `rtlMoveVisually` set to `true` (the default in most occasions), entering an opening bracket causes a cursor jump to the wrong direction. Instead of entering a closing bracket and putting the cursor in the middle, the cursor jumps an extra character ahead, possibly to the next line if it exists.
I tried reading through the code and I believe the reason is that in `closebrackets.js`, in `handleChar`, this flow uses the `goCharLeft` command. In visual RTL moving the cursor left means moving it forward rather than backwards, so CodeMirror enters a closing bracket and moves the cursor further forward.

**Comment by marijnh** [comment]
Good point. Attached patch should help.
