### ISSUE TITLE
Firefox requires Clipboard Events for Primary Selection handling

### ISSUE THREAD

**Issue by haarp** [codemirror/CodeMirror#6538]
Hello,

CodeMirror in Firefox on Linux / X11 requires clipboard events to handle the primary selection (aka middle click paste). If clipboard events are disabled (i.e. setting `dom.event.clipboardevents.enabled` to false in `about:config`), middle clicks stop pasting the buffer, and selections don't enter the buffer.

This has been observed in two extensions that make use of Codemirror: Ublock and Violentmonkey.

Why would one disable clipboard events, you ask? Sites can hijack the middle mouse button to spy on selection contents. Try it out by middle-clicking on an emtpy spot on the main page of imgur.com! You'll see an "URL failed to upload" dialog. Thus from a security perspective, it is crucial to keep this feature disabled.

Would it be possible to use some other method to handle this? Normal text boxes handle the primary selection without needing clipboard events.

Thanks a lot!

**Comment by marijnh** [comment]
CodeMirror is a script, so if you prevent scripts from reading clipboard events, it's not going to be able to access the clipboard for you. I am pretty certain there's no workaround for this, but if you find one feel free to add another comment.

**Comment by haarp** [comment]
Gotcha, thanks.
