### ISSUE TITLE
5.59.0 broke several keys, for example Ctrl-V (paste)

### ISSUE THREAD

**Issue by greggman** [codemirror/CodeMirror#6548]
Here's a sample with 5.58.1

https://jsgist.org/?src=713138fd81ba69b6fcd75456a8547c7b

And here's the same sample updated to 5.59.0

https://jsgist.org/?src=99056e38383ca7f2dc65389a5e2be4b6

Ctrl-Z (undo) also fails in 5.59.0 but works in 5.58.1 

Also checked 5.58.3 which works

Did something change like a default configuration?

**Comment by marijnh** [comment]
Both still work for me (Firefox and Chromium Linux). What platform and browser are you testing with?

**Comment by marijnh** [comment]
Ah, this is #6532. Release 5.59.1 should help.
