### ISSUE TITLE
Scrollbar is invisible until resizing the window

### ISSUE THREAD

**Issue by falsandtru** [codemirror/CodeMirror#6562]
In the following example, CodeMirror's scrollbar is invisible until resizing the window or typing `v`.

https://falsandtru.github.io/securemark/

Looks like the styles are not set.

```html
<div class="CodeMirror-vscrollbar" tabindex="-1" cm-not-content="true"><div style="min-width: 1px; height: 0px;"></div></div>
```

**Comment by marijnh** [comment]
I didn't look too closely into that page, but this happens when the editor is initialized without being visible yet. Call its `refresh()` method when it becomes visible or load the autorefresh addon to work around it.
