### ISSUE TITLE
CodeMirror inside Bootstrap Card Body not having full height

### ISSUE THREAD

**Issue by Jithin-C-V** [codemirror/CodeMirror#6570]
Hi,

Thanks in advance for any help. Also sorry if this is already answered somewhere. I tried search, not found anything.

I have placed the editor div inside a bootstrap card body and in one row. I need to have the CodeMirror in full height of Card Body.

How to achieve it ?

```
            <div class="card" style="height: 75vh;">
              <div class="card-body">
                <div class="row mb-3">
                  <div class="col-12 some-actions justify-content-center">
                    <div class="some-action">
                      <!-- Area For Custom Buttons -->
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12">
                    <div class="codeArea">
                      <textarea id="script-editor"></textarea>
                    </div>
                  </div>
                </div>
              </div>
            </div>
```

**Comment by marijnh** [comment]
There's not really enough information in there for me to know what's going on. But if the wrapper element uses flexbox layout, that has caused problems before. Adding an additional wrapper element around the editor usually helps for that.

**Comment by Jithin-C-V** [comment]
> There's not really enough information in there for me to know what's going on. But if the wrapper element uses flexbox layout, that has caused problems before. Adding an additional wrapper element around the editor usually helps for that.

All the DIV Class mentioned above are from bootstrap 4. What details you required extra to support me ?

The parent class `.card` is having `display:flex`.
The code mirror initializing on `<textarea id="script-editor"></textarea>` which is inside class `.codeArea` which is having `display: block`

**Comment by marijnh** [comment]
Were you expecting the outer flexbox to force the editor height to the full height of the card-body? I don't think CSS works that way—there's a whole bunch of other elements (row, col-12) between those that compute their own height. You could try to explicitly size them, but that's a bit awkward because card-body has a padding, so they shouldn't be 100% of their parent either. In any case, I don't think this is a CodeMirror problem.
