### ISSUE TITLE
Some TypeScript syntax errors (still) cause infinite loops

### ISSUE THREAD

**Issue by garybernhardt** [codemirror/CodeMirror#6571]
This is a continuation of #6542. The commit to fix that (d2728850abe64849ddd2730dc22536ef1361a90a) did make the bug reproduction code that I provided stop going into an infinite loop. However, other TS syntax error still cause infinite loops. Here's a reproduction script. This is identical to the script in #6542 except that:

1. It's running against the latest CodeMirror version (5.59.1, which contains the fix in d2728850abe64849ddd2730dc22536ef1361a90a).
2. It uses a different TypeScript code example to show that the bug still exists. (The original code example from #6542 no longer causes an infinite loop).

As before, opening this HTML file will lock your browser tab, pinning the CPU. Flipping `demonstrateBug` to false will change only the code in the CodeMirror editor, which prevents the infinite loop, showing that the bug is sensitive to specific types of invalid TS syntax.

```html
<!doctype html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.1/codemirror.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.1/codemirror.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.1/mode/javascript/javascript.min.js"></script>

    <script>
      document.addEventListener("DOMContentLoaded", function() {
        const textarea = document.getElementById("editor")
        const editor = CodeMirror.fromTextArea(textarea, {
          mode: "text/typescript",
        });

        const demonstrateBug = true;
        let code;

        if (demonstrateBug) {
          code = `function extractEmail({email}: {): string {
  return email;
}`;
        } else {
          code = `const x = 1;`;
        }
        editor.setValue(code)
      })
    </script>

  </head>
  <body>
    <textarea id="editor"></textarea>
  </body>
</html>
```

**Comment by garybernhardt** [comment]
(I forgot to mention: we sponsor CodeMirror (https://www.executeprogram.com/). Thanks for your work on this project!)

**Comment by marijnh** [comment]
Ah, how embarrassing. Attached patch should fix it. (If you are able to upgrade to CodeMirror 6, the LR parser approach in the new JavaScript syntax makes these kind of bugs mostly impossible by construction—modulo issues in hand-written tokenizers or the library, of course).

**Comment by garybernhardt** [comment]
Thanks for the quick fix again!

I took a look at the CodeMirror 6 site... the fact that some systems are already using it in production is promising! I'll probably give the upgrade a try the next time I need to change our editor behavior.
