### ISSUE TITLE
line number appears to be wrong when last line is not trailed by something

### ISSUE THREAD

**Issue by leomcelroy** [codemirror/CodeMirror#6575]
Thanks so much for this great project. It's been really helpful to me.

I think this may be a bug. I've demonstrated below with some screenshots.
The selected line obtained with codemirror.getCursor().line is indicated by the console log.

![Screen Shot 2021-01-22 at 3 32 05 PM](https://user-images.githubusercontent.com/27078897/105542245-02ca6d00-5cc7-11eb-9ada-19997f0f71b2.png)

Right off the bat this seems odd because I didn't think there was any line which corresponded to 0.

Now if I add a blank line below and select the first line again the line number increments by one (to what I believe is the correct line number).

![Screen Shot 2021-01-22 at 3 32 53 PM](https://user-images.githubusercontent.com/27078897/105542308-22619580-5cc7-11eb-88b0-1c4c258dcc33.png)

**Comment by marijnh** [comment]
Line numbers are 0-based. The line number for the first line will stay 0, regardless of whether it's the last line in the document—I really don't think it is changing.

**Comment by leomcelroy** [comment]
Thanks for your quick response, perhaps my example was unclear but if that's that case I'm not sure how it accounts for why I'm seeing this.

![Screen Shot 2021-01-23 at 7 59 10 AM](https://user-images.githubusercontent.com/27078897/105578903-65684b00-5d51-11eb-81d8-869af5ef107d.png)

In this scenario there is no line 0 and I would expect the lines to be line 1 and line 2 given what I've observed or line 0 and line 1 given what you're suggesting.

Now if I were to add a blank line at the bottom the line numbers that get logged for each selection become:

![Screen Shot 2021-01-23 at 8 04 14 AM](https://user-images.githubusercontent.com/27078897/105578932-9779ad00-5d51-11eb-9574-bcd359fd614d.png)

**Comment by marijnh** [comment]
I tried, but I'm not seeing this, so I suspect it's related to the way you're querying the line numbers.

**Comment by leomcelroy** [comment]
Thanks for looking into it. Upon further investigation it appears that the situation only occurs when triple clicking a line. So if you try to extract the line number when triple clicking  (event.detail === 3) a line (which highlights the whole line) you actually get the line number of the next non-highlighted line.

Another consequence of this is that it doesn't seem your able to select line 0 when triple clicking. I'm not sure if this is intended or not but just wanted to note in case someone else encounters the issue when trying to figure out how to get the line number when triple clicking. I decided to save the numbers from the first click and just use that.

Thanks again.

**Comment by marijnh** [comment]
Triple-clicking a line selects from the start of the line to the start of the next line, except on the last line, where it'll just select to the end of the line because there is no next line.
