### ISSUE TITLE
VoiceOver speaks line numbers

### ISSUE THREAD

**Issue by nonplus** [codemirror/CodeMirror#6578]
I have CodeMirror configured with `inputStyle="contenteditable"` and displaying line numbers and code folding.  On the Mac, when using VoiceOver in Chrome, the contents of the gutter (line number and disclosure) is voiced by the screenreader, which confuses users.  This happens when the entire page is being read, or when there is a multiline selection inside of the editing area.

FWIW, I do not have this problem in Chrome when using the NVDA screen reader on Windows.

As a workaround, I'm hiding the gutter area from screen readers by setting `aria-hidden="true"` on `.CodeMirror-gutter-wrapper` elements, but that feels like a hack.

**Comment by marijnh** [comment]
Please take a look at the [version 6 rewrite](https://codemirror.net/6/), which has been designed with screen readers in mind. The experience with version 5.x is probably never going to be great, but if you have a patch that improves this (I think the code currently misguidedly uses role=presentation for line numbers, and aria-hidden would be a better approach.
