### ISSUE TITLE
Feature Request: ``J`` Mode

### ISSUE THREAD

**Issue by nathanesau** [codemirror/CodeMirror#6583]
Support syntax highlighting for J language (https://github.com/codereport/jsource).

I will probably implement this myself using some of the other modes as reference.

**Comment by marijnh** [comment]
We aren't taking feature requests for languages—new languages have to be maintained and distributed separately, outside of the core library (see for example the [elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir)).
