### ISSUE TITLE
TAB char expands current line

### ISSUE THREAD

**Issue by oynozan** [codemirror/CodeMirror#6590]
When I press TAB line expands. A long time ago I had solved it with changing theme but now this issue exists on every theme. I tried in "Cobalt" and "Xq-light" theme.

![1](https://user-images.githubusercontent.com/47722606/107892711-03f26100-6f38-11eb-9fe0-681a03970b70.png)
![2](https://user-images.githubusercontent.com/47722606/107892712-048af780-6f38-11eb-80be-cecd10ab9b07.png)

**Comment by marijnh** [comment]
I think this may be related to the font you're using or the style you're applying to `cm-tab` elements. It doesn't appear to happen in, for example, the demos on the website.

**Comment by oynozan** [comment]
It made sense and I removed the font but still, the problem exists.

**Comment by marijnh** [comment]
Interesting. You'll have to try to reduce this to the minimal possible setup to see what's causing it then (since, again, it doesn't appear in typical setups of the editor).

**Comment by oynozan** [comment]
Yeah I'm removing the lines from CSS file one by one. If I figure out I'll tell you.

**Comment by oynozan** [comment]
Okay I figured out the problem, it's not about the library, I changed the Codemirror.css long time ago and this line causes the problem:
`.CodeMirror pre span {padding:5px 0;}`
