### ISSUE TITLE
Support edit/continuelist.js in mode: gfm

### ISSUE THREAD

**Issue by JasonEtco** [codemirror/CodeMirror#6592]
Hello! I'm not sure if this is a bug or a feature request, but it'd be great to support the `continuelist.js` behavior in `gfm`. It works great in `markdown`, and I don't see a reason it shouldn't be supported in `gfm`.

There's a check for the mode here:

https://github.com/codemirror/CodeMirror/blob/9d0f9d19de70abe817e8b8e161034fbd3f907030/addon/edit/continuelist.js#L26-L32

And I believe that this file is conditionally included for `mode: 'markdown'`, but I'm not sure where. Happy to open a PR if y'all can point me in the right direction!

**Comment by marijnh** [comment]
It already _does_ work with the gfm mode, you just have to load an enable it yourself. See the [Markdown demo](https://codemirror.net/mode/markdown/index.html)'s source for an example.

**Comment by JasonEtco** [comment]
You're absolutely right - thanks for the quick advice @marijnh 🙏
