### ISSUE TITLE
Seems allowDropFileTypes does not disallow other file types

### ISSUE THREAD

**Issue by crystalfp** [codemirror/CodeMirror#6595]
Codemirror 5.59.2 on Window 10 in Chrome.

I create an editor using the `allowDropFileTypes` option. But seems the editor continues to accept `"text"` and `"text/plain"` file types even if I set an impossible file type to be accepted like: `allowDropFileTypes: ["impossible/impossible"]`.

I'm dropping items from other parts of the application and the data has various types: `"internal/project"`, `"text/html"` and `"text/plain"`. The last two are needed if I drop the item to an external editor or MS Word. I can allow or disallow dropping on other part of the application based on `"internal/project"` without problems.

There is a seemingly related issue #6098 still open.

Bug or am I missing something?
Thanks for your help!
mario

**Comment by marijnh** [comment]
Looking at the code, there's no exception for text files. Could it be that the browser converts such drops into plain text drops, bypassing the `dataTransfer.files` mechanism?

**Comment by crystalfp** [comment]
I think I have found the cause of my problem. The problems with `allowDropFileTypes` not filtering file types remains, but the specific problem comes outside CodeMirror.

My problem is originated by the source of the drag. I take an entry from a list managed by [Sortable.js](https://sortablejs.github.io/Sortable/). This library uses drag and drop to reorder the list elements and uses internally a setData of type `"Text"`. Seems this data type interferes somehow with my data that has a type of `"text/plain"`. Unfortunately if I add to the dragged item a file type of `"internal/project"` modifying `allowDropFileTypes` to `["internal/project"]` this data is not selected by CodeMirror. Other parts of the code accept without problem this type for the dropped item.

ASAP I will try to print the real set of data types my dragged item has and will be back.
Thanks again!
mario

**Comment by crystalfp** [comment]
In `dragover` handler the `event.originalEvent!.dataTransfer!.types` list contains `["text/plain", "internal/project"]` so my theory works only if Sortable.js overwrites `text/plain` entry. Or maybe there is another, parallel, data path besides setData() that I ignore...

Anyway, my understanding is that setting `allowDropFileTypes: ["impossible/impossible"]` should block all dropping in CodeMirror. Right? If yes, this does not work right now.

Thanks a lot!
mario

**Comment by marijnh** [comment]
> Anyway, my understanding is that setting allowDropFileTypes: ["impossible/impossible"] should block all dropping in CodeMirror. Right?

No, that only block dropping of _files_ with those mime types.

**Comment by crystalfp** [comment]
Ah, now understand! So I had a basic misunderstanding of this option. Sorry for the time I made you lost on this.
