### ISSUE TITLE
Scrollbar filler is transparent and shows text behind it.

### ISSUE THREAD

**Issue by TimvdLippe** [codemirror/CodeMirror#6599]
In #6485 the scrollbar filler was changed to be transparent. As a result of that change, the text in a CodeMirror text editor can now be shown behind the filler. For some screenshots and a video of the issue, please see https://bugs.chromium.org/p/chromium/issues/detail?id=1180740

For now, we have locally reverted this particular change in DevTools: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2714547 I had attempted to let CodeMirror use `background: inherit` and `background: initial`, but neither of these works. Ideally we can figure out a solution in CodeMirror so that we can remove our local patch.

**Comment by marijnh** [comment]
Oh, wow, not sure how I didn't catch that. Making it transparent completely defeats the purpose of having this element in the first place. I've reverted the patch, will make a patch release.
