### ISSUE TITLE
Syntax highlighting breaks for `import.meta.url` inside template string

### ISSUE THREAD

**Issue by TimvdLippe** [codemirror/CodeMirror#6603]
The syntax highlighter for an `import.meta.url` usage inside a template string breaks and turns all later text orange (the color of the template string).

Example code:

```html
<script type="module">
    const test=`${ import.meta.url }`;
    console.log( "hello, world" );
    debugger
</script>
```

Rendered output:

![Screen Shot 2021-02-25 at 16 48 36](https://user-images.githubusercontent.com/5948271/109186916-4eba7700-7789-11eb-9f77-700166cd0fea.png)

Reported downstream at https://bugs.chromium.org/p/chromium/issues/detail?id=1166646

**Comment by marijnh** [comment]
Attached patch should help with this.
