### ISSUE TITLE
Julia: parentheses are not properly matched

### ISSUE THREAD

**Issue by XRFXLP** [codemirror/CodeMirror#6609]
Almost same as #6534 

![image](https://user-images.githubusercontent.com/23459568/109590622-5041c180-7b32-11eb-9ca3-a3f08b629bc9.png)
![image](https://user-images.githubusercontent.com/23459568/109590664-618ace00-7b32-11eb-8eab-e3144de4709c.png)
![image](https://user-images.githubusercontent.com/23459568/109590642-5899fc80-7b32-11eb-9388-ce1e8ae2d653.png)

Browser: Brave 1.2

**Comment by marijnh** [comment]
Attached patch should help with this.
