### ISSUE TITLE
Bottom line when typing

### ISSUE THREAD

**Issue by felipeacelino** [codemirror/CodeMirror#6611]
When I'm typing, the text appears on the bottom line.
I'm using Bootstrap 4.5.

![codemirror_bug](https://user-images.githubusercontent.com/17582743/109826002-21524b00-7c19-11eb-9351-3bc458bbceda.gif)

```
const myTextArea = document.getElementById('code-editor');
const editor = CodeMirror.fromTextArea(myTextArea, {
  mode: 'application/xml',
  lineNumbers: true,
  smartIndent: true,
  matchBrackets: true,
  lineWrapping: true,
  indentWithTabs: true,
});
```

**Comment by marijnh** [comment]
This is probably a problem with external CSS. Try disabling CSS until the problem goes away to figure where it's coming from.

**Comment by felipeacelino** [comment]
That was exactly the problem!

I had some styles for the `<pre>` tag. To solve it, I just modified the style by removing the classes from the `<pre>` tag used in the plugin.

```
// PHP Debug
pre:not(.CodeMirror-line-like):not(.CodeMirror-line) {
  ...
}
```
Thank you very much!
