### ISSUE TITLE
Autocomplete picklist width grows until infinite

### ISSUE THREAD

**Issue by dani7cl** [codemirror/CodeMirror#6614]
**Issue**
When the text of the suggestions is bigger than the container, the width equals the size of the biggest text,  even goes outside of the viewport making it unusable
<img width="178" alt="Screenshot 2021-03-05 at 13 47 52" src="https://user-images.githubusercontent.com/15110589/110117858-c3a93480-7db9-11eb-8e7a-4f602e15e3a5.png">
<img width="1095" alt="Screenshot 2021-03-05 at 13 49 53" src="https://user-images.githubusercontent.com/15110589/110117843-bc822680-7db9-11eb-8362-181749f68ee0.png">

**Expected behaviour**
Suggestions are shrinked to fit the parent component

<img width="749" alt="Screenshot 2021-03-05 at 13 44 04" src="https://user-images.githubusercontent.com/15110589/110117855-c146da80-7db9-11eb-86e0-cfc0d4b42727.png">

**Comment by marijnh** [comment]
Attached patch limits the width to the minimum of 700px or 95% of the viewport. Tooltips intentionally aren't contained inside the editor, since that would often get very cramped.

**Comment by marijnh** [comment]
Not sure why the patch wasn't automatically linked, but I meant patch https://github.com/codemirror/autocomplete/commit/45b277af094d22235abc3510c22f3d18f0f782d7
