### ISSUE TITLE
Shift+Tab unindent issue in Python

### ISSUE THREAD

**Issue by oTree-org** [codemirror/CodeMirror#6615]
Using the official Python demo: https://codemirror.net/mode/python/

Paste in this code:

```
    if 1:
        p = 1
    if 2:
        p = 2
```

Select all text then try Shift+Tab to unindent it. 

I expected this:

```
if 1:
    p = 1
if 2:
    p = 2
```

But got this:

```
if 1:
    p = 1
    if 2:
        p = 2
```

This issue is also described here: https://github.com/LightTable/Python/issues/41

**Comment by marijnh** [comment]
Shift-tab doesn't unindent by default (ctrl/cmd-[ does). Shift-tab auto-indents, and since python indentation isn't unambiguous from source, that may change the code.

**Comment by oTree-org** [comment]
OK I see, thank you for the explanation.
