### ISSUE TITLE
Simple mode: Cannot use empty string matching for last group of regex

### ISSUE THREAD

**Issue by Billiam** [codemirror/CodeMirror#6618]
I think this is a bug, but might just be a documentation issue.

It seems like simple mode's regex can match an empty string for any group _except_ the last group of the regex.
Otherwise, `Uncaught TypeError: Cannot read property 'text' of undefined` will be thrown when entering on the next line (see video)

I believe matching an empty string is intended behavior, based on the solution given in #5374

Example: https://codepen.io/billiam/pen/poNxZMw

https://user-images.githubusercontent.com/242008/110401496-4858b480-803f-11eb-818f-2c4a46485469.mp4

**Comment by marijnh** [comment]
That was a bug. Attached patch should fix it.
