### ISSUE TITLE
Textarea with autofocus attribute is not focused in contenteditable mode

### ISSUE THREAD

**Issue by cwfoo** [codemirror/CodeMirror#6624]
According to the documentation about the `autofocus` option:

> autofocus: boolean
>
> Can be used to make CodeMirror focus itself on initialization. Defaults to off. **When fromTextArea is used, and no explicit value is given for this option, it will be set to true when either the source textarea is focused, or it has an autofocus attribute and no other element is focused.**

In contenteditable mode, when I use `fromTextArea` on a textarea with an autofocus attribute, the textarea is not focused.

CodeMirror version: 5.59.4
Browser: Firefox 86.0 on Ubuntu 20.04

**Comment by marijnh** [comment]
Attached patch should help here.
