### ISSUE TITLE
adding an m4 mode

### ISSUE THREAD

**Issue by ebblake** [codemirror/CodeMirror#6625]
I noticed that while you have syntax formatting for a number of languages, you are lacking it for m4. There are a few keywords (such as define, incr, substr, ...), comments (# to newline), as well as substitutions like $1, $2 which at least the emacs mode for m4 is able to colorize. https://github.com/jwiegley/emacs-release/blob/master/lisp/progmodes/m4-mode.el could serve as inspiration.

**Comment by marijnh** [comment]
We're not adding new language modes to the distribution. You could implement one yourself, and distribute it separately, if you need to.
