### ISSUE TITLE
Complex accents don't display well on chrome-based browsers

### ISSUE THREAD

**Issue by smartlitchi** [codemirror/CodeMirror#6626]
I am writing in Vietnamese and the accents on words like `rất, rồng, nguyễn, hổi` overlap on chrome-based browsers but not on firefox. You can see the result in both browsers here :

- Chromium : 
![chromium-screenshot](https://user-images.githubusercontent.com/56811153/111914605-ea7e9080-8a72-11eb-8aad-699196aafd1f.png)
-  Firefox : 
![firefox-screenshot](https://user-images.githubusercontent.com/56811153/111914653-1d288900-8a73-11eb-8fc4-2028d72eb68b.png)

For good measure, I tried on Codemirror version 6 and I couldn't reproduce the issue.

**Comment by marijnh** [comment]
Could this be font-related? I don't know all that much about accent rendering, but the editor shouldn't really be able to interfere with that. You could try turning off CSS rules and see if that helps (maybe the `font-variant-ligatures: contextual` one is related?).

**Comment by smartlitchi** [comment]
Could you confirm that you see the accents rendered correctly on Chrome in CodeMirror ? What makes me think that it is an issue with CodeMirror is that I can't reproduce it with Version 6.

**Comment by marijnh** [comment]
On Chrome Linux they look different (probably still wrong, but they look like that in all contexts in Chrome)—the second accent is rendered above the letter after the one that actually has the accents.

**Comment by smartlitchi** [comment]
You were right, it was a font problem. Thank you !
