### ISSUE TITLE
Syntax highlighting of variable usage in outer for-loop is missing

### ISSUE THREAD

**Issue by TimvdLippe** [codemirror/CodeMirror#6627]
For the first definition of a for-loop, the variables in the stop-condition and increment-statement are not getting colored as variables. Subsequent definitions of the for-loop are correct and are showing the correct color.

```js
for (var i = 0; i < arr.length; i++) {
  for (var k = 0; k < arr.length; k++) {
   
  }
}
```

Screenshot:

<img width="651" alt="Screen Shot 2021-03-22 at 11 54 22" src="https://user-images.githubusercontent.com/5948271/111986084-61fd0000-8b05-11eb-84e1-23d650ae5745.png">

The expected coloring would be that the `i` in both `i < arr.length` and `i++` would be colored in the same way as the `k` in the sequent for-loop.

Reported downstream as https://bugs.chromium.org/p/chromium/issues/detail?id=1187980

**Comment by marijnh** [comment]
The blue color on the uses of `k` indicates this is a local variable, as opposed to `i` which is highlighted as a global variable.

That is of course still incorrect, since the way `var` works means they are both global. The scope handling in the mode is somewhat simplistic.

Given that info, how do you want to proceed with this?

**Comment by TimvdLippe** [comment]
Ah good catch! That said, it seems that using `let` will show the same behavior:

![Screen Shot 2021-03-22 at 12 43 26](https://user-images.githubusercontent.com/5948271/111991448-40534700-8b0c-11eb-897a-e1568a6ef081.png)

I personally don't have any strong opinions on this, as long as it is consistent. I just tried out generic a let-assignment:

![Screen Shot 2021-03-22 at 12 44 41](https://user-images.githubusercontent.com/5948271/111991632-6d9ff500-8b0c-11eb-837f-437491630b74.png)

Based on that behavior, I think it would make the most sense to remove the highlighting from `k` and keep all variable usages consistent (e.g. a black text color).

**Comment by marijnh** [comment]
Attached patches improve scope tracking for `for` loops, but also add an option to turn off local variable detection entirely (`mode: {name: "javascript", trackScope: false}`), if that's what you prefer. Does that work for you?

**Comment by TimvdLippe** [comment]
The first patch resolves our downstream issue and therefore would be sufficient for us. Thanks for fixing it so quickly!

With regards to the option: increased flexibility is great and might be useful in the future, but I think it won't be necessary to be used by DevTools with the bugfix in the first patch. Therefore if you want to keep the option for the future, feel free to do so, but I would also be fine with CodeMirror not shipping the option.

**Comment by TimvdLippe** [comment]
@marijnh I have applied the first patch to DevTools and I consider the downstream bug closed. Therefore, I would be okay with closing this issue as resolved, WDYT?

**Comment by marijnh** [comment]
Great, thanks for the feedback. The `trackScope` option is just a few lines of code and might come in useful for someone else, so I'll leave it in.
