### ISSUE TITLE
Pressing escape on JavaScript "confirm()" breaks CodeMirror

### ISSUE THREAD

**Issue by cmason3** [codemirror/CodeMirror#6628]
Running CodeMirror 5.59.4 on Chrome 89.0.4389.90 as well as Microsoft Edge 89.0.774.57 (Windows 10 64Bit), there seems to be an issue if we use a JavaScript `confirm()` dialogue anywhere in the web page.

Using the code at the bottom, if you click on the button and then close the confirmation dialogue using the escape key then you can no longer type in the CodeMirror window using the keyboard.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.4/codemirror.min.css">
    <style>
      .CodeMirror { border: 1px solid lightgray; width: 500px; height: 300px; }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.4/codemirror.min.js"></script>
    <script>
      window.onload = function() {
        window.cmData = CodeMirror.fromTextArea(data, {
          autofocus: true
        });
      };
    </script>
  </head>
  <body>
    <textarea id="data"></textarea>
    <button onclick="confirm('Are You Sure?')">Click and Press ESC then try and type in CodeMirror</button>
  </body>
</html>
```

**Comment by marijnh** [comment]
This seems to be a bug in Chrome/Blink—I can produce the exact same problem with a plain textarea. So that's annoying, but you'll have to try to report it with the Chrome people.
