### ISSUE TITLE
Feature request: autocompletion (ctrl-p, ctrl-n)

### ISSUE THREAD

**Issue by RhvdG** [codemirror/CodeMirror#6635]
I realise no-one is actively developing this aspect of CodeMirror, but it can't hurt to list this as a feature request: autocompletion (ctrl-p, ctrl-n). It would be very convenient to have this in Obsidian.

**Comment by marijnh** [comment]
Sorry, but this doesn't really describe what it's asking for (I have no idea what ctrl-p and ctrl-n are supposed to do), and the `show-hint` addon provides what most people call autocompletion. Going to close this issue.

**Comment by RhvdG** [comment]
OK.
