### ISSUE TITLE
codemirror.js is not located in the /lib folder in the release

### ISSUE THREAD

**Issue by mitcht** [codemirror/CodeMirror#6640]
Am I overthinking this?  I was trying to get codemirror to work using cdns, etc and I thought, "oh heck i'll just clone the repo and see how they do it there".

..Only to find that index.html tries to load in codemirror.js from the /lib folder, but its not there.

**Comment by marijnh** [comment]
It's created by the build process. Use the npm package or the zip files from the website to get a built library.
