### ISSUE TITLE
Makefile syntax support

### ISSUE THREAD

**Issue by inem** [codemirror/CodeMirror#6641]
Make is a great tool even for [modern development](https://makefile.site/).
There's a bunch of projects depending on CodeMirror, which I'd like to have Makefile syntax highlight support.

I know that there's a [closed issue](https://github.com/codemirror/CodeMirror/issues/5408) for this, but please keep this one open, because I posted [reward for it on bountysource.com](https://www.bountysource.com/issues/97590166-makefile-syntax-support)

**Comment by marijnh** [comment]
No PR to add a new mode is going to be merged in this repository, so a Makefile mode would have to live in its own package, and I don't think this is the appropriate place for this issue, bountysource or not.

**Comment by V-Lor** [comment]
@inem , check the update on BountySource.
