### ISSUE TITLE
Markdown Demo autoindent mixes tabs and spaces

### ISSUE THREAD

**Issue by jonschull** [codemirror/CodeMirror#6645]
The Markdown demo at https://codemirror.net/demo/folding.html mixes spaces with a tab as illustrated here:

![image](https://user-images.githubusercontent.com/53673/113957658-a36ff980-97ed-11eb-966e-1a3f37ef0faf.png)

Here's the result, illustrated by replacing tab with ====  and space with :

![image](https://user-images.githubusercontent.com/53673/113958305-d961ad80-97ee-11eb-8908-9e9a885265f5.png)

I find similar misbehavior when I use this simple code:
`CodeMirror.fromTextArea(document.getElementById('my-code'), config);", config={
        'theme': 'darcula',
        'lineNumbers': True
    })
`

**Comment by jonschull** [comment]
P.S. What I want is  no tab characters:
    four-space indents when I hit the tab key
    all-space indents from auto-indent

Thanks!

**Comment by marijnh** [comment]
The default Tab binding doesn't autoindent. It just inserts a tab. You'll want to bind it to something else if you want different behavior.
