### ISSUE TITLE
startScroll is undefined error

### ISSUE THREAD

**Issue by shucon** [codemirror/CodeMirror#6656]
I'm getting `startScroll is undefined` error when trying to reproduce https://github.com/phpmyadmin/phpmyadmin/issues/16793.

I've narrowed down the issue to this change in the commit https://github.com/codemirror/CodeMirror/blob/f4b04da36d5c88762382db44651b0b5389077bac/addon/hint/show-hint.js#L274 which causes the issue here: https://github.com/codemirror/CodeMirror/blob/f4b04da36d5c88762382db44651b0b5389077bac/addon/hint/show-hint.js#L322

**Comment by marijnh** [comment]
Looks like that patch indeed caused a regression there. Attached patch should help.

**Comment by williamdes** [comment]
> Looks like that patch indeed caused a regression there. Attached patch should help.

Thank you @marijnh !
Will wait for a release to update phpMyAdmin to it
