### ISSUE TITLE
JSX mode syntax highlighting issue on ES6 string interpolation

### ISSUE THREAD

**Issue by yenoiwesa** [codemirror/CodeMirror#6662]
Hi there 👋 

We found an issue with syntax highlighting using the JSX mode related to ES6 string interpolation.

This issue can be reproduced on the demo page: https://codemirror.net/mode/jsx/index.html
With the following code:
```jsx
mountWithDi(
    <Something />,
    [
      useUserPreferencesValue,
      mockUsePreferencesValue.mockReturnValue([
          `${mockPastDateSevenDays}`,
          mockUserPreferencesSetter,
      ]),
    ],
);
```

The output of the highlighting stops working after the string end token:
![image](https://user-images.githubusercontent.com/1464666/115806531-46e61e80-a42a-11eb-804a-b11eb486fb2e.png)

This is happening on the latest version of CodeMirror `5.61.0`.

Thank you for the awesome library :-)

**Comment by marijnh** [comment]
Attached patch should help here.

**Comment by yenoiwesa** [comment]
Thank you so much for already having fixed this! Legend.
