### ISSUE TITLE
Read-only editor should have a special CSS class so it can be customized in CSS

### ISSUE THREAD

**Issue by viridium** [codemirror/CodeMirror#6669]
When made read-only, an editor should be given a special CSS class so that we can customize read-only editors. For instance, I'd like to mark my read-only editors with a grey background to indicate they are not editable.

**Comment by marijnh** [comment]
You can just add it yourself when you enable the readOnly option (`cm.getWrapperElement().classList.add("...")`).

**Comment by viridium** [comment]
Thanks. I was already aware of that option when I started this ticket, though. The point was that CodeMirror can make the task of customizing the visual aspect of a read-only editor easier for clients. Anyway, if the appetite isn't there to add this support, that's fine by me.
