### ISSUE TITLE
Keystrokes do not work for Vim bindings

### ISSUE THREAD

**Issue by Edenharder** [codemirror/CodeMirror#6670]
I tested the Vim bindings in the webpage of CodeMirror, almost any keystrokes except the arrows do not work. I have thought that it was a problem of the browser Firefox, then I tested Chromium and other browsers, same problem was still there.

My OS is Archlinux. Well, with same version of Firefox on Windows10, it works. In fact, even I use the installation media on the USB, it also works. It seems that I have some mistake in the configuration of the system. The problem might be related with keyboard mappings. But I have no idea how to dig into it further.

What kind of further information do I need to provide?

A similar issue has been reported [here](https://github.com/axelfahy/jupyterlab-vim/issues/33)

**Comment by marijnh** [comment]
Do key bindings like Ctrl-D (for delete-line) work in the other CodeMirror demos for you?

**Comment by Edenharder** [comment]
`Ctrl-D` does works in other CodeMirror demos. As I have tested for the Vim demo, 
`Ctrl-D`: go half page down
`Ctrl-U`: go half page up
`Ctrl-V`: visual mode
That's all.

**Comment by Edenharder** [comment]
I just deleted some unnecessary packages and updated the system, now it works. Although I have no idea what has happened.

**Comment by Edenharder** [comment]
Finally, I find out the reason. It's a problem with my input method. The Vim demo works fine if I just switch to the normal input method.
