### ISSUE TITLE
CSS height behaviour is incorrect.

### ISSUE THREAD

**Issue by chaosprint** [codemirror/CodeMirror#6674]
See this codepen:

https://codepen.io/chaosprint/pen/KKajbLN

```
<div id="editor"></div>
```
```
CodeMirror(document.getElementById('editor'), {
	lineNumbers: true
})
```
```
body {
	padding: 0;
	margin: 0;
}

.CodeMirror {
	border: 1px solid red;
	height: 90%;
	font-size: 20px;
}

/* #editor {
	border: 1px solid blue;
	height: 90%;
} */
```

The CSS part I comment out does not work either.

I know I can call ```setSize``` to solve it, or

```
.CodeMirror {
	height: 100vh;
}
```
can work. But to be responsive requires more work then.

The behaviour in the codepen is very against intuition, isn't it?

**Comment by marijnh** [comment]
I don't think CodeMirror can do anything about this—it's CSS behavior (as should be obvious from the fact that your own div also won't set its height in this case).
