### ISSUE TITLE
Visual bug when reloading the website. 

### ISSUE THREAD

**Issue by pheralb** [codemirror/CodeMirror#6676]
I am working on a small website where I use Codemirror quite a lot for almost all the textareas. I use jQuery to convert all textareas and implement Codemirror (using Angular 11 and importing both css/js from codemirror into angular.json):

HTML ->
`<textarea class="json_editor" rows="5"></textarea>`

JS ->
`var textareas = document.querySelectorAll(".js_editor");
  for (var i = 0; i < textareas.length; i++) {
    CodeMirror.fromTextArea(textareas[i], {
      lineWrapping: true,
      mode: "javascript",
      theme: "base16-dark",
      readOnly: true,
      lineNumbers: true
    });
  }`

The problem is that if I reload the site for the first time, Codemirror loads perfectly, but I reload again and the Codemirror components do not load.

Website URL: https://www.strap.ga/docs/nextjs

First time running the website ->
![image](https://user-images.githubusercontent.com/62877300/117297562-490a9d00-ae6e-11eb-8e9c-e31698759a5c.png)

Second time running the website (press F5) ->
![image](https://user-images.githubusercontent.com/62877300/117297675-663f6b80-ae6e-11eb-86e7-789cec1d9eff.png)

Is there any solution so that this bug does not happen? Thank you very much!

**Comment by marijnh** [comment]
This sounds like a problem in your integration, rather than an issue in the library. If you can reduce it to an obvious malfunction in the library, feel free to add more information. But for now, I'm closing this.
