### ISSUE TITLE
Cursor not visible at the right edge

### ISSUE THREAD

**Issue by stasoid** [codemirror/CodeMirror#6686]
OS: Windows 10 64 bit
Browser: Chrome 90.0
CodeMirror: 5.61.0

When keyboard right arrow button is pressed at the right edge of the view the cursor becomes hidden:
![Animation](https://user-images.githubusercontent.com/2577509/118207319-3869b080-b486-11eb-84d3-729e6bb5b572.gif)
This also happens when End button is pressed.

For Consolas it happens with size 14pt or bigger.

|    |  inputStyle: "textarea"      |   inputStyle: "contenteditable" |
|----|  ----------                  |   -------------                 |
|11pt|  always visible              |   always visible                |
|12pt|  disappears periodically     |   always visible                |
|13pt|  always hidden               |   disappears periodically       |
|14pt|  always hidden               |   always hidden                 |

This issue becomes more pronounced with bigger size.
At 15pt or higher not only cursor is not visible, but also some letters become cropped:
![cm](https://user-images.githubusercontent.com/2577509/118208630-eece9500-b488-11eb-90a8-bf70cd5f7794.png)

Full code ([try it online](https://jsbin.com/bexayuceyo/edit?html,output)):
```html
<script src="https://codemirror.net/lib/codemirror.js"></script>
<link rel="stylesheet" href="https://codemirror.net/lib/codemirror.css">

<style>
.CodeMirror
{
	width:100px;
	height:100px;
	border:1px solid black;
	font-family:Consolas;
	font-size:14pt; /* !!! IMPORTANT !!! */
}
</style>

<body></body>

<script>
var editor = CodeMirror(document.body, {inputStyle: "textarea"});
editor.focus();
editor.setValue("abcdefghijklmnopqrstuvwxyz");
</script>
```

**Comment by stasoid** [comment]
This bug was introduced in [this commit](https://github.com/codemirror/CodeMirror/commit/695d0086).

**Comment by marijnh** [comment]
Indeed. It guess the scroll margin masks the bug with smaller font sizes.
