### ISSUE TITLE
[Markdown] Allow dots in tag parsing

### ISSUE THREAD

**Issue by bplace** [codemirror/CodeMirror#6687]
I've struggled hours to have my custom tags working with markdown mode.

I'm using Laravel 8 components, which allow these kind of tags : ```<x-front.custom attr="val"></x-front.custom>```

Dots in tag parsing are not allowed, and it disables tag coloring, or the closetags addon will crash when using these tags.

I have made a very slight edit to ```/mode/markdown/markdown.js``` :

```
// Line 549
if (modeCfg.xml && ch === '<' && stream.match(/^(!--|\?|!\[CDATA\[|[a-z][a-z0-9-]*(?:\s+[a-z_:.\-]+(?:\s*=\s*[^>]+)?)*\s*(?:>|$))/i, false)) {
```

The regular expression for tags now has a dot ```[a-z][a-z0-9\.-]*```

```
if (modeCfg.xml && ch === '<' && stream.match(/^(!--|\?|!\[CDATA\[|[a-z][a-z0-9\.-]*(?:\s+[a-z_:.\-]+(?:\s*=\s*[^>]+)?)*\s*(?:>|$))/i, false)) {
```

It would be nice to allow dots, as the [closetags example page](https://codemirror.net/demo/closetag.html) supports these kind of tags.

**Comment by marijnh** [comment]
CommonMark does not allow dots in tag names, and I think it's reasonable for our Markdown parser to follow the standard here.

**Comment by bplace** [comment]
Sounds reasonable indeed!
