### ISSUE TITLE
[Feature request] Please implement vertical writing mode and vertical cursor

### ISSUE THREAD

**Issue by yo-goto** [codemirror/CodeMirror#6692]
Hi, I'm a Japanese and developing an add-on for the specific text editor using CodeMirror. 
I want CodeMirror dev team to implement vertical writing mode and vertical cursor.
Vertical writing is so important for Japanese writing and reading system. Most part of Japanese books is written in vertical direction.

This means many writer want to view and write contents in vertical mode. 
So important. Please consider implementing this feature.

## Related issue
[is it possible to support the writing-mode: vertical-lr; ? · Issue #6499 · codemirror/CodeMirror](https://github.com/codemirror/CodeMirror/issues/6499)

**Comment by marijnh** [comment]
Sorry, but this is unlikely to ever be implemented in CodeMirror.

**Comment by yo-goto** [comment]
thanks for a reply. it's a pity😭
