### ISSUE TITLE
JS syntax highlight for template string broken when multiplexingMode is used

### ISSUE THREAD

**Issue by SashaSkywalker** [codemirror/CodeMirror#6693]
Hi, I faced the issue with JS syntax highlighting, anything after `${}` with custom interpolations marked as `string-2`

![image](https://user-images.githubusercontent.com/6690616/119262060-90b95480-bbe2-11eb-87f2-12fdcd1cf294.png)

I am using `multiplexingMode`:
```javascript
multiplexingMode(
  getMode(config, { name: 'javascript', typescript: true }),
  {
    open: new RegExp(
       '(?<!([\'"`].*))' + // starts not with quote and any content
       '(\{\{)',// match "{{"
     ),
     close: '}}',
     delimStyle: 'my-interpolation',
     innerStyle: 'my-interpolation-code',
     mode: getMode(config, { name: 'javascript', typescript: true }),
  },
);
```
If I switch `open` to the string `{{` then JS highlighting is correct but my custom mode displayed wrong:
![image](https://user-images.githubusercontent.com/6690616/119262394-c01c9100-bbe3-11eb-9f2a-ef5f51687124.png)

Codemirror version: `5.61.1`

Thanks!

**Comment by marijnh** [comment]
What the JavaScript mode is seeing in this case is `` console.log(`${}`) ``, which is indeed not valid JavaScript.

Attached patch adds a kludge to make it a bit more tolerant about situations like that.
