### ISSUE TITLE
5.61.1 causes infinite parsing loop

### ISSUE THREAD

**Issue by nmackey** [codemirror/CodeMirror#6697]
Not sure I can share the code, but upgrading from 5.61.0 to 5.61.1 caused my app to get stuck in an infinite loop inside parseJS.  Reverting to 5.61.0 fixed the issue for me.

**Comment by marijnh** [comment]
I'm going to need more details to be able to say anything about this. The code that you're highlighting and whether the same problem occurs on https://codemirror.net/mode/javascript/ would be a good start.

**Comment by AnthonyTonev** [comment]
Hello - I have the same issue. 

Consider the following code.
`() => { console.log('hello word') }  `

if you add a non matching ) it will loop forever.
`() => { console.log('hello word') })` this will crash it.

I've added a log to the most recent change (the very "last" code mirror commit 6fbe464029ca4f8dc7d63b14de3ff0b16135b059)
      if (type.match(/[;\}\)\]]/)) {
          console.log('matching');
          return pass();
      }

As soon as I add the no-matching brace:
![image](https://user-images.githubusercontent.com/32884987/120100166-ed1ef580-c147-11eb-9068-1b83bd6514ca.png)

**Comment by marijnh** [comment]
Ah, thanks, that was indeed a recent regression. Not sure if it was the original issue (the offending patch isn't in 5.61.1), but attached patch should address that.

**Comment by AnthonyTonev** [comment]
This fixed the previous case but it still gets stuck on this one:

Let's say we write an IFEE that decares an object:
```
(function () {
    var position = {  x: 1, y: 2 };
} )() 
```
but we write the function body first and declare the object last:
```
// minimal amout of brackets that are causing the infinite loop
(function () {
    var position = {   // if this bracket is added last it loops forever
})
```

If we write each line in order (from top to bottom) it will work fine though.

**Comment by marijnh** [comment]
Good point, it seems the problem was a bit more widespread. Attached patch reverts the original change and applies a different, safer, solution for the thing it was trying to solve.
