### ISSUE TITLE
multiplexingMode doesn't restore the outer mode's state

### ISSUE THREAD

**Issue by bradencanderson** [codemirror/CodeMirror#6700]
I created a simple mode for embedding arbitrary expressions inside of `{{}}` blocks inside JSON:

```js
CodeMirror.defineMode("fancyjson", (config) => {
  return CodeMirror.multiplexingMode(
    CodeMirror.getMode(config, { name: "javascript", json: true }),
    {
      open: "{{",
      close: "}}",
      mode: CodeMirror.getMode(config, "text/plain"),
      parseDelimiters: false
    }
  );
});

const els = document.querySelectorAll(".code");
els.forEach((el) => {
  CodeMirror.fromTextArea(el, {
    lineNumbers: true,
    mode: "fancyjson"
  });
});

```

Codepen is [here](https://codepen.io/bca2021/pen/WNpzZwe).

Screenshot:
<img width="229" alt="Screen Shot 2021-06-03 at 5 21 29 PM" src="https://user-images.githubusercontent.com/5060341/120727799-4c567000-c490-11eb-83ca-a32af6c38c39.png">

Note how the string syntax highlight is incorrect in the second block. Is this expected behavior?

**Comment by marijnh** [comment]
Please don't post the same thing both in the forum and the bug tracker. See my response [here](https://discuss.codemirror.net/t/multiplexingmode-doesnt-restore-the-outer-modes-state/3249). This is unlikely to be fixed on the library side, but you might be able to build a completely custom wrapped node (without multiplex.js) that sidesteps the issue.
