### ISSUE TITLE
iOS spacebar cursor disappears sometimes

### ISSUE THREAD

**Issue by hesselbom** [codemirror/CodeMirror#6702]
With iOS you can use spacebar to move your cursor inside a textfield. In CodeMirror the cursor disappears if I move it too far up (see attached video).

At about 3 seconds in to my video I move the cursor too far up and it disappears and is not visible even if I move the cursor down again. I can see CodeMirror scrolling so some selection is happening but I don't know where anymore.

Unclear if this is a bug in CodeMirror or something to do with iOS Safari's handling of contentEditable.

## Example
I uploaded the example (which is just an index.html file, you can view page source to see it all) to see here: https://lying-wind.surge.sh/ - but in short it's just a textarea with a bunch of text and initiating the editor like this:
```js
var editor = CodeMirror.fromTextArea(document.querySelector('textarea'), {
  lineWrapping: true,
  singleCursorHeightPerLine: false
})
```

## Video showing issue
**Video**: https://lying-wind.surge.sh/example.mp4
**GIF**: https://lying-wind.surge.sh/example.gif
![example.gif](https://lying-wind.surge.sh/example.gif)

## Info
**CodeMirror version:** 5.61.1
**Browser:** iOS Safari (iOS version 14.6)

**Comment by marijnh** [comment]
What the browser seems to be doing in this case is moving the selection into the gutter (which isn't even editable) while keeping the focus on the editor. This makes zero sense, but is rather in keeping with the general brokenness of cursor handling in mobile Safari.

I tried to find a workaround with `user-select` styles and some more dodgy hacks, but wasn't able to find anything that actually worked. So I'd say this isn't fixable in a reasonable way in this library, and your only hope is to report it to the Safari developers (which, admittedly, isn't very likely to get you much response either).
