### ISSUE TITLE
Why i use rollup but show something wrong?

### ISSUE THREAD

**Issue by Kelier** [codemirror/CodeMirror#6703]
./node_modules/@tutor/qae-lib/dist/main.js
Module not found: Can't resolve '../../lib/codemirror' in '/Users/cococola/2020_vendor/tutor-laser-react/node_modules/@tutor/qae-lib/dist'

![image](https://user-images.githubusercontent.com/16694478/121158543-0842e100-c87d-11eb-9705-c8aa6bc36169.png)

my rollup.config.js

```
const tasks = [
    {
        input: './src/main.ts', 
        output: {
            file: './dist/main.js',
            format: 'es',
            sourcemap: true,
        },
        external: Object.keys(pkg.dependencies)
            .concat(Object.keys(pkg.peerDependencies))
            .concat(['@ant-design/icons', 'react/jsx-runtime', 'moment']),
        plugins: [
            resolve(),
            typescript({
                include: ['*.ts+(|x)', '**/*.ts+(|x)'],
                tsconfig: './tsconfig.build.json',
            }),
            postcss({
                modules: true,
                use: {
                    less: {
                        javascriptEnabled: true,
                    },
                },
            }),
.....
```

external without codemirror

**Comment by marijnh** [comment]
It appears that your system contains some copied code from (what looks like) an old distribution of CodeMirror, which is specifying its dependency incorrectly. That's not something I can help you with.
