### ISSUE TITLE
CodeMirror 6 moveLineUp and moveLineDown moves more than the selected lines

### ISSUE THREAD

**Issue by larspontoppidan** [codemirror/CodeMirror#6705]
How to reproduce:

1. Go to https://codesandbox.io/s/codemirror-6-demo-pl8dc

2. Replace the index.js code with a minimal editor using defaultKeymap: (to enable Alt-Up, Alt-Down line movement)

```
import { EditorState } from "@codemirror/state";
import { EditorView, keymap } from "@codemirror/view";
import { defaultKeymap } from "@codemirror/commands";
import { lineNumbers } from "@codemirror/gutter";

let myView = new EditorView({
  state: EditorState.create({
    extensions: [lineNumbers(), keymap.of([...defaultKeymap])]
  })
});

document.body.appendChild(myView.dom);
```

3. Let codesandbox.io add the dependencies to make it compile

4. Add the same code from 2. in the Codemirror 6 editor to get some material to work with 

5. Select the full line 2 and line 3 like this: place the cursor at start of line 2 and press Shift-Down two times.

6. Press Alt-Up a few times and Alt-Down a few times

-> Observe that progressively more than two lines are moved around.

Expected: Only line 2 and line 3 should move around

Reproduced in Firefox 88.0 (64-bit) and Chromium Version 90.0.4430.72

**Comment by marijnh** [comment]
Thanks for the report. Attached patch should fix this.

**Comment by larspontoppidan** [comment]
I can confirm https://github.com/codemirror/commands/commit/94aca087e7db0b38f62563d2589171fdc847c732  fixes the issue
