### ISSUE TITLE
Python I just want to auto hint some arguments for my own function

### ISSUE THREAD

**Issue by iamjing66** [codemirror/CodeMirror#6706]
hello,just like title, I want to add some auto hint for my own function,but I don`t know how to add it.
I think it`s better to add it into python.js then create a new mode, can you help me?

**Comment by marijnh** [comment]
Context-aware completion for Python doesn't currently exist. You don't need to modify python.js—you could try to write your completion logic to look at the tokens produced by the Python mode and do basic context analysis from that.

**Comment by iamjing66** [comment]
I get it,thanks for your reply
