### ISSUE TITLE
CodeMirror Search/Dialog AddOn and Content-Security-Policy

### ISSUE THREAD

**Issue by cmason3** [codemirror/CodeMirror#6707]
CodeMirror 5.61.1 and Chrome/Edge/Firefox or Safari (any browser which supports CSP which is everything except IE11):

When implementing a best practice `Content-Security-Policy` which allows CodeMirror to be used from a CDN, e.g:

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' https://cdnjs.cloudflare.com; script-src 'self' https://cdnjs.cloudflare.com">
```

There is a security violation when using the search AddOn as `dialog.js` tries to use an inline style: 

```
dialog.js:24 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://cdnjs.cloudflare.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```

The use of `unsafe-inline` basically makes CSP pretty weak so it isn't advisable (especially when I have spent many hours removing all the inline styles from my web application). This appears to be caused by the following line in `dialog.js` at line 24:

```
dialog.innerHTML = template;
```

I assume it can be fixed by referencing an actual CSS style in `dialog.css` instead of making it inline?

**Comment by marijnh** [comment]
This isn't likely to change, so your options are to drop the search addon or to drop the policy.
