### ISSUE TITLE
The selection layer not updated on font size change.

### ISSUE THREAD

**Issue by jdbruxelles** [codemirror/CodeMirror#6712]
Hi, there is a demo of how the editor don't update the layer of selection when the font size change. If it's possible to fix that.

https://user-images.githubusercontent.com/18559798/122407645-129e6280-cf82-11eb-8384-e793da75f967.mp4

**Comment by marijnh** [comment]
That is by design (there's no reliable way to get notified of style changes in the DOM), and you're required to call `cm.refresh()` whenever you change something that'll affect the geometry of the editor.

**Comment by jdbruxelles** [comment]
Ok, that helped me 🤗. Thank you for the fast reply 💫.
