### ISSUE TITLE
Persian Language Suggestion

### ISSUE THREAD

**Issue by haftado3** [codemirror/CodeMirror#6719]
hey there,
I hope you are doing fine
thanks for the great job you have done with this project.
recently I started using your project inside my own project and its language is Persian.
but when I wrote anything in Persian it would not change the direction of every line automatically like `textarea` every new paragraph, it checks first character of the line and if its rtl character then makes that line rtl .so after searching a lot around your code I have changed `buildLineContent` function a little bit so it can support basic `rtl | ltr` mixed situation together (like `dir=auto`)
my final code is like this :

```
function buildLineContent(cm, lineView) {
    var firstcharofline = lineView.line.text.charAt(0)
    var pattern = /[\u0600-\u06FF\u0750-\u077F]/;
    var isarabic = pattern.test(firstcharofline);
      var content = eltP("span", null, null, isarabic ? "padding-right: .1px;display:block;" :"padding-right: .1px;" , null);
```
and after that my problem have been solved , I thought you maybe want to know this or you can suggest me better solution for it.

**Comment by marijnh** [comment]
How does adding `display: block` to that span help with changing text direction?

**Comment by haftado3** [comment]
ok let me explain this for you.
when you use span for a text because its not a block it wont use full width of line and because its width is less than required for the actual width of box even if you use `text-align : right;` it wont work in rtl languages.
unless you set direction to `rtl` and it will change the direction of the whole thing.
but alternatively if you change the display of it to block in rtl languages you can have a right aligned text because its width is 100% of its parents width.

**Comment by marijnh** [comment]
So how are you adding the `text-align` property?

**Comment by haftado3** [comment]
in my case I have a style like this :
```
p, span {
    direction: rtl;
    text-align: justify;
}
```
but it wont work without making that span style `display:block;`

**Comment by haftado3** [comment]
i have some other things too , like `dir="auto"` in `textarea` but I'm not sure if code mirror checks that.

**Comment by marijnh** [comment]
Why don't you directly target `.CodeMirror-line` with your CSS rule?

**Comment by haftado3** [comment]
let me show you in a picture how this should work in arabic or any rtl languages :
`<textarea style="width: 80%;display: block;margin: 20px auto; font-size: 30px;padding-right: 10px;" dir="auto"> </textarea>`
so this is my output :
![ddddddd](https://user-images.githubusercontent.com/8863902/122753021-e3039900-d2a6-11eb-8177-1feebbcbfc03.PNG)

**Comment by haftado3** [comment]
this works as expected when you write in any rtl languages it will change the direction of every paragraph after `\n` to the first charachter of that lines direction

**Comment by marijnh** [comment]
That does not explain why the `<span>` has to be targeted, though.

Also, even with a hack like this, CodeMirror doesn't really support this and you'll run into other issues (such as the library being unaware that a given line is being rendered RTL, and computing the visual text order incorrectly because of that).

**Comment by haftado3** [comment]
so what is the correct way of having same functionality like `<textarea dir="auto"></textarea>`

**Comment by marijnh** [comment]
There's isn't one—this is not a feature the library supports.

**Comment by haftado3** [comment]
ok thanks then.
do I have permission to change the source for myself to have this functionality for me ?

**Comment by marijnh** [comment]
Absolutely!
