### ISSUE TITLE
Wrong thing passed to StringStream?

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#6723]
I was trying to make sense of some of the code involved in computing indentation when pressing enter, and noticed that in https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/src/line/highlight.js#L144 the StringStream constructor is passed a Context object, whereas it seems to expect a "line oracle", and these don't seem to be compatible. Was this intentional somehow?

**Comment by marijnh** [comment]
Why do you say they are not compatible? The stream uses the `baseToken` and `lookAhead` methods on its line oracle, both of which are provided by context objects.

**Comment by mtaran-google** [comment]
Oh, okay. If you say so :)
