### ISSUE TITLE
Can't scroll with mouse selection

### ISSUE THREAD

**Issue by hata6502** [codemirror/CodeMirror#6731]
Can't scroll with mouse selection.
This problem also be occured in [CodeMirror 6 Top Page](https://codemirror.net/6/).

https://user-images.githubusercontent.com/7702653/124218179-ad776f00-db34-11eb-97fe-f82b922ad45d.mp4

This problem is due to viewport.
I forked [codemirror/view](https://github.com/codemirror/view) to [hata6502/codemirror-view](https://github.com/hata6502/codemirror-view), and disabled viewport.

commit: https://github.com/hata6502/codemirror-view/commit/b3fb35c967726935ad0c56ff08228e6511d78d0c

But, this problem should be resolved by fixing the viewport logic.

Thank you for maintaining!
　

### Bug tracking information
OS: Ubuntu 20.04
browser: Google Chrome 91.0.4472.114
Code Mirror version: @codemirror/view@0.18.17

**Comment by marijnh** [comment]
Attached patch seems to resolve this.
