### ISSUE TITLE
[Addon feature request] `closetag.js` setting to only close tags when `</` is typed

### ISSUE THREAD

**Issue by williamd5** [codemirror/CodeMirror#6736]
Upon creating a new tag, by default, the addon will insert a new indented line and close the tag on the next line. This in particular could cause potential frustration when using tags that are expected to have text only (e.g. `<p>`, `<h1>`, etc.)

In my opinion, it would altogether be better if there is an option to control the functionality of this addon using something similar to the following:
```js
const editor = CodeMirror.fromTextArea(document.getElementById("code"), {
  mode: 'text/html',

  // different options for the addon
  autoCloseTags: true, // default functionality (close both when created or </ typed)
  autoCloseTags: "create", // close the tag when it's created
  autoCloseTags: "slash" // close the tag only when </ is typed
});
```
This would for instance further enable functionality similar to the one seen in Sublime Text (v3 and v4) by default and to which many coders, including myself, might be accustomed to.

**Comment by marijnh** [comment]
That's the `whenOpening` option—i.e. `autoCloseTags: {whenOpening: false}`.

**Comment by williamd5** [comment]
Link to docs? Can't find anything about this

**Comment by marijnh** [comment]
Seems to only be document in a comment in the addon script file at the moment.
