### ISSUE TITLE
Not possible to fold first heading in yaml-frontmatter mode, if heading is at start of document

### ISSUE THREAD

**Issue by Billiam** [codemirror/CodeMirror#6737]
If an otherwise foldable heading is the first bit of content when in a yaml-markdown document, it's not possible to fold that heading.

https://codepen.io/billiam/pen/PomNZLQ

I believe this is occurring because, when searching for fold helpers at the first character of the first line, the markdown fold helpers are not returned, because the **mode** at position `{ line: 0, ch: 0 }` is actually `yaml` until tokens are processed.

```javascript
  CodeMirror.registerHelper("fold", "auto", function(cm, start) {
    var helpers = cm.getHelpers(start, "fold");
...
```
Adding some content above the heading allows the first heading to fold correctly.
Adding newlines above the content does not, because the `yaml-frontmatter` mode tolerates empty lines before the content, so the mode remains yaml).

As a workaround, in my app, I've changed the `start` value to be `{ line, ch: 1}` if line and ch are 0. It's not the correct solution, but it's working for me (for this one use case).

**Comment by marijnh** [comment]
Indeed, that's not ideal. Attached patch should fix this.
