### ISSUE TITLE
Codemirror editor inside Bootstrap Modal is not loading content until clicked

### ISSUE THREAD

**Issue by rboughani** [codemirror/CodeMirror#6739]
I'm triying to display different values in my Codemirror editor inside a Bootstrap modal, using many buttons. But the content of editor is not updated until i click on it !

i'm triying like that :

`
      $(document).ready(function() {
    
      var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        matchBrackets: true,
        autoCloseBrackets: true,
        mode: "application/ld+json",
        lineWrapping: true,
        lineNumbers: true,
        readOnly: true,
        autoRefresh: true
      });
        
    //$('body').on('click', 'input.ajust', function (e) {
     $('input.ajust').click(function (e) {
        var tagId = $(this).attr('id');
        var jsonInput;
        
        var mymodal = $('#myModal');
        
       switch (tagId) {
          
    case 'mazigh':
      //var url = "data/input/exposure/input.json";  
      //$.getJSON(url, function (data) {
        editor.getDoc().setValue(JSON.stringify('MAZIGH', null, "\t")); 
        editor.refresh();
        setTimeout(function() {
            editor.refresh();
        },1);
      //});
            break;
          
    case 'takfa': 
      //var url = "data/input/unpaid/input.json";  
      //$.getJSON(url, function (data) {
        editor.getDoc().setValue(JSON.stringify('TAKFA', null, "\t"));  
        editor.refresh();
        setTimeout(function() {
            editor.refresh();
        },1);
      //});
            break;
          
          default:
            console.log('Sorry, we are out.');
        }
        
        editor.refresh();
        mymodal.modal('show');//.trigger("change");         
 
    });
    editor.refresh();`
    });

i created this jsfiddle to show the behavior

https://jsfiddle.net/s91mvb2p/43/

**Comment by marijnh** [comment]
If you initialize the editor in an element that's not yet in the DOM, you have to arrange to call `.refresh()` on the editor once it's in the actual document, so that it can measure its dimensions. This can be annoying, but is by design (there's no robust way to detect when an element is 'mounted' in the DOM).
