### ISSUE TITLE
Keyboard Shortcut ALT+u removes text when it should just undoSelection

### ISSUE THREAD

**Issue by cblte** [codemirror/CodeMirror#6742]
Hello, 
I am using Firefox Browser with TiddlyWiki 5.1.23 and CodeMirror version 5.58.3 

I am using an MacBook Air with US layout and trying to type german umlaut characters. 

**Problem:** 

When creating a new tiddler, I start typing. After a couple of words I press ALT+u to start the Umlaut automation, the text I have written is deleted, and the cursor jumps back a couple world and prints the two dots waiting for the next input. 
From the README of CodeMirror I could not figure out what the problem is, as the list of keyboard shortcuts tell for the ALT+u shortcut to remove the selection but not UNDO my input. 

**Expected Behavior:**

Do not delete the text I have written and just wait for next keyboard input

**Possible Solution:**

Change the keyboard bindings for the ALT+u keyboard shortcut. As this behavior does not happen when using the standard TiddlyWiki editor. 

---

Thank you for looking into this or telling me how to disable this keyboard shortcut.

**Comment by marijnh** [comment]
There is no binding for Alt-U in the macOS key bindings, so I don't think this is related to the undo selection command. Does the same problem occur with other composition keys?

**Comment by cblte** [comment]
Hello marijnh, I am sorry I just recognized that I posted this onto the wrong GitHub profile. I close as it is not realted to this version of the codemirror editor implementation. sorry.
