### ISSUE TITLE
 Markdown highlighting bug: formatting spreads to further lines.

### ISSUE THREAD

**Issue by saarantras** [codemirror/CodeMirror#6744]
Steps to reproduce:
Go to : [CodeMirror: Markdown mode](https://codemirror.net/mode/markdown/)
Paste in the following:
```
**foo ** bar
baz


reference
```

Note that it is formatted as the following:
![e7bfaa514e5dbc8024acc575a609350c0010ae4c](https://user-images.githubusercontent.com/31054972/126169215-8c4c4839-c4dc-49de-b627-a48c21f6f7fb.png)

Which is not the expected result. Why are bar and baz bolded?
I’ve been told foo shouldn’t be bolded either, and referenced to [this demo](https://spec.commonmark.org/dingus/?text=**foo%20**%20bar%0A%0Abaz%0A%0Areference).
I originally reported the bug [here](https://github.com/laurent22/joplin/issues/5170), but it appears to be a problem with this software (CodeMiror), not that one (Joplin), since you can even see it in the web-demo.

**Comment by marijnh** [comment]
Please don't post the same thing both here and on the forums. See my [reply](https://discuss.codemirror.net/t/markdown-highlighting-bug-formatting-spreads-to-further-lines/3369/2) there. This is unlikely to get fixed in the Markdown mode for CodeMirror 5.x.

**Comment by saarantras** [comment]
Ok thanks for the reply. Sorry for double-posting, I didn't know if I had submitted the issue in the right location.
