### ISSUE TITLE
[lint addon] Tooltip Placement

### ISSUE THREAD

**Issue by Clashsoft** [codemirror/CodeMirror#6745]
The lint addon should allow some basic customization of the tooltip placement. For example, if i have a CodeMirror near the top of my page, the tooltip is cut off:

<img width="481" alt="Screenshot 2021-07-20 at 12 51 55" src="https://user-images.githubusercontent.com/4145923/126312313-efeb228a-2b01-46b5-981e-4f5b9317dd23.png">

While it is possible with `z-index` to put the tooltip above the navbar in this case, a longer tooltip would hit the top of the viewport.

A nice solution would be a `placement` option, for example with values `top` or `bottom`, that would place the tooltip in the direction relative to the cursor. `top` would be the default. I figure `bottom` would be straightforward to implement, since it just needs to set the `top` style attribute to the location of the cursor plus some offset.

Another option would be `auto`, which automatically selects top or bottom based on the viewport bounds, so that the tooltip is always visible no matter where. Perhaps this is an idea for the future.

**Comment by marijnh** [comment]
> While it is possible with z-index to put the tooltip above the navbar in this case, a longer tooltip would hit the top of the viewport.

I don't think so—the module contains logic to keep the tooltips inside of the window. The 'auto' option you're describing is pretty much what should be happening there.

So yeah, working with a z-index is probably the way to go here. I don't really want to make the extension more complex for cases like this.
