### ISSUE TITLE
Julia mode doesn't detect all macro calls as such

### ISSUE THREAD

**Issue by elecprog** [codemirror/CodeMirror#6750]
First and foremost, thanks for this cool project!

In Julia mode some macro calls aren't detected as such. Most notably `@.` in eg.
```julia
@. v = v * w
```

Presumably this can be fixed by adapting lines [60 through 62 of `julia.js`](https://github.com/codemirror/CodeMirror/blob/master/mode/julia/julia.js#L60):
```js
var macro = /^@[_A-Za-z][\w]*/;
var symbol = /^:[_A-Za-z\u00A1-\uFFFF][\w\u00A1-\uFFFF]*!*/;
var stringPrefixes = /^(`|([_A-Za-z\u00A1-\uFFFF]*"("")?))/;
```
I think macro calls and symbols are identical (apart from the prefix), but I'm not entirely sure.

Tested on Firefox 90 on Linux, but I'd be surprised if tokenization/parsing is different depending on the browser/OS. I've noticed the behaviour in Pluto, I could also reproduce it on [your website](https://codemirror.net/mode/julia/index.html).

**Comment by marijnh** [comment]
I don't know enough about Julia to say much here, but maybe @pabloferz or @joe-loco can provide input?

**Comment by pabloferz** [comment]
Yes, I think macro and symbol can be the same apart from the `@` vs `:`.

**Comment by pabloferz** [comment]
Well, turns out to be a bit more involved. See #6751.

**Comment by marijnh** [comment]
Thanks for taking a look! Let me know when you consider that ready to merge.
