### ISSUE TITLE
how to use setFocus

### ISSUE THREAD

**Issue by xiaoxian521** [codemirror/CodeMirror#6753]
how to use setFocus Go to set the focus position

**Comment by marijnh** [comment]
You're going to have to be more specific about what you are trying to do.

**Comment by xiaoxian521** [comment]
I need to dynamically set the cursor position

my code:
 ```
hintOptions: { 
    customKeys: {
         "setFocus": "setFocus"
     }
}
```
I found that this setting still doesn't work

**Comment by xiaoxian521** [comment]
If you don’t configure setFocus in customKeys, you get null by default. How can I get setFocus?

**Comment by marijnh** [comment]
No, indeed, that doesn't work. You want something like

```
hintOptions: {
  customKeys: {
    "Space": function(cm, handle) { handle.setFocus(0) }
  }
}
```

**Comment by xiaoxian521** [comment]
cm, handle is undefined

**Comment by xiaoxian521** [comment]
I want to use this setFocus through a non-keyboard event such as a click event, is that okay?

**Comment by marijnh** [comment]
No, `customKeys` is for key handling. There isn't currently a way to change the completion focus from random events.

**Comment by xiaoxian521** [comment]
Use cm.focus() to focus to the beginning, can it be brought to the end?

**Comment by marijnh** [comment]
I'm really confused what you are even trying to do — the mention of `hintOptions` suggested that you're trying to work with the show-hint addon, but `cm.focus()` is about editor focus. Please put some more through into the question and ask it on the [forum](https://discuss.codemirror.net/) instead.

**Comment by xiaoxian521** [comment]
<img width="383" alt="截屏2021-07-29 下午1 46 48" src="https://user-images.githubusercontent.com/44761321/127438300-19b1d6c2-07e1-4a2d-9bb2-0b10dd3edf94.png">
My problem is mainly to position the cursor in the middle of (), but it is always at the end
