### ISSUE TITLE
filter custom autocomplete with html mixed mode?

### ISSUE THREAD

**Issue by basileguoz** [codemirror/CodeMirror#6754]
Hi, i'm trying to filter a custom list of words to the hint/autocomplete mode but with some problems.
I added the css:
![image](https://user-images.githubusercontent.com/29287707/127308776-19b07904-0346-4433-b6e9-006c86ec96ef.png)
and the js:
![image](https://user-images.githubusercontent.com/29287707/127308852-016d65fc-7da4-4158-95d4-6665b2ac934b.png)
Then i istantiated Codemirror on my textarea:
![image](https://user-images.githubusercontent.com/29287707/127309106-7b11c20e-959f-4535-8907-7b45d0e1d956.png)
And i override the hint.html method:
![image](https://user-images.githubusercontent.com/29287707/127309379-c84549d6-2ac0-4e63-8419-57fa614b0cc5.png)
This will add my list to the html hints but it wont be able to filter through my added words.
Is there a way to filter even through them?
And can i add my custom list to hint.html and hint.javascript without having to override both methods?
Thanks

**Comment by marijnh** [comment]
Please use the [forum](https://discuss.codemirror.net/) for questions. This is the bug tracker.

As an aside, posting screenshots of code is generally not a reasonable thing to do (just paste the actual code and wrap it in a code block).
