### ISSUE TITLE
doc.SetValue(...) always adds to history

### ISSUE THREAD

**Issue by TysonMN** [codemirror/CodeMirror#6756]
Suppose `doc.historySize().undo === 0`.  Then after calling `doc.setValue(doc.getValue())`, we now have `doc.historySize().undo === 1`.

Is that the intended behavior?

At first, I was expecting that the `undo` size would not grow.  However, after thinking about it more, it might be very expenses to check if the new code is equal to the old code when the size of the code is very large.

**Comment by marijnh** [comment]
Yes, this is the intended behavior.
