### ISSUE TITLE
Obsidian.md: Undo (Ctrl+Z) undoes more than one last step

### ISSUE THREAD

**Issue by mikkovedru** [codemirror/CodeMirror#6759]
I am using [Obsidian](https://obsidian.md) knowledge base editor. 

I found a bug in it, [reported it to the developers](https://forum.obsidian.md/t/undo-ctrl-z-undoes-more-than-one-last-step/21868/1), but it was shot down on the grounds of "it is a CodeMirror bug". Hence I am writing to you.

Here is a copy&paste of my original bug report:

----------
### Steps to reproduce
0. Install Obsidian.
1. Go to any youtube video (for example [here](https://www.youtube.com/watch?v=xZU5M-joMOc))
2. Select one line with the name of the channel (in this case “DistroTube”)
![![image](https://user-images.githubusercontent.com/2521942/127931521-adb9305f-d302-47b8-8af6-6065aed1fb97.png)](https://user-images.githubusercontent.com/2521942/127931478-f9b72d79-3655-46b8-937f-0a11057496fa.png)
3. Write "Test " in a document.
4. Press Ctrl+Ins(Ctrl+C) to copy.
5. Go to Obsidian document and write "Test ".
6. Press Shift+Ins (Ctrl+V) to paste. The result should look like this:
```
Test [DistroTube](https://www.youtube.com/channel/UCVls1GmFKf6WlTraIb_IaJg)
```
![image](https://user-images.githubusercontent.com/2521942/127931543-b0719d48-1ea3-41d2-9ded-55f4233999b8.png)
7. BUG: Press Ctrl+Z to undo. You will see that the whole line will be deleted, not only the youtube link.

### Expected result
Only the last step should be undoed. Typing and pasting are clearly two different steps/activities.
Environment
- Operating system: Linux Mint 20.2 Cinnamon
- Obsidian version: 0.12.10

### Additional information

This bug shows itself with youtube channel links. Everything works fine with most other copy-pasted text. Including if you paste+select+copy the same exact youtube channel link and try to reproduce the bug… 

------------

**Comment by marijnh** [comment]
Sorry, I'm not debugging problems that involve integrations. And more generally, not very sure that this is a CodeMirror bug. It sounds like the Obsidian link pasting behavior replaces the entire line, and that's what's causing this behavior.

**Comment by lishid** [comment]
Got word of this recently. Here's the repro on https://codemirror.net/:

Type this into console:
```js
editor.on('paste', (cm, e) => {
  cm.replaceSelection('test');
  e.preventDefault();
});
```

Create new line, then type anything, then paste anything, then undo undoes both the typing and pasting.

**Comment by marijnh** [comment]
That's by design -- `replaceSelection` defaults to setting the "origin" of the change to `+input`, which allows the change to be merge with other plain input changes. Call `.replaceSelection("test", false, "customOrigin")` to avoid this.

**Comment by lishid** [comment]
Ah I see, thanks for the response!
