### ISSUE TITLE
Does CodeMirror have a syntax highlighter online ?

### ISSUE THREAD

**Issue by ioanf2** [codemirror/CodeMirror#6761]
hello, Does CodeMirror have a syntax highlighter online ?

I find this link, seems to be good, but I need to highlight the code in PERL and PYTHON, also in BASH

https://codemirror.net/1/highlight.html

Does CodeMirror have a syntax highlighter online with all programming languages? It is very important this future for almost all CSS designers. It is much easier than to add js.

**Comment by marijnh** [comment]
No, there's no online syntax highlighter
