### ISSUE TITLE
Add "cbl" as an extension for COBOL programs

### ISSUE THREAD

**Issue by Crosswind** [codemirror/CodeMirror#6762]
A lot of the editors that support syntax highlighting for COBOL use the .cbl file extensions. It would therefore be good to have that added to the list of extensions for the language. .cob and .cpy are already there. This would also enable syntax highlighting in Bitbucket server as they rely on CodeMirror. We use Bitbucket heavily for COBOL development.

.cbl is not taken by any other language and I'm not aware this is used in other places. Would this be a suitable change?

**Comment by marijnh** [comment]
Sure, that seems to be a no-brainer. Sorry, I already pushed my patch before I saw you had your own (a pull request would be a good format for minor changes like this, if you have a patch)

**Comment by Crosswind** [comment]
Thanks for the heads up and implementing the change! I'm still a bit new to contributing
