### ISSUE TITLE
After cm.setValue() ，an error occurred when entering the Chinese exclamation mark character

### ISSUE THREAD

**Issue by charleschan1998** [codemirror/CodeMirror#6763]
After cm.setValue() ，an error occurred when entering the Chinese exclamation mark character. 

![image](https://user-images.githubusercontent.com/44195693/129034031-5b6fb75b-9497-42bb-9093-604864883793.png)

**Comment by marijnh** [comment]
How do I reproduce this? Specifically...

 - What CodeMirror options need to be enabled to get this to happen?
 - Does the content in which you are typing matter?
 - Which Chinese IME are you using on which platform, and how do you compose the character that causes the problem?

**Comment by charleschan1998** [comment]
1. This error will be triggered even if there is no option. 
`let cm = CodeMirror.fromTextArea(this.$refs.codemirror)`

2. The input content is of type String
```
     const  text =
        "# corgicoding-theme-css\n" +
        "Render css based on the markdown format modified by typo.css.";
       ……

     cm.setValue(text);
```

3. This error occurred when I used the cm.setValue() method and then used the Chinese input method to input the exclamation mark .I have tried several Chinese IME under the windows 10 platform.  You can use the official input method of windows and try adding Chinese language.

**Comment by charleschan1998** [comment]
lol, I'm sorry, I found it was a problem with vue3. thank you.
