### ISSUE TITLE
Text selection handling options

### ISSUE THREAD

**Issue by gopz19** [codemirror/CodeMirror#6769]
Hi @marijnh/Team,

Can we have customizable extra options like:
1) Clear text selection when we click outside of code mirror.
2) Clear text selection on clicking undo and just undo the text.

These use cases are useful in our application so thought of checking.

**Comment by marijnh** [comment]
> Clear text selection when we click outside of code mirror.

You can either register a "blur" handler that sets the selection to a cursor, or style the selection to be invisible when the editor isn't focused.

> Clear text selection on clicking undo and just undo the text.

I'm not sure what 'clicking undo' means here, or why you'd want to clear your selection after undoing.
