### ISSUE TITLE
setSelections + contentEditable doesn't work correctly on the first call

### ISSUE THREAD

**Issue by Billiam** [codemirror/CodeMirror#6773]
**Description**: In contenteditable mode (only), calling `setSelections()` with an array of selections _appears_ to work correctly, but doesn't create real selections.

Typing will only replace the first selection, deselecting the following ones, and calls like `get`/`listSelections()` will only list the first selection

**Version**: 5.59.2
**Steps**:

With an editor using `inputStyle: 'contenteditable'`

1. Call `setSelections()` with a list of selections.
2. Focus text editor and type

Only the first selection will be replaced with typed content

3. Call `setSelections()` multiple times with the same values
4. Focus text editor and type

All selections will be replaced with typed content correctly

**Demo**: https://codepen.io/billiam/pen/VwWeZwO

**Comment by marijnh** [comment]
Attached patch should help. The editor ended up updating from within an update due to a synchronous focus event handler, which caused general confusion.
