### ISSUE TITLE
Syntax highlighting breaks when HTML tags are capitalized [HTML + Markdown]

### ISSUE THREAD

**Issue by Gazook89** [codemirror/CodeMirror#6779]
When using a mix of Markdown and HTML, the use of capitalized letters inside html tags ends up breaking any subsequent syntax highlighting.  

For example:
```md
*Line 1*

<Br>

*Line 3*
```
I would expect that both "line 1" and "line 3" would be "highlighted"/rendered as italicized in my Codemirror pane.  Instead, the result:

<img width="143" alt="image" src="https://user-images.githubusercontent.com/58999374/133315414-148f45e8-fd17-4155-a6d5-c1b6541666f6.png">

**Comment by marijnh** [comment]
That was caused by the HTML mode not properly treating tags as case-insensitive. Attached patch should help.
