### ISSUE TITLE
Typing looping statements

### ISSUE THREAD

**Issue by warfarejohn16** [codemirror/CodeMirror#6784]
I download .zip file of codemirror 2 then
When typing for() loop the var inside the curly braces is not highlighted?
Example:

For() {
 var <-- (not highlighted)
}

**Comment by marijnh** [comment]
Which language mode are you using? And are you really typing `For` with a capital `F`?

**Comment by warfarejohn16** [comment]
no and i use javascript. sorry for late comment.

**Comment by marijnh** [comment]
CodeMirror version 2 is 10 years old, so maybe try version 5. On https://codemirror.net/mode/javascript/ `var` is highlighted as a keyword with this code.
