### ISSUE TITLE
get Value is not Working in htmlMixed Mode

### ISSUE THREAD

**Issue by hsm-gowtham** [codemirror/CodeMirror#6785]
Hi There,
```
<div class="new-editor">
        <textarea id="codemirror-textarea"></textarea>
 </div>
```
    the above is the html code I'm using.
    
   to the textarea, I'm sending html code through ajax call.
   before sending the ajax call, I'm removing CodeMirror div which is created automatically on page Load.
```
   $('.CodeMirror.cm-s-default').remove();
   $('#codemirror-textarea').text(html);
```
       
    and I'm using code refresh as My code is overlapping with line numbers after ajaxcall.
```
   const Editor = CodeMirror.fromTextArea($('#codemirror-textarea')[0], { lineNumbers: true });
    Editor.refresh();
```
     and the below is the code I wrote for htmlmixed, I took reference from site.
```
        var mixedMode = {
        name: "htmlmixed",
        scriptTypes: [{matches: /\/x-handlebars-template|\/x-mustache/i,
                       mode: null},
                      {matches: /(text|application)\/(x-)?vb(a|script)/i,
                       mode: "vbscript"}]
      };
      var editor = CodeMirror.fromTextArea(document.getElementById("codemirror-textarea"), {
        mode: mixedMode,
        selectionPointer: true,
        lineNumbers: true
      });
```
      

Everything seems fine.
but when I click on preview button, I want to get the code in console.
but in console, I'm getting nothing.
```
 $('.preview-btn').on('click',function(){
        var gg = editor.getValue();
        console.log('preview',gg);
});
```

my final goal is to run the html code inside editor and show the preview.
On click of preview, I want to get the code and keep it in iframe.
but i was unable to get anything, it's returning empty string.

Any help would be greatful.
Thanks

**Comment by marijnh** [comment]
`getValue` has nothing to do with the mode, and it is really unlikely that it is returning the empty string when the editor is showing code. So my guess would be that you're somehow creating multiple editor instances and getting them confused (the fact that `Editor` is capitalized in one of your code snippets might be related).

**Comment by hsm-gowtham** [comment]
@marijnh ,
it's resolved, 
Now I'm using setValue(); Instead of setting the html code through .text(html);


Thanks

**Comment by hsm-gowtham** [comment]
Hi There, Another issue I'm having.

I'm trying to switch between themes dynamically through jquery.
I was able to change the themes.
however, I'm unable to find default theme. I want to give default theme option. But in themes there is no default option

Kindly help me in this regards.

Thanks

**Comment by marijnh** [comment]
`.setOption("theme", "default")` should do it.
