### ISSUE TITLE
Typescript Template Literal can break the javascript mode

### ISSUE THREAD

**Issue by dperetti** [codemirror/CodeMirror#6786]
A [template literal](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) edge case in Typescript that breaks the javascript mode:

```ts
export type State = {
  works `category-${NoteCategory}`;
  breaks: `category-${NonNullable<NoteCategory>}`;
  blah: number;
  foo: string
};
```
<img width="420" alt="image" src="https://user-images.githubusercontent.com/845612/134968239-9dd9fe40-df3d-45dc-8a57-a922e4d3e8a2.png">

**Comment by marijnh** [comment]
Are you enabling the TypeScript mode, or doing this in the plain JavaScript mode? Because `type` and `State` should already be highlighted in TypeScript, and they aren't in your screenshot.

**Comment by dperetti** [comment]
Correct, for the purpose of the screenshot I used the wrong page at codemirror.net.
Here is the right screenshot from https://codemirror.net/mode/javascript/typescript.html
<img width="452" alt="image" src="https://user-images.githubusercontent.com/845612/135039353-26c7687b-7835-43dc-937e-1b4c3ccb1c70.png">

**Comment by marijnh** [comment]
Now you're using the JSX mode, for some reason. [This page](http://cm/mode/javascript/typescript.html) has the TypeScript mode enabled.
