### ISSUE TITLE
Cannot read properties of undefined (reading 'theme')

### ISSUE THREAD

**Issue by JQzhong-Fruen** [codemirror/CodeMirror#6787]
TypeError: Cannot read properties of undefined (reading 'theme')   at /cjs/theme/light.js

![image](https://user-images.githubusercontent.com/74750580/135203783-c9395427-bbb7-403c-b55a-d25d59160b8b.png)

**Comment by marijnh** [comment]
react-codemirror is a different package. Maybe try reporting this there.
