### ISSUE TITLE
#codemirror.js# artefact after installing CodeMirror

### ISSUE THREAD

**Issue by forgie1** [codemirror/CodeMirror#6797]
In version 5.63.1 after `bower install --force` there is one strange file: `/bower/codemirror/lib/#codemirror.js#`.

In version 5.63.0. and before there was no this kind of artefact file.

This file causes trouble during the deploy :( is it inevitable to be there, or could you prevent this file to be created?

**Comment by marijnh** [comment]
That's an accident (an emacs auto-save file that happened to be in the tree while I published). I've released 5.63.2 without it.
