### ISSUE TITLE
Set onClick event to LineNumbers 

### ISSUE THREAD

**Issue by Muhammad-Tahir-S** [codemirror/CodeMirror#6811]
Browser version: Google Chrome Version 94.0.4606.8
Operating system: macOS Big Sur v 11.5.2
Codemirror version: v 5.63.3

Issue: unable to set onClick event to lineNumbers. 

Having gone through the docs, I was wondering if there might be a workaround to help me achieve this. Any help is appreciated.

**Comment by marijnh** [comment]
Use the [`gutterClick`](https://codemirror.net/doc/manual.html#event_gutterClick) event for this. And next time, please use the [forum](https://discuss.codemirror.net), not the bug tracker, for questions.

**Comment by Muhammad-Tahir-S** [comment]
> Use the [`gutterClick`](https://codemirror.net/doc/manual.html#event_gutterClick) event for this. And next time, please use the [forum](https://discuss.codemirror.net), not the bug tracker, for questions.

Thank you very much. And understood.
