### ISSUE TITLE
About block comment

### ISSUE THREAD

**Issue by canmeng** [codemirror/CodeMirror#6813]
I'll annotate an SQL code
![image](https://user-images.githubusercontent.com/15072609/140019027-606f85b2-2f5a-40b6-9ae6-ad9c5287b17e.png)
This is what I want
But I get
![image](https://user-images.githubusercontent.com/15072609/140019101-8932dddc-4937-4fc0-b4d8-4dfee5697158.png)
What shall I do?
Thank you for your help!

**Comment by marijnh** [comment]
SQL supports nested block comments, so the behavior in the second screenshot seems correct, no?

**Comment by canmeng** [comment]
![企业微信截图_16359232694992](https://user-images.githubusercontent.com/15072609/140020780-c077cb1a-d0d1-47ce-a9cc-f47c9e887825.png)
But at Navicat,I get this

**Comment by marijnh** [comment]
I guess that other tool doesn't parse nested comments, then.
