### ISSUE TITLE
A syntax error occurs in SQL formatting

### ISSUE THREAD

**Issue by xingorg1** [codemirror/CodeMirror#6815]
When sql code has "!= "operator, formatting code gets wrong syntax formatting"! = ". There is an extra space between the  "!" symbol and the "=" symbol

for example：
```sql
SELECT
  *
FROM
  tableName
WHERE
  dt = '2021-11-09'
  AND some != '111'
```
i‘ll get it
```sql
SELECT
  *
FROM
  tableName
WHERE
  dt = '2021-11-09'
  AND some ! = '111'
```
browser：Chrome@latest

**Comment by marijnh** [comment]
This library doesn't do code formatting, so it doesn't seem like it could be responsible for this.

**Comment by xingorg1** [comment]
> This library doesn't do code formatting, so it doesn't seem like it could be responsible for this.

Yes, I just found it. Thank you for your reply.
