### ISSUE TITLE
Scroll position not updated when editor size change

### ISSUE THREAD

**Issue by lishid** [codemirror/CodeMirror#6819]
## Steps to repro

- Go to https://codemirror.net/
- Run console code `editor.setValue(new Array(100).fill('test').join('\n'));`
- Scroll editor down.
- Run console code `editor.setValue('test');`
- Run console code `editor.setValue(new Array(100).fill('test').join('\n'));`

## Expected results
Editor fully scrolled to the top

## Observed results
Scroll bar shows editor scrolled to the bottom, while text seems to be scrolled to the top.

## Notes
Could be a recent regression

## Screencap

![test](https://user-images.githubusercontent.com/609710/140960015-27185c31-7345-4779-b2c6-54bc440cea68.gif)

**Comment by marijnh** [comment]
This doesn't happen on Firefox. Seems Chrome somehow 'smartly' restores the scrollbar position here, which isn't a good idea. Attached patch should fix it.
