### ISSUE TITLE
kill and yank on Mac OS 

### ISSUE THREAD

**Issue by midas0441** [codemirror/CodeMirror#6820]
"In the MacOS and many linux system, the following hotkey is defined: Ctrl+k is “kill-to-end-of-line”, but what is killed goes into a buffer that you can later yank back out with Ctrl+y." ([Source](https://forum.obsidian.md/t/a-misalignment-on-the-support-of-the-kill-and-yank/6560?u=midas0441))

While CTRL-k works to kill, CTRL-y doesn't yank back the text.

The issue is discussed further at the [source](https://forum.obsidian.md/t/a-misalignment-on-the-support-of-the-kill-and-yank/6560?u=midas0441) cited above.

**Comment by WhiteNoiseDev** [comment]
This issue can be closed since I can see now that yank (as well as other commands) has been implemented in the external `emacs.js` keymap.
