### ISSUE TITLE
Scheme mode issue with escaped symbols

### ISSUE THREAD

**Issue by jcubic** [codemirror/CodeMirror#6822]
I found an issue in Scheme mode. GitHub has more issues than CodeMirror that only don't handle escaped symbols in the form: `|foo bar|`.

Here is my nasty example:

```
(let ((x #;(foo
             bar ")") 10)
      (|foo )))) bar| 20))
   (print #|
            this is comment ))))
          |# x)
   (print (+ x |foo )))) bar|)))
```
Here `|foo )))) bar|` is a valid symbol but it's not processed as a single token.

I can try to fix the issue and create a PR since I use a modified version that I also need to fix.

Here is a demo with matching parentheses that use my modified version of the mode (I have extensions on top of Scheme that I want to support) https://codepen.io/jcubic/pen/VwKeZob?editors=1010

**Comment by marijnh** [comment]
A PR would be wonderful!
