### ISSUE TITLE
Highlight roxygen comments in R code

### ISSUE THREAD

**Issue by wurli** [codemirror/CodeMirror#6830]
When writing R code it would be great to have {roxygen2} comments highlighted similarly to how it's done in RStudio. This isn't part of the official R syntax, but as most R users, and particularly package developers, now use roxygen and RStudio, I think it would be a solid improvement if it was included in CodeMirror. Here's an example:

Using CodeMirror (via Carbon):
![highlighting-cobalt](https://user-images.githubusercontent.com/17475731/143200600-f3fdaaf1-f2d8-4d7e-b746-1304601cbeb9.png)

Using RStudio:
![highlighting-rstudio](https://user-images.githubusercontent.com/17475731/143200629-57479976-c23e-403f-bf01-e5ef49b61b12.png)

Thanks!

**Comment by marijnh** [comment]
This isn't something I'm going to work on, but a pull request that adds it would be welcome.
