### ISSUE TITLE
watch value not work properly

### ISSUE THREAD

**Issue by zhamdoctor** [codemirror/CodeMirror#6843]
when i change the value on yaml-editor,watch doesnt always work unless i change my code to trigger recompiling.however, when i refresh the network. watch doesnt work again! also codemirror reported some errors like string is not a function.it obviesly shows that my struct is not proper.it contains some number.not all string.i just want to know why value only work when i change my code to trigger recompiling

**Comment by zhamdoctor** [comment]
code like this :https://github.com/zhamdoctor/test

**Comment by zhamdoctor** [comment]
two examples .comment aa was the problem.comment bb was my partner which works well

**Comment by marijnh** [comment]
I don't know what yaml-editor is, but compiling is entirely outside of the scope of this library. This issue report does not contain enough information for us to do anything with it.

**Comment by zhamdoctor** [comment]
https://github.com/zhamdoctor/test&nbsp; &nbsp; ,this is my test code,code with comment aa was mine,bb was my colleges.comment aa when i changed textarea value,watch didnt work well with&nbsp; what i had changed.when i used console.log(this.value),the value was older than i had ***@***.*** didnt listen anything .if only i change sth in yaml-editor triggering recompiling,watch workes fine pushing newest textarea value.but when i refresh the website and reopen the editor.watch doesnt work again




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marijn ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codemirror/CodeMirror] watch value not work properly (Issue #6843)





 
I don't know what yaml-editor is, but compiling is entirely outside of the scope of this library. This issue report does not contain enough information for us to do anything with it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
