### ISSUE TITLE
Incompatible types between @codemirror/language and @codemirror/view

### ISSUE THREAD

**Issue by winniederidder** [codemirror/CodeMirror#6846]
My project is no longer able to build due to an inconsistency in dependencies. My main guess is that the most recent push to @codemirror/view (which occurred around a day ago, coinciding with when my builds started failing), caused a discrepancy.  Removing node_modules and reinstalling allowed me to reproduce the issue locally, with the following error:
```
Argument of type 'KeyBinding[]' is not assignable to parameter of type 'readonly KeyBinding[]'.
  Type 'import("/node_modules/@codemirror/language/node_modules/@codemirror/view/dist/index").KeyBinding' is not assignable to type 'import("/node_modules/@codemirror/view/dist/index").KeyBinding'.
    Types of property 'run' are incompatible.
      Type 'import("/node_modules/@codemirror/language/node_modules/@codemirror/view/dist/index").Command' is not assignable to type 'import("/node_modules/@codemirror/view/dist/index").Command'.
        Types of parameters 'target' and 'target' are incompatible.
          Type 'import("/node_modules/@codemirror/view/dist/index").EditorView' is not assignable to type 'import("/node_modules/@codemirror/language/node_modules/@codemirror/view/dist/index").EditorView'.
            Types have separate declarations of a private property '_dispatch'.ts(2345)
```
A minimally reproducing sample is obtained by trying to use the following extensions in the editor:
```javascript
        keymap.of([
            ...closeBracketsKeymap,
            ...defaultKeymap
        ]),
``` 
with the following package.json:
```
    "@codemirror/autocomplete": "^0.19.8",
    "@codemirror/closebrackets": "^0.19.0",
    "@codemirror/commands": "^0.19.5",
    "@codemirror/comment": "^0.19.0",
    "@codemirror/fold": "^0.19.1",
    "@codemirror/history": "^0.19.0",
    "@codemirror/lang-javascript": "^0.19.3",
    "@codemirror/lang-python": "^0.19.2",
    "@codemirror/rectangular-selection": "^0.19.1",
    "@codemirror/search": "^0.19.3",
    "@codemirror/state": "^0.19.6",
    "@codemirror/view": "^0.19.29",
```

Any suggestions on how to fix this are appreciated, as perhaps I am overlooking something?
I've tried updating my dependencies to the latest version, but the errors persist.

**Comment by marijnh** [comment]
I'm not seeing this. Installing those dependencies plus typescript, and running `tsc` on a file containing that `keymap` use gives me zero type errors.

**Comment by winniederidder** [comment]
After some further inspection, the issue seemed to be an inconsistency in my yarn.lock-file, which was causing the type inconsistency. Thank you for your swift response and my apologies for the inconvenience. The issue has been resolved.
