### ISSUE TITLE
bug: "fold" "brace" helper in brace-fold.js does not detect folding due to wrong order of brackets on the same line

### ISSUE THREAD

**Issue by SwatDoge** [codemirror/CodeMirror#6847]
## What is the issue?
The little folding gutter that codemirror offers, will not work on this code: 
```cpp
public action test(num[] number){

}
```
If I remove the square bracket it works again. It seems that having either brackets on the same line breaks the code.

## Where is the issue?
https://github.com/codemirror/CodeMirror/blob/master/addon/fold/brace-fold.js in "fold", "brace" helper.

## Explanation of the bug
1. The brace helper will first look for "{" on line 34. In the findOpening function, a variable `tokenType` gets assigned the "{" character outside of the functions scope.
2. On line 34, another findOpening will run for "[", which once again overrides `tokenType` to be "[" this time.
3. Outside of those scopes, a for loop runs, searching for the closing bracket, being the closing bracket for [. It finds "]" 1 character later and because there is no indent, no folding icon is shown.

### [A quick example video](https://youtu.be/2PfzaKN66e4)

**Comment by marijnh** [comment]
Attached patch should fix this.
