### ISSUE TITLE
Can't toggle line comment when line starts with keyword specified in `parserConfig.client`

### ISSUE THREAD

**Issue by sfc-gh-niaconis** [codemirror/CodeMirror#6852]
## Expected Behavior

It should be possible to toggle line comments for lines starting with a keyword specified in either of `parserConfig.keywords` or `parserConfig.client`.

## Actual Behavior

It is not possible to toggle line comments for lines starting with a keyword specified in `parserConfig.client`.

## Analysis

This appears to happen because [the function `probablyInsideString`](https://github.com/codemirror/CodeMirror/blob/d60fff6750cd4963ebfd83d446d5bd3ad6b083a3/addon/comment/comment.js#L47-L50) returns true for tokens of type `string-2`, even though multi-line strings have a token type of `string` in practice.

## Demo

https://jsfiddle.net/niaconis/npue9ys5/51/

## Recommendation

To fix this, `probablyInsideString` should be updated to return false for tokens of type `string-2`.

## CodeMirror Version

We are using version 5.58.2, but this also happens in the latest version, which is 5.65.0 at time of writing. (The above demo uses the latest version.)

**Comment by marijnh** [comment]
Treating string-2 as string seems reasonable -- many language modes do use it for string-like content. The way the sql mode is using it for client-side commands is not terribly reasonable. Attached patch changes that.

**Comment by sfc-gh-niaconis** [comment]
That should work for us too. Thanks for the quick turn around! Looking forward to when this lands in the release.
