### ISSUE TITLE
[Safari] Interrupted momentum scrolls cause a scroll jump

### ISSUE THREAD

**Issue by smfr** [codemirror/CodeMirror#6858]
WebKit engineer here. With any CodeMirror example that allows for a reasonable amount of scrolling (e.g. https://codemirror.net/demo/search.html), do a trackpad momentum scrolling Safari, and interrupt the scroll by tapping two fingers on the trackpad.

This often triggers a scroll position jump in CodeMirror, if the scroll had any non-zero dx (which is common).

This happens because of this code:

```
    // On some browsers, horizontal scrolling will cause redraws to
    // happen before the gutter has been realigned, causing it to
    // wriggle around in a most unseemly way. When we have an
    // estimated pixels/delta value, we just handle horizontal
    // scrolling entirely here. It'll be slightly off from native, but
    // better than glitching out.
    if (dx && !gecko && !presto && pixelsPerUnit != null) {
      if (dy && canScrollY)
        { updateScrollTop(cm, Math.max(0, scroll.scrollTop + dy * pixelsPerUnit)); }
```

When scrolling down, `dy` is negative, so this applies a negative offset to the current `scrollTop` which triggers an upward jump.

Commenting out this code and testing Safari gives better behavior than with the code left in.

**Comment by smfr** [comment]
In general, WebKit has a lot of issues with CodeMirror's custom wheel event handling. I'd be curious about whether the `onScrollWheel` code is a net benefit at all, now.

**Comment by marijnh** [comment]
> When scrolling down, dy is negative

`dy` should be positive when scrolling down. What are the `deltaMode`, `deltaX`, and `deltaY` values of the event when this happens, and do they make sense?

**Comment by smfr** [comment]
You're right, `dy` is positive (I was confused by the mess that is the wheel event fields). I think this is actually a WebKit bug: when you interrupt a momentum scroll, we receive a "cancelled" event from the OS which may have a non-zero `deltaX` and negative `deltaY`, which we dispatch like other wheel events. However, phases aren't exposed to JS to there's no way for you to tell that this is a gesture cancel.

**Comment by marijnh** [comment]
Right. So do you agree it'd make more sense to fix this in Webkit?

**Comment by smfr** [comment]
I'll fix it and see what the behavior is like with the fix.

**Comment by smfr** [comment]
This turned out to be a WebKit (actually an OS) bug. Still, it would be nice if CodeMirror could stop listening for wheel events.

**Comment by marijnh** [comment]
CodeMirror 6 doesn't listen for wheel events, but the [baroque virtual scroll magic](https://marijnhaverbeke.nl/blog/a-pathological-scrolling-model.html) in this version depends on it, and it's unlikely that that is going to be redone at this point.
