### ISSUE TITLE
Optimize CSS z-ordering

### ISSUE THREAD

**Issue by smfr** [codemirror/CodeMirror#6859]
WebKit engineer here. CodeMirror tiggers some really inefficient code paths in browser engines related to z-ordering and CSS stacking context, which causes every line in the scrolled content to get multiple composed layers (i.e. GPU textures) in some cases. For example, here's a JSFiddle, snapshotted with Safari Web Inspector's "layer borders" turned on:

<img width="973" alt="Screen Shot 2021-12-31 at 12 29 56 PM" src="https://user-images.githubusercontent.com/20968/147838341-c9b0a3a8-0a99-4768-bc8f-1c183707fde4.png">

Here's the same content with `<div class="CodeMirror-scroll" tabindex="-1">` made a CSS stacking context by adding `z-index: 0` style:

<img width="978" alt="Screen Shot 2021-12-31 at 12 30 03 PM" src="https://user-images.githubusercontent.com/20968/147838357-b3620cc9-c78e-4a05-b732-ee9591d3b750.png">

What's happening here is that in its shipping config, CodeMirror is creating an `overflow:scroll` element which is not a CSS stacking context. Browsers optimize scrolling by promoting overflow:scroll to compositing layers, but in so doing, must also promote other elements which are higher in paint order to compositing layers. Because of the details of how the CSS painting model works and how browsers implement compositing, this can trigger every `position:relative` descendant to also get composited, which causes additional memory use and computation.

There's a really simple fix; make the `CodeMirror-scroll` element a CSS stacking context. You could use `z-index: 0` or `will-change: z-index`.

**Comment by marijnh** [comment]
I can't find a case where this breaks reasonable setups, so sure, added the z-index in attached patch.

**Comment by schanzer** [comment]
@smfr awesome report - and thanks for all your hard work on WebKit! would love to know how much of a performance gain you're seeing from the patch.

**Comment by smfr** [comment]
This will approximately halve layer-related memory use for the CodeMirror in WebKit browsers. I don't have data on the runtime benefits, but would expect them to be noticeable for larger content.
