### ISSUE TITLE
JS-File does not exist

### ISSUE THREAD

**Issue by chrishucke** [codemirror/CodeMirror#6860]
Where: CodeMirror/test/index.html 
What: <script src="../lib/codemirror.js">
Problem: File does not exist in 5.65.0

**Comment by marijnh** [comment]
Do you mean lib/codemirror.js is not in the repository? That file is created by building the library, or you can download the package from npm or the website to get it.

**Comment by chrishucke** [comment]
Thanks for solving my problem. I was updating old software and I was worried that the file was missing.
