### ISSUE TITLE
Wrong cursor position when adding line widget above the first line and code folding

### ISSUE THREAD

**Issue by 11bit** [codemirror/CodeMirror#6862]
I want to add a line widget above the first line of my json content but when json is folded cursor appears on a widget instead of the line:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/4057095/148357071-83f8a8ea-0fe5-4e7b-98d8-69641f1ce1f2.png">

**Example codesandbox**
https://codesandbox.io/s/sharp-raman-glxbh?file=/src/index.js

**Steps to reproduce**
1. Add a json with folding
2. Add line widget above the first line
3. Fold the first line
4. Click on the first line to put a cursor in there - cusor will have wrong vertical positioning 

BTW are there other ways to add some UI on top of the code inside scrollable container so it will be scrolled together with the code? Thanks!

**Comment by marijnh** [comment]
Attached patch should address this.

**Comment by 11bit** [comment]
Great. Thank you very much!
