### ISSUE TITLE
Feature Request: brace-fold plugin should also fold parenthesis

### ISSUE THREAD

**Issue by LeifAndersen** [codemirror/CodeMirror#6868]
Right now the brace fold plugin folds both braces and brackets. Some languages also use large parenthesized blocks, and it would be nice to be able to fold them. As with this website:

https://visr.pl
![Screenshot from 2022-01-09 23-30-04](https://user-images.githubusercontent.com/285926/149817704-3a376628-935f-456a-9d6e-b73734096352.png)

Currently I have a patch that does this, but i would make sense to have this be a default feature for the brace-fold plugin.

https://github.com/LeifAndersen/interactive-syntax-clojure/blob/main/patches/codemirror%2B5.63.3.patch

**Comment by marijnh** [comment]
Attached patch should do this without making backwards-incompatible changes to the existing `"brace"` helper.
