### ISSUE TITLE
Fortran mode: Incorrect highlighting for certain operators

### ISSUE THREAD

**Issue by dcshzj** [codemirror/CodeMirror#6869]
In Fortran mode, some of the operators are incorrectly highlighted, such as the "len" and "new_line" functions. These functions begin with "le" and "ne" respectively, which is an operator in Fortran. The incorrect syntax highlighting is shown in the following screenshot (originally reported at https://github.com/highlightjs/highlight.js/issues/3450):

![image](https://user-images.githubusercontent.com/38887928/147980136-1f7bf7a5-701e-4040-83fb-9340a65ec480.jpeg)

**Comment by marijnh** [comment]
Does attached patch do what you were looking for?

**Comment by dcshzj** [comment]
I'm not knowledgeable on Fortran, so I am unable to verify it, sorry.
