### ISSUE TITLE
nomnom  pulls in underscore 1.6 which has security issue of high severity

### ISSUE THREAD

**Issue by mennucc** [codemirror/CodeMirror#6871]
dear all,

CodeMirror uses `nomnom` , that depends on `underscore` version 1.6, but that version has a security issue of Severity: high
*Arbitrary Code Execution in underscore*  see  https://github.com/advisories/GHSA-cf4h-3jhx-xvhq

Is there 

TIA

a.

**Comment by marijnh** [comment]
These are dev dependencies, and as such shouldn't concern you. But a PR that upgraded/replaces them would be welcome.

**Comment by mennucc** [comment]
I have patched `nomnom` as follows

```
diff --git a/package.json b/package.json
index 6556f58..721ca0f 100644
--- a/package.json
+++ b/package.json
@@ -19,7 +19,7 @@
     "parser"
   ],
   "dependencies": {
-    "underscore": "~1.6.0",
+    "underscore": "~1.12.1",
     "chalk": "~0.4.0"
   },
   "devDependencies": {
```

and the patched CodeMirror as follows

```
diff --git a/package.json b/package.json
index 1794a38..18c29f1 100644
--- a/package.json
+++ b/package.json
@@ -43,5 +43,8 @@
     "dependencies": {},
     "devDependencies": {}
   },
-  "dependencies": {}
+  "dependencies": {
+    "nomnom": "^1.8.1",
+    "underscore": "^1.13.2"
+  }
 }
```
and I have reinstalled both, and it seems to be working fine

a.
