### ISSUE TITLE
Using the mode : 'application/x-cypher-query' to print a new a line it is drawing multiple spaces at the beginning of the new line

### ISSUE THREAD

**Issue by oOBlinkOo** [codemirror/CodeMirror#6872]
Hello im using codemirror i have this configuration

```codeMirrorOptions: any = {
    mode: 'application/x-cypher-query',
    lineNumbers: true,
    lineWrapping: true,
    foldGutter: true,
    gutters: [
      'CodeMirror-linenumbers',
      'CodeMirror-foldgutter',
      'CodeMirror-lint-markers',
    ],
    autoCloseBrackets: true,
    matchBrackets: true,
    lint: true
   ```
    

this is how my application load at the beginning.
    
![image](https://user-images.githubusercontent.com/5222538/151270303-532c0db2-8cd8-4176-9b6b-c2ed8c8e36ca.png)

then if the user enter a new line happen this:

![image](https://user-images.githubusercontent.com/5222538/151270399-ceff5ef8-4d16-4c2e-86be-36a390a812a6.png)

it is creating multiple " " chars in the new line.

if i change the mode it is not doing that anymore. i think it is only happening on cypher.

**Comment by marijnh** [comment]
Can you provide that document as plain text, rather than a screenshot, so that I can replicate this without typing it all in?

**Comment by oOBlinkOo** [comment]
https://codemirror.net/mode/cypher/index.html
it is happening also in the demo.
if you enter a new line.

it is the same query as the demo.
```// Cypher Mode for CodeMirror, using the neo theme
MATCH (joe { name: 'Joe' })-[:knows*2..2]-(friend_of_friend)
WHERE NOT (joe)-[:knows]-(friend_of_friend)
RETURN friend_of_friend.name, COUNT(*)
ORDER BY COUNT(*) DESC , friend_of_friend.name```

**Comment by marijnh** [comment]
Ah, I see. Attached patch seems to help.
