### ISSUE TITLE
newlineAndIndentContinueMarkdownList doesn't work in markdown demo

### ISSUE THREAD

**Issue by Geist-zz** [codemirror/CodeMirror#6877]
newlineAndIndentContinueMarkdownList (addon/edit/continuelist.js) doesn't work on the [markdown demo](https://codemirror.net/mode/markdown/index.html).

If the cursor is in the list, and you press Enter, the list isn't continued. I assume, judging by the addon description, that the list character should be repeated/inserted?

**Comment by marijnh** [comment]
How are you testing this? Because it seems to work for me.

**Comment by Geist-zz** [comment]
I press Enter after the * in line (in the Lists section; ex. in * Gum. line).
On both FF and Edge only the indent is inserted (FF & Edge in Windows 7, and  Edge on Win 10).

Also if I manually type '* ' (star and space) and press Enter (to make an empty list), the '* ' line will be deleted.

After some tests: it seems that, if there are more than 4 spaces before the * (list on demo page has 5), the completion stops working, because the 4th space is changed to code 42 (`line.charCodeAt(4)`; tabulation perhaps?) for some reason.

**Comment by marijnh** [comment]
Those are code blocks (indented four spaces). I guess the example text is from some reference that shows how markdown syntax works. But in a properly indented list, this works.
