### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by AwesomeWithRex** [codemirror/CodeMirror#6879]
I did npm install codemirror and then I did npm run codemirror and it says this:
npm ERR! Missing script: "codemirror"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AWR_G\AppData\Local\npm-cache\_logs\2022-02-10T20_23_05_068Z-debug-0.log

Does anyone know how to fix?

**Comment by marijnh** [comment]
There is no `npm run codemirror`. This is a library, not a tool (and note that even with tools, `npm run toolname` isn't how you run stuff you install with npm.)

**Comment by AwesomeWithRex** [comment]
Then how do I use this>
