### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by wowet** [codemirror/CodeMirror#6887]

**Comment by marijnh** [comment]
How is this related to CodeMirror?

**Comment by Javikirito** [comment]
did the CodeMirror tpyeerror solved ? @marijnh

**Comment by Javikirito** [comment]
if so, how? can please provide the solution.

**Comment by Marium-dotcom** [comment]
I had the error and removed blackbox extension and it did work

**Comment by EthanHDT** [comment]
> I had the error and removed blackbox extension and it did work
Tysm, I was using Draw.io when this problem happened

**Comment by alexferreras** [comment]
Removing Blackbox extension also works for me too. thanks @Marium-dotcom
