### ISSUE TITLE
Cursor interference problem

### ISSUE THREAD

**Issue by liushuai05** [codemirror/CodeMirror#6891]
When I open CodeMirror, enter sql statement, and the table name is halfway through, then click other input boxes to get focus and enter text. CodeMirror prompt also appears.
![1646280096048](https://user-images.githubusercontent.com/26994692/156495012-4a60f163-4652-41f3-b7c4-9d4ab76bcbfb.png)

The above content comes from sogou Translate.

**Comment by marijnh** [comment]
This report does not, at the moment, contain enough information for us to do much with.

**Comment by liushuai05** [comment]
> This report does not, at the moment, contain enough information for us to do much with.

I made a very simple demo that I hope will be useful to you. Plus a video I recorded.

https://user-images.githubusercontent.com/26994692/157649291-e3e8b129-febf-4fc3-ad76-6d8789580f7c.mp4

[vue_code_test.zip](https://github.com/codemirror/CodeMirror/files/8222786/vue_code_test.zip)

**Comment by marijnh** [comment]
You've got a `document.onkeyup` handler that calls `editor.showHint()`. Please don't waste my time like this.

**Comment by liushuai05** [comment]
> You've got a `document.onkeyup` handler that calls `editor.showHint()`. Please don't waste my time like this.

Oh, thank you very much for your patience. I really made a stupid mistake.
