### ISSUE TITLE
CDNJS does not contain map files anymore since 5.54.0

### ISSUE THREAD

**Issue by drauch** [codemirror/CodeMirror#6892]
Why does the CDNJS package no longer contain map files since 5.54.0? Are there anywhere else? Is this a bug?

Best regards,
D.R.

**Comment by marijnh** [comment]
What do you mean by 'map files'?

**Comment by drauch** [comment]
The corresponding map files to the minified JS files, so I can use minified files and still debug the JavaScript code.

Our package manager libman says they're now missing.

**Comment by marijnh** [comment]
This library never shipped minified JS files or source maps, so this is probably not the place to solve your issue.

**Comment by drauch** [comment]
So, you're not responsible for the cdnjs package of your library? Do you know who is?
