### ISSUE TITLE
How to keep hint？not need extraKeys

### ISSUE THREAD

**Issue by zhoufanglu** [codemirror/CodeMirror#6897]
* options
```js
const cmOptions = {
  mode: "sql", // 语言模式
  //mode: "text/javascript", // 语言模式
  theme: "cobalt", // 主题
  lineNumbers: true, // 显示行号
  smartIndent: true, // 智能缩进
  indentUnit: 2, // 智能缩进单位为4个空格长度
  foldGutter: true, // 启用行槽中的代码折叠
  styleActiveLine: true, // 显示选中行的样式
  extraKeys: {
    // 触发按键
    // Ctrl: "autocomplete",
  }
};
```

i don't want use extraKeys, i want to auto trigger, can realize?

**Comment by marijnh** [comment]
Run something like this in an `inputRead` handler:

```javascript
setTimeout(function() {
  if (!cm.state.completionActive) cm.showHint({completeSingle: false})
}, 100)
```

Please, in the future, use the [forum](https://discuss.codemirror.net), not the bug tracker, for questions.

**Comment by zhoufanglu** [comment]
> Run something like this in an `inputRead` handler:
> 
> ```js
> setTimeout(function() {
>   if (!cm.state.completionActive) cm.showHint({completeSingle: false})
> }, 100)
> ```
> 
> Please, in the future, use the [forum](https://discuss.codemirror.net), not the bug tracker, for questions.

Thank you for your answer, i knowed
