### ISSUE TITLE
Julia: Wrong syntax highlighting of === 

### ISSUE THREAD

**Issue by XRFXLP** [codemirror/CodeMirror#6913]
`===` is not properly tokenized, despite the fact that there is a `===` operator in julia:

![image](https://user-images.githubusercontent.com/23459568/165688098-0c26a84a-5dda-42fe-a3aa-72640882ee38.png)

(Not sure about whether the different highlighting of `=` and `==` is intended or is it a bug, but I cannot find any other alternative(I've tried VSCode and OhMyREPL) which highlights `=` and `==` differently)

Browser: Brave 1.38
OS: Manjaro KDE

**Comment by marijnh** [comment]
Attached patch should help.

**Comment by Suphonseesanong** [comment]
> #6735

**Comment by XRFXLP** [comment]
@marijnh sorry, but that's not fixed:

![image](https://user-images.githubusercontent.com/23459568/169628035-ded4206e-464c-43c7-a4d8-97c2de55a91e.png)

**Comment by marijnh** [comment]
New attempt in attached patch.
