### ISSUE TITLE
feature-request - include jslint-addon?

### ISSUE THREAD

**Issue by kaizhu256** [codemirror/CodeMirror#6914]
- www.jslint.com has been using codemirror in its homepage since 2021. 
- the internal codemirror-jslint-integration-code was recently made public-facing as an addon file ([jslint_wrapper_codemirror.js](https://github.com/jslint-org/jslint/blob/72231e1f/jslint_wrapper_codemirror.js))
- would you be interested in a PR to include the jslint-addon under `/addon/lint/jslint-lint.js` (or something similarly named)?

**Comment by marijnh** [comment]
No, I'm not expanding the set of extensions included in the main distribution anymore. But if you want to publish this to npm so people can easily install it, that'd be wonderful.

**Comment by kaizhu256** [comment]
ok, thx for input
