### ISSUE TITLE
lang-html: Long closing HTML comment tags break syntax highlighting

### ISSUE THREAD

**Issue by chriscalo** [codemirror/CodeMirror#6917]
A closing HTML comment tag is two dashes and greater than symbol:

`-->`

You should be able to put anything you want in front of these, including more dashes:

`------------>`
`----------------------->`
`------------------------------------------->`

In long HTML files, I use these long comment blocks like the one below as visual anchors to more quickly find key parts of the document I'm working on.

``` html
<!------------------------------------------------------------------------------
Block comment
------------------------------------------------------------------------------->
```

Unfortunately, they break Codemirror HTML syntax if they're long enough (79 characters)

The following HTML document demonstrates the specific breaking point:

```html
<!DOCTYPE html>
<!----------------------------------------------------------------------------
This stylized HTML comment is used to divide long documents into
easily-findable sections. 
The following closing comment tag is 78 characters: 77 dashes and a greater
than symbol. This should be recognized by Codemirror as a closing comment tag,
and all following syntax highlighting should work correctly.
----------------------------------------------------------------------------->
<div>syntax highlighting after the first comment works</div>
<!-----------------------------------------------------------------------------
However, this stylized HTML comment is slightly longer: 79 characters. By
adding just one more dash to the closing comment tag, Codemirror no longer
recognizes this closing tag, breaking all following syntax highlighting.
------------------------------------------------------------------------------>
<div>Codemirror still thinks this is inside the HTML comment</div>
```

See the screenshot below:

![Screenshot 2022-05-15 at 23 25 26](https://user-images.githubusercontent.com/867717/168514814-d96e26ba-a6d8-4ecf-83bb-c1ecdf3c6e8a.png)

A full reproduction is at https://github.com/chriscalo/codemirror6-html-bug, but it should be pretty easy to reproduce in any CodeMirror instance by pasting in the HTML snippet above.

**Comment by marijnh** [comment]
That was a bug in the HTML tokenizer. Attached patch should help.

**Comment by chriscalo** [comment]
thanks for the quick fix! 🙏🏼
