### ISSUE TITLE
Request switch to unprefixed webkit properties

### ISSUE THREAD

**Issue by brentfulgham** [codemirror/CodeMirror#6921]
I noticed that 'codemirror.css' includes '-webkit-' prefixed CSS properties that we now support without prefixes.

Would you consider removing these deprecated CSS properties:

-webkit-animation: blink 1.06s steps(1) infinite;
-webkit-user-select: none;

Current WebKit will correctly handle the unprefixed CSS you already provide.

**Comment by nt1m** [comment]
I'd recommend keeping `-webkit-user-select` for now to not break websites using CodeMirror (since only experimental versions have it unprefixed), but yeah, `-webkit-animation` can be removed.

**Comment by marijnh** [comment]
No, these are staying -- they do no harm, and make sure things continue to work on old browsers.
