### ISSUE TITLE
CodeMirror support Clickhouse sql mode

### ISSUE THREAD

**Issue by Dennayz** [codemirror/CodeMirror#6922]
Hi, I was wondering if code mirror will ever have a mode for the database Clickhouse syntax highlighting or is there a way to do it with codemirror now? Thanks!

**Comment by marijnh** [comment]
I don't know anything about this language, but no, CodeMirror will not support it out of the box, so if you want support, you'll have to figure out how to write it yourself (possibly using mode/sql/sql.js as a basis).
