### ISSUE TITLE
[Bug] Scrolling pauses on Chrome 102

### ISSUE THREAD

**Issue by mustafamunawar** [codemirror/CodeMirror#6923]
**Info**: When using  the mouse wheel to scrolls, there are pauses every few scroll units. Makes scrolling unusable.

**Reproduce**:  Go to the CodeMirror demo site (https://codemirror.net/index.html) and add large enough text. Now, try scrolling with the mouse wheel. The bug should manifest.

**Fix**: The fix seems simple: set pointer-events "none" on CodeMirror-sizer. How did I figure this out? I guessed that Chrome was not able to target the parent "CodeMirror-scroll", thus causing scroll issues.

Please let me know if there is a better, less-hackish fix than this.

**Comment by krystian3w** [comment]
If projects no "harassing" outdated browsers so for few months possible change `>=` to `==(=)` instead revert commits.
