### ISSUE TITLE
Ruby mode if..then..else..end broken

### ISSUE THREAD

**Issue by jcubic** [codemirror/CodeMirror#6927]
I'm trying to create a mode for my language based on ruby-mode and I was not able to make it work for this syntax:

```ruby
if x == 10 then
    x
end
    |
```

which is valid ruby (then is optional but only when the body is after a newline).

But it seems that ruby-mode also has the same error, the indentation is broken (marked with pipe character) for the next line after the `end` keyword.

**Comment by marijnh** [comment]
Attached patch should help.
