### ISSUE TITLE
PEG.js mode and template literals

### ISSUE THREAD

**Issue by jcubic** [codemirror/CodeMirror#6929]
Found in peggyjs/peggy#249 that the problem with my code is in PEG.js mode and its handling of JS code which looks like this:

```javascript
const error = new Error(`invalid function name, '${fn_name}' is a command`);
```

it seems that PEG.js mode or JS mode doesn't support template literals at all.

**Comment by marijnh** [comment]
The pegjs mode was contributed and is not being actively maintained. A pull request to improve it is welcome, but I'm not investigating issues like this. I can ensure you that the JavaScript mode handles template literals.

**Comment by jcubic** [comment]
I will try to investigate why the PEG.js mode is not working, maybe I will find the issue. If so I will create a PR.
