### ISSUE TITLE
addon/tern functions like jumpToDef do not work for tcl language

### ISSUE THREAD

**Issue by Raghad-Mufeed** [codemirror/CodeMirror#6930]
I am using codeMirror for tcl script, and one of the features that I need to add them to my script is navigation (Jump to Function), I read from the documentation that I can use JumpToDef function from addon/tern file to do that, but it didn't work for me. I got "Could not find a definition ." message, always. Please any help how to use it in a right way? and if there is any special configuration that I need to add to make it work?

**Comment by marijnh** [comment]
Tern is JavaScript tooling. It does not work for other languages (and no similar feature is available for tcl).
