### ISSUE TITLE
Splitting CodeMirror into specific files

### ISSUE THREAD

**Issue by ugin** [codemirror/CodeMirror#747]
Could we make an effort to split CodeMirror's source intro specific files?

I've noticed the branch v3, and maybe there we can split it like ace's source, I can put the effort to fork and rewrite the code, if we can agree on how to split it and choose a code style guide. (also I could add grunt.js for build, min, etc)

Thoughts?

**Comment by marijnh** [comment]
Reopening this. Two things have changed since my original decision: 1) CodeMirror's core is bigger, and 2) JS module loaders have gotten better and more widely used. If I can get the work funded, I want to move CodeMirror version 6 (maybe 7) to a collection of ES6 modules, loaded into the demos with a client-side loader shim, and packaged up into single files for distribution with a static build script (browserify or some equivalent).

**Comment by TEugen** [comment]
@marijnh :heart:

I would like to help if you could share what's on your mind and how to split it.

**Comment by marijnh** [comment]
I am considering splitting a few pieces out into NPM modules, but mostly they'll be files inside the project. (There is something to be said for having each mode and addon be an NPM module, but I fear the awkwardness of managing 100+ modules.)

**Comment by janl** [comment]
@marijnh what are you afraid of in particular?

At Hoodie, we built a few things that help with this. Most notably:

- Ubersicht: a cross-org “what is going on” tool with lots of filtering options: http://espy.github.io/ubersicht/#hoodiehq
- grunt-semantic-release: makes releasing SemVer compliant modules a snap, takes care of all the boring grunt work like tagging and pushing to npm, having the same LICENSE file etc.: https://github.com/boennemann/grunt-semantic-release / announcement here: http://hood.ie/blog/semantic-releases.html (yes grunt, this might get ported to raw npm, but that might take a while cc @boennemann)

Not saying that solves everything, but these two help us manage 50+ repos.

**Comment by marijnh** [comment]
@janl

>  what are you afraid of in particular?

The inconvenience for users, mostly. (Though the work required to create, update, and track so many modules is also, even with automation, not very attractive.) Right now, if you get the CodeMirror module, you get 90 language modes neatly lined up in a `mode` directory, and you can load the ones you need, or even defer the decision of which modes to load to run-time, and dynamically load them based on file extensions/mimes. If these are all separate NPM packages, you have to go hunt for them, figure out which ones are of good quality, and run `npm install --save` a zillion times to declare them as dependencies. The core CodeMirror package will be smaller, but I'm not sure that's really so valuable.

**Comment by janl** [comment]
Ah I see! How about a meta package that bundles everything as it is today, but is comprised of the separated modules?

**Comment by marijnh** [comment]
Still, what would be the win?

**Comment by janl** [comment]
for us it helps that they each get their own CI treatment, e.g. might not apply here tho.

**Comment by kof** [comment]
If you publish a separate small lib dedicated to one task, the chance is big someone will use it in a different project and possibly improve it to solve that task even better. If you don't make a separate repository - no one will use your modules, which are part of some bigger project. In best case they will copy paste them.

**Comment by silverwind** [comment]
@ehd Right now, [meta.js](https://github.com/silverwind/droppy/blob/ea7b9b52e4a214dc0f09f17cee95bea4fb2ffce7/server/lib/mime.js#L28-L54) for mime types and extensions. The data is used for dynamic mode loading based on the mime type served by the server on the http request. Besides that, I run all CM resources through automatic minfication on startup.

When I designed that, I wasn't aware of method like `CodeMirror.findModeByExtension` and `CodeMirror.findModeByMIME`, which most likely would've made this a lot simpler.

**Comment by kolya-ay** [comment]
@marijnh, have you considered using [rollupjs](https://github.com/rollup/rollup/wiki/jsnext:main) as module builder (might be used for PromseMirror too)? It works with ES6 modules, produces almost no boilerplate and supports cyclic deps which might be useful while refactoring.

**Comment by marijnh** [comment]
Done, 6 years later, via #4200
