### ISSUE TITLE
Allow multi-line lookahead in modes

### ISSUE THREAD

**Issue by marijnh** [codemirror/CodeMirror#839]
Since patch 846d043e9fd88afd98f8615b5df117de72242206 , the considerations that made lookahead past the current line problematic have largely been made irrelevant.

See discussion [here](https://groups.google.com/forum/#!msg/codemirror/FcpXnrGMyZQ/ZZXR8vwNNesJ)

A mode would still have to declare its maxmimum lookahead, so that the parser frontier can be backed up appropriately when the document is edited. And it does muddle up the StringStream API a bit more (i.e. the various pieces of code that run parsers, such as `runMode`, need to somehow expose the whole document to the stream), but it's probably worth it.

**Comment by superlou** [comment]
Also interested in limited look-ahead, particularly for [Fountain.io](http://fountain.io/) markup.

**Comment by marijnh** [comment]
This was finally implemented in 5.27.0 (via the `StringStream.lookahead` method)
